import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { AxisMapping, Breakpoints, CSSSelector, FlexSpacing } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class PaddingAxisInsideBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
> {
  private constructor(
    classesMapping: ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new PaddinClassesMapping();
    return new PaddingAxisInsideBreakpoints(classesMapping, selector);
  }

  public write(
    breakpoint: Breakpoints,
    axis: AxisMapping,
    spacing: FlexSpacing
  ) {
    return this.getClassName(breakpoint, axis, spacing);
  }
}

class PaddinClassesMapping
  implements
    ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
    >
{
  private defaultValue: DefaultValue<
    Breakpoints,
    Map<AxisMapping, Map<FlexSpacing, string>>
  >;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<AxisMapping, Map<FlexSpacing, string>>
    >(
      "xs",
      new Map<AxisMapping, Map<FlexSpacing, string>>([
        [
          "x",
          new Map<FlexSpacing, string>([
            [0, "xs:px-0"],
            ["px", "xs:px-px"],
            [0.5, "xs:px-0.5"],
            [1, "xs:px-1"],
            [1.5, "xs:px-1.5"],
            [2, "xs:px-2"],
            [2.5, "xs:px-2.5"],
            [3, "xs:px-3"],
            [3.5, "xs:px-3.5"],
            [4, "xs:px-4"],
            [5, "xs:px-5"],
            [6, "xs:px-6"],
            [7, "xs:px-7"],
            [8, "xs:px-8"],
            [9, "xs:px-9"],
            [10, "xs:px-10"],
            [11, "xs:px-11"],
            [12, "xs:px-12"],
            [14, "xs:px-14"],
            [16, "xs:px-16"],
            [20, "xs:px-20"],
            [24, "xs:px-24"],
            [28, "xs:px-28"],
            [32, "xs:px-32"],
            [36, "xs:px-36"],
            [40, "xs:px-40"],
            [44, "xs:px-44"],
            [48, "xs:px-48"],
            [52, "xs:px-52"],
            [56, "xs:px-56"],
            [60, "xs:px-60"],
            [64, "xs:px-64"],
            [72, "xs:px-72"],
            [80, "xs:px-80"],
            [96, "xs:px-96"],
          ]),
        ],
        [
          "y",
          new Map<FlexSpacing, string>([
            [0, "xs:py-0"],
            ["px", "xs:py-px"],
            [0.5, "xs:py-0.5"],
            [1, "xs:py-1"],
            [1.5, "xs:py-1.5"],
            [2, "xs:py-2"],
            [2.5, "xs:py-2.5"],
            [3, "xs:py-3"],
            [3.5, "xs:py-3.5"],
            [4, "xs:py-4"],
            [5, "xs:py-5"],
            [6, "xs:py-6"],
            [7, "xs:py-7"],
            [8, "xs:py-8"],
            [9, "xs:py-9"],
            [10, "xs:py-10"],
            [11, "xs:py-11"],
            [12, "xs:py-12"],
            [14, "xs:py-14"],
            [16, "xs:py-16"],
            [20, "xs:py-20"],
            [24, "xs:py-24"],
            [28, "xs:py-28"],
            [32, "xs:py-32"],
            [36, "xs:py-36"],
            [40, "xs:py-40"],
            [44, "xs:py-44"],
            [48, "xs:py-48"],
            [52, "xs:py-52"],
            [56, "xs:py-56"],
            [60, "xs:py-60"],
            [64, "xs:py-64"],
            [72, "xs:py-72"],
            [80, "xs:py-80"],
            [96, "xs:py-96"],
          ]),
        ],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<
        CSSSelector,
        Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
      >([
        [
          "active",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:active:px-0"],
                    ["px", "xs:active:px-px"],
                    [0.5, "xs:active:px-0.5"],
                    [1, "xs:active:px-1"],
                    [1.5, "xs:active:px-1.5"],
                    [2, "xs:active:px-2"],
                    [2.5, "xs:active:px-2.5"],
                    [3, "xs:active:px-3"],
                    [3.5, "xs:active:px-3.5"],
                    [4, "xs:active:px-4"],
                    [5, "xs:active:px-5"],
                    [6, "xs:active:px-6"],
                    [7, "xs:active:px-7"],
                    [8, "xs:active:px-8"],
                    [9, "xs:active:px-9"],
                    [10, "xs:active:px-10"],
                    [11, "xs:active:px-11"],
                    [12, "xs:active:px-12"],
                    [14, "xs:active:px-14"],
                    [16, "xs:active:px-16"],
                    [20, "xs:active:px-20"],
                    [24, "xs:active:px-24"],
                    [28, "xs:active:px-28"],
                    [32, "xs:active:px-32"],
                    [36, "xs:active:px-36"],
                    [40, "xs:active:px-40"],
                    [44, "xs:active:px-44"],
                    [48, "xs:active:px-48"],
                    [52, "xs:active:px-52"],
                    [56, "xs:active:px-56"],
                    [60, "xs:active:px-60"],
                    [64, "xs:active:px-64"],
                    [72, "xs:active:px-72"],
                    [80, "xs:active:px-80"],
                    [96, "xs:active:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:active:py-0"],
                    ["px", "xs:active:py-px"],
                    [0.5, "xs:active:py-0.5"],
                    [1, "xs:active:py-1"],
                    [1.5, "xs:active:py-1.5"],
                    [2, "xs:active:py-2"],
                    [2.5, "xs:active:py-2.5"],
                    [3, "xs:active:py-3"],
                    [3.5, "xs:active:py-3.5"],
                    [4, "xs:active:py-4"],
                    [5, "xs:active:py-5"],
                    [6, "xs:active:py-6"],
                    [7, "xs:active:py-7"],
                    [8, "xs:active:py-8"],
                    [9, "xs:active:py-9"],
                    [10, "xs:active:py-10"],
                    [11, "xs:active:py-11"],
                    [12, "xs:active:py-12"],
                    [14, "xs:active:py-14"],
                    [16, "xs:active:py-16"],
                    [20, "xs:active:py-20"],
                    [24, "xs:active:py-24"],
                    [28, "xs:active:py-28"],
                    [32, "xs:active:py-32"],
                    [36, "xs:active:py-36"],
                    [40, "xs:active:py-40"],
                    [44, "xs:active:py-44"],
                    [48, "xs:active:py-48"],
                    [52, "xs:active:py-52"],
                    [56, "xs:active:py-56"],
                    [60, "xs:active:py-60"],
                    [64, "xs:active:py-64"],
                    [72, "xs:active:py-72"],
                    [80, "xs:active:py-80"],
                    [96, "xs:active:py-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:active:px-0"],
                    ["px", "sm:active:px-px"],
                    [0.5, "sm:active:px-0.5"],
                    [1, "sm:active:px-1"],
                    [1.5, "sm:active:px-1.5"],
                    [2, "sm:active:px-2"],
                    [2.5, "sm:active:px-2.5"],
                    [3, "sm:active:px-3"],
                    [3.5, "sm:active:px-3.5"],
                    [4, "sm:active:px-4"],
                    [5, "sm:active:px-5"],
                    [6, "sm:active:px-6"],
                    [7, "sm:active:px-7"],
                    [8, "sm:active:px-8"],
                    [9, "sm:active:px-9"],
                    [10, "sm:active:px-10"],
                    [11, "sm:active:px-11"],
                    [12, "sm:active:px-12"],
                    [14, "sm:active:px-14"],
                    [16, "sm:active:px-16"],
                    [20, "sm:active:px-20"],
                    [24, "sm:active:px-24"],
                    [28, "sm:active:px-28"],
                    [32, "sm:active:px-32"],
                    [36, "sm:active:px-36"],
                    [40, "sm:active:px-40"],
                    [44, "sm:active:px-44"],
                    [48, "sm:active:px-48"],
                    [52, "sm:active:px-52"],
                    [56, "sm:active:px-56"],
                    [60, "sm:active:px-60"],
                    [64, "sm:active:px-64"],
                    [72, "sm:active:px-72"],
                    [80, "sm:active:px-80"],
                    [96, "sm:active:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:active:py-0"],
                    ["px", "sm:active:py-px"],
                    [0.5, "sm:active:py-0.5"],
                    [1, "sm:active:py-1"],
                    [1.5, "sm:active:py-1.5"],
                    [2, "sm:active:py-2"],
                    [2.5, "sm:active:py-2.5"],
                    [3, "sm:active:py-3"],
                    [3.5, "sm:active:py-3.5"],
                    [4, "sm:active:py-4"],
                    [5, "sm:active:py-5"],
                    [6, "sm:active:py-6"],
                    [7, "sm:active:py-7"],
                    [8, "sm:active:py-8"],
                    [9, "sm:active:py-9"],
                    [10, "sm:active:py-10"],
                    [11, "sm:active:py-11"],
                    [12, "sm:active:py-12"],
                    [14, "sm:active:py-14"],
                    [16, "sm:active:py-16"],
                    [20, "sm:active:py-20"],
                    [24, "sm:active:py-24"],
                    [28, "sm:active:py-28"],
                    [32, "sm:active:py-32"],
                    [36, "sm:active:py-36"],
                    [40, "sm:active:py-40"],
                    [44, "sm:active:py-44"],
                    [48, "sm:active:py-48"],
                    [52, "sm:active:py-52"],
                    [56, "sm:active:py-56"],
                    [60, "sm:active:py-60"],
                    [64, "sm:active:py-64"],
                    [72, "sm:active:py-72"],
                    [80, "sm:active:py-80"],
                    [96, "sm:active:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:active:px-0"],
                    ["px", "md:active:px-px"],
                    [0.5, "md:active:px-0.5"],
                    [1, "md:active:px-1"],
                    [1.5, "md:active:px-1.5"],
                    [2, "md:active:px-2"],
                    [2.5, "md:active:px-2.5"],
                    [3, "md:active:px-3"],
                    [3.5, "md:active:px-3.5"],
                    [4, "md:active:px-4"],
                    [5, "md:active:px-5"],
                    [6, "md:active:px-6"],
                    [7, "md:active:px-7"],
                    [8, "md:active:px-8"],
                    [9, "md:active:px-9"],
                    [10, "md:active:px-10"],
                    [11, "md:active:px-11"],
                    [12, "md:active:px-12"],
                    [14, "md:active:px-14"],
                    [16, "md:active:px-16"],
                    [20, "md:active:px-20"],
                    [24, "md:active:px-24"],
                    [28, "md:active:px-28"],
                    [32, "md:active:px-32"],
                    [36, "md:active:px-36"],
                    [40, "md:active:px-40"],
                    [44, "md:active:px-44"],
                    [48, "md:active:px-48"],
                    [52, "md:active:px-52"],
                    [56, "md:active:px-56"],
                    [60, "md:active:px-60"],
                    [64, "md:active:px-64"],
                    [72, "md:active:px-72"],
                    [80, "md:active:px-80"],
                    [96, "md:active:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:active:py-0"],
                    ["px", "md:active:py-px"],
                    [0.5, "md:active:py-0.5"],
                    [1, "md:active:py-1"],
                    [1.5, "md:active:py-1.5"],
                    [2, "md:active:py-2"],
                    [2.5, "md:active:py-2.5"],
                    [3, "md:active:py-3"],
                    [3.5, "md:active:py-3.5"],
                    [4, "md:active:py-4"],
                    [5, "md:active:py-5"],
                    [6, "md:active:py-6"],
                    [7, "md:active:py-7"],
                    [8, "md:active:py-8"],
                    [9, "md:active:py-9"],
                    [10, "md:active:py-10"],
                    [11, "md:active:py-11"],
                    [12, "md:active:py-12"],
                    [14, "md:active:py-14"],
                    [16, "md:active:py-16"],
                    [20, "md:active:py-20"],
                    [24, "md:active:py-24"],
                    [28, "md:active:py-28"],
                    [32, "md:active:py-32"],
                    [36, "md:active:py-36"],
                    [40, "md:active:py-40"],
                    [44, "md:active:py-44"],
                    [48, "md:active:py-48"],
                    [52, "md:active:py-52"],
                    [56, "md:active:py-56"],
                    [60, "md:active:py-60"],
                    [64, "md:active:py-64"],
                    [72, "md:active:py-72"],
                    [80, "md:active:py-80"],
                    [96, "md:active:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:active:px-0"],
                    ["px", "lg:active:px-px"],
                    [0.5, "lg:active:px-0.5"],
                    [1, "lg:active:px-1"],
                    [1.5, "lg:active:px-1.5"],
                    [2, "lg:active:px-2"],
                    [2.5, "lg:active:px-2.5"],
                    [3, "lg:active:px-3"],
                    [3.5, "lg:active:px-3.5"],
                    [4, "lg:active:px-4"],
                    [5, "lg:active:px-5"],
                    [6, "lg:active:px-6"],
                    [7, "lg:active:px-7"],
                    [8, "lg:active:px-8"],
                    [9, "lg:active:px-9"],
                    [10, "lg:active:px-10"],
                    [11, "lg:active:px-11"],
                    [12, "lg:active:px-12"],
                    [14, "lg:active:px-14"],
                    [16, "lg:active:px-16"],
                    [20, "lg:active:px-20"],
                    [24, "lg:active:px-24"],
                    [28, "lg:active:px-28"],
                    [32, "lg:active:px-32"],
                    [36, "lg:active:px-36"],
                    [40, "lg:active:px-40"],
                    [44, "lg:active:px-44"],
                    [48, "lg:active:px-48"],
                    [52, "lg:active:px-52"],
                    [56, "lg:active:px-56"],
                    [60, "lg:active:px-60"],
                    [64, "lg:active:px-64"],
                    [72, "lg:active:px-72"],
                    [80, "lg:active:px-80"],
                    [96, "lg:active:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:active:py-0"],
                    ["px", "lg:active:py-px"],
                    [0.5, "lg:active:py-0.5"],
                    [1, "lg:active:py-1"],
                    [1.5, "lg:active:py-1.5"],
                    [2, "lg:active:py-2"],
                    [2.5, "lg:active:py-2.5"],
                    [3, "lg:active:py-3"],
                    [3.5, "lg:active:py-3.5"],
                    [4, "lg:active:py-4"],
                    [5, "lg:active:py-5"],
                    [6, "lg:active:py-6"],
                    [7, "lg:active:py-7"],
                    [8, "lg:active:py-8"],
                    [9, "lg:active:py-9"],
                    [10, "lg:active:py-10"],
                    [11, "lg:active:py-11"],
                    [12, "lg:active:py-12"],
                    [14, "lg:active:py-14"],
                    [16, "lg:active:py-16"],
                    [20, "lg:active:py-20"],
                    [24, "lg:active:py-24"],
                    [28, "lg:active:py-28"],
                    [32, "lg:active:py-32"],
                    [36, "lg:active:py-36"],
                    [40, "lg:active:py-40"],
                    [44, "lg:active:py-44"],
                    [48, "lg:active:py-48"],
                    [52, "lg:active:py-52"],
                    [56, "lg:active:py-56"],
                    [60, "lg:active:py-60"],
                    [64, "lg:active:py-64"],
                    [72, "lg:active:py-72"],
                    [80, "lg:active:py-80"],
                    [96, "lg:active:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:active:px-0"],
                    ["px", "xl:active:px-px"],
                    [0.5, "xl:active:px-0.5"],
                    [1, "xl:active:px-1"],
                    [1.5, "xl:active:px-1.5"],
                    [2, "xl:active:px-2"],
                    [2.5, "xl:active:px-2.5"],
                    [3, "xl:active:px-3"],
                    [3.5, "xl:active:px-3.5"],
                    [4, "xl:active:px-4"],
                    [5, "xl:active:px-5"],
                    [6, "xl:active:px-6"],
                    [7, "xl:active:px-7"],
                    [8, "xl:active:px-8"],
                    [9, "xl:active:px-9"],
                    [10, "xl:active:px-10"],
                    [11, "xl:active:px-11"],
                    [12, "xl:active:px-12"],
                    [14, "xl:active:px-14"],
                    [16, "xl:active:px-16"],
                    [20, "xl:active:px-20"],
                    [24, "xl:active:px-24"],
                    [28, "xl:active:px-28"],
                    [32, "xl:active:px-32"],
                    [36, "xl:active:px-36"],
                    [40, "xl:active:px-40"],
                    [44, "xl:active:px-44"],
                    [48, "xl:active:px-48"],
                    [52, "xl:active:px-52"],
                    [56, "xl:active:px-56"],
                    [60, "xl:active:px-60"],
                    [64, "xl:active:px-64"],
                    [72, "xl:active:px-72"],
                    [80, "xl:active:px-80"],
                    [96, "xl:active:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:active:py-0"],
                    ["px", "xl:active:py-px"],
                    [0.5, "xl:active:py-0.5"],
                    [1, "xl:active:py-1"],
                    [1.5, "xl:active:py-1.5"],
                    [2, "xl:active:py-2"],
                    [2.5, "xl:active:py-2.5"],
                    [3, "xl:active:py-3"],
                    [3.5, "xl:active:py-3.5"],
                    [4, "xl:active:py-4"],
                    [5, "xl:active:py-5"],
                    [6, "xl:active:py-6"],
                    [7, "xl:active:py-7"],
                    [8, "xl:active:py-8"],
                    [9, "xl:active:py-9"],
                    [10, "xl:active:py-10"],
                    [11, "xl:active:py-11"],
                    [12, "xl:active:py-12"],
                    [14, "xl:active:py-14"],
                    [16, "xl:active:py-16"],
                    [20, "xl:active:py-20"],
                    [24, "xl:active:py-24"],
                    [28, "xl:active:py-28"],
                    [32, "xl:active:py-32"],
                    [36, "xl:active:py-36"],
                    [40, "xl:active:py-40"],
                    [44, "xl:active:py-44"],
                    [48, "xl:active:py-48"],
                    [52, "xl:active:py-52"],
                    [56, "xl:active:py-56"],
                    [60, "xl:active:py-60"],
                    [64, "xl:active:py-64"],
                    [72, "xl:active:py-72"],
                    [80, "xl:active:py-80"],
                    [96, "xl:active:py-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:disabled:px-0"],
                    ["px", "xs:disabled:px-px"],
                    [0.5, "xs:disabled:px-0.5"],
                    [1, "xs:disabled:px-1"],
                    [1.5, "xs:disabled:px-1.5"],
                    [2, "xs:disabled:px-2"],
                    [2.5, "xs:disabled:px-2.5"],
                    [3, "xs:disabled:px-3"],
                    [3.5, "xs:disabled:px-3.5"],
                    [4, "xs:disabled:px-4"],
                    [5, "xs:disabled:px-5"],
                    [6, "xs:disabled:px-6"],
                    [7, "xs:disabled:px-7"],
                    [8, "xs:disabled:px-8"],
                    [9, "xs:disabled:px-9"],
                    [10, "xs:disabled:px-10"],
                    [11, "xs:disabled:px-11"],
                    [12, "xs:disabled:px-12"],
                    [14, "xs:disabled:px-14"],
                    [16, "xs:disabled:px-16"],
                    [20, "xs:disabled:px-20"],
                    [24, "xs:disabled:px-24"],
                    [28, "xs:disabled:px-28"],
                    [32, "xs:disabled:px-32"],
                    [36, "xs:disabled:px-36"],
                    [40, "xs:disabled:px-40"],
                    [44, "xs:disabled:px-44"],
                    [48, "xs:disabled:px-48"],
                    [52, "xs:disabled:px-52"],
                    [56, "xs:disabled:px-56"],
                    [60, "xs:disabled:px-60"],
                    [64, "xs:disabled:px-64"],
                    [72, "xs:disabled:px-72"],
                    [80, "xs:disabled:px-80"],
                    [96, "xs:disabled:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:disabled:py-0"],
                    ["px", "xs:disabled:py-px"],
                    [0.5, "xs:disabled:py-0.5"],
                    [1, "xs:disabled:py-1"],
                    [1.5, "xs:disabled:py-1.5"],
                    [2, "xs:disabled:py-2"],
                    [2.5, "xs:disabled:py-2.5"],
                    [3, "xs:disabled:py-3"],
                    [3.5, "xs:disabled:py-3.5"],
                    [4, "xs:disabled:py-4"],
                    [5, "xs:disabled:py-5"],
                    [6, "xs:disabled:py-6"],
                    [7, "xs:disabled:py-7"],
                    [8, "xs:disabled:py-8"],
                    [9, "xs:disabled:py-9"],
                    [10, "xs:disabled:py-10"],
                    [11, "xs:disabled:py-11"],
                    [12, "xs:disabled:py-12"],
                    [14, "xs:disabled:py-14"],
                    [16, "xs:disabled:py-16"],
                    [20, "xs:disabled:py-20"],
                    [24, "xs:disabled:py-24"],
                    [28, "xs:disabled:py-28"],
                    [32, "xs:disabled:py-32"],
                    [36, "xs:disabled:py-36"],
                    [40, "xs:disabled:py-40"],
                    [44, "xs:disabled:py-44"],
                    [48, "xs:disabled:py-48"],
                    [52, "xs:disabled:py-52"],
                    [56, "xs:disabled:py-56"],
                    [60, "xs:disabled:py-60"],
                    [64, "xs:disabled:py-64"],
                    [72, "xs:disabled:py-72"],
                    [80, "xs:disabled:py-80"],
                    [96, "xs:disabled:py-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:disabled:px-0"],
                    ["px", "sm:disabled:px-px"],
                    [0.5, "sm:disabled:px-0.5"],
                    [1, "sm:disabled:px-1"],
                    [1.5, "sm:disabled:px-1.5"],
                    [2, "sm:disabled:px-2"],
                    [2.5, "sm:disabled:px-2.5"],
                    [3, "sm:disabled:px-3"],
                    [3.5, "sm:disabled:px-3.5"],
                    [4, "sm:disabled:px-4"],
                    [5, "sm:disabled:px-5"],
                    [6, "sm:disabled:px-6"],
                    [7, "sm:disabled:px-7"],
                    [8, "sm:disabled:px-8"],
                    [9, "sm:disabled:px-9"],
                    [10, "sm:disabled:px-10"],
                    [11, "sm:disabled:px-11"],
                    [12, "sm:disabled:px-12"],
                    [14, "sm:disabled:px-14"],
                    [16, "sm:disabled:px-16"],
                    [20, "sm:disabled:px-20"],
                    [24, "sm:disabled:px-24"],
                    [28, "sm:disabled:px-28"],
                    [32, "sm:disabled:px-32"],
                    [36, "sm:disabled:px-36"],
                    [40, "sm:disabled:px-40"],
                    [44, "sm:disabled:px-44"],
                    [48, "sm:disabled:px-48"],
                    [52, "sm:disabled:px-52"],
                    [56, "sm:disabled:px-56"],
                    [60, "sm:disabled:px-60"],
                    [64, "sm:disabled:px-64"],
                    [72, "sm:disabled:px-72"],
                    [80, "sm:disabled:px-80"],
                    [96, "sm:disabled:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:disabled:py-0"],
                    ["px", "sm:disabled:py-px"],
                    [0.5, "sm:disabled:py-0.5"],
                    [1, "sm:disabled:py-1"],
                    [1.5, "sm:disabled:py-1.5"],
                    [2, "sm:disabled:py-2"],
                    [2.5, "sm:disabled:py-2.5"],
                    [3, "sm:disabled:py-3"],
                    [3.5, "sm:disabled:py-3.5"],
                    [4, "sm:disabled:py-4"],
                    [5, "sm:disabled:py-5"],
                    [6, "sm:disabled:py-6"],
                    [7, "sm:disabled:py-7"],
                    [8, "sm:disabled:py-8"],
                    [9, "sm:disabled:py-9"],
                    [10, "sm:disabled:py-10"],
                    [11, "sm:disabled:py-11"],
                    [12, "sm:disabled:py-12"],
                    [14, "sm:disabled:py-14"],
                    [16, "sm:disabled:py-16"],
                    [20, "sm:disabled:py-20"],
                    [24, "sm:disabled:py-24"],
                    [28, "sm:disabled:py-28"],
                    [32, "sm:disabled:py-32"],
                    [36, "sm:disabled:py-36"],
                    [40, "sm:disabled:py-40"],
                    [44, "sm:disabled:py-44"],
                    [48, "sm:disabled:py-48"],
                    [52, "sm:disabled:py-52"],
                    [56, "sm:disabled:py-56"],
                    [60, "sm:disabled:py-60"],
                    [64, "sm:disabled:py-64"],
                    [72, "sm:disabled:py-72"],
                    [80, "sm:disabled:py-80"],
                    [96, "sm:disabled:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:disabled:px-0"],
                    ["px", "md:disabled:px-px"],
                    [0.5, "md:disabled:px-0.5"],
                    [1, "md:disabled:px-1"],
                    [1.5, "md:disabled:px-1.5"],
                    [2, "md:disabled:px-2"],
                    [2.5, "md:disabled:px-2.5"],
                    [3, "md:disabled:px-3"],
                    [3.5, "md:disabled:px-3.5"],
                    [4, "md:disabled:px-4"],
                    [5, "md:disabled:px-5"],
                    [6, "md:disabled:px-6"],
                    [7, "md:disabled:px-7"],
                    [8, "md:disabled:px-8"],
                    [9, "md:disabled:px-9"],
                    [10, "md:disabled:px-10"],
                    [11, "md:disabled:px-11"],
                    [12, "md:disabled:px-12"],
                    [14, "md:disabled:px-14"],
                    [16, "md:disabled:px-16"],
                    [20, "md:disabled:px-20"],
                    [24, "md:disabled:px-24"],
                    [28, "md:disabled:px-28"],
                    [32, "md:disabled:px-32"],
                    [36, "md:disabled:px-36"],
                    [40, "md:disabled:px-40"],
                    [44, "md:disabled:px-44"],
                    [48, "md:disabled:px-48"],
                    [52, "md:disabled:px-52"],
                    [56, "md:disabled:px-56"],
                    [60, "md:disabled:px-60"],
                    [64, "md:disabled:px-64"],
                    [72, "md:disabled:px-72"],
                    [80, "md:disabled:px-80"],
                    [96, "md:disabled:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:disabled:py-0"],
                    ["px", "md:disabled:py-px"],
                    [0.5, "md:disabled:py-0.5"],
                    [1, "md:disabled:py-1"],
                    [1.5, "md:disabled:py-1.5"],
                    [2, "md:disabled:py-2"],
                    [2.5, "md:disabled:py-2.5"],
                    [3, "md:disabled:py-3"],
                    [3.5, "md:disabled:py-3.5"],
                    [4, "md:disabled:py-4"],
                    [5, "md:disabled:py-5"],
                    [6, "md:disabled:py-6"],
                    [7, "md:disabled:py-7"],
                    [8, "md:disabled:py-8"],
                    [9, "md:disabled:py-9"],
                    [10, "md:disabled:py-10"],
                    [11, "md:disabled:py-11"],
                    [12, "md:disabled:py-12"],
                    [14, "md:disabled:py-14"],
                    [16, "md:disabled:py-16"],
                    [20, "md:disabled:py-20"],
                    [24, "md:disabled:py-24"],
                    [28, "md:disabled:py-28"],
                    [32, "md:disabled:py-32"],
                    [36, "md:disabled:py-36"],
                    [40, "md:disabled:py-40"],
                    [44, "md:disabled:py-44"],
                    [48, "md:disabled:py-48"],
                    [52, "md:disabled:py-52"],
                    [56, "md:disabled:py-56"],
                    [60, "md:disabled:py-60"],
                    [64, "md:disabled:py-64"],
                    [72, "md:disabled:py-72"],
                    [80, "md:disabled:py-80"],
                    [96, "md:disabled:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:disabled:px-0"],
                    ["px", "lg:disabled:px-px"],
                    [0.5, "lg:disabled:px-0.5"],
                    [1, "lg:disabled:px-1"],
                    [1.5, "lg:disabled:px-1.5"],
                    [2, "lg:disabled:px-2"],
                    [2.5, "lg:disabled:px-2.5"],
                    [3, "lg:disabled:px-3"],
                    [3.5, "lg:disabled:px-3.5"],
                    [4, "lg:disabled:px-4"],
                    [5, "lg:disabled:px-5"],
                    [6, "lg:disabled:px-6"],
                    [7, "lg:disabled:px-7"],
                    [8, "lg:disabled:px-8"],
                    [9, "lg:disabled:px-9"],
                    [10, "lg:disabled:px-10"],
                    [11, "lg:disabled:px-11"],
                    [12, "lg:disabled:px-12"],
                    [14, "lg:disabled:px-14"],
                    [16, "lg:disabled:px-16"],
                    [20, "lg:disabled:px-20"],
                    [24, "lg:disabled:px-24"],
                    [28, "lg:disabled:px-28"],
                    [32, "lg:disabled:px-32"],
                    [36, "lg:disabled:px-36"],
                    [40, "lg:disabled:px-40"],
                    [44, "lg:disabled:px-44"],
                    [48, "lg:disabled:px-48"],
                    [52, "lg:disabled:px-52"],
                    [56, "lg:disabled:px-56"],
                    [60, "lg:disabled:px-60"],
                    [64, "lg:disabled:px-64"],
                    [72, "lg:disabled:px-72"],
                    [80, "lg:disabled:px-80"],
                    [96, "lg:disabled:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:disabled:py-0"],
                    ["px", "lg:disabled:py-px"],
                    [0.5, "lg:disabled:py-0.5"],
                    [1, "lg:disabled:py-1"],
                    [1.5, "lg:disabled:py-1.5"],
                    [2, "lg:disabled:py-2"],
                    [2.5, "lg:disabled:py-2.5"],
                    [3, "lg:disabled:py-3"],
                    [3.5, "lg:disabled:py-3.5"],
                    [4, "lg:disabled:py-4"],
                    [5, "lg:disabled:py-5"],
                    [6, "lg:disabled:py-6"],
                    [7, "lg:disabled:py-7"],
                    [8, "lg:disabled:py-8"],
                    [9, "lg:disabled:py-9"],
                    [10, "lg:disabled:py-10"],
                    [11, "lg:disabled:py-11"],
                    [12, "lg:disabled:py-12"],
                    [14, "lg:disabled:py-14"],
                    [16, "lg:disabled:py-16"],
                    [20, "lg:disabled:py-20"],
                    [24, "lg:disabled:py-24"],
                    [28, "lg:disabled:py-28"],
                    [32, "lg:disabled:py-32"],
                    [36, "lg:disabled:py-36"],
                    [40, "lg:disabled:py-40"],
                    [44, "lg:disabled:py-44"],
                    [48, "lg:disabled:py-48"],
                    [52, "lg:disabled:py-52"],
                    [56, "lg:disabled:py-56"],
                    [60, "lg:disabled:py-60"],
                    [64, "lg:disabled:py-64"],
                    [72, "lg:disabled:py-72"],
                    [80, "lg:disabled:py-80"],
                    [96, "lg:disabled:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:disabled:px-0"],
                    ["px", "xl:disabled:px-px"],
                    [0.5, "xl:disabled:px-0.5"],
                    [1, "xl:disabled:px-1"],
                    [1.5, "xl:disabled:px-1.5"],
                    [2, "xl:disabled:px-2"],
                    [2.5, "xl:disabled:px-2.5"],
                    [3, "xl:disabled:px-3"],
                    [3.5, "xl:disabled:px-3.5"],
                    [4, "xl:disabled:px-4"],
                    [5, "xl:disabled:px-5"],
                    [6, "xl:disabled:px-6"],
                    [7, "xl:disabled:px-7"],
                    [8, "xl:disabled:px-8"],
                    [9, "xl:disabled:px-9"],
                    [10, "xl:disabled:px-10"],
                    [11, "xl:disabled:px-11"],
                    [12, "xl:disabled:px-12"],
                    [14, "xl:disabled:px-14"],
                    [16, "xl:disabled:px-16"],
                    [20, "xl:disabled:px-20"],
                    [24, "xl:disabled:px-24"],
                    [28, "xl:disabled:px-28"],
                    [32, "xl:disabled:px-32"],
                    [36, "xl:disabled:px-36"],
                    [40, "xl:disabled:px-40"],
                    [44, "xl:disabled:px-44"],
                    [48, "xl:disabled:px-48"],
                    [52, "xl:disabled:px-52"],
                    [56, "xl:disabled:px-56"],
                    [60, "xl:disabled:px-60"],
                    [64, "xl:disabled:px-64"],
                    [72, "xl:disabled:px-72"],
                    [80, "xl:disabled:px-80"],
                    [96, "xl:disabled:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:disabled:py-0"],
                    ["px", "xl:disabled:py-px"],
                    [0.5, "xl:disabled:py-0.5"],
                    [1, "xl:disabled:py-1"],
                    [1.5, "xl:disabled:py-1.5"],
                    [2, "xl:disabled:py-2"],
                    [2.5, "xl:disabled:py-2.5"],
                    [3, "xl:disabled:py-3"],
                    [3.5, "xl:disabled:py-3.5"],
                    [4, "xl:disabled:py-4"],
                    [5, "xl:disabled:py-5"],
                    [6, "xl:disabled:py-6"],
                    [7, "xl:disabled:py-7"],
                    [8, "xl:disabled:py-8"],
                    [9, "xl:disabled:py-9"],
                    [10, "xl:disabled:py-10"],
                    [11, "xl:disabled:py-11"],
                    [12, "xl:disabled:py-12"],
                    [14, "xl:disabled:py-14"],
                    [16, "xl:disabled:py-16"],
                    [20, "xl:disabled:py-20"],
                    [24, "xl:disabled:py-24"],
                    [28, "xl:disabled:py-28"],
                    [32, "xl:disabled:py-32"],
                    [36, "xl:disabled:py-36"],
                    [40, "xl:disabled:py-40"],
                    [44, "xl:disabled:py-44"],
                    [48, "xl:disabled:py-48"],
                    [52, "xl:disabled:py-52"],
                    [56, "xl:disabled:py-56"],
                    [60, "xl:disabled:py-60"],
                    [64, "xl:disabled:py-64"],
                    [72, "xl:disabled:py-72"],
                    [80, "xl:disabled:py-80"],
                    [96, "xl:disabled:py-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:hover:px-0"],
                    ["px", "xs:hover:px-px"],
                    [0.5, "xs:hover:px-0.5"],
                    [1, "xs:hover:px-1"],
                    [1.5, "xs:hover:px-1.5"],
                    [2, "xs:hover:px-2"],
                    [2.5, "xs:hover:px-2.5"],
                    [3, "xs:hover:px-3"],
                    [3.5, "xs:hover:px-3.5"],
                    [4, "xs:hover:px-4"],
                    [5, "xs:hover:px-5"],
                    [6, "xs:hover:px-6"],
                    [7, "xs:hover:px-7"],
                    [8, "xs:hover:px-8"],
                    [9, "xs:hover:px-9"],
                    [10, "xs:hover:px-10"],
                    [11, "xs:hover:px-11"],
                    [12, "xs:hover:px-12"],
                    [14, "xs:hover:px-14"],
                    [16, "xs:hover:px-16"],
                    [20, "xs:hover:px-20"],
                    [24, "xs:hover:px-24"],
                    [28, "xs:hover:px-28"],
                    [32, "xs:hover:px-32"],
                    [36, "xs:hover:px-36"],
                    [40, "xs:hover:px-40"],
                    [44, "xs:hover:px-44"],
                    [48, "xs:hover:px-48"],
                    [52, "xs:hover:px-52"],
                    [56, "xs:hover:px-56"],
                    [60, "xs:hover:px-60"],
                    [64, "xs:hover:px-64"],
                    [72, "xs:hover:px-72"],
                    [80, "xs:hover:px-80"],
                    [96, "xs:hover:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:hover:py-0"],
                    ["px", "xs:hover:py-px"],
                    [0.5, "xs:hover:py-0.5"],
                    [1, "xs:hover:py-1"],
                    [1.5, "xs:hover:py-1.5"],
                    [2, "xs:hover:py-2"],
                    [2.5, "xs:hover:py-2.5"],
                    [3, "xs:hover:py-3"],
                    [3.5, "xs:hover:py-3.5"],
                    [4, "xs:hover:py-4"],
                    [5, "xs:hover:py-5"],
                    [6, "xs:hover:py-6"],
                    [7, "xs:hover:py-7"],
                    [8, "xs:hover:py-8"],
                    [9, "xs:hover:py-9"],
                    [10, "xs:hover:py-10"],
                    [11, "xs:hover:py-11"],
                    [12, "xs:hover:py-12"],
                    [14, "xs:hover:py-14"],
                    [16, "xs:hover:py-16"],
                    [20, "xs:hover:py-20"],
                    [24, "xs:hover:py-24"],
                    [28, "xs:hover:py-28"],
                    [32, "xs:hover:py-32"],
                    [36, "xs:hover:py-36"],
                    [40, "xs:hover:py-40"],
                    [44, "xs:hover:py-44"],
                    [48, "xs:hover:py-48"],
                    [52, "xs:hover:py-52"],
                    [56, "xs:hover:py-56"],
                    [60, "xs:hover:py-60"],
                    [64, "xs:hover:py-64"],
                    [72, "xs:hover:py-72"],
                    [80, "xs:hover:py-80"],
                    [96, "xs:hover:py-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:hover:px-0"],
                    ["px", "sm:hover:px-px"],
                    [0.5, "sm:hover:px-0.5"],
                    [1, "sm:hover:px-1"],
                    [1.5, "sm:hover:px-1.5"],
                    [2, "sm:hover:px-2"],
                    [2.5, "sm:hover:px-2.5"],
                    [3, "sm:hover:px-3"],
                    [3.5, "sm:hover:px-3.5"],
                    [4, "sm:hover:px-4"],
                    [5, "sm:hover:px-5"],
                    [6, "sm:hover:px-6"],
                    [7, "sm:hover:px-7"],
                    [8, "sm:hover:px-8"],
                    [9, "sm:hover:px-9"],
                    [10, "sm:hover:px-10"],
                    [11, "sm:hover:px-11"],
                    [12, "sm:hover:px-12"],
                    [14, "sm:hover:px-14"],
                    [16, "sm:hover:px-16"],
                    [20, "sm:hover:px-20"],
                    [24, "sm:hover:px-24"],
                    [28, "sm:hover:px-28"],
                    [32, "sm:hover:px-32"],
                    [36, "sm:hover:px-36"],
                    [40, "sm:hover:px-40"],
                    [44, "sm:hover:px-44"],
                    [48, "sm:hover:px-48"],
                    [52, "sm:hover:px-52"],
                    [56, "sm:hover:px-56"],
                    [60, "sm:hover:px-60"],
                    [64, "sm:hover:px-64"],
                    [72, "sm:hover:px-72"],
                    [80, "sm:hover:px-80"],
                    [96, "sm:hover:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:hover:py-0"],
                    ["px", "sm:hover:py-px"],
                    [0.5, "sm:hover:py-0.5"],
                    [1, "sm:hover:py-1"],
                    [1.5, "sm:hover:py-1.5"],
                    [2, "sm:hover:py-2"],
                    [2.5, "sm:hover:py-2.5"],
                    [3, "sm:hover:py-3"],
                    [3.5, "sm:hover:py-3.5"],
                    [4, "sm:hover:py-4"],
                    [5, "sm:hover:py-5"],
                    [6, "sm:hover:py-6"],
                    [7, "sm:hover:py-7"],
                    [8, "sm:hover:py-8"],
                    [9, "sm:hover:py-9"],
                    [10, "sm:hover:py-10"],
                    [11, "sm:hover:py-11"],
                    [12, "sm:hover:py-12"],
                    [14, "sm:hover:py-14"],
                    [16, "sm:hover:py-16"],
                    [20, "sm:hover:py-20"],
                    [24, "sm:hover:py-24"],
                    [28, "sm:hover:py-28"],
                    [32, "sm:hover:py-32"],
                    [36, "sm:hover:py-36"],
                    [40, "sm:hover:py-40"],
                    [44, "sm:hover:py-44"],
                    [48, "sm:hover:py-48"],
                    [52, "sm:hover:py-52"],
                    [56, "sm:hover:py-56"],
                    [60, "sm:hover:py-60"],
                    [64, "sm:hover:py-64"],
                    [72, "sm:hover:py-72"],
                    [80, "sm:hover:py-80"],
                    [96, "sm:hover:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:hover:px-0"],
                    ["px", "md:hover:px-px"],
                    [0.5, "md:hover:px-0.5"],
                    [1, "md:hover:px-1"],
                    [1.5, "md:hover:px-1.5"],
                    [2, "md:hover:px-2"],
                    [2.5, "md:hover:px-2.5"],
                    [3, "md:hover:px-3"],
                    [3.5, "md:hover:px-3.5"],
                    [4, "md:hover:px-4"],
                    [5, "md:hover:px-5"],
                    [6, "md:hover:px-6"],
                    [7, "md:hover:px-7"],
                    [8, "md:hover:px-8"],
                    [9, "md:hover:px-9"],
                    [10, "md:hover:px-10"],
                    [11, "md:hover:px-11"],
                    [12, "md:hover:px-12"],
                    [14, "md:hover:px-14"],
                    [16, "md:hover:px-16"],
                    [20, "md:hover:px-20"],
                    [24, "md:hover:px-24"],
                    [28, "md:hover:px-28"],
                    [32, "md:hover:px-32"],
                    [36, "md:hover:px-36"],
                    [40, "md:hover:px-40"],
                    [44, "md:hover:px-44"],
                    [48, "md:hover:px-48"],
                    [52, "md:hover:px-52"],
                    [56, "md:hover:px-56"],
                    [60, "md:hover:px-60"],
                    [64, "md:hover:px-64"],
                    [72, "md:hover:px-72"],
                    [80, "md:hover:px-80"],
                    [96, "md:hover:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:hover:py-0"],
                    ["px", "md:hover:py-px"],
                    [0.5, "md:hover:py-0.5"],
                    [1, "md:hover:py-1"],
                    [1.5, "md:hover:py-1.5"],
                    [2, "md:hover:py-2"],
                    [2.5, "md:hover:py-2.5"],
                    [3, "md:hover:py-3"],
                    [3.5, "md:hover:py-3.5"],
                    [4, "md:hover:py-4"],
                    [5, "md:hover:py-5"],
                    [6, "md:hover:py-6"],
                    [7, "md:hover:py-7"],
                    [8, "md:hover:py-8"],
                    [9, "md:hover:py-9"],
                    [10, "md:hover:py-10"],
                    [11, "md:hover:py-11"],
                    [12, "md:hover:py-12"],
                    [14, "md:hover:py-14"],
                    [16, "md:hover:py-16"],
                    [20, "md:hover:py-20"],
                    [24, "md:hover:py-24"],
                    [28, "md:hover:py-28"],
                    [32, "md:hover:py-32"],
                    [36, "md:hover:py-36"],
                    [40, "md:hover:py-40"],
                    [44, "md:hover:py-44"],
                    [48, "md:hover:py-48"],
                    [52, "md:hover:py-52"],
                    [56, "md:hover:py-56"],
                    [60, "md:hover:py-60"],
                    [64, "md:hover:py-64"],
                    [72, "md:hover:py-72"],
                    [80, "md:hover:py-80"],
                    [96, "md:hover:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:hover:px-0"],
                    ["px", "lg:hover:px-px"],
                    [0.5, "lg:hover:px-0.5"],
                    [1, "lg:hover:px-1"],
                    [1.5, "lg:hover:px-1.5"],
                    [2, "lg:hover:px-2"],
                    [2.5, "lg:hover:px-2.5"],
                    [3, "lg:hover:px-3"],
                    [3.5, "lg:hover:px-3.5"],
                    [4, "lg:hover:px-4"],
                    [5, "lg:hover:px-5"],
                    [6, "lg:hover:px-6"],
                    [7, "lg:hover:px-7"],
                    [8, "lg:hover:px-8"],
                    [9, "lg:hover:px-9"],
                    [10, "lg:hover:px-10"],
                    [11, "lg:hover:px-11"],
                    [12, "lg:hover:px-12"],
                    [14, "lg:hover:px-14"],
                    [16, "lg:hover:px-16"],
                    [20, "lg:hover:px-20"],
                    [24, "lg:hover:px-24"],
                    [28, "lg:hover:px-28"],
                    [32, "lg:hover:px-32"],
                    [36, "lg:hover:px-36"],
                    [40, "lg:hover:px-40"],
                    [44, "lg:hover:px-44"],
                    [48, "lg:hover:px-48"],
                    [52, "lg:hover:px-52"],
                    [56, "lg:hover:px-56"],
                    [60, "lg:hover:px-60"],
                    [64, "lg:hover:px-64"],
                    [72, "lg:hover:px-72"],
                    [80, "lg:hover:px-80"],
                    [96, "lg:hover:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:hover:py-0"],
                    ["px", "lg:hover:py-px"],
                    [0.5, "lg:hover:py-0.5"],
                    [1, "lg:hover:py-1"],
                    [1.5, "lg:hover:py-1.5"],
                    [2, "lg:hover:py-2"],
                    [2.5, "lg:hover:py-2.5"],
                    [3, "lg:hover:py-3"],
                    [3.5, "lg:hover:py-3.5"],
                    [4, "lg:hover:py-4"],
                    [5, "lg:hover:py-5"],
                    [6, "lg:hover:py-6"],
                    [7, "lg:hover:py-7"],
                    [8, "lg:hover:py-8"],
                    [9, "lg:hover:py-9"],
                    [10, "lg:hover:py-10"],
                    [11, "lg:hover:py-11"],
                    [12, "lg:hover:py-12"],
                    [14, "lg:hover:py-14"],
                    [16, "lg:hover:py-16"],
                    [20, "lg:hover:py-20"],
                    [24, "lg:hover:py-24"],
                    [28, "lg:hover:py-28"],
                    [32, "lg:hover:py-32"],
                    [36, "lg:hover:py-36"],
                    [40, "lg:hover:py-40"],
                    [44, "lg:hover:py-44"],
                    [48, "lg:hover:py-48"],
                    [52, "lg:hover:py-52"],
                    [56, "lg:hover:py-56"],
                    [60, "lg:hover:py-60"],
                    [64, "lg:hover:py-64"],
                    [72, "lg:hover:py-72"],
                    [80, "lg:hover:py-80"],
                    [96, "lg:hover:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:hover:px-0"],
                    ["px", "xl:hover:px-px"],
                    [0.5, "xl:hover:px-0.5"],
                    [1, "xl:hover:px-1"],
                    [1.5, "xl:hover:px-1.5"],
                    [2, "xl:hover:px-2"],
                    [2.5, "xl:hover:px-2.5"],
                    [3, "xl:hover:px-3"],
                    [3.5, "xl:hover:px-3.5"],
                    [4, "xl:hover:px-4"],
                    [5, "xl:hover:px-5"],
                    [6, "xl:hover:px-6"],
                    [7, "xl:hover:px-7"],
                    [8, "xl:hover:px-8"],
                    [9, "xl:hover:px-9"],
                    [10, "xl:hover:px-10"],
                    [11, "xl:hover:px-11"],
                    [12, "xl:hover:px-12"],
                    [14, "xl:hover:px-14"],
                    [16, "xl:hover:px-16"],
                    [20, "xl:hover:px-20"],
                    [24, "xl:hover:px-24"],
                    [28, "xl:hover:px-28"],
                    [32, "xl:hover:px-32"],
                    [36, "xl:hover:px-36"],
                    [40, "xl:hover:px-40"],
                    [44, "xl:hover:px-44"],
                    [48, "xl:hover:px-48"],
                    [52, "xl:hover:px-52"],
                    [56, "xl:hover:px-56"],
                    [60, "xl:hover:px-60"],
                    [64, "xl:hover:px-64"],
                    [72, "xl:hover:px-72"],
                    [80, "xl:hover:px-80"],
                    [96, "xl:hover:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:hover:py-0"],
                    ["px", "xl:hover:py-px"],
                    [0.5, "xl:hover:py-0.5"],
                    [1, "xl:hover:py-1"],
                    [1.5, "xl:hover:py-1.5"],
                    [2, "xl:hover:py-2"],
                    [2.5, "xl:hover:py-2.5"],
                    [3, "xl:hover:py-3"],
                    [3.5, "xl:hover:py-3.5"],
                    [4, "xl:hover:py-4"],
                    [5, "xl:hover:py-5"],
                    [6, "xl:hover:py-6"],
                    [7, "xl:hover:py-7"],
                    [8, "xl:hover:py-8"],
                    [9, "xl:hover:py-9"],
                    [10, "xl:hover:py-10"],
                    [11, "xl:hover:py-11"],
                    [12, "xl:hover:py-12"],
                    [14, "xl:hover:py-14"],
                    [16, "xl:hover:py-16"],
                    [20, "xl:hover:py-20"],
                    [24, "xl:hover:py-24"],
                    [28, "xl:hover:py-28"],
                    [32, "xl:hover:py-32"],
                    [36, "xl:hover:py-36"],
                    [40, "xl:hover:py-40"],
                    [44, "xl:hover:py-44"],
                    [48, "xl:hover:py-48"],
                    [52, "xl:hover:py-52"],
                    [56, "xl:hover:py-56"],
                    [60, "xl:hover:py-60"],
                    [64, "xl:hover:py-64"],
                    [72, "xl:hover:py-72"],
                    [80, "xl:hover:py-80"],
                    [96, "xl:hover:py-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:px-0"],
                    ["px", "xs:px-px"],
                    [0.5, "xs:px-0.5"],
                    [1, "xs:px-1"],
                    [1.5, "xs:px-1.5"],
                    [2, "xs:px-2"],
                    [2.5, "xs:px-2.5"],
                    [3, "xs:px-3"],
                    [3.5, "xs:px-3.5"],
                    [4, "xs:px-4"],
                    [5, "xs:px-5"],
                    [6, "xs:px-6"],
                    [7, "xs:px-7"],
                    [8, "xs:px-8"],
                    [9, "xs:px-9"],
                    [10, "xs:px-10"],
                    [11, "xs:px-11"],
                    [12, "xs:px-12"],
                    [14, "xs:px-14"],
                    [16, "xs:px-16"],
                    [20, "xs:px-20"],
                    [24, "xs:px-24"],
                    [28, "xs:px-28"],
                    [32, "xs:px-32"],
                    [36, "xs:px-36"],
                    [40, "xs:px-40"],
                    [44, "xs:px-44"],
                    [48, "xs:px-48"],
                    [52, "xs:px-52"],
                    [56, "xs:px-56"],
                    [60, "xs:px-60"],
                    [64, "xs:px-64"],
                    [72, "xs:px-72"],
                    [80, "xs:px-80"],
                    [96, "xs:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:py-0"],
                    ["px", "xs:py-px"],
                    [0.5, "xs:py-0.5"],
                    [1, "xs:py-1"],
                    [1.5, "xs:py-1.5"],
                    [2, "xs:py-2"],
                    [2.5, "xs:py-2.5"],
                    [3, "xs:py-3"],
                    [3.5, "xs:py-3.5"],
                    [4, "xs:py-4"],
                    [5, "xs:py-5"],
                    [6, "xs:py-6"],
                    [7, "xs:py-7"],
                    [8, "xs:py-8"],
                    [9, "xs:py-9"],
                    [10, "xs:py-10"],
                    [11, "xs:py-11"],
                    [12, "xs:py-12"],
                    [14, "xs:py-14"],
                    [16, "xs:py-16"],
                    [20, "xs:py-20"],
                    [24, "xs:py-24"],
                    [28, "xs:py-28"],
                    [32, "xs:py-32"],
                    [36, "xs:py-36"],
                    [40, "xs:py-40"],
                    [44, "xs:py-44"],
                    [48, "xs:py-48"],
                    [52, "xs:py-52"],
                    [56, "xs:py-56"],
                    [60, "xs:py-60"],
                    [64, "xs:py-64"],
                    [72, "xs:py-72"],
                    [80, "xs:py-80"],
                    [96, "xs:py-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:px-0"],
                    ["px", "sm:px-px"],
                    [0.5, "sm:px-0.5"],
                    [1, "sm:px-1"],
                    [1.5, "sm:px-1.5"],
                    [2, "sm:px-2"],
                    [2.5, "sm:px-2.5"],
                    [3, "sm:px-3"],
                    [3.5, "sm:px-3.5"],
                    [4, "sm:px-4"],
                    [5, "sm:px-5"],
                    [6, "sm:px-6"],
                    [7, "sm:px-7"],
                    [8, "sm:px-8"],
                    [9, "sm:px-9"],
                    [10, "sm:px-10"],
                    [11, "sm:px-11"],
                    [12, "sm:px-12"],
                    [14, "sm:px-14"],
                    [16, "sm:px-16"],
                    [20, "sm:px-20"],
                    [24, "sm:px-24"],
                    [28, "sm:px-28"],
                    [32, "sm:px-32"],
                    [36, "sm:px-36"],
                    [40, "sm:px-40"],
                    [44, "sm:px-44"],
                    [48, "sm:px-48"],
                    [52, "sm:px-52"],
                    [56, "sm:px-56"],
                    [60, "sm:px-60"],
                    [64, "sm:px-64"],
                    [72, "sm:px-72"],
                    [80, "sm:px-80"],
                    [96, "sm:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:py-0"],
                    ["px", "sm:py-px"],
                    [0.5, "sm:py-0.5"],
                    [1, "sm:py-1"],
                    [1.5, "sm:py-1.5"],
                    [2, "sm:py-2"],
                    [2.5, "sm:py-2.5"],
                    [3, "sm:py-3"],
                    [3.5, "sm:py-3.5"],
                    [4, "sm:py-4"],
                    [5, "sm:py-5"],
                    [6, "sm:py-6"],
                    [7, "sm:py-7"],
                    [8, "sm:py-8"],
                    [9, "sm:py-9"],
                    [10, "sm:py-10"],
                    [11, "sm:py-11"],
                    [12, "sm:py-12"],
                    [14, "sm:py-14"],
                    [16, "sm:py-16"],
                    [20, "sm:py-20"],
                    [24, "sm:py-24"],
                    [28, "sm:py-28"],
                    [32, "sm:py-32"],
                    [36, "sm:py-36"],
                    [40, "sm:py-40"],
                    [44, "sm:py-44"],
                    [48, "sm:py-48"],
                    [52, "sm:py-52"],
                    [56, "sm:py-56"],
                    [60, "sm:py-60"],
                    [64, "sm:py-64"],
                    [72, "sm:py-72"],
                    [80, "sm:py-80"],
                    [96, "sm:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:px-0"],
                    ["px", "md:px-px"],
                    [0.5, "md:px-0.5"],
                    [1, "md:px-1"],
                    [1.5, "md:px-1.5"],
                    [2, "md:px-2"],
                    [2.5, "md:px-2.5"],
                    [3, "md:px-3"],
                    [3.5, "md:px-3.5"],
                    [4, "md:px-4"],
                    [5, "md:px-5"],
                    [6, "md:px-6"],
                    [7, "md:px-7"],
                    [8, "md:px-8"],
                    [9, "md:px-9"],
                    [10, "md:px-10"],
                    [11, "md:px-11"],
                    [12, "md:px-12"],
                    [14, "md:px-14"],
                    [16, "md:px-16"],
                    [20, "md:px-20"],
                    [24, "md:px-24"],
                    [28, "md:px-28"],
                    [32, "md:px-32"],
                    [36, "md:px-36"],
                    [40, "md:px-40"],
                    [44, "md:px-44"],
                    [48, "md:px-48"],
                    [52, "md:px-52"],
                    [56, "md:px-56"],
                    [60, "md:px-60"],
                    [64, "md:px-64"],
                    [72, "md:px-72"],
                    [80, "md:px-80"],
                    [96, "md:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:py-0"],
                    ["px", "md:py-px"],
                    [0.5, "md:py-0.5"],
                    [1, "md:py-1"],
                    [1.5, "md:py-1.5"],
                    [2, "md:py-2"],
                    [2.5, "md:py-2.5"],
                    [3, "md:py-3"],
                    [3.5, "md:py-3.5"],
                    [4, "md:py-4"],
                    [5, "md:py-5"],
                    [6, "md:py-6"],
                    [7, "md:py-7"],
                    [8, "md:py-8"],
                    [9, "md:py-9"],
                    [10, "md:py-10"],
                    [11, "md:py-11"],
                    [12, "md:py-12"],
                    [14, "md:py-14"],
                    [16, "md:py-16"],
                    [20, "md:py-20"],
                    [24, "md:py-24"],
                    [28, "md:py-28"],
                    [32, "md:py-32"],
                    [36, "md:py-36"],
                    [40, "md:py-40"],
                    [44, "md:py-44"],
                    [48, "md:py-48"],
                    [52, "md:py-52"],
                    [56, "md:py-56"],
                    [60, "md:py-60"],
                    [64, "md:py-64"],
                    [72, "md:py-72"],
                    [80, "md:py-80"],
                    [96, "md:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:px-0"],
                    ["px", "lg:px-px"],
                    [0.5, "lg:px-0.5"],
                    [1, "lg:px-1"],
                    [1.5, "lg:px-1.5"],
                    [2, "lg:px-2"],
                    [2.5, "lg:px-2.5"],
                    [3, "lg:px-3"],
                    [3.5, "lg:px-3.5"],
                    [4, "lg:px-4"],
                    [5, "lg:px-5"],
                    [6, "lg:px-6"],
                    [7, "lg:px-7"],
                    [8, "lg:px-8"],
                    [9, "lg:px-9"],
                    [10, "lg:px-10"],
                    [11, "lg:px-11"],
                    [12, "lg:px-12"],
                    [14, "lg:px-14"],
                    [16, "lg:px-16"],
                    [20, "lg:px-20"],
                    [24, "lg:px-24"],
                    [28, "lg:px-28"],
                    [32, "lg:px-32"],
                    [36, "lg:px-36"],
                    [40, "lg:px-40"],
                    [44, "lg:px-44"],
                    [48, "lg:px-48"],
                    [52, "lg:px-52"],
                    [56, "lg:px-56"],
                    [60, "lg:px-60"],
                    [64, "lg:px-64"],
                    [72, "lg:px-72"],
                    [80, "lg:px-80"],
                    [96, "lg:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:py-0"],
                    ["px", "lg:py-px"],
                    [0.5, "lg:py-0.5"],
                    [1, "lg:py-1"],
                    [1.5, "lg:py-1.5"],
                    [2, "lg:py-2"],
                    [2.5, "lg:py-2.5"],
                    [3, "lg:py-3"],
                    [3.5, "lg:py-3.5"],
                    [4, "lg:py-4"],
                    [5, "lg:py-5"],
                    [6, "lg:py-6"],
                    [7, "lg:py-7"],
                    [8, "lg:py-8"],
                    [9, "lg:py-9"],
                    [10, "lg:py-10"],
                    [11, "lg:py-11"],
                    [12, "lg:py-12"],
                    [14, "lg:py-14"],
                    [16, "lg:py-16"],
                    [20, "lg:py-20"],
                    [24, "lg:py-24"],
                    [28, "lg:py-28"],
                    [32, "lg:py-32"],
                    [36, "lg:py-36"],
                    [40, "lg:py-40"],
                    [44, "lg:py-44"],
                    [48, "lg:py-48"],
                    [52, "lg:py-52"],
                    [56, "lg:py-56"],
                    [60, "lg:py-60"],
                    [64, "lg:py-64"],
                    [72, "lg:py-72"],
                    [80, "lg:py-80"],
                    [96, "lg:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:px-0"],
                    ["px", "xl:px-px"],
                    [0.5, "xl:px-0.5"],
                    [1, "xl:px-1"],
                    [1.5, "xl:px-1.5"],
                    [2, "xl:px-2"],
                    [2.5, "xl:px-2.5"],
                    [3, "xl:px-3"],
                    [3.5, "xl:px-3.5"],
                    [4, "xl:px-4"],
                    [5, "xl:px-5"],
                    [6, "xl:px-6"],
                    [7, "xl:px-7"],
                    [8, "xl:px-8"],
                    [9, "xl:px-9"],
                    [10, "xl:px-10"],
                    [11, "xl:px-11"],
                    [12, "xl:px-12"],
                    [14, "xl:px-14"],
                    [16, "xl:px-16"],
                    [20, "xl:px-20"],
                    [24, "xl:px-24"],
                    [28, "xl:px-28"],
                    [32, "xl:px-32"],
                    [36, "xl:px-36"],
                    [40, "xl:px-40"],
                    [44, "xl:px-44"],
                    [48, "xl:px-48"],
                    [52, "xl:px-52"],
                    [56, "xl:px-56"],
                    [60, "xl:px-60"],
                    [64, "xl:px-64"],
                    [72, "xl:px-72"],
                    [80, "xl:px-80"],
                    [96, "xl:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:py-0"],
                    ["px", "xl:py-px"],
                    [0.5, "xl:py-0.5"],
                    [1, "xl:py-1"],
                    [1.5, "xl:py-1.5"],
                    [2, "xl:py-2"],
                    [2.5, "xl:py-2.5"],
                    [3, "xl:py-3"],
                    [3.5, "xl:py-3.5"],
                    [4, "xl:py-4"],
                    [5, "xl:py-5"],
                    [6, "xl:py-6"],
                    [7, "xl:py-7"],
                    [8, "xl:py-8"],
                    [9, "xl:py-9"],
                    [10, "xl:py-10"],
                    [11, "xl:py-11"],
                    [12, "xl:py-12"],
                    [14, "xl:py-14"],
                    [16, "xl:py-16"],
                    [20, "xl:py-20"],
                    [24, "xl:py-24"],
                    [28, "xl:py-28"],
                    [32, "xl:py-32"],
                    [36, "xl:py-36"],
                    [40, "xl:py-40"],
                    [44, "xl:py-44"],
                    [48, "xl:py-48"],
                    [52, "xl:py-52"],
                    [56, "xl:py-56"],
                    [60, "xl:py-60"],
                    [64, "xl:py-64"],
                    [72, "xl:py-72"],
                    [80, "xl:py-80"],
                    [96, "xl:py-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:open:px-0"],
                    ["px", "xs:open:px-px"],
                    [0.5, "xs:open:px-0.5"],
                    [1, "xs:open:px-1"],
                    [1.5, "xs:open:px-1.5"],
                    [2, "xs:open:px-2"],
                    [2.5, "xs:open:px-2.5"],
                    [3, "xs:open:px-3"],
                    [3.5, "xs:open:px-3.5"],
                    [4, "xs:open:px-4"],
                    [5, "xs:open:px-5"],
                    [6, "xs:open:px-6"],
                    [7, "xs:open:px-7"],
                    [8, "xs:open:px-8"],
                    [9, "xs:open:px-9"],
                    [10, "xs:open:px-10"],
                    [11, "xs:open:px-11"],
                    [12, "xs:open:px-12"],
                    [14, "xs:open:px-14"],
                    [16, "xs:open:px-16"],
                    [20, "xs:open:px-20"],
                    [24, "xs:open:px-24"],
                    [28, "xs:open:px-28"],
                    [32, "xs:open:px-32"],
                    [36, "xs:open:px-36"],
                    [40, "xs:open:px-40"],
                    [44, "xs:open:px-44"],
                    [48, "xs:open:px-48"],
                    [52, "xs:open:px-52"],
                    [56, "xs:open:px-56"],
                    [60, "xs:open:px-60"],
                    [64, "xs:open:px-64"],
                    [72, "xs:open:px-72"],
                    [80, "xs:open:px-80"],
                    [96, "xs:open:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:open:py-0"],
                    ["px", "xs:open:py-px"],
                    [0.5, "xs:open:py-0.5"],
                    [1, "xs:open:py-1"],
                    [1.5, "xs:open:py-1.5"],
                    [2, "xs:open:py-2"],
                    [2.5, "xs:open:py-2.5"],
                    [3, "xs:open:py-3"],
                    [3.5, "xs:open:py-3.5"],
                    [4, "xs:open:py-4"],
                    [5, "xs:open:py-5"],
                    [6, "xs:open:py-6"],
                    [7, "xs:open:py-7"],
                    [8, "xs:open:py-8"],
                    [9, "xs:open:py-9"],
                    [10, "xs:open:py-10"],
                    [11, "xs:open:py-11"],
                    [12, "xs:open:py-12"],
                    [14, "xs:open:py-14"],
                    [16, "xs:open:py-16"],
                    [20, "xs:open:py-20"],
                    [24, "xs:open:py-24"],
                    [28, "xs:open:py-28"],
                    [32, "xs:open:py-32"],
                    [36, "xs:open:py-36"],
                    [40, "xs:open:py-40"],
                    [44, "xs:open:py-44"],
                    [48, "xs:open:py-48"],
                    [52, "xs:open:py-52"],
                    [56, "xs:open:py-56"],
                    [60, "xs:open:py-60"],
                    [64, "xs:open:py-64"],
                    [72, "xs:open:py-72"],
                    [80, "xs:open:py-80"],
                    [96, "xs:open:py-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:open:px-0"],
                    ["px", "sm:open:px-px"],
                    [0.5, "sm:open:px-0.5"],
                    [1, "sm:open:px-1"],
                    [1.5, "sm:open:px-1.5"],
                    [2, "sm:open:px-2"],
                    [2.5, "sm:open:px-2.5"],
                    [3, "sm:open:px-3"],
                    [3.5, "sm:open:px-3.5"],
                    [4, "sm:open:px-4"],
                    [5, "sm:open:px-5"],
                    [6, "sm:open:px-6"],
                    [7, "sm:open:px-7"],
                    [8, "sm:open:px-8"],
                    [9, "sm:open:px-9"],
                    [10, "sm:open:px-10"],
                    [11, "sm:open:px-11"],
                    [12, "sm:open:px-12"],
                    [14, "sm:open:px-14"],
                    [16, "sm:open:px-16"],
                    [20, "sm:open:px-20"],
                    [24, "sm:open:px-24"],
                    [28, "sm:open:px-28"],
                    [32, "sm:open:px-32"],
                    [36, "sm:open:px-36"],
                    [40, "sm:open:px-40"],
                    [44, "sm:open:px-44"],
                    [48, "sm:open:px-48"],
                    [52, "sm:open:px-52"],
                    [56, "sm:open:px-56"],
                    [60, "sm:open:px-60"],
                    [64, "sm:open:px-64"],
                    [72, "sm:open:px-72"],
                    [80, "sm:open:px-80"],
                    [96, "sm:open:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:open:py-0"],
                    ["px", "sm:open:py-px"],
                    [0.5, "sm:open:py-0.5"],
                    [1, "sm:open:py-1"],
                    [1.5, "sm:open:py-1.5"],
                    [2, "sm:open:py-2"],
                    [2.5, "sm:open:py-2.5"],
                    [3, "sm:open:py-3"],
                    [3.5, "sm:open:py-3.5"],
                    [4, "sm:open:py-4"],
                    [5, "sm:open:py-5"],
                    [6, "sm:open:py-6"],
                    [7, "sm:open:py-7"],
                    [8, "sm:open:py-8"],
                    [9, "sm:open:py-9"],
                    [10, "sm:open:py-10"],
                    [11, "sm:open:py-11"],
                    [12, "sm:open:py-12"],
                    [14, "sm:open:py-14"],
                    [16, "sm:open:py-16"],
                    [20, "sm:open:py-20"],
                    [24, "sm:open:py-24"],
                    [28, "sm:open:py-28"],
                    [32, "sm:open:py-32"],
                    [36, "sm:open:py-36"],
                    [40, "sm:open:py-40"],
                    [44, "sm:open:py-44"],
                    [48, "sm:open:py-48"],
                    [52, "sm:open:py-52"],
                    [56, "sm:open:py-56"],
                    [60, "sm:open:py-60"],
                    [64, "sm:open:py-64"],
                    [72, "sm:open:py-72"],
                    [80, "sm:open:py-80"],
                    [96, "sm:open:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:open:px-0"],
                    ["px", "md:open:px-px"],
                    [0.5, "md:open:px-0.5"],
                    [1, "md:open:px-1"],
                    [1.5, "md:open:px-1.5"],
                    [2, "md:open:px-2"],
                    [2.5, "md:open:px-2.5"],
                    [3, "md:open:px-3"],
                    [3.5, "md:open:px-3.5"],
                    [4, "md:open:px-4"],
                    [5, "md:open:px-5"],
                    [6, "md:open:px-6"],
                    [7, "md:open:px-7"],
                    [8, "md:open:px-8"],
                    [9, "md:open:px-9"],
                    [10, "md:open:px-10"],
                    [11, "md:open:px-11"],
                    [12, "md:open:px-12"],
                    [14, "md:open:px-14"],
                    [16, "md:open:px-16"],
                    [20, "md:open:px-20"],
                    [24, "md:open:px-24"],
                    [28, "md:open:px-28"],
                    [32, "md:open:px-32"],
                    [36, "md:open:px-36"],
                    [40, "md:open:px-40"],
                    [44, "md:open:px-44"],
                    [48, "md:open:px-48"],
                    [52, "md:open:px-52"],
                    [56, "md:open:px-56"],
                    [60, "md:open:px-60"],
                    [64, "md:open:px-64"],
                    [72, "md:open:px-72"],
                    [80, "md:open:px-80"],
                    [96, "md:open:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:open:py-0"],
                    ["px", "md:open:py-px"],
                    [0.5, "md:open:py-0.5"],
                    [1, "md:open:py-1"],
                    [1.5, "md:open:py-1.5"],
                    [2, "md:open:py-2"],
                    [2.5, "md:open:py-2.5"],
                    [3, "md:open:py-3"],
                    [3.5, "md:open:py-3.5"],
                    [4, "md:open:py-4"],
                    [5, "md:open:py-5"],
                    [6, "md:open:py-6"],
                    [7, "md:open:py-7"],
                    [8, "md:open:py-8"],
                    [9, "md:open:py-9"],
                    [10, "md:open:py-10"],
                    [11, "md:open:py-11"],
                    [12, "md:open:py-12"],
                    [14, "md:open:py-14"],
                    [16, "md:open:py-16"],
                    [20, "md:open:py-20"],
                    [24, "md:open:py-24"],
                    [28, "md:open:py-28"],
                    [32, "md:open:py-32"],
                    [36, "md:open:py-36"],
                    [40, "md:open:py-40"],
                    [44, "md:open:py-44"],
                    [48, "md:open:py-48"],
                    [52, "md:open:py-52"],
                    [56, "md:open:py-56"],
                    [60, "md:open:py-60"],
                    [64, "md:open:py-64"],
                    [72, "md:open:py-72"],
                    [80, "md:open:py-80"],
                    [96, "md:open:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:open:px-0"],
                    ["px", "lg:open:px-px"],
                    [0.5, "lg:open:px-0.5"],
                    [1, "lg:open:px-1"],
                    [1.5, "lg:open:px-1.5"],
                    [2, "lg:open:px-2"],
                    [2.5, "lg:open:px-2.5"],
                    [3, "lg:open:px-3"],
                    [3.5, "lg:open:px-3.5"],
                    [4, "lg:open:px-4"],
                    [5, "lg:open:px-5"],
                    [6, "lg:open:px-6"],
                    [7, "lg:open:px-7"],
                    [8, "lg:open:px-8"],
                    [9, "lg:open:px-9"],
                    [10, "lg:open:px-10"],
                    [11, "lg:open:px-11"],
                    [12, "lg:open:px-12"],
                    [14, "lg:open:px-14"],
                    [16, "lg:open:px-16"],
                    [20, "lg:open:px-20"],
                    [24, "lg:open:px-24"],
                    [28, "lg:open:px-28"],
                    [32, "lg:open:px-32"],
                    [36, "lg:open:px-36"],
                    [40, "lg:open:px-40"],
                    [44, "lg:open:px-44"],
                    [48, "lg:open:px-48"],
                    [52, "lg:open:px-52"],
                    [56, "lg:open:px-56"],
                    [60, "lg:open:px-60"],
                    [64, "lg:open:px-64"],
                    [72, "lg:open:px-72"],
                    [80, "lg:open:px-80"],
                    [96, "lg:open:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:open:py-0"],
                    ["px", "lg:open:py-px"],
                    [0.5, "lg:open:py-0.5"],
                    [1, "lg:open:py-1"],
                    [1.5, "lg:open:py-1.5"],
                    [2, "lg:open:py-2"],
                    [2.5, "lg:open:py-2.5"],
                    [3, "lg:open:py-3"],
                    [3.5, "lg:open:py-3.5"],
                    [4, "lg:open:py-4"],
                    [5, "lg:open:py-5"],
                    [6, "lg:open:py-6"],
                    [7, "lg:open:py-7"],
                    [8, "lg:open:py-8"],
                    [9, "lg:open:py-9"],
                    [10, "lg:open:py-10"],
                    [11, "lg:open:py-11"],
                    [12, "lg:open:py-12"],
                    [14, "lg:open:py-14"],
                    [16, "lg:open:py-16"],
                    [20, "lg:open:py-20"],
                    [24, "lg:open:py-24"],
                    [28, "lg:open:py-28"],
                    [32, "lg:open:py-32"],
                    [36, "lg:open:py-36"],
                    [40, "lg:open:py-40"],
                    [44, "lg:open:py-44"],
                    [48, "lg:open:py-48"],
                    [52, "lg:open:py-52"],
                    [56, "lg:open:py-56"],
                    [60, "lg:open:py-60"],
                    [64, "lg:open:py-64"],
                    [72, "lg:open:py-72"],
                    [80, "lg:open:py-80"],
                    [96, "lg:open:py-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:open:px-0"],
                    ["px", "xl:open:px-px"],
                    [0.5, "xl:open:px-0.5"],
                    [1, "xl:open:px-1"],
                    [1.5, "xl:open:px-1.5"],
                    [2, "xl:open:px-2"],
                    [2.5, "xl:open:px-2.5"],
                    [3, "xl:open:px-3"],
                    [3.5, "xl:open:px-3.5"],
                    [4, "xl:open:px-4"],
                    [5, "xl:open:px-5"],
                    [6, "xl:open:px-6"],
                    [7, "xl:open:px-7"],
                    [8, "xl:open:px-8"],
                    [9, "xl:open:px-9"],
                    [10, "xl:open:px-10"],
                    [11, "xl:open:px-11"],
                    [12, "xl:open:px-12"],
                    [14, "xl:open:px-14"],
                    [16, "xl:open:px-16"],
                    [20, "xl:open:px-20"],
                    [24, "xl:open:px-24"],
                    [28, "xl:open:px-28"],
                    [32, "xl:open:px-32"],
                    [36, "xl:open:px-36"],
                    [40, "xl:open:px-40"],
                    [44, "xl:open:px-44"],
                    [48, "xl:open:px-48"],
                    [52, "xl:open:px-52"],
                    [56, "xl:open:px-56"],
                    [60, "xl:open:px-60"],
                    [64, "xl:open:px-64"],
                    [72, "xl:open:px-72"],
                    [80, "xl:open:px-80"],
                    [96, "xl:open:px-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:open:py-0"],
                    ["px", "xl:open:py-px"],
                    [0.5, "xl:open:py-0.5"],
                    [1, "xl:open:py-1"],
                    [1.5, "xl:open:py-1.5"],
                    [2, "xl:open:py-2"],
                    [2.5, "xl:open:py-2.5"],
                    [3, "xl:open:py-3"],
                    [3.5, "xl:open:py-3.5"],
                    [4, "xl:open:py-4"],
                    [5, "xl:open:py-5"],
                    [6, "xl:open:py-6"],
                    [7, "xl:open:py-7"],
                    [8, "xl:open:py-8"],
                    [9, "xl:open:py-9"],
                    [10, "xl:open:py-10"],
                    [11, "xl:open:py-11"],
                    [12, "xl:open:py-12"],
                    [14, "xl:open:py-14"],
                    [16, "xl:open:py-16"],
                    [20, "xl:open:py-20"],
                    [24, "xl:open:py-24"],
                    [28, "xl:open:py-28"],
                    [32, "xl:open:py-32"],
                    [36, "xl:open:py-36"],
                    [40, "xl:open:py-40"],
                    [44, "xl:open:py-44"],
                    [48, "xl:open:py-48"],
                    [52, "xl:open:py-52"],
                    [56, "xl:open:py-56"],
                    [60, "xl:open:py-60"],
                    [64, "xl:open:py-64"],
                    [72, "xl:open:py-72"],
                    [80, "xl:open:py-80"],
                    [96, "xl:open:py-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
