import {
  AxisMapping,
  Breakpoints,
  CSSSelector,
  FlexSpacing,
  SideMapping,
} from "../../types";
import { PaddingAxisInsideBreakpoints } from "./PaddingAxisInsideBreakpoints";
import { PaddingSidesInsideBreakpoints } from "./PaddingSidesInsideBreakpoints";
import { Axleable } from "../../Entities/Axleable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { Sideable } from "../../Entities/Sideable";
import { DefaultValue } from "../DefaultValue";

export class PaddingBreakpoints
  extends Axleable<
    Map<Breakpoints, Map<FlexSpacing, string>>,
    Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
  >
  implements
    Sideable<Map<Breakpoints, Map<SideMapping, Map<FlexSpacing, string>>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexSpacing, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new PaddingClassesMapping();
    return new PaddingBreakpoints(classesMapping, selector);
  }

  public axis() {
    return PaddingAxisInsideBreakpoints.create(this.cssSelector);
  }

  public sides() {
    return PaddingSidesInsideBreakpoints.create(this.cssSelector);
  }

  public write(breakpoint: Breakpoints, spacing: FlexSpacing) {
    return this.getClassName(breakpoint, spacing);
  }
}

class PaddingClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexSpacing, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexSpacing, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexSpacing, string>>(
      "xs",
      new Map<FlexSpacing, string>([
        [0, "xs:p-0"],
        ["px", "xs:p-px"],
        [0.5, "xs:p-0.5"],
        [1, "xs:p-1"],
        [1.5, "xs:p-1.5"],
        [2, "xs:p-2"],
        [2.5, "xs:p-2.5"],
        [3, "xs:p-3"],
        [3.5, "xs:p-3.5"],
        [4, "xs:p-4"],
        [5, "xs:p-5"],
        [6, "xs:p-6"],
        [7, "xs:p-7"],
        [8, "xs:p-8"],
        [9, "xs:p-9"],
        [10, "xs:p-10"],
        [11, "xs:p-11"],
        [12, "xs:p-12"],
        [14, "xs:p-14"],
        [16, "xs:p-16"],
        [20, "xs:p-20"],
        [24, "xs:p-24"],
        [28, "xs:p-28"],
        [32, "xs:p-32"],
        [36, "xs:p-36"],
        [40, "xs:p-40"],
        [44, "xs:p-44"],
        [48, "xs:p-48"],
        [52, "xs:p-52"],
        [56, "xs:p-56"],
        [60, "xs:p-60"],
        [64, "xs:p-64"],
        [72, "xs:p-72"],
        [80, "xs:p-80"],
        [96, "xs:p-96"],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexSpacing, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:active:p-0"],
                ["px", "xs:active:p-px"],
                [0.5, "xs:active:p-0.5"],
                [1, "xs:active:p-1"],
                [1.5, "xs:active:p-1.5"],
                [2, "xs:active:p-2"],
                [2.5, "xs:active:p-2.5"],
                [3, "xs:active:p-3"],
                [3.5, "xs:active:p-3.5"],
                [4, "xs:active:p-4"],
                [5, "xs:active:p-5"],
                [6, "xs:active:p-6"],
                [7, "xs:active:p-7"],
                [8, "xs:active:p-8"],
                [9, "xs:active:p-9"],
                [10, "xs:active:p-10"],
                [11, "xs:active:p-11"],
                [12, "xs:active:p-12"],
                [14, "xs:active:p-14"],
                [16, "xs:active:p-16"],
                [20, "xs:active:p-20"],
                [24, "xs:active:p-24"],
                [28, "xs:active:p-28"],
                [32, "xs:active:p-32"],
                [36, "xs:active:p-36"],
                [40, "xs:active:p-40"],
                [44, "xs:active:p-44"],
                [48, "xs:active:p-48"],
                [52, "xs:active:p-52"],
                [56, "xs:active:p-56"],
                [60, "xs:active:p-60"],
                [64, "xs:active:p-64"],
                [72, "xs:active:p-72"],
                [80, "xs:active:p-80"],
                [96, "xs:active:p-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:active:p-0"],
                ["px", "sm:active:p-px"],
                [0.5, "sm:active:p-0.5"],
                [1, "sm:active:p-1"],
                [1.5, "sm:active:p-1.5"],
                [2, "sm:active:p-2"],
                [2.5, "sm:active:p-2.5"],
                [3, "sm:active:p-3"],
                [3.5, "sm:active:p-3.5"],
                [4, "sm:active:p-4"],
                [5, "sm:active:p-5"],
                [6, "sm:active:p-6"],
                [7, "sm:active:p-7"],
                [8, "sm:active:p-8"],
                [9, "sm:active:p-9"],
                [10, "sm:active:p-10"],
                [11, "sm:active:p-11"],
                [12, "sm:active:p-12"],
                [14, "sm:active:p-14"],
                [16, "sm:active:p-16"],
                [20, "sm:active:p-20"],
                [24, "sm:active:p-24"],
                [28, "sm:active:p-28"],
                [32, "sm:active:p-32"],
                [36, "sm:active:p-36"],
                [40, "sm:active:p-40"],
                [44, "sm:active:p-44"],
                [48, "sm:active:p-48"],
                [52, "sm:active:p-52"],
                [56, "sm:active:p-56"],
                [60, "sm:active:p-60"],
                [64, "sm:active:p-64"],
                [72, "sm:active:p-72"],
                [80, "sm:active:p-80"],
                [96, "sm:active:p-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:active:p-0"],
                ["px", "md:active:p-px"],
                [0.5, "md:active:p-0.5"],
                [1, "md:active:p-1"],
                [1.5, "md:active:p-1.5"],
                [2, "md:active:p-2"],
                [2.5, "md:active:p-2.5"],
                [3, "md:active:p-3"],
                [3.5, "md:active:p-3.5"],
                [4, "md:active:p-4"],
                [5, "md:active:p-5"],
                [6, "md:active:p-6"],
                [7, "md:active:p-7"],
                [8, "md:active:p-8"],
                [9, "md:active:p-9"],
                [10, "md:active:p-10"],
                [11, "md:active:p-11"],
                [12, "md:active:p-12"],
                [14, "md:active:p-14"],
                [16, "md:active:p-16"],
                [20, "md:active:p-20"],
                [24, "md:active:p-24"],
                [28, "md:active:p-28"],
                [32, "md:active:p-32"],
                [36, "md:active:p-36"],
                [40, "md:active:p-40"],
                [44, "md:active:p-44"],
                [48, "md:active:p-48"],
                [52, "md:active:p-52"],
                [56, "md:active:p-56"],
                [60, "md:active:p-60"],
                [64, "md:active:p-64"],
                [72, "md:active:p-72"],
                [80, "md:active:p-80"],
                [96, "md:active:p-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:active:p-0"],
                ["px", "lg:active:p-px"],
                [0.5, "lg:active:p-0.5"],
                [1, "lg:active:p-1"],
                [1.5, "lg:active:p-1.5"],
                [2, "lg:active:p-2"],
                [2.5, "lg:active:p-2.5"],
                [3, "lg:active:p-3"],
                [3.5, "lg:active:p-3.5"],
                [4, "lg:active:p-4"],
                [5, "lg:active:p-5"],
                [6, "lg:active:p-6"],
                [7, "lg:active:p-7"],
                [8, "lg:active:p-8"],
                [9, "lg:active:p-9"],
                [10, "lg:active:p-10"],
                [11, "lg:active:p-11"],
                [12, "lg:active:p-12"],
                [14, "lg:active:p-14"],
                [16, "lg:active:p-16"],
                [20, "lg:active:p-20"],
                [24, "lg:active:p-24"],
                [28, "lg:active:p-28"],
                [32, "lg:active:p-32"],
                [36, "lg:active:p-36"],
                [40, "lg:active:p-40"],
                [44, "lg:active:p-44"],
                [48, "lg:active:p-48"],
                [52, "lg:active:p-52"],
                [56, "lg:active:p-56"],
                [60, "lg:active:p-60"],
                [64, "lg:active:p-64"],
                [72, "lg:active:p-72"],
                [80, "lg:active:p-80"],
                [96, "lg:active:p-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:active:p-0"],
                ["px", "xl:active:p-px"],
                [0.5, "xl:active:p-0.5"],
                [1, "xl:active:p-1"],
                [1.5, "xl:active:p-1.5"],
                [2, "xl:active:p-2"],
                [2.5, "xl:active:p-2.5"],
                [3, "xl:active:p-3"],
                [3.5, "xl:active:p-3.5"],
                [4, "xl:active:p-4"],
                [5, "xl:active:p-5"],
                [6, "xl:active:p-6"],
                [7, "xl:active:p-7"],
                [8, "xl:active:p-8"],
                [9, "xl:active:p-9"],
                [10, "xl:active:p-10"],
                [11, "xl:active:p-11"],
                [12, "xl:active:p-12"],
                [14, "xl:active:p-14"],
                [16, "xl:active:p-16"],
                [20, "xl:active:p-20"],
                [24, "xl:active:p-24"],
                [28, "xl:active:p-28"],
                [32, "xl:active:p-32"],
                [36, "xl:active:p-36"],
                [40, "xl:active:p-40"],
                [44, "xl:active:p-44"],
                [48, "xl:active:p-48"],
                [52, "xl:active:p-52"],
                [56, "xl:active:p-56"],
                [60, "xl:active:p-60"],
                [64, "xl:active:p-64"],
                [72, "xl:active:p-72"],
                [80, "xl:active:p-80"],
                [96, "xl:active:p-96"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:disabled:p-0"],
                ["px", "xs:disabled:p-px"],
                [0.5, "xs:disabled:p-0.5"],
                [1, "xs:disabled:p-1"],
                [1.5, "xs:disabled:p-1.5"],
                [2, "xs:disabled:p-2"],
                [2.5, "xs:disabled:p-2.5"],
                [3, "xs:disabled:p-3"],
                [3.5, "xs:disabled:p-3.5"],
                [4, "xs:disabled:p-4"],
                [5, "xs:disabled:p-5"],
                [6, "xs:disabled:p-6"],
                [7, "xs:disabled:p-7"],
                [8, "xs:disabled:p-8"],
                [9, "xs:disabled:p-9"],
                [10, "xs:disabled:p-10"],
                [11, "xs:disabled:p-11"],
                [12, "xs:disabled:p-12"],
                [14, "xs:disabled:p-14"],
                [16, "xs:disabled:p-16"],
                [20, "xs:disabled:p-20"],
                [24, "xs:disabled:p-24"],
                [28, "xs:disabled:p-28"],
                [32, "xs:disabled:p-32"],
                [36, "xs:disabled:p-36"],
                [40, "xs:disabled:p-40"],
                [44, "xs:disabled:p-44"],
                [48, "xs:disabled:p-48"],
                [52, "xs:disabled:p-52"],
                [56, "xs:disabled:p-56"],
                [60, "xs:disabled:p-60"],
                [64, "xs:disabled:p-64"],
                [72, "xs:disabled:p-72"],
                [80, "xs:disabled:p-80"],
                [96, "xs:disabled:p-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:disabled:p-0"],
                ["px", "sm:disabled:p-px"],
                [0.5, "sm:disabled:p-0.5"],
                [1, "sm:disabled:p-1"],
                [1.5, "sm:disabled:p-1.5"],
                [2, "sm:disabled:p-2"],
                [2.5, "sm:disabled:p-2.5"],
                [3, "sm:disabled:p-3"],
                [3.5, "sm:disabled:p-3.5"],
                [4, "sm:disabled:p-4"],
                [5, "sm:disabled:p-5"],
                [6, "sm:disabled:p-6"],
                [7, "sm:disabled:p-7"],
                [8, "sm:disabled:p-8"],
                [9, "sm:disabled:p-9"],
                [10, "sm:disabled:p-10"],
                [11, "sm:disabled:p-11"],
                [12, "sm:disabled:p-12"],
                [14, "sm:disabled:p-14"],
                [16, "sm:disabled:p-16"],
                [20, "sm:disabled:p-20"],
                [24, "sm:disabled:p-24"],
                [28, "sm:disabled:p-28"],
                [32, "sm:disabled:p-32"],
                [36, "sm:disabled:p-36"],
                [40, "sm:disabled:p-40"],
                [44, "sm:disabled:p-44"],
                [48, "sm:disabled:p-48"],
                [52, "sm:disabled:p-52"],
                [56, "sm:disabled:p-56"],
                [60, "sm:disabled:p-60"],
                [64, "sm:disabled:p-64"],
                [72, "sm:disabled:p-72"],
                [80, "sm:disabled:p-80"],
                [96, "sm:disabled:p-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:disabled:p-0"],
                ["px", "md:disabled:p-px"],
                [0.5, "md:disabled:p-0.5"],
                [1, "md:disabled:p-1"],
                [1.5, "md:disabled:p-1.5"],
                [2, "md:disabled:p-2"],
                [2.5, "md:disabled:p-2.5"],
                [3, "md:disabled:p-3"],
                [3.5, "md:disabled:p-3.5"],
                [4, "md:disabled:p-4"],
                [5, "md:disabled:p-5"],
                [6, "md:disabled:p-6"],
                [7, "md:disabled:p-7"],
                [8, "md:disabled:p-8"],
                [9, "md:disabled:p-9"],
                [10, "md:disabled:p-10"],
                [11, "md:disabled:p-11"],
                [12, "md:disabled:p-12"],
                [14, "md:disabled:p-14"],
                [16, "md:disabled:p-16"],
                [20, "md:disabled:p-20"],
                [24, "md:disabled:p-24"],
                [28, "md:disabled:p-28"],
                [32, "md:disabled:p-32"],
                [36, "md:disabled:p-36"],
                [40, "md:disabled:p-40"],
                [44, "md:disabled:p-44"],
                [48, "md:disabled:p-48"],
                [52, "md:disabled:p-52"],
                [56, "md:disabled:p-56"],
                [60, "md:disabled:p-60"],
                [64, "md:disabled:p-64"],
                [72, "md:disabled:p-72"],
                [80, "md:disabled:p-80"],
                [96, "md:disabled:p-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:disabled:p-0"],
                ["px", "lg:disabled:p-px"],
                [0.5, "lg:disabled:p-0.5"],
                [1, "lg:disabled:p-1"],
                [1.5, "lg:disabled:p-1.5"],
                [2, "lg:disabled:p-2"],
                [2.5, "lg:disabled:p-2.5"],
                [3, "lg:disabled:p-3"],
                [3.5, "lg:disabled:p-3.5"],
                [4, "lg:disabled:p-4"],
                [5, "lg:disabled:p-5"],
                [6, "lg:disabled:p-6"],
                [7, "lg:disabled:p-7"],
                [8, "lg:disabled:p-8"],
                [9, "lg:disabled:p-9"],
                [10, "lg:disabled:p-10"],
                [11, "lg:disabled:p-11"],
                [12, "lg:disabled:p-12"],
                [14, "lg:disabled:p-14"],
                [16, "lg:disabled:p-16"],
                [20, "lg:disabled:p-20"],
                [24, "lg:disabled:p-24"],
                [28, "lg:disabled:p-28"],
                [32, "lg:disabled:p-32"],
                [36, "lg:disabled:p-36"],
                [40, "lg:disabled:p-40"],
                [44, "lg:disabled:p-44"],
                [48, "lg:disabled:p-48"],
                [52, "lg:disabled:p-52"],
                [56, "lg:disabled:p-56"],
                [60, "lg:disabled:p-60"],
                [64, "lg:disabled:p-64"],
                [72, "lg:disabled:p-72"],
                [80, "lg:disabled:p-80"],
                [96, "lg:disabled:p-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:disabled:p-0"],
                ["px", "xl:disabled:p-px"],
                [0.5, "xl:disabled:p-0.5"],
                [1, "xl:disabled:p-1"],
                [1.5, "xl:disabled:p-1.5"],
                [2, "xl:disabled:p-2"],
                [2.5, "xl:disabled:p-2.5"],
                [3, "xl:disabled:p-3"],
                [3.5, "xl:disabled:p-3.5"],
                [4, "xl:disabled:p-4"],
                [5, "xl:disabled:p-5"],
                [6, "xl:disabled:p-6"],
                [7, "xl:disabled:p-7"],
                [8, "xl:disabled:p-8"],
                [9, "xl:disabled:p-9"],
                [10, "xl:disabled:p-10"],
                [11, "xl:disabled:p-11"],
                [12, "xl:disabled:p-12"],
                [14, "xl:disabled:p-14"],
                [16, "xl:disabled:p-16"],
                [20, "xl:disabled:p-20"],
                [24, "xl:disabled:p-24"],
                [28, "xl:disabled:p-28"],
                [32, "xl:disabled:p-32"],
                [36, "xl:disabled:p-36"],
                [40, "xl:disabled:p-40"],
                [44, "xl:disabled:p-44"],
                [48, "xl:disabled:p-48"],
                [52, "xl:disabled:p-52"],
                [56, "xl:disabled:p-56"],
                [60, "xl:disabled:p-60"],
                [64, "xl:disabled:p-64"],
                [72, "xl:disabled:p-72"],
                [80, "xl:disabled:p-80"],
                [96, "xl:disabled:p-96"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:hover:p-0"],
                ["px", "xs:hover:p-px"],
                [0.5, "xs:hover:p-0.5"],
                [1, "xs:hover:p-1"],
                [1.5, "xs:hover:p-1.5"],
                [2, "xs:hover:p-2"],
                [2.5, "xs:hover:p-2.5"],
                [3, "xs:hover:p-3"],
                [3.5, "xs:hover:p-3.5"],
                [4, "xs:hover:p-4"],
                [5, "xs:hover:p-5"],
                [6, "xs:hover:p-6"],
                [7, "xs:hover:p-7"],
                [8, "xs:hover:p-8"],
                [9, "xs:hover:p-9"],
                [10, "xs:hover:p-10"],
                [11, "xs:hover:p-11"],
                [12, "xs:hover:p-12"],
                [14, "xs:hover:p-14"],
                [16, "xs:hover:p-16"],
                [20, "xs:hover:p-20"],
                [24, "xs:hover:p-24"],
                [28, "xs:hover:p-28"],
                [32, "xs:hover:p-32"],
                [36, "xs:hover:p-36"],
                [40, "xs:hover:p-40"],
                [44, "xs:hover:p-44"],
                [48, "xs:hover:p-48"],
                [52, "xs:hover:p-52"],
                [56, "xs:hover:p-56"],
                [60, "xs:hover:p-60"],
                [64, "xs:hover:p-64"],
                [72, "xs:hover:p-72"],
                [80, "xs:hover:p-80"],
                [96, "xs:hover:p-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:hover:p-0"],
                ["px", "sm:hover:p-px"],
                [0.5, "sm:hover:p-0.5"],
                [1, "sm:hover:p-1"],
                [1.5, "sm:hover:p-1.5"],
                [2, "sm:hover:p-2"],
                [2.5, "sm:hover:p-2.5"],
                [3, "sm:hover:p-3"],
                [3.5, "sm:hover:p-3.5"],
                [4, "sm:hover:p-4"],
                [5, "sm:hover:p-5"],
                [6, "sm:hover:p-6"],
                [7, "sm:hover:p-7"],
                [8, "sm:hover:p-8"],
                [9, "sm:hover:p-9"],
                [10, "sm:hover:p-10"],
                [11, "sm:hover:p-11"],
                [12, "sm:hover:p-12"],
                [14, "sm:hover:p-14"],
                [16, "sm:hover:p-16"],
                [20, "sm:hover:p-20"],
                [24, "sm:hover:p-24"],
                [28, "sm:hover:p-28"],
                [32, "sm:hover:p-32"],
                [36, "sm:hover:p-36"],
                [40, "sm:hover:p-40"],
                [44, "sm:hover:p-44"],
                [48, "sm:hover:p-48"],
                [52, "sm:hover:p-52"],
                [56, "sm:hover:p-56"],
                [60, "sm:hover:p-60"],
                [64, "sm:hover:p-64"],
                [72, "sm:hover:p-72"],
                [80, "sm:hover:p-80"],
                [96, "sm:hover:p-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:hover:p-0"],
                ["px", "md:hover:p-px"],
                [0.5, "md:hover:p-0.5"],
                [1, "md:hover:p-1"],
                [1.5, "md:hover:p-1.5"],
                [2, "md:hover:p-2"],
                [2.5, "md:hover:p-2.5"],
                [3, "md:hover:p-3"],
                [3.5, "md:hover:p-3.5"],
                [4, "md:hover:p-4"],
                [5, "md:hover:p-5"],
                [6, "md:hover:p-6"],
                [7, "md:hover:p-7"],
                [8, "md:hover:p-8"],
                [9, "md:hover:p-9"],
                [10, "md:hover:p-10"],
                [11, "md:hover:p-11"],
                [12, "md:hover:p-12"],
                [14, "md:hover:p-14"],
                [16, "md:hover:p-16"],
                [20, "md:hover:p-20"],
                [24, "md:hover:p-24"],
                [28, "md:hover:p-28"],
                [32, "md:hover:p-32"],
                [36, "md:hover:p-36"],
                [40, "md:hover:p-40"],
                [44, "md:hover:p-44"],
                [48, "md:hover:p-48"],
                [52, "md:hover:p-52"],
                [56, "md:hover:p-56"],
                [60, "md:hover:p-60"],
                [64, "md:hover:p-64"],
                [72, "md:hover:p-72"],
                [80, "md:hover:p-80"],
                [96, "md:hover:p-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:hover:p-0"],
                ["px", "lg:hover:p-px"],
                [0.5, "lg:hover:p-0.5"],
                [1, "lg:hover:p-1"],
                [1.5, "lg:hover:p-1.5"],
                [2, "lg:hover:p-2"],
                [2.5, "lg:hover:p-2.5"],
                [3, "lg:hover:p-3"],
                [3.5, "lg:hover:p-3.5"],
                [4, "lg:hover:p-4"],
                [5, "lg:hover:p-5"],
                [6, "lg:hover:p-6"],
                [7, "lg:hover:p-7"],
                [8, "lg:hover:p-8"],
                [9, "lg:hover:p-9"],
                [10, "lg:hover:p-10"],
                [11, "lg:hover:p-11"],
                [12, "lg:hover:p-12"],
                [14, "lg:hover:p-14"],
                [16, "lg:hover:p-16"],
                [20, "lg:hover:p-20"],
                [24, "lg:hover:p-24"],
                [28, "lg:hover:p-28"],
                [32, "lg:hover:p-32"],
                [36, "lg:hover:p-36"],
                [40, "lg:hover:p-40"],
                [44, "lg:hover:p-44"],
                [48, "lg:hover:p-48"],
                [52, "lg:hover:p-52"],
                [56, "lg:hover:p-56"],
                [60, "lg:hover:p-60"],
                [64, "lg:hover:p-64"],
                [72, "lg:hover:p-72"],
                [80, "lg:hover:p-80"],
                [96, "lg:hover:p-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:hover:p-0"],
                ["px", "xl:hover:p-px"],
                [0.5, "xl:hover:p-0.5"],
                [1, "xl:hover:p-1"],
                [1.5, "xl:hover:p-1.5"],
                [2, "xl:hover:p-2"],
                [2.5, "xl:hover:p-2.5"],
                [3, "xl:hover:p-3"],
                [3.5, "xl:hover:p-3.5"],
                [4, "xl:hover:p-4"],
                [5, "xl:hover:p-5"],
                [6, "xl:hover:p-6"],
                [7, "xl:hover:p-7"],
                [8, "xl:hover:p-8"],
                [9, "xl:hover:p-9"],
                [10, "xl:hover:p-10"],
                [11, "xl:hover:p-11"],
                [12, "xl:hover:p-12"],
                [14, "xl:hover:p-14"],
                [16, "xl:hover:p-16"],
                [20, "xl:hover:p-20"],
                [24, "xl:hover:p-24"],
                [28, "xl:hover:p-28"],
                [32, "xl:hover:p-32"],
                [36, "xl:hover:p-36"],
                [40, "xl:hover:p-40"],
                [44, "xl:hover:p-44"],
                [48, "xl:hover:p-48"],
                [52, "xl:hover:p-52"],
                [56, "xl:hover:p-56"],
                [60, "xl:hover:p-60"],
                [64, "xl:hover:p-64"],
                [72, "xl:hover:p-72"],
                [80, "xl:hover:p-80"],
                [96, "xl:hover:p-96"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:p-0"],
                ["px", "xs:p-px"],
                [0.5, "xs:p-0.5"],
                [1, "xs:p-1"],
                [1.5, "xs:p-1.5"],
                [2, "xs:p-2"],
                [2.5, "xs:p-2.5"],
                [3, "xs:p-3"],
                [3.5, "xs:p-3.5"],
                [4, "xs:p-4"],
                [5, "xs:p-5"],
                [6, "xs:p-6"],
                [7, "xs:p-7"],
                [8, "xs:p-8"],
                [9, "xs:p-9"],
                [10, "xs:p-10"],
                [11, "xs:p-11"],
                [12, "xs:p-12"],
                [14, "xs:p-14"],
                [16, "xs:p-16"],
                [20, "xs:p-20"],
                [24, "xs:p-24"],
                [28, "xs:p-28"],
                [32, "xs:p-32"],
                [36, "xs:p-36"],
                [40, "xs:p-40"],
                [44, "xs:p-44"],
                [48, "xs:p-48"],
                [52, "xs:p-52"],
                [56, "xs:p-56"],
                [60, "xs:p-60"],
                [64, "xs:p-64"],
                [72, "xs:p-72"],
                [80, "xs:p-80"],
                [96, "xs:p-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:p-0"],
                ["px", "sm:p-px"],
                [0.5, "sm:p-0.5"],
                [1, "sm:p-1"],
                [1.5, "sm:p-1.5"],
                [2, "sm:p-2"],
                [2.5, "sm:p-2.5"],
                [3, "sm:p-3"],
                [3.5, "sm:p-3.5"],
                [4, "sm:p-4"],
                [5, "sm:p-5"],
                [6, "sm:p-6"],
                [7, "sm:p-7"],
                [8, "sm:p-8"],
                [9, "sm:p-9"],
                [10, "sm:p-10"],
                [11, "sm:p-11"],
                [12, "sm:p-12"],
                [14, "sm:p-14"],
                [16, "sm:p-16"],
                [20, "sm:p-20"],
                [24, "sm:p-24"],
                [28, "sm:p-28"],
                [32, "sm:p-32"],
                [36, "sm:p-36"],
                [40, "sm:p-40"],
                [44, "sm:p-44"],
                [48, "sm:p-48"],
                [52, "sm:p-52"],
                [56, "sm:p-56"],
                [60, "sm:p-60"],
                [64, "sm:p-64"],
                [72, "sm:p-72"],
                [80, "sm:p-80"],
                [96, "sm:p-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:p-0"],
                ["px", "md:p-px"],
                [0.5, "md:p-0.5"],
                [1, "md:p-1"],
                [1.5, "md:p-1.5"],
                [2, "md:p-2"],
                [2.5, "md:p-2.5"],
                [3, "md:p-3"],
                [3.5, "md:p-3.5"],
                [4, "md:p-4"],
                [5, "md:p-5"],
                [6, "md:p-6"],
                [7, "md:p-7"],
                [8, "md:p-8"],
                [9, "md:p-9"],
                [10, "md:p-10"],
                [11, "md:p-11"],
                [12, "md:p-12"],
                [14, "md:p-14"],
                [16, "md:p-16"],
                [20, "md:p-20"],
                [24, "md:p-24"],
                [28, "md:p-28"],
                [32, "md:p-32"],
                [36, "md:p-36"],
                [40, "md:p-40"],
                [44, "md:p-44"],
                [48, "md:p-48"],
                [52, "md:p-52"],
                [56, "md:p-56"],
                [60, "md:p-60"],
                [64, "md:p-64"],
                [72, "md:p-72"],
                [80, "md:p-80"],
                [96, "md:p-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:p-0"],
                ["px", "lg:p-px"],
                [0.5, "lg:p-0.5"],
                [1, "lg:p-1"],
                [1.5, "lg:p-1.5"],
                [2, "lg:p-2"],
                [2.5, "lg:p-2.5"],
                [3, "lg:p-3"],
                [3.5, "lg:p-3.5"],
                [4, "lg:p-4"],
                [5, "lg:p-5"],
                [6, "lg:p-6"],
                [7, "lg:p-7"],
                [8, "lg:p-8"],
                [9, "lg:p-9"],
                [10, "lg:p-10"],
                [11, "lg:p-11"],
                [12, "lg:p-12"],
                [14, "lg:p-14"],
                [16, "lg:p-16"],
                [20, "lg:p-20"],
                [24, "lg:p-24"],
                [28, "lg:p-28"],
                [32, "lg:p-32"],
                [36, "lg:p-36"],
                [40, "lg:p-40"],
                [44, "lg:p-44"],
                [48, "lg:p-48"],
                [52, "lg:p-52"],
                [56, "lg:p-56"],
                [60, "lg:p-60"],
                [64, "lg:p-64"],
                [72, "lg:p-72"],
                [80, "lg:p-80"],
                [96, "lg:p-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:p-0"],
                ["px", "xl:p-px"],
                [0.5, "xl:p-0.5"],
                [1, "xl:p-1"],
                [1.5, "xl:p-1.5"],
                [2, "xl:p-2"],
                [2.5, "xl:p-2.5"],
                [3, "xl:p-3"],
                [3.5, "xl:p-3.5"],
                [4, "xl:p-4"],
                [5, "xl:p-5"],
                [6, "xl:p-6"],
                [7, "xl:p-7"],
                [8, "xl:p-8"],
                [9, "xl:p-9"],
                [10, "xl:p-10"],
                [11, "xl:p-11"],
                [12, "xl:p-12"],
                [14, "xl:p-14"],
                [16, "xl:p-16"],
                [20, "xl:p-20"],
                [24, "xl:p-24"],
                [28, "xl:p-28"],
                [32, "xl:p-32"],
                [36, "xl:p-36"],
                [40, "xl:p-40"],
                [44, "xl:p-44"],
                [48, "xl:p-48"],
                [52, "xl:p-52"],
                [56, "xl:p-56"],
                [60, "xl:p-60"],
                [64, "xl:p-64"],
                [72, "xl:p-72"],
                [80, "xl:p-80"],
                [96, "xl:p-96"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:open:p-0"],
                ["px", "xs:open:p-px"],
                [0.5, "xs:open:p-0.5"],
                [1, "xs:open:p-1"],
                [1.5, "xs:open:p-1.5"],
                [2, "xs:open:p-2"],
                [2.5, "xs:open:p-2.5"],
                [3, "xs:open:p-3"],
                [3.5, "xs:open:p-3.5"],
                [4, "xs:open:p-4"],
                [5, "xs:open:p-5"],
                [6, "xs:open:p-6"],
                [7, "xs:open:p-7"],
                [8, "xs:open:p-8"],
                [9, "xs:open:p-9"],
                [10, "xs:open:p-10"],
                [11, "xs:open:p-11"],
                [12, "xs:open:p-12"],
                [14, "xs:open:p-14"],
                [16, "xs:open:p-16"],
                [20, "xs:open:p-20"],
                [24, "xs:open:p-24"],
                [28, "xs:open:p-28"],
                [32, "xs:open:p-32"],
                [36, "xs:open:p-36"],
                [40, "xs:open:p-40"],
                [44, "xs:open:p-44"],
                [48, "xs:open:p-48"],
                [52, "xs:open:p-52"],
                [56, "xs:open:p-56"],
                [60, "xs:open:p-60"],
                [64, "xs:open:p-64"],
                [72, "xs:open:p-72"],
                [80, "xs:open:p-80"],
                [96, "xs:open:p-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:open:p-0"],
                ["px", "sm:open:p-px"],
                [0.5, "sm:open:p-0.5"],
                [1, "sm:open:p-1"],
                [1.5, "sm:open:p-1.5"],
                [2, "sm:open:p-2"],
                [2.5, "sm:open:p-2.5"],
                [3, "sm:open:p-3"],
                [3.5, "sm:open:p-3.5"],
                [4, "sm:open:p-4"],
                [5, "sm:open:p-5"],
                [6, "sm:open:p-6"],
                [7, "sm:open:p-7"],
                [8, "sm:open:p-8"],
                [9, "sm:open:p-9"],
                [10, "sm:open:p-10"],
                [11, "sm:open:p-11"],
                [12, "sm:open:p-12"],
                [14, "sm:open:p-14"],
                [16, "sm:open:p-16"],
                [20, "sm:open:p-20"],
                [24, "sm:open:p-24"],
                [28, "sm:open:p-28"],
                [32, "sm:open:p-32"],
                [36, "sm:open:p-36"],
                [40, "sm:open:p-40"],
                [44, "sm:open:p-44"],
                [48, "sm:open:p-48"],
                [52, "sm:open:p-52"],
                [56, "sm:open:p-56"],
                [60, "sm:open:p-60"],
                [64, "sm:open:p-64"],
                [72, "sm:open:p-72"],
                [80, "sm:open:p-80"],
                [96, "sm:open:p-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:open:p-0"],
                ["px", "md:open:p-px"],
                [0.5, "md:open:p-0.5"],
                [1, "md:open:p-1"],
                [1.5, "md:open:p-1.5"],
                [2, "md:open:p-2"],
                [2.5, "md:open:p-2.5"],
                [3, "md:open:p-3"],
                [3.5, "md:open:p-3.5"],
                [4, "md:open:p-4"],
                [5, "md:open:p-5"],
                [6, "md:open:p-6"],
                [7, "md:open:p-7"],
                [8, "md:open:p-8"],
                [9, "md:open:p-9"],
                [10, "md:open:p-10"],
                [11, "md:open:p-11"],
                [12, "md:open:p-12"],
                [14, "md:open:p-14"],
                [16, "md:open:p-16"],
                [20, "md:open:p-20"],
                [24, "md:open:p-24"],
                [28, "md:open:p-28"],
                [32, "md:open:p-32"],
                [36, "md:open:p-36"],
                [40, "md:open:p-40"],
                [44, "md:open:p-44"],
                [48, "md:open:p-48"],
                [52, "md:open:p-52"],
                [56, "md:open:p-56"],
                [60, "md:open:p-60"],
                [64, "md:open:p-64"],
                [72, "md:open:p-72"],
                [80, "md:open:p-80"],
                [96, "md:open:p-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:open:p-0"],
                ["px", "lg:open:p-px"],
                [0.5, "lg:open:p-0.5"],
                [1, "lg:open:p-1"],
                [1.5, "lg:open:p-1.5"],
                [2, "lg:open:p-2"],
                [2.5, "lg:open:p-2.5"],
                [3, "lg:open:p-3"],
                [3.5, "lg:open:p-3.5"],
                [4, "lg:open:p-4"],
                [5, "lg:open:p-5"],
                [6, "lg:open:p-6"],
                [7, "lg:open:p-7"],
                [8, "lg:open:p-8"],
                [9, "lg:open:p-9"],
                [10, "lg:open:p-10"],
                [11, "lg:open:p-11"],
                [12, "lg:open:p-12"],
                [14, "lg:open:p-14"],
                [16, "lg:open:p-16"],
                [20, "lg:open:p-20"],
                [24, "lg:open:p-24"],
                [28, "lg:open:p-28"],
                [32, "lg:open:p-32"],
                [36, "lg:open:p-36"],
                [40, "lg:open:p-40"],
                [44, "lg:open:p-44"],
                [48, "lg:open:p-48"],
                [52, "lg:open:p-52"],
                [56, "lg:open:p-56"],
                [60, "lg:open:p-60"],
                [64, "lg:open:p-64"],
                [72, "lg:open:p-72"],
                [80, "lg:open:p-80"],
                [96, "lg:open:p-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:open:p-0"],
                ["px", "xl:open:p-px"],
                [0.5, "xl:open:p-0.5"],
                [1, "xl:open:p-1"],
                [1.5, "xl:open:p-1.5"],
                [2, "xl:open:p-2"],
                [2.5, "xl:open:p-2.5"],
                [3, "xl:open:p-3"],
                [3.5, "xl:open:p-3.5"],
                [4, "xl:open:p-4"],
                [5, "xl:open:p-5"],
                [6, "xl:open:p-6"],
                [7, "xl:open:p-7"],
                [8, "xl:open:p-8"],
                [9, "xl:open:p-9"],
                [10, "xl:open:p-10"],
                [11, "xl:open:p-11"],
                [12, "xl:open:p-12"],
                [14, "xl:open:p-14"],
                [16, "xl:open:p-16"],
                [20, "xl:open:p-20"],
                [24, "xl:open:p-24"],
                [28, "xl:open:p-28"],
                [32, "xl:open:p-32"],
                [36, "xl:open:p-36"],
                [40, "xl:open:p-40"],
                [44, "xl:open:p-44"],
                [48, "xl:open:p-48"],
                [52, "xl:open:p-52"],
                [56, "xl:open:p-56"],
                [60, "xl:open:p-60"],
                [64, "xl:open:p-64"],
                [72, "xl:open:p-72"],
                [80, "xl:open:p-80"],
                [96, "xl:open:p-96"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
