import { Breakpoints, CSSSelector, FlexHeight } from "../../types";
import { HeightBreakpoints } from "./HeightBreakpoints";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakable } from "../../Entities/Brekable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";

export class Height
  extends CSSProperty<Map<FlexHeight, string>>
  implements Breakable<Map<Breakpoints, Map<FlexHeight, string>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<FlexHeight, string>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new HeightClassesMapping();
    return new Height(classesMapping, selector);
  }

  public breakpoints() {
    return HeightBreakpoints.create(this.cssSelector);
  }

  public write(spacing: FlexHeight) {
    return this.getClassName(spacing);
  }
}

class HeightClassesMapping implements ClassesMapping<Map<FlexHeight, string>> {
  private defaultValue: DefaultValue<FlexHeight, string>;

  constructor() {
    this.defaultValue = new DefaultValue<FlexHeight, string>("auto", "h-auto");
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<FlexHeight, string>>([
        [
          "active",
          new Map<FlexHeight, string>([
            [0, "active:h-0"],
            ["px", "active:h-px"],
            [0.5, "active:h-0.5"],
            [1, "active:h-1"],
            [1.5, "active:h-1.5"],
            [2, "active:h-2"],
            [2.5, "active:h-2.5"],
            [3, "active:h-3"],
            [3.5, "active:h-3.5"],
            [4, "active:h-4"],
            [5, "active:h-5"],
            [6, "active:h-6"],
            [7, "active:h-7"],
            [8, "active:h-8"],
            [9, "active:h-9"],
            [10, "active:h-10"],
            [11, "active:h-11"],
            [12, "active:h-12"],
            [14, "active:h-14"],
            [16, "active:h-16"],
            [20, "active:h-20"],
            [24, "active:h-24"],
            [28, "active:h-28"],
            [32, "active:h-32"],
            [36, "active:h-36"],
            [40, "active:h-40"],
            [44, "active:h-44"],
            [48, "active:h-48"],
            [52, "active:h-52"],
            [56, "active:h-56"],
            [60, "active:h-60"],
            [64, "active:h-64"],
            [72, "active:h-72"],
            [80, "active:h-80"],
            [96, "active:h-96"],
            ["auto", "active:h-auto"],
            ["1/2", "active:h-1/2"],
            ["1/3", "active:h-1/3"],
            ["2/3", "active:h-2/3"],
            ["1/4", "active:h-1/4"],
            ["2/4", "active:h-2/4"],
            ["3/4", "active:h-3/4"],
            ["1/5", "active:h-1/5"],
            ["2/5", "active:h-2/5"],
            ["3/5", "active:h-3/5"],
            ["4/5", "active:h-4/5"],
            ["1/6", "active:h-1/6"],
            ["2/6", "active:h-2/6"],
            ["3/6", "active:h-3/6"],
            ["4/6", "active:h-4/6"],
            ["5/6", "active:h-5/6"],
            ["full", "active:h-full"],
            ["screen", "active:h-screen"],
            ["svh", "active:h-svh"],
            ["lvh", "active:h-lvh"],
            ["dvh", "active:h-dvh"],
            ["min", "active:h-min"],
            ["max", "active:h-max"],
            ["fit", "active:h-fit"],
          ]),
        ],
        [
          "disabled",
          new Map<FlexHeight, string>([
            [0, "disabled:h-0"],
            ["px", "disabled:h-px"],
            [0.5, "disabled:h-0.5"],
            [1, "disabled:h-1"],
            [1.5, "disabled:h-1.5"],
            [2, "disabled:h-2"],
            [2.5, "disabled:h-2.5"],
            [3, "disabled:h-3"],
            [3.5, "disabled:h-3.5"],
            [4, "disabled:h-4"],
            [5, "disabled:h-5"],
            [6, "disabled:h-6"],
            [7, "disabled:h-7"],
            [8, "disabled:h-8"],
            [9, "disabled:h-9"],
            [10, "disabled:h-10"],
            [11, "disabled:h-11"],
            [12, "disabled:h-12"],
            [14, "disabled:h-14"],
            [16, "disabled:h-16"],
            [20, "disabled:h-20"],
            [24, "disabled:h-24"],
            [28, "disabled:h-28"],
            [32, "disabled:h-32"],
            [36, "disabled:h-36"],
            [40, "disabled:h-40"],
            [44, "disabled:h-44"],
            [48, "disabled:h-48"],
            [52, "disabled:h-52"],
            [56, "disabled:h-56"],
            [60, "disabled:h-60"],
            [64, "disabled:h-64"],
            [72, "disabled:h-72"],
            [80, "disabled:h-80"],
            [96, "disabled:h-96"],
            ["auto", "disabled:h-auto"],
            ["1/2", "disabled:h-1/2"],
            ["1/3", "disabled:h-1/3"],
            ["2/3", "disabled:h-2/3"],
            ["1/4", "disabled:h-1/4"],
            ["2/4", "disabled:h-2/4"],
            ["3/4", "disabled:h-3/4"],
            ["1/5", "disabled:h-1/5"],
            ["2/5", "disabled:h-2/5"],
            ["3/5", "disabled:h-3/5"],
            ["4/5", "disabled:h-4/5"],
            ["1/6", "disabled:h-1/6"],
            ["2/6", "disabled:h-2/6"],
            ["3/6", "disabled:h-3/6"],
            ["4/6", "disabled:h-4/6"],
            ["5/6", "disabled:h-5/6"],
            ["full", "disabled:h-full"],
            ["screen", "disabled:h-screen"],
            ["svh", "disabled:h-svh"],
            ["lvh", "disabled:h-lvh"],
            ["dvh", "disabled:h-dvh"],
            ["min", "disabled:h-min"],
            ["max", "disabled:h-max"],
            ["fit", "disabled:h-fit"],
          ]),
        ],
        [
          "hover",
          new Map<FlexHeight, string>([
            [0, "hover:h-0"],
            ["px", "hover:h-px"],
            [0.5, "hover:h-0.5"],
            [1, "hover:h-1"],
            [1.5, "hover:h-1.5"],
            [2, "hover:h-2"],
            [2.5, "hover:h-2.5"],
            [3, "hover:h-3"],
            [3.5, "hover:h-3.5"],
            [4, "hover:h-4"],
            [5, "hover:h-5"],
            [6, "hover:h-6"],
            [7, "hover:h-7"],
            [8, "hover:h-8"],
            [9, "hover:h-9"],
            [10, "hover:h-10"],
            [11, "hover:h-11"],
            [12, "hover:h-12"],
            [14, "hover:h-14"],
            [16, "hover:h-16"],
            [20, "hover:h-20"],
            [24, "hover:h-24"],
            [28, "hover:h-28"],
            [32, "hover:h-32"],
            [36, "hover:h-36"],
            [40, "hover:h-40"],
            [44, "hover:h-44"],
            [48, "hover:h-48"],
            [52, "hover:h-52"],
            [56, "hover:h-56"],
            [60, "hover:h-60"],
            [64, "hover:h-64"],
            [72, "hover:h-72"],
            [80, "hover:h-80"],
            [96, "hover:h-96"],
            ["auto", "hover:h-auto"],
            ["1/2", "hover:h-1/2"],
            ["1/3", "hover:h-1/3"],
            ["2/3", "hover:h-2/3"],
            ["1/4", "hover:h-1/4"],
            ["2/4", "hover:h-2/4"],
            ["3/4", "hover:h-3/4"],
            ["1/5", "hover:h-1/5"],
            ["2/5", "hover:h-2/5"],
            ["3/5", "hover:h-3/5"],
            ["4/5", "hover:h-4/5"],
            ["1/6", "hover:h-1/6"],
            ["2/6", "hover:h-2/6"],
            ["3/6", "hover:h-3/6"],
            ["4/6", "hover:h-4/6"],
            ["5/6", "hover:h-5/6"],
            ["full", "hover:h-full"],
            ["screen", "hover:h-screen"],
            ["svh", "hover:h-svh"],
            ["lvh", "hover:h-lvh"],
            ["dvh", "hover:h-dvh"],
            ["min", "hover:h-min"],
            ["max", "hover:h-max"],
            ["fit", "hover:h-fit"],
          ]),
        ],
        [
          "none",
          new Map<FlexHeight, string>([
            [0, "h-0"],
            ["px", "h-px"],
            [0.5, "h-0.5"],
            [1, "h-1"],
            [1.5, "h-1.5"],
            [2, "h-2"],
            [2.5, "h-2.5"],
            [3, "h-3"],
            [3.5, "h-3.5"],
            [4, "h-4"],
            [5, "h-5"],
            [6, "h-6"],
            [7, "h-7"],
            [8, "h-8"],
            [9, "h-9"],
            [10, "h-10"],
            [11, "h-11"],
            [12, "h-12"],
            [14, "h-14"],
            [16, "h-16"],
            [20, "h-20"],
            [24, "h-24"],
            [28, "h-28"],
            [32, "h-32"],
            [36, "h-36"],
            [40, "h-40"],
            [44, "h-44"],
            [48, "h-48"],
            [52, "h-52"],
            [56, "h-56"],
            [60, "h-60"],
            [64, "h-64"],
            [72, "h-72"],
            [80, "h-80"],
            [96, "h-96"],
            ["auto", "h-auto"],
            ["1/2", "h-1/2"],
            ["1/3", "h-1/3"],
            ["2/3", "h-2/3"],
            ["1/4", "h-1/4"],
            ["2/4", "h-2/4"],
            ["3/4", "h-3/4"],
            ["1/5", "h-1/5"],
            ["2/5", "h-2/5"],
            ["3/5", "h-3/5"],
            ["4/5", "h-4/5"],
            ["1/6", "h-1/6"],
            ["2/6", "h-2/6"],
            ["3/6", "h-3/6"],
            ["4/6", "h-4/6"],
            ["5/6", "h-5/6"],
            ["full", "h-full"],
            ["screen", "h-screen"],
            ["svh", "h-svh"],
            ["lvh", "h-lvh"],
            ["dvh", "h-dvh"],
            ["min", "h-min"],
            ["max", "h-max"],
            ["fit", "h-fit"],
          ]),
        ],
        [
          "open",
          new Map<FlexHeight, string>([
            [0, "open:h-0"],
            ["px", "open:h-px"],
            [0.5, "open:h-0.5"],
            [1, "open:h-1"],
            [1.5, "open:h-1.5"],
            [2, "open:h-2"],
            [2.5, "open:h-2.5"],
            [3, "open:h-3"],
            [3.5, "open:h-3.5"],
            [4, "open:h-4"],
            [5, "open:h-5"],
            [6, "open:h-6"],
            [7, "open:h-7"],
            [8, "open:h-8"],
            [9, "open:h-9"],
            [10, "open:h-10"],
            [11, "open:h-11"],
            [12, "open:h-12"],
            [14, "open:h-14"],
            [16, "open:h-16"],
            [20, "open:h-20"],
            [24, "open:h-24"],
            [28, "open:h-28"],
            [32, "open:h-32"],
            [36, "open:h-36"],
            [40, "open:h-40"],
            [44, "open:h-44"],
            [48, "open:h-48"],
            [52, "open:h-52"],
            [56, "open:h-56"],
            [60, "open:h-60"],
            [64, "open:h-64"],
            [72, "open:h-72"],
            [80, "open:h-80"],
            [96, "open:h-96"],
            ["auto", "open:h-auto"],
            ["1/2", "open:h-1/2"],
            ["1/3", "open:h-1/3"],
            ["2/3", "open:h-2/3"],
            ["1/4", "open:h-1/4"],
            ["2/4", "open:h-2/4"],
            ["3/4", "open:h-3/4"],
            ["1/5", "open:h-1/5"],
            ["2/5", "open:h-2/5"],
            ["3/5", "open:h-3/5"],
            ["4/5", "open:h-4/5"],
            ["1/6", "open:h-1/6"],
            ["2/6", "open:h-2/6"],
            ["3/6", "open:h-3/6"],
            ["4/6", "open:h-4/6"],
            ["5/6", "open:h-5/6"],
            ["full", "open:h-full"],
            ["screen", "open:h-screen"],
            ["svh", "open:h-svh"],
            ["lvh", "open:h-lvh"],
            ["dvh", "open:h-dvh"],
            ["min", "open:h-min"],
            ["max", "open:h-max"],
            ["fit", "open:h-fit"],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
