import { DefaultValue } from "./../DefaultValue";
import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexHeight } from "../../types";

export class HeightBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexHeight, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexHeight, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new HeightClassesMapping();
    return new HeightBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, spacing: FlexHeight) {
    return this.getClassName(breakpoint, spacing);
  }
}

class HeightClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexHeight, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexHeight, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexHeight, string>>(
      "xs",
      new Map<FlexHeight, string>([["auto", "xs:h-auto"]])
    );
  }
  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexHeight, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexHeight, string>>([
            [
              "xs",
              new Map<FlexHeight, string>([
                [0, "xs:active:h-0"],
                ["px", "xs:active:h-px"],
                [0.5, "xs:active:h-0.5"],
                [1, "xs:active:h-1"],
                [1.5, "xs:active:h-1.5"],
                [2, "xs:active:h-2"],
                [2.5, "xs:active:h-2.5"],
                [3, "xs:active:h-3"],
                [3.5, "xs:active:h-3.5"],
                [4, "xs:active:h-4"],
                [5, "xs:active:h-5"],
                [6, "xs:active:h-6"],
                [7, "xs:active:h-7"],
                [8, "xs:active:h-8"],
                [9, "xs:active:h-9"],
                [10, "xs:active:h-10"],
                [11, "xs:active:h-11"],
                [12, "xs:active:h-12"],
                [14, "xs:active:h-14"],
                [16, "xs:active:h-16"],
                [20, "xs:active:h-20"],
                [24, "xs:active:h-24"],
                [28, "xs:active:h-28"],
                [32, "xs:active:h-32"],
                [36, "xs:active:h-36"],
                [40, "xs:active:h-40"],
                [44, "xs:active:h-44"],
                [48, "xs:active:h-48"],
                [52, "xs:active:h-52"],
                [56, "xs:active:h-56"],
                [60, "xs:active:h-60"],
                [64, "xs:active:h-64"],
                [72, "xs:active:h-72"],
                [80, "xs:active:h-80"],
                [96, "xs:active:h-96"],
                ["auto", "xs:active:h-auto"],
                ["1/2", "xs:active:h-1/2"],
                ["1/3", "xs:active:h-1/3"],
                ["2/3", "xs:active:h-2/3"],
                ["1/4", "xs:active:h-1/4"],
                ["2/4", "xs:active:h-2/4"],
                ["3/4", "xs:active:h-3/4"],
                ["1/5", "xs:active:h-1/5"],
                ["2/5", "xs:active:h-2/5"],
                ["3/5", "xs:active:h-3/5"],
                ["4/5", "xs:active:h-4/5"],
                ["1/6", "xs:active:h-1/6"],
                ["2/6", "xs:active:h-2/6"],
                ["3/6", "xs:active:h-3/6"],
                ["4/6", "xs:active:h-4/6"],
                ["5/6", "xs:active:h-5/6"],
                ["full", "xs:active:h-full"],
                ["screen", "xs:active:h-screen"],
                ["svh", "xs:active:h-svh"],
                ["lvh", "xs:active:h-lvh"],
                ["dvh", "xs:active:h-dvh"],
                ["min", "xs:active:h-min"],
                ["max", "xs:active:h-max"],
                ["fit", "xs:active:h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexHeight, string>([
                [0, "sm:active:h-0"],
                ["px", "sm:active:h-px"],
                [0.5, "sm:active:h-0.5"],
                [1, "sm:active:h-1"],
                [1.5, "sm:active:h-1.5"],
                [2, "sm:active:h-2"],
                [2.5, "sm:active:h-2.5"],
                [3, "sm:active:h-3"],
                [3.5, "sm:active:h-3.5"],
                [4, "sm:active:h-4"],
                [5, "sm:active:h-5"],
                [6, "sm:active:h-6"],
                [7, "sm:active:h-7"],
                [8, "sm:active:h-8"],
                [9, "sm:active:h-9"],
                [10, "sm:active:h-10"],
                [11, "sm:active:h-11"],
                [12, "sm:active:h-12"],
                [14, "sm:active:h-14"],
                [16, "sm:active:h-16"],
                [20, "sm:active:h-20"],
                [24, "sm:active:h-24"],
                [28, "sm:active:h-28"],
                [32, "sm:active:h-32"],
                [36, "sm:active:h-36"],
                [40, "sm:active:h-40"],
                [44, "sm:active:h-44"],
                [48, "sm:active:h-48"],
                [52, "sm:active:h-52"],
                [56, "sm:active:h-56"],
                [60, "sm:active:h-60"],
                [64, "sm:active:h-64"],
                [72, "sm:active:h-72"],
                [80, "sm:active:h-80"],
                [96, "sm:active:h-96"],
                ["auto", "sm:active:h-auto"],
                ["1/2", "sm:active:h-1/2"],
                ["1/3", "sm:active:h-1/3"],
                ["2/3", "sm:active:h-2/3"],
                ["1/4", "sm:active:h-1/4"],
                ["2/4", "sm:active:h-2/4"],
                ["3/4", "sm:active:h-3/4"],
                ["1/5", "sm:active:h-1/5"],
                ["2/5", "sm:active:h-2/5"],
                ["3/5", "sm:active:h-3/5"],
                ["4/5", "sm:active:h-4/5"],
                ["1/6", "sm:active:h-1/6"],
                ["2/6", "sm:active:h-2/6"],
                ["3/6", "sm:active:h-3/6"],
                ["4/6", "sm:active:h-4/6"],
                ["5/6", "sm:active:h-5/6"],
                ["full", "sm:active:h-full"],
                ["screen", "sm:active:h-screen"],
                ["svh", "sm:active:h-svh"],
                ["lvh", "sm:active:h-lvh"],
                ["dvh", "sm:active:h-dvh"],
                ["min", "sm:active:h-min"],
                ["max", "sm:active:h-max"],
                ["fit", "sm:active:h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexHeight, string>([
                [0, "md:active:h-0"],
                ["px", "md:active:h-px"],
                [0.5, "md:active:h-0.5"],
                [1, "md:active:h-1"],
                [1.5, "md:active:h-1.5"],
                [2, "md:active:h-2"],
                [2.5, "md:active:h-2.5"],
                [3, "md:active:h-3"],
                [3.5, "md:active:h-3.5"],
                [4, "md:active:h-4"],
                [5, "md:active:h-5"],
                [6, "md:active:h-6"],
                [7, "md:active:h-7"],
                [8, "md:active:h-8"],
                [9, "md:active:h-9"],
                [10, "md:active:h-10"],
                [11, "md:active:h-11"],
                [12, "md:active:h-12"],
                [14, "md:active:h-14"],
                [16, "md:active:h-16"],
                [20, "md:active:h-20"],
                [24, "md:active:h-24"],
                [28, "md:active:h-28"],
                [32, "md:active:h-32"],
                [36, "md:active:h-36"],
                [40, "md:active:h-40"],
                [44, "md:active:h-44"],
                [48, "md:active:h-48"],
                [52, "md:active:h-52"],
                [56, "md:active:h-56"],
                [60, "md:active:h-60"],
                [64, "md:active:h-64"],
                [72, "md:active:h-72"],
                [80, "md:active:h-80"],
                [96, "md:active:h-96"],
                ["auto", "md:active:h-auto"],
                ["1/2", "md:active:h-1/2"],
                ["1/3", "md:active:h-1/3"],
                ["2/3", "md:active:h-2/3"],
                ["1/4", "md:active:h-1/4"],
                ["2/4", "md:active:h-2/4"],
                ["3/4", "md:active:h-3/4"],
                ["1/5", "md:active:h-1/5"],
                ["2/5", "md:active:h-2/5"],
                ["3/5", "md:active:h-3/5"],
                ["4/5", "md:active:h-4/5"],
                ["1/6", "md:active:h-1/6"],
                ["2/6", "md:active:h-2/6"],
                ["3/6", "md:active:h-3/6"],
                ["4/6", "md:active:h-4/6"],
                ["5/6", "md:active:h-5/6"],
                ["full", "md:active:h-full"],
                ["screen", "md:active:h-screen"],
                ["svh", "md:active:h-svh"],
                ["lvh", "md:active:h-lvh"],
                ["dvh", "md:active:h-dvh"],
                ["min", "md:active:h-min"],
                ["max", "md:active:h-max"],
                ["fit", "md:active:h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexHeight, string>([
                [0, "lg:active:h-0"],
                ["px", "lg:active:h-px"],
                [0.5, "lg:active:h-0.5"],
                [1, "lg:active:h-1"],
                [1.5, "lg:active:h-1.5"],
                [2, "lg:active:h-2"],
                [2.5, "lg:active:h-2.5"],
                [3, "lg:active:h-3"],
                [3.5, "lg:active:h-3.5"],
                [4, "lg:active:h-4"],
                [5, "lg:active:h-5"],
                [6, "lg:active:h-6"],
                [7, "lg:active:h-7"],
                [8, "lg:active:h-8"],
                [9, "lg:active:h-9"],
                [10, "lg:active:h-10"],
                [11, "lg:active:h-11"],
                [12, "lg:active:h-12"],
                [14, "lg:active:h-14"],
                [16, "lg:active:h-16"],
                [20, "lg:active:h-20"],
                [24, "lg:active:h-24"],
                [28, "lg:active:h-28"],
                [32, "lg:active:h-32"],
                [36, "lg:active:h-36"],
                [40, "lg:active:h-40"],
                [44, "lg:active:h-44"],
                [48, "lg:active:h-48"],
                [52, "lg:active:h-52"],
                [56, "lg:active:h-56"],
                [60, "lg:active:h-60"],
                [64, "lg:active:h-64"],
                [72, "lg:active:h-72"],
                [80, "lg:active:h-80"],
                [96, "lg:active:h-96"],
                ["auto", "lg:active:h-auto"],
                ["1/2", "lg:active:h-1/2"],
                ["1/3", "lg:active:h-1/3"],
                ["2/3", "lg:active:h-2/3"],
                ["1/4", "lg:active:h-1/4"],
                ["2/4", "lg:active:h-2/4"],
                ["3/4", "lg:active:h-3/4"],
                ["1/5", "lg:active:h-1/5"],
                ["2/5", "lg:active:h-2/5"],
                ["3/5", "lg:active:h-3/5"],
                ["4/5", "lg:active:h-4/5"],
                ["1/6", "lg:active:h-1/6"],
                ["2/6", "lg:active:h-2/6"],
                ["3/6", "lg:active:h-3/6"],
                ["4/6", "lg:active:h-4/6"],
                ["5/6", "lg:active:h-5/6"],
                ["full", "lg:active:h-full"],
                ["screen", "lg:active:h-screen"],
                ["svh", "lg:active:h-svh"],
                ["lvh", "lg:active:h-lvh"],
                ["dvh", "lg:active:h-dvh"],
                ["min", "lg:active:h-min"],
                ["max", "lg:active:h-max"],
                ["fit", "lg:active:h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexHeight, string>([
                [0, "xl:active:h-0"],
                ["px", "xl:active:h-px"],
                [0.5, "xl:active:h-0.5"],
                [1, "xl:active:h-1"],
                [1.5, "xl:active:h-1.5"],
                [2, "xl:active:h-2"],
                [2.5, "xl:active:h-2.5"],
                [3, "xl:active:h-3"],
                [3.5, "xl:active:h-3.5"],
                [4, "xl:active:h-4"],
                [5, "xl:active:h-5"],
                [6, "xl:active:h-6"],
                [7, "xl:active:h-7"],
                [8, "xl:active:h-8"],
                [9, "xl:active:h-9"],
                [10, "xl:active:h-10"],
                [11, "xl:active:h-11"],
                [12, "xl:active:h-12"],
                [14, "xl:active:h-14"],
                [16, "xl:active:h-16"],
                [20, "xl:active:h-20"],
                [24, "xl:active:h-24"],
                [28, "xl:active:h-28"],
                [32, "xl:active:h-32"],
                [36, "xl:active:h-36"],
                [40, "xl:active:h-40"],
                [44, "xl:active:h-44"],
                [48, "xl:active:h-48"],
                [52, "xl:active:h-52"],
                [56, "xl:active:h-56"],
                [60, "xl:active:h-60"],
                [64, "xl:active:h-64"],
                [72, "xl:active:h-72"],
                [80, "xl:active:h-80"],
                [96, "xl:active:h-96"],
                ["auto", "xl:active:h-auto"],
                ["1/2", "xl:active:h-1/2"],
                ["1/3", "xl:active:h-1/3"],
                ["2/3", "xl:active:h-2/3"],
                ["1/4", "xl:active:h-1/4"],
                ["2/4", "xl:active:h-2/4"],
                ["3/4", "xl:active:h-3/4"],
                ["1/5", "xl:active:h-1/5"],
                ["2/5", "xl:active:h-2/5"],
                ["3/5", "xl:active:h-3/5"],
                ["4/5", "xl:active:h-4/5"],
                ["1/6", "xl:active:h-1/6"],
                ["2/6", "xl:active:h-2/6"],
                ["3/6", "xl:active:h-3/6"],
                ["4/6", "xl:active:h-4/6"],
                ["5/6", "xl:active:h-5/6"],
                ["full", "xl:active:h-full"],
                ["screen", "xl:active:h-screen"],
                ["svh", "xl:active:h-svh"],
                ["lvh", "xl:active:h-lvh"],
                ["dvh", "xl:active:h-dvh"],
                ["min", "xl:active:h-min"],
                ["max", "xl:active:h-max"],
                ["fit", "xl:active:h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexHeight, string>>([
            [
              "xs",
              new Map<FlexHeight, string>([
                [0, "xs:disabled:h-0"],
                ["px", "xs:disabled:h-px"],
                [0.5, "xs:disabled:h-0.5"],
                [1, "xs:disabled:h-1"],
                [1.5, "xs:disabled:h-1.5"],
                [2, "xs:disabled:h-2"],
                [2.5, "xs:disabled:h-2.5"],
                [3, "xs:disabled:h-3"],
                [3.5, "xs:disabled:h-3.5"],
                [4, "xs:disabled:h-4"],
                [5, "xs:disabled:h-5"],
                [6, "xs:disabled:h-6"],
                [7, "xs:disabled:h-7"],
                [8, "xs:disabled:h-8"],
                [9, "xs:disabled:h-9"],
                [10, "xs:disabled:h-10"],
                [11, "xs:disabled:h-11"],
                [12, "xs:disabled:h-12"],
                [14, "xs:disabled:h-14"],
                [16, "xs:disabled:h-16"],
                [20, "xs:disabled:h-20"],
                [24, "xs:disabled:h-24"],
                [28, "xs:disabled:h-28"],
                [32, "xs:disabled:h-32"],
                [36, "xs:disabled:h-36"],
                [40, "xs:disabled:h-40"],
                [44, "xs:disabled:h-44"],
                [48, "xs:disabled:h-48"],
                [52, "xs:disabled:h-52"],
                [56, "xs:disabled:h-56"],
                [60, "xs:disabled:h-60"],
                [64, "xs:disabled:h-64"],
                [72, "xs:disabled:h-72"],
                [80, "xs:disabled:h-80"],
                [96, "xs:disabled:h-96"],
                ["auto", "xs:disabled:h-auto"],
                ["1/2", "xs:disabled:h-1/2"],
                ["1/3", "xs:disabled:h-1/3"],
                ["2/3", "xs:disabled:h-2/3"],
                ["1/4", "xs:disabled:h-1/4"],
                ["2/4", "xs:disabled:h-2/4"],
                ["3/4", "xs:disabled:h-3/4"],
                ["1/5", "xs:disabled:h-1/5"],
                ["2/5", "xs:disabled:h-2/5"],
                ["3/5", "xs:disabled:h-3/5"],
                ["4/5", "xs:disabled:h-4/5"],
                ["1/6", "xs:disabled:h-1/6"],
                ["2/6", "xs:disabled:h-2/6"],
                ["3/6", "xs:disabled:h-3/6"],
                ["4/6", "xs:disabled:h-4/6"],
                ["5/6", "xs:disabled:h-5/6"],
                ["full", "xs:disabled:h-full"],
                ["screen", "xs:disabled:h-screen"],
                ["svh", "xs:disabled:h-svh"],
                ["lvh", "xs:disabled:h-lvh"],
                ["dvh", "xs:disabled:h-dvh"],
                ["min", "xs:disabled:h-min"],
                ["max", "xs:disabled:h-max"],
                ["fit", "xs:disabled:h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexHeight, string>([
                [0, "sm:disabled:h-0"],
                ["px", "sm:disabled:h-px"],
                [0.5, "sm:disabled:h-0.5"],
                [1, "sm:disabled:h-1"],
                [1.5, "sm:disabled:h-1.5"],
                [2, "sm:disabled:h-2"],
                [2.5, "sm:disabled:h-2.5"],
                [3, "sm:disabled:h-3"],
                [3.5, "sm:disabled:h-3.5"],
                [4, "sm:disabled:h-4"],
                [5, "sm:disabled:h-5"],
                [6, "sm:disabled:h-6"],
                [7, "sm:disabled:h-7"],
                [8, "sm:disabled:h-8"],
                [9, "sm:disabled:h-9"],
                [10, "sm:disabled:h-10"],
                [11, "sm:disabled:h-11"],
                [12, "sm:disabled:h-12"],
                [14, "sm:disabled:h-14"],
                [16, "sm:disabled:h-16"],
                [20, "sm:disabled:h-20"],
                [24, "sm:disabled:h-24"],
                [28, "sm:disabled:h-28"],
                [32, "sm:disabled:h-32"],
                [36, "sm:disabled:h-36"],
                [40, "sm:disabled:h-40"],
                [44, "sm:disabled:h-44"],
                [48, "sm:disabled:h-48"],
                [52, "sm:disabled:h-52"],
                [56, "sm:disabled:h-56"],
                [60, "sm:disabled:h-60"],
                [64, "sm:disabled:h-64"],
                [72, "sm:disabled:h-72"],
                [80, "sm:disabled:h-80"],
                [96, "sm:disabled:h-96"],
                ["auto", "sm:disabled:h-auto"],
                ["1/2", "sm:disabled:h-1/2"],
                ["1/3", "sm:disabled:h-1/3"],
                ["2/3", "sm:disabled:h-2/3"],
                ["1/4", "sm:disabled:h-1/4"],
                ["2/4", "sm:disabled:h-2/4"],
                ["3/4", "sm:disabled:h-3/4"],
                ["1/5", "sm:disabled:h-1/5"],
                ["2/5", "sm:disabled:h-2/5"],
                ["3/5", "sm:disabled:h-3/5"],
                ["4/5", "sm:disabled:h-4/5"],
                ["1/6", "sm:disabled:h-1/6"],
                ["2/6", "sm:disabled:h-2/6"],
                ["3/6", "sm:disabled:h-3/6"],
                ["4/6", "sm:disabled:h-4/6"],
                ["5/6", "sm:disabled:h-5/6"],
                ["full", "sm:disabled:h-full"],
                ["screen", "sm:disabled:h-screen"],
                ["svh", "sm:disabled:h-svh"],
                ["lvh", "sm:disabled:h-lvh"],
                ["dvh", "sm:disabled:h-dvh"],
                ["min", "sm:disabled:h-min"],
                ["max", "sm:disabled:h-max"],
                ["fit", "sm:disabled:h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexHeight, string>([
                [0, "md:disabled:h-0"],
                ["px", "md:disabled:h-px"],
                [0.5, "md:disabled:h-0.5"],
                [1, "md:disabled:h-1"],
                [1.5, "md:disabled:h-1.5"],
                [2, "md:disabled:h-2"],
                [2.5, "md:disabled:h-2.5"],
                [3, "md:disabled:h-3"],
                [3.5, "md:disabled:h-3.5"],
                [4, "md:disabled:h-4"],
                [5, "md:disabled:h-5"],
                [6, "md:disabled:h-6"],
                [7, "md:disabled:h-7"],
                [8, "md:disabled:h-8"],
                [9, "md:disabled:h-9"],
                [10, "md:disabled:h-10"],
                [11, "md:disabled:h-11"],
                [12, "md:disabled:h-12"],
                [14, "md:disabled:h-14"],
                [16, "md:disabled:h-16"],
                [20, "md:disabled:h-20"],
                [24, "md:disabled:h-24"],
                [28, "md:disabled:h-28"],
                [32, "md:disabled:h-32"],
                [36, "md:disabled:h-36"],
                [40, "md:disabled:h-40"],
                [44, "md:disabled:h-44"],
                [48, "md:disabled:h-48"],
                [52, "md:disabled:h-52"],
                [56, "md:disabled:h-56"],
                [60, "md:disabled:h-60"],
                [64, "md:disabled:h-64"],
                [72, "md:disabled:h-72"],
                [80, "md:disabled:h-80"],
                [96, "md:disabled:h-96"],
                ["auto", "md:disabled:h-auto"],
                ["1/2", "md:disabled:h-1/2"],
                ["1/3", "md:disabled:h-1/3"],
                ["2/3", "md:disabled:h-2/3"],
                ["1/4", "md:disabled:h-1/4"],
                ["2/4", "md:disabled:h-2/4"],
                ["3/4", "md:disabled:h-3/4"],
                ["1/5", "md:disabled:h-1/5"],
                ["2/5", "md:disabled:h-2/5"],
                ["3/5", "md:disabled:h-3/5"],
                ["4/5", "md:disabled:h-4/5"],
                ["1/6", "md:disabled:h-1/6"],
                ["2/6", "md:disabled:h-2/6"],
                ["3/6", "md:disabled:h-3/6"],
                ["4/6", "md:disabled:h-4/6"],
                ["5/6", "md:disabled:h-5/6"],
                ["full", "md:disabled:h-full"],
                ["screen", "md:disabled:h-screen"],
                ["svh", "md:disabled:h-svh"],
                ["lvh", "md:disabled:h-lvh"],
                ["dvh", "md:disabled:h-dvh"],
                ["min", "md:disabled:h-min"],
                ["max", "md:disabled:h-max"],
                ["fit", "md:disabled:h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexHeight, string>([
                [0, "lg:disabled:h-0"],
                ["px", "lg:disabled:h-px"],
                [0.5, "lg:disabled:h-0.5"],
                [1, "lg:disabled:h-1"],
                [1.5, "lg:disabled:h-1.5"],
                [2, "lg:disabled:h-2"],
                [2.5, "lg:disabled:h-2.5"],
                [3, "lg:disabled:h-3"],
                [3.5, "lg:disabled:h-3.5"],
                [4, "lg:disabled:h-4"],
                [5, "lg:disabled:h-5"],
                [6, "lg:disabled:h-6"],
                [7, "lg:disabled:h-7"],
                [8, "lg:disabled:h-8"],
                [9, "lg:disabled:h-9"],
                [10, "lg:disabled:h-10"],
                [11, "lg:disabled:h-11"],
                [12, "lg:disabled:h-12"],
                [14, "lg:disabled:h-14"],
                [16, "lg:disabled:h-16"],
                [20, "lg:disabled:h-20"],
                [24, "lg:disabled:h-24"],
                [28, "lg:disabled:h-28"],
                [32, "lg:disabled:h-32"],
                [36, "lg:disabled:h-36"],
                [40, "lg:disabled:h-40"],
                [44, "lg:disabled:h-44"],
                [48, "lg:disabled:h-48"],
                [52, "lg:disabled:h-52"],
                [56, "lg:disabled:h-56"],
                [60, "lg:disabled:h-60"],
                [64, "lg:disabled:h-64"],
                [72, "lg:disabled:h-72"],
                [80, "lg:disabled:h-80"],
                [96, "lg:disabled:h-96"],
                ["auto", "lg:disabled:h-auto"],
                ["1/2", "lg:disabled:h-1/2"],
                ["1/3", "lg:disabled:h-1/3"],
                ["2/3", "lg:disabled:h-2/3"],
                ["1/4", "lg:disabled:h-1/4"],
                ["2/4", "lg:disabled:h-2/4"],
                ["3/4", "lg:disabled:h-3/4"],
                ["1/5", "lg:disabled:h-1/5"],
                ["2/5", "lg:disabled:h-2/5"],
                ["3/5", "lg:disabled:h-3/5"],
                ["4/5", "lg:disabled:h-4/5"],
                ["1/6", "lg:disabled:h-1/6"],
                ["2/6", "lg:disabled:h-2/6"],
                ["3/6", "lg:disabled:h-3/6"],
                ["4/6", "lg:disabled:h-4/6"],
                ["5/6", "lg:disabled:h-5/6"],
                ["full", "lg:disabled:h-full"],
                ["screen", "lg:disabled:h-screen"],
                ["svh", "lg:disabled:h-svh"],
                ["lvh", "lg:disabled:h-lvh"],
                ["dvh", "lg:disabled:h-dvh"],
                ["min", "lg:disabled:h-min"],
                ["max", "lg:disabled:h-max"],
                ["fit", "lg:disabled:h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexHeight, string>([
                [0, "xl:disabled:h-0"],
                ["px", "xl:disabled:h-px"],
                [0.5, "xl:disabled:h-0.5"],
                [1, "xl:disabled:h-1"],
                [1.5, "xl:disabled:h-1.5"],
                [2, "xl:disabled:h-2"],
                [2.5, "xl:disabled:h-2.5"],
                [3, "xl:disabled:h-3"],
                [3.5, "xl:disabled:h-3.5"],
                [4, "xl:disabled:h-4"],
                [5, "xl:disabled:h-5"],
                [6, "xl:disabled:h-6"],
                [7, "xl:disabled:h-7"],
                [8, "xl:disabled:h-8"],
                [9, "xl:disabled:h-9"],
                [10, "xl:disabled:h-10"],
                [11, "xl:disabled:h-11"],
                [12, "xl:disabled:h-12"],
                [14, "xl:disabled:h-14"],
                [16, "xl:disabled:h-16"],
                [20, "xl:disabled:h-20"],
                [24, "xl:disabled:h-24"],
                [28, "xl:disabled:h-28"],
                [32, "xl:disabled:h-32"],
                [36, "xl:disabled:h-36"],
                [40, "xl:disabled:h-40"],
                [44, "xl:disabled:h-44"],
                [48, "xl:disabled:h-48"],
                [52, "xl:disabled:h-52"],
                [56, "xl:disabled:h-56"],
                [60, "xl:disabled:h-60"],
                [64, "xl:disabled:h-64"],
                [72, "xl:disabled:h-72"],
                [80, "xl:disabled:h-80"],
                [96, "xl:disabled:h-96"],
                ["auto", "xl:disabled:h-auto"],
                ["1/2", "xl:disabled:h-1/2"],
                ["1/3", "xl:disabled:h-1/3"],
                ["2/3", "xl:disabled:h-2/3"],
                ["1/4", "xl:disabled:h-1/4"],
                ["2/4", "xl:disabled:h-2/4"],
                ["3/4", "xl:disabled:h-3/4"],
                ["1/5", "xl:disabled:h-1/5"],
                ["2/5", "xl:disabled:h-2/5"],
                ["3/5", "xl:disabled:h-3/5"],
                ["4/5", "xl:disabled:h-4/5"],
                ["1/6", "xl:disabled:h-1/6"],
                ["2/6", "xl:disabled:h-2/6"],
                ["3/6", "xl:disabled:h-3/6"],
                ["4/6", "xl:disabled:h-4/6"],
                ["5/6", "xl:disabled:h-5/6"],
                ["full", "xl:disabled:h-full"],
                ["screen", "xl:disabled:h-screen"],
                ["svh", "xl:disabled:h-svh"],
                ["lvh", "xl:disabled:h-lvh"],
                ["dvh", "xl:disabled:h-dvh"],
                ["min", "xl:disabled:h-min"],
                ["max", "xl:disabled:h-max"],
                ["fit", "xl:disabled:h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexHeight, string>>([
            [
              "xs",
              new Map<FlexHeight, string>([
                [0, "xs:hover:h-0"],
                ["px", "xs:hover:h-px"],
                [0.5, "xs:hover:h-0.5"],
                [1, "xs:hover:h-1"],
                [1.5, "xs:hover:h-1.5"],
                [2, "xs:hover:h-2"],
                [2.5, "xs:hover:h-2.5"],
                [3, "xs:hover:h-3"],
                [3.5, "xs:hover:h-3.5"],
                [4, "xs:hover:h-4"],
                [5, "xs:hover:h-5"],
                [6, "xs:hover:h-6"],
                [7, "xs:hover:h-7"],
                [8, "xs:hover:h-8"],
                [9, "xs:hover:h-9"],
                [10, "xs:hover:h-10"],
                [11, "xs:hover:h-11"],
                [12, "xs:hover:h-12"],
                [14, "xs:hover:h-14"],
                [16, "xs:hover:h-16"],
                [20, "xs:hover:h-20"],
                [24, "xs:hover:h-24"],
                [28, "xs:hover:h-28"],
                [32, "xs:hover:h-32"],
                [36, "xs:hover:h-36"],
                [40, "xs:hover:h-40"],
                [44, "xs:hover:h-44"],
                [48, "xs:hover:h-48"],
                [52, "xs:hover:h-52"],
                [56, "xs:hover:h-56"],
                [60, "xs:hover:h-60"],
                [64, "xs:hover:h-64"],
                [72, "xs:hover:h-72"],
                [80, "xs:hover:h-80"],
                [96, "xs:hover:h-96"],
                ["auto", "xs:hover:h-auto"],
                ["1/2", "xs:hover:h-1/2"],
                ["1/3", "xs:hover:h-1/3"],
                ["2/3", "xs:hover:h-2/3"],
                ["1/4", "xs:hover:h-1/4"],
                ["2/4", "xs:hover:h-2/4"],
                ["3/4", "xs:hover:h-3/4"],
                ["1/5", "xs:hover:h-1/5"],
                ["2/5", "xs:hover:h-2/5"],
                ["3/5", "xs:hover:h-3/5"],
                ["4/5", "xs:hover:h-4/5"],
                ["1/6", "xs:hover:h-1/6"],
                ["2/6", "xs:hover:h-2/6"],
                ["3/6", "xs:hover:h-3/6"],
                ["4/6", "xs:hover:h-4/6"],
                ["5/6", "xs:hover:h-5/6"],
                ["full", "xs:hover:h-full"],
                ["screen", "xs:hover:h-screen"],
                ["svh", "xs:hover:h-svh"],
                ["lvh", "xs:hover:h-lvh"],
                ["dvh", "xs:hover:h-dvh"],
                ["min", "xs:hover:h-min"],
                ["max", "xs:hover:h-max"],
                ["fit", "xs:hover:h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexHeight, string>([
                [0, "sm:hover:h-0"],
                ["px", "sm:hover:h-px"],
                [0.5, "sm:hover:h-0.5"],
                [1, "sm:hover:h-1"],
                [1.5, "sm:hover:h-1.5"],
                [2, "sm:hover:h-2"],
                [2.5, "sm:hover:h-2.5"],
                [3, "sm:hover:h-3"],
                [3.5, "sm:hover:h-3.5"],
                [4, "sm:hover:h-4"],
                [5, "sm:hover:h-5"],
                [6, "sm:hover:h-6"],
                [7, "sm:hover:h-7"],
                [8, "sm:hover:h-8"],
                [9, "sm:hover:h-9"],
                [10, "sm:hover:h-10"],
                [11, "sm:hover:h-11"],
                [12, "sm:hover:h-12"],
                [14, "sm:hover:h-14"],
                [16, "sm:hover:h-16"],
                [20, "sm:hover:h-20"],
                [24, "sm:hover:h-24"],
                [28, "sm:hover:h-28"],
                [32, "sm:hover:h-32"],
                [36, "sm:hover:h-36"],
                [40, "sm:hover:h-40"],
                [44, "sm:hover:h-44"],
                [48, "sm:hover:h-48"],
                [52, "sm:hover:h-52"],
                [56, "sm:hover:h-56"],
                [60, "sm:hover:h-60"],
                [64, "sm:hover:h-64"],
                [72, "sm:hover:h-72"],
                [80, "sm:hover:h-80"],
                [96, "sm:hover:h-96"],
                ["auto", "sm:hover:h-auto"],
                ["1/2", "sm:hover:h-1/2"],
                ["1/3", "sm:hover:h-1/3"],
                ["2/3", "sm:hover:h-2/3"],
                ["1/4", "sm:hover:h-1/4"],
                ["2/4", "sm:hover:h-2/4"],
                ["3/4", "sm:hover:h-3/4"],
                ["1/5", "sm:hover:h-1/5"],
                ["2/5", "sm:hover:h-2/5"],
                ["3/5", "sm:hover:h-3/5"],
                ["4/5", "sm:hover:h-4/5"],
                ["1/6", "sm:hover:h-1/6"],
                ["2/6", "sm:hover:h-2/6"],
                ["3/6", "sm:hover:h-3/6"],
                ["4/6", "sm:hover:h-4/6"],
                ["5/6", "sm:hover:h-5/6"],
                ["full", "sm:hover:h-full"],
                ["screen", "sm:hover:h-screen"],
                ["svh", "sm:hover:h-svh"],
                ["lvh", "sm:hover:h-lvh"],
                ["dvh", "sm:hover:h-dvh"],
                ["min", "sm:hover:h-min"],
                ["max", "sm:hover:h-max"],
                ["fit", "sm:hover:h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexHeight, string>([
                [0, "md:hover:h-0"],
                ["px", "md:hover:h-px"],
                [0.5, "md:hover:h-0.5"],
                [1, "md:hover:h-1"],
                [1.5, "md:hover:h-1.5"],
                [2, "md:hover:h-2"],
                [2.5, "md:hover:h-2.5"],
                [3, "md:hover:h-3"],
                [3.5, "md:hover:h-3.5"],
                [4, "md:hover:h-4"],
                [5, "md:hover:h-5"],
                [6, "md:hover:h-6"],
                [7, "md:hover:h-7"],
                [8, "md:hover:h-8"],
                [9, "md:hover:h-9"],
                [10, "md:hover:h-10"],
                [11, "md:hover:h-11"],
                [12, "md:hover:h-12"],
                [14, "md:hover:h-14"],
                [16, "md:hover:h-16"],
                [20, "md:hover:h-20"],
                [24, "md:hover:h-24"],
                [28, "md:hover:h-28"],
                [32, "md:hover:h-32"],
                [36, "md:hover:h-36"],
                [40, "md:hover:h-40"],
                [44, "md:hover:h-44"],
                [48, "md:hover:h-48"],
                [52, "md:hover:h-52"],
                [56, "md:hover:h-56"],
                [60, "md:hover:h-60"],
                [64, "md:hover:h-64"],
                [72, "md:hover:h-72"],
                [80, "md:hover:h-80"],
                [96, "md:hover:h-96"],
                ["auto", "md:hover:h-auto"],
                ["1/2", "md:hover:h-1/2"],
                ["1/3", "md:hover:h-1/3"],
                ["2/3", "md:hover:h-2/3"],
                ["1/4", "md:hover:h-1/4"],
                ["2/4", "md:hover:h-2/4"],
                ["3/4", "md:hover:h-3/4"],
                ["1/5", "md:hover:h-1/5"],
                ["2/5", "md:hover:h-2/5"],
                ["3/5", "md:hover:h-3/5"],
                ["4/5", "md:hover:h-4/5"],
                ["1/6", "md:hover:h-1/6"],
                ["2/6", "md:hover:h-2/6"],
                ["3/6", "md:hover:h-3/6"],
                ["4/6", "md:hover:h-4/6"],
                ["5/6", "md:hover:h-5/6"],
                ["full", "md:hover:h-full"],
                ["screen", "md:hover:h-screen"],
                ["svh", "md:hover:h-svh"],
                ["lvh", "md:hover:h-lvh"],
                ["dvh", "md:hover:h-dvh"],
                ["min", "md:hover:h-min"],
                ["max", "md:hover:h-max"],
                ["fit", "md:hover:h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexHeight, string>([
                [0, "lg:hover:h-0"],
                ["px", "lg:hover:h-px"],
                [0.5, "lg:hover:h-0.5"],
                [1, "lg:hover:h-1"],
                [1.5, "lg:hover:h-1.5"],
                [2, "lg:hover:h-2"],
                [2.5, "lg:hover:h-2.5"],
                [3, "lg:hover:h-3"],
                [3.5, "lg:hover:h-3.5"],
                [4, "lg:hover:h-4"],
                [5, "lg:hover:h-5"],
                [6, "lg:hover:h-6"],
                [7, "lg:hover:h-7"],
                [8, "lg:hover:h-8"],
                [9, "lg:hover:h-9"],
                [10, "lg:hover:h-10"],
                [11, "lg:hover:h-11"],
                [12, "lg:hover:h-12"],
                [14, "lg:hover:h-14"],
                [16, "lg:hover:h-16"],
                [20, "lg:hover:h-20"],
                [24, "lg:hover:h-24"],
                [28, "lg:hover:h-28"],
                [32, "lg:hover:h-32"],
                [36, "lg:hover:h-36"],
                [40, "lg:hover:h-40"],
                [44, "lg:hover:h-44"],
                [48, "lg:hover:h-48"],
                [52, "lg:hover:h-52"],
                [56, "lg:hover:h-56"],
                [60, "lg:hover:h-60"],
                [64, "lg:hover:h-64"],
                [72, "lg:hover:h-72"],
                [80, "lg:hover:h-80"],
                [96, "lg:hover:h-96"],
                ["auto", "lg:hover:h-auto"],
                ["1/2", "lg:hover:h-1/2"],
                ["1/3", "lg:hover:h-1/3"],
                ["2/3", "lg:hover:h-2/3"],
                ["1/4", "lg:hover:h-1/4"],
                ["2/4", "lg:hover:h-2/4"],
                ["3/4", "lg:hover:h-3/4"],
                ["1/5", "lg:hover:h-1/5"],
                ["2/5", "lg:hover:h-2/5"],
                ["3/5", "lg:hover:h-3/5"],
                ["4/5", "lg:hover:h-4/5"],
                ["1/6", "lg:hover:h-1/6"],
                ["2/6", "lg:hover:h-2/6"],
                ["3/6", "lg:hover:h-3/6"],
                ["4/6", "lg:hover:h-4/6"],
                ["5/6", "lg:hover:h-5/6"],
                ["full", "lg:hover:h-full"],
                ["screen", "lg:hover:h-screen"],
                ["svh", "lg:hover:h-svh"],
                ["lvh", "lg:hover:h-lvh"],
                ["dvh", "lg:hover:h-dvh"],
                ["min", "lg:hover:h-min"],
                ["max", "lg:hover:h-max"],
                ["fit", "lg:hover:h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexHeight, string>([
                [0, "xl:hover:h-0"],
                ["px", "xl:hover:h-px"],
                [0.5, "xl:hover:h-0.5"],
                [1, "xl:hover:h-1"],
                [1.5, "xl:hover:h-1.5"],
                [2, "xl:hover:h-2"],
                [2.5, "xl:hover:h-2.5"],
                [3, "xl:hover:h-3"],
                [3.5, "xl:hover:h-3.5"],
                [4, "xl:hover:h-4"],
                [5, "xl:hover:h-5"],
                [6, "xl:hover:h-6"],
                [7, "xl:hover:h-7"],
                [8, "xl:hover:h-8"],
                [9, "xl:hover:h-9"],
                [10, "xl:hover:h-10"],
                [11, "xl:hover:h-11"],
                [12, "xl:hover:h-12"],
                [14, "xl:hover:h-14"],
                [16, "xl:hover:h-16"],
                [20, "xl:hover:h-20"],
                [24, "xl:hover:h-24"],
                [28, "xl:hover:h-28"],
                [32, "xl:hover:h-32"],
                [36, "xl:hover:h-36"],
                [40, "xl:hover:h-40"],
                [44, "xl:hover:h-44"],
                [48, "xl:hover:h-48"],
                [52, "xl:hover:h-52"],
                [56, "xl:hover:h-56"],
                [60, "xl:hover:h-60"],
                [64, "xl:hover:h-64"],
                [72, "xl:hover:h-72"],
                [80, "xl:hover:h-80"],
                [96, "xl:hover:h-96"],
                ["auto", "xl:hover:h-auto"],
                ["1/2", "xl:hover:h-1/2"],
                ["1/3", "xl:hover:h-1/3"],
                ["2/3", "xl:hover:h-2/3"],
                ["1/4", "xl:hover:h-1/4"],
                ["2/4", "xl:hover:h-2/4"],
                ["3/4", "xl:hover:h-3/4"],
                ["1/5", "xl:hover:h-1/5"],
                ["2/5", "xl:hover:h-2/5"],
                ["3/5", "xl:hover:h-3/5"],
                ["4/5", "xl:hover:h-4/5"],
                ["1/6", "xl:hover:h-1/6"],
                ["2/6", "xl:hover:h-2/6"],
                ["3/6", "xl:hover:h-3/6"],
                ["4/6", "xl:hover:h-4/6"],
                ["5/6", "xl:hover:h-5/6"],
                ["full", "xl:hover:h-full"],
                ["screen", "xl:hover:h-screen"],
                ["svh", "xl:hover:h-svh"],
                ["lvh", "xl:hover:h-lvh"],
                ["dvh", "xl:hover:h-dvh"],
                ["min", "xl:hover:h-min"],
                ["max", "xl:hover:h-max"],
                ["fit", "xl:hover:h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexHeight, string>>([
            [
              "xs",
              new Map<FlexHeight, string>([
                [0, "xs:h-0"],
                ["px", "xs:h-px"],
                [0.5, "xs:h-0.5"],
                [1, "xs:h-1"],
                [1.5, "xs:h-1.5"],
                [2, "xs:h-2"],
                [2.5, "xs:h-2.5"],
                [3, "xs:h-3"],
                [3.5, "xs:h-3.5"],
                [4, "xs:h-4"],
                [5, "xs:h-5"],
                [6, "xs:h-6"],
                [7, "xs:h-7"],
                [8, "xs:h-8"],
                [9, "xs:h-9"],
                [10, "xs:h-10"],
                [11, "xs:h-11"],
                [12, "xs:h-12"],
                [14, "xs:h-14"],
                [16, "xs:h-16"],
                [20, "xs:h-20"],
                [24, "xs:h-24"],
                [28, "xs:h-28"],
                [32, "xs:h-32"],
                [36, "xs:h-36"],
                [40, "xs:h-40"],
                [44, "xs:h-44"],
                [48, "xs:h-48"],
                [52, "xs:h-52"],
                [56, "xs:h-56"],
                [60, "xs:h-60"],
                [64, "xs:h-64"],
                [72, "xs:h-72"],
                [80, "xs:h-80"],
                [96, "xs:h-96"],
                ["auto", "xs:h-auto"],
                ["1/2", "xs:h-1/2"],
                ["1/3", "xs:h-1/3"],
                ["2/3", "xs:h-2/3"],
                ["1/4", "xs:h-1/4"],
                ["2/4", "xs:h-2/4"],
                ["3/4", "xs:h-3/4"],
                ["1/5", "xs:h-1/5"],
                ["2/5", "xs:h-2/5"],
                ["3/5", "xs:h-3/5"],
                ["4/5", "xs:h-4/5"],
                ["1/6", "xs:h-1/6"],
                ["2/6", "xs:h-2/6"],
                ["3/6", "xs:h-3/6"],
                ["4/6", "xs:h-4/6"],
                ["5/6", "xs:h-5/6"],
                ["full", "xs:h-full"],
                ["screen", "xs:h-screen"],
                ["svh", "xs:h-svh"],
                ["lvh", "xs:h-lvh"],
                ["dvh", "xs:h-dvh"],
                ["min", "xs:h-min"],
                ["max", "xs:h-max"],
                ["fit", "xs:h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexHeight, string>([
                [0, "sm:h-0"],
                ["px", "sm:h-px"],
                [0.5, "sm:h-0.5"],
                [1, "sm:h-1"],
                [1.5, "sm:h-1.5"],
                [2, "sm:h-2"],
                [2.5, "sm:h-2.5"],
                [3, "sm:h-3"],
                [3.5, "sm:h-3.5"],
                [4, "sm:h-4"],
                [5, "sm:h-5"],
                [6, "sm:h-6"],
                [7, "sm:h-7"],
                [8, "sm:h-8"],
                [9, "sm:h-9"],
                [10, "sm:h-10"],
                [11, "sm:h-11"],
                [12, "sm:h-12"],
                [14, "sm:h-14"],
                [16, "sm:h-16"],
                [20, "sm:h-20"],
                [24, "sm:h-24"],
                [28, "sm:h-28"],
                [32, "sm:h-32"],
                [36, "sm:h-36"],
                [40, "sm:h-40"],
                [44, "sm:h-44"],
                [48, "sm:h-48"],
                [52, "sm:h-52"],
                [56, "sm:h-56"],
                [60, "sm:h-60"],
                [64, "sm:h-64"],
                [72, "sm:h-72"],
                [80, "sm:h-80"],
                [96, "sm:h-96"],
                ["auto", "sm:h-auto"],
                ["1/2", "sm:h-1/2"],
                ["1/3", "sm:h-1/3"],
                ["2/3", "sm:h-2/3"],
                ["1/4", "sm:h-1/4"],
                ["2/4", "sm:h-2/4"],
                ["3/4", "sm:h-3/4"],
                ["1/5", "sm:h-1/5"],
                ["2/5", "sm:h-2/5"],
                ["3/5", "sm:h-3/5"],
                ["4/5", "sm:h-4/5"],
                ["1/6", "sm:h-1/6"],
                ["2/6", "sm:h-2/6"],
                ["3/6", "sm:h-3/6"],
                ["4/6", "sm:h-4/6"],
                ["5/6", "sm:h-5/6"],
                ["full", "sm:h-full"],
                ["screen", "sm:h-screen"],
                ["svh", "sm:h-svh"],
                ["lvh", "sm:h-lvh"],
                ["dvh", "sm:h-dvh"],
                ["min", "sm:h-min"],
                ["max", "sm:h-max"],
                ["fit", "sm:h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexHeight, string>([
                [0, "md:h-0"],
                ["px", "md:h-px"],
                [0.5, "md:h-0.5"],
                [1, "md:h-1"],
                [1.5, "md:h-1.5"],
                [2, "md:h-2"],
                [2.5, "md:h-2.5"],
                [3, "md:h-3"],
                [3.5, "md:h-3.5"],
                [4, "md:h-4"],
                [5, "md:h-5"],
                [6, "md:h-6"],
                [7, "md:h-7"],
                [8, "md:h-8"],
                [9, "md:h-9"],
                [10, "md:h-10"],
                [11, "md:h-11"],
                [12, "md:h-12"],
                [14, "md:h-14"],
                [16, "md:h-16"],
                [20, "md:h-20"],
                [24, "md:h-24"],
                [28, "md:h-28"],
                [32, "md:h-32"],
                [36, "md:h-36"],
                [40, "md:h-40"],
                [44, "md:h-44"],
                [48, "md:h-48"],
                [52, "md:h-52"],
                [56, "md:h-56"],
                [60, "md:h-60"],
                [64, "md:h-64"],
                [72, "md:h-72"],
                [80, "md:h-80"],
                [96, "md:h-96"],
                ["auto", "md:h-auto"],
                ["1/2", "md:h-1/2"],
                ["1/3", "md:h-1/3"],
                ["2/3", "md:h-2/3"],
                ["1/4", "md:h-1/4"],
                ["2/4", "md:h-2/4"],
                ["3/4", "md:h-3/4"],
                ["1/5", "md:h-1/5"],
                ["2/5", "md:h-2/5"],
                ["3/5", "md:h-3/5"],
                ["4/5", "md:h-4/5"],
                ["1/6", "md:h-1/6"],
                ["2/6", "md:h-2/6"],
                ["3/6", "md:h-3/6"],
                ["4/6", "md:h-4/6"],
                ["5/6", "md:h-5/6"],
                ["full", "md:h-full"],
                ["screen", "md:h-screen"],
                ["svh", "md:h-svh"],
                ["lvh", "md:h-lvh"],
                ["dvh", "md:h-dvh"],
                ["min", "md:h-min"],
                ["max", "md:h-max"],
                ["fit", "md:h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexHeight, string>([
                [0, "lg:h-0"],
                ["px", "lg:h-px"],
                [0.5, "lg:h-0.5"],
                [1, "lg:h-1"],
                [1.5, "lg:h-1.5"],
                [2, "lg:h-2"],
                [2.5, "lg:h-2.5"],
                [3, "lg:h-3"],
                [3.5, "lg:h-3.5"],
                [4, "lg:h-4"],
                [5, "lg:h-5"],
                [6, "lg:h-6"],
                [7, "lg:h-7"],
                [8, "lg:h-8"],
                [9, "lg:h-9"],
                [10, "lg:h-10"],
                [11, "lg:h-11"],
                [12, "lg:h-12"],
                [14, "lg:h-14"],
                [16, "lg:h-16"],
                [20, "lg:h-20"],
                [24, "lg:h-24"],
                [28, "lg:h-28"],
                [32, "lg:h-32"],
                [36, "lg:h-36"],
                [40, "lg:h-40"],
                [44, "lg:h-44"],
                [48, "lg:h-48"],
                [52, "lg:h-52"],
                [56, "lg:h-56"],
                [60, "lg:h-60"],
                [64, "lg:h-64"],
                [72, "lg:h-72"],
                [80, "lg:h-80"],
                [96, "lg:h-96"],
                ["auto", "lg:h-auto"],
                ["1/2", "lg:h-1/2"],
                ["1/3", "lg:h-1/3"],
                ["2/3", "lg:h-2/3"],
                ["1/4", "lg:h-1/4"],
                ["2/4", "lg:h-2/4"],
                ["3/4", "lg:h-3/4"],
                ["1/5", "lg:h-1/5"],
                ["2/5", "lg:h-2/5"],
                ["3/5", "lg:h-3/5"],
                ["4/5", "lg:h-4/5"],
                ["1/6", "lg:h-1/6"],
                ["2/6", "lg:h-2/6"],
                ["3/6", "lg:h-3/6"],
                ["4/6", "lg:h-4/6"],
                ["5/6", "lg:h-5/6"],
                ["full", "lg:h-full"],
                ["screen", "lg:h-screen"],
                ["svh", "lg:h-svh"],
                ["lvh", "lg:h-lvh"],
                ["dvh", "lg:h-dvh"],
                ["min", "lg:h-min"],
                ["max", "lg:h-max"],
                ["fit", "lg:h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexHeight, string>([
                [0, "xl:h-0"],
                ["px", "xl:h-px"],
                [0.5, "xl:h-0.5"],
                [1, "xl:h-1"],
                [1.5, "xl:h-1.5"],
                [2, "xl:h-2"],
                [2.5, "xl:h-2.5"],
                [3, "xl:h-3"],
                [3.5, "xl:h-3.5"],
                [4, "xl:h-4"],
                [5, "xl:h-5"],
                [6, "xl:h-6"],
                [7, "xl:h-7"],
                [8, "xl:h-8"],
                [9, "xl:h-9"],
                [10, "xl:h-10"],
                [11, "xl:h-11"],
                [12, "xl:h-12"],
                [14, "xl:h-14"],
                [16, "xl:h-16"],
                [20, "xl:h-20"],
                [24, "xl:h-24"],
                [28, "xl:h-28"],
                [32, "xl:h-32"],
                [36, "xl:h-36"],
                [40, "xl:h-40"],
                [44, "xl:h-44"],
                [48, "xl:h-48"],
                [52, "xl:h-52"],
                [56, "xl:h-56"],
                [60, "xl:h-60"],
                [64, "xl:h-64"],
                [72, "xl:h-72"],
                [80, "xl:h-80"],
                [96, "xl:h-96"],
                ["auto", "xl:h-auto"],
                ["1/2", "xl:h-1/2"],
                ["1/3", "xl:h-1/3"],
                ["2/3", "xl:h-2/3"],
                ["1/4", "xl:h-1/4"],
                ["2/4", "xl:h-2/4"],
                ["3/4", "xl:h-3/4"],
                ["1/5", "xl:h-1/5"],
                ["2/5", "xl:h-2/5"],
                ["3/5", "xl:h-3/5"],
                ["4/5", "xl:h-4/5"],
                ["1/6", "xl:h-1/6"],
                ["2/6", "xl:h-2/6"],
                ["3/6", "xl:h-3/6"],
                ["4/6", "xl:h-4/6"],
                ["5/6", "xl:h-5/6"],
                ["full", "xl:h-full"],
                ["screen", "xl:h-screen"],
                ["svh", "xl:h-svh"],
                ["lvh", "xl:h-lvh"],
                ["dvh", "xl:h-dvh"],
                ["min", "xl:h-min"],
                ["max", "xl:h-max"],
                ["fit", "xl:h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexHeight, string>>([
            [
              "xs",
              new Map<FlexHeight, string>([
                [0, "xs:open:h-0"],
                ["px", "xs:open:h-px"],
                [0.5, "xs:open:h-0.5"],
                [1, "xs:open:h-1"],
                [1.5, "xs:open:h-1.5"],
                [2, "xs:open:h-2"],
                [2.5, "xs:open:h-2.5"],
                [3, "xs:open:h-3"],
                [3.5, "xs:open:h-3.5"],
                [4, "xs:open:h-4"],
                [5, "xs:open:h-5"],
                [6, "xs:open:h-6"],
                [7, "xs:open:h-7"],
                [8, "xs:open:h-8"],
                [9, "xs:open:h-9"],
                [10, "xs:open:h-10"],
                [11, "xs:open:h-11"],
                [12, "xs:open:h-12"],
                [14, "xs:open:h-14"],
                [16, "xs:open:h-16"],
                [20, "xs:open:h-20"],
                [24, "xs:open:h-24"],
                [28, "xs:open:h-28"],
                [32, "xs:open:h-32"],
                [36, "xs:open:h-36"],
                [40, "xs:open:h-40"],
                [44, "xs:open:h-44"],
                [48, "xs:open:h-48"],
                [52, "xs:open:h-52"],
                [56, "xs:open:h-56"],
                [60, "xs:open:h-60"],
                [64, "xs:open:h-64"],
                [72, "xs:open:h-72"],
                [80, "xs:open:h-80"],
                [96, "xs:open:h-96"],
                ["auto", "xs:open:h-auto"],
                ["1/2", "xs:open:h-1/2"],
                ["1/3", "xs:open:h-1/3"],
                ["2/3", "xs:open:h-2/3"],
                ["1/4", "xs:open:h-1/4"],
                ["2/4", "xs:open:h-2/4"],
                ["3/4", "xs:open:h-3/4"],
                ["1/5", "xs:open:h-1/5"],
                ["2/5", "xs:open:h-2/5"],
                ["3/5", "xs:open:h-3/5"],
                ["4/5", "xs:open:h-4/5"],
                ["1/6", "xs:open:h-1/6"],
                ["2/6", "xs:open:h-2/6"],
                ["3/6", "xs:open:h-3/6"],
                ["4/6", "xs:open:h-4/6"],
                ["5/6", "xs:open:h-5/6"],
                ["full", "xs:open:h-full"],
                ["screen", "xs:open:h-screen"],
                ["svh", "xs:open:h-svh"],
                ["lvh", "xs:open:h-lvh"],
                ["dvh", "xs:open:h-dvh"],
                ["min", "xs:open:h-min"],
                ["max", "xs:open:h-max"],
                ["fit", "xs:open:h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexHeight, string>([
                [0, "sm:open:h-0"],
                ["px", "sm:open:h-px"],
                [0.5, "sm:open:h-0.5"],
                [1, "sm:open:h-1"],
                [1.5, "sm:open:h-1.5"],
                [2, "sm:open:h-2"],
                [2.5, "sm:open:h-2.5"],
                [3, "sm:open:h-3"],
                [3.5, "sm:open:h-3.5"],
                [4, "sm:open:h-4"],
                [5, "sm:open:h-5"],
                [6, "sm:open:h-6"],
                [7, "sm:open:h-7"],
                [8, "sm:open:h-8"],
                [9, "sm:open:h-9"],
                [10, "sm:open:h-10"],
                [11, "sm:open:h-11"],
                [12, "sm:open:h-12"],
                [14, "sm:open:h-14"],
                [16, "sm:open:h-16"],
                [20, "sm:open:h-20"],
                [24, "sm:open:h-24"],
                [28, "sm:open:h-28"],
                [32, "sm:open:h-32"],
                [36, "sm:open:h-36"],
                [40, "sm:open:h-40"],
                [44, "sm:open:h-44"],
                [48, "sm:open:h-48"],
                [52, "sm:open:h-52"],
                [56, "sm:open:h-56"],
                [60, "sm:open:h-60"],
                [64, "sm:open:h-64"],
                [72, "sm:open:h-72"],
                [80, "sm:open:h-80"],
                [96, "sm:open:h-96"],
                ["auto", "sm:open:h-auto"],
                ["1/2", "sm:open:h-1/2"],
                ["1/3", "sm:open:h-1/3"],
                ["2/3", "sm:open:h-2/3"],
                ["1/4", "sm:open:h-1/4"],
                ["2/4", "sm:open:h-2/4"],
                ["3/4", "sm:open:h-3/4"],
                ["1/5", "sm:open:h-1/5"],
                ["2/5", "sm:open:h-2/5"],
                ["3/5", "sm:open:h-3/5"],
                ["4/5", "sm:open:h-4/5"],
                ["1/6", "sm:open:h-1/6"],
                ["2/6", "sm:open:h-2/6"],
                ["3/6", "sm:open:h-3/6"],
                ["4/6", "sm:open:h-4/6"],
                ["5/6", "sm:open:h-5/6"],
                ["full", "sm:open:h-full"],
                ["screen", "sm:open:h-screen"],
                ["svh", "sm:open:h-svh"],
                ["lvh", "sm:open:h-lvh"],
                ["dvh", "sm:open:h-dvh"],
                ["min", "sm:open:h-min"],
                ["max", "sm:open:h-max"],
                ["fit", "sm:open:h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexHeight, string>([
                [0, "md:open:h-0"],
                ["px", "md:open:h-px"],
                [0.5, "md:open:h-0.5"],
                [1, "md:open:h-1"],
                [1.5, "md:open:h-1.5"],
                [2, "md:open:h-2"],
                [2.5, "md:open:h-2.5"],
                [3, "md:open:h-3"],
                [3.5, "md:open:h-3.5"],
                [4, "md:open:h-4"],
                [5, "md:open:h-5"],
                [6, "md:open:h-6"],
                [7, "md:open:h-7"],
                [8, "md:open:h-8"],
                [9, "md:open:h-9"],
                [10, "md:open:h-10"],
                [11, "md:open:h-11"],
                [12, "md:open:h-12"],
                [14, "md:open:h-14"],
                [16, "md:open:h-16"],
                [20, "md:open:h-20"],
                [24, "md:open:h-24"],
                [28, "md:open:h-28"],
                [32, "md:open:h-32"],
                [36, "md:open:h-36"],
                [40, "md:open:h-40"],
                [44, "md:open:h-44"],
                [48, "md:open:h-48"],
                [52, "md:open:h-52"],
                [56, "md:open:h-56"],
                [60, "md:open:h-60"],
                [64, "md:open:h-64"],
                [72, "md:open:h-72"],
                [80, "md:open:h-80"],
                [96, "md:open:h-96"],
                ["auto", "md:open:h-auto"],
                ["1/2", "md:open:h-1/2"],
                ["1/3", "md:open:h-1/3"],
                ["2/3", "md:open:h-2/3"],
                ["1/4", "md:open:h-1/4"],
                ["2/4", "md:open:h-2/4"],
                ["3/4", "md:open:h-3/4"],
                ["1/5", "md:open:h-1/5"],
                ["2/5", "md:open:h-2/5"],
                ["3/5", "md:open:h-3/5"],
                ["4/5", "md:open:h-4/5"],
                ["1/6", "md:open:h-1/6"],
                ["2/6", "md:open:h-2/6"],
                ["3/6", "md:open:h-3/6"],
                ["4/6", "md:open:h-4/6"],
                ["5/6", "md:open:h-5/6"],
                ["full", "md:open:h-full"],
                ["screen", "md:open:h-screen"],
                ["svh", "md:open:h-svh"],
                ["lvh", "md:open:h-lvh"],
                ["dvh", "md:open:h-dvh"],
                ["min", "md:open:h-min"],
                ["max", "md:open:h-max"],
                ["fit", "md:open:h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexHeight, string>([
                [0, "lg:open:h-0"],
                ["px", "lg:open:h-px"],
                [0.5, "lg:open:h-0.5"],
                [1, "lg:open:h-1"],
                [1.5, "lg:open:h-1.5"],
                [2, "lg:open:h-2"],
                [2.5, "lg:open:h-2.5"],
                [3, "lg:open:h-3"],
                [3.5, "lg:open:h-3.5"],
                [4, "lg:open:h-4"],
                [5, "lg:open:h-5"],
                [6, "lg:open:h-6"],
                [7, "lg:open:h-7"],
                [8, "lg:open:h-8"],
                [9, "lg:open:h-9"],
                [10, "lg:open:h-10"],
                [11, "lg:open:h-11"],
                [12, "lg:open:h-12"],
                [14, "lg:open:h-14"],
                [16, "lg:open:h-16"],
                [20, "lg:open:h-20"],
                [24, "lg:open:h-24"],
                [28, "lg:open:h-28"],
                [32, "lg:open:h-32"],
                [36, "lg:open:h-36"],
                [40, "lg:open:h-40"],
                [44, "lg:open:h-44"],
                [48, "lg:open:h-48"],
                [52, "lg:open:h-52"],
                [56, "lg:open:h-56"],
                [60, "lg:open:h-60"],
                [64, "lg:open:h-64"],
                [72, "lg:open:h-72"],
                [80, "lg:open:h-80"],
                [96, "lg:open:h-96"],
                ["auto", "lg:open:h-auto"],
                ["1/2", "lg:open:h-1/2"],
                ["1/3", "lg:open:h-1/3"],
                ["2/3", "lg:open:h-2/3"],
                ["1/4", "lg:open:h-1/4"],
                ["2/4", "lg:open:h-2/4"],
                ["3/4", "lg:open:h-3/4"],
                ["1/5", "lg:open:h-1/5"],
                ["2/5", "lg:open:h-2/5"],
                ["3/5", "lg:open:h-3/5"],
                ["4/5", "lg:open:h-4/5"],
                ["1/6", "lg:open:h-1/6"],
                ["2/6", "lg:open:h-2/6"],
                ["3/6", "lg:open:h-3/6"],
                ["4/6", "lg:open:h-4/6"],
                ["5/6", "lg:open:h-5/6"],
                ["full", "lg:open:h-full"],
                ["screen", "lg:open:h-screen"],
                ["svh", "lg:open:h-svh"],
                ["lvh", "lg:open:h-lvh"],
                ["dvh", "lg:open:h-dvh"],
                ["min", "lg:open:h-min"],
                ["max", "lg:open:h-max"],
                ["fit", "lg:open:h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexHeight, string>([
                [0, "xl:open:h-0"],
                ["px", "xl:open:h-px"],
                [0.5, "xl:open:h-0.5"],
                [1, "xl:open:h-1"],
                [1.5, "xl:open:h-1.5"],
                [2, "xl:open:h-2"],
                [2.5, "xl:open:h-2.5"],
                [3, "xl:open:h-3"],
                [3.5, "xl:open:h-3.5"],
                [4, "xl:open:h-4"],
                [5, "xl:open:h-5"],
                [6, "xl:open:h-6"],
                [7, "xl:open:h-7"],
                [8, "xl:open:h-8"],
                [9, "xl:open:h-9"],
                [10, "xl:open:h-10"],
                [11, "xl:open:h-11"],
                [12, "xl:open:h-12"],
                [14, "xl:open:h-14"],
                [16, "xl:open:h-16"],
                [20, "xl:open:h-20"],
                [24, "xl:open:h-24"],
                [28, "xl:open:h-28"],
                [32, "xl:open:h-32"],
                [36, "xl:open:h-36"],
                [40, "xl:open:h-40"],
                [44, "xl:open:h-44"],
                [48, "xl:open:h-48"],
                [52, "xl:open:h-52"],
                [56, "xl:open:h-56"],
                [60, "xl:open:h-60"],
                [64, "xl:open:h-64"],
                [72, "xl:open:h-72"],
                [80, "xl:open:h-80"],
                [96, "xl:open:h-96"],
                ["auto", "xl:open:h-auto"],
                ["1/2", "xl:open:h-1/2"],
                ["1/3", "xl:open:h-1/3"],
                ["2/3", "xl:open:h-2/3"],
                ["1/4", "xl:open:h-1/4"],
                ["2/4", "xl:open:h-2/4"],
                ["3/4", "xl:open:h-3/4"],
                ["1/5", "xl:open:h-1/5"],
                ["2/5", "xl:open:h-2/5"],
                ["3/5", "xl:open:h-3/5"],
                ["4/5", "xl:open:h-4/5"],
                ["1/6", "xl:open:h-1/6"],
                ["2/6", "xl:open:h-2/6"],
                ["3/6", "xl:open:h-3/6"],
                ["4/6", "xl:open:h-4/6"],
                ["5/6", "xl:open:h-5/6"],
                ["full", "xl:open:h-full"],
                ["screen", "xl:open:h-screen"],
                ["svh", "xl:open:h-svh"],
                ["lvh", "xl:open:h-lvh"],
                ["dvh", "xl:open:h-dvh"],
                ["min", "xl:open:h-min"],
                ["max", "xl:open:h-max"],
                ["fit", "xl:open:h-fit"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
