import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexMaxHeight } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class MaxHeightBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexMaxHeight, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<
      Map<Breakpoints, Map<FlexMaxHeight, string>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MaxHeightClassesMapping();
    return new MaxHeightBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, grow: FlexMaxHeight) {
    return this.getClassName(breakpoint, grow);
  }
}

class MaxHeightClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexMaxHeight, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexMaxHeight, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<FlexMaxHeight, string>
    >("xs", new Map<FlexMaxHeight, string>([["none", "xs:max-h-none"]]));
  }
  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexMaxHeight, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexMaxHeight, string>>([
            [
              "xs",
              new Map<FlexMaxHeight, string>([
                [0, "xs:active:max-h-0"],
                ["px", "xs:active:max-h-px"],
                [0.5, "xs:active:max-h-0.5"],
                [1, "xs:active:max-h-1"],
                [1.5, "xs:active:max-h-1.5"],
                [2, "xs:active:max-h-2"],
                [2.5, "xs:active:max-h-2.5"],
                [3, "xs:active:max-h-3"],
                [3.5, "xs:active:max-h-3.5"],
                [4, "xs:active:max-h-4"],
                [5, "xs:active:max-h-5"],
                [6, "xs:active:max-h-6"],
                [7, "xs:active:max-h-7"],
                [8, "xs:active:max-h-8"],
                [9, "xs:active:max-h-9"],
                [10, "xs:active:max-h-10"],
                [11, "xs:active:max-h-11"],
                [12, "xs:active:max-h-12"],
                [14, "xs:active:max-h-14"],
                [16, "xs:active:max-h-16"],
                [20, "xs:active:max-h-20"],
                [24, "xs:active:max-h-24"],
                [28, "xs:active:max-h-28"],
                [32, "xs:active:max-h-32"],
                [36, "xs:active:max-h-36"],
                [40, "xs:active:max-h-40"],
                [44, "xs:active:max-h-44"],
                [48, "xs:active:max-h-48"],
                [52, "xs:active:max-h-52"],
                [56, "xs:active:max-h-56"],
                [60, "xs:active:max-h-60"],
                [64, "xs:active:max-h-64"],
                [72, "xs:active:max-h-72"],
                [80, "xs:active:max-h-80"],
                [96, "xs:active:max-h-96"],
                ["none", "xs:active:max-h-none"],
                ["full", "xs:active:max-h-full"],
                ["screen", "xs:active:max-h-screen"],
                ["svh", "xs:active:max-h-svh"],
                ["lvh", "xs:active:max-h-lvh"],
                ["dvh", "xs:active:max-h-dvh"],
                ["min", "xs:active:max-h-min"],
                ["max", "xs:active:max-h-max"],
                ["fit", "xs:active:max-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxHeight, string>([
                [0, "sm:active:max-h-0"],
                ["px", "sm:active:max-h-px"],
                [0.5, "sm:active:max-h-0.5"],
                [1, "sm:active:max-h-1"],
                [1.5, "sm:active:max-h-1.5"],
                [2, "sm:active:max-h-2"],
                [2.5, "sm:active:max-h-2.5"],
                [3, "sm:active:max-h-3"],
                [3.5, "sm:active:max-h-3.5"],
                [4, "sm:active:max-h-4"],
                [5, "sm:active:max-h-5"],
                [6, "sm:active:max-h-6"],
                [7, "sm:active:max-h-7"],
                [8, "sm:active:max-h-8"],
                [9, "sm:active:max-h-9"],
                [10, "sm:active:max-h-10"],
                [11, "sm:active:max-h-11"],
                [12, "sm:active:max-h-12"],
                [14, "sm:active:max-h-14"],
                [16, "sm:active:max-h-16"],
                [20, "sm:active:max-h-20"],
                [24, "sm:active:max-h-24"],
                [28, "sm:active:max-h-28"],
                [32, "sm:active:max-h-32"],
                [36, "sm:active:max-h-36"],
                [40, "sm:active:max-h-40"],
                [44, "sm:active:max-h-44"],
                [48, "sm:active:max-h-48"],
                [52, "sm:active:max-h-52"],
                [56, "sm:active:max-h-56"],
                [60, "sm:active:max-h-60"],
                [64, "sm:active:max-h-64"],
                [72, "sm:active:max-h-72"],
                [80, "sm:active:max-h-80"],
                [96, "sm:active:max-h-96"],
                ["none", "sm:active:max-h-none"],
                ["full", "sm:active:max-h-full"],
                ["screen", "sm:active:max-h-screen"],
                ["svh", "sm:active:max-h-svh"],
                ["lvh", "sm:active:max-h-lvh"],
                ["dvh", "sm:active:max-h-dvh"],
                ["min", "sm:active:max-h-min"],
                ["max", "sm:active:max-h-max"],
                ["fit", "sm:active:max-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxHeight, string>([
                [0, "md:active:max-h-0"],
                ["px", "md:active:max-h-px"],
                [0.5, "md:active:max-h-0.5"],
                [1, "md:active:max-h-1"],
                [1.5, "md:active:max-h-1.5"],
                [2, "md:active:max-h-2"],
                [2.5, "md:active:max-h-2.5"],
                [3, "md:active:max-h-3"],
                [3.5, "md:active:max-h-3.5"],
                [4, "md:active:max-h-4"],
                [5, "md:active:max-h-5"],
                [6, "md:active:max-h-6"],
                [7, "md:active:max-h-7"],
                [8, "md:active:max-h-8"],
                [9, "md:active:max-h-9"],
                [10, "md:active:max-h-10"],
                [11, "md:active:max-h-11"],
                [12, "md:active:max-h-12"],
                [14, "md:active:max-h-14"],
                [16, "md:active:max-h-16"],
                [20, "md:active:max-h-20"],
                [24, "md:active:max-h-24"],
                [28, "md:active:max-h-28"],
                [32, "md:active:max-h-32"],
                [36, "md:active:max-h-36"],
                [40, "md:active:max-h-40"],
                [44, "md:active:max-h-44"],
                [48, "md:active:max-h-48"],
                [52, "md:active:max-h-52"],
                [56, "md:active:max-h-56"],
                [60, "md:active:max-h-60"],
                [64, "md:active:max-h-64"],
                [72, "md:active:max-h-72"],
                [80, "md:active:max-h-80"],
                [96, "md:active:max-h-96"],
                ["none", "md:active:max-h-none"],
                ["full", "md:active:max-h-full"],
                ["screen", "md:active:max-h-screen"],
                ["svh", "md:active:max-h-svh"],
                ["lvh", "md:active:max-h-lvh"],
                ["dvh", "md:active:max-h-dvh"],
                ["min", "md:active:max-h-min"],
                ["max", "md:active:max-h-max"],
                ["fit", "md:active:max-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxHeight, string>([
                [0, "lg:active:max-h-0"],
                ["px", "lg:active:max-h-px"],
                [0.5, "lg:active:max-h-0.5"],
                [1, "lg:active:max-h-1"],
                [1.5, "lg:active:max-h-1.5"],
                [2, "lg:active:max-h-2"],
                [2.5, "lg:active:max-h-2.5"],
                [3, "lg:active:max-h-3"],
                [3.5, "lg:active:max-h-3.5"],
                [4, "lg:active:max-h-4"],
                [5, "lg:active:max-h-5"],
                [6, "lg:active:max-h-6"],
                [7, "lg:active:max-h-7"],
                [8, "lg:active:max-h-8"],
                [9, "lg:active:max-h-9"],
                [10, "lg:active:max-h-10"],
                [11, "lg:active:max-h-11"],
                [12, "lg:active:max-h-12"],
                [14, "lg:active:max-h-14"],
                [16, "lg:active:max-h-16"],
                [20, "lg:active:max-h-20"],
                [24, "lg:active:max-h-24"],
                [28, "lg:active:max-h-28"],
                [32, "lg:active:max-h-32"],
                [36, "lg:active:max-h-36"],
                [40, "lg:active:max-h-40"],
                [44, "lg:active:max-h-44"],
                [48, "lg:active:max-h-48"],
                [52, "lg:active:max-h-52"],
                [56, "lg:active:max-h-56"],
                [60, "lg:active:max-h-60"],
                [64, "lg:active:max-h-64"],
                [72, "lg:active:max-h-72"],
                [80, "lg:active:max-h-80"],
                [96, "lg:active:max-h-96"],
                ["none", "lg:active:max-h-none"],
                ["full", "lg:active:max-h-full"],
                ["screen", "lg:active:max-h-screen"],
                ["svh", "lg:active:max-h-svh"],
                ["lvh", "lg:active:max-h-lvh"],
                ["dvh", "lg:active:max-h-dvh"],
                ["min", "lg:active:max-h-min"],
                ["max", "lg:active:max-h-max"],
                ["fit", "lg:active:max-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxHeight, string>([
                [0, "xl:active:max-h-0"],
                ["px", "xl:active:max-h-px"],
                [0.5, "xl:active:max-h-0.5"],
                [1, "xl:active:max-h-1"],
                [1.5, "xl:active:max-h-1.5"],
                [2, "xl:active:max-h-2"],
                [2.5, "xl:active:max-h-2.5"],
                [3, "xl:active:max-h-3"],
                [3.5, "xl:active:max-h-3.5"],
                [4, "xl:active:max-h-4"],
                [5, "xl:active:max-h-5"],
                [6, "xl:active:max-h-6"],
                [7, "xl:active:max-h-7"],
                [8, "xl:active:max-h-8"],
                [9, "xl:active:max-h-9"],
                [10, "xl:active:max-h-10"],
                [11, "xl:active:max-h-11"],
                [12, "xl:active:max-h-12"],
                [14, "xl:active:max-h-14"],
                [16, "xl:active:max-h-16"],
                [20, "xl:active:max-h-20"],
                [24, "xl:active:max-h-24"],
                [28, "xl:active:max-h-28"],
                [32, "xl:active:max-h-32"],
                [36, "xl:active:max-h-36"],
                [40, "xl:active:max-h-40"],
                [44, "xl:active:max-h-44"],
                [48, "xl:active:max-h-48"],
                [52, "xl:active:max-h-52"],
                [56, "xl:active:max-h-56"],
                [60, "xl:active:max-h-60"],
                [64, "xl:active:max-h-64"],
                [72, "xl:active:max-h-72"],
                [80, "xl:active:max-h-80"],
                [96, "xl:active:max-h-96"],
                ["none", "xl:active:max-h-none"],
                ["full", "xl:active:max-h-full"],
                ["screen", "xl:active:max-h-screen"],
                ["svh", "xl:active:max-h-svh"],
                ["lvh", "xl:active:max-h-lvh"],
                ["dvh", "xl:active:max-h-dvh"],
                ["min", "xl:active:max-h-min"],
                ["max", "xl:active:max-h-max"],
                ["fit", "xl:active:max-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexMaxHeight, string>>([
            [
              "xs",
              new Map<FlexMaxHeight, string>([
                [0, "xs:disabled:max-h-0"],
                ["px", "xs:disabled:max-h-px"],
                [0.5, "xs:disabled:max-h-0.5"],
                [1, "xs:disabled:max-h-1"],
                [1.5, "xs:disabled:max-h-1.5"],
                [2, "xs:disabled:max-h-2"],
                [2.5, "xs:disabled:max-h-2.5"],
                [3, "xs:disabled:max-h-3"],
                [3.5, "xs:disabled:max-h-3.5"],
                [4, "xs:disabled:max-h-4"],
                [5, "xs:disabled:max-h-5"],
                [6, "xs:disabled:max-h-6"],
                [7, "xs:disabled:max-h-7"],
                [8, "xs:disabled:max-h-8"],
                [9, "xs:disabled:max-h-9"],
                [10, "xs:disabled:max-h-10"],
                [11, "xs:disabled:max-h-11"],
                [12, "xs:disabled:max-h-12"],
                [14, "xs:disabled:max-h-14"],
                [16, "xs:disabled:max-h-16"],
                [20, "xs:disabled:max-h-20"],
                [24, "xs:disabled:max-h-24"],
                [28, "xs:disabled:max-h-28"],
                [32, "xs:disabled:max-h-32"],
                [36, "xs:disabled:max-h-36"],
                [40, "xs:disabled:max-h-40"],
                [44, "xs:disabled:max-h-44"],
                [48, "xs:disabled:max-h-48"],
                [52, "xs:disabled:max-h-52"],
                [56, "xs:disabled:max-h-56"],
                [60, "xs:disabled:max-h-60"],
                [64, "xs:disabled:max-h-64"],
                [72, "xs:disabled:max-h-72"],
                [80, "xs:disabled:max-h-80"],
                [96, "xs:disabled:max-h-96"],
                ["none", "xs:disabled:max-h-none"],
                ["full", "xs:disabled:max-h-full"],
                ["screen", "xs:disabled:max-h-screen"],
                ["svh", "xs:disabled:max-h-svh"],
                ["lvh", "xs:disabled:max-h-lvh"],
                ["dvh", "xs:disabled:max-h-dvh"],
                ["min", "xs:disabled:max-h-min"],
                ["max", "xs:disabled:max-h-max"],
                ["fit", "xs:disabled:max-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxHeight, string>([
                [0, "sm:disabled:max-h-0"],
                ["px", "sm:disabled:max-h-px"],
                [0.5, "sm:disabled:max-h-0.5"],
                [1, "sm:disabled:max-h-1"],
                [1.5, "sm:disabled:max-h-1.5"],
                [2, "sm:disabled:max-h-2"],
                [2.5, "sm:disabled:max-h-2.5"],
                [3, "sm:disabled:max-h-3"],
                [3.5, "sm:disabled:max-h-3.5"],
                [4, "sm:disabled:max-h-4"],
                [5, "sm:disabled:max-h-5"],
                [6, "sm:disabled:max-h-6"],
                [7, "sm:disabled:max-h-7"],
                [8, "sm:disabled:max-h-8"],
                [9, "sm:disabled:max-h-9"],
                [10, "sm:disabled:max-h-10"],
                [11, "sm:disabled:max-h-11"],
                [12, "sm:disabled:max-h-12"],
                [14, "sm:disabled:max-h-14"],
                [16, "sm:disabled:max-h-16"],
                [20, "sm:disabled:max-h-20"],
                [24, "sm:disabled:max-h-24"],
                [28, "sm:disabled:max-h-28"],
                [32, "sm:disabled:max-h-32"],
                [36, "sm:disabled:max-h-36"],
                [40, "sm:disabled:max-h-40"],
                [44, "sm:disabled:max-h-44"],
                [48, "sm:disabled:max-h-48"],
                [52, "sm:disabled:max-h-52"],
                [56, "sm:disabled:max-h-56"],
                [60, "sm:disabled:max-h-60"],
                [64, "sm:disabled:max-h-64"],
                [72, "sm:disabled:max-h-72"],
                [80, "sm:disabled:max-h-80"],
                [96, "sm:disabled:max-h-96"],
                ["none", "sm:disabled:max-h-none"],
                ["full", "sm:disabled:max-h-full"],
                ["screen", "sm:disabled:max-h-screen"],
                ["svh", "sm:disabled:max-h-svh"],
                ["lvh", "sm:disabled:max-h-lvh"],
                ["dvh", "sm:disabled:max-h-dvh"],
                ["min", "sm:disabled:max-h-min"],
                ["max", "sm:disabled:max-h-max"],
                ["fit", "sm:disabled:max-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxHeight, string>([
                [0, "md:disabled:max-h-0"],
                ["px", "md:disabled:max-h-px"],
                [0.5, "md:disabled:max-h-0.5"],
                [1, "md:disabled:max-h-1"],
                [1.5, "md:disabled:max-h-1.5"],
                [2, "md:disabled:max-h-2"],
                [2.5, "md:disabled:max-h-2.5"],
                [3, "md:disabled:max-h-3"],
                [3.5, "md:disabled:max-h-3.5"],
                [4, "md:disabled:max-h-4"],
                [5, "md:disabled:max-h-5"],
                [6, "md:disabled:max-h-6"],
                [7, "md:disabled:max-h-7"],
                [8, "md:disabled:max-h-8"],
                [9, "md:disabled:max-h-9"],
                [10, "md:disabled:max-h-10"],
                [11, "md:disabled:max-h-11"],
                [12, "md:disabled:max-h-12"],
                [14, "md:disabled:max-h-14"],
                [16, "md:disabled:max-h-16"],
                [20, "md:disabled:max-h-20"],
                [24, "md:disabled:max-h-24"],
                [28, "md:disabled:max-h-28"],
                [32, "md:disabled:max-h-32"],
                [36, "md:disabled:max-h-36"],
                [40, "md:disabled:max-h-40"],
                [44, "md:disabled:max-h-44"],
                [48, "md:disabled:max-h-48"],
                [52, "md:disabled:max-h-52"],
                [56, "md:disabled:max-h-56"],
                [60, "md:disabled:max-h-60"],
                [64, "md:disabled:max-h-64"],
                [72, "md:disabled:max-h-72"],
                [80, "md:disabled:max-h-80"],
                [96, "md:disabled:max-h-96"],
                ["none", "md:disabled:max-h-none"],
                ["full", "md:disabled:max-h-full"],
                ["screen", "md:disabled:max-h-screen"],
                ["svh", "md:disabled:max-h-svh"],
                ["lvh", "md:disabled:max-h-lvh"],
                ["dvh", "md:disabled:max-h-dvh"],
                ["min", "md:disabled:max-h-min"],
                ["max", "md:disabled:max-h-max"],
                ["fit", "md:disabled:max-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxHeight, string>([
                [0, "lg:disabled:max-h-0"],
                ["px", "lg:disabled:max-h-px"],
                [0.5, "lg:disabled:max-h-0.5"],
                [1, "lg:disabled:max-h-1"],
                [1.5, "lg:disabled:max-h-1.5"],
                [2, "lg:disabled:max-h-2"],
                [2.5, "lg:disabled:max-h-2.5"],
                [3, "lg:disabled:max-h-3"],
                [3.5, "lg:disabled:max-h-3.5"],
                [4, "lg:disabled:max-h-4"],
                [5, "lg:disabled:max-h-5"],
                [6, "lg:disabled:max-h-6"],
                [7, "lg:disabled:max-h-7"],
                [8, "lg:disabled:max-h-8"],
                [9, "lg:disabled:max-h-9"],
                [10, "lg:disabled:max-h-10"],
                [11, "lg:disabled:max-h-11"],
                [12, "lg:disabled:max-h-12"],
                [14, "lg:disabled:max-h-14"],
                [16, "lg:disabled:max-h-16"],
                [20, "lg:disabled:max-h-20"],
                [24, "lg:disabled:max-h-24"],
                [28, "lg:disabled:max-h-28"],
                [32, "lg:disabled:max-h-32"],
                [36, "lg:disabled:max-h-36"],
                [40, "lg:disabled:max-h-40"],
                [44, "lg:disabled:max-h-44"],
                [48, "lg:disabled:max-h-48"],
                [52, "lg:disabled:max-h-52"],
                [56, "lg:disabled:max-h-56"],
                [60, "lg:disabled:max-h-60"],
                [64, "lg:disabled:max-h-64"],
                [72, "lg:disabled:max-h-72"],
                [80, "lg:disabled:max-h-80"],
                [96, "lg:disabled:max-h-96"],
                ["none", "lg:disabled:max-h-none"],
                ["full", "lg:disabled:max-h-full"],
                ["screen", "lg:disabled:max-h-screen"],
                ["svh", "lg:disabled:max-h-svh"],
                ["lvh", "lg:disabled:max-h-lvh"],
                ["dvh", "lg:disabled:max-h-dvh"],
                ["min", "lg:disabled:max-h-min"],
                ["max", "lg:disabled:max-h-max"],
                ["fit", "lg:disabled:max-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxHeight, string>([
                [0, "xl:disabled:max-h-0"],
                ["px", "xl:disabled:max-h-px"],
                [0.5, "xl:disabled:max-h-0.5"],
                [1, "xl:disabled:max-h-1"],
                [1.5, "xl:disabled:max-h-1.5"],
                [2, "xl:disabled:max-h-2"],
                [2.5, "xl:disabled:max-h-2.5"],
                [3, "xl:disabled:max-h-3"],
                [3.5, "xl:disabled:max-h-3.5"],
                [4, "xl:disabled:max-h-4"],
                [5, "xl:disabled:max-h-5"],
                [6, "xl:disabled:max-h-6"],
                [7, "xl:disabled:max-h-7"],
                [8, "xl:disabled:max-h-8"],
                [9, "xl:disabled:max-h-9"],
                [10, "xl:disabled:max-h-10"],
                [11, "xl:disabled:max-h-11"],
                [12, "xl:disabled:max-h-12"],
                [14, "xl:disabled:max-h-14"],
                [16, "xl:disabled:max-h-16"],
                [20, "xl:disabled:max-h-20"],
                [24, "xl:disabled:max-h-24"],
                [28, "xl:disabled:max-h-28"],
                [32, "xl:disabled:max-h-32"],
                [36, "xl:disabled:max-h-36"],
                [40, "xl:disabled:max-h-40"],
                [44, "xl:disabled:max-h-44"],
                [48, "xl:disabled:max-h-48"],
                [52, "xl:disabled:max-h-52"],
                [56, "xl:disabled:max-h-56"],
                [60, "xl:disabled:max-h-60"],
                [64, "xl:disabled:max-h-64"],
                [72, "xl:disabled:max-h-72"],
                [80, "xl:disabled:max-h-80"],
                [96, "xl:disabled:max-h-96"],
                ["none", "xl:disabled:max-h-none"],
                ["full", "xl:disabled:max-h-full"],
                ["screen", "xl:disabled:max-h-screen"],
                ["svh", "xl:disabled:max-h-svh"],
                ["lvh", "xl:disabled:max-h-lvh"],
                ["dvh", "xl:disabled:max-h-dvh"],
                ["min", "xl:disabled:max-h-min"],
                ["max", "xl:disabled:max-h-max"],
                ["fit", "xl:disabled:max-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexMaxHeight, string>>([
            [
              "xs",
              new Map<FlexMaxHeight, string>([
                [0, "xs:hover:max-h-0"],
                ["px", "xs:hover:max-h-px"],
                [0.5, "xs:hover:max-h-0.5"],
                [1, "xs:hover:max-h-1"],
                [1.5, "xs:hover:max-h-1.5"],
                [2, "xs:hover:max-h-2"],
                [2.5, "xs:hover:max-h-2.5"],
                [3, "xs:hover:max-h-3"],
                [3.5, "xs:hover:max-h-3.5"],
                [4, "xs:hover:max-h-4"],
                [5, "xs:hover:max-h-5"],
                [6, "xs:hover:max-h-6"],
                [7, "xs:hover:max-h-7"],
                [8, "xs:hover:max-h-8"],
                [9, "xs:hover:max-h-9"],
                [10, "xs:hover:max-h-10"],
                [11, "xs:hover:max-h-11"],
                [12, "xs:hover:max-h-12"],
                [14, "xs:hover:max-h-14"],
                [16, "xs:hover:max-h-16"],
                [20, "xs:hover:max-h-20"],
                [24, "xs:hover:max-h-24"],
                [28, "xs:hover:max-h-28"],
                [32, "xs:hover:max-h-32"],
                [36, "xs:hover:max-h-36"],
                [40, "xs:hover:max-h-40"],
                [44, "xs:hover:max-h-44"],
                [48, "xs:hover:max-h-48"],
                [52, "xs:hover:max-h-52"],
                [56, "xs:hover:max-h-56"],
                [60, "xs:hover:max-h-60"],
                [64, "xs:hover:max-h-64"],
                [72, "xs:hover:max-h-72"],
                [80, "xs:hover:max-h-80"],
                [96, "xs:hover:max-h-96"],
                ["none", "xs:hover:max-h-none"],
                ["full", "xs:hover:max-h-full"],
                ["screen", "xs:hover:max-h-screen"],
                ["svh", "xs:hover:max-h-svh"],
                ["lvh", "xs:hover:max-h-lvh"],
                ["dvh", "xs:hover:max-h-dvh"],
                ["min", "xs:hover:max-h-min"],
                ["max", "xs:hover:max-h-max"],
                ["fit", "xs:hover:max-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxHeight, string>([
                [0, "sm:hover:max-h-0"],
                ["px", "sm:hover:max-h-px"],
                [0.5, "sm:hover:max-h-0.5"],
                [1, "sm:hover:max-h-1"],
                [1.5, "sm:hover:max-h-1.5"],
                [2, "sm:hover:max-h-2"],
                [2.5, "sm:hover:max-h-2.5"],
                [3, "sm:hover:max-h-3"],
                [3.5, "sm:hover:max-h-3.5"],
                [4, "sm:hover:max-h-4"],
                [5, "sm:hover:max-h-5"],
                [6, "sm:hover:max-h-6"],
                [7, "sm:hover:max-h-7"],
                [8, "sm:hover:max-h-8"],
                [9, "sm:hover:max-h-9"],
                [10, "sm:hover:max-h-10"],
                [11, "sm:hover:max-h-11"],
                [12, "sm:hover:max-h-12"],
                [14, "sm:hover:max-h-14"],
                [16, "sm:hover:max-h-16"],
                [20, "sm:hover:max-h-20"],
                [24, "sm:hover:max-h-24"],
                [28, "sm:hover:max-h-28"],
                [32, "sm:hover:max-h-32"],
                [36, "sm:hover:max-h-36"],
                [40, "sm:hover:max-h-40"],
                [44, "sm:hover:max-h-44"],
                [48, "sm:hover:max-h-48"],
                [52, "sm:hover:max-h-52"],
                [56, "sm:hover:max-h-56"],
                [60, "sm:hover:max-h-60"],
                [64, "sm:hover:max-h-64"],
                [72, "sm:hover:max-h-72"],
                [80, "sm:hover:max-h-80"],
                [96, "sm:hover:max-h-96"],
                ["none", "sm:hover:max-h-none"],
                ["full", "sm:hover:max-h-full"],
                ["screen", "sm:hover:max-h-screen"],
                ["svh", "sm:hover:max-h-svh"],
                ["lvh", "sm:hover:max-h-lvh"],
                ["dvh", "sm:hover:max-h-dvh"],
                ["min", "sm:hover:max-h-min"],
                ["max", "sm:hover:max-h-max"],
                ["fit", "sm:hover:max-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxHeight, string>([
                [0, "md:hover:max-h-0"],
                ["px", "md:hover:max-h-px"],
                [0.5, "md:hover:max-h-0.5"],
                [1, "md:hover:max-h-1"],
                [1.5, "md:hover:max-h-1.5"],
                [2, "md:hover:max-h-2"],
                [2.5, "md:hover:max-h-2.5"],
                [3, "md:hover:max-h-3"],
                [3.5, "md:hover:max-h-3.5"],
                [4, "md:hover:max-h-4"],
                [5, "md:hover:max-h-5"],
                [6, "md:hover:max-h-6"],
                [7, "md:hover:max-h-7"],
                [8, "md:hover:max-h-8"],
                [9, "md:hover:max-h-9"],
                [10, "md:hover:max-h-10"],
                [11, "md:hover:max-h-11"],
                [12, "md:hover:max-h-12"],
                [14, "md:hover:max-h-14"],
                [16, "md:hover:max-h-16"],
                [20, "md:hover:max-h-20"],
                [24, "md:hover:max-h-24"],
                [28, "md:hover:max-h-28"],
                [32, "md:hover:max-h-32"],
                [36, "md:hover:max-h-36"],
                [40, "md:hover:max-h-40"],
                [44, "md:hover:max-h-44"],
                [48, "md:hover:max-h-48"],
                [52, "md:hover:max-h-52"],
                [56, "md:hover:max-h-56"],
                [60, "md:hover:max-h-60"],
                [64, "md:hover:max-h-64"],
                [72, "md:hover:max-h-72"],
                [80, "md:hover:max-h-80"],
                [96, "md:hover:max-h-96"],
                ["none", "md:hover:max-h-none"],
                ["full", "md:hover:max-h-full"],
                ["screen", "md:hover:max-h-screen"],
                ["svh", "md:hover:max-h-svh"],
                ["lvh", "md:hover:max-h-lvh"],
                ["dvh", "md:hover:max-h-dvh"],
                ["min", "md:hover:max-h-min"],
                ["max", "md:hover:max-h-max"],
                ["fit", "md:hover:max-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxHeight, string>([
                [0, "lg:hover:max-h-0"],
                ["px", "lg:hover:max-h-px"],
                [0.5, "lg:hover:max-h-0.5"],
                [1, "lg:hover:max-h-1"],
                [1.5, "lg:hover:max-h-1.5"],
                [2, "lg:hover:max-h-2"],
                [2.5, "lg:hover:max-h-2.5"],
                [3, "lg:hover:max-h-3"],
                [3.5, "lg:hover:max-h-3.5"],
                [4, "lg:hover:max-h-4"],
                [5, "lg:hover:max-h-5"],
                [6, "lg:hover:max-h-6"],
                [7, "lg:hover:max-h-7"],
                [8, "lg:hover:max-h-8"],
                [9, "lg:hover:max-h-9"],
                [10, "lg:hover:max-h-10"],
                [11, "lg:hover:max-h-11"],
                [12, "lg:hover:max-h-12"],
                [14, "lg:hover:max-h-14"],
                [16, "lg:hover:max-h-16"],
                [20, "lg:hover:max-h-20"],
                [24, "lg:hover:max-h-24"],
                [28, "lg:hover:max-h-28"],
                [32, "lg:hover:max-h-32"],
                [36, "lg:hover:max-h-36"],
                [40, "lg:hover:max-h-40"],
                [44, "lg:hover:max-h-44"],
                [48, "lg:hover:max-h-48"],
                [52, "lg:hover:max-h-52"],
                [56, "lg:hover:max-h-56"],
                [60, "lg:hover:max-h-60"],
                [64, "lg:hover:max-h-64"],
                [72, "lg:hover:max-h-72"],
                [80, "lg:hover:max-h-80"],
                [96, "lg:hover:max-h-96"],
                ["none", "lg:hover:max-h-none"],
                ["full", "lg:hover:max-h-full"],
                ["screen", "lg:hover:max-h-screen"],
                ["svh", "lg:hover:max-h-svh"],
                ["lvh", "lg:hover:max-h-lvh"],
                ["dvh", "lg:hover:max-h-dvh"],
                ["min", "lg:hover:max-h-min"],
                ["max", "lg:hover:max-h-max"],
                ["fit", "lg:hover:max-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxHeight, string>([
                [0, "xl:hover:max-h-0"],
                ["px", "xl:hover:max-h-px"],
                [0.5, "xl:hover:max-h-0.5"],
                [1, "xl:hover:max-h-1"],
                [1.5, "xl:hover:max-h-1.5"],
                [2, "xl:hover:max-h-2"],
                [2.5, "xl:hover:max-h-2.5"],
                [3, "xl:hover:max-h-3"],
                [3.5, "xl:hover:max-h-3.5"],
                [4, "xl:hover:max-h-4"],
                [5, "xl:hover:max-h-5"],
                [6, "xl:hover:max-h-6"],
                [7, "xl:hover:max-h-7"],
                [8, "xl:hover:max-h-8"],
                [9, "xl:hover:max-h-9"],
                [10, "xl:hover:max-h-10"],
                [11, "xl:hover:max-h-11"],
                [12, "xl:hover:max-h-12"],
                [14, "xl:hover:max-h-14"],
                [16, "xl:hover:max-h-16"],
                [20, "xl:hover:max-h-20"],
                [24, "xl:hover:max-h-24"],
                [28, "xl:hover:max-h-28"],
                [32, "xl:hover:max-h-32"],
                [36, "xl:hover:max-h-36"],
                [40, "xl:hover:max-h-40"],
                [44, "xl:hover:max-h-44"],
                [48, "xl:hover:max-h-48"],
                [52, "xl:hover:max-h-52"],
                [56, "xl:hover:max-h-56"],
                [60, "xl:hover:max-h-60"],
                [64, "xl:hover:max-h-64"],
                [72, "xl:hover:max-h-72"],
                [80, "xl:hover:max-h-80"],
                [96, "xl:hover:max-h-96"],
                ["none", "xl:hover:max-h-none"],
                ["full", "xl:hover:max-h-full"],
                ["screen", "xl:hover:max-h-screen"],
                ["svh", "xl:hover:max-h-svh"],
                ["lvh", "xl:hover:max-h-lvh"],
                ["dvh", "xl:hover:max-h-dvh"],
                ["min", "xl:hover:max-h-min"],
                ["max", "xl:hover:max-h-max"],
                ["fit", "xl:hover:max-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexMaxHeight, string>>([
            [
              "xs",
              new Map<FlexMaxHeight, string>([
                [0, "xs:max-h-0"],
                ["px", "xs:max-h-px"],
                [0.5, "xs:max-h-0.5"],
                [1, "xs:max-h-1"],
                [1.5, "xs:max-h-1.5"],
                [2, "xs:max-h-2"],
                [2.5, "xs:max-h-2.5"],
                [3, "xs:max-h-3"],
                [3.5, "xs:max-h-3.5"],
                [4, "xs:max-h-4"],
                [5, "xs:max-h-5"],
                [6, "xs:max-h-6"],
                [7, "xs:max-h-7"],
                [8, "xs:max-h-8"],
                [9, "xs:max-h-9"],
                [10, "xs:max-h-10"],
                [11, "xs:max-h-11"],
                [12, "xs:max-h-12"],
                [14, "xs:max-h-14"],
                [16, "xs:max-h-16"],
                [20, "xs:max-h-20"],
                [24, "xs:max-h-24"],
                [28, "xs:max-h-28"],
                [32, "xs:max-h-32"],
                [36, "xs:max-h-36"],
                [40, "xs:max-h-40"],
                [44, "xs:max-h-44"],
                [48, "xs:max-h-48"],
                [52, "xs:max-h-52"],
                [56, "xs:max-h-56"],
                [60, "xs:max-h-60"],
                [64, "xs:max-h-64"],
                [72, "xs:max-h-72"],
                [80, "xs:max-h-80"],
                [96, "xs:max-h-96"],
                ["none", "xs:max-h-none"],
                ["full", "xs:max-h-full"],
                ["screen", "xs:max-h-screen"],
                ["svh", "xs:max-h-svh"],
                ["lvh", "xs:max-h-lvh"],
                ["dvh", "xs:max-h-dvh"],
                ["min", "xs:max-h-min"],
                ["max", "xs:max-h-max"],
                ["fit", "xs:max-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxHeight, string>([
                [0, "sm:max-h-0"],
                ["px", "sm:max-h-px"],
                [0.5, "sm:max-h-0.5"],
                [1, "sm:max-h-1"],
                [1.5, "sm:max-h-1.5"],
                [2, "sm:max-h-2"],
                [2.5, "sm:max-h-2.5"],
                [3, "sm:max-h-3"],
                [3.5, "sm:max-h-3.5"],
                [4, "sm:max-h-4"],
                [5, "sm:max-h-5"],
                [6, "sm:max-h-6"],
                [7, "sm:max-h-7"],
                [8, "sm:max-h-8"],
                [9, "sm:max-h-9"],
                [10, "sm:max-h-10"],
                [11, "sm:max-h-11"],
                [12, "sm:max-h-12"],
                [14, "sm:max-h-14"],
                [16, "sm:max-h-16"],
                [20, "sm:max-h-20"],
                [24, "sm:max-h-24"],
                [28, "sm:max-h-28"],
                [32, "sm:max-h-32"],
                [36, "sm:max-h-36"],
                [40, "sm:max-h-40"],
                [44, "sm:max-h-44"],
                [48, "sm:max-h-48"],
                [52, "sm:max-h-52"],
                [56, "sm:max-h-56"],
                [60, "sm:max-h-60"],
                [64, "sm:max-h-64"],
                [72, "sm:max-h-72"],
                [80, "sm:max-h-80"],
                [96, "sm:max-h-96"],
                ["none", "sm:max-h-none"],
                ["full", "sm:max-h-full"],
                ["screen", "sm:max-h-screen"],
                ["svh", "sm:max-h-svh"],
                ["lvh", "sm:max-h-lvh"],
                ["dvh", "sm:max-h-dvh"],
                ["min", "sm:max-h-min"],
                ["max", "sm:max-h-max"],
                ["fit", "sm:max-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxHeight, string>([
                [0, "md:max-h-0"],
                ["px", "md:max-h-px"],
                [0.5, "md:max-h-0.5"],
                [1, "md:max-h-1"],
                [1.5, "md:max-h-1.5"],
                [2, "md:max-h-2"],
                [2.5, "md:max-h-2.5"],
                [3, "md:max-h-3"],
                [3.5, "md:max-h-3.5"],
                [4, "md:max-h-4"],
                [5, "md:max-h-5"],
                [6, "md:max-h-6"],
                [7, "md:max-h-7"],
                [8, "md:max-h-8"],
                [9, "md:max-h-9"],
                [10, "md:max-h-10"],
                [11, "md:max-h-11"],
                [12, "md:max-h-12"],
                [14, "md:max-h-14"],
                [16, "md:max-h-16"],
                [20, "md:max-h-20"],
                [24, "md:max-h-24"],
                [28, "md:max-h-28"],
                [32, "md:max-h-32"],
                [36, "md:max-h-36"],
                [40, "md:max-h-40"],
                [44, "md:max-h-44"],
                [48, "md:max-h-48"],
                [52, "md:max-h-52"],
                [56, "md:max-h-56"],
                [60, "md:max-h-60"],
                [64, "md:max-h-64"],
                [72, "md:max-h-72"],
                [80, "md:max-h-80"],
                [96, "md:max-h-96"],
                ["none", "md:max-h-none"],
                ["full", "md:max-h-full"],
                ["screen", "md:max-h-screen"],
                ["svh", "md:max-h-svh"],
                ["lvh", "md:max-h-lvh"],
                ["dvh", "md:max-h-dvh"],
                ["min", "md:max-h-min"],
                ["max", "md:max-h-max"],
                ["fit", "md:max-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxHeight, string>([
                [0, "lg:max-h-0"],
                ["px", "lg:max-h-px"],
                [0.5, "lg:max-h-0.5"],
                [1, "lg:max-h-1"],
                [1.5, "lg:max-h-1.5"],
                [2, "lg:max-h-2"],
                [2.5, "lg:max-h-2.5"],
                [3, "lg:max-h-3"],
                [3.5, "lg:max-h-3.5"],
                [4, "lg:max-h-4"],
                [5, "lg:max-h-5"],
                [6, "lg:max-h-6"],
                [7, "lg:max-h-7"],
                [8, "lg:max-h-8"],
                [9, "lg:max-h-9"],
                [10, "lg:max-h-10"],
                [11, "lg:max-h-11"],
                [12, "lg:max-h-12"],
                [14, "lg:max-h-14"],
                [16, "lg:max-h-16"],
                [20, "lg:max-h-20"],
                [24, "lg:max-h-24"],
                [28, "lg:max-h-28"],
                [32, "lg:max-h-32"],
                [36, "lg:max-h-36"],
                [40, "lg:max-h-40"],
                [44, "lg:max-h-44"],
                [48, "lg:max-h-48"],
                [52, "lg:max-h-52"],
                [56, "lg:max-h-56"],
                [60, "lg:max-h-60"],
                [64, "lg:max-h-64"],
                [72, "lg:max-h-72"],
                [80, "lg:max-h-80"],
                [96, "lg:max-h-96"],
                ["none", "lg:max-h-none"],
                ["full", "lg:max-h-full"],
                ["screen", "lg:max-h-screen"],
                ["svh", "lg:max-h-svh"],
                ["lvh", "lg:max-h-lvh"],
                ["dvh", "lg:max-h-dvh"],
                ["min", "lg:max-h-min"],
                ["max", "lg:max-h-max"],
                ["fit", "lg:max-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxHeight, string>([
                [0, "xl:max-h-0"],
                ["px", "xl:max-h-px"],
                [0.5, "xl:max-h-0.5"],
                [1, "xl:max-h-1"],
                [1.5, "xl:max-h-1.5"],
                [2, "xl:max-h-2"],
                [2.5, "xl:max-h-2.5"],
                [3, "xl:max-h-3"],
                [3.5, "xl:max-h-3.5"],
                [4, "xl:max-h-4"],
                [5, "xl:max-h-5"],
                [6, "xl:max-h-6"],
                [7, "xl:max-h-7"],
                [8, "xl:max-h-8"],
                [9, "xl:max-h-9"],
                [10, "xl:max-h-10"],
                [11, "xl:max-h-11"],
                [12, "xl:max-h-12"],
                [14, "xl:max-h-14"],
                [16, "xl:max-h-16"],
                [20, "xl:max-h-20"],
                [24, "xl:max-h-24"],
                [28, "xl:max-h-28"],
                [32, "xl:max-h-32"],
                [36, "xl:max-h-36"],
                [40, "xl:max-h-40"],
                [44, "xl:max-h-44"],
                [48, "xl:max-h-48"],
                [52, "xl:max-h-52"],
                [56, "xl:max-h-56"],
                [60, "xl:max-h-60"],
                [64, "xl:max-h-64"],
                [72, "xl:max-h-72"],
                [80, "xl:max-h-80"],
                [96, "xl:max-h-96"],
                ["none", "xl:max-h-none"],
                ["full", "xl:max-h-full"],
                ["screen", "xl:max-h-screen"],
                ["svh", "xl:max-h-svh"],
                ["lvh", "xl:max-h-lvh"],
                ["dvh", "xl:max-h-dvh"],
                ["min", "xl:max-h-min"],
                ["max", "xl:max-h-max"],
                ["fit", "xl:max-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexMaxHeight, string>>([
            [
              "xs",
              new Map<FlexMaxHeight, string>([
                [0, "xs:open:max-h-0"],
                ["px", "xs:open:max-h-px"],
                [0.5, "xs:open:max-h-0.5"],
                [1, "xs:open:max-h-1"],
                [1.5, "xs:open:max-h-1.5"],
                [2, "xs:open:max-h-2"],
                [2.5, "xs:open:max-h-2.5"],
                [3, "xs:open:max-h-3"],
                [3.5, "xs:open:max-h-3.5"],
                [4, "xs:open:max-h-4"],
                [5, "xs:open:max-h-5"],
                [6, "xs:open:max-h-6"],
                [7, "xs:open:max-h-7"],
                [8, "xs:open:max-h-8"],
                [9, "xs:open:max-h-9"],
                [10, "xs:open:max-h-10"],
                [11, "xs:open:max-h-11"],
                [12, "xs:open:max-h-12"],
                [14, "xs:open:max-h-14"],
                [16, "xs:open:max-h-16"],
                [20, "xs:open:max-h-20"],
                [24, "xs:open:max-h-24"],
                [28, "xs:open:max-h-28"],
                [32, "xs:open:max-h-32"],
                [36, "xs:open:max-h-36"],
                [40, "xs:open:max-h-40"],
                [44, "xs:open:max-h-44"],
                [48, "xs:open:max-h-48"],
                [52, "xs:open:max-h-52"],
                [56, "xs:open:max-h-56"],
                [60, "xs:open:max-h-60"],
                [64, "xs:open:max-h-64"],
                [72, "xs:open:max-h-72"],
                [80, "xs:open:max-h-80"],
                [96, "xs:open:max-h-96"],
                ["none", "xs:open:max-h-none"],
                ["full", "xs:open:max-h-full"],
                ["screen", "xs:open:max-h-screen"],
                ["svh", "xs:open:max-h-svh"],
                ["lvh", "xs:open:max-h-lvh"],
                ["dvh", "xs:open:max-h-dvh"],
                ["min", "xs:open:max-h-min"],
                ["max", "xs:open:max-h-max"],
                ["fit", "xs:open:max-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxHeight, string>([
                [0, "sm:open:max-h-0"],
                ["px", "sm:open:max-h-px"],
                [0.5, "sm:open:max-h-0.5"],
                [1, "sm:open:max-h-1"],
                [1.5, "sm:open:max-h-1.5"],
                [2, "sm:open:max-h-2"],
                [2.5, "sm:open:max-h-2.5"],
                [3, "sm:open:max-h-3"],
                [3.5, "sm:open:max-h-3.5"],
                [4, "sm:open:max-h-4"],
                [5, "sm:open:max-h-5"],
                [6, "sm:open:max-h-6"],
                [7, "sm:open:max-h-7"],
                [8, "sm:open:max-h-8"],
                [9, "sm:open:max-h-9"],
                [10, "sm:open:max-h-10"],
                [11, "sm:open:max-h-11"],
                [12, "sm:open:max-h-12"],
                [14, "sm:open:max-h-14"],
                [16, "sm:open:max-h-16"],
                [20, "sm:open:max-h-20"],
                [24, "sm:open:max-h-24"],
                [28, "sm:open:max-h-28"],
                [32, "sm:open:max-h-32"],
                [36, "sm:open:max-h-36"],
                [40, "sm:open:max-h-40"],
                [44, "sm:open:max-h-44"],
                [48, "sm:open:max-h-48"],
                [52, "sm:open:max-h-52"],
                [56, "sm:open:max-h-56"],
                [60, "sm:open:max-h-60"],
                [64, "sm:open:max-h-64"],
                [72, "sm:open:max-h-72"],
                [80, "sm:open:max-h-80"],
                [96, "sm:open:max-h-96"],
                ["none", "sm:open:max-h-none"],
                ["full", "sm:open:max-h-full"],
                ["screen", "sm:open:max-h-screen"],
                ["svh", "sm:open:max-h-svh"],
                ["lvh", "sm:open:max-h-lvh"],
                ["dvh", "sm:open:max-h-dvh"],
                ["min", "sm:open:max-h-min"],
                ["max", "sm:open:max-h-max"],
                ["fit", "sm:open:max-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxHeight, string>([
                [0, "md:open:max-h-0"],
                ["px", "md:open:max-h-px"],
                [0.5, "md:open:max-h-0.5"],
                [1, "md:open:max-h-1"],
                [1.5, "md:open:max-h-1.5"],
                [2, "md:open:max-h-2"],
                [2.5, "md:open:max-h-2.5"],
                [3, "md:open:max-h-3"],
                [3.5, "md:open:max-h-3.5"],
                [4, "md:open:max-h-4"],
                [5, "md:open:max-h-5"],
                [6, "md:open:max-h-6"],
                [7, "md:open:max-h-7"],
                [8, "md:open:max-h-8"],
                [9, "md:open:max-h-9"],
                [10, "md:open:max-h-10"],
                [11, "md:open:max-h-11"],
                [12, "md:open:max-h-12"],
                [14, "md:open:max-h-14"],
                [16, "md:open:max-h-16"],
                [20, "md:open:max-h-20"],
                [24, "md:open:max-h-24"],
                [28, "md:open:max-h-28"],
                [32, "md:open:max-h-32"],
                [36, "md:open:max-h-36"],
                [40, "md:open:max-h-40"],
                [44, "md:open:max-h-44"],
                [48, "md:open:max-h-48"],
                [52, "md:open:max-h-52"],
                [56, "md:open:max-h-56"],
                [60, "md:open:max-h-60"],
                [64, "md:open:max-h-64"],
                [72, "md:open:max-h-72"],
                [80, "md:open:max-h-80"],
                [96, "md:open:max-h-96"],
                ["none", "md:open:max-h-none"],
                ["full", "md:open:max-h-full"],
                ["screen", "md:open:max-h-screen"],
                ["svh", "md:open:max-h-svh"],
                ["lvh", "md:open:max-h-lvh"],
                ["dvh", "md:open:max-h-dvh"],
                ["min", "md:open:max-h-min"],
                ["max", "md:open:max-h-max"],
                ["fit", "md:open:max-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxHeight, string>([
                [0, "lg:open:max-h-0"],
                ["px", "lg:open:max-h-px"],
                [0.5, "lg:open:max-h-0.5"],
                [1, "lg:open:max-h-1"],
                [1.5, "lg:open:max-h-1.5"],
                [2, "lg:open:max-h-2"],
                [2.5, "lg:open:max-h-2.5"],
                [3, "lg:open:max-h-3"],
                [3.5, "lg:open:max-h-3.5"],
                [4, "lg:open:max-h-4"],
                [5, "lg:open:max-h-5"],
                [6, "lg:open:max-h-6"],
                [7, "lg:open:max-h-7"],
                [8, "lg:open:max-h-8"],
                [9, "lg:open:max-h-9"],
                [10, "lg:open:max-h-10"],
                [11, "lg:open:max-h-11"],
                [12, "lg:open:max-h-12"],
                [14, "lg:open:max-h-14"],
                [16, "lg:open:max-h-16"],
                [20, "lg:open:max-h-20"],
                [24, "lg:open:max-h-24"],
                [28, "lg:open:max-h-28"],
                [32, "lg:open:max-h-32"],
                [36, "lg:open:max-h-36"],
                [40, "lg:open:max-h-40"],
                [44, "lg:open:max-h-44"],
                [48, "lg:open:max-h-48"],
                [52, "lg:open:max-h-52"],
                [56, "lg:open:max-h-56"],
                [60, "lg:open:max-h-60"],
                [64, "lg:open:max-h-64"],
                [72, "lg:open:max-h-72"],
                [80, "lg:open:max-h-80"],
                [96, "lg:open:max-h-96"],
                ["none", "lg:open:max-h-none"],
                ["full", "lg:open:max-h-full"],
                ["screen", "lg:open:max-h-screen"],
                ["svh", "lg:open:max-h-svh"],
                ["lvh", "lg:open:max-h-lvh"],
                ["dvh", "lg:open:max-h-dvh"],
                ["min", "lg:open:max-h-min"],
                ["max", "lg:open:max-h-max"],
                ["fit", "lg:open:max-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxHeight, string>([
                [0, "xl:open:max-h-0"],
                ["px", "xl:open:max-h-px"],
                [0.5, "xl:open:max-h-0.5"],
                [1, "xl:open:max-h-1"],
                [1.5, "xl:open:max-h-1.5"],
                [2, "xl:open:max-h-2"],
                [2.5, "xl:open:max-h-2.5"],
                [3, "xl:open:max-h-3"],
                [3.5, "xl:open:max-h-3.5"],
                [4, "xl:open:max-h-4"],
                [5, "xl:open:max-h-5"],
                [6, "xl:open:max-h-6"],
                [7, "xl:open:max-h-7"],
                [8, "xl:open:max-h-8"],
                [9, "xl:open:max-h-9"],
                [10, "xl:open:max-h-10"],
                [11, "xl:open:max-h-11"],
                [12, "xl:open:max-h-12"],
                [14, "xl:open:max-h-14"],
                [16, "xl:open:max-h-16"],
                [20, "xl:open:max-h-20"],
                [24, "xl:open:max-h-24"],
                [28, "xl:open:max-h-28"],
                [32, "xl:open:max-h-32"],
                [36, "xl:open:max-h-36"],
                [40, "xl:open:max-h-40"],
                [44, "xl:open:max-h-44"],
                [48, "xl:open:max-h-48"],
                [52, "xl:open:max-h-52"],
                [56, "xl:open:max-h-56"],
                [60, "xl:open:max-h-60"],
                [64, "xl:open:max-h-64"],
                [72, "xl:open:max-h-72"],
                [80, "xl:open:max-h-80"],
                [96, "xl:open:max-h-96"],
                ["none", "xl:open:max-h-none"],
                ["full", "xl:open:max-h-full"],
                ["screen", "xl:open:max-h-screen"],
                ["svh", "xl:open:max-h-svh"],
                ["lvh", "xl:open:max-h-lvh"],
                ["dvh", "xl:open:max-h-dvh"],
                ["min", "xl:open:max-h-min"],
                ["max", "xl:open:max-h-max"],
                ["fit", "xl:open:max-h-fit"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
