import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexMinHeight } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class MinHeightBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexMinHeight, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<
      Map<Breakpoints, Map<FlexMinHeight, string>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MinHeightClassesMapping();
    return new MinHeightBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, grow: FlexMinHeight) {
    return this.getClassName(breakpoint, grow);
  }
}

class MinHeightClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexMinHeight, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexMinHeight, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<FlexMinHeight, string>
    >("xs", new Map<FlexMinHeight, string>([["fit", "min-h-fit"]]));
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexMinHeight, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexMinHeight, string>>([
            [
              "xs",
              new Map<FlexMinHeight, string>([
                [0, "xs:active:min-h-0"],
                [1, "xs:active:min-h-1"],
                [2, "xs:active:min-h-2"],
                [3, "xs:active:min-h-3"],
                [4, "xs:active:min-h-4"],
                [5, "xs:active:min-h-5"],
                [6, "xs:active:min-h-6"],
                [7, "xs:active:min-h-7"],
                [8, "xs:active:min-h-8"],
                [9, "xs:active:min-h-9"],
                [10, "xs:active:min-h-10"],
                [11, "xs:active:min-h-11"],
                [12, "xs:active:min-h-12"],
                [14, "xs:active:min-h-14"],
                [16, "xs:active:min-h-16"],
                [20, "xs:active:min-h-20"],
                [24, "xs:active:min-h-24"],
                [28, "xs:active:min-h-28"],
                [32, "xs:active:min-h-32"],
                [36, "xs:active:min-h-36"],
                [40, "xs:active:min-h-40"],
                [44, "xs:active:min-h-44"],
                [48, "xs:active:min-h-48"],
                [52, "xs:active:min-h-52"],
                [56, "xs:active:min-h-56"],
                [60, "xs:active:min-h-60"],
                [64, "xs:active:min-h-64"],
                [72, "xs:active:min-h-72"],
                [80, "xs:active:min-h-80"],
                [96, "xs:active:min-h-96"],
                ["px", "xs:active:min-h-px"],
                [0.5, "xs:active:min-h-0.5"],
                [1.5, "xs:active:min-h-1.5"],
                [2.5, "xs:active:min-h-2.5"],
                [3.5, "xs:active:min-h-3.5"],
                ["full", "xs:active:min-h-full"],
                ["screen", "xs:active:min-h-screen"],
                ["svh", "xs:active:min-h-svh"],
                ["lvh", "xs:active:min-h-lvh"],
                ["dvh", "xs:active:min-h-dvh"],
                ["min", "xs:active:min-h-min"],
                ["max", "xs:active:min-h-max"],
                ["fit", "xs:active:min-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinHeight, string>([
                [0, "sm:active:min-h-0"],
                [1, "sm:active:min-h-1"],
                [2, "sm:active:min-h-2"],
                [3, "sm:active:min-h-3"],
                [4, "sm:active:min-h-4"],
                [5, "sm:active:min-h-5"],
                [6, "sm:active:min-h-6"],
                [7, "sm:active:min-h-7"],
                [8, "sm:active:min-h-8"],
                [9, "sm:active:min-h-9"],
                [10, "sm:active:min-h-10"],
                [11, "sm:active:min-h-11"],
                [12, "sm:active:min-h-12"],
                [14, "sm:active:min-h-14"],
                [16, "sm:active:min-h-16"],
                [20, "sm:active:min-h-20"],
                [24, "sm:active:min-h-24"],
                [28, "sm:active:min-h-28"],
                [32, "sm:active:min-h-32"],
                [36, "sm:active:min-h-36"],
                [40, "sm:active:min-h-40"],
                [44, "sm:active:min-h-44"],
                [48, "sm:active:min-h-48"],
                [52, "sm:active:min-h-52"],
                [56, "sm:active:min-h-56"],
                [60, "sm:active:min-h-60"],
                [64, "sm:active:min-h-64"],
                [72, "sm:active:min-h-72"],
                [80, "sm:active:min-h-80"],
                [96, "sm:active:min-h-96"],
                ["px", "sm:active:min-h-px"],
                [0.5, "sm:active:min-h-0.5"],
                [1.5, "sm:active:min-h-1.5"],
                [2.5, "sm:active:min-h-2.5"],
                [3.5, "sm:active:min-h-3.5"],
                ["full", "sm:active:min-h-full"],
                ["screen", "sm:active:min-h-screen"],
                ["svh", "sm:active:min-h-svh"],
                ["lvh", "sm:active:min-h-lvh"],
                ["dvh", "sm:active:min-h-dvh"],
                ["min", "sm:active:min-h-min"],
                ["max", "sm:active:min-h-max"],
                ["fit", "sm:active:min-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinHeight, string>([
                [0, "md:active:min-h-0"],
                [1, "md:active:min-h-1"],
                [2, "md:active:min-h-2"],
                [3, "md:active:min-h-3"],
                [4, "md:active:min-h-4"],
                [5, "md:active:min-h-5"],
                [6, "md:active:min-h-6"],
                [7, "md:active:min-h-7"],
                [8, "md:active:min-h-8"],
                [9, "md:active:min-h-9"],
                [10, "md:active:min-h-10"],
                [11, "md:active:min-h-11"],
                [12, "md:active:min-h-12"],
                [14, "md:active:min-h-14"],
                [16, "md:active:min-h-16"],
                [20, "md:active:min-h-20"],
                [24, "md:active:min-h-24"],
                [28, "md:active:min-h-28"],
                [32, "md:active:min-h-32"],
                [36, "md:active:min-h-36"],
                [40, "md:active:min-h-40"],
                [44, "md:active:min-h-44"],
                [48, "md:active:min-h-48"],
                [52, "md:active:min-h-52"],
                [56, "md:active:min-h-56"],
                [60, "md:active:min-h-60"],
                [64, "md:active:min-h-64"],
                [72, "md:active:min-h-72"],
                [80, "md:active:min-h-80"],
                [96, "md:active:min-h-96"],
                ["px", "md:active:min-h-px"],
                [0.5, "md:active:min-h-0.5"],
                [1.5, "md:active:min-h-1.5"],
                [2.5, "md:active:min-h-2.5"],
                [3.5, "md:active:min-h-3.5"],
                ["full", "md:active:min-h-full"],
                ["screen", "md:active:min-h-screen"],
                ["svh", "md:active:min-h-svh"],
                ["lvh", "md:active:min-h-lvh"],
                ["dvh", "md:active:min-h-dvh"],
                ["min", "md:active:min-h-min"],
                ["max", "md:active:min-h-max"],
                ["fit", "md:active:min-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinHeight, string>([
                [0, "lg:active:min-h-0"],
                [1, "lg:active:min-h-1"],
                [2, "lg:active:min-h-2"],
                [3, "lg:active:min-h-3"],
                [4, "lg:active:min-h-4"],
                [5, "lg:active:min-h-5"],
                [6, "lg:active:min-h-6"],
                [7, "lg:active:min-h-7"],
                [8, "lg:active:min-h-8"],
                [9, "lg:active:min-h-9"],
                [10, "lg:active:min-h-10"],
                [11, "lg:active:min-h-11"],
                [12, "lg:active:min-h-12"],
                [14, "lg:active:min-h-14"],
                [16, "lg:active:min-h-16"],
                [20, "lg:active:min-h-20"],
                [24, "lg:active:min-h-24"],
                [28, "lg:active:min-h-28"],
                [32, "lg:active:min-h-32"],
                [36, "lg:active:min-h-36"],
                [40, "lg:active:min-h-40"],
                [44, "lg:active:min-h-44"],
                [48, "lg:active:min-h-48"],
                [52, "lg:active:min-h-52"],
                [56, "lg:active:min-h-56"],
                [60, "lg:active:min-h-60"],
                [64, "lg:active:min-h-64"],
                [72, "lg:active:min-h-72"],
                [80, "lg:active:min-h-80"],
                [96, "lg:active:min-h-96"],
                ["px", "lg:active:min-h-px"],
                [0.5, "lg:active:min-h-0.5"],
                [1.5, "lg:active:min-h-1.5"],
                [2.5, "lg:active:min-h-2.5"],
                [3.5, "lg:active:min-h-3.5"],
                ["full", "lg:active:min-h-full"],
                ["screen", "lg:active:min-h-screen"],
                ["svh", "lg:active:min-h-svh"],
                ["lvh", "lg:active:min-h-lvh"],
                ["dvh", "lg:active:min-h-dvh"],
                ["min", "lg:active:min-h-min"],
                ["max", "lg:active:min-h-max"],
                ["fit", "lg:active:min-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinHeight, string>([
                [0, "xl:active:min-h-0"],
                [1, "xl:active:min-h-1"],
                [2, "xl:active:min-h-2"],
                [3, "xl:active:min-h-3"],
                [4, "xl:active:min-h-4"],
                [5, "xl:active:min-h-5"],
                [6, "xl:active:min-h-6"],
                [7, "xl:active:min-h-7"],
                [8, "xl:active:min-h-8"],
                [9, "xl:active:min-h-9"],
                [10, "xl:active:min-h-10"],
                [11, "xl:active:min-h-11"],
                [12, "xl:active:min-h-12"],
                [14, "xl:active:min-h-14"],
                [16, "xl:active:min-h-16"],
                [20, "xl:active:min-h-20"],
                [24, "xl:active:min-h-24"],
                [28, "xl:active:min-h-28"],
                [32, "xl:active:min-h-32"],
                [36, "xl:active:min-h-36"],
                [40, "xl:active:min-h-40"],
                [44, "xl:active:min-h-44"],
                [48, "xl:active:min-h-48"],
                [52, "xl:active:min-h-52"],
                [56, "xl:active:min-h-56"],
                [60, "xl:active:min-h-60"],
                [64, "xl:active:min-h-64"],
                [72, "xl:active:min-h-72"],
                [80, "xl:active:min-h-80"],
                [96, "xl:active:min-h-96"],
                ["px", "xl:active:min-h-px"],
                [0.5, "xl:active:min-h-0.5"],
                [1.5, "xl:active:min-h-1.5"],
                [2.5, "xl:active:min-h-2.5"],
                [3.5, "xl:active:min-h-3.5"],
                ["full", "xl:active:min-h-full"],
                ["screen", "xl:active:min-h-screen"],
                ["svh", "xl:active:min-h-svh"],
                ["lvh", "xl:active:min-h-lvh"],
                ["dvh", "xl:active:min-h-dvh"],
                ["min", "xl:active:min-h-min"],
                ["max", "xl:active:min-h-max"],
                ["fit", "xl:active:min-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexMinHeight, string>>([
            [
              "xs",
              new Map<FlexMinHeight, string>([
                [0, "xs:disabled:min-h-0"],
                [1, "xs:disabled:min-h-1"],
                [2, "xs:disabled:min-h-2"],
                [3, "xs:disabled:min-h-3"],
                [4, "xs:disabled:min-h-4"],
                [5, "xs:disabled:min-h-5"],
                [6, "xs:disabled:min-h-6"],
                [7, "xs:disabled:min-h-7"],
                [8, "xs:disabled:min-h-8"],
                [9, "xs:disabled:min-h-9"],
                [10, "xs:disabled:min-h-10"],
                [11, "xs:disabled:min-h-11"],
                [12, "xs:disabled:min-h-12"],
                [14, "xs:disabled:min-h-14"],
                [16, "xs:disabled:min-h-16"],
                [20, "xs:disabled:min-h-20"],
                [24, "xs:disabled:min-h-24"],
                [28, "xs:disabled:min-h-28"],
                [32, "xs:disabled:min-h-32"],
                [36, "xs:disabled:min-h-36"],
                [40, "xs:disabled:min-h-40"],
                [44, "xs:disabled:min-h-44"],
                [48, "xs:disabled:min-h-48"],
                [52, "xs:disabled:min-h-52"],
                [56, "xs:disabled:min-h-56"],
                [60, "xs:disabled:min-h-60"],
                [64, "xs:disabled:min-h-64"],
                [72, "xs:disabled:min-h-72"],
                [80, "xs:disabled:min-h-80"],
                [96, "xs:disabled:min-h-96"],
                ["px", "xs:disabled:min-h-px"],
                [0.5, "xs:disabled:min-h-0.5"],
                [1.5, "xs:disabled:min-h-1.5"],
                [2.5, "xs:disabled:min-h-2.5"],
                [3.5, "xs:disabled:min-h-3.5"],
                ["full", "xs:disabled:min-h-full"],
                ["screen", "xs:disabled:min-h-screen"],
                ["svh", "xs:disabled:min-h-svh"],
                ["lvh", "xs:disabled:min-h-lvh"],
                ["dvh", "xs:disabled:min-h-dvh"],
                ["min", "xs:disabled:min-h-min"],
                ["max", "xs:disabled:min-h-max"],
                ["fit", "xs:disabled:min-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinHeight, string>([
                [0, "sm:disabled:min-h-0"],
                [1, "sm:disabled:min-h-1"],
                [2, "sm:disabled:min-h-2"],
                [3, "sm:disabled:min-h-3"],
                [4, "sm:disabled:min-h-4"],
                [5, "sm:disabled:min-h-5"],
                [6, "sm:disabled:min-h-6"],
                [7, "sm:disabled:min-h-7"],
                [8, "sm:disabled:min-h-8"],
                [9, "sm:disabled:min-h-9"],
                [10, "sm:disabled:min-h-10"],
                [11, "sm:disabled:min-h-11"],
                [12, "sm:disabled:min-h-12"],
                [14, "sm:disabled:min-h-14"],
                [16, "sm:disabled:min-h-16"],
                [20, "sm:disabled:min-h-20"],
                [24, "sm:disabled:min-h-24"],
                [28, "sm:disabled:min-h-28"],
                [32, "sm:disabled:min-h-32"],
                [36, "sm:disabled:min-h-36"],
                [40, "sm:disabled:min-h-40"],
                [44, "sm:disabled:min-h-44"],
                [48, "sm:disabled:min-h-48"],
                [52, "sm:disabled:min-h-52"],
                [56, "sm:disabled:min-h-56"],
                [60, "sm:disabled:min-h-60"],
                [64, "sm:disabled:min-h-64"],
                [72, "sm:disabled:min-h-72"],
                [80, "sm:disabled:min-h-80"],
                [96, "sm:disabled:min-h-96"],
                ["px", "sm:disabled:min-h-px"],
                [0.5, "sm:disabled:min-h-0.5"],
                [1.5, "sm:disabled:min-h-1.5"],
                [2.5, "sm:disabled:min-h-2.5"],
                [3.5, "sm:disabled:min-h-3.5"],
                ["full", "sm:disabled:min-h-full"],
                ["screen", "sm:disabled:min-h-screen"],
                ["svh", "sm:disabled:min-h-svh"],
                ["lvh", "sm:disabled:min-h-lvh"],
                ["dvh", "sm:disabled:min-h-dvh"],
                ["min", "sm:disabled:min-h-min"],
                ["max", "sm:disabled:min-h-max"],
                ["fit", "sm:disabled:min-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinHeight, string>([
                [0, "md:disabled:min-h-0"],
                [1, "md:disabled:min-h-1"],
                [2, "md:disabled:min-h-2"],
                [3, "md:disabled:min-h-3"],
                [4, "md:disabled:min-h-4"],
                [5, "md:disabled:min-h-5"],
                [6, "md:disabled:min-h-6"],
                [7, "md:disabled:min-h-7"],
                [8, "md:disabled:min-h-8"],
                [9, "md:disabled:min-h-9"],
                [10, "md:disabled:min-h-10"],
                [11, "md:disabled:min-h-11"],
                [12, "md:disabled:min-h-12"],
                [14, "md:disabled:min-h-14"],
                [16, "md:disabled:min-h-16"],
                [20, "md:disabled:min-h-20"],
                [24, "md:disabled:min-h-24"],
                [28, "md:disabled:min-h-28"],
                [32, "md:disabled:min-h-32"],
                [36, "md:disabled:min-h-36"],
                [40, "md:disabled:min-h-40"],
                [44, "md:disabled:min-h-44"],
                [48, "md:disabled:min-h-48"],
                [52, "md:disabled:min-h-52"],
                [56, "md:disabled:min-h-56"],
                [60, "md:disabled:min-h-60"],
                [64, "md:disabled:min-h-64"],
                [72, "md:disabled:min-h-72"],
                [80, "md:disabled:min-h-80"],
                [96, "md:disabled:min-h-96"],
                ["px", "md:disabled:min-h-px"],
                [0.5, "md:disabled:min-h-0.5"],
                [1.5, "md:disabled:min-h-1.5"],
                [2.5, "md:disabled:min-h-2.5"],
                [3.5, "md:disabled:min-h-3.5"],
                ["full", "md:disabled:min-h-full"],
                ["screen", "md:disabled:min-h-screen"],
                ["svh", "md:disabled:min-h-svh"],
                ["lvh", "md:disabled:min-h-lvh"],
                ["dvh", "md:disabled:min-h-dvh"],
                ["min", "md:disabled:min-h-min"],
                ["max", "md:disabled:min-h-max"],
                ["fit", "md:disabled:min-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinHeight, string>([
                [0, "lg:disabled:min-h-0"],
                [1, "lg:disabled:min-h-1"],
                [2, "lg:disabled:min-h-2"],
                [3, "lg:disabled:min-h-3"],
                [4, "lg:disabled:min-h-4"],
                [5, "lg:disabled:min-h-5"],
                [6, "lg:disabled:min-h-6"],
                [7, "lg:disabled:min-h-7"],
                [8, "lg:disabled:min-h-8"],
                [9, "lg:disabled:min-h-9"],
                [10, "lg:disabled:min-h-10"],
                [11, "lg:disabled:min-h-11"],
                [12, "lg:disabled:min-h-12"],
                [14, "lg:disabled:min-h-14"],
                [16, "lg:disabled:min-h-16"],
                [20, "lg:disabled:min-h-20"],
                [24, "lg:disabled:min-h-24"],
                [28, "lg:disabled:min-h-28"],
                [32, "lg:disabled:min-h-32"],
                [36, "lg:disabled:min-h-36"],
                [40, "lg:disabled:min-h-40"],
                [44, "lg:disabled:min-h-44"],
                [48, "lg:disabled:min-h-48"],
                [52, "lg:disabled:min-h-52"],
                [56, "lg:disabled:min-h-56"],
                [60, "lg:disabled:min-h-60"],
                [64, "lg:disabled:min-h-64"],
                [72, "lg:disabled:min-h-72"],
                [80, "lg:disabled:min-h-80"],
                [96, "lg:disabled:min-h-96"],
                ["px", "lg:disabled:min-h-px"],
                [0.5, "lg:disabled:min-h-0.5"],
                [1.5, "lg:disabled:min-h-1.5"],
                [2.5, "lg:disabled:min-h-2.5"],
                [3.5, "lg:disabled:min-h-3.5"],
                ["full", "lg:disabled:min-h-full"],
                ["screen", "lg:disabled:min-h-screen"],
                ["svh", "lg:disabled:min-h-svh"],
                ["lvh", "lg:disabled:min-h-lvh"],
                ["dvh", "lg:disabled:min-h-dvh"],
                ["min", "lg:disabled:min-h-min"],
                ["max", "lg:disabled:min-h-max"],
                ["fit", "lg:disabled:min-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinHeight, string>([
                [0, "xl:disabled:min-h-0"],
                [1, "xl:disabled:min-h-1"],
                [2, "xl:disabled:min-h-2"],
                [3, "xl:disabled:min-h-3"],
                [4, "xl:disabled:min-h-4"],
                [5, "xl:disabled:min-h-5"],
                [6, "xl:disabled:min-h-6"],
                [7, "xl:disabled:min-h-7"],
                [8, "xl:disabled:min-h-8"],
                [9, "xl:disabled:min-h-9"],
                [10, "xl:disabled:min-h-10"],
                [11, "xl:disabled:min-h-11"],
                [12, "xl:disabled:min-h-12"],
                [14, "xl:disabled:min-h-14"],
                [16, "xl:disabled:min-h-16"],
                [20, "xl:disabled:min-h-20"],
                [24, "xl:disabled:min-h-24"],
                [28, "xl:disabled:min-h-28"],
                [32, "xl:disabled:min-h-32"],
                [36, "xl:disabled:min-h-36"],
                [40, "xl:disabled:min-h-40"],
                [44, "xl:disabled:min-h-44"],
                [48, "xl:disabled:min-h-48"],
                [52, "xl:disabled:min-h-52"],
                [56, "xl:disabled:min-h-56"],
                [60, "xl:disabled:min-h-60"],
                [64, "xl:disabled:min-h-64"],
                [72, "xl:disabled:min-h-72"],
                [80, "xl:disabled:min-h-80"],
                [96, "xl:disabled:min-h-96"],
                ["px", "xl:disabled:min-h-px"],
                [0.5, "xl:disabled:min-h-0.5"],
                [1.5, "xl:disabled:min-h-1.5"],
                [2.5, "xl:disabled:min-h-2.5"],
                [3.5, "xl:disabled:min-h-3.5"],
                ["full", "xl:disabled:min-h-full"],
                ["screen", "xl:disabled:min-h-screen"],
                ["svh", "xl:disabled:min-h-svh"],
                ["lvh", "xl:disabled:min-h-lvh"],
                ["dvh", "xl:disabled:min-h-dvh"],
                ["min", "xl:disabled:min-h-min"],
                ["max", "xl:disabled:min-h-max"],
                ["fit", "xl:disabled:min-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexMinHeight, string>>([
            [
              "xs",
              new Map<FlexMinHeight, string>([
                [0, "xs:hover:min-h-0"],
                [1, "xs:hover:min-h-1"],
                [2, "xs:hover:min-h-2"],
                [3, "xs:hover:min-h-3"],
                [4, "xs:hover:min-h-4"],
                [5, "xs:hover:min-h-5"],
                [6, "xs:hover:min-h-6"],
                [7, "xs:hover:min-h-7"],
                [8, "xs:hover:min-h-8"],
                [9, "xs:hover:min-h-9"],
                [10, "xs:hover:min-h-10"],
                [11, "xs:hover:min-h-11"],
                [12, "xs:hover:min-h-12"],
                [14, "xs:hover:min-h-14"],
                [16, "xs:hover:min-h-16"],
                [20, "xs:hover:min-h-20"],
                [24, "xs:hover:min-h-24"],
                [28, "xs:hover:min-h-28"],
                [32, "xs:hover:min-h-32"],
                [36, "xs:hover:min-h-36"],
                [40, "xs:hover:min-h-40"],
                [44, "xs:hover:min-h-44"],
                [48, "xs:hover:min-h-48"],
                [52, "xs:hover:min-h-52"],
                [56, "xs:hover:min-h-56"],
                [60, "xs:hover:min-h-60"],
                [64, "xs:hover:min-h-64"],
                [72, "xs:hover:min-h-72"],
                [80, "xs:hover:min-h-80"],
                [96, "xs:hover:min-h-96"],
                ["px", "xs:hover:min-h-px"],
                [0.5, "xs:hover:min-h-0.5"],
                [1.5, "xs:hover:min-h-1.5"],
                [2.5, "xs:hover:min-h-2.5"],
                [3.5, "xs:hover:min-h-3.5"],
                ["full", "xs:hover:min-h-full"],
                ["screen", "xs:hover:min-h-screen"],
                ["svh", "xs:hover:min-h-svh"],
                ["lvh", "xs:hover:min-h-lvh"],
                ["dvh", "xs:hover:min-h-dvh"],
                ["min", "xs:hover:min-h-min"],
                ["max", "xs:hover:min-h-max"],
                ["fit", "xs:hover:min-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinHeight, string>([
                [0, "sm:hover:min-h-0"],
                [1, "sm:hover:min-h-1"],
                [2, "sm:hover:min-h-2"],
                [3, "sm:hover:min-h-3"],
                [4, "sm:hover:min-h-4"],
                [5, "sm:hover:min-h-5"],
                [6, "sm:hover:min-h-6"],
                [7, "sm:hover:min-h-7"],
                [8, "sm:hover:min-h-8"],
                [9, "sm:hover:min-h-9"],
                [10, "sm:hover:min-h-10"],
                [11, "sm:hover:min-h-11"],
                [12, "sm:hover:min-h-12"],
                [14, "sm:hover:min-h-14"],
                [16, "sm:hover:min-h-16"],
                [20, "sm:hover:min-h-20"],
                [24, "sm:hover:min-h-24"],
                [28, "sm:hover:min-h-28"],
                [32, "sm:hover:min-h-32"],
                [36, "sm:hover:min-h-36"],
                [40, "sm:hover:min-h-40"],
                [44, "sm:hover:min-h-44"],
                [48, "sm:hover:min-h-48"],
                [52, "sm:hover:min-h-52"],
                [56, "sm:hover:min-h-56"],
                [60, "sm:hover:min-h-60"],
                [64, "sm:hover:min-h-64"],
                [72, "sm:hover:min-h-72"],
                [80, "sm:hover:min-h-80"],
                [96, "sm:hover:min-h-96"],
                ["px", "sm:hover:min-h-px"],
                [0.5, "sm:hover:min-h-0.5"],
                [1.5, "sm:hover:min-h-1.5"],
                [2.5, "sm:hover:min-h-2.5"],
                [3.5, "sm:hover:min-h-3.5"],
                ["full", "sm:hover:min-h-full"],
                ["screen", "sm:hover:min-h-screen"],
                ["svh", "sm:hover:min-h-svh"],
                ["lvh", "sm:hover:min-h-lvh"],
                ["dvh", "sm:hover:min-h-dvh"],
                ["min", "sm:hover:min-h-min"],
                ["max", "sm:hover:min-h-max"],
                ["fit", "sm:hover:min-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinHeight, string>([
                [0, "md:hover:min-h-0"],
                [1, "md:hover:min-h-1"],
                [2, "md:hover:min-h-2"],
                [3, "md:hover:min-h-3"],
                [4, "md:hover:min-h-4"],
                [5, "md:hover:min-h-5"],
                [6, "md:hover:min-h-6"],
                [7, "md:hover:min-h-7"],
                [8, "md:hover:min-h-8"],
                [9, "md:hover:min-h-9"],
                [10, "md:hover:min-h-10"],
                [11, "md:hover:min-h-11"],
                [12, "md:hover:min-h-12"],
                [14, "md:hover:min-h-14"],
                [16, "md:hover:min-h-16"],
                [20, "md:hover:min-h-20"],
                [24, "md:hover:min-h-24"],
                [28, "md:hover:min-h-28"],
                [32, "md:hover:min-h-32"],
                [36, "md:hover:min-h-36"],
                [40, "md:hover:min-h-40"],
                [44, "md:hover:min-h-44"],
                [48, "md:hover:min-h-48"],
                [52, "md:hover:min-h-52"],
                [56, "md:hover:min-h-56"],
                [60, "md:hover:min-h-60"],
                [64, "md:hover:min-h-64"],
                [72, "md:hover:min-h-72"],
                [80, "md:hover:min-h-80"],
                [96, "md:hover:min-h-96"],
                ["px", "md:hover:min-h-px"],
                [0.5, "md:hover:min-h-0.5"],
                [1.5, "md:hover:min-h-1.5"],
                [2.5, "md:hover:min-h-2.5"],
                [3.5, "md:hover:min-h-3.5"],
                ["full", "md:hover:min-h-full"],
                ["screen", "md:hover:min-h-screen"],
                ["svh", "md:hover:min-h-svh"],
                ["lvh", "md:hover:min-h-lvh"],
                ["dvh", "md:hover:min-h-dvh"],
                ["min", "md:hover:min-h-min"],
                ["max", "md:hover:min-h-max"],
                ["fit", "md:hover:min-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinHeight, string>([
                [0, "lg:hover:min-h-0"],
                [1, "lg:hover:min-h-1"],
                [2, "lg:hover:min-h-2"],
                [3, "lg:hover:min-h-3"],
                [4, "lg:hover:min-h-4"],
                [5, "lg:hover:min-h-5"],
                [6, "lg:hover:min-h-6"],
                [7, "lg:hover:min-h-7"],
                [8, "lg:hover:min-h-8"],
                [9, "lg:hover:min-h-9"],
                [10, "lg:hover:min-h-10"],
                [11, "lg:hover:min-h-11"],
                [12, "lg:hover:min-h-12"],
                [14, "lg:hover:min-h-14"],
                [16, "lg:hover:min-h-16"],
                [20, "lg:hover:min-h-20"],
                [24, "lg:hover:min-h-24"],
                [28, "lg:hover:min-h-28"],
                [32, "lg:hover:min-h-32"],
                [36, "lg:hover:min-h-36"],
                [40, "lg:hover:min-h-40"],
                [44, "lg:hover:min-h-44"],
                [48, "lg:hover:min-h-48"],
                [52, "lg:hover:min-h-52"],
                [56, "lg:hover:min-h-56"],
                [60, "lg:hover:min-h-60"],
                [64, "lg:hover:min-h-64"],
                [72, "lg:hover:min-h-72"],
                [80, "lg:hover:min-h-80"],
                [96, "lg:hover:min-h-96"],
                ["px", "lg:hover:min-h-px"],
                [0.5, "lg:hover:min-h-0.5"],
                [1.5, "lg:hover:min-h-1.5"],
                [2.5, "lg:hover:min-h-2.5"],
                [3.5, "lg:hover:min-h-3.5"],
                ["full", "lg:hover:min-h-full"],
                ["screen", "lg:hover:min-h-screen"],
                ["svh", "lg:hover:min-h-svh"],
                ["lvh", "lg:hover:min-h-lvh"],
                ["dvh", "lg:hover:min-h-dvh"],
                ["min", "lg:hover:min-h-min"],
                ["max", "lg:hover:min-h-max"],
                ["fit", "lg:hover:min-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinHeight, string>([
                [0, "xl:hover:min-h-0"],
                [1, "xl:hover:min-h-1"],
                [2, "xl:hover:min-h-2"],
                [3, "xl:hover:min-h-3"],
                [4, "xl:hover:min-h-4"],
                [5, "xl:hover:min-h-5"],
                [6, "xl:hover:min-h-6"],
                [7, "xl:hover:min-h-7"],
                [8, "xl:hover:min-h-8"],
                [9, "xl:hover:min-h-9"],
                [10, "xl:hover:min-h-10"],
                [11, "xl:hover:min-h-11"],
                [12, "xl:hover:min-h-12"],
                [14, "xl:hover:min-h-14"],
                [16, "xl:hover:min-h-16"],
                [20, "xl:hover:min-h-20"],
                [24, "xl:hover:min-h-24"],
                [28, "xl:hover:min-h-28"],
                [32, "xl:hover:min-h-32"],
                [36, "xl:hover:min-h-36"],
                [40, "xl:hover:min-h-40"],
                [44, "xl:hover:min-h-44"],
                [48, "xl:hover:min-h-48"],
                [52, "xl:hover:min-h-52"],
                [56, "xl:hover:min-h-56"],
                [60, "xl:hover:min-h-60"],
                [64, "xl:hover:min-h-64"],
                [72, "xl:hover:min-h-72"],
                [80, "xl:hover:min-h-80"],
                [96, "xl:hover:min-h-96"],
                ["px", "xl:hover:min-h-px"],
                [0.5, "xl:hover:min-h-0.5"],
                [1.5, "xl:hover:min-h-1.5"],
                [2.5, "xl:hover:min-h-2.5"],
                [3.5, "xl:hover:min-h-3.5"],
                ["full", "xl:hover:min-h-full"],
                ["screen", "xl:hover:min-h-screen"],
                ["svh", "xl:hover:min-h-svh"],
                ["lvh", "xl:hover:min-h-lvh"],
                ["dvh", "xl:hover:min-h-dvh"],
                ["min", "xl:hover:min-h-min"],
                ["max", "xl:hover:min-h-max"],
                ["fit", "xl:hover:min-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexMinHeight, string>>([
            [
              "xs",
              new Map<FlexMinHeight, string>([
                [0, "xs:min-h-0"],
                [1, "xs:min-h-1"],
                [2, "xs:min-h-2"],
                [3, "xs:min-h-3"],
                [4, "xs:min-h-4"],
                [5, "xs:min-h-5"],
                [6, "xs:min-h-6"],
                [7, "xs:min-h-7"],
                [8, "xs:min-h-8"],
                [9, "xs:min-h-9"],
                [10, "xs:min-h-10"],
                [11, "xs:min-h-11"],
                [12, "xs:min-h-12"],
                [14, "xs:min-h-14"],
                [16, "xs:min-h-16"],
                [20, "xs:min-h-20"],
                [24, "xs:min-h-24"],
                [28, "xs:min-h-28"],
                [32, "xs:min-h-32"],
                [36, "xs:min-h-36"],
                [40, "xs:min-h-40"],
                [44, "xs:min-h-44"],
                [48, "xs:min-h-48"],
                [52, "xs:min-h-52"],
                [56, "xs:min-h-56"],
                [60, "xs:min-h-60"],
                [64, "xs:min-h-64"],
                [72, "xs:min-h-72"],
                [80, "xs:min-h-80"],
                [96, "xs:min-h-96"],
                ["px", "xs:min-h-px"],
                [0.5, "xs:min-h-0.5"],
                [1.5, "xs:min-h-1.5"],
                [2.5, "xs:min-h-2.5"],
                [3.5, "xs:min-h-3.5"],
                ["full", "xs:min-h-full"],
                ["screen", "xs:min-h-screen"],
                ["svh", "xs:min-h-svh"],
                ["lvh", "xs:min-h-lvh"],
                ["dvh", "xs:min-h-dvh"],
                ["min", "xs:min-h-min"],
                ["max", "xs:min-h-max"],
                ["fit", "xs:min-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinHeight, string>([
                [0, "sm:min-h-0"],
                [1, "sm:min-h-1"],
                [2, "sm:min-h-2"],
                [3, "sm:min-h-3"],
                [4, "sm:min-h-4"],
                [5, "sm:min-h-5"],
                [6, "sm:min-h-6"],
                [7, "sm:min-h-7"],
                [8, "sm:min-h-8"],
                [9, "sm:min-h-9"],
                [10, "sm:min-h-10"],
                [11, "sm:min-h-11"],
                [12, "sm:min-h-12"],
                [14, "sm:min-h-14"],
                [16, "sm:min-h-16"],
                [20, "sm:min-h-20"],
                [24, "sm:min-h-24"],
                [28, "sm:min-h-28"],
                [32, "sm:min-h-32"],
                [36, "sm:min-h-36"],
                [40, "sm:min-h-40"],
                [44, "sm:min-h-44"],
                [48, "sm:min-h-48"],
                [52, "sm:min-h-52"],
                [56, "sm:min-h-56"],
                [60, "sm:min-h-60"],
                [64, "sm:min-h-64"],
                [72, "sm:min-h-72"],
                [80, "sm:min-h-80"],
                [96, "sm:min-h-96"],
                ["px", "sm:min-h-px"],
                [0.5, "sm:min-h-0.5"],
                [1.5, "sm:min-h-1.5"],
                [2.5, "sm:min-h-2.5"],
                [3.5, "sm:min-h-3.5"],
                ["full", "sm:min-h-full"],
                ["screen", "sm:min-h-screen"],
                ["svh", "sm:min-h-svh"],
                ["lvh", "sm:min-h-lvh"],
                ["dvh", "sm:min-h-dvh"],
                ["min", "sm:min-h-min"],
                ["max", "sm:min-h-max"],
                ["fit", "sm:min-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinHeight, string>([
                [0, "md:min-h-0"],
                [1, "md:min-h-1"],
                [2, "md:min-h-2"],
                [3, "md:min-h-3"],
                [4, "md:min-h-4"],
                [5, "md:min-h-5"],
                [6, "md:min-h-6"],
                [7, "md:min-h-7"],
                [8, "md:min-h-8"],
                [9, "md:min-h-9"],
                [10, "md:min-h-10"],
                [11, "md:min-h-11"],
                [12, "md:min-h-12"],
                [14, "md:min-h-14"],
                [16, "md:min-h-16"],
                [20, "md:min-h-20"],
                [24, "md:min-h-24"],
                [28, "md:min-h-28"],
                [32, "md:min-h-32"],
                [36, "md:min-h-36"],
                [40, "md:min-h-40"],
                [44, "md:min-h-44"],
                [48, "md:min-h-48"],
                [52, "md:min-h-52"],
                [56, "md:min-h-56"],
                [60, "md:min-h-60"],
                [64, "md:min-h-64"],
                [72, "md:min-h-72"],
                [80, "md:min-h-80"],
                [96, "md:min-h-96"],
                ["px", "md:min-h-px"],
                [0.5, "md:min-h-0.5"],
                [1.5, "md:min-h-1.5"],
                [2.5, "md:min-h-2.5"],
                [3.5, "md:min-h-3.5"],
                ["full", "md:min-h-full"],
                ["screen", "md:min-h-screen"],
                ["svh", "md:min-h-svh"],
                ["lvh", "md:min-h-lvh"],
                ["dvh", "md:min-h-dvh"],
                ["min", "md:min-h-min"],
                ["max", "md:min-h-max"],
                ["fit", "md:min-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinHeight, string>([
                [0, "lg:min-h-0"],
                [1, "lg:min-h-1"],
                [2, "lg:min-h-2"],
                [3, "lg:min-h-3"],
                [4, "lg:min-h-4"],
                [5, "lg:min-h-5"],
                [6, "lg:min-h-6"],
                [7, "lg:min-h-7"],
                [8, "lg:min-h-8"],
                [9, "lg:min-h-9"],
                [10, "lg:min-h-10"],
                [11, "lg:min-h-11"],
                [12, "lg:min-h-12"],
                [14, "lg:min-h-14"],
                [16, "lg:min-h-16"],
                [20, "lg:min-h-20"],
                [24, "lg:min-h-24"],
                [28, "lg:min-h-28"],
                [32, "lg:min-h-32"],
                [36, "lg:min-h-36"],
                [40, "lg:min-h-40"],
                [44, "lg:min-h-44"],
                [48, "lg:min-h-48"],
                [52, "lg:min-h-52"],
                [56, "lg:min-h-56"],
                [60, "lg:min-h-60"],
                [64, "lg:min-h-64"],
                [72, "lg:min-h-72"],
                [80, "lg:min-h-80"],
                [96, "lg:min-h-96"],
                ["px", "lg:min-h-px"],
                [0.5, "lg:min-h-0.5"],
                [1.5, "lg:min-h-1.5"],
                [2.5, "lg:min-h-2.5"],
                [3.5, "lg:min-h-3.5"],
                ["full", "lg:min-h-full"],
                ["screen", "lg:min-h-screen"],
                ["svh", "lg:min-h-svh"],
                ["lvh", "lg:min-h-lvh"],
                ["dvh", "lg:min-h-dvh"],
                ["min", "lg:min-h-min"],
                ["max", "lg:min-h-max"],
                ["fit", "lg:min-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinHeight, string>([
                [0, "xl:min-h-0"],
                [1, "xl:min-h-1"],
                [2, "xl:min-h-2"],
                [3, "xl:min-h-3"],
                [4, "xl:min-h-4"],
                [5, "xl:min-h-5"],
                [6, "xl:min-h-6"],
                [7, "xl:min-h-7"],
                [8, "xl:min-h-8"],
                [9, "xl:min-h-9"],
                [10, "xl:min-h-10"],
                [11, "xl:min-h-11"],
                [12, "xl:min-h-12"],
                [14, "xl:min-h-14"],
                [16, "xl:min-h-16"],
                [20, "xl:min-h-20"],
                [24, "xl:min-h-24"],
                [28, "xl:min-h-28"],
                [32, "xl:min-h-32"],
                [36, "xl:min-h-36"],
                [40, "xl:min-h-40"],
                [44, "xl:min-h-44"],
                [48, "xl:min-h-48"],
                [52, "xl:min-h-52"],
                [56, "xl:min-h-56"],
                [60, "xl:min-h-60"],
                [64, "xl:min-h-64"],
                [72, "xl:min-h-72"],
                [80, "xl:min-h-80"],
                [96, "xl:min-h-96"],
                ["px", "xl:min-h-px"],
                [0.5, "xl:min-h-0.5"],
                [1.5, "xl:min-h-1.5"],
                [2.5, "xl:min-h-2.5"],
                [3.5, "xl:min-h-3.5"],
                ["full", "xl:min-h-full"],
                ["screen", "xl:min-h-screen"],
                ["svh", "xl:min-h-svh"],
                ["lvh", "xl:min-h-lvh"],
                ["dvh", "xl:min-h-dvh"],
                ["min", "xl:min-h-min"],
                ["max", "xl:min-h-max"],
                ["fit", "xl:min-h-fit"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexMinHeight, string>>([
            [
              "xs",
              new Map<FlexMinHeight, string>([
                [0, "xs:open:min-h-0"],
                [1, "xs:open:min-h-1"],
                [2, "xs:open:min-h-2"],
                [3, "xs:open:min-h-3"],
                [4, "xs:open:min-h-4"],
                [5, "xs:open:min-h-5"],
                [6, "xs:open:min-h-6"],
                [7, "xs:open:min-h-7"],
                [8, "xs:open:min-h-8"],
                [9, "xs:open:min-h-9"],
                [10, "xs:open:min-h-10"],
                [11, "xs:open:min-h-11"],
                [12, "xs:open:min-h-12"],
                [14, "xs:open:min-h-14"],
                [16, "xs:open:min-h-16"],
                [20, "xs:open:min-h-20"],
                [24, "xs:open:min-h-24"],
                [28, "xs:open:min-h-28"],
                [32, "xs:open:min-h-32"],
                [36, "xs:open:min-h-36"],
                [40, "xs:open:min-h-40"],
                [44, "xs:open:min-h-44"],
                [48, "xs:open:min-h-48"],
                [52, "xs:open:min-h-52"],
                [56, "xs:open:min-h-56"],
                [60, "xs:open:min-h-60"],
                [64, "xs:open:min-h-64"],
                [72, "xs:open:min-h-72"],
                [80, "xs:open:min-h-80"],
                [96, "xs:open:min-h-96"],
                ["px", "xs:open:min-h-px"],
                [0.5, "xs:open:min-h-0.5"],
                [1.5, "xs:open:min-h-1.5"],
                [2.5, "xs:open:min-h-2.5"],
                [3.5, "xs:open:min-h-3.5"],
                ["full", "xs:open:min-h-full"],
                ["screen", "xs:open:min-h-screen"],
                ["svh", "xs:open:min-h-svh"],
                ["lvh", "xs:open:min-h-lvh"],
                ["dvh", "xs:open:min-h-dvh"],
                ["min", "xs:open:min-h-min"],
                ["max", "xs:open:min-h-max"],
                ["fit", "xs:open:min-h-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinHeight, string>([
                [0, "sm:open:min-h-0"],
                [1, "sm:open:min-h-1"],
                [2, "sm:open:min-h-2"],
                [3, "sm:open:min-h-3"],
                [4, "sm:open:min-h-4"],
                [5, "sm:open:min-h-5"],
                [6, "sm:open:min-h-6"],
                [7, "sm:open:min-h-7"],
                [8, "sm:open:min-h-8"],
                [9, "sm:open:min-h-9"],
                [10, "sm:open:min-h-10"],
                [11, "sm:open:min-h-11"],
                [12, "sm:open:min-h-12"],
                [14, "sm:open:min-h-14"],
                [16, "sm:open:min-h-16"],
                [20, "sm:open:min-h-20"],
                [24, "sm:open:min-h-24"],
                [28, "sm:open:min-h-28"],
                [32, "sm:open:min-h-32"],
                [36, "sm:open:min-h-36"],
                [40, "sm:open:min-h-40"],
                [44, "sm:open:min-h-44"],
                [48, "sm:open:min-h-48"],
                [52, "sm:open:min-h-52"],
                [56, "sm:open:min-h-56"],
                [60, "sm:open:min-h-60"],
                [64, "sm:open:min-h-64"],
                [72, "sm:open:min-h-72"],
                [80, "sm:open:min-h-80"],
                [96, "sm:open:min-h-96"],
                ["px", "sm:open:min-h-px"],
                [0.5, "sm:open:min-h-0.5"],
                [1.5, "sm:open:min-h-1.5"],
                [2.5, "sm:open:min-h-2.5"],
                [3.5, "sm:open:min-h-3.5"],
                ["full", "sm:open:min-h-full"],
                ["screen", "sm:open:min-h-screen"],
                ["svh", "sm:open:min-h-svh"],
                ["lvh", "sm:open:min-h-lvh"],
                ["dvh", "sm:open:min-h-dvh"],
                ["min", "sm:open:min-h-min"],
                ["max", "sm:open:min-h-max"],
                ["fit", "sm:open:min-h-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinHeight, string>([
                [0, "md:open:min-h-0"],
                [1, "md:open:min-h-1"],
                [2, "md:open:min-h-2"],
                [3, "md:open:min-h-3"],
                [4, "md:open:min-h-4"],
                [5, "md:open:min-h-5"],
                [6, "md:open:min-h-6"],
                [7, "md:open:min-h-7"],
                [8, "md:open:min-h-8"],
                [9, "md:open:min-h-9"],
                [10, "md:open:min-h-10"],
                [11, "md:open:min-h-11"],
                [12, "md:open:min-h-12"],
                [14, "md:open:min-h-14"],
                [16, "md:open:min-h-16"],
                [20, "md:open:min-h-20"],
                [24, "md:open:min-h-24"],
                [28, "md:open:min-h-28"],
                [32, "md:open:min-h-32"],
                [36, "md:open:min-h-36"],
                [40, "md:open:min-h-40"],
                [44, "md:open:min-h-44"],
                [48, "md:open:min-h-48"],
                [52, "md:open:min-h-52"],
                [56, "md:open:min-h-56"],
                [60, "md:open:min-h-60"],
                [64, "md:open:min-h-64"],
                [72, "md:open:min-h-72"],
                [80, "md:open:min-h-80"],
                [96, "md:open:min-h-96"],
                ["px", "md:open:min-h-px"],
                [0.5, "md:open:min-h-0.5"],
                [1.5, "md:open:min-h-1.5"],
                [2.5, "md:open:min-h-2.5"],
                [3.5, "md:open:min-h-3.5"],
                ["full", "md:open:min-h-full"],
                ["screen", "md:open:min-h-screen"],
                ["svh", "md:open:min-h-svh"],
                ["lvh", "md:open:min-h-lvh"],
                ["dvh", "md:open:min-h-dvh"],
                ["min", "md:open:min-h-min"],
                ["max", "md:open:min-h-max"],
                ["fit", "md:open:min-h-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinHeight, string>([
                [0, "lg:open:min-h-0"],
                [1, "lg:open:min-h-1"],
                [2, "lg:open:min-h-2"],
                [3, "lg:open:min-h-3"],
                [4, "lg:open:min-h-4"],
                [5, "lg:open:min-h-5"],
                [6, "lg:open:min-h-6"],
                [7, "lg:open:min-h-7"],
                [8, "lg:open:min-h-8"],
                [9, "lg:open:min-h-9"],
                [10, "lg:open:min-h-10"],
                [11, "lg:open:min-h-11"],
                [12, "lg:open:min-h-12"],
                [14, "lg:open:min-h-14"],
                [16, "lg:open:min-h-16"],
                [20, "lg:open:min-h-20"],
                [24, "lg:open:min-h-24"],
                [28, "lg:open:min-h-28"],
                [32, "lg:open:min-h-32"],
                [36, "lg:open:min-h-36"],
                [40, "lg:open:min-h-40"],
                [44, "lg:open:min-h-44"],
                [48, "lg:open:min-h-48"],
                [52, "lg:open:min-h-52"],
                [56, "lg:open:min-h-56"],
                [60, "lg:open:min-h-60"],
                [64, "lg:open:min-h-64"],
                [72, "lg:open:min-h-72"],
                [80, "lg:open:min-h-80"],
                [96, "lg:open:min-h-96"],
                ["px", "lg:open:min-h-px"],
                [0.5, "lg:open:min-h-0.5"],
                [1.5, "lg:open:min-h-1.5"],
                [2.5, "lg:open:min-h-2.5"],
                [3.5, "lg:open:min-h-3.5"],
                ["full", "lg:open:min-h-full"],
                ["screen", "lg:open:min-h-screen"],
                ["svh", "lg:open:min-h-svh"],
                ["lvh", "lg:open:min-h-lvh"],
                ["dvh", "lg:open:min-h-dvh"],
                ["min", "lg:open:min-h-min"],
                ["max", "lg:open:min-h-max"],
                ["fit", "lg:open:min-h-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinHeight, string>([
                [0, "xl:open:min-h-0"],
                [1, "xl:open:min-h-1"],
                [2, "xl:open:min-h-2"],
                [3, "xl:open:min-h-3"],
                [4, "xl:open:min-h-4"],
                [5, "xl:open:min-h-5"],
                [6, "xl:open:min-h-6"],
                [7, "xl:open:min-h-7"],
                [8, "xl:open:min-h-8"],
                [9, "xl:open:min-h-9"],
                [10, "xl:open:min-h-10"],
                [11, "xl:open:min-h-11"],
                [12, "xl:open:min-h-12"],
                [14, "xl:open:min-h-14"],
                [16, "xl:open:min-h-16"],
                [20, "xl:open:min-h-20"],
                [24, "xl:open:min-h-24"],
                [28, "xl:open:min-h-28"],
                [32, "xl:open:min-h-32"],
                [36, "xl:open:min-h-36"],
                [40, "xl:open:min-h-40"],
                [44, "xl:open:min-h-44"],
                [48, "xl:open:min-h-48"],
                [52, "xl:open:min-h-52"],
                [56, "xl:open:min-h-56"],
                [60, "xl:open:min-h-60"],
                [64, "xl:open:min-h-64"],
                [72, "xl:open:min-h-72"],
                [80, "xl:open:min-h-80"],
                [96, "xl:open:min-h-96"],
                ["px", "xl:open:min-h-px"],
                [0.5, "xl:open:min-h-0.5"],
                [1.5, "xl:open:min-h-1.5"],
                [2.5, "xl:open:min-h-2.5"],
                [3.5, "xl:open:min-h-3.5"],
                ["full", "xl:open:min-h-full"],
                ["screen", "xl:open:min-h-screen"],
                ["svh", "xl:open:min-h-svh"],
                ["lvh", "xl:open:min-h-lvh"],
                ["dvh", "xl:open:min-h-dvh"],
                ["min", "xl:open:min-h-min"],
                ["max", "xl:open:min-h-max"],
                ["fit", "xl:open:min-h-fit"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
