import { Breakable } from "../../Entities/Brekable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { AxisMapping, Breakpoints, CSSSelector, FlexSpacing } from "../../types";
import { GapAxisInsideBreakpoints } from "./GapAxisIsideBreakpoints";
import { DefaultValue } from "../DefaultValue";

export class GapAxis
  extends CSSProperty<Map<AxisMapping, Map<FlexSpacing, string>>>
  implements
    Breakable<Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<AxisMapping, Map<FlexSpacing, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new GapClassesMapping();
    return new GapAxis(classesMapping, selector);
  }

  public breakpoints() {
    return GapAxisInsideBreakpoints.create(this.cssSelector);
  }

  public write(axis: AxisMapping, spacing: FlexSpacing) {
    return this.getClassName(axis, spacing);
  }
}

class GapClassesMapping
  implements ClassesMapping<Map<AxisMapping, Map<FlexSpacing, string>>>
{
  private defaultValue: DefaultValue<AxisMapping, Map<FlexSpacing, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<AxisMapping, Map<FlexSpacing, string>>(
      "x",
      new Map<FlexSpacing, string>([
        [0, "gap-x-0"],
        ["px", "gap-x-px"],
        [0.5, "gap-x-0.5"],
        [1, "gap-x-1"],
        [1.5, "gap-x-1.5"],
        [2, "gap-x-2"],
        [2.5, "gap-x-2.5"],
        [3, "gap-x-3"],
        [3.5, "gap-x-3.5"],
        [4, "gap-x-4"],
        [5, "gap-x-5"],
        [6, "gap-x-6"],
        [7, "gap-x-7"],
        [8, "gap-x-8"],
        [9, "gap-x-9"],
        [10, "gap-x-10"],
        [11, "gap-x-11"],
        [12, "gap-x-12"],
        [14, "gap-x-14"],
        [16, "gap-x-16"],
        [20, "gap-x-20"],
        [24, "gap-x-24"],
        [28, "gap-x-28"],
        [32, "gap-x-32"],
        [36, "gap-x-36"],
        [40, "gap-x-40"],
        [44, "gap-x-44"],
        [48, "gap-x-48"],
        [52, "gap-x-52"],
        [56, "gap-x-56"],
        [60, "gap-x-60"],
        [64, "gap-x-64"],
        [72, "gap-x-72"],
        [80, "gap-x-80"],
        [96, "gap-x-96"],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<AxisMapping, Map<FlexSpacing, string>>>([
        [
          "active",
          new Map<AxisMapping, Map<FlexSpacing, string>>([
            [
              "x",
              new Map<FlexSpacing, string>([
                [0, "active:gap-x-0"],
                ["px", "active:gap-x-px"],
                [0.5, "active:gap-x-0.5"],
                [1, "active:gap-x-1"],
                [1.5, "active:gap-x-1.5"],
                [2, "active:gap-x-2"],
                [2.5, "active:gap-x-2.5"],
                [3, "active:gap-x-3"],
                [3.5, "active:gap-x-3.5"],
                [4, "active:gap-x-4"],
                [5, "active:gap-x-5"],
                [6, "active:gap-x-6"],
                [7, "active:gap-x-7"],
                [8, "active:gap-x-8"],
                [9, "active:gap-x-9"],
                [10, "active:gap-x-10"],
                [11, "active:gap-x-11"],
                [12, "active:gap-x-12"],
                [14, "active:gap-x-14"],
                [16, "active:gap-x-16"],
                [20, "active:gap-x-20"],
                [24, "active:gap-x-24"],
                [28, "active:gap-x-28"],
                [32, "active:gap-x-32"],
                [36, "active:gap-x-36"],
                [40, "active:gap-x-40"],
                [44, "active:gap-x-44"],
                [48, "active:gap-x-48"],
                [52, "active:gap-x-52"],
                [56, "active:gap-x-56"],
                [60, "active:gap-x-60"],
                [64, "active:gap-x-64"],
                [72, "active:gap-x-72"],
                [80, "active:gap-x-80"],
                [96, "active:gap-x-96"],
              ]),
            ],
            [
              "y",
              new Map<FlexSpacing, string>([
                [0, "active:gap-y-0"],
                ["px", "active:gap-y-px"],
                [0.5, "active:gap-y-0.5"],
                [1, "active:gap-y-1"],
                [1.5, "active:gap-y-1.5"],
                [2, "active:gap-y-2"],
                [2.5, "active:gap-y-2.5"],
                [3, "active:gap-y-3"],
                [3.5, "active:gap-y-3.5"],
                [4, "active:gap-y-4"],
                [5, "active:gap-y-5"],
                [6, "active:gap-y-6"],
                [7, "active:gap-y-7"],
                [8, "active:gap-y-8"],
                [9, "active:gap-y-9"],
                [10, "active:gap-y-10"],
                [11, "active:gap-y-11"],
                [12, "active:gap-y-12"],
                [14, "active:gap-y-14"],
                [16, "active:gap-y-16"],
                [20, "active:gap-y-20"],
                [24, "active:gap-y-24"],
                [28, "active:gap-y-28"],
                [32, "active:gap-y-32"],
                [36, "active:gap-y-36"],
                [40, "active:gap-y-40"],
                [44, "active:gap-y-44"],
                [48, "active:gap-y-48"],
                [52, "active:gap-y-52"],
                [56, "active:gap-y-56"],
                [60, "active:gap-y-60"],
                [64, "active:gap-y-64"],
                [72, "active:gap-y-72"],
                [80, "active:gap-y-80"],
                [96, "active:gap-y-96"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<AxisMapping, Map<FlexSpacing, string>>([
            [
              "x",
              new Map<FlexSpacing, string>([
                [0, "disabled:gap-x-0"],
                ["px", "disabled:gap-x-px"],
                [0.5, "disabled:gap-x-0.5"],
                [1, "disabled:gap-x-1"],
                [1.5, "disabled:gap-x-1.5"],
                [2, "disabled:gap-x-2"],
                [2.5, "disabled:gap-x-2.5"],
                [3, "disabled:gap-x-3"],
                [3.5, "disabled:gap-x-3.5"],
                [4, "disabled:gap-x-4"],
                [5, "disabled:gap-x-5"],
                [6, "disabled:gap-x-6"],
                [7, "disabled:gap-x-7"],
                [8, "disabled:gap-x-8"],
                [9, "disabled:gap-x-9"],
                [10, "disabled:gap-x-10"],
                [11, "disabled:gap-x-11"],
                [12, "disabled:gap-x-12"],
                [14, "disabled:gap-x-14"],
                [16, "disabled:gap-x-16"],
                [20, "disabled:gap-x-20"],
                [24, "disabled:gap-x-24"],
                [28, "disabled:gap-x-28"],
                [32, "disabled:gap-x-32"],
                [36, "disabled:gap-x-36"],
                [40, "disabled:gap-x-40"],
                [44, "disabled:gap-x-44"],
                [48, "disabled:gap-x-48"],
                [52, "disabled:gap-x-52"],
                [56, "disabled:gap-x-56"],
                [60, "disabled:gap-x-60"],
                [64, "disabled:gap-x-64"],
                [72, "disabled:gap-x-72"],
                [80, "disabled:gap-x-80"],
                [96, "disabled:gap-x-96"],
              ]),
            ],
            [
              "y",
              new Map<FlexSpacing, string>([
                [0, "disabled:gap-y-0"],
                ["px", "disabled:gap-y-px"],
                [0.5, "disabled:gap-y-0.5"],
                [1, "disabled:gap-y-1"],
                [1.5, "disabled:gap-y-1.5"],
                [2, "disabled:gap-y-2"],
                [2.5, "disabled:gap-y-2.5"],
                [3, "disabled:gap-y-3"],
                [3.5, "disabled:gap-y-3.5"],
                [4, "disabled:gap-y-4"],
                [5, "disabled:gap-y-5"],
                [6, "disabled:gap-y-6"],
                [7, "disabled:gap-y-7"],
                [8, "disabled:gap-y-8"],
                [9, "disabled:gap-y-9"],
                [10, "disabled:gap-y-10"],
                [11, "disabled:gap-y-11"],
                [12, "disabled:gap-y-12"],
                [14, "disabled:gap-y-14"],
                [16, "disabled:gap-y-16"],
                [20, "disabled:gap-y-20"],
                [24, "disabled:gap-y-24"],
                [28, "disabled:gap-y-28"],
                [32, "disabled:gap-y-32"],
                [36, "disabled:gap-y-36"],
                [40, "disabled:gap-y-40"],
                [44, "disabled:gap-y-44"],
                [48, "disabled:gap-y-48"],
                [52, "disabled:gap-y-52"],
                [56, "disabled:gap-y-56"],
                [60, "disabled:gap-y-60"],
                [64, "disabled:gap-y-64"],
                [72, "disabled:gap-y-72"],
                [80, "disabled:gap-y-80"],
                [96, "disabled:gap-y-96"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<AxisMapping, Map<FlexSpacing, string>>([
            [
              "x",
              new Map<FlexSpacing, string>([
                [0, "hover:gap-x-0"],
                ["px", "hover:gap-x-px"],
                [0.5, "hover:gap-x-0.5"],
                [1, "hover:gap-x-1"],
                [1.5, "hover:gap-x-1.5"],
                [2, "hover:gap-x-2"],
                [2.5, "hover:gap-x-2.5"],
                [3, "hover:gap-x-3"],
                [3.5, "hover:gap-x-3.5"],
                [4, "hover:gap-x-4"],
                [5, "hover:gap-x-5"],
                [6, "hover:gap-x-6"],
                [7, "hover:gap-x-7"],
                [8, "hover:gap-x-8"],
                [9, "hover:gap-x-9"],
                [10, "hover:gap-x-10"],
                [11, "hover:gap-x-11"],
                [12, "hover:gap-x-12"],
                [14, "hover:gap-x-14"],
                [16, "hover:gap-x-16"],
                [20, "hover:gap-x-20"],
                [24, "hover:gap-x-24"],
                [28, "hover:gap-x-28"],
                [32, "hover:gap-x-32"],
                [36, "hover:gap-x-36"],
                [40, "hover:gap-x-40"],
                [44, "hover:gap-x-44"],
                [48, "hover:gap-x-48"],
                [52, "hover:gap-x-52"],
                [56, "hover:gap-x-56"],
                [60, "hover:gap-x-60"],
                [64, "hover:gap-x-64"],
                [72, "hover:gap-x-72"],
                [80, "hover:gap-x-80"],
                [96, "hover:gap-x-96"],
              ]),
            ],
            [
              "y",
              new Map<FlexSpacing, string>([
                [0, "hover:gap-y-0"],
                ["px", "hover:gap-y-px"],
                [0.5, "hover:gap-y-0.5"],
                [1, "hover:gap-y-1"],
                [1.5, "hover:gap-y-1.5"],
                [2, "hover:gap-y-2"],
                [2.5, "hover:gap-y-2.5"],
                [3, "hover:gap-y-3"],
                [3.5, "hover:gap-y-3.5"],
                [4, "hover:gap-y-4"],
                [5, "hover:gap-y-5"],
                [6, "hover:gap-y-6"],
                [7, "hover:gap-y-7"],
                [8, "hover:gap-y-8"],
                [9, "hover:gap-y-9"],
                [10, "hover:gap-y-10"],
                [11, "hover:gap-y-11"],
                [12, "hover:gap-y-12"],
                [14, "hover:gap-y-14"],
                [16, "hover:gap-y-16"],
                [20, "hover:gap-y-20"],
                [24, "hover:gap-y-24"],
                [28, "hover:gap-y-28"],
                [32, "hover:gap-y-32"],
                [36, "hover:gap-y-36"],
                [40, "hover:gap-y-40"],
                [44, "hover:gap-y-44"],
                [48, "hover:gap-y-48"],
                [52, "hover:gap-y-52"],
                [56, "hover:gap-y-56"],
                [60, "hover:gap-y-60"],
                [64, "hover:gap-y-64"],
                [72, "hover:gap-y-72"],
                [80, "hover:gap-y-80"],
                [96, "hover:gap-y-96"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<AxisMapping, Map<FlexSpacing, string>>([
            [
              "x",
              new Map<FlexSpacing, string>([
                [0, "gap-x-0"],
                ["px", "gap-x-px"],
                [0.5, "gap-x-0.5"],
                [1, "gap-x-1"],
                [1.5, "gap-x-1.5"],
                [2, "gap-x-2"],
                [2.5, "gap-x-2.5"],
                [3, "gap-x-3"],
                [3.5, "gap-x-3.5"],
                [4, "gap-x-4"],
                [5, "gap-x-5"],
                [6, "gap-x-6"],
                [7, "gap-x-7"],
                [8, "gap-x-8"],
                [9, "gap-x-9"],
                [10, "gap-x-10"],
                [11, "gap-x-11"],
                [12, "gap-x-12"],
                [14, "gap-x-14"],
                [16, "gap-x-16"],
                [20, "gap-x-20"],
                [24, "gap-x-24"],
                [28, "gap-x-28"],
                [32, "gap-x-32"],
                [36, "gap-x-36"],
                [40, "gap-x-40"],
                [44, "gap-x-44"],
                [48, "gap-x-48"],
                [52, "gap-x-52"],
                [56, "gap-x-56"],
                [60, "gap-x-60"],
                [64, "gap-x-64"],
                [72, "gap-x-72"],
                [80, "gap-x-80"],
                [96, "gap-x-96"],
              ]),
            ],
            [
              "y",
              new Map<FlexSpacing, string>([
                [0, "gap-y-0"],
                ["px", "gap-y-px"],
                [0.5, "gap-y-0.5"],
                [1, "gap-y-1"],
                [1.5, "gap-y-1.5"],
                [2, "gap-y-2"],
                [2.5, "gap-y-2.5"],
                [3, "gap-y-3"],
                [3.5, "gap-y-3.5"],
                [4, "gap-y-4"],
                [5, "gap-y-5"],
                [6, "gap-y-6"],
                [7, "gap-y-7"],
                [8, "gap-y-8"],
                [9, "gap-y-9"],
                [10, "gap-y-10"],
                [11, "gap-y-11"],
                [12, "gap-y-12"],
                [14, "gap-y-14"],
                [16, "gap-y-16"],
                [20, "gap-y-20"],
                [24, "gap-y-24"],
                [28, "gap-y-28"],
                [32, "gap-y-32"],
                [36, "gap-y-36"],
                [40, "gap-y-40"],
                [44, "gap-y-44"],
                [48, "gap-y-48"],
                [52, "gap-y-52"],
                [56, "gap-y-56"],
                [60, "gap-y-60"],
                [64, "gap-y-64"],
                [72, "gap-y-72"],
                [80, "gap-y-80"],
                [96, "gap-y-96"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<AxisMapping, Map<FlexSpacing, string>>([
            [
              "x",
              new Map<FlexSpacing, string>([
                [0, "open:gap-x-0"],
                ["px", "open:gap-x-px"],
                [0.5, "open:gap-x-0.5"],
                [1, "open:gap-x-1"],
                [1.5, "open:gap-x-1.5"],
                [2, "open:gap-x-2"],
                [2.5, "open:gap-x-2.5"],
                [3, "open:gap-x-3"],
                [3.5, "open:gap-x-3.5"],
                [4, "open:gap-x-4"],
                [5, "open:gap-x-5"],
                [6, "open:gap-x-6"],
                [7, "open:gap-x-7"],
                [8, "open:gap-x-8"],
                [9, "open:gap-x-9"],
                [10, "open:gap-x-10"],
                [11, "open:gap-x-11"],
                [12, "open:gap-x-12"],
                [14, "open:gap-x-14"],
                [16, "open:gap-x-16"],
                [20, "open:gap-x-20"],
                [24, "open:gap-x-24"],
                [28, "open:gap-x-28"],
                [32, "open:gap-x-32"],
                [36, "open:gap-x-36"],
                [40, "open:gap-x-40"],
                [44, "open:gap-x-44"],
                [48, "open:gap-x-48"],
                [52, "open:gap-x-52"],
                [56, "open:gap-x-56"],
                [60, "open:gap-x-60"],
                [64, "open:gap-x-64"],
                [72, "open:gap-x-72"],
                [80, "open:gap-x-80"],
                [96, "open:gap-x-96"],
              ]),
            ],
            [
              "y",
              new Map<FlexSpacing, string>([
                [0, "open:gap-y-0"],
                ["px", "open:gap-y-px"],
                [0.5, "open:gap-y-0.5"],
                [1, "open:gap-y-1"],
                [1.5, "open:gap-y-1.5"],
                [2, "open:gap-y-2"],
                [2.5, "open:gap-y-2.5"],
                [3, "open:gap-y-3"],
                [3.5, "open:gap-y-3.5"],
                [4, "open:gap-y-4"],
                [5, "open:gap-y-5"],
                [6, "open:gap-y-6"],
                [7, "open:gap-y-7"],
                [8, "open:gap-y-8"],
                [9, "open:gap-y-9"],
                [10, "open:gap-y-10"],
                [11, "open:gap-y-11"],
                [12, "open:gap-y-12"],
                [14, "open:gap-y-14"],
                [16, "open:gap-y-16"],
                [20, "open:gap-y-20"],
                [24, "open:gap-y-24"],
                [28, "open:gap-y-28"],
                [32, "open:gap-y-32"],
                [36, "open:gap-y-36"],
                [40, "open:gap-y-40"],
                [44, "open:gap-y-44"],
                [48, "open:gap-y-48"],
                [52, "open:gap-y-52"],
                [56, "open:gap-y-56"],
                [60, "open:gap-y-60"],
                [64, "open:gap-y-64"],
                [72, "open:gap-y-72"],
                [80, "open:gap-y-80"],
                [96, "open:gap-y-96"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
