import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { AxisMapping, Breakpoints, CSSSelector, FlexSpacing } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class GapAxisInsideBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
> {
  private constructor(
    classesMapping: ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }
  static create(selector: CSSSelector = "none") {
    const classesMapping = new GapClassesMapping();
    return new GapAxisInsideBreakpoints(classesMapping, selector);
  }

  public write(
    breakpoint: Breakpoints,
    axis: AxisMapping,
    spacing: FlexSpacing
  ) {
    return this.getClassName(breakpoint, axis, spacing);
  }
}

class GapClassesMapping
  implements
    ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
    >
{
  private defaultValue: DefaultValue<
    Breakpoints,
    Map<AxisMapping, Map<FlexSpacing, string>>
  >;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<AxisMapping, Map<FlexSpacing, string>>
    >(
      "xs",
      new Map<AxisMapping, Map<FlexSpacing, string>>([
        [
          "x",
          new Map<FlexSpacing, string>([
            [0, "xs:gap-x-0"],
            ["px", "xs:gap-x-px"],
            [0.5, "xs:gap-x-0.5"],
            [1, "xs:gap-x-1"],
            [1.5, "xs:gap-x-1.5"],
            [2, "xs:gap-x-2"],
            [2.5, "xs:gap-x-2.5"],
            [3, "xs:gap-x-3"],
            [3.5, "xs:gap-x-3.5"],
            [4, "xs:gap-x-4"],
            [5, "xs:gap-x-5"],
            [6, "xs:gap-x-6"],
            [7, "xs:gap-x-7"],
            [8, "xs:gap-x-8"],
            [9, "xs:gap-x-9"],
            [10, "xs:gap-x-10"],
            [11, "xs:gap-x-11"],
            [12, "xs:gap-x-12"],
            [14, "xs:gap-x-14"],
            [16, "xs:gap-x-16"],
            [20, "xs:gap-x-20"],
            [24, "xs:gap-x-24"],
            [28, "xs:gap-x-28"],
            [32, "xs:gap-x-32"],
            [36, "xs:gap-x-36"],
            [40, "xs:gap-x-40"],
            [44, "xs:gap-x-44"],
            [48, "xs:gap-x-48"],
            [52, "xs:gap-x-52"],
            [56, "xs:gap-x-56"],
            [60, "xs:gap-x-60"],
            [64, "xs:gap-x-64"],
            [72, "xs:gap-x-72"],
            [80, "xs:gap-x-80"],
            [96, "xs:gap-x-96"],
          ]),
        ],
        [
          "y",
          new Map<FlexSpacing, string>([
            [0, "xs:gap-y-0"],
            ["px", "xs:gap-y-px"],
            [0.5, "xs:gap-y-0.5"],
            [1, "xs:gap-y-1"],
            [1.5, "xs:gap-y-1.5"],
            [2, "xs:gap-y-2"],
            [2.5, "xs:gap-y-2.5"],
            [3, "xs:gap-y-3"],
            [3.5, "xs:gap-y-3.5"],
            [4, "xs:gap-y-4"],
            [5, "xs:gap-y-5"],
            [6, "xs:gap-y-6"],
            [7, "xs:gap-y-7"],
            [8, "xs:gap-y-8"],
            [9, "xs:gap-y-9"],
            [10, "xs:gap-y-10"],
            [11, "xs:gap-y-11"],
            [12, "xs:gap-y-12"],
            [14, "xs:gap-y-14"],
            [16, "xs:gap-y-16"],
            [20, "xs:gap-y-20"],
            [24, "xs:gap-y-24"],
            [28, "xs:gap-y-28"],
            [32, "xs:gap-y-32"],
            [36, "xs:gap-y-36"],
            [40, "xs:gap-y-40"],
            [44, "xs:gap-y-44"],
            [48, "xs:gap-y-48"],
            [52, "xs:gap-y-52"],
            [56, "xs:gap-y-56"],
            [60, "xs:gap-y-60"],
            [64, "xs:gap-y-64"],
            [72, "xs:gap-y-72"],
            [80, "xs:gap-y-80"],
            [96, "xs:gap-y-96"],
          ]),
        ],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<
        CSSSelector,
        Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
      >([
        [
          "active",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:active:gap-x-0"],
                    ["px", "xs:active:gap-x-px"],
                    [0.5, "xs:active:gap-x-0.5"],
                    [1, "xs:active:gap-x-1"],
                    [1.5, "xs:active:gap-x-1.5"],
                    [2, "xs:active:gap-x-2"],
                    [2.5, "xs:active:gap-x-2.5"],
                    [3, "xs:active:gap-x-3"],
                    [3.5, "xs:active:gap-x-3.5"],
                    [4, "xs:active:gap-x-4"],
                    [5, "xs:active:gap-x-5"],
                    [6, "xs:active:gap-x-6"],
                    [7, "xs:active:gap-x-7"],
                    [8, "xs:active:gap-x-8"],
                    [9, "xs:active:gap-x-9"],
                    [10, "xs:active:gap-x-10"],
                    [11, "xs:active:gap-x-11"],
                    [12, "xs:active:gap-x-12"],
                    [14, "xs:active:gap-x-14"],
                    [16, "xs:active:gap-x-16"],
                    [20, "xs:active:gap-x-20"],
                    [24, "xs:active:gap-x-24"],
                    [28, "xs:active:gap-x-28"],
                    [32, "xs:active:gap-x-32"],
                    [36, "xs:active:gap-x-36"],
                    [40, "xs:active:gap-x-40"],
                    [44, "xs:active:gap-x-44"],
                    [48, "xs:active:gap-x-48"],
                    [52, "xs:active:gap-x-52"],
                    [56, "xs:active:gap-x-56"],
                    [60, "xs:active:gap-x-60"],
                    [64, "xs:active:gap-x-64"],
                    [72, "xs:active:gap-x-72"],
                    [80, "xs:active:gap-x-80"],
                    [96, "xs:active:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:active:gap-y-0"],
                    ["px", "xs:active:gap-y-px"],
                    [0.5, "xs:active:gap-y-0.5"],
                    [1, "xs:active:gap-y-1"],
                    [1.5, "xs:active:gap-y-1.5"],
                    [2, "xs:active:gap-y-2"],
                    [2.5, "xs:active:gap-y-2.5"],
                    [3, "xs:active:gap-y-3"],
                    [3.5, "xs:active:gap-y-3.5"],
                    [4, "xs:active:gap-y-4"],
                    [5, "xs:active:gap-y-5"],
                    [6, "xs:active:gap-y-6"],
                    [7, "xs:active:gap-y-7"],
                    [8, "xs:active:gap-y-8"],
                    [9, "xs:active:gap-y-9"],
                    [10, "xs:active:gap-y-10"],
                    [11, "xs:active:gap-y-11"],
                    [12, "xs:active:gap-y-12"],
                    [14, "xs:active:gap-y-14"],
                    [16, "xs:active:gap-y-16"],
                    [20, "xs:active:gap-y-20"],
                    [24, "xs:active:gap-y-24"],
                    [28, "xs:active:gap-y-28"],
                    [32, "xs:active:gap-y-32"],
                    [36, "xs:active:gap-y-36"],
                    [40, "xs:active:gap-y-40"],
                    [44, "xs:active:gap-y-44"],
                    [48, "xs:active:gap-y-48"],
                    [52, "xs:active:gap-y-52"],
                    [56, "xs:active:gap-y-56"],
                    [60, "xs:active:gap-y-60"],
                    [64, "xs:active:gap-y-64"],
                    [72, "xs:active:gap-y-72"],
                    [80, "xs:active:gap-y-80"],
                    [96, "xs:active:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:active:gap-x-0"],
                    ["px", "sm:active:gap-x-px"],
                    [0.5, "sm:active:gap-x-0.5"],
                    [1, "sm:active:gap-x-1"],
                    [1.5, "sm:active:gap-x-1.5"],
                    [2, "sm:active:gap-x-2"],
                    [2.5, "sm:active:gap-x-2.5"],
                    [3, "sm:active:gap-x-3"],
                    [3.5, "sm:active:gap-x-3.5"],
                    [4, "sm:active:gap-x-4"],
                    [5, "sm:active:gap-x-5"],
                    [6, "sm:active:gap-x-6"],
                    [7, "sm:active:gap-x-7"],
                    [8, "sm:active:gap-x-8"],
                    [9, "sm:active:gap-x-9"],
                    [10, "sm:active:gap-x-10"],
                    [11, "sm:active:gap-x-11"],
                    [12, "sm:active:gap-x-12"],
                    [14, "sm:active:gap-x-14"],
                    [16, "sm:active:gap-x-16"],
                    [20, "sm:active:gap-x-20"],
                    [24, "sm:active:gap-x-24"],
                    [28, "sm:active:gap-x-28"],
                    [32, "sm:active:gap-x-32"],
                    [36, "sm:active:gap-x-36"],
                    [40, "sm:active:gap-x-40"],
                    [44, "sm:active:gap-x-44"],
                    [48, "sm:active:gap-x-48"],
                    [52, "sm:active:gap-x-52"],
                    [56, "sm:active:gap-x-56"],
                    [60, "sm:active:gap-x-60"],
                    [64, "sm:active:gap-x-64"],
                    [72, "sm:active:gap-x-72"],
                    [80, "sm:active:gap-x-80"],
                    [96, "sm:active:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:active:gap-y-0"],
                    ["px", "sm:active:gap-y-px"],
                    [0.5, "sm:active:gap-y-0.5"],
                    [1, "sm:active:gap-y-1"],
                    [1.5, "sm:active:gap-y-1.5"],
                    [2, "sm:active:gap-y-2"],
                    [2.5, "sm:active:gap-y-2.5"],
                    [3, "sm:active:gap-y-3"],
                    [3.5, "sm:active:gap-y-3.5"],
                    [4, "sm:active:gap-y-4"],
                    [5, "sm:active:gap-y-5"],
                    [6, "sm:active:gap-y-6"],
                    [7, "sm:active:gap-y-7"],
                    [8, "sm:active:gap-y-8"],
                    [9, "sm:active:gap-y-9"],
                    [10, "sm:active:gap-y-10"],
                    [11, "sm:active:gap-y-11"],
                    [12, "sm:active:gap-y-12"],
                    [14, "sm:active:gap-y-14"],
                    [16, "sm:active:gap-y-16"],
                    [20, "sm:active:gap-y-20"],
                    [24, "sm:active:gap-y-24"],
                    [28, "sm:active:gap-y-28"],
                    [32, "sm:active:gap-y-32"],
                    [36, "sm:active:gap-y-36"],
                    [40, "sm:active:gap-y-40"],
                    [44, "sm:active:gap-y-44"],
                    [48, "sm:active:gap-y-48"],
                    [52, "sm:active:gap-y-52"],
                    [56, "sm:active:gap-y-56"],
                    [60, "sm:active:gap-y-60"],
                    [64, "sm:active:gap-y-64"],
                    [72, "sm:active:gap-y-72"],
                    [80, "sm:active:gap-y-80"],
                    [96, "sm:active:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:active:gap-x-0"],
                    ["px", "md:active:gap-x-px"],
                    [0.5, "md:active:gap-x-0.5"],
                    [1, "md:active:gap-x-1"],
                    [1.5, "md:active:gap-x-1.5"],
                    [2, "md:active:gap-x-2"],
                    [2.5, "md:active:gap-x-2.5"],
                    [3, "md:active:gap-x-3"],
                    [3.5, "md:active:gap-x-3.5"],
                    [4, "md:active:gap-x-4"],
                    [5, "md:active:gap-x-5"],
                    [6, "md:active:gap-x-6"],
                    [7, "md:active:gap-x-7"],
                    [8, "md:active:gap-x-8"],
                    [9, "md:active:gap-x-9"],
                    [10, "md:active:gap-x-10"],
                    [11, "md:active:gap-x-11"],
                    [12, "md:active:gap-x-12"],
                    [14, "md:active:gap-x-14"],
                    [16, "md:active:gap-x-16"],
                    [20, "md:active:gap-x-20"],
                    [24, "md:active:gap-x-24"],
                    [28, "md:active:gap-x-28"],
                    [32, "md:active:gap-x-32"],
                    [36, "md:active:gap-x-36"],
                    [40, "md:active:gap-x-40"],
                    [44, "md:active:gap-x-44"],
                    [48, "md:active:gap-x-48"],
                    [52, "md:active:gap-x-52"],
                    [56, "md:active:gap-x-56"],
                    [60, "md:active:gap-x-60"],
                    [64, "md:active:gap-x-64"],
                    [72, "md:active:gap-x-72"],
                    [80, "md:active:gap-x-80"],
                    [96, "md:active:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:active:gap-y-0"],
                    ["px", "md:active:gap-y-px"],
                    [0.5, "md:active:gap-y-0.5"],
                    [1, "md:active:gap-y-1"],
                    [1.5, "md:active:gap-y-1.5"],
                    [2, "md:active:gap-y-2"],
                    [2.5, "md:active:gap-y-2.5"],
                    [3, "md:active:gap-y-3"],
                    [3.5, "md:active:gap-y-3.5"],
                    [4, "md:active:gap-y-4"],
                    [5, "md:active:gap-y-5"],
                    [6, "md:active:gap-y-6"],
                    [7, "md:active:gap-y-7"],
                    [8, "md:active:gap-y-8"],
                    [9, "md:active:gap-y-9"],
                    [10, "md:active:gap-y-10"],
                    [11, "md:active:gap-y-11"],
                    [12, "md:active:gap-y-12"],
                    [14, "md:active:gap-y-14"],
                    [16, "md:active:gap-y-16"],
                    [20, "md:active:gap-y-20"],
                    [24, "md:active:gap-y-24"],
                    [28, "md:active:gap-y-28"],
                    [32, "md:active:gap-y-32"],
                    [36, "md:active:gap-y-36"],
                    [40, "md:active:gap-y-40"],
                    [44, "md:active:gap-y-44"],
                    [48, "md:active:gap-y-48"],
                    [52, "md:active:gap-y-52"],
                    [56, "md:active:gap-y-56"],
                    [60, "md:active:gap-y-60"],
                    [64, "md:active:gap-y-64"],
                    [72, "md:active:gap-y-72"],
                    [80, "md:active:gap-y-80"],
                    [96, "md:active:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:active:gap-x-0"],
                    ["px", "lg:active:gap-x-px"],
                    [0.5, "lg:active:gap-x-0.5"],
                    [1, "lg:active:gap-x-1"],
                    [1.5, "lg:active:gap-x-1.5"],
                    [2, "lg:active:gap-x-2"],
                    [2.5, "lg:active:gap-x-2.5"],
                    [3, "lg:active:gap-x-3"],
                    [3.5, "lg:active:gap-x-3.5"],
                    [4, "lg:active:gap-x-4"],
                    [5, "lg:active:gap-x-5"],
                    [6, "lg:active:gap-x-6"],
                    [7, "lg:active:gap-x-7"],
                    [8, "lg:active:gap-x-8"],
                    [9, "lg:active:gap-x-9"],
                    [10, "lg:active:gap-x-10"],
                    [11, "lg:active:gap-x-11"],
                    [12, "lg:active:gap-x-12"],
                    [14, "lg:active:gap-x-14"],
                    [16, "lg:active:gap-x-16"],
                    [20, "lg:active:gap-x-20"],
                    [24, "lg:active:gap-x-24"],
                    [28, "lg:active:gap-x-28"],
                    [32, "lg:active:gap-x-32"],
                    [36, "lg:active:gap-x-36"],
                    [40, "lg:active:gap-x-40"],
                    [44, "lg:active:gap-x-44"],
                    [48, "lg:active:gap-x-48"],
                    [52, "lg:active:gap-x-52"],
                    [56, "lg:active:gap-x-56"],
                    [60, "lg:active:gap-x-60"],
                    [64, "lg:active:gap-x-64"],
                    [72, "lg:active:gap-x-72"],
                    [80, "lg:active:gap-x-80"],
                    [96, "lg:active:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:active:gap-y-0"],
                    ["px", "lg:active:gap-y-px"],
                    [0.5, "lg:active:gap-y-0.5"],
                    [1, "lg:active:gap-y-1"],
                    [1.5, "lg:active:gap-y-1.5"],
                    [2, "lg:active:gap-y-2"],
                    [2.5, "lg:active:gap-y-2.5"],
                    [3, "lg:active:gap-y-3"],
                    [3.5, "lg:active:gap-y-3.5"],
                    [4, "lg:active:gap-y-4"],
                    [5, "lg:active:gap-y-5"],
                    [6, "lg:active:gap-y-6"],
                    [7, "lg:active:gap-y-7"],
                    [8, "lg:active:gap-y-8"],
                    [9, "lg:active:gap-y-9"],
                    [10, "lg:active:gap-y-10"],
                    [11, "lg:active:gap-y-11"],
                    [12, "lg:active:gap-y-12"],
                    [14, "lg:active:gap-y-14"],
                    [16, "lg:active:gap-y-16"],
                    [20, "lg:active:gap-y-20"],
                    [24, "lg:active:gap-y-24"],
                    [28, "lg:active:gap-y-28"],
                    [32, "lg:active:gap-y-32"],
                    [36, "lg:active:gap-y-36"],
                    [40, "lg:active:gap-y-40"],
                    [44, "lg:active:gap-y-44"],
                    [48, "lg:active:gap-y-48"],
                    [52, "lg:active:gap-y-52"],
                    [56, "lg:active:gap-y-56"],
                    [60, "lg:active:gap-y-60"],
                    [64, "lg:active:gap-y-64"],
                    [72, "lg:active:gap-y-72"],
                    [80, "lg:active:gap-y-80"],
                    [96, "lg:active:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:active:gap-x-0"],
                    ["px", "xl:active:gap-x-px"],
                    [0.5, "xl:active:gap-x-0.5"],
                    [1, "xl:active:gap-x-1"],
                    [1.5, "xl:active:gap-x-1.5"],
                    [2, "xl:active:gap-x-2"],
                    [2.5, "xl:active:gap-x-2.5"],
                    [3, "xl:active:gap-x-3"],
                    [3.5, "xl:active:gap-x-3.5"],
                    [4, "xl:active:gap-x-4"],
                    [5, "xl:active:gap-x-5"],
                    [6, "xl:active:gap-x-6"],
                    [7, "xl:active:gap-x-7"],
                    [8, "xl:active:gap-x-8"],
                    [9, "xl:active:gap-x-9"],
                    [10, "xl:active:gap-x-10"],
                    [11, "xl:active:gap-x-11"],
                    [12, "xl:active:gap-x-12"],
                    [14, "xl:active:gap-x-14"],
                    [16, "xl:active:gap-x-16"],
                    [20, "xl:active:gap-x-20"],
                    [24, "xl:active:gap-x-24"],
                    [28, "xl:active:gap-x-28"],
                    [32, "xl:active:gap-x-32"],
                    [36, "xl:active:gap-x-36"],
                    [40, "xl:active:gap-x-40"],
                    [44, "xl:active:gap-x-44"],
                    [48, "xl:active:gap-x-48"],
                    [52, "xl:active:gap-x-52"],
                    [56, "xl:active:gap-x-56"],
                    [60, "xl:active:gap-x-60"],
                    [64, "xl:active:gap-x-64"],
                    [72, "xl:active:gap-x-72"],
                    [80, "xl:active:gap-x-80"],
                    [96, "xl:active:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:active:gap-y-0"],
                    ["px", "xl:active:gap-y-px"],
                    [0.5, "xl:active:gap-y-0.5"],
                    [1, "xl:active:gap-y-1"],
                    [1.5, "xl:active:gap-y-1.5"],
                    [2, "xl:active:gap-y-2"],
                    [2.5, "xl:active:gap-y-2.5"],
                    [3, "xl:active:gap-y-3"],
                    [3.5, "xl:active:gap-y-3.5"],
                    [4, "xl:active:gap-y-4"],
                    [5, "xl:active:gap-y-5"],
                    [6, "xl:active:gap-y-6"],
                    [7, "xl:active:gap-y-7"],
                    [8, "xl:active:gap-y-8"],
                    [9, "xl:active:gap-y-9"],
                    [10, "xl:active:gap-y-10"],
                    [11, "xl:active:gap-y-11"],
                    [12, "xl:active:gap-y-12"],
                    [14, "xl:active:gap-y-14"],
                    [16, "xl:active:gap-y-16"],
                    [20, "xl:active:gap-y-20"],
                    [24, "xl:active:gap-y-24"],
                    [28, "xl:active:gap-y-28"],
                    [32, "xl:active:gap-y-32"],
                    [36, "xl:active:gap-y-36"],
                    [40, "xl:active:gap-y-40"],
                    [44, "xl:active:gap-y-44"],
                    [48, "xl:active:gap-y-48"],
                    [52, "xl:active:gap-y-52"],
                    [56, "xl:active:gap-y-56"],
                    [60, "xl:active:gap-y-60"],
                    [64, "xl:active:gap-y-64"],
                    [72, "xl:active:gap-y-72"],
                    [80, "xl:active:gap-y-80"],
                    [96, "xl:active:gap-y-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:disabled:gap-x-0"],
                    ["px", "xs:disabled:gap-x-px"],
                    [0.5, "xs:disabled:gap-x-0.5"],
                    [1, "xs:disabled:gap-x-1"],
                    [1.5, "xs:disabled:gap-x-1.5"],
                    [2, "xs:disabled:gap-x-2"],
                    [2.5, "xs:disabled:gap-x-2.5"],
                    [3, "xs:disabled:gap-x-3"],
                    [3.5, "xs:disabled:gap-x-3.5"],
                    [4, "xs:disabled:gap-x-4"],
                    [5, "xs:disabled:gap-x-5"],
                    [6, "xs:disabled:gap-x-6"],
                    [7, "xs:disabled:gap-x-7"],
                    [8, "xs:disabled:gap-x-8"],
                    [9, "xs:disabled:gap-x-9"],
                    [10, "xs:disabled:gap-x-10"],
                    [11, "xs:disabled:gap-x-11"],
                    [12, "xs:disabled:gap-x-12"],
                    [14, "xs:disabled:gap-x-14"],
                    [16, "xs:disabled:gap-x-16"],
                    [20, "xs:disabled:gap-x-20"],
                    [24, "xs:disabled:gap-x-24"],
                    [28, "xs:disabled:gap-x-28"],
                    [32, "xs:disabled:gap-x-32"],
                    [36, "xs:disabled:gap-x-36"],
                    [40, "xs:disabled:gap-x-40"],
                    [44, "xs:disabled:gap-x-44"],
                    [48, "xs:disabled:gap-x-48"],
                    [52, "xs:disabled:gap-x-52"],
                    [56, "xs:disabled:gap-x-56"],
                    [60, "xs:disabled:gap-x-60"],
                    [64, "xs:disabled:gap-x-64"],
                    [72, "xs:disabled:gap-x-72"],
                    [80, "xs:disabled:gap-x-80"],
                    [96, "xs:disabled:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:disabled:gap-y-0"],
                    ["px", "xs:disabled:gap-y-px"],
                    [0.5, "xs:disabled:gap-y-0.5"],
                    [1, "xs:disabled:gap-y-1"],
                    [1.5, "xs:disabled:gap-y-1.5"],
                    [2, "xs:disabled:gap-y-2"],
                    [2.5, "xs:disabled:gap-y-2.5"],
                    [3, "xs:disabled:gap-y-3"],
                    [3.5, "xs:disabled:gap-y-3.5"],
                    [4, "xs:disabled:gap-y-4"],
                    [5, "xs:disabled:gap-y-5"],
                    [6, "xs:disabled:gap-y-6"],
                    [7, "xs:disabled:gap-y-7"],
                    [8, "xs:disabled:gap-y-8"],
                    [9, "xs:disabled:gap-y-9"],
                    [10, "xs:disabled:gap-y-10"],
                    [11, "xs:disabled:gap-y-11"],
                    [12, "xs:disabled:gap-y-12"],
                    [14, "xs:disabled:gap-y-14"],
                    [16, "xs:disabled:gap-y-16"],
                    [20, "xs:disabled:gap-y-20"],
                    [24, "xs:disabled:gap-y-24"],
                    [28, "xs:disabled:gap-y-28"],
                    [32, "xs:disabled:gap-y-32"],
                    [36, "xs:disabled:gap-y-36"],
                    [40, "xs:disabled:gap-y-40"],
                    [44, "xs:disabled:gap-y-44"],
                    [48, "xs:disabled:gap-y-48"],
                    [52, "xs:disabled:gap-y-52"],
                    [56, "xs:disabled:gap-y-56"],
                    [60, "xs:disabled:gap-y-60"],
                    [64, "xs:disabled:gap-y-64"],
                    [72, "xs:disabled:gap-y-72"],
                    [80, "xs:disabled:gap-y-80"],
                    [96, "xs:disabled:gap-y-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:disabled:gap-x-0"],
                    ["px", "sm:disabled:gap-x-px"],
                    [0.5, "sm:disabled:gap-x-0.5"],
                    [1, "sm:disabled:gap-x-1"],
                    [1.5, "sm:disabled:gap-x-1.5"],
                    [2, "sm:disabled:gap-x-2"],
                    [2.5, "sm:disabled:gap-x-2.5"],
                    [3, "sm:disabled:gap-x-3"],
                    [3.5, "sm:disabled:gap-x-3.5"],
                    [4, "sm:disabled:gap-x-4"],
                    [5, "sm:disabled:gap-x-5"],
                    [6, "sm:disabled:gap-x-6"],
                    [7, "sm:disabled:gap-x-7"],
                    [8, "sm:disabled:gap-x-8"],
                    [9, "sm:disabled:gap-x-9"],
                    [10, "sm:disabled:gap-x-10"],
                    [11, "sm:disabled:gap-x-11"],
                    [12, "sm:disabled:gap-x-12"],
                    [14, "sm:disabled:gap-x-14"],
                    [16, "sm:disabled:gap-x-16"],
                    [20, "sm:disabled:gap-x-20"],
                    [24, "sm:disabled:gap-x-24"],
                    [28, "sm:disabled:gap-x-28"],
                    [32, "sm:disabled:gap-x-32"],
                    [36, "sm:disabled:gap-x-36"],
                    [40, "sm:disabled:gap-x-40"],
                    [44, "sm:disabled:gap-x-44"],
                    [48, "sm:disabled:gap-x-48"],
                    [52, "sm:disabled:gap-x-52"],
                    [56, "sm:disabled:gap-x-56"],
                    [60, "sm:disabled:gap-x-60"],
                    [64, "sm:disabled:gap-x-64"],
                    [72, "sm:disabled:gap-x-72"],
                    [80, "sm:disabled:gap-x-80"],
                    [96, "sm:disabled:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:disabled:gap-y-0"],
                    ["px", "sm:disabled:gap-y-px"],
                    [0.5, "sm:disabled:gap-y-0.5"],
                    [1, "sm:disabled:gap-y-1"],
                    [1.5, "sm:disabled:gap-y-1.5"],
                    [2, "sm:disabled:gap-y-2"],
                    [2.5, "sm:disabled:gap-y-2.5"],
                    [3, "sm:disabled:gap-y-3"],
                    [3.5, "sm:disabled:gap-y-3.5"],
                    [4, "sm:disabled:gap-y-4"],
                    [5, "sm:disabled:gap-y-5"],
                    [6, "sm:disabled:gap-y-6"],
                    [7, "sm:disabled:gap-y-7"],
                    [8, "sm:disabled:gap-y-8"],
                    [9, "sm:disabled:gap-y-9"],
                    [10, "sm:disabled:gap-y-10"],
                    [11, "sm:disabled:gap-y-11"],
                    [12, "sm:disabled:gap-y-12"],
                    [14, "sm:disabled:gap-y-14"],
                    [16, "sm:disabled:gap-y-16"],
                    [20, "sm:disabled:gap-y-20"],
                    [24, "sm:disabled:gap-y-24"],
                    [28, "sm:disabled:gap-y-28"],
                    [32, "sm:disabled:gap-y-32"],
                    [36, "sm:disabled:gap-y-36"],
                    [40, "sm:disabled:gap-y-40"],
                    [44, "sm:disabled:gap-y-44"],
                    [48, "sm:disabled:gap-y-48"],
                    [52, "sm:disabled:gap-y-52"],
                    [56, "sm:disabled:gap-y-56"],
                    [60, "sm:disabled:gap-y-60"],
                    [64, "sm:disabled:gap-y-64"],
                    [72, "sm:disabled:gap-y-72"],
                    [80, "sm:disabled:gap-y-80"],
                    [96, "sm:disabled:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:disabled:gap-x-0"],
                    ["px", "md:disabled:gap-x-px"],
                    [0.5, "md:disabled:gap-x-0.5"],
                    [1, "md:disabled:gap-x-1"],
                    [1.5, "md:disabled:gap-x-1.5"],
                    [2, "md:disabled:gap-x-2"],
                    [2.5, "md:disabled:gap-x-2.5"],
                    [3, "md:disabled:gap-x-3"],
                    [3.5, "md:disabled:gap-x-3.5"],
                    [4, "md:disabled:gap-x-4"],
                    [5, "md:disabled:gap-x-5"],
                    [6, "md:disabled:gap-x-6"],
                    [7, "md:disabled:gap-x-7"],
                    [8, "md:disabled:gap-x-8"],
                    [9, "md:disabled:gap-x-9"],
                    [10, "md:disabled:gap-x-10"],
                    [11, "md:disabled:gap-x-11"],
                    [12, "md:disabled:gap-x-12"],
                    [14, "md:disabled:gap-x-14"],
                    [16, "md:disabled:gap-x-16"],
                    [20, "md:disabled:gap-x-20"],
                    [24, "md:disabled:gap-x-24"],
                    [28, "md:disabled:gap-x-28"],
                    [32, "md:disabled:gap-x-32"],
                    [36, "md:disabled:gap-x-36"],
                    [40, "md:disabled:gap-x-40"],
                    [44, "md:disabled:gap-x-44"],
                    [48, "md:disabled:gap-x-48"],
                    [52, "md:disabled:gap-x-52"],
                    [56, "md:disabled:gap-x-56"],
                    [60, "md:disabled:gap-x-60"],
                    [64, "md:disabled:gap-x-64"],
                    [72, "md:disabled:gap-x-72"],
                    [80, "md:disabled:gap-x-80"],
                    [96, "md:disabled:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:disabled:gap-y-0"],
                    ["px", "md:disabled:gap-y-px"],
                    [0.5, "md:disabled:gap-y-0.5"],
                    [1, "md:disabled:gap-y-1"],
                    [1.5, "md:disabled:gap-y-1.5"],
                    [2, "md:disabled:gap-y-2"],
                    [2.5, "md:disabled:gap-y-2.5"],
                    [3, "md:disabled:gap-y-3"],
                    [3.5, "md:disabled:gap-y-3.5"],
                    [4, "md:disabled:gap-y-4"],
                    [5, "md:disabled:gap-y-5"],
                    [6, "md:disabled:gap-y-6"],
                    [7, "md:disabled:gap-y-7"],
                    [8, "md:disabled:gap-y-8"],
                    [9, "md:disabled:gap-y-9"],
                    [10, "md:disabled:gap-y-10"],
                    [11, "md:disabled:gap-y-11"],
                    [12, "md:disabled:gap-y-12"],
                    [14, "md:disabled:gap-y-14"],
                    [16, "md:disabled:gap-y-16"],
                    [20, "md:disabled:gap-y-20"],
                    [24, "md:disabled:gap-y-24"],
                    [28, "md:disabled:gap-y-28"],
                    [32, "md:disabled:gap-y-32"],
                    [36, "md:disabled:gap-y-36"],
                    [40, "md:disabled:gap-y-40"],
                    [44, "md:disabled:gap-y-44"],
                    [48, "md:disabled:gap-y-48"],
                    [52, "md:disabled:gap-y-52"],
                    [56, "md:disabled:gap-y-56"],
                    [60, "md:disabled:gap-y-60"],
                    [64, "md:disabled:gap-y-64"],
                    [72, "md:disabled:gap-y-72"],
                    [80, "md:disabled:gap-y-80"],
                    [96, "md:disabled:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:disabled:gap-x-0"],
                    ["px", "lg:disabled:gap-x-px"],
                    [0.5, "lg:disabled:gap-x-0.5"],
                    [1, "lg:disabled:gap-x-1"],
                    [1.5, "lg:disabled:gap-x-1.5"],
                    [2, "lg:disabled:gap-x-2"],
                    [2.5, "lg:disabled:gap-x-2.5"],
                    [3, "lg:disabled:gap-x-3"],
                    [3.5, "lg:disabled:gap-x-3.5"],
                    [4, "lg:disabled:gap-x-4"],
                    [5, "lg:disabled:gap-x-5"],
                    [6, "lg:disabled:gap-x-6"],
                    [7, "lg:disabled:gap-x-7"],
                    [8, "lg:disabled:gap-x-8"],
                    [9, "lg:disabled:gap-x-9"],
                    [10, "lg:disabled:gap-x-10"],
                    [11, "lg:disabled:gap-x-11"],
                    [12, "lg:disabled:gap-x-12"],
                    [14, "lg:disabled:gap-x-14"],
                    [16, "lg:disabled:gap-x-16"],
                    [20, "lg:disabled:gap-x-20"],
                    [24, "lg:disabled:gap-x-24"],
                    [28, "lg:disabled:gap-x-28"],
                    [32, "lg:disabled:gap-x-32"],
                    [36, "lg:disabled:gap-x-36"],
                    [40, "lg:disabled:gap-x-40"],
                    [44, "lg:disabled:gap-x-44"],
                    [48, "lg:disabled:gap-x-48"],
                    [52, "lg:disabled:gap-x-52"],
                    [56, "lg:disabled:gap-x-56"],
                    [60, "lg:disabled:gap-x-60"],
                    [64, "lg:disabled:gap-x-64"],
                    [72, "lg:disabled:gap-x-72"],
                    [80, "lg:disabled:gap-x-80"],
                    [96, "lg:disabled:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:disabled:gap-y-0"],
                    ["px", "lg:disabled:gap-y-px"],
                    [0.5, "lg:disabled:gap-y-0.5"],
                    [1, "lg:disabled:gap-y-1"],
                    [1.5, "lg:disabled:gap-y-1.5"],
                    [2, "lg:disabled:gap-y-2"],
                    [2.5, "lg:disabled:gap-y-2.5"],
                    [3, "lg:disabled:gap-y-3"],
                    [3.5, "lg:disabled:gap-y-3.5"],
                    [4, "lg:disabled:gap-y-4"],
                    [5, "lg:disabled:gap-y-5"],
                    [6, "lg:disabled:gap-y-6"],
                    [7, "lg:disabled:gap-y-7"],
                    [8, "lg:disabled:gap-y-8"],
                    [9, "lg:disabled:gap-y-9"],
                    [10, "lg:disabled:gap-y-10"],
                    [11, "lg:disabled:gap-y-11"],
                    [12, "lg:disabled:gap-y-12"],
                    [14, "lg:disabled:gap-y-14"],
                    [16, "lg:disabled:gap-y-16"],
                    [20, "lg:disabled:gap-y-20"],
                    [24, "lg:disabled:gap-y-24"],
                    [28, "lg:disabled:gap-y-28"],
                    [32, "lg:disabled:gap-y-32"],
                    [36, "lg:disabled:gap-y-36"],
                    [40, "lg:disabled:gap-y-40"],
                    [44, "lg:disabled:gap-y-44"],
                    [48, "lg:disabled:gap-y-48"],
                    [52, "lg:disabled:gap-y-52"],
                    [56, "lg:disabled:gap-y-56"],
                    [60, "lg:disabled:gap-y-60"],
                    [64, "lg:disabled:gap-y-64"],
                    [72, "lg:disabled:gap-y-72"],
                    [80, "lg:disabled:gap-y-80"],
                    [96, "lg:disabled:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:disabled:gap-x-0"],
                    ["px", "xl:disabled:gap-x-px"],
                    [0.5, "xl:disabled:gap-x-0.5"],
                    [1, "xl:disabled:gap-x-1"],
                    [1.5, "xl:disabled:gap-x-1.5"],
                    [2, "xl:disabled:gap-x-2"],
                    [2.5, "xl:disabled:gap-x-2.5"],
                    [3, "xl:disabled:gap-x-3"],
                    [3.5, "xl:disabled:gap-x-3.5"],
                    [4, "xl:disabled:gap-x-4"],
                    [5, "xl:disabled:gap-x-5"],
                    [6, "xl:disabled:gap-x-6"],
                    [7, "xl:disabled:gap-x-7"],
                    [8, "xl:disabled:gap-x-8"],
                    [9, "xl:disabled:gap-x-9"],
                    [10, "xl:disabled:gap-x-10"],
                    [11, "xl:disabled:gap-x-11"],
                    [12, "xl:disabled:gap-x-12"],
                    [14, "xl:disabled:gap-x-14"],
                    [16, "xl:disabled:gap-x-16"],
                    [20, "xl:disabled:gap-x-20"],
                    [24, "xl:disabled:gap-x-24"],
                    [28, "xl:disabled:gap-x-28"],
                    [32, "xl:disabled:gap-x-32"],
                    [36, "xl:disabled:gap-x-36"],
                    [40, "xl:disabled:gap-x-40"],
                    [44, "xl:disabled:gap-x-44"],
                    [48, "xl:disabled:gap-x-48"],
                    [52, "xl:disabled:gap-x-52"],
                    [56, "xl:disabled:gap-x-56"],
                    [60, "xl:disabled:gap-x-60"],
                    [64, "xl:disabled:gap-x-64"],
                    [72, "xl:disabled:gap-x-72"],
                    [80, "xl:disabled:gap-x-80"],
                    [96, "xl:disabled:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:disabled:gap-y-0"],
                    ["px", "xl:disabled:gap-y-px"],
                    [0.5, "xl:disabled:gap-y-0.5"],
                    [1, "xl:disabled:gap-y-1"],
                    [1.5, "xl:disabled:gap-y-1.5"],
                    [2, "xl:disabled:gap-y-2"],
                    [2.5, "xl:disabled:gap-y-2.5"],
                    [3, "xl:disabled:gap-y-3"],
                    [3.5, "xl:disabled:gap-y-3.5"],
                    [4, "xl:disabled:gap-y-4"],
                    [5, "xl:disabled:gap-y-5"],
                    [6, "xl:disabled:gap-y-6"],
                    [7, "xl:disabled:gap-y-7"],
                    [8, "xl:disabled:gap-y-8"],
                    [9, "xl:disabled:gap-y-9"],
                    [10, "xl:disabled:gap-y-10"],
                    [11, "xl:disabled:gap-y-11"],
                    [12, "xl:disabled:gap-y-12"],
                    [14, "xl:disabled:gap-y-14"],
                    [16, "xl:disabled:gap-y-16"],
                    [20, "xl:disabled:gap-y-20"],
                    [24, "xl:disabled:gap-y-24"],
                    [28, "xl:disabled:gap-y-28"],
                    [32, "xl:disabled:gap-y-32"],
                    [36, "xl:disabled:gap-y-36"],
                    [40, "xl:disabled:gap-y-40"],
                    [44, "xl:disabled:gap-y-44"],
                    [48, "xl:disabled:gap-y-48"],
                    [52, "xl:disabled:gap-y-52"],
                    [56, "xl:disabled:gap-y-56"],
                    [60, "xl:disabled:gap-y-60"],
                    [64, "xl:disabled:gap-y-64"],
                    [72, "xl:disabled:gap-y-72"],
                    [80, "xl:disabled:gap-y-80"],
                    [96, "xl:disabled:gap-y-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:hover:gap-x-0"],
                    ["px", "xs:hover:gap-x-px"],
                    [0.5, "xs:hover:gap-x-0.5"],
                    [1, "xs:hover:gap-x-1"],
                    [1.5, "xs:hover:gap-x-1.5"],
                    [2, "xs:hover:gap-x-2"],
                    [2.5, "xs:hover:gap-x-2.5"],
                    [3, "xs:hover:gap-x-3"],
                    [3.5, "xs:hover:gap-x-3.5"],
                    [4, "xs:hover:gap-x-4"],
                    [5, "xs:hover:gap-x-5"],
                    [6, "xs:hover:gap-x-6"],
                    [7, "xs:hover:gap-x-7"],
                    [8, "xs:hover:gap-x-8"],
                    [9, "xs:hover:gap-x-9"],
                    [10, "xs:hover:gap-x-10"],
                    [11, "xs:hover:gap-x-11"],
                    [12, "xs:hover:gap-x-12"],
                    [14, "xs:hover:gap-x-14"],
                    [16, "xs:hover:gap-x-16"],
                    [20, "xs:hover:gap-x-20"],
                    [24, "xs:hover:gap-x-24"],
                    [28, "xs:hover:gap-x-28"],
                    [32, "xs:hover:gap-x-32"],
                    [36, "xs:hover:gap-x-36"],
                    [40, "xs:hover:gap-x-40"],
                    [44, "xs:hover:gap-x-44"],
                    [48, "xs:hover:gap-x-48"],
                    [52, "xs:hover:gap-x-52"],
                    [56, "xs:hover:gap-x-56"],
                    [60, "xs:hover:gap-x-60"],
                    [64, "xs:hover:gap-x-64"],
                    [72, "xs:hover:gap-x-72"],
                    [80, "xs:hover:gap-x-80"],
                    [96, "xs:hover:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:hover:gap-y-0"],
                    ["px", "xs:hover:gap-y-px"],
                    [0.5, "xs:hover:gap-y-0.5"],
                    [1, "xs:hover:gap-y-1"],
                    [1.5, "xs:hover:gap-y-1.5"],
                    [2, "xs:hover:gap-y-2"],
                    [2.5, "xs:hover:gap-y-2.5"],
                    [3, "xs:hover:gap-y-3"],
                    [3.5, "xs:hover:gap-y-3.5"],
                    [4, "xs:hover:gap-y-4"],
                    [5, "xs:hover:gap-y-5"],
                    [6, "xs:hover:gap-y-6"],
                    [7, "xs:hover:gap-y-7"],
                    [8, "xs:hover:gap-y-8"],
                    [9, "xs:hover:gap-y-9"],
                    [10, "xs:hover:gap-y-10"],
                    [11, "xs:hover:gap-y-11"],
                    [12, "xs:hover:gap-y-12"],
                    [14, "xs:hover:gap-y-14"],
                    [16, "xs:hover:gap-y-16"],
                    [20, "xs:hover:gap-y-20"],
                    [24, "xs:hover:gap-y-24"],
                    [28, "xs:hover:gap-y-28"],
                    [32, "xs:hover:gap-y-32"],
                    [36, "xs:hover:gap-y-36"],
                    [40, "xs:hover:gap-y-40"],
                    [44, "xs:hover:gap-y-44"],
                    [48, "xs:hover:gap-y-48"],
                    [52, "xs:hover:gap-y-52"],
                    [56, "xs:hover:gap-y-56"],
                    [60, "xs:hover:gap-y-60"],
                    [64, "xs:hover:gap-y-64"],
                    [72, "xs:hover:gap-y-72"],
                    [80, "xs:hover:gap-y-80"],
                    [96, "xs:hover:gap-y-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:hover:gap-x-0"],
                    ["px", "sm:hover:gap-x-px"],
                    [0.5, "sm:hover:gap-x-0.5"],
                    [1, "sm:hover:gap-x-1"],
                    [1.5, "sm:hover:gap-x-1.5"],
                    [2, "sm:hover:gap-x-2"],
                    [2.5, "sm:hover:gap-x-2.5"],
                    [3, "sm:hover:gap-x-3"],
                    [3.5, "sm:hover:gap-x-3.5"],
                    [4, "sm:hover:gap-x-4"],
                    [5, "sm:hover:gap-x-5"],
                    [6, "sm:hover:gap-x-6"],
                    [7, "sm:hover:gap-x-7"],
                    [8, "sm:hover:gap-x-8"],
                    [9, "sm:hover:gap-x-9"],
                    [10, "sm:hover:gap-x-10"],
                    [11, "sm:hover:gap-x-11"],
                    [12, "sm:hover:gap-x-12"],
                    [14, "sm:hover:gap-x-14"],
                    [16, "sm:hover:gap-x-16"],
                    [20, "sm:hover:gap-x-20"],
                    [24, "sm:hover:gap-x-24"],
                    [28, "sm:hover:gap-x-28"],
                    [32, "sm:hover:gap-x-32"],
                    [36, "sm:hover:gap-x-36"],
                    [40, "sm:hover:gap-x-40"],
                    [44, "sm:hover:gap-x-44"],
                    [48, "sm:hover:gap-x-48"],
                    [52, "sm:hover:gap-x-52"],
                    [56, "sm:hover:gap-x-56"],
                    [60, "sm:hover:gap-x-60"],
                    [64, "sm:hover:gap-x-64"],
                    [72, "sm:hover:gap-x-72"],
                    [80, "sm:hover:gap-x-80"],
                    [96, "sm:hover:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:hover:gap-y-0"],
                    ["px", "sm:hover:gap-y-px"],
                    [0.5, "sm:hover:gap-y-0.5"],
                    [1, "sm:hover:gap-y-1"],
                    [1.5, "sm:hover:gap-y-1.5"],
                    [2, "sm:hover:gap-y-2"],
                    [2.5, "sm:hover:gap-y-2.5"],
                    [3, "sm:hover:gap-y-3"],
                    [3.5, "sm:hover:gap-y-3.5"],
                    [4, "sm:hover:gap-y-4"],
                    [5, "sm:hover:gap-y-5"],
                    [6, "sm:hover:gap-y-6"],
                    [7, "sm:hover:gap-y-7"],
                    [8, "sm:hover:gap-y-8"],
                    [9, "sm:hover:gap-y-9"],
                    [10, "sm:hover:gap-y-10"],
                    [11, "sm:hover:gap-y-11"],
                    [12, "sm:hover:gap-y-12"],
                    [14, "sm:hover:gap-y-14"],
                    [16, "sm:hover:gap-y-16"],
                    [20, "sm:hover:gap-y-20"],
                    [24, "sm:hover:gap-y-24"],
                    [28, "sm:hover:gap-y-28"],
                    [32, "sm:hover:gap-y-32"],
                    [36, "sm:hover:gap-y-36"],
                    [40, "sm:hover:gap-y-40"],
                    [44, "sm:hover:gap-y-44"],
                    [48, "sm:hover:gap-y-48"],
                    [52, "sm:hover:gap-y-52"],
                    [56, "sm:hover:gap-y-56"],
                    [60, "sm:hover:gap-y-60"],
                    [64, "sm:hover:gap-y-64"],
                    [72, "sm:hover:gap-y-72"],
                    [80, "sm:hover:gap-y-80"],
                    [96, "sm:hover:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:hover:gap-x-0"],
                    ["px", "md:hover:gap-x-px"],
                    [0.5, "md:hover:gap-x-0.5"],
                    [1, "md:hover:gap-x-1"],
                    [1.5, "md:hover:gap-x-1.5"],
                    [2, "md:hover:gap-x-2"],
                    [2.5, "md:hover:gap-x-2.5"],
                    [3, "md:hover:gap-x-3"],
                    [3.5, "md:hover:gap-x-3.5"],
                    [4, "md:hover:gap-x-4"],
                    [5, "md:hover:gap-x-5"],
                    [6, "md:hover:gap-x-6"],
                    [7, "md:hover:gap-x-7"],
                    [8, "md:hover:gap-x-8"],
                    [9, "md:hover:gap-x-9"],
                    [10, "md:hover:gap-x-10"],
                    [11, "md:hover:gap-x-11"],
                    [12, "md:hover:gap-x-12"],
                    [14, "md:hover:gap-x-14"],
                    [16, "md:hover:gap-x-16"],
                    [20, "md:hover:gap-x-20"],
                    [24, "md:hover:gap-x-24"],
                    [28, "md:hover:gap-x-28"],
                    [32, "md:hover:gap-x-32"],
                    [36, "md:hover:gap-x-36"],
                    [40, "md:hover:gap-x-40"],
                    [44, "md:hover:gap-x-44"],
                    [48, "md:hover:gap-x-48"],
                    [52, "md:hover:gap-x-52"],
                    [56, "md:hover:gap-x-56"],
                    [60, "md:hover:gap-x-60"],
                    [64, "md:hover:gap-x-64"],
                    [72, "md:hover:gap-x-72"],
                    [80, "md:hover:gap-x-80"],
                    [96, "md:hover:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:hover:gap-y-0"],
                    ["px", "md:hover:gap-y-px"],
                    [0.5, "md:hover:gap-y-0.5"],
                    [1, "md:hover:gap-y-1"],
                    [1.5, "md:hover:gap-y-1.5"],
                    [2, "md:hover:gap-y-2"],
                    [2.5, "md:hover:gap-y-2.5"],
                    [3, "md:hover:gap-y-3"],
                    [3.5, "md:hover:gap-y-3.5"],
                    [4, "md:hover:gap-y-4"],
                    [5, "md:hover:gap-y-5"],
                    [6, "md:hover:gap-y-6"],
                    [7, "md:hover:gap-y-7"],
                    [8, "md:hover:gap-y-8"],
                    [9, "md:hover:gap-y-9"],
                    [10, "md:hover:gap-y-10"],
                    [11, "md:hover:gap-y-11"],
                    [12, "md:hover:gap-y-12"],
                    [14, "md:hover:gap-y-14"],
                    [16, "md:hover:gap-y-16"],
                    [20, "md:hover:gap-y-20"],
                    [24, "md:hover:gap-y-24"],
                    [28, "md:hover:gap-y-28"],
                    [32, "md:hover:gap-y-32"],
                    [36, "md:hover:gap-y-36"],
                    [40, "md:hover:gap-y-40"],
                    [44, "md:hover:gap-y-44"],
                    [48, "md:hover:gap-y-48"],
                    [52, "md:hover:gap-y-52"],
                    [56, "md:hover:gap-y-56"],
                    [60, "md:hover:gap-y-60"],
                    [64, "md:hover:gap-y-64"],
                    [72, "md:hover:gap-y-72"],
                    [80, "md:hover:gap-y-80"],
                    [96, "md:hover:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:hover:gap-x-0"],
                    ["px", "lg:hover:gap-x-px"],
                    [0.5, "lg:hover:gap-x-0.5"],
                    [1, "lg:hover:gap-x-1"],
                    [1.5, "lg:hover:gap-x-1.5"],
                    [2, "lg:hover:gap-x-2"],
                    [2.5, "lg:hover:gap-x-2.5"],
                    [3, "lg:hover:gap-x-3"],
                    [3.5, "lg:hover:gap-x-3.5"],
                    [4, "lg:hover:gap-x-4"],
                    [5, "lg:hover:gap-x-5"],
                    [6, "lg:hover:gap-x-6"],
                    [7, "lg:hover:gap-x-7"],
                    [8, "lg:hover:gap-x-8"],
                    [9, "lg:hover:gap-x-9"],
                    [10, "lg:hover:gap-x-10"],
                    [11, "lg:hover:gap-x-11"],
                    [12, "lg:hover:gap-x-12"],
                    [14, "lg:hover:gap-x-14"],
                    [16, "lg:hover:gap-x-16"],
                    [20, "lg:hover:gap-x-20"],
                    [24, "lg:hover:gap-x-24"],
                    [28, "lg:hover:gap-x-28"],
                    [32, "lg:hover:gap-x-32"],
                    [36, "lg:hover:gap-x-36"],
                    [40, "lg:hover:gap-x-40"],
                    [44, "lg:hover:gap-x-44"],
                    [48, "lg:hover:gap-x-48"],
                    [52, "lg:hover:gap-x-52"],
                    [56, "lg:hover:gap-x-56"],
                    [60, "lg:hover:gap-x-60"],
                    [64, "lg:hover:gap-x-64"],
                    [72, "lg:hover:gap-x-72"],
                    [80, "lg:hover:gap-x-80"],
                    [96, "lg:hover:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:hover:gap-y-0"],
                    ["px", "lg:hover:gap-y-px"],
                    [0.5, "lg:hover:gap-y-0.5"],
                    [1, "lg:hover:gap-y-1"],
                    [1.5, "lg:hover:gap-y-1.5"],
                    [2, "lg:hover:gap-y-2"],
                    [2.5, "lg:hover:gap-y-2.5"],
                    [3, "lg:hover:gap-y-3"],
                    [3.5, "lg:hover:gap-y-3.5"],
                    [4, "lg:hover:gap-y-4"],
                    [5, "lg:hover:gap-y-5"],
                    [6, "lg:hover:gap-y-6"],
                    [7, "lg:hover:gap-y-7"],
                    [8, "lg:hover:gap-y-8"],
                    [9, "lg:hover:gap-y-9"],
                    [10, "lg:hover:gap-y-10"],
                    [11, "lg:hover:gap-y-11"],
                    [12, "lg:hover:gap-y-12"],
                    [14, "lg:hover:gap-y-14"],
                    [16, "lg:hover:gap-y-16"],
                    [20, "lg:hover:gap-y-20"],
                    [24, "lg:hover:gap-y-24"],
                    [28, "lg:hover:gap-y-28"],
                    [32, "lg:hover:gap-y-32"],
                    [36, "lg:hover:gap-y-36"],
                    [40, "lg:hover:gap-y-40"],
                    [44, "lg:hover:gap-y-44"],
                    [48, "lg:hover:gap-y-48"],
                    [52, "lg:hover:gap-y-52"],
                    [56, "lg:hover:gap-y-56"],
                    [60, "lg:hover:gap-y-60"],
                    [64, "lg:hover:gap-y-64"],
                    [72, "lg:hover:gap-y-72"],
                    [80, "lg:hover:gap-y-80"],
                    [96, "lg:hover:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:hover:gap-x-0"],
                    ["px", "xl:hover:gap-x-px"],
                    [0.5, "xl:hover:gap-x-0.5"],
                    [1, "xl:hover:gap-x-1"],
                    [1.5, "xl:hover:gap-x-1.5"],
                    [2, "xl:hover:gap-x-2"],
                    [2.5, "xl:hover:gap-x-2.5"],
                    [3, "xl:hover:gap-x-3"],
                    [3.5, "xl:hover:gap-x-3.5"],
                    [4, "xl:hover:gap-x-4"],
                    [5, "xl:hover:gap-x-5"],
                    [6, "xl:hover:gap-x-6"],
                    [7, "xl:hover:gap-x-7"],
                    [8, "xl:hover:gap-x-8"],
                    [9, "xl:hover:gap-x-9"],
                    [10, "xl:hover:gap-x-10"],
                    [11, "xl:hover:gap-x-11"],
                    [12, "xl:hover:gap-x-12"],
                    [14, "xl:hover:gap-x-14"],
                    [16, "xl:hover:gap-x-16"],
                    [20, "xl:hover:gap-x-20"],
                    [24, "xl:hover:gap-x-24"],
                    [28, "xl:hover:gap-x-28"],
                    [32, "xl:hover:gap-x-32"],
                    [36, "xl:hover:gap-x-36"],
                    [40, "xl:hover:gap-x-40"],
                    [44, "xl:hover:gap-x-44"],
                    [48, "xl:hover:gap-x-48"],
                    [52, "xl:hover:gap-x-52"],
                    [56, "xl:hover:gap-x-56"],
                    [60, "xl:hover:gap-x-60"],
                    [64, "xl:hover:gap-x-64"],
                    [72, "xl:hover:gap-x-72"],
                    [80, "xl:hover:gap-x-80"],
                    [96, "xl:hover:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:hover:gap-y-0"],
                    ["px", "xl:hover:gap-y-px"],
                    [0.5, "xl:hover:gap-y-0.5"],
                    [1, "xl:hover:gap-y-1"],
                    [1.5, "xl:hover:gap-y-1.5"],
                    [2, "xl:hover:gap-y-2"],
                    [2.5, "xl:hover:gap-y-2.5"],
                    [3, "xl:hover:gap-y-3"],
                    [3.5, "xl:hover:gap-y-3.5"],
                    [4, "xl:hover:gap-y-4"],
                    [5, "xl:hover:gap-y-5"],
                    [6, "xl:hover:gap-y-6"],
                    [7, "xl:hover:gap-y-7"],
                    [8, "xl:hover:gap-y-8"],
                    [9, "xl:hover:gap-y-9"],
                    [10, "xl:hover:gap-y-10"],
                    [11, "xl:hover:gap-y-11"],
                    [12, "xl:hover:gap-y-12"],
                    [14, "xl:hover:gap-y-14"],
                    [16, "xl:hover:gap-y-16"],
                    [20, "xl:hover:gap-y-20"],
                    [24, "xl:hover:gap-y-24"],
                    [28, "xl:hover:gap-y-28"],
                    [32, "xl:hover:gap-y-32"],
                    [36, "xl:hover:gap-y-36"],
                    [40, "xl:hover:gap-y-40"],
                    [44, "xl:hover:gap-y-44"],
                    [48, "xl:hover:gap-y-48"],
                    [52, "xl:hover:gap-y-52"],
                    [56, "xl:hover:gap-y-56"],
                    [60, "xl:hover:gap-y-60"],
                    [64, "xl:hover:gap-y-64"],
                    [72, "xl:hover:gap-y-72"],
                    [80, "xl:hover:gap-y-80"],
                    [96, "xl:hover:gap-y-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:gap-x-0"],
                    ["px", "xs:gap-x-px"],
                    [0.5, "xs:gap-x-0.5"],
                    [1, "xs:gap-x-1"],
                    [1.5, "xs:gap-x-1.5"],
                    [2, "xs:gap-x-2"],
                    [2.5, "xs:gap-x-2.5"],
                    [3, "xs:gap-x-3"],
                    [3.5, "xs:gap-x-3.5"],
                    [4, "xs:gap-x-4"],
                    [5, "xs:gap-x-5"],
                    [6, "xs:gap-x-6"],
                    [7, "xs:gap-x-7"],
                    [8, "xs:gap-x-8"],
                    [9, "xs:gap-x-9"],
                    [10, "xs:gap-x-10"],
                    [11, "xs:gap-x-11"],
                    [12, "xs:gap-x-12"],
                    [14, "xs:gap-x-14"],
                    [16, "xs:gap-x-16"],
                    [20, "xs:gap-x-20"],
                    [24, "xs:gap-x-24"],
                    [28, "xs:gap-x-28"],
                    [32, "xs:gap-x-32"],
                    [36, "xs:gap-x-36"],
                    [40, "xs:gap-x-40"],
                    [44, "xs:gap-x-44"],
                    [48, "xs:gap-x-48"],
                    [52, "xs:gap-x-52"],
                    [56, "xs:gap-x-56"],
                    [60, "xs:gap-x-60"],
                    [64, "xs:gap-x-64"],
                    [72, "xs:gap-x-72"],
                    [80, "xs:gap-x-80"],
                    [96, "xs:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:gap-y-0"],
                    ["px", "xs:gap-y-px"],
                    [0.5, "xs:gap-y-0.5"],
                    [1, "xs:gap-y-1"],
                    [1.5, "xs:gap-y-1.5"],
                    [2, "xs:gap-y-2"],
                    [2.5, "xs:gap-y-2.5"],
                    [3, "xs:gap-y-3"],
                    [3.5, "xs:gap-y-3.5"],
                    [4, "xs:gap-y-4"],
                    [5, "xs:gap-y-5"],
                    [6, "xs:gap-y-6"],
                    [7, "xs:gap-y-7"],
                    [8, "xs:gap-y-8"],
                    [9, "xs:gap-y-9"],
                    [10, "xs:gap-y-10"],
                    [11, "xs:gap-y-11"],
                    [12, "xs:gap-y-12"],
                    [14, "xs:gap-y-14"],
                    [16, "xs:gap-y-16"],
                    [20, "xs:gap-y-20"],
                    [24, "xs:gap-y-24"],
                    [28, "xs:gap-y-28"],
                    [32, "xs:gap-y-32"],
                    [36, "xs:gap-y-36"],
                    [40, "xs:gap-y-40"],
                    [44, "xs:gap-y-44"],
                    [48, "xs:gap-y-48"],
                    [52, "xs:gap-y-52"],
                    [56, "xs:gap-y-56"],
                    [60, "xs:gap-y-60"],
                    [64, "xs:gap-y-64"],
                    [72, "xs:gap-y-72"],
                    [80, "xs:gap-y-80"],
                    [96, "xs:gap-y-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:gap-x-0"],
                    ["px", "sm:gap-x-px"],
                    [0.5, "sm:gap-x-0.5"],
                    [1, "sm:gap-x-1"],
                    [1.5, "sm:gap-x-1.5"],
                    [2, "sm:gap-x-2"],
                    [2.5, "sm:gap-x-2.5"],
                    [3, "sm:gap-x-3"],
                    [3.5, "sm:gap-x-3.5"],
                    [4, "sm:gap-x-4"],
                    [5, "sm:gap-x-5"],
                    [6, "sm:gap-x-6"],
                    [7, "sm:gap-x-7"],
                    [8, "sm:gap-x-8"],
                    [9, "sm:gap-x-9"],
                    [10, "sm:gap-x-10"],
                    [11, "sm:gap-x-11"],
                    [12, "sm:gap-x-12"],
                    [14, "sm:gap-x-14"],
                    [16, "sm:gap-x-16"],
                    [20, "sm:gap-x-20"],
                    [24, "sm:gap-x-24"],
                    [28, "sm:gap-x-28"],
                    [32, "sm:gap-x-32"],
                    [36, "sm:gap-x-36"],
                    [40, "sm:gap-x-40"],
                    [44, "sm:gap-x-44"],
                    [48, "sm:gap-x-48"],
                    [52, "sm:gap-x-52"],
                    [56, "sm:gap-x-56"],
                    [60, "sm:gap-x-60"],
                    [64, "sm:gap-x-64"],
                    [72, "sm:gap-x-72"],
                    [80, "sm:gap-x-80"],
                    [96, "sm:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:gap-y-0"],
                    ["px", "sm:gap-y-px"],
                    [0.5, "sm:gap-y-0.5"],
                    [1, "sm:gap-y-1"],
                    [1.5, "sm:gap-y-1.5"],
                    [2, "sm:gap-y-2"],
                    [2.5, "sm:gap-y-2.5"],
                    [3, "sm:gap-y-3"],
                    [3.5, "sm:gap-y-3.5"],
                    [4, "sm:gap-y-4"],
                    [5, "sm:gap-y-5"],
                    [6, "sm:gap-y-6"],
                    [7, "sm:gap-y-7"],
                    [8, "sm:gap-y-8"],
                    [9, "sm:gap-y-9"],
                    [10, "sm:gap-y-10"],
                    [11, "sm:gap-y-11"],
                    [12, "sm:gap-y-12"],
                    [14, "sm:gap-y-14"],
                    [16, "sm:gap-y-16"],
                    [20, "sm:gap-y-20"],
                    [24, "sm:gap-y-24"],
                    [28, "sm:gap-y-28"],
                    [32, "sm:gap-y-32"],
                    [36, "sm:gap-y-36"],
                    [40, "sm:gap-y-40"],
                    [44, "sm:gap-y-44"],
                    [48, "sm:gap-y-48"],
                    [52, "sm:gap-y-52"],
                    [56, "sm:gap-y-56"],
                    [60, "sm:gap-y-60"],
                    [64, "sm:gap-y-64"],
                    [72, "sm:gap-y-72"],
                    [80, "sm:gap-y-80"],
                    [96, "sm:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:gap-x-0"],
                    ["px", "md:gap-x-px"],
                    [0.5, "md:gap-x-0.5"],
                    [1, "md:gap-x-1"],
                    [1.5, "md:gap-x-1.5"],
                    [2, "md:gap-x-2"],
                    [2.5, "md:gap-x-2.5"],
                    [3, "md:gap-x-3"],
                    [3.5, "md:gap-x-3.5"],
                    [4, "md:gap-x-4"],
                    [5, "md:gap-x-5"],
                    [6, "md:gap-x-6"],
                    [7, "md:gap-x-7"],
                    [8, "md:gap-x-8"],
                    [9, "md:gap-x-9"],
                    [10, "md:gap-x-10"],
                    [11, "md:gap-x-11"],
                    [12, "md:gap-x-12"],
                    [14, "md:gap-x-14"],
                    [16, "md:gap-x-16"],
                    [20, "md:gap-x-20"],
                    [24, "md:gap-x-24"],
                    [28, "md:gap-x-28"],
                    [32, "md:gap-x-32"],
                    [36, "md:gap-x-36"],
                    [40, "md:gap-x-40"],
                    [44, "md:gap-x-44"],
                    [48, "md:gap-x-48"],
                    [52, "md:gap-x-52"],
                    [56, "md:gap-x-56"],
                    [60, "md:gap-x-60"],
                    [64, "md:gap-x-64"],
                    [72, "md:gap-x-72"],
                    [80, "md:gap-x-80"],
                    [96, "md:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:gap-y-0"],
                    ["px", "md:gap-y-px"],
                    [0.5, "md:gap-y-0.5"],
                    [1, "md:gap-y-1"],
                    [1.5, "md:gap-y-1.5"],
                    [2, "md:gap-y-2"],
                    [2.5, "md:gap-y-2.5"],
                    [3, "md:gap-y-3"],
                    [3.5, "md:gap-y-3.5"],
                    [4, "md:gap-y-4"],
                    [5, "md:gap-y-5"],
                    [6, "md:gap-y-6"],
                    [7, "md:gap-y-7"],
                    [8, "md:gap-y-8"],
                    [9, "md:gap-y-9"],
                    [10, "md:gap-y-10"],
                    [11, "md:gap-y-11"],
                    [12, "md:gap-y-12"],
                    [14, "md:gap-y-14"],
                    [16, "md:gap-y-16"],
                    [20, "md:gap-y-20"],
                    [24, "md:gap-y-24"],
                    [28, "md:gap-y-28"],
                    [32, "md:gap-y-32"],
                    [36, "md:gap-y-36"],
                    [40, "md:gap-y-40"],
                    [44, "md:gap-y-44"],
                    [48, "md:gap-y-48"],
                    [52, "md:gap-y-52"],
                    [56, "md:gap-y-56"],
                    [60, "md:gap-y-60"],
                    [64, "md:gap-y-64"],
                    [72, "md:gap-y-72"],
                    [80, "md:gap-y-80"],
                    [96, "md:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:gap-x-0"],
                    ["px", "lg:gap-x-px"],
                    [0.5, "lg:gap-x-0.5"],
                    [1, "lg:gap-x-1"],
                    [1.5, "lg:gap-x-1.5"],
                    [2, "lg:gap-x-2"],
                    [2.5, "lg:gap-x-2.5"],
                    [3, "lg:gap-x-3"],
                    [3.5, "lg:gap-x-3.5"],
                    [4, "lg:gap-x-4"],
                    [5, "lg:gap-x-5"],
                    [6, "lg:gap-x-6"],
                    [7, "lg:gap-x-7"],
                    [8, "lg:gap-x-8"],
                    [9, "lg:gap-x-9"],
                    [10, "lg:gap-x-10"],
                    [11, "lg:gap-x-11"],
                    [12, "lg:gap-x-12"],
                    [14, "lg:gap-x-14"],
                    [16, "lg:gap-x-16"],
                    [20, "lg:gap-x-20"],
                    [24, "lg:gap-x-24"],
                    [28, "lg:gap-x-28"],
                    [32, "lg:gap-x-32"],
                    [36, "lg:gap-x-36"],
                    [40, "lg:gap-x-40"],
                    [44, "lg:gap-x-44"],
                    [48, "lg:gap-x-48"],
                    [52, "lg:gap-x-52"],
                    [56, "lg:gap-x-56"],
                    [60, "lg:gap-x-60"],
                    [64, "lg:gap-x-64"],
                    [72, "lg:gap-x-72"],
                    [80, "lg:gap-x-80"],
                    [96, "lg:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:gap-y-0"],
                    ["px", "lg:gap-y-px"],
                    [0.5, "lg:gap-y-0.5"],
                    [1, "lg:gap-y-1"],
                    [1.5, "lg:gap-y-1.5"],
                    [2, "lg:gap-y-2"],
                    [2.5, "lg:gap-y-2.5"],
                    [3, "lg:gap-y-3"],
                    [3.5, "lg:gap-y-3.5"],
                    [4, "lg:gap-y-4"],
                    [5, "lg:gap-y-5"],
                    [6, "lg:gap-y-6"],
                    [7, "lg:gap-y-7"],
                    [8, "lg:gap-y-8"],
                    [9, "lg:gap-y-9"],
                    [10, "lg:gap-y-10"],
                    [11, "lg:gap-y-11"],
                    [12, "lg:gap-y-12"],
                    [14, "lg:gap-y-14"],
                    [16, "lg:gap-y-16"],
                    [20, "lg:gap-y-20"],
                    [24, "lg:gap-y-24"],
                    [28, "lg:gap-y-28"],
                    [32, "lg:gap-y-32"],
                    [36, "lg:gap-y-36"],
                    [40, "lg:gap-y-40"],
                    [44, "lg:gap-y-44"],
                    [48, "lg:gap-y-48"],
                    [52, "lg:gap-y-52"],
                    [56, "lg:gap-y-56"],
                    [60, "lg:gap-y-60"],
                    [64, "lg:gap-y-64"],
                    [72, "lg:gap-y-72"],
                    [80, "lg:gap-y-80"],
                    [96, "lg:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:gap-x-0"],
                    ["px", "xl:gap-x-px"],
                    [0.5, "xl:gap-x-0.5"],
                    [1, "xl:gap-x-1"],
                    [1.5, "xl:gap-x-1.5"],
                    [2, "xl:gap-x-2"],
                    [2.5, "xl:gap-x-2.5"],
                    [3, "xl:gap-x-3"],
                    [3.5, "xl:gap-x-3.5"],
                    [4, "xl:gap-x-4"],
                    [5, "xl:gap-x-5"],
                    [6, "xl:gap-x-6"],
                    [7, "xl:gap-x-7"],
                    [8, "xl:gap-x-8"],
                    [9, "xl:gap-x-9"],
                    [10, "xl:gap-x-10"],
                    [11, "xl:gap-x-11"],
                    [12, "xl:gap-x-12"],
                    [14, "xl:gap-x-14"],
                    [16, "xl:gap-x-16"],
                    [20, "xl:gap-x-20"],
                    [24, "xl:gap-x-24"],
                    [28, "xl:gap-x-28"],
                    [32, "xl:gap-x-32"],
                    [36, "xl:gap-x-36"],
                    [40, "xl:gap-x-40"],
                    [44, "xl:gap-x-44"],
                    [48, "xl:gap-x-48"],
                    [52, "xl:gap-x-52"],
                    [56, "xl:gap-x-56"],
                    [60, "xl:gap-x-60"],
                    [64, "xl:gap-x-64"],
                    [72, "xl:gap-x-72"],
                    [80, "xl:gap-x-80"],
                    [96, "xl:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:gap-y-0"],
                    ["px", "xl:gap-y-px"],
                    [0.5, "xl:gap-y-0.5"],
                    [1, "xl:gap-y-1"],
                    [1.5, "xl:gap-y-1.5"],
                    [2, "xl:gap-y-2"],
                    [2.5, "xl:gap-y-2.5"],
                    [3, "xl:gap-y-3"],
                    [3.5, "xl:gap-y-3.5"],
                    [4, "xl:gap-y-4"],
                    [5, "xl:gap-y-5"],
                    [6, "xl:gap-y-6"],
                    [7, "xl:gap-y-7"],
                    [8, "xl:gap-y-8"],
                    [9, "xl:gap-y-9"],
                    [10, "xl:gap-y-10"],
                    [11, "xl:gap-y-11"],
                    [12, "xl:gap-y-12"],
                    [14, "xl:gap-y-14"],
                    [16, "xl:gap-y-16"],
                    [20, "xl:gap-y-20"],
                    [24, "xl:gap-y-24"],
                    [28, "xl:gap-y-28"],
                    [32, "xl:gap-y-32"],
                    [36, "xl:gap-y-36"],
                    [40, "xl:gap-y-40"],
                    [44, "xl:gap-y-44"],
                    [48, "xl:gap-y-48"],
                    [52, "xl:gap-y-52"],
                    [56, "xl:gap-y-56"],
                    [60, "xl:gap-y-60"],
                    [64, "xl:gap-y-64"],
                    [72, "xl:gap-y-72"],
                    [80, "xl:gap-y-80"],
                    [96, "xl:gap-y-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xs:open:gap-x-0"],
                    ["px", "xs:open:gap-x-px"],
                    [0.5, "xs:open:gap-x-0.5"],
                    [1, "xs:open:gap-x-1"],
                    [1.5, "xs:open:gap-x-1.5"],
                    [2, "xs:open:gap-x-2"],
                    [2.5, "xs:open:gap-x-2.5"],
                    [3, "xs:open:gap-x-3"],
                    [3.5, "xs:open:gap-x-3.5"],
                    [4, "xs:open:gap-x-4"],
                    [5, "xs:open:gap-x-5"],
                    [6, "xs:open:gap-x-6"],
                    [7, "xs:open:gap-x-7"],
                    [8, "xs:open:gap-x-8"],
                    [9, "xs:open:gap-x-9"],
                    [10, "xs:open:gap-x-10"],
                    [11, "xs:open:gap-x-11"],
                    [12, "xs:open:gap-x-12"],
                    [14, "xs:open:gap-x-14"],
                    [16, "xs:open:gap-x-16"],
                    [20, "xs:open:gap-x-20"],
                    [24, "xs:open:gap-x-24"],
                    [28, "xs:open:gap-x-28"],
                    [32, "xs:open:gap-x-32"],
                    [36, "xs:open:gap-x-36"],
                    [40, "xs:open:gap-x-40"],
                    [44, "xs:open:gap-x-44"],
                    [48, "xs:open:gap-x-48"],
                    [52, "xs:open:gap-x-52"],
                    [56, "xs:open:gap-x-56"],
                    [60, "xs:open:gap-x-60"],
                    [64, "xs:open:gap-x-64"],
                    [72, "xs:open:gap-x-72"],
                    [80, "xs:open:gap-x-80"],
                    [96, "xs:open:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xs:open:gap-y-0"],
                    ["px", "xs:open:gap-y-px"],
                    [0.5, "xs:open:gap-y-0.5"],
                    [1, "xs:open:gap-y-1"],
                    [1.5, "xs:open:gap-y-1.5"],
                    [2, "xs:open:gap-y-2"],
                    [2.5, "xs:open:gap-y-2.5"],
                    [3, "xs:open:gap-y-3"],
                    [3.5, "xs:open:gap-y-3.5"],
                    [4, "xs:open:gap-y-4"],
                    [5, "xs:open:gap-y-5"],
                    [6, "xs:open:gap-y-6"],
                    [7, "xs:open:gap-y-7"],
                    [8, "xs:open:gap-y-8"],
                    [9, "xs:open:gap-y-9"],
                    [10, "xs:open:gap-y-10"],
                    [11, "xs:open:gap-y-11"],
                    [12, "xs:open:gap-y-12"],
                    [14, "xs:open:gap-y-14"],
                    [16, "xs:open:gap-y-16"],
                    [20, "xs:open:gap-y-20"],
                    [24, "xs:open:gap-y-24"],
                    [28, "xs:open:gap-y-28"],
                    [32, "xs:open:gap-y-32"],
                    [36, "xs:open:gap-y-36"],
                    [40, "xs:open:gap-y-40"],
                    [44, "xs:open:gap-y-44"],
                    [48, "xs:open:gap-y-48"],
                    [52, "xs:open:gap-y-52"],
                    [56, "xs:open:gap-y-56"],
                    [60, "xs:open:gap-y-60"],
                    [64, "xs:open:gap-y-64"],
                    [72, "xs:open:gap-y-72"],
                    [80, "xs:open:gap-y-80"],
                    [96, "xs:open:gap-y-96"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "sm:open:gap-x-0"],
                    ["px", "sm:open:gap-x-px"],
                    [0.5, "sm:open:gap-x-0.5"],
                    [1, "sm:open:gap-x-1"],
                    [1.5, "sm:open:gap-x-1.5"],
                    [2, "sm:open:gap-x-2"],
                    [2.5, "sm:open:gap-x-2.5"],
                    [3, "sm:open:gap-x-3"],
                    [3.5, "sm:open:gap-x-3.5"],
                    [4, "sm:open:gap-x-4"],
                    [5, "sm:open:gap-x-5"],
                    [6, "sm:open:gap-x-6"],
                    [7, "sm:open:gap-x-7"],
                    [8, "sm:open:gap-x-8"],
                    [9, "sm:open:gap-x-9"],
                    [10, "sm:open:gap-x-10"],
                    [11, "sm:open:gap-x-11"],
                    [12, "sm:open:gap-x-12"],
                    [14, "sm:open:gap-x-14"],
                    [16, "sm:open:gap-x-16"],
                    [20, "sm:open:gap-x-20"],
                    [24, "sm:open:gap-x-24"],
                    [28, "sm:open:gap-x-28"],
                    [32, "sm:open:gap-x-32"],
                    [36, "sm:open:gap-x-36"],
                    [40, "sm:open:gap-x-40"],
                    [44, "sm:open:gap-x-44"],
                    [48, "sm:open:gap-x-48"],
                    [52, "sm:open:gap-x-52"],
                    [56, "sm:open:gap-x-56"],
                    [60, "sm:open:gap-x-60"],
                    [64, "sm:open:gap-x-64"],
                    [72, "sm:open:gap-x-72"],
                    [80, "sm:open:gap-x-80"],
                    [96, "sm:open:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "sm:open:gap-y-0"],
                    ["px", "sm:open:gap-y-px"],
                    [0.5, "sm:open:gap-y-0.5"],
                    [1, "sm:open:gap-y-1"],
                    [1.5, "sm:open:gap-y-1.5"],
                    [2, "sm:open:gap-y-2"],
                    [2.5, "sm:open:gap-y-2.5"],
                    [3, "sm:open:gap-y-3"],
                    [3.5, "sm:open:gap-y-3.5"],
                    [4, "sm:open:gap-y-4"],
                    [5, "sm:open:gap-y-5"],
                    [6, "sm:open:gap-y-6"],
                    [7, "sm:open:gap-y-7"],
                    [8, "sm:open:gap-y-8"],
                    [9, "sm:open:gap-y-9"],
                    [10, "sm:open:gap-y-10"],
                    [11, "sm:open:gap-y-11"],
                    [12, "sm:open:gap-y-12"],
                    [14, "sm:open:gap-y-14"],
                    [16, "sm:open:gap-y-16"],
                    [20, "sm:open:gap-y-20"],
                    [24, "sm:open:gap-y-24"],
                    [28, "sm:open:gap-y-28"],
                    [32, "sm:open:gap-y-32"],
                    [36, "sm:open:gap-y-36"],
                    [40, "sm:open:gap-y-40"],
                    [44, "sm:open:gap-y-44"],
                    [48, "sm:open:gap-y-48"],
                    [52, "sm:open:gap-y-52"],
                    [56, "sm:open:gap-y-56"],
                    [60, "sm:open:gap-y-60"],
                    [64, "sm:open:gap-y-64"],
                    [72, "sm:open:gap-y-72"],
                    [80, "sm:open:gap-y-80"],
                    [96, "sm:open:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "md:open:gap-x-0"],
                    ["px", "md:open:gap-x-px"],
                    [0.5, "md:open:gap-x-0.5"],
                    [1, "md:open:gap-x-1"],
                    [1.5, "md:open:gap-x-1.5"],
                    [2, "md:open:gap-x-2"],
                    [2.5, "md:open:gap-x-2.5"],
                    [3, "md:open:gap-x-3"],
                    [3.5, "md:open:gap-x-3.5"],
                    [4, "md:open:gap-x-4"],
                    [5, "md:open:gap-x-5"],
                    [6, "md:open:gap-x-6"],
                    [7, "md:open:gap-x-7"],
                    [8, "md:open:gap-x-8"],
                    [9, "md:open:gap-x-9"],
                    [10, "md:open:gap-x-10"],
                    [11, "md:open:gap-x-11"],
                    [12, "md:open:gap-x-12"],
                    [14, "md:open:gap-x-14"],
                    [16, "md:open:gap-x-16"],
                    [20, "md:open:gap-x-20"],
                    [24, "md:open:gap-x-24"],
                    [28, "md:open:gap-x-28"],
                    [32, "md:open:gap-x-32"],
                    [36, "md:open:gap-x-36"],
                    [40, "md:open:gap-x-40"],
                    [44, "md:open:gap-x-44"],
                    [48, "md:open:gap-x-48"],
                    [52, "md:open:gap-x-52"],
                    [56, "md:open:gap-x-56"],
                    [60, "md:open:gap-x-60"],
                    [64, "md:open:gap-x-64"],
                    [72, "md:open:gap-x-72"],
                    [80, "md:open:gap-x-80"],
                    [96, "md:open:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "md:open:gap-y-0"],
                    ["px", "md:open:gap-y-px"],
                    [0.5, "md:open:gap-y-0.5"],
                    [1, "md:open:gap-y-1"],
                    [1.5, "md:open:gap-y-1.5"],
                    [2, "md:open:gap-y-2"],
                    [2.5, "md:open:gap-y-2.5"],
                    [3, "md:open:gap-y-3"],
                    [3.5, "md:open:gap-y-3.5"],
                    [4, "md:open:gap-y-4"],
                    [5, "md:open:gap-y-5"],
                    [6, "md:open:gap-y-6"],
                    [7, "md:open:gap-y-7"],
                    [8, "md:open:gap-y-8"],
                    [9, "md:open:gap-y-9"],
                    [10, "md:open:gap-y-10"],
                    [11, "md:open:gap-y-11"],
                    [12, "md:open:gap-y-12"],
                    [14, "md:open:gap-y-14"],
                    [16, "md:open:gap-y-16"],
                    [20, "md:open:gap-y-20"],
                    [24, "md:open:gap-y-24"],
                    [28, "md:open:gap-y-28"],
                    [32, "md:open:gap-y-32"],
                    [36, "md:open:gap-y-36"],
                    [40, "md:open:gap-y-40"],
                    [44, "md:open:gap-y-44"],
                    [48, "md:open:gap-y-48"],
                    [52, "md:open:gap-y-52"],
                    [56, "md:open:gap-y-56"],
                    [60, "md:open:gap-y-60"],
                    [64, "md:open:gap-y-64"],
                    [72, "md:open:gap-y-72"],
                    [80, "md:open:gap-y-80"],
                    [96, "md:open:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "lg:open:gap-x-0"],
                    ["px", "lg:open:gap-x-px"],
                    [0.5, "lg:open:gap-x-0.5"],
                    [1, "lg:open:gap-x-1"],
                    [1.5, "lg:open:gap-x-1.5"],
                    [2, "lg:open:gap-x-2"],
                    [2.5, "lg:open:gap-x-2.5"],
                    [3, "lg:open:gap-x-3"],
                    [3.5, "lg:open:gap-x-3.5"],
                    [4, "lg:open:gap-x-4"],
                    [5, "lg:open:gap-x-5"],
                    [6, "lg:open:gap-x-6"],
                    [7, "lg:open:gap-x-7"],
                    [8, "lg:open:gap-x-8"],
                    [9, "lg:open:gap-x-9"],
                    [10, "lg:open:gap-x-10"],
                    [11, "lg:open:gap-x-11"],
                    [12, "lg:open:gap-x-12"],
                    [14, "lg:open:gap-x-14"],
                    [16, "lg:open:gap-x-16"],
                    [20, "lg:open:gap-x-20"],
                    [24, "lg:open:gap-x-24"],
                    [28, "lg:open:gap-x-28"],
                    [32, "lg:open:gap-x-32"],
                    [36, "lg:open:gap-x-36"],
                    [40, "lg:open:gap-x-40"],
                    [44, "lg:open:gap-x-44"],
                    [48, "lg:open:gap-x-48"],
                    [52, "lg:open:gap-x-52"],
                    [56, "lg:open:gap-x-56"],
                    [60, "lg:open:gap-x-60"],
                    [64, "lg:open:gap-x-64"],
                    [72, "lg:open:gap-x-72"],
                    [80, "lg:open:gap-x-80"],
                    [96, "lg:open:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "lg:open:gap-y-0"],
                    ["px", "lg:open:gap-y-px"],
                    [0.5, "lg:open:gap-y-0.5"],
                    [1, "lg:open:gap-y-1"],
                    [1.5, "lg:open:gap-y-1.5"],
                    [2, "lg:open:gap-y-2"],
                    [2.5, "lg:open:gap-y-2.5"],
                    [3, "lg:open:gap-y-3"],
                    [3.5, "lg:open:gap-y-3.5"],
                    [4, "lg:open:gap-y-4"],
                    [5, "lg:open:gap-y-5"],
                    [6, "lg:open:gap-y-6"],
                    [7, "lg:open:gap-y-7"],
                    [8, "lg:open:gap-y-8"],
                    [9, "lg:open:gap-y-9"],
                    [10, "lg:open:gap-y-10"],
                    [11, "lg:open:gap-y-11"],
                    [12, "lg:open:gap-y-12"],
                    [14, "lg:open:gap-y-14"],
                    [16, "lg:open:gap-y-16"],
                    [20, "lg:open:gap-y-20"],
                    [24, "lg:open:gap-y-24"],
                    [28, "lg:open:gap-y-28"],
                    [32, "lg:open:gap-y-32"],
                    [36, "lg:open:gap-y-36"],
                    [40, "lg:open:gap-y-40"],
                    [44, "lg:open:gap-y-44"],
                    [48, "lg:open:gap-y-48"],
                    [52, "lg:open:gap-y-52"],
                    [56, "lg:open:gap-y-56"],
                    [60, "lg:open:gap-y-60"],
                    [64, "lg:open:gap-y-64"],
                    [72, "lg:open:gap-y-72"],
                    [80, "lg:open:gap-y-80"],
                    [96, "lg:open:gap-y-96"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<FlexSpacing, string>>([
                [
                  "x",
                  new Map<FlexSpacing, string>([
                    [0, "xl:open:gap-x-0"],
                    ["px", "xl:open:gap-x-px"],
                    [0.5, "xl:open:gap-x-0.5"],
                    [1, "xl:open:gap-x-1"],
                    [1.5, "xl:open:gap-x-1.5"],
                    [2, "xl:open:gap-x-2"],
                    [2.5, "xl:open:gap-x-2.5"],
                    [3, "xl:open:gap-x-3"],
                    [3.5, "xl:open:gap-x-3.5"],
                    [4, "xl:open:gap-x-4"],
                    [5, "xl:open:gap-x-5"],
                    [6, "xl:open:gap-x-6"],
                    [7, "xl:open:gap-x-7"],
                    [8, "xl:open:gap-x-8"],
                    [9, "xl:open:gap-x-9"],
                    [10, "xl:open:gap-x-10"],
                    [11, "xl:open:gap-x-11"],
                    [12, "xl:open:gap-x-12"],
                    [14, "xl:open:gap-x-14"],
                    [16, "xl:open:gap-x-16"],
                    [20, "xl:open:gap-x-20"],
                    [24, "xl:open:gap-x-24"],
                    [28, "xl:open:gap-x-28"],
                    [32, "xl:open:gap-x-32"],
                    [36, "xl:open:gap-x-36"],
                    [40, "xl:open:gap-x-40"],
                    [44, "xl:open:gap-x-44"],
                    [48, "xl:open:gap-x-48"],
                    [52, "xl:open:gap-x-52"],
                    [56, "xl:open:gap-x-56"],
                    [60, "xl:open:gap-x-60"],
                    [64, "xl:open:gap-x-64"],
                    [72, "xl:open:gap-x-72"],
                    [80, "xl:open:gap-x-80"],
                    [96, "xl:open:gap-x-96"],
                  ]),
                ],
                [
                  "y",
                  new Map<FlexSpacing, string>([
                    [0, "xl:open:gap-y-0"],
                    ["px", "xl:open:gap-y-px"],
                    [0.5, "xl:open:gap-y-0.5"],
                    [1, "xl:open:gap-y-1"],
                    [1.5, "xl:open:gap-y-1.5"],
                    [2, "xl:open:gap-y-2"],
                    [2.5, "xl:open:gap-y-2.5"],
                    [3, "xl:open:gap-y-3"],
                    [3.5, "xl:open:gap-y-3.5"],
                    [4, "xl:open:gap-y-4"],
                    [5, "xl:open:gap-y-5"],
                    [6, "xl:open:gap-y-6"],
                    [7, "xl:open:gap-y-7"],
                    [8, "xl:open:gap-y-8"],
                    [9, "xl:open:gap-y-9"],
                    [10, "xl:open:gap-y-10"],
                    [11, "xl:open:gap-y-11"],
                    [12, "xl:open:gap-y-12"],
                    [14, "xl:open:gap-y-14"],
                    [16, "xl:open:gap-y-16"],
                    [20, "xl:open:gap-y-20"],
                    [24, "xl:open:gap-y-24"],
                    [28, "xl:open:gap-y-28"],
                    [32, "xl:open:gap-y-32"],
                    [36, "xl:open:gap-y-36"],
                    [40, "xl:open:gap-y-40"],
                    [44, "xl:open:gap-y-44"],
                    [48, "xl:open:gap-y-48"],
                    [52, "xl:open:gap-y-52"],
                    [56, "xl:open:gap-y-56"],
                    [60, "xl:open:gap-y-60"],
                    [64, "xl:open:gap-y-64"],
                    [72, "xl:open:gap-y-72"],
                    [80, "xl:open:gap-y-80"],
                    [96, "xl:open:gap-y-96"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
