import { AxisMapping, Breakpoints, CSSSelector, FlexSpacing } from "../../types";
import { GapAxisInsideBreakpoints } from "./GapAxisIsideBreakpoints";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";
import { Axleable } from "../../Entities/Axleable";

export class GapBreakpoints extends Axleable<
  Map<Breakpoints, Map<FlexSpacing, string>>,
  Map<Breakpoints, Map<AxisMapping, Map<FlexSpacing, string>>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexSpacing, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new GapClassesMapping();
    return new GapBreakpoints(classesMapping, selector);
  }

  public axis() {
    return GapAxisInsideBreakpoints.create(this.cssSelector);
  }

  public write(breakpoint: Breakpoints, spacing: FlexSpacing) {
    return this.getClassName(breakpoint, spacing);
  }
}

class GapClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexSpacing, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexSpacing, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexSpacing, string>>(
      "xs",
      new Map<FlexSpacing, string>([
        [0, "xs:gap-0"],
        ["px", "xs:gap-px"],
        [0.5, "xs:gap-0.5"],
        [1, "xs:gap-1"],
        [1.5, "xs:gap-1.5"],
        [2, "xs:gap-2"],
        [2.5, "xs:gap-2.5"],
        [3, "xs:gap-3"],
        [3.5, "xs:gap-3.5"],
        [4, "xs:gap-4"],
        [5, "xs:gap-5"],
        [6, "xs:gap-6"],
        [7, "xs:gap-7"],
        [8, "xs:gap-8"],
        [9, "xs:gap-9"],
        [10, "xs:gap-10"],
        [11, "xs:gap-11"],
        [12, "xs:gap-12"],
        [14, "xs:gap-14"],
        [16, "xs:gap-16"],
        [20, "xs:gap-20"],
        [24, "xs:gap-24"],
        [28, "xs:gap-28"],
        [32, "xs:gap-32"],
        [36, "xs:gap-36"],
        [40, "xs:gap-40"],
        [44, "xs:gap-44"],
        [48, "xs:gap-48"],
        [52, "xs:gap-52"],
        [56, "xs:gap-56"],
        [60, "xs:gap-60"],
        [64, "xs:gap-64"],
        [72, "xs:gap-72"],
        [80, "xs:gap-80"],
        [96, "xs:gap-96"],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexSpacing, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:active:gap-0"],
                ["px", "xs:active:gap-px"],
                [0.5, "xs:active:gap-0.5"],
                [1, "xs:active:gap-1"],
                [1.5, "xs:active:gap-1.5"],
                [2, "xs:active:gap-2"],
                [2.5, "xs:active:gap-2.5"],
                [3, "xs:active:gap-3"],
                [3.5, "xs:active:gap-3.5"],
                [4, "xs:active:gap-4"],
                [5, "xs:active:gap-5"],
                [6, "xs:active:gap-6"],
                [7, "xs:active:gap-7"],
                [8, "xs:active:gap-8"],
                [9, "xs:active:gap-9"],
                [10, "xs:active:gap-10"],
                [11, "xs:active:gap-11"],
                [12, "xs:active:gap-12"],
                [14, "xs:active:gap-14"],
                [16, "xs:active:gap-16"],
                [20, "xs:active:gap-20"],
                [24, "xs:active:gap-24"],
                [28, "xs:active:gap-28"],
                [32, "xs:active:gap-32"],
                [36, "xs:active:gap-36"],
                [40, "xs:active:gap-40"],
                [44, "xs:active:gap-44"],
                [48, "xs:active:gap-48"],
                [52, "xs:active:gap-52"],
                [56, "xs:active:gap-56"],
                [60, "xs:active:gap-60"],
                [64, "xs:active:gap-64"],
                [72, "xs:active:gap-72"],
                [80, "xs:active:gap-80"],
                [96, "xs:active:gap-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:active:gap-0"],
                ["px", "sm:active:gap-px"],
                [0.5, "sm:active:gap-0.5"],
                [1, "sm:active:gap-1"],
                [1.5, "sm:active:gap-1.5"],
                [2, "sm:active:gap-2"],
                [2.5, "sm:active:gap-2.5"],
                [3, "sm:active:gap-3"],
                [3.5, "sm:active:gap-3.5"],
                [4, "sm:active:gap-4"],
                [5, "sm:active:gap-5"],
                [6, "sm:active:gap-6"],
                [7, "sm:active:gap-7"],
                [8, "sm:active:gap-8"],
                [9, "sm:active:gap-9"],
                [10, "sm:active:gap-10"],
                [11, "sm:active:gap-11"],
                [12, "sm:active:gap-12"],
                [14, "sm:active:gap-14"],
                [16, "sm:active:gap-16"],
                [20, "sm:active:gap-20"],
                [24, "sm:active:gap-24"],
                [28, "sm:active:gap-28"],
                [32, "sm:active:gap-32"],
                [36, "sm:active:gap-36"],
                [40, "sm:active:gap-40"],
                [44, "sm:active:gap-44"],
                [48, "sm:active:gap-48"],
                [52, "sm:active:gap-52"],
                [56, "sm:active:gap-56"],
                [60, "sm:active:gap-60"],
                [64, "sm:active:gap-64"],
                [72, "sm:active:gap-72"],
                [80, "sm:active:gap-80"],
                [96, "sm:active:gap-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:active:gap-0"],
                ["px", "md:active:gap-px"],
                [0.5, "md:active:gap-0.5"],
                [1, "md:active:gap-1"],
                [1.5, "md:active:gap-1.5"],
                [2, "md:active:gap-2"],
                [2.5, "md:active:gap-2.5"],
                [3, "md:active:gap-3"],
                [3.5, "md:active:gap-3.5"],
                [4, "md:active:gap-4"],
                [5, "md:active:gap-5"],
                [6, "md:active:gap-6"],
                [7, "md:active:gap-7"],
                [8, "md:active:gap-8"],
                [9, "md:active:gap-9"],
                [10, "md:active:gap-10"],
                [11, "md:active:gap-11"],
                [12, "md:active:gap-12"],
                [14, "md:active:gap-14"],
                [16, "md:active:gap-16"],
                [20, "md:active:gap-20"],
                [24, "md:active:gap-24"],
                [28, "md:active:gap-28"],
                [32, "md:active:gap-32"],
                [36, "md:active:gap-36"],
                [40, "md:active:gap-40"],
                [44, "md:active:gap-44"],
                [48, "md:active:gap-48"],
                [52, "md:active:gap-52"],
                [56, "md:active:gap-56"],
                [60, "md:active:gap-60"],
                [64, "md:active:gap-64"],
                [72, "md:active:gap-72"],
                [80, "md:active:gap-80"],
                [96, "md:active:gap-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:active:gap-0"],
                ["px", "lg:active:gap-px"],
                [0.5, "lg:active:gap-0.5"],
                [1, "lg:active:gap-1"],
                [1.5, "lg:active:gap-1.5"],
                [2, "lg:active:gap-2"],
                [2.5, "lg:active:gap-2.5"],
                [3, "lg:active:gap-3"],
                [3.5, "lg:active:gap-3.5"],
                [4, "lg:active:gap-4"],
                [5, "lg:active:gap-5"],
                [6, "lg:active:gap-6"],
                [7, "lg:active:gap-7"],
                [8, "lg:active:gap-8"],
                [9, "lg:active:gap-9"],
                [10, "lg:active:gap-10"],
                [11, "lg:active:gap-11"],
                [12, "lg:active:gap-12"],
                [14, "lg:active:gap-14"],
                [16, "lg:active:gap-16"],
                [20, "lg:active:gap-20"],
                [24, "lg:active:gap-24"],
                [28, "lg:active:gap-28"],
                [32, "lg:active:gap-32"],
                [36, "lg:active:gap-36"],
                [40, "lg:active:gap-40"],
                [44, "lg:active:gap-44"],
                [48, "lg:active:gap-48"],
                [52, "lg:active:gap-52"],
                [56, "lg:active:gap-56"],
                [60, "lg:active:gap-60"],
                [64, "lg:active:gap-64"],
                [72, "lg:active:gap-72"],
                [80, "lg:active:gap-80"],
                [96, "lg:active:gap-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:active:gap-0"],
                ["px", "xl:active:gap-px"],
                [0.5, "xl:active:gap-0.5"],
                [1, "xl:active:gap-1"],
                [1.5, "xl:active:gap-1.5"],
                [2, "xl:active:gap-2"],
                [2.5, "xl:active:gap-2.5"],
                [3, "xl:active:gap-3"],
                [3.5, "xl:active:gap-3.5"],
                [4, "xl:active:gap-4"],
                [5, "xl:active:gap-5"],
                [6, "xl:active:gap-6"],
                [7, "xl:active:gap-7"],
                [8, "xl:active:gap-8"],
                [9, "xl:active:gap-9"],
                [10, "xl:active:gap-10"],
                [11, "xl:active:gap-11"],
                [12, "xl:active:gap-12"],
                [14, "xl:active:gap-14"],
                [16, "xl:active:gap-16"],
                [20, "xl:active:gap-20"],
                [24, "xl:active:gap-24"],
                [28, "xl:active:gap-28"],
                [32, "xl:active:gap-32"],
                [36, "xl:active:gap-36"],
                [40, "xl:active:gap-40"],
                [44, "xl:active:gap-44"],
                [48, "xl:active:gap-48"],
                [52, "xl:active:gap-52"],
                [56, "xl:active:gap-56"],
                [60, "xl:active:gap-60"],
                [64, "xl:active:gap-64"],
                [72, "xl:active:gap-72"],
                [80, "xl:active:gap-80"],
                [96, "xl:active:gap-96"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:disabled:gap-0"],
                ["px", "xs:disabled:gap-px"],
                [0.5, "xs:disabled:gap-0.5"],
                [1, "xs:disabled:gap-1"],
                [1.5, "xs:disabled:gap-1.5"],
                [2, "xs:disabled:gap-2"],
                [2.5, "xs:disabled:gap-2.5"],
                [3, "xs:disabled:gap-3"],
                [3.5, "xs:disabled:gap-3.5"],
                [4, "xs:disabled:gap-4"],
                [5, "xs:disabled:gap-5"],
                [6, "xs:disabled:gap-6"],
                [7, "xs:disabled:gap-7"],
                [8, "xs:disabled:gap-8"],
                [9, "xs:disabled:gap-9"],
                [10, "xs:disabled:gap-10"],
                [11, "xs:disabled:gap-11"],
                [12, "xs:disabled:gap-12"],
                [14, "xs:disabled:gap-14"],
                [16, "xs:disabled:gap-16"],
                [20, "xs:disabled:gap-20"],
                [24, "xs:disabled:gap-24"],
                [28, "xs:disabled:gap-28"],
                [32, "xs:disabled:gap-32"],
                [36, "xs:disabled:gap-36"],
                [40, "xs:disabled:gap-40"],
                [44, "xs:disabled:gap-44"],
                [48, "xs:disabled:gap-48"],
                [52, "xs:disabled:gap-52"],
                [56, "xs:disabled:gap-56"],
                [60, "xs:disabled:gap-60"],
                [64, "xs:disabled:gap-64"],
                [72, "xs:disabled:gap-72"],
                [80, "xs:disabled:gap-80"],
                [96, "xs:disabled:gap-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:disabled:gap-0"],
                ["px", "sm:disabled:gap-px"],
                [0.5, "sm:disabled:gap-0.5"],
                [1, "sm:disabled:gap-1"],
                [1.5, "sm:disabled:gap-1.5"],
                [2, "sm:disabled:gap-2"],
                [2.5, "sm:disabled:gap-2.5"],
                [3, "sm:disabled:gap-3"],
                [3.5, "sm:disabled:gap-3.5"],
                [4, "sm:disabled:gap-4"],
                [5, "sm:disabled:gap-5"],
                [6, "sm:disabled:gap-6"],
                [7, "sm:disabled:gap-7"],
                [8, "sm:disabled:gap-8"],
                [9, "sm:disabled:gap-9"],
                [10, "sm:disabled:gap-10"],
                [11, "sm:disabled:gap-11"],
                [12, "sm:disabled:gap-12"],
                [14, "sm:disabled:gap-14"],
                [16, "sm:disabled:gap-16"],
                [20, "sm:disabled:gap-20"],
                [24, "sm:disabled:gap-24"],
                [28, "sm:disabled:gap-28"],
                [32, "sm:disabled:gap-32"],
                [36, "sm:disabled:gap-36"],
                [40, "sm:disabled:gap-40"],
                [44, "sm:disabled:gap-44"],
                [48, "sm:disabled:gap-48"],
                [52, "sm:disabled:gap-52"],
                [56, "sm:disabled:gap-56"],
                [60, "sm:disabled:gap-60"],
                [64, "sm:disabled:gap-64"],
                [72, "sm:disabled:gap-72"],
                [80, "sm:disabled:gap-80"],
                [96, "sm:disabled:gap-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:disabled:gap-0"],
                ["px", "md:disabled:gap-px"],
                [0.5, "md:disabled:gap-0.5"],
                [1, "md:disabled:gap-1"],
                [1.5, "md:disabled:gap-1.5"],
                [2, "md:disabled:gap-2"],
                [2.5, "md:disabled:gap-2.5"],
                [3, "md:disabled:gap-3"],
                [3.5, "md:disabled:gap-3.5"],
                [4, "md:disabled:gap-4"],
                [5, "md:disabled:gap-5"],
                [6, "md:disabled:gap-6"],
                [7, "md:disabled:gap-7"],
                [8, "md:disabled:gap-8"],
                [9, "md:disabled:gap-9"],
                [10, "md:disabled:gap-10"],
                [11, "md:disabled:gap-11"],
                [12, "md:disabled:gap-12"],
                [14, "md:disabled:gap-14"],
                [16, "md:disabled:gap-16"],
                [20, "md:disabled:gap-20"],
                [24, "md:disabled:gap-24"],
                [28, "md:disabled:gap-28"],
                [32, "md:disabled:gap-32"],
                [36, "md:disabled:gap-36"],
                [40, "md:disabled:gap-40"],
                [44, "md:disabled:gap-44"],
                [48, "md:disabled:gap-48"],
                [52, "md:disabled:gap-52"],
                [56, "md:disabled:gap-56"],
                [60, "md:disabled:gap-60"],
                [64, "md:disabled:gap-64"],
                [72, "md:disabled:gap-72"],
                [80, "md:disabled:gap-80"],
                [96, "md:disabled:gap-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:disabled:gap-0"],
                ["px", "lg:disabled:gap-px"],
                [0.5, "lg:disabled:gap-0.5"],
                [1, "lg:disabled:gap-1"],
                [1.5, "lg:disabled:gap-1.5"],
                [2, "lg:disabled:gap-2"],
                [2.5, "lg:disabled:gap-2.5"],
                [3, "lg:disabled:gap-3"],
                [3.5, "lg:disabled:gap-3.5"],
                [4, "lg:disabled:gap-4"],
                [5, "lg:disabled:gap-5"],
                [6, "lg:disabled:gap-6"],
                [7, "lg:disabled:gap-7"],
                [8, "lg:disabled:gap-8"],
                [9, "lg:disabled:gap-9"],
                [10, "lg:disabled:gap-10"],
                [11, "lg:disabled:gap-11"],
                [12, "lg:disabled:gap-12"],
                [14, "lg:disabled:gap-14"],
                [16, "lg:disabled:gap-16"],
                [20, "lg:disabled:gap-20"],
                [24, "lg:disabled:gap-24"],
                [28, "lg:disabled:gap-28"],
                [32, "lg:disabled:gap-32"],
                [36, "lg:disabled:gap-36"],
                [40, "lg:disabled:gap-40"],
                [44, "lg:disabled:gap-44"],
                [48, "lg:disabled:gap-48"],
                [52, "lg:disabled:gap-52"],
                [56, "lg:disabled:gap-56"],
                [60, "lg:disabled:gap-60"],
                [64, "lg:disabled:gap-64"],
                [72, "lg:disabled:gap-72"],
                [80, "lg:disabled:gap-80"],
                [96, "lg:disabled:gap-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:disabled:gap-0"],
                ["px", "xl:disabled:gap-px"],
                [0.5, "xl:disabled:gap-0.5"],
                [1, "xl:disabled:gap-1"],
                [1.5, "xl:disabled:gap-1.5"],
                [2, "xl:disabled:gap-2"],
                [2.5, "xl:disabled:gap-2.5"],
                [3, "xl:disabled:gap-3"],
                [3.5, "xl:disabled:gap-3.5"],
                [4, "xl:disabled:gap-4"],
                [5, "xl:disabled:gap-5"],
                [6, "xl:disabled:gap-6"],
                [7, "xl:disabled:gap-7"],
                [8, "xl:disabled:gap-8"],
                [9, "xl:disabled:gap-9"],
                [10, "xl:disabled:gap-10"],
                [11, "xl:disabled:gap-11"],
                [12, "xl:disabled:gap-12"],
                [14, "xl:disabled:gap-14"],
                [16, "xl:disabled:gap-16"],
                [20, "xl:disabled:gap-20"],
                [24, "xl:disabled:gap-24"],
                [28, "xl:disabled:gap-28"],
                [32, "xl:disabled:gap-32"],
                [36, "xl:disabled:gap-36"],
                [40, "xl:disabled:gap-40"],
                [44, "xl:disabled:gap-44"],
                [48, "xl:disabled:gap-48"],
                [52, "xl:disabled:gap-52"],
                [56, "xl:disabled:gap-56"],
                [60, "xl:disabled:gap-60"],
                [64, "xl:disabled:gap-64"],
                [72, "xl:disabled:gap-72"],
                [80, "xl:disabled:gap-80"],
                [96, "xl:disabled:gap-96"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:hover:gap-0"],
                ["px", "xs:hover:gap-px"],
                [0.5, "xs:hover:gap-0.5"],
                [1, "xs:hover:gap-1"],
                [1.5, "xs:hover:gap-1.5"],
                [2, "xs:hover:gap-2"],
                [2.5, "xs:hover:gap-2.5"],
                [3, "xs:hover:gap-3"],
                [3.5, "xs:hover:gap-3.5"],
                [4, "xs:hover:gap-4"],
                [5, "xs:hover:gap-5"],
                [6, "xs:hover:gap-6"],
                [7, "xs:hover:gap-7"],
                [8, "xs:hover:gap-8"],
                [9, "xs:hover:gap-9"],
                [10, "xs:hover:gap-10"],
                [11, "xs:hover:gap-11"],
                [12, "xs:hover:gap-12"],
                [14, "xs:hover:gap-14"],
                [16, "xs:hover:gap-16"],
                [20, "xs:hover:gap-20"],
                [24, "xs:hover:gap-24"],
                [28, "xs:hover:gap-28"],
                [32, "xs:hover:gap-32"],
                [36, "xs:hover:gap-36"],
                [40, "xs:hover:gap-40"],
                [44, "xs:hover:gap-44"],
                [48, "xs:hover:gap-48"],
                [52, "xs:hover:gap-52"],
                [56, "xs:hover:gap-56"],
                [60, "xs:hover:gap-60"],
                [64, "xs:hover:gap-64"],
                [72, "xs:hover:gap-72"],
                [80, "xs:hover:gap-80"],
                [96, "xs:hover:gap-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:hover:gap-0"],
                ["px", "sm:hover:gap-px"],
                [0.5, "sm:hover:gap-0.5"],
                [1, "sm:hover:gap-1"],
                [1.5, "sm:hover:gap-1.5"],
                [2, "sm:hover:gap-2"],
                [2.5, "sm:hover:gap-2.5"],
                [3, "sm:hover:gap-3"],
                [3.5, "sm:hover:gap-3.5"],
                [4, "sm:hover:gap-4"],
                [5, "sm:hover:gap-5"],
                [6, "sm:hover:gap-6"],
                [7, "sm:hover:gap-7"],
                [8, "sm:hover:gap-8"],
                [9, "sm:hover:gap-9"],
                [10, "sm:hover:gap-10"],
                [11, "sm:hover:gap-11"],
                [12, "sm:hover:gap-12"],
                [14, "sm:hover:gap-14"],
                [16, "sm:hover:gap-16"],
                [20, "sm:hover:gap-20"],
                [24, "sm:hover:gap-24"],
                [28, "sm:hover:gap-28"],
                [32, "sm:hover:gap-32"],
                [36, "sm:hover:gap-36"],
                [40, "sm:hover:gap-40"],
                [44, "sm:hover:gap-44"],
                [48, "sm:hover:gap-48"],
                [52, "sm:hover:gap-52"],
                [56, "sm:hover:gap-56"],
                [60, "sm:hover:gap-60"],
                [64, "sm:hover:gap-64"],
                [72, "sm:hover:gap-72"],
                [80, "sm:hover:gap-80"],
                [96, "sm:hover:gap-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:hover:gap-0"],
                ["px", "md:hover:gap-px"],
                [0.5, "md:hover:gap-0.5"],
                [1, "md:hover:gap-1"],
                [1.5, "md:hover:gap-1.5"],
                [2, "md:hover:gap-2"],
                [2.5, "md:hover:gap-2.5"],
                [3, "md:hover:gap-3"],
                [3.5, "md:hover:gap-3.5"],
                [4, "md:hover:gap-4"],
                [5, "md:hover:gap-5"],
                [6, "md:hover:gap-6"],
                [7, "md:hover:gap-7"],
                [8, "md:hover:gap-8"],
                [9, "md:hover:gap-9"],
                [10, "md:hover:gap-10"],
                [11, "md:hover:gap-11"],
                [12, "md:hover:gap-12"],
                [14, "md:hover:gap-14"],
                [16, "md:hover:gap-16"],
                [20, "md:hover:gap-20"],
                [24, "md:hover:gap-24"],
                [28, "md:hover:gap-28"],
                [32, "md:hover:gap-32"],
                [36, "md:hover:gap-36"],
                [40, "md:hover:gap-40"],
                [44, "md:hover:gap-44"],
                [48, "md:hover:gap-48"],
                [52, "md:hover:gap-52"],
                [56, "md:hover:gap-56"],
                [60, "md:hover:gap-60"],
                [64, "md:hover:gap-64"],
                [72, "md:hover:gap-72"],
                [80, "md:hover:gap-80"],
                [96, "md:hover:gap-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:hover:gap-0"],
                ["px", "lg:hover:gap-px"],
                [0.5, "lg:hover:gap-0.5"],
                [1, "lg:hover:gap-1"],
                [1.5, "lg:hover:gap-1.5"],
                [2, "lg:hover:gap-2"],
                [2.5, "lg:hover:gap-2.5"],
                [3, "lg:hover:gap-3"],
                [3.5, "lg:hover:gap-3.5"],
                [4, "lg:hover:gap-4"],
                [5, "lg:hover:gap-5"],
                [6, "lg:hover:gap-6"],
                [7, "lg:hover:gap-7"],
                [8, "lg:hover:gap-8"],
                [9, "lg:hover:gap-9"],
                [10, "lg:hover:gap-10"],
                [11, "lg:hover:gap-11"],
                [12, "lg:hover:gap-12"],
                [14, "lg:hover:gap-14"],
                [16, "lg:hover:gap-16"],
                [20, "lg:hover:gap-20"],
                [24, "lg:hover:gap-24"],
                [28, "lg:hover:gap-28"],
                [32, "lg:hover:gap-32"],
                [36, "lg:hover:gap-36"],
                [40, "lg:hover:gap-40"],
                [44, "lg:hover:gap-44"],
                [48, "lg:hover:gap-48"],
                [52, "lg:hover:gap-52"],
                [56, "lg:hover:gap-56"],
                [60, "lg:hover:gap-60"],
                [64, "lg:hover:gap-64"],
                [72, "lg:hover:gap-72"],
                [80, "lg:hover:gap-80"],
                [96, "lg:hover:gap-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:hover:gap-0"],
                ["px", "xl:hover:gap-px"],
                [0.5, "xl:hover:gap-0.5"],
                [1, "xl:hover:gap-1"],
                [1.5, "xl:hover:gap-1.5"],
                [2, "xl:hover:gap-2"],
                [2.5, "xl:hover:gap-2.5"],
                [3, "xl:hover:gap-3"],
                [3.5, "xl:hover:gap-3.5"],
                [4, "xl:hover:gap-4"],
                [5, "xl:hover:gap-5"],
                [6, "xl:hover:gap-6"],
                [7, "xl:hover:gap-7"],
                [8, "xl:hover:gap-8"],
                [9, "xl:hover:gap-9"],
                [10, "xl:hover:gap-10"],
                [11, "xl:hover:gap-11"],
                [12, "xl:hover:gap-12"],
                [14, "xl:hover:gap-14"],
                [16, "xl:hover:gap-16"],
                [20, "xl:hover:gap-20"],
                [24, "xl:hover:gap-24"],
                [28, "xl:hover:gap-28"],
                [32, "xl:hover:gap-32"],
                [36, "xl:hover:gap-36"],
                [40, "xl:hover:gap-40"],
                [44, "xl:hover:gap-44"],
                [48, "xl:hover:gap-48"],
                [52, "xl:hover:gap-52"],
                [56, "xl:hover:gap-56"],
                [60, "xl:hover:gap-60"],
                [64, "xl:hover:gap-64"],
                [72, "xl:hover:gap-72"],
                [80, "xl:hover:gap-80"],
                [96, "xl:hover:gap-96"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:gap-0"],
                ["px", "xs:gap-px"],
                [0.5, "xs:gap-0.5"],
                [1, "xs:gap-1"],
                [1.5, "xs:gap-1.5"],
                [2, "xs:gap-2"],
                [2.5, "xs:gap-2.5"],
                [3, "xs:gap-3"],
                [3.5, "xs:gap-3.5"],
                [4, "xs:gap-4"],
                [5, "xs:gap-5"],
                [6, "xs:gap-6"],
                [7, "xs:gap-7"],
                [8, "xs:gap-8"],
                [9, "xs:gap-9"],
                [10, "xs:gap-10"],
                [11, "xs:gap-11"],
                [12, "xs:gap-12"],
                [14, "xs:gap-14"],
                [16, "xs:gap-16"],
                [20, "xs:gap-20"],
                [24, "xs:gap-24"],
                [28, "xs:gap-28"],
                [32, "xs:gap-32"],
                [36, "xs:gap-36"],
                [40, "xs:gap-40"],
                [44, "xs:gap-44"],
                [48, "xs:gap-48"],
                [52, "xs:gap-52"],
                [56, "xs:gap-56"],
                [60, "xs:gap-60"],
                [64, "xs:gap-64"],
                [72, "xs:gap-72"],
                [80, "xs:gap-80"],
                [96, "xs:gap-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:gap-0"],
                ["px", "sm:gap-px"],
                [0.5, "sm:gap-0.5"],
                [1, "sm:gap-1"],
                [1.5, "sm:gap-1.5"],
                [2, "sm:gap-2"],
                [2.5, "sm:gap-2.5"],
                [3, "sm:gap-3"],
                [3.5, "sm:gap-3.5"],
                [4, "sm:gap-4"],
                [5, "sm:gap-5"],
                [6, "sm:gap-6"],
                [7, "sm:gap-7"],
                [8, "sm:gap-8"],
                [9, "sm:gap-9"],
                [10, "sm:gap-10"],
                [11, "sm:gap-11"],
                [12, "sm:gap-12"],
                [14, "sm:gap-14"],
                [16, "sm:gap-16"],
                [20, "sm:gap-20"],
                [24, "sm:gap-24"],
                [28, "sm:gap-28"],
                [32, "sm:gap-32"],
                [36, "sm:gap-36"],
                [40, "sm:gap-40"],
                [44, "sm:gap-44"],
                [48, "sm:gap-48"],
                [52, "sm:gap-52"],
                [56, "sm:gap-56"],
                [60, "sm:gap-60"],
                [64, "sm:gap-64"],
                [72, "sm:gap-72"],
                [80, "sm:gap-80"],
                [96, "sm:gap-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:gap-0"],
                ["px", "md:gap-px"],
                [0.5, "md:gap-0.5"],
                [1, "md:gap-1"],
                [1.5, "md:gap-1.5"],
                [2, "md:gap-2"],
                [2.5, "md:gap-2.5"],
                [3, "md:gap-3"],
                [3.5, "md:gap-3.5"],
                [4, "md:gap-4"],
                [5, "md:gap-5"],
                [6, "md:gap-6"],
                [7, "md:gap-7"],
                [8, "md:gap-8"],
                [9, "md:gap-9"],
                [10, "md:gap-10"],
                [11, "md:gap-11"],
                [12, "md:gap-12"],
                [14, "md:gap-14"],
                [16, "md:gap-16"],
                [20, "md:gap-20"],
                [24, "md:gap-24"],
                [28, "md:gap-28"],
                [32, "md:gap-32"],
                [36, "md:gap-36"],
                [40, "md:gap-40"],
                [44, "md:gap-44"],
                [48, "md:gap-48"],
                [52, "md:gap-52"],
                [56, "md:gap-56"],
                [60, "md:gap-60"],
                [64, "md:gap-64"],
                [72, "md:gap-72"],
                [80, "md:gap-80"],
                [96, "md:gap-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:gap-0"],
                ["px", "lg:gap-px"],
                [0.5, "lg:gap-0.5"],
                [1, "lg:gap-1"],
                [1.5, "lg:gap-1.5"],
                [2, "lg:gap-2"],
                [2.5, "lg:gap-2.5"],
                [3, "lg:gap-3"],
                [3.5, "lg:gap-3.5"],
                [4, "lg:gap-4"],
                [5, "lg:gap-5"],
                [6, "lg:gap-6"],
                [7, "lg:gap-7"],
                [8, "lg:gap-8"],
                [9, "lg:gap-9"],
                [10, "lg:gap-10"],
                [11, "lg:gap-11"],
                [12, "lg:gap-12"],
                [14, "lg:gap-14"],
                [16, "lg:gap-16"],
                [20, "lg:gap-20"],
                [24, "lg:gap-24"],
                [28, "lg:gap-28"],
                [32, "lg:gap-32"],
                [36, "lg:gap-36"],
                [40, "lg:gap-40"],
                [44, "lg:gap-44"],
                [48, "lg:gap-48"],
                [52, "lg:gap-52"],
                [56, "lg:gap-56"],
                [60, "lg:gap-60"],
                [64, "lg:gap-64"],
                [72, "lg:gap-72"],
                [80, "lg:gap-80"],
                [96, "lg:gap-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:gap-0"],
                ["px", "xl:gap-px"],
                [0.5, "xl:gap-0.5"],
                [1, "xl:gap-1"],
                [1.5, "xl:gap-1.5"],
                [2, "xl:gap-2"],
                [2.5, "xl:gap-2.5"],
                [3, "xl:gap-3"],
                [3.5, "xl:gap-3.5"],
                [4, "xl:gap-4"],
                [5, "xl:gap-5"],
                [6, "xl:gap-6"],
                [7, "xl:gap-7"],
                [8, "xl:gap-8"],
                [9, "xl:gap-9"],
                [10, "xl:gap-10"],
                [11, "xl:gap-11"],
                [12, "xl:gap-12"],
                [14, "xl:gap-14"],
                [16, "xl:gap-16"],
                [20, "xl:gap-20"],
                [24, "xl:gap-24"],
                [28, "xl:gap-28"],
                [32, "xl:gap-32"],
                [36, "xl:gap-36"],
                [40, "xl:gap-40"],
                [44, "xl:gap-44"],
                [48, "xl:gap-48"],
                [52, "xl:gap-52"],
                [56, "xl:gap-56"],
                [60, "xl:gap-60"],
                [64, "xl:gap-64"],
                [72, "xl:gap-72"],
                [80, "xl:gap-80"],
                [96, "xl:gap-96"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexSpacing, string>>([
            [
              "xs",
              new Map<FlexSpacing, string>([
                [0, "xs:open:gap-0"],
                ["px", "xs:open:gap-px"],
                [0.5, "xs:open:gap-0.5"],
                [1, "xs:open:gap-1"],
                [1.5, "xs:open:gap-1.5"],
                [2, "xs:open:gap-2"],
                [2.5, "xs:open:gap-2.5"],
                [3, "xs:open:gap-3"],
                [3.5, "xs:open:gap-3.5"],
                [4, "xs:open:gap-4"],
                [5, "xs:open:gap-5"],
                [6, "xs:open:gap-6"],
                [7, "xs:open:gap-7"],
                [8, "xs:open:gap-8"],
                [9, "xs:open:gap-9"],
                [10, "xs:open:gap-10"],
                [11, "xs:open:gap-11"],
                [12, "xs:open:gap-12"],
                [14, "xs:open:gap-14"],
                [16, "xs:open:gap-16"],
                [20, "xs:open:gap-20"],
                [24, "xs:open:gap-24"],
                [28, "xs:open:gap-28"],
                [32, "xs:open:gap-32"],
                [36, "xs:open:gap-36"],
                [40, "xs:open:gap-40"],
                [44, "xs:open:gap-44"],
                [48, "xs:open:gap-48"],
                [52, "xs:open:gap-52"],
                [56, "xs:open:gap-56"],
                [60, "xs:open:gap-60"],
                [64, "xs:open:gap-64"],
                [72, "xs:open:gap-72"],
                [80, "xs:open:gap-80"],
                [96, "xs:open:gap-96"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSpacing, string>([
                [0, "sm:open:gap-0"],
                ["px", "sm:open:gap-px"],
                [0.5, "sm:open:gap-0.5"],
                [1, "sm:open:gap-1"],
                [1.5, "sm:open:gap-1.5"],
                [2, "sm:open:gap-2"],
                [2.5, "sm:open:gap-2.5"],
                [3, "sm:open:gap-3"],
                [3.5, "sm:open:gap-3.5"],
                [4, "sm:open:gap-4"],
                [5, "sm:open:gap-5"],
                [6, "sm:open:gap-6"],
                [7, "sm:open:gap-7"],
                [8, "sm:open:gap-8"],
                [9, "sm:open:gap-9"],
                [10, "sm:open:gap-10"],
                [11, "sm:open:gap-11"],
                [12, "sm:open:gap-12"],
                [14, "sm:open:gap-14"],
                [16, "sm:open:gap-16"],
                [20, "sm:open:gap-20"],
                [24, "sm:open:gap-24"],
                [28, "sm:open:gap-28"],
                [32, "sm:open:gap-32"],
                [36, "sm:open:gap-36"],
                [40, "sm:open:gap-40"],
                [44, "sm:open:gap-44"],
                [48, "sm:open:gap-48"],
                [52, "sm:open:gap-52"],
                [56, "sm:open:gap-56"],
                [60, "sm:open:gap-60"],
                [64, "sm:open:gap-64"],
                [72, "sm:open:gap-72"],
                [80, "sm:open:gap-80"],
                [96, "sm:open:gap-96"],
              ]),
            ],
            [
              "md",
              new Map<FlexSpacing, string>([
                [0, "md:open:gap-0"],
                ["px", "md:open:gap-px"],
                [0.5, "md:open:gap-0.5"],
                [1, "md:open:gap-1"],
                [1.5, "md:open:gap-1.5"],
                [2, "md:open:gap-2"],
                [2.5, "md:open:gap-2.5"],
                [3, "md:open:gap-3"],
                [3.5, "md:open:gap-3.5"],
                [4, "md:open:gap-4"],
                [5, "md:open:gap-5"],
                [6, "md:open:gap-6"],
                [7, "md:open:gap-7"],
                [8, "md:open:gap-8"],
                [9, "md:open:gap-9"],
                [10, "md:open:gap-10"],
                [11, "md:open:gap-11"],
                [12, "md:open:gap-12"],
                [14, "md:open:gap-14"],
                [16, "md:open:gap-16"],
                [20, "md:open:gap-20"],
                [24, "md:open:gap-24"],
                [28, "md:open:gap-28"],
                [32, "md:open:gap-32"],
                [36, "md:open:gap-36"],
                [40, "md:open:gap-40"],
                [44, "md:open:gap-44"],
                [48, "md:open:gap-48"],
                [52, "md:open:gap-52"],
                [56, "md:open:gap-56"],
                [60, "md:open:gap-60"],
                [64, "md:open:gap-64"],
                [72, "md:open:gap-72"],
                [80, "md:open:gap-80"],
                [96, "md:open:gap-96"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSpacing, string>([
                [0, "lg:open:gap-0"],
                ["px", "lg:open:gap-px"],
                [0.5, "lg:open:gap-0.5"],
                [1, "lg:open:gap-1"],
                [1.5, "lg:open:gap-1.5"],
                [2, "lg:open:gap-2"],
                [2.5, "lg:open:gap-2.5"],
                [3, "lg:open:gap-3"],
                [3.5, "lg:open:gap-3.5"],
                [4, "lg:open:gap-4"],
                [5, "lg:open:gap-5"],
                [6, "lg:open:gap-6"],
                [7, "lg:open:gap-7"],
                [8, "lg:open:gap-8"],
                [9, "lg:open:gap-9"],
                [10, "lg:open:gap-10"],
                [11, "lg:open:gap-11"],
                [12, "lg:open:gap-12"],
                [14, "lg:open:gap-14"],
                [16, "lg:open:gap-16"],
                [20, "lg:open:gap-20"],
                [24, "lg:open:gap-24"],
                [28, "lg:open:gap-28"],
                [32, "lg:open:gap-32"],
                [36, "lg:open:gap-36"],
                [40, "lg:open:gap-40"],
                [44, "lg:open:gap-44"],
                [48, "lg:open:gap-48"],
                [52, "lg:open:gap-52"],
                [56, "lg:open:gap-56"],
                [60, "lg:open:gap-60"],
                [64, "lg:open:gap-64"],
                [72, "lg:open:gap-72"],
                [80, "lg:open:gap-80"],
                [96, "lg:open:gap-96"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSpacing, string>([
                [0, "xl:open:gap-0"],
                ["px", "xl:open:gap-px"],
                [0.5, "xl:open:gap-0.5"],
                [1, "xl:open:gap-1"],
                [1.5, "xl:open:gap-1.5"],
                [2, "xl:open:gap-2"],
                [2.5, "xl:open:gap-2.5"],
                [3, "xl:open:gap-3"],
                [3.5, "xl:open:gap-3.5"],
                [4, "xl:open:gap-4"],
                [5, "xl:open:gap-5"],
                [6, "xl:open:gap-6"],
                [7, "xl:open:gap-7"],
                [8, "xl:open:gap-8"],
                [9, "xl:open:gap-9"],
                [10, "xl:open:gap-10"],
                [11, "xl:open:gap-11"],
                [12, "xl:open:gap-12"],
                [14, "xl:open:gap-14"],
                [16, "xl:open:gap-16"],
                [20, "xl:open:gap-20"],
                [24, "xl:open:gap-24"],
                [28, "xl:open:gap-28"],
                [32, "xl:open:gap-32"],
                [36, "xl:open:gap-36"],
                [40, "xl:open:gap-40"],
                [44, "xl:open:gap-44"],
                [48, "xl:open:gap-48"],
                [52, "xl:open:gap-52"],
                [56, "xl:open:gap-56"],
                [60, "xl:open:gap-60"],
                [64, "xl:open:gap-64"],
                [72, "xl:open:gap-72"],
                [80, "xl:open:gap-80"],
                [96, "xl:open:gap-96"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
