import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, GridStartEnd } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class GridColumnEndBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<GridStartEnd, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<GridStartEnd, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector) {
    const classesMapping = new GridColumnClassesMapping();
    return new GridColumnEndBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, template: GridStartEnd) {
    return this.getClassName(breakpoint, template);
  }
}

class GridColumnClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<GridStartEnd, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<GridStartEnd, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<GridStartEnd, string>
    >(
      "xs",
      new Map<GridStartEnd, string>([
        [1, "xs:col-end-1"],
        [2, "xs:col-end-2"],
        [3, "xs:col-end-3"],
        [4, "xs:col-end-4"],
        [5, "xs:col-end-5"],
        [6, "xs:col-end-6"],
        [7, "xs:col-end-7"],
        [8, "xs:col-end-8"],
        [9, "xs:col-end-9"],
        [10, "xs:col-end-10"],
        [11, "xs:col-end-11"],
        [12, "xs:col-end-12"],
        [13, "xs:col-end-13"],
        ["auto", "xs:col-end-auto"],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<GridStartEnd, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<GridStartEnd, string>>([
            [
              "xs",
              new Map<GridStartEnd, string>([
                [1, "xs:active:col-end-1"],
                [2, "xs:active:col-end-2"],
                [3, "xs:active:col-end-3"],
                [4, "xs:active:col-end-4"],
                [5, "xs:active:col-end-5"],
                [6, "xs:active:col-end-6"],
                [7, "xs:active:col-end-7"],
                [8, "xs:active:col-end-8"],
                [9, "xs:active:col-end-9"],
                [10, "xs:active:col-end-10"],
                [11, "xs:active:col-end-11"],
                [12, "xs:active:col-end-12"],
                [13, "xs:active:col-end-13"],
                ["auto", "xs:active:col-end-auto"],
              ]),
            ],
            [
              "sm",
              new Map<GridStartEnd, string>([
                [1, "sm:active:col-end-1"],
                [2, "sm:active:col-end-2"],
                [3, "sm:active:col-end-3"],
                [4, "sm:active:col-end-4"],
                [5, "sm:active:col-end-5"],
                [6, "sm:active:col-end-6"],
                [7, "sm:active:col-end-7"],
                [8, "sm:active:col-end-8"],
                [9, "sm:active:col-end-9"],
                [10, "sm:active:col-end-10"],
                [11, "sm:active:col-end-11"],
                [12, "sm:active:col-end-12"],
                [13, "sm:active:col-end-13"],
                ["auto", "sm:active:col-end-auto"],
              ]),
            ],
            [
              "md",
              new Map<GridStartEnd, string>([
                [1, "md:active:col-end-1"],
                [2, "md:active:col-end-2"],
                [3, "md:active:col-end-3"],
                [4, "md:active:col-end-4"],
                [5, "md:active:col-end-5"],
                [6, "md:active:col-end-6"],
                [7, "md:active:col-end-7"],
                [8, "md:active:col-end-8"],
                [9, "md:active:col-end-9"],
                [10, "md:active:col-end-10"],
                [11, "md:active:col-end-11"],
                [12, "md:active:col-end-12"],
                [13, "md:active:col-end-13"],
                ["auto", "md:active:col-end-auto"],
              ]),
            ],
            [
              "lg",
              new Map<GridStartEnd, string>([
                [1, "lg:active:col-end-1"],
                [2, "lg:active:col-end-2"],
                [3, "lg:active:col-end-3"],
                [4, "lg:active:col-end-4"],
                [5, "lg:active:col-end-5"],
                [6, "lg:active:col-end-6"],
                [7, "lg:active:col-end-7"],
                [8, "lg:active:col-end-8"],
                [9, "lg:active:col-end-9"],
                [10, "lg:active:col-end-10"],
                [11, "lg:active:col-end-11"],
                [12, "lg:active:col-end-12"],
                [13, "lg:active:col-end-13"],
                ["auto", "lg:active:col-end-auto"],
              ]),
            ],
            [
              "xl",
              new Map<GridStartEnd, string>([
                [1, "xl:active:col-end-1"],
                [2, "xl:active:col-end-2"],
                [3, "xl:active:col-end-3"],
                [4, "xl:active:col-end-4"],
                [5, "xl:active:col-end-5"],
                [6, "xl:active:col-end-6"],
                [7, "xl:active:col-end-7"],
                [8, "xl:active:col-end-8"],
                [9, "xl:active:col-end-9"],
                [10, "xl:active:col-end-10"],
                [11, "xl:active:col-end-11"],
                [12, "xl:active:col-end-12"],
                [13, "xl:active:col-end-13"],
                ["auto", "xl:active:col-end-auto"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<GridStartEnd, string>>([
            [
              "xs",
              new Map<GridStartEnd, string>([
                [1, "xs:disabled:col-end-1"],
                [2, "xs:disabled:col-end-2"],
                [3, "xs:disabled:col-end-3"],
                [4, "xs:disabled:col-end-4"],
                [5, "xs:disabled:col-end-5"],
                [6, "xs:disabled:col-end-6"],
                [7, "xs:disabled:col-end-7"],
                [8, "xs:disabled:col-end-8"],
                [9, "xs:disabled:col-end-9"],
                [10, "xs:disabled:col-end-10"],
                [11, "xs:disabled:col-end-11"],
                [12, "xs:disabled:col-end-12"],
                [13, "xs:disabled:col-end-13"],
                ["auto", "xs:disabled:col-end-auto"],
              ]),
            ],
            [
              "sm",
              new Map<GridStartEnd, string>([
                [1, "sm:disabled:col-end-1"],
                [2, "sm:disabled:col-end-2"],
                [3, "sm:disabled:col-end-3"],
                [4, "sm:disabled:col-end-4"],
                [5, "sm:disabled:col-end-5"],
                [6, "sm:disabled:col-end-6"],
                [7, "sm:disabled:col-end-7"],
                [8, "sm:disabled:col-end-8"],
                [9, "sm:disabled:col-end-9"],
                [10, "sm:disabled:col-end-10"],
                [11, "sm:disabled:col-end-11"],
                [12, "sm:disabled:col-end-12"],
                [13, "sm:disabled:col-end-13"],
                ["auto", "sm:disabled:col-end-auto"],
              ]),
            ],
            [
              "md",
              new Map<GridStartEnd, string>([
                [1, "md:disabled:col-end-1"],
                [2, "md:disabled:col-end-2"],
                [3, "md:disabled:col-end-3"],
                [4, "md:disabled:col-end-4"],
                [5, "md:disabled:col-end-5"],
                [6, "md:disabled:col-end-6"],
                [7, "md:disabled:col-end-7"],
                [8, "md:disabled:col-end-8"],
                [9, "md:disabled:col-end-9"],
                [10, "md:disabled:col-end-10"],
                [11, "md:disabled:col-end-11"],
                [12, "md:disabled:col-end-12"],
                [13, "md:disabled:col-end-13"],
                ["auto", "md:disabled:col-end-auto"],
              ]),
            ],
            [
              "lg",
              new Map<GridStartEnd, string>([
                [1, "lg:disabled:col-end-1"],
                [2, "lg:disabled:col-end-2"],
                [3, "lg:disabled:col-end-3"],
                [4, "lg:disabled:col-end-4"],
                [5, "lg:disabled:col-end-5"],
                [6, "lg:disabled:col-end-6"],
                [7, "lg:disabled:col-end-7"],
                [8, "lg:disabled:col-end-8"],
                [9, "lg:disabled:col-end-9"],
                [10, "lg:disabled:col-end-10"],
                [11, "lg:disabled:col-end-11"],
                [12, "lg:disabled:col-end-12"],
                [13, "lg:disabled:col-end-13"],
                ["auto", "lg:disabled:col-end-auto"],
              ]),
            ],
            [
              "xl",
              new Map<GridStartEnd, string>([
                [1, "xl:disabled:col-end-1"],
                [2, "xl:disabled:col-end-2"],
                [3, "xl:disabled:col-end-3"],
                [4, "xl:disabled:col-end-4"],
                [5, "xl:disabled:col-end-5"],
                [6, "xl:disabled:col-end-6"],
                [7, "xl:disabled:col-end-7"],
                [8, "xl:disabled:col-end-8"],
                [9, "xl:disabled:col-end-9"],
                [10, "xl:disabled:col-end-10"],
                [11, "xl:disabled:col-end-11"],
                [12, "xl:disabled:col-end-12"],
                [13, "xl:disabled:col-end-13"],
                ["auto", "xl:disabled:col-end-auto"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<GridStartEnd, string>>([
            [
              "xs",
              new Map<GridStartEnd, string>([
                [1, "xs:hover:col-end-1"],
                [2, "xs:hover:col-end-2"],
                [3, "xs:hover:col-end-3"],
                [4, "xs:hover:col-end-4"],
                [5, "xs:hover:col-end-5"],
                [6, "xs:hover:col-end-6"],
                [7, "xs:hover:col-end-7"],
                [8, "xs:hover:col-end-8"],
                [9, "xs:hover:col-end-9"],
                [10, "xs:hover:col-end-10"],
                [11, "xs:hover:col-end-11"],
                [12, "xs:hover:col-end-12"],
                [13, "xs:hover:col-end-13"],
                ["auto", "xs:hover:col-end-auto"],
              ]),
            ],
            [
              "sm",
              new Map<GridStartEnd, string>([
                [1, "sm:hover:col-end-1"],
                [2, "sm:hover:col-end-2"],
                [3, "sm:hover:col-end-3"],
                [4, "sm:hover:col-end-4"],
                [5, "sm:hover:col-end-5"],
                [6, "sm:hover:col-end-6"],
                [7, "sm:hover:col-end-7"],
                [8, "sm:hover:col-end-8"],
                [9, "sm:hover:col-end-9"],
                [10, "sm:hover:col-end-10"],
                [11, "sm:hover:col-end-11"],
                [12, "sm:hover:col-end-12"],
                [13, "sm:hover:col-end-13"],
                ["auto", "sm:hover:col-end-auto"],
              ]),
            ],
            [
              "md",
              new Map<GridStartEnd, string>([
                [1, "md:hover:col-end-1"],
                [2, "md:hover:col-end-2"],
                [3, "md:hover:col-end-3"],
                [4, "md:hover:col-end-4"],
                [5, "md:hover:col-end-5"],
                [6, "md:hover:col-end-6"],
                [7, "md:hover:col-end-7"],
                [8, "md:hover:col-end-8"],
                [9, "md:hover:col-end-9"],
                [10, "md:hover:col-end-10"],
                [11, "md:hover:col-end-11"],
                [12, "md:hover:col-end-12"],
                [13, "md:hover:col-end-13"],
                ["auto", "md:hover:col-end-auto"],
              ]),
            ],
            [
              "lg",
              new Map<GridStartEnd, string>([
                [1, "lg:hover:col-end-1"],
                [2, "lg:hover:col-end-2"],
                [3, "lg:hover:col-end-3"],
                [4, "lg:hover:col-end-4"],
                [5, "lg:hover:col-end-5"],
                [6, "lg:hover:col-end-6"],
                [7, "lg:hover:col-end-7"],
                [8, "lg:hover:col-end-8"],
                [9, "lg:hover:col-end-9"],
                [10, "lg:hover:col-end-10"],
                [11, "lg:hover:col-end-11"],
                [12, "lg:hover:col-end-12"],
                [13, "lg:hover:col-end-13"],
                ["auto", "lg:hover:col-end-auto"],
              ]),
            ],
            [
              "xl",
              new Map<GridStartEnd, string>([
                [1, "xl:hover:col-end-1"],
                [2, "xl:hover:col-end-2"],
                [3, "xl:hover:col-end-3"],
                [4, "xl:hover:col-end-4"],
                [5, "xl:hover:col-end-5"],
                [6, "xl:hover:col-end-6"],
                [7, "xl:hover:col-end-7"],
                [8, "xl:hover:col-end-8"],
                [9, "xl:hover:col-end-9"],
                [10, "xl:hover:col-end-10"],
                [11, "xl:hover:col-end-11"],
                [12, "xl:hover:col-end-12"],
                [13, "xl:hover:col-end-13"],
                ["auto", "xl:hover:col-end-auto"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<GridStartEnd, string>>([
            [
              "xs",
              new Map<GridStartEnd, string>([
                [1, "xs:col-end-1"],
                [2, "xs:col-end-2"],
                [3, "xs:col-end-3"],
                [4, "xs:col-end-4"],
                [5, "xs:col-end-5"],
                [6, "xs:col-end-6"],
                [7, "xs:col-end-7"],
                [8, "xs:col-end-8"],
                [9, "xs:col-end-9"],
                [10, "xs:col-end-10"],
                [11, "xs:col-end-11"],
                [12, "xs:col-end-12"],
                [13, "xs:col-end-13"],
                ["auto", "xs:col-end-auto"],
              ]),
            ],
            [
              "sm",
              new Map<GridStartEnd, string>([
                [1, "sm:col-end-1"],
                [2, "sm:col-end-2"],
                [3, "sm:col-end-3"],
                [4, "sm:col-end-4"],
                [5, "sm:col-end-5"],
                [6, "sm:col-end-6"],
                [7, "sm:col-end-7"],
                [8, "sm:col-end-8"],
                [9, "sm:col-end-9"],
                [10, "sm:col-end-10"],
                [11, "sm:col-end-11"],
                [12, "sm:col-end-12"],
                [13, "sm:col-end-13"],
                ["auto", "sm:col-end-auto"],
              ]),
            ],
            [
              "md",
              new Map<GridStartEnd, string>([
                [1, "md:col-end-1"],
                [2, "md:col-end-2"],
                [3, "md:col-end-3"],
                [4, "md:col-end-4"],
                [5, "md:col-end-5"],
                [6, "md:col-end-6"],
                [7, "md:col-end-7"],
                [8, "md:col-end-8"],
                [9, "md:col-end-9"],
                [10, "md:col-end-10"],
                [11, "md:col-end-11"],
                [12, "md:col-end-12"],
                [13, "md:col-end-13"],
                ["auto", "md:col-end-auto"],
              ]),
            ],
            [
              "lg",
              new Map<GridStartEnd, string>([
                [1, "lg:col-end-1"],
                [2, "lg:col-end-2"],
                [3, "lg:col-end-3"],
                [4, "lg:col-end-4"],
                [5, "lg:col-end-5"],
                [6, "lg:col-end-6"],
                [7, "lg:col-end-7"],
                [8, "lg:col-end-8"],
                [9, "lg:col-end-9"],
                [10, "lg:col-end-10"],
                [11, "lg:col-end-11"],
                [12, "lg:col-end-12"],
                [13, "lg:col-end-13"],
                ["auto", "lg:col-end-auto"],
              ]),
            ],
            [
              "xl",
              new Map<GridStartEnd, string>([
                [1, "xl:col-end-1"],
                [2, "xl:col-end-2"],
                [3, "xl:col-end-3"],
                [4, "xl:col-end-4"],
                [5, "xl:col-end-5"],
                [6, "xl:col-end-6"],
                [7, "xl:col-end-7"],
                [8, "xl:col-end-8"],
                [9, "xl:col-end-9"],
                [10, "xl:col-end-10"],
                [11, "xl:col-end-11"],
                [12, "xl:col-end-12"],
                [13, "xl:col-end-13"],
                ["auto", "xl:col-end-auto"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<GridStartEnd, string>>([
            [
              "xs",
              new Map<GridStartEnd, string>([
                [1, "xs:open:col-end-1"],
                [2, "xs:open:col-end-2"],
                [3, "xs:open:col-end-3"],
                [4, "xs:open:col-end-4"],
                [5, "xs:open:col-end-5"],
                [6, "xs:open:col-end-6"],
                [7, "xs:open:col-end-7"],
                [8, "xs:open:col-end-8"],
                [9, "xs:open:col-end-9"],
                [10, "xs:open:col-end-10"],
                [11, "xs:open:col-end-11"],
                [12, "xs:open:col-end-12"],
                [13, "xs:open:col-end-13"],
                ["auto", "xs:open:col-end-auto"],
              ]),
            ],
            [
              "sm",
              new Map<GridStartEnd, string>([
                [1, "sm:open:col-end-1"],
                [2, "sm:open:col-end-2"],
                [3, "sm:open:col-end-3"],
                [4, "sm:open:col-end-4"],
                [5, "sm:open:col-end-5"],
                [6, "sm:open:col-end-6"],
                [7, "sm:open:col-end-7"],
                [8, "sm:open:col-end-8"],
                [9, "sm:open:col-end-9"],
                [10, "sm:open:col-end-10"],
                [11, "sm:open:col-end-11"],
                [12, "sm:open:col-end-12"],
                [13, "sm:open:col-end-13"],
                ["auto", "sm:open:col-end-auto"],
              ]),
            ],
            [
              "md",
              new Map<GridStartEnd, string>([
                [1, "md:open:col-end-1"],
                [2, "md:open:col-end-2"],
                [3, "md:open:col-end-3"],
                [4, "md:open:col-end-4"],
                [5, "md:open:col-end-5"],
                [6, "md:open:col-end-6"],
                [7, "md:open:col-end-7"],
                [8, "md:open:col-end-8"],
                [9, "md:open:col-end-9"],
                [10, "md:open:col-end-10"],
                [11, "md:open:col-end-11"],
                [12, "md:open:col-end-12"],
                [13, "md:open:col-end-13"],
                ["auto", "md:open:col-end-auto"],
              ]),
            ],
            [
              "lg",
              new Map<GridStartEnd, string>([
                [1, "lg:open:col-end-1"],
                [2, "lg:open:col-end-2"],
                [3, "lg:open:col-end-3"],
                [4, "lg:open:col-end-4"],
                [5, "lg:open:col-end-5"],
                [6, "lg:open:col-end-6"],
                [7, "lg:open:col-end-7"],
                [8, "lg:open:col-end-8"],
                [9, "lg:open:col-end-9"],
                [10, "lg:open:col-end-10"],
                [11, "lg:open:col-end-11"],
                [12, "lg:open:col-end-12"],
                [13, "lg:open:col-end-13"],
                ["auto", "lg:open:col-end-auto"],
              ]),
            ],
            [
              "xl",
              new Map<GridStartEnd, string>([
                [1, "xl:open:col-end-1"],
                [2, "xl:open:col-end-2"],
                [3, "xl:open:col-end-3"],
                [4, "xl:open:col-end-4"],
                [5, "xl:open:col-end-5"],
                [6, "xl:open:col-end-6"],
                [7, "xl:open:col-end-7"],
                [8, "xl:open:col-end-8"],
                [9, "xl:open:col-end-9"],
                [10, "xl:open:col-end-10"],
                [11, "xl:open:col-end-11"],
                [12, "xl:open:col-end-12"],
                [13, "xl:open:col-end-13"],
                ["auto", "xl:open:col-end-auto"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
