import { Breakpoints, CSSSelector, FlexSize } from "../../types";
import { CSSProperty } from "../../Entities/CSSProperty";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";

export class SizeBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexSize, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexSize, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new SizeClassesMapping();
    return new SizeBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, size: FlexSize) {
    return this.getClassName(breakpoint, size);
  }
}

class SizeClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexSize, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexSize, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexSize, string>>(
      "xs",
      new Map<FlexSize, string>([["auto", "size-auto"]])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexSize, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexSize, string>>([
            [
              "xs",
              new Map<FlexSize, string>([
                [0, "xs:active:size-0"],
                ["px", "xs:active:size-px"],
                [0.5, "xs:active:size-0.5"],
                [1, "xs:active:size-1"],
                [1.5, "xs:active:size-1.5"],
                [2, "xs:active:size-2"],
                [2.5, "xs:active:size-2.5"],
                [3, "xs:active:size-3"],
                [3.5, "xs:active:size-3.5"],
                [4, "xs:active:size-4"],
                [5, "xs:active:size-5"],
                [6, "xs:active:size-6"],
                [7, "xs:active:size-7"],
                [8, "xs:active:size-8"],
                [9, "xs:active:size-9"],
                [10, "xs:active:size-10"],
                [11, "xs:active:size-11"],
                [12, "xs:active:size-12"],
                [14, "xs:active:size-14"],
                [16, "xs:active:size-16"],
                [20, "xs:active:size-20"],
                [24, "xs:active:size-24"],
                [28, "xs:active:size-28"],
                [32, "xs:active:size-32"],
                [36, "xs:active:size-36"],
                [40, "xs:active:size-40"],
                [44, "xs:active:size-44"],
                [48, "xs:active:size-48"],
                [52, "xs:active:size-52"],
                [56, "xs:active:size-56"],
                [60, "xs:active:size-60"],
                [64, "xs:active:size-64"],
                [72, "xs:active:size-72"],
                [80, "xs:active:size-80"],
                [96, "xs:active:size-96"],
                ["auto", "xs:active:size-auto"],
                ["1/2", "xs:active:size-1/2"],
                ["1/3", "xs:active:size-1/3"],
                ["2/3", "xs:active:size-2/3"],
                ["1/4", "xs:active:size-1/4"],
                ["2/4", "xs:active:size-2/4"],
                ["3/4", "xs:active:size-3/4"],
                ["1/5", "xs:active:size-1/5"],
                ["2/5", "xs:active:size-2/5"],
                ["3/5", "xs:active:size-3/5"],
                ["4/5", "xs:active:size-4/5"],
                ["1/6", "xs:active:size-1/6"],
                ["2/6", "xs:active:size-2/6"],
                ["3/6", "xs:active:size-3/6"],
                ["4/6", "xs:active:size-4/6"],
                ["5/6", "xs:active:size-5/6"],
                ["1/12", "xs:active:size-1/12"],
                ["2/12", "xs:active:size-2/12"],
                ["3/12", "xs:active:size-3/12"],
                ["4/12", "xs:active:size-4/12"],
                ["5/12", "xs:active:size-5/12"],
                ["6/12", "xs:active:size-6/12"],
                ["7/12", "xs:active:size-7/12"],
                ["8/12", "xs:active:size-8/12"],
                ["9/12", "xs:active:size-9/12"],
                ["10/12", "xs:active:size-10/12"],
                ["11/12", "xs:active:size-11/12"],
                ["full", "xs:active:size-full"],
                ["min", "xs:active:size-min"],
                ["max", "xs:active:size-max"],
                ["fit", "xs:active:size-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSize, string>([
                [0, "sm:active:size-0"],
                ["px", "sm:active:size-px"],
                [0.5, "sm:active:size-0.5"],
                [1, "sm:active:size-1"],
                [1.5, "sm:active:size-1.5"],
                [2, "sm:active:size-2"],
                [2.5, "sm:active:size-2.5"],
                [3, "sm:active:size-3"],
                [3.5, "sm:active:size-3.5"],
                [4, "sm:active:size-4"],
                [5, "sm:active:size-5"],
                [6, "sm:active:size-6"],
                [7, "sm:active:size-7"],
                [8, "sm:active:size-8"],
                [9, "sm:active:size-9"],
                [10, "sm:active:size-10"],
                [11, "sm:active:size-11"],
                [12, "sm:active:size-12"],
                [14, "sm:active:size-14"],
                [16, "sm:active:size-16"],
                [20, "sm:active:size-20"],
                [24, "sm:active:size-24"],
                [28, "sm:active:size-28"],
                [32, "sm:active:size-32"],
                [36, "sm:active:size-36"],
                [40, "sm:active:size-40"],
                [44, "sm:active:size-44"],
                [48, "sm:active:size-48"],
                [52, "sm:active:size-52"],
                [56, "sm:active:size-56"],
                [60, "sm:active:size-60"],
                [64, "sm:active:size-64"],
                [72, "sm:active:size-72"],
                [80, "sm:active:size-80"],
                [96, "sm:active:size-96"],
                ["auto", "sm:active:size-auto"],
                ["1/2", "sm:active:size-1/2"],
                ["1/3", "sm:active:size-1/3"],
                ["2/3", "sm:active:size-2/3"],
                ["1/4", "sm:active:size-1/4"],
                ["2/4", "sm:active:size-2/4"],
                ["3/4", "sm:active:size-3/4"],
                ["1/5", "sm:active:size-1/5"],
                ["2/5", "sm:active:size-2/5"],
                ["3/5", "sm:active:size-3/5"],
                ["4/5", "sm:active:size-4/5"],
                ["1/6", "sm:active:size-1/6"],
                ["2/6", "sm:active:size-2/6"],
                ["3/6", "sm:active:size-3/6"],
                ["4/6", "sm:active:size-4/6"],
                ["5/6", "sm:active:size-5/6"],
                ["1/12", "sm:active:size-1/12"],
                ["2/12", "sm:active:size-2/12"],
                ["3/12", "sm:active:size-3/12"],
                ["4/12", "sm:active:size-4/12"],
                ["5/12", "sm:active:size-5/12"],
                ["6/12", "sm:active:size-6/12"],
                ["7/12", "sm:active:size-7/12"],
                ["8/12", "sm:active:size-8/12"],
                ["9/12", "sm:active:size-9/12"],
                ["10/12", "sm:active:size-10/12"],
                ["11/12", "sm:active:size-11/12"],
                ["full", "sm:active:size-full"],
                ["min", "sm:active:size-min"],
                ["max", "sm:active:size-max"],
                ["fit", "sm:active:size-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexSize, string>([
                [0, "md:active:size-0"],
                ["px", "md:active:size-px"],
                [0.5, "md:active:size-0.5"],
                [1, "md:active:size-1"],
                [1.5, "md:active:size-1.5"],
                [2, "md:active:size-2"],
                [2.5, "md:active:size-2.5"],
                [3, "md:active:size-3"],
                [3.5, "md:active:size-3.5"],
                [4, "md:active:size-4"],
                [5, "md:active:size-5"],
                [6, "md:active:size-6"],
                [7, "md:active:size-7"],
                [8, "md:active:size-8"],
                [9, "md:active:size-9"],
                [10, "md:active:size-10"],
                [11, "md:active:size-11"],
                [12, "md:active:size-12"],
                [14, "md:active:size-14"],
                [16, "md:active:size-16"],
                [20, "md:active:size-20"],
                [24, "md:active:size-24"],
                [28, "md:active:size-28"],
                [32, "md:active:size-32"],
                [36, "md:active:size-36"],
                [40, "md:active:size-40"],
                [44, "md:active:size-44"],
                [48, "md:active:size-48"],
                [52, "md:active:size-52"],
                [56, "md:active:size-56"],
                [60, "md:active:size-60"],
                [64, "md:active:size-64"],
                [72, "md:active:size-72"],
                [80, "md:active:size-80"],
                [96, "md:active:size-96"],
                ["auto", "md:active:size-auto"],
                ["1/2", "md:active:size-1/2"],
                ["1/3", "md:active:size-1/3"],
                ["2/3", "md:active:size-2/3"],
                ["1/4", "md:active:size-1/4"],
                ["2/4", "md:active:size-2/4"],
                ["3/4", "md:active:size-3/4"],
                ["1/5", "md:active:size-1/5"],
                ["2/5", "md:active:size-2/5"],
                ["3/5", "md:active:size-3/5"],
                ["4/5", "md:active:size-4/5"],
                ["1/6", "md:active:size-1/6"],
                ["2/6", "md:active:size-2/6"],
                ["3/6", "md:active:size-3/6"],
                ["4/6", "md:active:size-4/6"],
                ["5/6", "md:active:size-5/6"],
                ["1/12", "md:active:size-1/12"],
                ["2/12", "md:active:size-2/12"],
                ["3/12", "md:active:size-3/12"],
                ["4/12", "md:active:size-4/12"],
                ["5/12", "md:active:size-5/12"],
                ["6/12", "md:active:size-6/12"],
                ["7/12", "md:active:size-7/12"],
                ["8/12", "md:active:size-8/12"],
                ["9/12", "md:active:size-9/12"],
                ["10/12", "md:active:size-10/12"],
                ["11/12", "md:active:size-11/12"],
                ["full", "md:active:size-full"],
                ["min", "md:active:size-min"],
                ["max", "md:active:size-max"],
                ["fit", "md:active:size-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSize, string>([
                [0, "lg:active:size-0"],
                ["px", "lg:active:size-px"],
                [0.5, "lg:active:size-0.5"],
                [1, "lg:active:size-1"],
                [1.5, "lg:active:size-1.5"],
                [2, "lg:active:size-2"],
                [2.5, "lg:active:size-2.5"],
                [3, "lg:active:size-3"],
                [3.5, "lg:active:size-3.5"],
                [4, "lg:active:size-4"],
                [5, "lg:active:size-5"],
                [6, "lg:active:size-6"],
                [7, "lg:active:size-7"],
                [8, "lg:active:size-8"],
                [9, "lg:active:size-9"],
                [10, "lg:active:size-10"],
                [11, "lg:active:size-11"],
                [12, "lg:active:size-12"],
                [14, "lg:active:size-14"],
                [16, "lg:active:size-16"],
                [20, "lg:active:size-20"],
                [24, "lg:active:size-24"],
                [28, "lg:active:size-28"],
                [32, "lg:active:size-32"],
                [36, "lg:active:size-36"],
                [40, "lg:active:size-40"],
                [44, "lg:active:size-44"],
                [48, "lg:active:size-48"],
                [52, "lg:active:size-52"],
                [56, "lg:active:size-56"],
                [60, "lg:active:size-60"],
                [64, "lg:active:size-64"],
                [72, "lg:active:size-72"],
                [80, "lg:active:size-80"],
                [96, "lg:active:size-96"],
                ["auto", "lg:active:size-auto"],
                ["1/2", "lg:active:size-1/2"],
                ["1/3", "lg:active:size-1/3"],
                ["2/3", "lg:active:size-2/3"],
                ["1/4", "lg:active:size-1/4"],
                ["2/4", "lg:active:size-2/4"],
                ["3/4", "lg:active:size-3/4"],
                ["1/5", "lg:active:size-1/5"],
                ["2/5", "lg:active:size-2/5"],
                ["3/5", "lg:active:size-3/5"],
                ["4/5", "lg:active:size-4/5"],
                ["1/6", "lg:active:size-1/6"],
                ["2/6", "lg:active:size-2/6"],
                ["3/6", "lg:active:size-3/6"],
                ["4/6", "lg:active:size-4/6"],
                ["5/6", "lg:active:size-5/6"],
                ["1/12", "lg:active:size-1/12"],
                ["2/12", "lg:active:size-2/12"],
                ["3/12", "lg:active:size-3/12"],
                ["4/12", "lg:active:size-4/12"],
                ["5/12", "lg:active:size-5/12"],
                ["6/12", "lg:active:size-6/12"],
                ["7/12", "lg:active:size-7/12"],
                ["8/12", "lg:active:size-8/12"],
                ["9/12", "lg:active:size-9/12"],
                ["10/12", "lg:active:size-10/12"],
                ["11/12", "lg:active:size-11/12"],
                ["full", "lg:active:size-full"],
                ["min", "lg:active:size-min"],
                ["max", "lg:active:size-max"],
                ["fit", "lg:active:size-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSize, string>([
                [0, "xl:active:size-0"],
                ["px", "xl:active:size-px"],
                [0.5, "xl:active:size-0.5"],
                [1, "xl:active:size-1"],
                [1.5, "xl:active:size-1.5"],
                [2, "xl:active:size-2"],
                [2.5, "xl:active:size-2.5"],
                [3, "xl:active:size-3"],
                [3.5, "xl:active:size-3.5"],
                [4, "xl:active:size-4"],
                [5, "xl:active:size-5"],
                [6, "xl:active:size-6"],
                [7, "xl:active:size-7"],
                [8, "xl:active:size-8"],
                [9, "xl:active:size-9"],
                [10, "xl:active:size-10"],
                [11, "xl:active:size-11"],
                [12, "xl:active:size-12"],
                [14, "xl:active:size-14"],
                [16, "xl:active:size-16"],
                [20, "xl:active:size-20"],
                [24, "xl:active:size-24"],
                [28, "xl:active:size-28"],
                [32, "xl:active:size-32"],
                [36, "xl:active:size-36"],
                [40, "xl:active:size-40"],
                [44, "xl:active:size-44"],
                [48, "xl:active:size-48"],
                [52, "xl:active:size-52"],
                [56, "xl:active:size-56"],
                [60, "xl:active:size-60"],
                [64, "xl:active:size-64"],
                [72, "xl:active:size-72"],
                [80, "xl:active:size-80"],
                [96, "xl:active:size-96"],
                ["auto", "xl:active:size-auto"],
                ["1/2", "xl:active:size-1/2"],
                ["1/3", "xl:active:size-1/3"],
                ["2/3", "xl:active:size-2/3"],
                ["1/4", "xl:active:size-1/4"],
                ["2/4", "xl:active:size-2/4"],
                ["3/4", "xl:active:size-3/4"],
                ["1/5", "xl:active:size-1/5"],
                ["2/5", "xl:active:size-2/5"],
                ["3/5", "xl:active:size-3/5"],
                ["4/5", "xl:active:size-4/5"],
                ["1/6", "xl:active:size-1/6"],
                ["2/6", "xl:active:size-2/6"],
                ["3/6", "xl:active:size-3/6"],
                ["4/6", "xl:active:size-4/6"],
                ["5/6", "xl:active:size-5/6"],
                ["1/12", "xl:active:size-1/12"],
                ["2/12", "xl:active:size-2/12"],
                ["3/12", "xl:active:size-3/12"],
                ["4/12", "xl:active:size-4/12"],
                ["5/12", "xl:active:size-5/12"],
                ["6/12", "xl:active:size-6/12"],
                ["7/12", "xl:active:size-7/12"],
                ["8/12", "xl:active:size-8/12"],
                ["9/12", "xl:active:size-9/12"],
                ["10/12", "xl:active:size-10/12"],
                ["11/12", "xl:active:size-11/12"],
                ["full", "xl:active:size-full"],
                ["min", "xl:active:size-min"],
                ["max", "xl:active:size-max"],
                ["fit", "xl:active:size-fit"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexSize, string>>([
            [
              "xs",
              new Map<FlexSize, string>([
                [0, "xs:disabled:size-0"],
                ["px", "xs:disabled:size-px"],
                [0.5, "xs:disabled:size-0.5"],
                [1, "xs:disabled:size-1"],
                [1.5, "xs:disabled:size-1.5"],
                [2, "xs:disabled:size-2"],
                [2.5, "xs:disabled:size-2.5"],
                [3, "xs:disabled:size-3"],
                [3.5, "xs:disabled:size-3.5"],
                [4, "xs:disabled:size-4"],
                [5, "xs:disabled:size-5"],
                [6, "xs:disabled:size-6"],
                [7, "xs:disabled:size-7"],
                [8, "xs:disabled:size-8"],
                [9, "xs:disabled:size-9"],
                [10, "xs:disabled:size-10"],
                [11, "xs:disabled:size-11"],
                [12, "xs:disabled:size-12"],
                [14, "xs:disabled:size-14"],
                [16, "xs:disabled:size-16"],
                [20, "xs:disabled:size-20"],
                [24, "xs:disabled:size-24"],
                [28, "xs:disabled:size-28"],
                [32, "xs:disabled:size-32"],
                [36, "xs:disabled:size-36"],
                [40, "xs:disabled:size-40"],
                [44, "xs:disabled:size-44"],
                [48, "xs:disabled:size-48"],
                [52, "xs:disabled:size-52"],
                [56, "xs:disabled:size-56"],
                [60, "xs:disabled:size-60"],
                [64, "xs:disabled:size-64"],
                [72, "xs:disabled:size-72"],
                [80, "xs:disabled:size-80"],
                [96, "xs:disabled:size-96"],
                ["auto", "xs:disabled:size-auto"],
                ["1/2", "xs:disabled:size-1/2"],
                ["1/3", "xs:disabled:size-1/3"],
                ["2/3", "xs:disabled:size-2/3"],
                ["1/4", "xs:disabled:size-1/4"],
                ["2/4", "xs:disabled:size-2/4"],
                ["3/4", "xs:disabled:size-3/4"],
                ["1/5", "xs:disabled:size-1/5"],
                ["2/5", "xs:disabled:size-2/5"],
                ["3/5", "xs:disabled:size-3/5"],
                ["4/5", "xs:disabled:size-4/5"],
                ["1/6", "xs:disabled:size-1/6"],
                ["2/6", "xs:disabled:size-2/6"],
                ["3/6", "xs:disabled:size-3/6"],
                ["4/6", "xs:disabled:size-4/6"],
                ["5/6", "xs:disabled:size-5/6"],
                ["1/12", "xs:disabled:size-1/12"],
                ["2/12", "xs:disabled:size-2/12"],
                ["3/12", "xs:disabled:size-3/12"],
                ["4/12", "xs:disabled:size-4/12"],
                ["5/12", "xs:disabled:size-5/12"],
                ["6/12", "xs:disabled:size-6/12"],
                ["7/12", "xs:disabled:size-7/12"],
                ["8/12", "xs:disabled:size-8/12"],
                ["9/12", "xs:disabled:size-9/12"],
                ["10/12", "xs:disabled:size-10/12"],
                ["11/12", "xs:disabled:size-11/12"],
                ["full", "xs:disabled:size-full"],
                ["min", "xs:disabled:size-min"],
                ["max", "xs:disabled:size-max"],
                ["fit", "xs:disabled:size-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSize, string>([
                [0, "sm:disabled:size-0"],
                ["px", "sm:disabled:size-px"],
                [0.5, "sm:disabled:size-0.5"],
                [1, "sm:disabled:size-1"],
                [1.5, "sm:disabled:size-1.5"],
                [2, "sm:disabled:size-2"],
                [2.5, "sm:disabled:size-2.5"],
                [3, "sm:disabled:size-3"],
                [3.5, "sm:disabled:size-3.5"],
                [4, "sm:disabled:size-4"],
                [5, "sm:disabled:size-5"],
                [6, "sm:disabled:size-6"],
                [7, "sm:disabled:size-7"],
                [8, "sm:disabled:size-8"],
                [9, "sm:disabled:size-9"],
                [10, "sm:disabled:size-10"],
                [11, "sm:disabled:size-11"],
                [12, "sm:disabled:size-12"],
                [14, "sm:disabled:size-14"],
                [16, "sm:disabled:size-16"],
                [20, "sm:disabled:size-20"],
                [24, "sm:disabled:size-24"],
                [28, "sm:disabled:size-28"],
                [32, "sm:disabled:size-32"],
                [36, "sm:disabled:size-36"],
                [40, "sm:disabled:size-40"],
                [44, "sm:disabled:size-44"],
                [48, "sm:disabled:size-48"],
                [52, "sm:disabled:size-52"],
                [56, "sm:disabled:size-56"],
                [60, "sm:disabled:size-60"],
                [64, "sm:disabled:size-64"],
                [72, "sm:disabled:size-72"],
                [80, "sm:disabled:size-80"],
                [96, "sm:disabled:size-96"],
                ["auto", "sm:disabled:size-auto"],
                ["1/2", "sm:disabled:size-1/2"],
                ["1/3", "sm:disabled:size-1/3"],
                ["2/3", "sm:disabled:size-2/3"],
                ["1/4", "sm:disabled:size-1/4"],
                ["2/4", "sm:disabled:size-2/4"],
                ["3/4", "sm:disabled:size-3/4"],
                ["1/5", "sm:disabled:size-1/5"],
                ["2/5", "sm:disabled:size-2/5"],
                ["3/5", "sm:disabled:size-3/5"],
                ["4/5", "sm:disabled:size-4/5"],
                ["1/6", "sm:disabled:size-1/6"],
                ["2/6", "sm:disabled:size-2/6"],
                ["3/6", "sm:disabled:size-3/6"],
                ["4/6", "sm:disabled:size-4/6"],
                ["5/6", "sm:disabled:size-5/6"],
                ["1/12", "sm:disabled:size-1/12"],
                ["2/12", "sm:disabled:size-2/12"],
                ["3/12", "sm:disabled:size-3/12"],
                ["4/12", "sm:disabled:size-4/12"],
                ["5/12", "sm:disabled:size-5/12"],
                ["6/12", "sm:disabled:size-6/12"],
                ["7/12", "sm:disabled:size-7/12"],
                ["8/12", "sm:disabled:size-8/12"],
                ["9/12", "sm:disabled:size-9/12"],
                ["10/12", "sm:disabled:size-10/12"],
                ["11/12", "sm:disabled:size-11/12"],
                ["full", "sm:disabled:size-full"],
                ["min", "sm:disabled:size-min"],
                ["max", "sm:disabled:size-max"],
                ["fit", "sm:disabled:size-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexSize, string>([
                [0, "md:disabled:size-0"],
                ["px", "md:disabled:size-px"],
                [0.5, "md:disabled:size-0.5"],
                [1, "md:disabled:size-1"],
                [1.5, "md:disabled:size-1.5"],
                [2, "md:disabled:size-2"],
                [2.5, "md:disabled:size-2.5"],
                [3, "md:disabled:size-3"],
                [3.5, "md:disabled:size-3.5"],
                [4, "md:disabled:size-4"],
                [5, "md:disabled:size-5"],
                [6, "md:disabled:size-6"],
                [7, "md:disabled:size-7"],
                [8, "md:disabled:size-8"],
                [9, "md:disabled:size-9"],
                [10, "md:disabled:size-10"],
                [11, "md:disabled:size-11"],
                [12, "md:disabled:size-12"],
                [14, "md:disabled:size-14"],
                [16, "md:disabled:size-16"],
                [20, "md:disabled:size-20"],
                [24, "md:disabled:size-24"],
                [28, "md:disabled:size-28"],
                [32, "md:disabled:size-32"],
                [36, "md:disabled:size-36"],
                [40, "md:disabled:size-40"],
                [44, "md:disabled:size-44"],
                [48, "md:disabled:size-48"],
                [52, "md:disabled:size-52"],
                [56, "md:disabled:size-56"],
                [60, "md:disabled:size-60"],
                [64, "md:disabled:size-64"],
                [72, "md:disabled:size-72"],
                [80, "md:disabled:size-80"],
                [96, "md:disabled:size-96"],
                ["auto", "md:disabled:size-auto"],
                ["1/2", "md:disabled:size-1/2"],
                ["1/3", "md:disabled:size-1/3"],
                ["2/3", "md:disabled:size-2/3"],
                ["1/4", "md:disabled:size-1/4"],
                ["2/4", "md:disabled:size-2/4"],
                ["3/4", "md:disabled:size-3/4"],
                ["1/5", "md:disabled:size-1/5"],
                ["2/5", "md:disabled:size-2/5"],
                ["3/5", "md:disabled:size-3/5"],
                ["4/5", "md:disabled:size-4/5"],
                ["1/6", "md:disabled:size-1/6"],
                ["2/6", "md:disabled:size-2/6"],
                ["3/6", "md:disabled:size-3/6"],
                ["4/6", "md:disabled:size-4/6"],
                ["5/6", "md:disabled:size-5/6"],
                ["1/12", "md:disabled:size-1/12"],
                ["2/12", "md:disabled:size-2/12"],
                ["3/12", "md:disabled:size-3/12"],
                ["4/12", "md:disabled:size-4/12"],
                ["5/12", "md:disabled:size-5/12"],
                ["6/12", "md:disabled:size-6/12"],
                ["7/12", "md:disabled:size-7/12"],
                ["8/12", "md:disabled:size-8/12"],
                ["9/12", "md:disabled:size-9/12"],
                ["10/12", "md:disabled:size-10/12"],
                ["11/12", "md:disabled:size-11/12"],
                ["full", "md:disabled:size-full"],
                ["min", "md:disabled:size-min"],
                ["max", "md:disabled:size-max"],
                ["fit", "md:disabled:size-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSize, string>([
                [0, "lg:disabled:size-0"],
                ["px", "lg:disabled:size-px"],
                [0.5, "lg:disabled:size-0.5"],
                [1, "lg:disabled:size-1"],
                [1.5, "lg:disabled:size-1.5"],
                [2, "lg:disabled:size-2"],
                [2.5, "lg:disabled:size-2.5"],
                [3, "lg:disabled:size-3"],
                [3.5, "lg:disabled:size-3.5"],
                [4, "lg:disabled:size-4"],
                [5, "lg:disabled:size-5"],
                [6, "lg:disabled:size-6"],
                [7, "lg:disabled:size-7"],
                [8, "lg:disabled:size-8"],
                [9, "lg:disabled:size-9"],
                [10, "lg:disabled:size-10"],
                [11, "lg:disabled:size-11"],
                [12, "lg:disabled:size-12"],
                [14, "lg:disabled:size-14"],
                [16, "lg:disabled:size-16"],
                [20, "lg:disabled:size-20"],
                [24, "lg:disabled:size-24"],
                [28, "lg:disabled:size-28"],
                [32, "lg:disabled:size-32"],
                [36, "lg:disabled:size-36"],
                [40, "lg:disabled:size-40"],
                [44, "lg:disabled:size-44"],
                [48, "lg:disabled:size-48"],
                [52, "lg:disabled:size-52"],
                [56, "lg:disabled:size-56"],
                [60, "lg:disabled:size-60"],
                [64, "lg:disabled:size-64"],
                [72, "lg:disabled:size-72"],
                [80, "lg:disabled:size-80"],
                [96, "lg:disabled:size-96"],
                ["auto", "lg:disabled:size-auto"],
                ["1/2", "lg:disabled:size-1/2"],
                ["1/3", "lg:disabled:size-1/3"],
                ["2/3", "lg:disabled:size-2/3"],
                ["1/4", "lg:disabled:size-1/4"],
                ["2/4", "lg:disabled:size-2/4"],
                ["3/4", "lg:disabled:size-3/4"],
                ["1/5", "lg:disabled:size-1/5"],
                ["2/5", "lg:disabled:size-2/5"],
                ["3/5", "lg:disabled:size-3/5"],
                ["4/5", "lg:disabled:size-4/5"],
                ["1/6", "lg:disabled:size-1/6"],
                ["2/6", "lg:disabled:size-2/6"],
                ["3/6", "lg:disabled:size-3/6"],
                ["4/6", "lg:disabled:size-4/6"],
                ["5/6", "lg:disabled:size-5/6"],
                ["1/12", "lg:disabled:size-1/12"],
                ["2/12", "lg:disabled:size-2/12"],
                ["3/12", "lg:disabled:size-3/12"],
                ["4/12", "lg:disabled:size-4/12"],
                ["5/12", "lg:disabled:size-5/12"],
                ["6/12", "lg:disabled:size-6/12"],
                ["7/12", "lg:disabled:size-7/12"],
                ["8/12", "lg:disabled:size-8/12"],
                ["9/12", "lg:disabled:size-9/12"],
                ["10/12", "lg:disabled:size-10/12"],
                ["11/12", "lg:disabled:size-11/12"],
                ["full", "lg:disabled:size-full"],
                ["min", "lg:disabled:size-min"],
                ["max", "lg:disabled:size-max"],
                ["fit", "lg:disabled:size-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSize, string>([
                [0, "xl:disabled:size-0"],
                ["px", "xl:disabled:size-px"],
                [0.5, "xl:disabled:size-0.5"],
                [1, "xl:disabled:size-1"],
                [1.5, "xl:disabled:size-1.5"],
                [2, "xl:disabled:size-2"],
                [2.5, "xl:disabled:size-2.5"],
                [3, "xl:disabled:size-3"],
                [3.5, "xl:disabled:size-3.5"],
                [4, "xl:disabled:size-4"],
                [5, "xl:disabled:size-5"],
                [6, "xl:disabled:size-6"],
                [7, "xl:disabled:size-7"],
                [8, "xl:disabled:size-8"],
                [9, "xl:disabled:size-9"],
                [10, "xl:disabled:size-10"],
                [11, "xl:disabled:size-11"],
                [12, "xl:disabled:size-12"],
                [14, "xl:disabled:size-14"],
                [16, "xl:disabled:size-16"],
                [20, "xl:disabled:size-20"],
                [24, "xl:disabled:size-24"],
                [28, "xl:disabled:size-28"],
                [32, "xl:disabled:size-32"],
                [36, "xl:disabled:size-36"],
                [40, "xl:disabled:size-40"],
                [44, "xl:disabled:size-44"],
                [48, "xl:disabled:size-48"],
                [52, "xl:disabled:size-52"],
                [56, "xl:disabled:size-56"],
                [60, "xl:disabled:size-60"],
                [64, "xl:disabled:size-64"],
                [72, "xl:disabled:size-72"],
                [80, "xl:disabled:size-80"],
                [96, "xl:disabled:size-96"],
                ["auto", "xl:disabled:size-auto"],
                ["1/2", "xl:disabled:size-1/2"],
                ["1/3", "xl:disabled:size-1/3"],
                ["2/3", "xl:disabled:size-2/3"],
                ["1/4", "xl:disabled:size-1/4"],
                ["2/4", "xl:disabled:size-2/4"],
                ["3/4", "xl:disabled:size-3/4"],
                ["1/5", "xl:disabled:size-1/5"],
                ["2/5", "xl:disabled:size-2/5"],
                ["3/5", "xl:disabled:size-3/5"],
                ["4/5", "xl:disabled:size-4/5"],
                ["1/6", "xl:disabled:size-1/6"],
                ["2/6", "xl:disabled:size-2/6"],
                ["3/6", "xl:disabled:size-3/6"],
                ["4/6", "xl:disabled:size-4/6"],
                ["5/6", "xl:disabled:size-5/6"],
                ["1/12", "xl:disabled:size-1/12"],
                ["2/12", "xl:disabled:size-2/12"],
                ["3/12", "xl:disabled:size-3/12"],
                ["4/12", "xl:disabled:size-4/12"],
                ["5/12", "xl:disabled:size-5/12"],
                ["6/12", "xl:disabled:size-6/12"],
                ["7/12", "xl:disabled:size-7/12"],
                ["8/12", "xl:disabled:size-8/12"],
                ["9/12", "xl:disabled:size-9/12"],
                ["10/12", "xl:disabled:size-10/12"],
                ["11/12", "xl:disabled:size-11/12"],
                ["full", "xl:disabled:size-full"],
                ["min", "xl:disabled:size-min"],
                ["max", "xl:disabled:size-max"],
                ["fit", "xl:disabled:size-fit"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexSize, string>>([
            [
              "xs",
              new Map<FlexSize, string>([
                [0, "xs:hover:size-0"],
                ["px", "xs:hover:size-px"],
                [0.5, "xs:hover:size-0.5"],
                [1, "xs:hover:size-1"],
                [1.5, "xs:hover:size-1.5"],
                [2, "xs:hover:size-2"],
                [2.5, "xs:hover:size-2.5"],
                [3, "xs:hover:size-3"],
                [3.5, "xs:hover:size-3.5"],
                [4, "xs:hover:size-4"],
                [5, "xs:hover:size-5"],
                [6, "xs:hover:size-6"],
                [7, "xs:hover:size-7"],
                [8, "xs:hover:size-8"],
                [9, "xs:hover:size-9"],
                [10, "xs:hover:size-10"],
                [11, "xs:hover:size-11"],
                [12, "xs:hover:size-12"],
                [14, "xs:hover:size-14"],
                [16, "xs:hover:size-16"],
                [20, "xs:hover:size-20"],
                [24, "xs:hover:size-24"],
                [28, "xs:hover:size-28"],
                [32, "xs:hover:size-32"],
                [36, "xs:hover:size-36"],
                [40, "xs:hover:size-40"],
                [44, "xs:hover:size-44"],
                [48, "xs:hover:size-48"],
                [52, "xs:hover:size-52"],
                [56, "xs:hover:size-56"],
                [60, "xs:hover:size-60"],
                [64, "xs:hover:size-64"],
                [72, "xs:hover:size-72"],
                [80, "xs:hover:size-80"],
                [96, "xs:hover:size-96"],
                ["auto", "xs:hover:size-auto"],
                ["1/2", "xs:hover:size-1/2"],
                ["1/3", "xs:hover:size-1/3"],
                ["2/3", "xs:hover:size-2/3"],
                ["1/4", "xs:hover:size-1/4"],
                ["2/4", "xs:hover:size-2/4"],
                ["3/4", "xs:hover:size-3/4"],
                ["1/5", "xs:hover:size-1/5"],
                ["2/5", "xs:hover:size-2/5"],
                ["3/5", "xs:hover:size-3/5"],
                ["4/5", "xs:hover:size-4/5"],
                ["1/6", "xs:hover:size-1/6"],
                ["2/6", "xs:hover:size-2/6"],
                ["3/6", "xs:hover:size-3/6"],
                ["4/6", "xs:hover:size-4/6"],
                ["5/6", "xs:hover:size-5/6"],
                ["1/12", "xs:hover:size-1/12"],
                ["2/12", "xs:hover:size-2/12"],
                ["3/12", "xs:hover:size-3/12"],
                ["4/12", "xs:hover:size-4/12"],
                ["5/12", "xs:hover:size-5/12"],
                ["6/12", "xs:hover:size-6/12"],
                ["7/12", "xs:hover:size-7/12"],
                ["8/12", "xs:hover:size-8/12"],
                ["9/12", "xs:hover:size-9/12"],
                ["10/12", "xs:hover:size-10/12"],
                ["11/12", "xs:hover:size-11/12"],
                ["full", "xs:hover:size-full"],
                ["min", "xs:hover:size-min"],
                ["max", "xs:hover:size-max"],
                ["fit", "xs:hover:size-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSize, string>([
                [0, "sm:hover:size-0"],
                ["px", "sm:hover:size-px"],
                [0.5, "sm:hover:size-0.5"],
                [1, "sm:hover:size-1"],
                [1.5, "sm:hover:size-1.5"],
                [2, "sm:hover:size-2"],
                [2.5, "sm:hover:size-2.5"],
                [3, "sm:hover:size-3"],
                [3.5, "sm:hover:size-3.5"],
                [4, "sm:hover:size-4"],
                [5, "sm:hover:size-5"],
                [6, "sm:hover:size-6"],
                [7, "sm:hover:size-7"],
                [8, "sm:hover:size-8"],
                [9, "sm:hover:size-9"],
                [10, "sm:hover:size-10"],
                [11, "sm:hover:size-11"],
                [12, "sm:hover:size-12"],
                [14, "sm:hover:size-14"],
                [16, "sm:hover:size-16"],
                [20, "sm:hover:size-20"],
                [24, "sm:hover:size-24"],
                [28, "sm:hover:size-28"],
                [32, "sm:hover:size-32"],
                [36, "sm:hover:size-36"],
                [40, "sm:hover:size-40"],
                [44, "sm:hover:size-44"],
                [48, "sm:hover:size-48"],
                [52, "sm:hover:size-52"],
                [56, "sm:hover:size-56"],
                [60, "sm:hover:size-60"],
                [64, "sm:hover:size-64"],
                [72, "sm:hover:size-72"],
                [80, "sm:hover:size-80"],
                [96, "sm:hover:size-96"],
                ["auto", "sm:hover:size-auto"],
                ["1/2", "sm:hover:size-1/2"],
                ["1/3", "sm:hover:size-1/3"],
                ["2/3", "sm:hover:size-2/3"],
                ["1/4", "sm:hover:size-1/4"],
                ["2/4", "sm:hover:size-2/4"],
                ["3/4", "sm:hover:size-3/4"],
                ["1/5", "sm:hover:size-1/5"],
                ["2/5", "sm:hover:size-2/5"],
                ["3/5", "sm:hover:size-3/5"],
                ["4/5", "sm:hover:size-4/5"],
                ["1/6", "sm:hover:size-1/6"],
                ["2/6", "sm:hover:size-2/6"],
                ["3/6", "sm:hover:size-3/6"],
                ["4/6", "sm:hover:size-4/6"],
                ["5/6", "sm:hover:size-5/6"],
                ["1/12", "sm:hover:size-1/12"],
                ["2/12", "sm:hover:size-2/12"],
                ["3/12", "sm:hover:size-3/12"],
                ["4/12", "sm:hover:size-4/12"],
                ["5/12", "sm:hover:size-5/12"],
                ["6/12", "sm:hover:size-6/12"],
                ["7/12", "sm:hover:size-7/12"],
                ["8/12", "sm:hover:size-8/12"],
                ["9/12", "sm:hover:size-9/12"],
                ["10/12", "sm:hover:size-10/12"],
                ["11/12", "sm:hover:size-11/12"],
                ["full", "sm:hover:size-full"],
                ["min", "sm:hover:size-min"],
                ["max", "sm:hover:size-max"],
                ["fit", "sm:hover:size-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexSize, string>([
                [0, "md:hover:size-0"],
                ["px", "md:hover:size-px"],
                [0.5, "md:hover:size-0.5"],
                [1, "md:hover:size-1"],
                [1.5, "md:hover:size-1.5"],
                [2, "md:hover:size-2"],
                [2.5, "md:hover:size-2.5"],
                [3, "md:hover:size-3"],
                [3.5, "md:hover:size-3.5"],
                [4, "md:hover:size-4"],
                [5, "md:hover:size-5"],
                [6, "md:hover:size-6"],
                [7, "md:hover:size-7"],
                [8, "md:hover:size-8"],
                [9, "md:hover:size-9"],
                [10, "md:hover:size-10"],
                [11, "md:hover:size-11"],
                [12, "md:hover:size-12"],
                [14, "md:hover:size-14"],
                [16, "md:hover:size-16"],
                [20, "md:hover:size-20"],
                [24, "md:hover:size-24"],
                [28, "md:hover:size-28"],
                [32, "md:hover:size-32"],
                [36, "md:hover:size-36"],
                [40, "md:hover:size-40"],
                [44, "md:hover:size-44"],
                [48, "md:hover:size-48"],
                [52, "md:hover:size-52"],
                [56, "md:hover:size-56"],
                [60, "md:hover:size-60"],
                [64, "md:hover:size-64"],
                [72, "md:hover:size-72"],
                [80, "md:hover:size-80"],
                [96, "md:hover:size-96"],
                ["auto", "md:hover:size-auto"],
                ["1/2", "md:hover:size-1/2"],
                ["1/3", "md:hover:size-1/3"],
                ["2/3", "md:hover:size-2/3"],
                ["1/4", "md:hover:size-1/4"],
                ["2/4", "md:hover:size-2/4"],
                ["3/4", "md:hover:size-3/4"],
                ["1/5", "md:hover:size-1/5"],
                ["2/5", "md:hover:size-2/5"],
                ["3/5", "md:hover:size-3/5"],
                ["4/5", "md:hover:size-4/5"],
                ["1/6", "md:hover:size-1/6"],
                ["2/6", "md:hover:size-2/6"],
                ["3/6", "md:hover:size-3/6"],
                ["4/6", "md:hover:size-4/6"],
                ["5/6", "md:hover:size-5/6"],
                ["1/12", "md:hover:size-1/12"],
                ["2/12", "md:hover:size-2/12"],
                ["3/12", "md:hover:size-3/12"],
                ["4/12", "md:hover:size-4/12"],
                ["5/12", "md:hover:size-5/12"],
                ["6/12", "md:hover:size-6/12"],
                ["7/12", "md:hover:size-7/12"],
                ["8/12", "md:hover:size-8/12"],
                ["9/12", "md:hover:size-9/12"],
                ["10/12", "md:hover:size-10/12"],
                ["11/12", "md:hover:size-11/12"],
                ["full", "md:hover:size-full"],
                ["min", "md:hover:size-min"],
                ["max", "md:hover:size-max"],
                ["fit", "md:hover:size-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSize, string>([
                [0, "lg:hover:size-0"],
                ["px", "lg:hover:size-px"],
                [0.5, "lg:hover:size-0.5"],
                [1, "lg:hover:size-1"],
                [1.5, "lg:hover:size-1.5"],
                [2, "lg:hover:size-2"],
                [2.5, "lg:hover:size-2.5"],
                [3, "lg:hover:size-3"],
                [3.5, "lg:hover:size-3.5"],
                [4, "lg:hover:size-4"],
                [5, "lg:hover:size-5"],
                [6, "lg:hover:size-6"],
                [7, "lg:hover:size-7"],
                [8, "lg:hover:size-8"],
                [9, "lg:hover:size-9"],
                [10, "lg:hover:size-10"],
                [11, "lg:hover:size-11"],
                [12, "lg:hover:size-12"],
                [14, "lg:hover:size-14"],
                [16, "lg:hover:size-16"],
                [20, "lg:hover:size-20"],
                [24, "lg:hover:size-24"],
                [28, "lg:hover:size-28"],
                [32, "lg:hover:size-32"],
                [36, "lg:hover:size-36"],
                [40, "lg:hover:size-40"],
                [44, "lg:hover:size-44"],
                [48, "lg:hover:size-48"],
                [52, "lg:hover:size-52"],
                [56, "lg:hover:size-56"],
                [60, "lg:hover:size-60"],
                [64, "lg:hover:size-64"],
                [72, "lg:hover:size-72"],
                [80, "lg:hover:size-80"],
                [96, "lg:hover:size-96"],
                ["auto", "lg:hover:size-auto"],
                ["1/2", "lg:hover:size-1/2"],
                ["1/3", "lg:hover:size-1/3"],
                ["2/3", "lg:hover:size-2/3"],
                ["1/4", "lg:hover:size-1/4"],
                ["2/4", "lg:hover:size-2/4"],
                ["3/4", "lg:hover:size-3/4"],
                ["1/5", "lg:hover:size-1/5"],
                ["2/5", "lg:hover:size-2/5"],
                ["3/5", "lg:hover:size-3/5"],
                ["4/5", "lg:hover:size-4/5"],
                ["1/6", "lg:hover:size-1/6"],
                ["2/6", "lg:hover:size-2/6"],
                ["3/6", "lg:hover:size-3/6"],
                ["4/6", "lg:hover:size-4/6"],
                ["5/6", "lg:hover:size-5/6"],
                ["1/12", "lg:hover:size-1/12"],
                ["2/12", "lg:hover:size-2/12"],
                ["3/12", "lg:hover:size-3/12"],
                ["4/12", "lg:hover:size-4/12"],
                ["5/12", "lg:hover:size-5/12"],
                ["6/12", "lg:hover:size-6/12"],
                ["7/12", "lg:hover:size-7/12"],
                ["8/12", "lg:hover:size-8/12"],
                ["9/12", "lg:hover:size-9/12"],
                ["10/12", "lg:hover:size-10/12"],
                ["11/12", "lg:hover:size-11/12"],
                ["full", "lg:hover:size-full"],
                ["min", "lg:hover:size-min"],
                ["max", "lg:hover:size-max"],
                ["fit", "lg:hover:size-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSize, string>([
                [0, "xl:hover:size-0"],
                ["px", "xl:hover:size-px"],
                [0.5, "xl:hover:size-0.5"],
                [1, "xl:hover:size-1"],
                [1.5, "xl:hover:size-1.5"],
                [2, "xl:hover:size-2"],
                [2.5, "xl:hover:size-2.5"],
                [3, "xl:hover:size-3"],
                [3.5, "xl:hover:size-3.5"],
                [4, "xl:hover:size-4"],
                [5, "xl:hover:size-5"],
                [6, "xl:hover:size-6"],
                [7, "xl:hover:size-7"],
                [8, "xl:hover:size-8"],
                [9, "xl:hover:size-9"],
                [10, "xl:hover:size-10"],
                [11, "xl:hover:size-11"],
                [12, "xl:hover:size-12"],
                [14, "xl:hover:size-14"],
                [16, "xl:hover:size-16"],
                [20, "xl:hover:size-20"],
                [24, "xl:hover:size-24"],
                [28, "xl:hover:size-28"],
                [32, "xl:hover:size-32"],
                [36, "xl:hover:size-36"],
                [40, "xl:hover:size-40"],
                [44, "xl:hover:size-44"],
                [48, "xl:hover:size-48"],
                [52, "xl:hover:size-52"],
                [56, "xl:hover:size-56"],
                [60, "xl:hover:size-60"],
                [64, "xl:hover:size-64"],
                [72, "xl:hover:size-72"],
                [80, "xl:hover:size-80"],
                [96, "xl:hover:size-96"],
                ["auto", "xl:hover:size-auto"],
                ["1/2", "xl:hover:size-1/2"],
                ["1/3", "xl:hover:size-1/3"],
                ["2/3", "xl:hover:size-2/3"],
                ["1/4", "xl:hover:size-1/4"],
                ["2/4", "xl:hover:size-2/4"],
                ["3/4", "xl:hover:size-3/4"],
                ["1/5", "xl:hover:size-1/5"],
                ["2/5", "xl:hover:size-2/5"],
                ["3/5", "xl:hover:size-3/5"],
                ["4/5", "xl:hover:size-4/5"],
                ["1/6", "xl:hover:size-1/6"],
                ["2/6", "xl:hover:size-2/6"],
                ["3/6", "xl:hover:size-3/6"],
                ["4/6", "xl:hover:size-4/6"],
                ["5/6", "xl:hover:size-5/6"],
                ["1/12", "xl:hover:size-1/12"],
                ["2/12", "xl:hover:size-2/12"],
                ["3/12", "xl:hover:size-3/12"],
                ["4/12", "xl:hover:size-4/12"],
                ["5/12", "xl:hover:size-5/12"],
                ["6/12", "xl:hover:size-6/12"],
                ["7/12", "xl:hover:size-7/12"],
                ["8/12", "xl:hover:size-8/12"],
                ["9/12", "xl:hover:size-9/12"],
                ["10/12", "xl:hover:size-10/12"],
                ["11/12", "xl:hover:size-11/12"],
                ["full", "xl:hover:size-full"],
                ["min", "xl:hover:size-min"],
                ["max", "xl:hover:size-max"],
                ["fit", "xl:hover:size-fit"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexSize, string>>([
            [
              "xs",
              new Map<FlexSize, string>([
                [0, "xs:size-0"],
                ["px", "xs:size-px"],
                [0.5, "xs:size-0.5"],
                [1, "xs:size-1"],
                [1.5, "xs:size-1.5"],
                [2, "xs:size-2"],
                [2.5, "xs:size-2.5"],
                [3, "xs:size-3"],
                [3.5, "xs:size-3.5"],
                [4, "xs:size-4"],
                [5, "xs:size-5"],
                [6, "xs:size-6"],
                [7, "xs:size-7"],
                [8, "xs:size-8"],
                [9, "xs:size-9"],
                [10, "xs:size-10"],
                [11, "xs:size-11"],
                [12, "xs:size-12"],
                [14, "xs:size-14"],
                [16, "xs:size-16"],
                [20, "xs:size-20"],
                [24, "xs:size-24"],
                [28, "xs:size-28"],
                [32, "xs:size-32"],
                [36, "xs:size-36"],
                [40, "xs:size-40"],
                [44, "xs:size-44"],
                [48, "xs:size-48"],
                [52, "xs:size-52"],
                [56, "xs:size-56"],
                [60, "xs:size-60"],
                [64, "xs:size-64"],
                [72, "xs:size-72"],
                [80, "xs:size-80"],
                [96, "xs:size-96"],
                ["auto", "xs:size-auto"],
                ["1/2", "xs:size-1/2"],
                ["1/3", "xs:size-1/3"],
                ["2/3", "xs:size-2/3"],
                ["1/4", "xs:size-1/4"],
                ["2/4", "xs:size-2/4"],
                ["3/4", "xs:size-3/4"],
                ["1/5", "xs:size-1/5"],
                ["2/5", "xs:size-2/5"],
                ["3/5", "xs:size-3/5"],
                ["4/5", "xs:size-4/5"],
                ["1/6", "xs:size-1/6"],
                ["2/6", "xs:size-2/6"],
                ["3/6", "xs:size-3/6"],
                ["4/6", "xs:size-4/6"],
                ["5/6", "xs:size-5/6"],
                ["1/12", "xs:size-1/12"],
                ["2/12", "xs:size-2/12"],
                ["3/12", "xs:size-3/12"],
                ["4/12", "xs:size-4/12"],
                ["5/12", "xs:size-5/12"],
                ["6/12", "xs:size-6/12"],
                ["7/12", "xs:size-7/12"],
                ["8/12", "xs:size-8/12"],
                ["9/12", "xs:size-9/12"],
                ["10/12", "xs:size-10/12"],
                ["11/12", "xs:size-11/12"],
                ["full", "xs:size-full"],
                ["min", "xs:size-min"],
                ["max", "xs:size-max"],
                ["fit", "xs:size-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSize, string>([
                [0, "sm:size-0"],
                ["px", "sm:size-px"],
                [0.5, "sm:size-0.5"],
                [1, "sm:size-1"],
                [1.5, "sm:size-1.5"],
                [2, "sm:size-2"],
                [2.5, "sm:size-2.5"],
                [3, "sm:size-3"],
                [3.5, "sm:size-3.5"],
                [4, "sm:size-4"],
                [5, "sm:size-5"],
                [6, "sm:size-6"],
                [7, "sm:size-7"],
                [8, "sm:size-8"],
                [9, "sm:size-9"],
                [10, "sm:size-10"],
                [11, "sm:size-11"],
                [12, "sm:size-12"],
                [14, "sm:size-14"],
                [16, "sm:size-16"],
                [20, "sm:size-20"],
                [24, "sm:size-24"],
                [28, "sm:size-28"],
                [32, "sm:size-32"],
                [36, "sm:size-36"],
                [40, "sm:size-40"],
                [44, "sm:size-44"],
                [48, "sm:size-48"],
                [52, "sm:size-52"],
                [56, "sm:size-56"],
                [60, "sm:size-60"],
                [64, "sm:size-64"],
                [72, "sm:size-72"],
                [80, "sm:size-80"],
                [96, "sm:size-96"],
                ["auto", "sm:size-auto"],
                ["1/2", "sm:size-1/2"],
                ["1/3", "sm:size-1/3"],
                ["2/3", "sm:size-2/3"],
                ["1/4", "sm:size-1/4"],
                ["2/4", "sm:size-2/4"],
                ["3/4", "sm:size-3/4"],
                ["1/5", "sm:size-1/5"],
                ["2/5", "sm:size-2/5"],
                ["3/5", "sm:size-3/5"],
                ["4/5", "sm:size-4/5"],
                ["1/6", "sm:size-1/6"],
                ["2/6", "sm:size-2/6"],
                ["3/6", "sm:size-3/6"],
                ["4/6", "sm:size-4/6"],
                ["5/6", "sm:size-5/6"],
                ["1/12", "sm:size-1/12"],
                ["2/12", "sm:size-2/12"],
                ["3/12", "sm:size-3/12"],
                ["4/12", "sm:size-4/12"],
                ["5/12", "sm:size-5/12"],
                ["6/12", "sm:size-6/12"],
                ["7/12", "sm:size-7/12"],
                ["8/12", "sm:size-8/12"],
                ["9/12", "sm:size-9/12"],
                ["10/12", "sm:size-10/12"],
                ["11/12", "sm:size-11/12"],
                ["full", "sm:size-full"],
                ["min", "sm:size-min"],
                ["max", "sm:size-max"],
                ["fit", "sm:size-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexSize, string>([
                [0, "md:size-0"],
                ["px", "md:size-px"],
                [0.5, "md:size-0.5"],
                [1, "md:size-1"],
                [1.5, "md:size-1.5"],
                [2, "md:size-2"],
                [2.5, "md:size-2.5"],
                [3, "md:size-3"],
                [3.5, "md:size-3.5"],
                [4, "md:size-4"],
                [5, "md:size-5"],
                [6, "md:size-6"],
                [7, "md:size-7"],
                [8, "md:size-8"],
                [9, "md:size-9"],
                [10, "md:size-10"],
                [11, "md:size-11"],
                [12, "md:size-12"],
                [14, "md:size-14"],
                [16, "md:size-16"],
                [20, "md:size-20"],
                [24, "md:size-24"],
                [28, "md:size-28"],
                [32, "md:size-32"],
                [36, "md:size-36"],
                [40, "md:size-40"],
                [44, "md:size-44"],
                [48, "md:size-48"],
                [52, "md:size-52"],
                [56, "md:size-56"],
                [60, "md:size-60"],
                [64, "md:size-64"],
                [72, "md:size-72"],
                [80, "md:size-80"],
                [96, "md:size-96"],
                ["auto", "md:size-auto"],
                ["1/2", "md:size-1/2"],
                ["1/3", "md:size-1/3"],
                ["2/3", "md:size-2/3"],
                ["1/4", "md:size-1/4"],
                ["2/4", "md:size-2/4"],
                ["3/4", "md:size-3/4"],
                ["1/5", "md:size-1/5"],
                ["2/5", "md:size-2/5"],
                ["3/5", "md:size-3/5"],
                ["4/5", "md:size-4/5"],
                ["1/6", "md:size-1/6"],
                ["2/6", "md:size-2/6"],
                ["3/6", "md:size-3/6"],
                ["4/6", "md:size-4/6"],
                ["5/6", "md:size-5/6"],
                ["1/12", "md:size-1/12"],
                ["2/12", "md:size-2/12"],
                ["3/12", "md:size-3/12"],
                ["4/12", "md:size-4/12"],
                ["5/12", "md:size-5/12"],
                ["6/12", "md:size-6/12"],
                ["7/12", "md:size-7/12"],
                ["8/12", "md:size-8/12"],
                ["9/12", "md:size-9/12"],
                ["10/12", "md:size-10/12"],
                ["11/12", "md:size-11/12"],
                ["full", "md:size-full"],
                ["min", "md:size-min"],
                ["max", "md:size-max"],
                ["fit", "md:size-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSize, string>([
                [0, "lg:size-0"],
                ["px", "lg:size-px"],
                [0.5, "lg:size-0.5"],
                [1, "lg:size-1"],
                [1.5, "lg:size-1.5"],
                [2, "lg:size-2"],
                [2.5, "lg:size-2.5"],
                [3, "lg:size-3"],
                [3.5, "lg:size-3.5"],
                [4, "lg:size-4"],
                [5, "lg:size-5"],
                [6, "lg:size-6"],
                [7, "lg:size-7"],
                [8, "lg:size-8"],
                [9, "lg:size-9"],
                [10, "lg:size-10"],
                [11, "lg:size-11"],
                [12, "lg:size-12"],
                [14, "lg:size-14"],
                [16, "lg:size-16"],
                [20, "lg:size-20"],
                [24, "lg:size-24"],
                [28, "lg:size-28"],
                [32, "lg:size-32"],
                [36, "lg:size-36"],
                [40, "lg:size-40"],
                [44, "lg:size-44"],
                [48, "lg:size-48"],
                [52, "lg:size-52"],
                [56, "lg:size-56"],
                [60, "lg:size-60"],
                [64, "lg:size-64"],
                [72, "lg:size-72"],
                [80, "lg:size-80"],
                [96, "lg:size-96"],
                ["auto", "lg:size-auto"],
                ["1/2", "lg:size-1/2"],
                ["1/3", "lg:size-1/3"],
                ["2/3", "lg:size-2/3"],
                ["1/4", "lg:size-1/4"],
                ["2/4", "lg:size-2/4"],
                ["3/4", "lg:size-3/4"],
                ["1/5", "lg:size-1/5"],
                ["2/5", "lg:size-2/5"],
                ["3/5", "lg:size-3/5"],
                ["4/5", "lg:size-4/5"],
                ["1/6", "lg:size-1/6"],
                ["2/6", "lg:size-2/6"],
                ["3/6", "lg:size-3/6"],
                ["4/6", "lg:size-4/6"],
                ["5/6", "lg:size-5/6"],
                ["1/12", "lg:size-1/12"],
                ["2/12", "lg:size-2/12"],
                ["3/12", "lg:size-3/12"],
                ["4/12", "lg:size-4/12"],
                ["5/12", "lg:size-5/12"],
                ["6/12", "lg:size-6/12"],
                ["7/12", "lg:size-7/12"],
                ["8/12", "lg:size-8/12"],
                ["9/12", "lg:size-9/12"],
                ["10/12", "lg:size-10/12"],
                ["11/12", "lg:size-11/12"],
                ["full", "lg:size-full"],
                ["min", "lg:size-min"],
                ["max", "lg:size-max"],
                ["fit", "lg:size-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSize, string>([
                [0, "xl:size-0"],
                ["px", "xl:size-px"],
                [0.5, "xl:size-0.5"],
                [1, "xl:size-1"],
                [1.5, "xl:size-1.5"],
                [2, "xl:size-2"],
                [2.5, "xl:size-2.5"],
                [3, "xl:size-3"],
                [3.5, "xl:size-3.5"],
                [4, "xl:size-4"],
                [5, "xl:size-5"],
                [6, "xl:size-6"],
                [7, "xl:size-7"],
                [8, "xl:size-8"],
                [9, "xl:size-9"],
                [10, "xl:size-10"],
                [11, "xl:size-11"],
                [12, "xl:size-12"],
                [14, "xl:size-14"],
                [16, "xl:size-16"],
                [20, "xl:size-20"],
                [24, "xl:size-24"],
                [28, "xl:size-28"],
                [32, "xl:size-32"],
                [36, "xl:size-36"],
                [40, "xl:size-40"],
                [44, "xl:size-44"],
                [48, "xl:size-48"],
                [52, "xl:size-52"],
                [56, "xl:size-56"],
                [60, "xl:size-60"],
                [64, "xl:size-64"],
                [72, "xl:size-72"],
                [80, "xl:size-80"],
                [96, "xl:size-96"],
                ["auto", "xl:size-auto"],
                ["1/2", "xl:size-1/2"],
                ["1/3", "xl:size-1/3"],
                ["2/3", "xl:size-2/3"],
                ["1/4", "xl:size-1/4"],
                ["2/4", "xl:size-2/4"],
                ["3/4", "xl:size-3/4"],
                ["1/5", "xl:size-1/5"],
                ["2/5", "xl:size-2/5"],
                ["3/5", "xl:size-3/5"],
                ["4/5", "xl:size-4/5"],
                ["1/6", "xl:size-1/6"],
                ["2/6", "xl:size-2/6"],
                ["3/6", "xl:size-3/6"],
                ["4/6", "xl:size-4/6"],
                ["5/6", "xl:size-5/6"],
                ["1/12", "xl:size-1/12"],
                ["2/12", "xl:size-2/12"],
                ["3/12", "xl:size-3/12"],
                ["4/12", "xl:size-4/12"],
                ["5/12", "xl:size-5/12"],
                ["6/12", "xl:size-6/12"],
                ["7/12", "xl:size-7/12"],
                ["8/12", "xl:size-8/12"],
                ["9/12", "xl:size-9/12"],
                ["10/12", "xl:size-10/12"],
                ["11/12", "xl:size-11/12"],
                ["full", "xl:size-full"],
                ["min", "xl:size-min"],
                ["max", "xl:size-max"],
                ["fit", "xl:size-fit"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexSize, string>>([
            [
              "xs",
              new Map<FlexSize, string>([
                [0, "xs:open:size-0"],
                ["px", "xs:open:size-px"],
                [0.5, "xs:open:size-0.5"],
                [1, "xs:open:size-1"],
                [1.5, "xs:open:size-1.5"],
                [2, "xs:open:size-2"],
                [2.5, "xs:open:size-2.5"],
                [3, "xs:open:size-3"],
                [3.5, "xs:open:size-3.5"],
                [4, "xs:open:size-4"],
                [5, "xs:open:size-5"],
                [6, "xs:open:size-6"],
                [7, "xs:open:size-7"],
                [8, "xs:open:size-8"],
                [9, "xs:open:size-9"],
                [10, "xs:open:size-10"],
                [11, "xs:open:size-11"],
                [12, "xs:open:size-12"],
                [14, "xs:open:size-14"],
                [16, "xs:open:size-16"],
                [20, "xs:open:size-20"],
                [24, "xs:open:size-24"],
                [28, "xs:open:size-28"],
                [32, "xs:open:size-32"],
                [36, "xs:open:size-36"],
                [40, "xs:open:size-40"],
                [44, "xs:open:size-44"],
                [48, "xs:open:size-48"],
                [52, "xs:open:size-52"],
                [56, "xs:open:size-56"],
                [60, "xs:open:size-60"],
                [64, "xs:open:size-64"],
                [72, "xs:open:size-72"],
                [80, "xs:open:size-80"],
                [96, "xs:open:size-96"],
                ["auto", "xs:open:size-auto"],
                ["1/2", "xs:open:size-1/2"],
                ["1/3", "xs:open:size-1/3"],
                ["2/3", "xs:open:size-2/3"],
                ["1/4", "xs:open:size-1/4"],
                ["2/4", "xs:open:size-2/4"],
                ["3/4", "xs:open:size-3/4"],
                ["1/5", "xs:open:size-1/5"],
                ["2/5", "xs:open:size-2/5"],
                ["3/5", "xs:open:size-3/5"],
                ["4/5", "xs:open:size-4/5"],
                ["1/6", "xs:open:size-1/6"],
                ["2/6", "xs:open:size-2/6"],
                ["3/6", "xs:open:size-3/6"],
                ["4/6", "xs:open:size-4/6"],
                ["5/6", "xs:open:size-5/6"],
                ["1/12", "xs:open:size-1/12"],
                ["2/12", "xs:open:size-2/12"],
                ["3/12", "xs:open:size-3/12"],
                ["4/12", "xs:open:size-4/12"],
                ["5/12", "xs:open:size-5/12"],
                ["6/12", "xs:open:size-6/12"],
                ["7/12", "xs:open:size-7/12"],
                ["8/12", "xs:open:size-8/12"],
                ["9/12", "xs:open:size-9/12"],
                ["10/12", "xs:open:size-10/12"],
                ["11/12", "xs:open:size-11/12"],
                ["full", "xs:open:size-full"],
                ["min", "xs:open:size-min"],
                ["max", "xs:open:size-max"],
                ["fit", "xs:open:size-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexSize, string>([
                [0, "sm:open:size-0"],
                ["px", "sm:open:size-px"],
                [0.5, "sm:open:size-0.5"],
                [1, "sm:open:size-1"],
                [1.5, "sm:open:size-1.5"],
                [2, "sm:open:size-2"],
                [2.5, "sm:open:size-2.5"],
                [3, "sm:open:size-3"],
                [3.5, "sm:open:size-3.5"],
                [4, "sm:open:size-4"],
                [5, "sm:open:size-5"],
                [6, "sm:open:size-6"],
                [7, "sm:open:size-7"],
                [8, "sm:open:size-8"],
                [9, "sm:open:size-9"],
                [10, "sm:open:size-10"],
                [11, "sm:open:size-11"],
                [12, "sm:open:size-12"],
                [14, "sm:open:size-14"],
                [16, "sm:open:size-16"],
                [20, "sm:open:size-20"],
                [24, "sm:open:size-24"],
                [28, "sm:open:size-28"],
                [32, "sm:open:size-32"],
                [36, "sm:open:size-36"],
                [40, "sm:open:size-40"],
                [44, "sm:open:size-44"],
                [48, "sm:open:size-48"],
                [52, "sm:open:size-52"],
                [56, "sm:open:size-56"],
                [60, "sm:open:size-60"],
                [64, "sm:open:size-64"],
                [72, "sm:open:size-72"],
                [80, "sm:open:size-80"],
                [96, "sm:open:size-96"],
                ["auto", "sm:open:size-auto"],
                ["1/2", "sm:open:size-1/2"],
                ["1/3", "sm:open:size-1/3"],
                ["2/3", "sm:open:size-2/3"],
                ["1/4", "sm:open:size-1/4"],
                ["2/4", "sm:open:size-2/4"],
                ["3/4", "sm:open:size-3/4"],
                ["1/5", "sm:open:size-1/5"],
                ["2/5", "sm:open:size-2/5"],
                ["3/5", "sm:open:size-3/5"],
                ["4/5", "sm:open:size-4/5"],
                ["1/6", "sm:open:size-1/6"],
                ["2/6", "sm:open:size-2/6"],
                ["3/6", "sm:open:size-3/6"],
                ["4/6", "sm:open:size-4/6"],
                ["5/6", "sm:open:size-5/6"],
                ["1/12", "sm:open:size-1/12"],
                ["2/12", "sm:open:size-2/12"],
                ["3/12", "sm:open:size-3/12"],
                ["4/12", "sm:open:size-4/12"],
                ["5/12", "sm:open:size-5/12"],
                ["6/12", "sm:open:size-6/12"],
                ["7/12", "sm:open:size-7/12"],
                ["8/12", "sm:open:size-8/12"],
                ["9/12", "sm:open:size-9/12"],
                ["10/12", "sm:open:size-10/12"],
                ["11/12", "sm:open:size-11/12"],
                ["full", "sm:open:size-full"],
                ["min", "sm:open:size-min"],
                ["max", "sm:open:size-max"],
                ["fit", "sm:open:size-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexSize, string>([
                [0, "md:open:size-0"],
                ["px", "md:open:size-px"],
                [0.5, "md:open:size-0.5"],
                [1, "md:open:size-1"],
                [1.5, "md:open:size-1.5"],
                [2, "md:open:size-2"],
                [2.5, "md:open:size-2.5"],
                [3, "md:open:size-3"],
                [3.5, "md:open:size-3.5"],
                [4, "md:open:size-4"],
                [5, "md:open:size-5"],
                [6, "md:open:size-6"],
                [7, "md:open:size-7"],
                [8, "md:open:size-8"],
                [9, "md:open:size-9"],
                [10, "md:open:size-10"],
                [11, "md:open:size-11"],
                [12, "md:open:size-12"],
                [14, "md:open:size-14"],
                [16, "md:open:size-16"],
                [20, "md:open:size-20"],
                [24, "md:open:size-24"],
                [28, "md:open:size-28"],
                [32, "md:open:size-32"],
                [36, "md:open:size-36"],
                [40, "md:open:size-40"],
                [44, "md:open:size-44"],
                [48, "md:open:size-48"],
                [52, "md:open:size-52"],
                [56, "md:open:size-56"],
                [60, "md:open:size-60"],
                [64, "md:open:size-64"],
                [72, "md:open:size-72"],
                [80, "md:open:size-80"],
                [96, "md:open:size-96"],
                ["auto", "md:open:size-auto"],
                ["1/2", "md:open:size-1/2"],
                ["1/3", "md:open:size-1/3"],
                ["2/3", "md:open:size-2/3"],
                ["1/4", "md:open:size-1/4"],
                ["2/4", "md:open:size-2/4"],
                ["3/4", "md:open:size-3/4"],
                ["1/5", "md:open:size-1/5"],
                ["2/5", "md:open:size-2/5"],
                ["3/5", "md:open:size-3/5"],
                ["4/5", "md:open:size-4/5"],
                ["1/6", "md:open:size-1/6"],
                ["2/6", "md:open:size-2/6"],
                ["3/6", "md:open:size-3/6"],
                ["4/6", "md:open:size-4/6"],
                ["5/6", "md:open:size-5/6"],
                ["1/12", "md:open:size-1/12"],
                ["2/12", "md:open:size-2/12"],
                ["3/12", "md:open:size-3/12"],
                ["4/12", "md:open:size-4/12"],
                ["5/12", "md:open:size-5/12"],
                ["6/12", "md:open:size-6/12"],
                ["7/12", "md:open:size-7/12"],
                ["8/12", "md:open:size-8/12"],
                ["9/12", "md:open:size-9/12"],
                ["10/12", "md:open:size-10/12"],
                ["11/12", "md:open:size-11/12"],
                ["full", "md:open:size-full"],
                ["min", "md:open:size-min"],
                ["max", "md:open:size-max"],
                ["fit", "md:open:size-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexSize, string>([
                [0, "lg:open:size-0"],
                ["px", "lg:open:size-px"],
                [0.5, "lg:open:size-0.5"],
                [1, "lg:open:size-1"],
                [1.5, "lg:open:size-1.5"],
                [2, "lg:open:size-2"],
                [2.5, "lg:open:size-2.5"],
                [3, "lg:open:size-3"],
                [3.5, "lg:open:size-3.5"],
                [4, "lg:open:size-4"],
                [5, "lg:open:size-5"],
                [6, "lg:open:size-6"],
                [7, "lg:open:size-7"],
                [8, "lg:open:size-8"],
                [9, "lg:open:size-9"],
                [10, "lg:open:size-10"],
                [11, "lg:open:size-11"],
                [12, "lg:open:size-12"],
                [14, "lg:open:size-14"],
                [16, "lg:open:size-16"],
                [20, "lg:open:size-20"],
                [24, "lg:open:size-24"],
                [28, "lg:open:size-28"],
                [32, "lg:open:size-32"],
                [36, "lg:open:size-36"],
                [40, "lg:open:size-40"],
                [44, "lg:open:size-44"],
                [48, "lg:open:size-48"],
                [52, "lg:open:size-52"],
                [56, "lg:open:size-56"],
                [60, "lg:open:size-60"],
                [64, "lg:open:size-64"],
                [72, "lg:open:size-72"],
                [80, "lg:open:size-80"],
                [96, "lg:open:size-96"],
                ["auto", "lg:open:size-auto"],
                ["1/2", "lg:open:size-1/2"],
                ["1/3", "lg:open:size-1/3"],
                ["2/3", "lg:open:size-2/3"],
                ["1/4", "lg:open:size-1/4"],
                ["2/4", "lg:open:size-2/4"],
                ["3/4", "lg:open:size-3/4"],
                ["1/5", "lg:open:size-1/5"],
                ["2/5", "lg:open:size-2/5"],
                ["3/5", "lg:open:size-3/5"],
                ["4/5", "lg:open:size-4/5"],
                ["1/6", "lg:open:size-1/6"],
                ["2/6", "lg:open:size-2/6"],
                ["3/6", "lg:open:size-3/6"],
                ["4/6", "lg:open:size-4/6"],
                ["5/6", "lg:open:size-5/6"],
                ["1/12", "lg:open:size-1/12"],
                ["2/12", "lg:open:size-2/12"],
                ["3/12", "lg:open:size-3/12"],
                ["4/12", "lg:open:size-4/12"],
                ["5/12", "lg:open:size-5/12"],
                ["6/12", "lg:open:size-6/12"],
                ["7/12", "lg:open:size-7/12"],
                ["8/12", "lg:open:size-8/12"],
                ["9/12", "lg:open:size-9/12"],
                ["10/12", "lg:open:size-10/12"],
                ["11/12", "lg:open:size-11/12"],
                ["full", "lg:open:size-full"],
                ["min", "lg:open:size-min"],
                ["max", "lg:open:size-max"],
                ["fit", "lg:open:size-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexSize, string>([
                [0, "xl:open:size-0"],
                ["px", "xl:open:size-px"],
                [0.5, "xl:open:size-0.5"],
                [1, "xl:open:size-1"],
                [1.5, "xl:open:size-1.5"],
                [2, "xl:open:size-2"],
                [2.5, "xl:open:size-2.5"],
                [3, "xl:open:size-3"],
                [3.5, "xl:open:size-3.5"],
                [4, "xl:open:size-4"],
                [5, "xl:open:size-5"],
                [6, "xl:open:size-6"],
                [7, "xl:open:size-7"],
                [8, "xl:open:size-8"],
                [9, "xl:open:size-9"],
                [10, "xl:open:size-10"],
                [11, "xl:open:size-11"],
                [12, "xl:open:size-12"],
                [14, "xl:open:size-14"],
                [16, "xl:open:size-16"],
                [20, "xl:open:size-20"],
                [24, "xl:open:size-24"],
                [28, "xl:open:size-28"],
                [32, "xl:open:size-32"],
                [36, "xl:open:size-36"],
                [40, "xl:open:size-40"],
                [44, "xl:open:size-44"],
                [48, "xl:open:size-48"],
                [52, "xl:open:size-52"],
                [56, "xl:open:size-56"],
                [60, "xl:open:size-60"],
                [64, "xl:open:size-64"],
                [72, "xl:open:size-72"],
                [80, "xl:open:size-80"],
                [96, "xl:open:size-96"],
                ["auto", "xl:open:size-auto"],
                ["1/2", "xl:open:size-1/2"],
                ["1/3", "xl:open:size-1/3"],
                ["2/3", "xl:open:size-2/3"],
                ["1/4", "xl:open:size-1/4"],
                ["2/4", "xl:open:size-2/4"],
                ["3/4", "xl:open:size-3/4"],
                ["1/5", "xl:open:size-1/5"],
                ["2/5", "xl:open:size-2/5"],
                ["3/5", "xl:open:size-3/5"],
                ["4/5", "xl:open:size-4/5"],
                ["1/6", "xl:open:size-1/6"],
                ["2/6", "xl:open:size-2/6"],
                ["3/6", "xl:open:size-3/6"],
                ["4/6", "xl:open:size-4/6"],
                ["5/6", "xl:open:size-5/6"],
                ["1/12", "xl:open:size-1/12"],
                ["2/12", "xl:open:size-2/12"],
                ["3/12", "xl:open:size-3/12"],
                ["4/12", "xl:open:size-4/12"],
                ["5/12", "xl:open:size-5/12"],
                ["6/12", "xl:open:size-6/12"],
                ["7/12", "xl:open:size-7/12"],
                ["8/12", "xl:open:size-8/12"],
                ["9/12", "xl:open:size-9/12"],
                ["10/12", "xl:open:size-10/12"],
                ["11/12", "xl:open:size-11/12"],
                ["full", "xl:open:size-full"],
                ["min", "xl:open:size-min"],
                ["max", "xl:open:size-max"],
                ["fit", "xl:open:size-fit"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
