import { Breakpoints, CSSSelector, FlexMaxWidth } from "../../types";
import { MaxWidthBreakpoints } from "./MaxWidthBreakpoints";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakable } from "../../Entities/Brekable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";

export class MaxWidth
  extends CSSProperty<Map<FlexMaxWidth, string>>
  implements Breakable<Map<Breakpoints, Map<FlexMaxWidth, string>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<FlexMaxWidth, string>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MaxWidthClassesMapping();
    return new MaxWidth(classesMapping, selector);
  }

  public breakpoints() {
    return MaxWidthBreakpoints.create(this.cssSelector);
  }

  public write(grow: FlexMaxWidth) {
    return this.getClassName(grow);
  }
}

class MaxWidthClassesMapping
  implements ClassesMapping<Map<FlexMaxWidth, string>>
{
  private defaultValue: DefaultValue<FlexMaxWidth, string>;

  constructor() {
    this.defaultValue = new DefaultValue<FlexMaxWidth, string>(
      "none",
      "max-w-none"
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<FlexMaxWidth, string>>([
        [
          "active",
          new Map<FlexMaxWidth, string>([
            [0, "active:max-w-0"],
            ["px", "active:max-w-px"],
            [0.5, "active:max-w-0.5"],
            [1, "active:max-w-1"],
            [1.5, "active:max-w-1.5"],
            [2, "active:max-w-2"],
            [2.5, "active:max-w-2.5"],
            [3, "active:max-w-3"],
            [3.5, "active:max-w-3.5"],
            [4, "active:max-w-4"],
            [5, "active:max-w-5"],
            [6, "active:max-w-6"],
            [7, "active:max-w-7"],
            [8, "active:max-w-8"],
            [9, "active:max-w-9"],
            [10, "active:max-w-10"],
            [11, "active:max-w-11"],
            [12, "active:max-w-12"],
            [14, "active:max-w-14"],
            [16, "active:max-w-16"],
            [20, "active:max-w-20"],
            [24, "active:max-w-24"],
            [28, "active:max-w-28"],
            [32, "active:max-w-32"],
            [36, "active:max-w-36"],
            [40, "active:max-w-40"],
            [44, "active:max-w-44"],
            [48, "active:max-w-48"],
            [52, "active:max-w-52"],
            [56, "active:max-w-56"],
            [60, "active:max-w-60"],
            [64, "active:max-w-64"],
            [72, "active:max-w-72"],
            [80, "active:max-w-80"],
            [96, "active:max-w-96"],
            ["none", "active:max-w-none"],
            ["xs", "active:max-w-xs"],
            ["sm", "active:max-w-sm"],
            ["md", "active:max-w-md"],
            ["lg", "active:max-w-lg"],
            ["xl", "active:max-w-xl"],
            ["2xl", "active:max-w-2xl"],
            ["3xl", "active:max-w-3xl"],
            ["4xl", "active:max-w-4xl"],
            ["5xl", "active:max-w-5xl"],
            ["6xl", "active:max-w-6xl"],
            ["7xl", "active:max-w-7xl"],
            ["full", "active:max-w-full"],
            ["min", "active:max-w-min"],
            ["max", "active:max-w-max"],
            ["fit", "active:max-w-fit"],
            ["prose", "active:max-w-prose"],
            ["screen-xs", "active:max-w-screen-xs"],
            ["screen-sm", "active:max-w-screen-sm"],
            ["screen-md", "active:max-w-screen-md"],
            ["screen-lg", "active:max-w-screen-lg"],
            ["screen-xl", "active:max-w-screen-xl"],
            ["screen-2xl", "active:max-w-screen-2xl"],
          ]),
        ],
        [
          "disabled",
          new Map<FlexMaxWidth, string>([
            [0, "disabled:max-w-0"],
            ["px", "disabled:max-w-px"],
            [0.5, "disabled:max-w-0.5"],
            [1, "disabled:max-w-1"],
            [1.5, "disabled:max-w-1.5"],
            [2, "disabled:max-w-2"],
            [2.5, "disabled:max-w-2.5"],
            [3, "disabled:max-w-3"],
            [3.5, "disabled:max-w-3.5"],
            [4, "disabled:max-w-4"],
            [5, "disabled:max-w-5"],
            [6, "disabled:max-w-6"],
            [7, "disabled:max-w-7"],
            [8, "disabled:max-w-8"],
            [9, "disabled:max-w-9"],
            [10, "disabled:max-w-10"],
            [11, "disabled:max-w-11"],
            [12, "disabled:max-w-12"],
            [14, "disabled:max-w-14"],
            [16, "disabled:max-w-16"],
            [20, "disabled:max-w-20"],
            [24, "disabled:max-w-24"],
            [28, "disabled:max-w-28"],
            [32, "disabled:max-w-32"],
            [36, "disabled:max-w-36"],
            [40, "disabled:max-w-40"],
            [44, "disabled:max-w-44"],
            [48, "disabled:max-w-48"],
            [52, "disabled:max-w-52"],
            [56, "disabled:max-w-56"],
            [60, "disabled:max-w-60"],
            [64, "disabled:max-w-64"],
            [72, "disabled:max-w-72"],
            [80, "disabled:max-w-80"],
            [96, "disabled:max-w-96"],
            ["none", "disabled:max-w-none"],
            ["xs", "disabled:max-w-xs"],
            ["sm", "disabled:max-w-sm"],
            ["md", "disabled:max-w-md"],
            ["lg", "disabled:max-w-lg"],
            ["xl", "disabled:max-w-xl"],
            ["2xl", "disabled:max-w-2xl"],
            ["3xl", "disabled:max-w-3xl"],
            ["4xl", "disabled:max-w-4xl"],
            ["5xl", "disabled:max-w-5xl"],
            ["6xl", "disabled:max-w-6xl"],
            ["7xl", "disabled:max-w-7xl"],
            ["full", "disabled:max-w-full"],
            ["min", "disabled:max-w-min"],
            ["max", "disabled:max-w-max"],
            ["fit", "disabled:max-w-fit"],
            ["prose", "disabled:max-w-prose"],
            ["screen-xs", "disabled:max-w-screen-xs"],
            ["screen-sm", "disabled:max-w-screen-sm"],
            ["screen-md", "disabled:max-w-screen-md"],
            ["screen-lg", "disabled:max-w-screen-lg"],
            ["screen-xl", "disabled:max-w-screen-xl"],
            ["screen-2xl", "disabled:max-w-screen-2xl"],
          ]),
        ],
        [
          "hover",
          new Map<FlexMaxWidth, string>([
            [0, "hover:max-w-0"],
            ["px", "hover:max-w-px"],
            [0.5, "hover:max-w-0.5"],
            [1, "hover:max-w-1"],
            [1.5, "hover:max-w-1.5"],
            [2, "hover:max-w-2"],
            [2.5, "hover:max-w-2.5"],
            [3, "hover:max-w-3"],
            [3.5, "hover:max-w-3.5"],
            [4, "hover:max-w-4"],
            [5, "hover:max-w-5"],
            [6, "hover:max-w-6"],
            [7, "hover:max-w-7"],
            [8, "hover:max-w-8"],
            [9, "hover:max-w-9"],
            [10, "hover:max-w-10"],
            [11, "hover:max-w-11"],
            [12, "hover:max-w-12"],
            [14, "hover:max-w-14"],
            [16, "hover:max-w-16"],
            [20, "hover:max-w-20"],
            [24, "hover:max-w-24"],
            [28, "hover:max-w-28"],
            [32, "hover:max-w-32"],
            [36, "hover:max-w-36"],
            [40, "hover:max-w-40"],
            [44, "hover:max-w-44"],
            [48, "hover:max-w-48"],
            [52, "hover:max-w-52"],
            [56, "hover:max-w-56"],
            [60, "hover:max-w-60"],
            [64, "hover:max-w-64"],
            [72, "hover:max-w-72"],
            [80, "hover:max-w-80"],
            [96, "hover:max-w-96"],
            ["none", "hover:max-w-none"],
            ["xs", "hover:max-w-xs"],
            ["sm", "hover:max-w-sm"],
            ["md", "hover:max-w-md"],
            ["lg", "hover:max-w-lg"],
            ["xl", "hover:max-w-xl"],
            ["2xl", "hover:max-w-2xl"],
            ["3xl", "hover:max-w-3xl"],
            ["4xl", "hover:max-w-4xl"],
            ["5xl", "hover:max-w-5xl"],
            ["6xl", "hover:max-w-6xl"],
            ["7xl", "hover:max-w-7xl"],
            ["full", "hover:max-w-full"],
            ["min", "hover:max-w-min"],
            ["max", "hover:max-w-max"],
            ["fit", "hover:max-w-fit"],
            ["prose", "hover:max-w-prose"],
            ["screen-xs", "hover:max-w-screen-xs"],
            ["screen-sm", "hover:max-w-screen-sm"],
            ["screen-md", "hover:max-w-screen-md"],
            ["screen-lg", "hover:max-w-screen-lg"],
            ["screen-xl", "hover:max-w-screen-xl"],
            ["screen-2xl", "hover:max-w-screen-2xl"],
          ]),
        ],
        [
          "none",
          new Map<FlexMaxWidth, string>([
            [0, "max-w-0"],
            ["px", "max-w-px"],
            [0.5, "max-w-0.5"],
            [1, "max-w-1"],
            [1.5, "max-w-1.5"],
            [2, "max-w-2"],
            [2.5, "max-w-2.5"],
            [3, "max-w-3"],
            [3.5, "max-w-3.5"],
            [4, "max-w-4"],
            [5, "max-w-5"],
            [6, "max-w-6"],
            [7, "max-w-7"],
            [8, "max-w-8"],
            [9, "max-w-9"],
            [10, "max-w-10"],
            [11, "max-w-11"],
            [12, "max-w-12"],
            [14, "max-w-14"],
            [16, "max-w-16"],
            [20, "max-w-20"],
            [24, "max-w-24"],
            [28, "max-w-28"],
            [32, "max-w-32"],
            [36, "max-w-36"],
            [40, "max-w-40"],
            [44, "max-w-44"],
            [48, "max-w-48"],
            [52, "max-w-52"],
            [56, "max-w-56"],
            [60, "max-w-60"],
            [64, "max-w-64"],
            [72, "max-w-72"],
            [80, "max-w-80"],
            [96, "max-w-96"],
            ["none", "max-w-none"],
            ["xs", "max-w-xs"],
            ["sm", "max-w-sm"],
            ["md", "max-w-md"],
            ["lg", "max-w-lg"],
            ["xl", "max-w-xl"],
            ["2xl", "max-w-2xl"],
            ["3xl", "max-w-3xl"],
            ["4xl", "max-w-4xl"],
            ["5xl", "max-w-5xl"],
            ["6xl", "max-w-6xl"],
            ["7xl", "max-w-7xl"],
            ["full", "max-w-full"],
            ["min", "max-w-min"],
            ["max", "max-w-max"],
            ["fit", "max-w-fit"],
            ["prose", "max-w-prose"],
            ["screen-xs", "max-w-screen-xs"],
            ["screen-sm", "max-w-screen-sm"],
            ["screen-md", "max-w-screen-md"],
            ["screen-lg", "max-w-screen-lg"],
            ["screen-xl", "max-w-screen-xl"],
            ["screen-2xl", "max-w-screen-2xl"],
          ]),
        ],
        [
          "open",
          new Map<FlexMaxWidth, string>([
            [0, "open:max-w-0"],
            ["px", "open:max-w-px"],
            [0.5, "open:max-w-0.5"],
            [1, "open:max-w-1"],
            [1.5, "open:max-w-1.5"],
            [2, "open:max-w-2"],
            [2.5, "open:max-w-2.5"],
            [3, "open:max-w-3"],
            [3.5, "open:max-w-3.5"],
            [4, "open:max-w-4"],
            [5, "open:max-w-5"],
            [6, "open:max-w-6"],
            [7, "open:max-w-7"],
            [8, "open:max-w-8"],
            [9, "open:max-w-9"],
            [10, "open:max-w-10"],
            [11, "open:max-w-11"],
            [12, "open:max-w-12"],
            [14, "open:max-w-14"],
            [16, "open:max-w-16"],
            [20, "open:max-w-20"],
            [24, "open:max-w-24"],
            [28, "open:max-w-28"],
            [32, "open:max-w-32"],
            [36, "open:max-w-36"],
            [40, "open:max-w-40"],
            [44, "open:max-w-44"],
            [48, "open:max-w-48"],
            [52, "open:max-w-52"],
            [56, "open:max-w-56"],
            [60, "open:max-w-60"],
            [64, "open:max-w-64"],
            [72, "open:max-w-72"],
            [80, "open:max-w-80"],
            [96, "open:max-w-96"],
            ["none", "open:max-w-none"],
            ["xs", "open:max-w-xs"],
            ["sm", "open:max-w-sm"],
            ["md", "open:max-w-md"],
            ["lg", "open:max-w-lg"],
            ["xl", "open:max-w-xl"],
            ["2xl", "open:max-w-2xl"],
            ["3xl", "open:max-w-3xl"],
            ["4xl", "open:max-w-4xl"],
            ["5xl", "open:max-w-5xl"],
            ["6xl", "open:max-w-6xl"],
            ["7xl", "open:max-w-7xl"],
            ["full", "open:max-w-full"],
            ["min", "open:max-w-min"],
            ["max", "open:max-w-max"],
            ["fit", "open:max-w-fit"],
            ["prose", "open:max-w-prose"],
            ["screen-xs", "open:max-w-screen-xs"],
            ["screen-sm", "open:max-w-screen-sm"],
            ["screen-md", "open:max-w-screen-md"],
            ["screen-lg", "open:max-w-screen-lg"],
            ["screen-xl", "open:max-w-screen-xl"],
            ["screen-2xl", "open:max-w-screen-2xl"],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
