import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexMaxWidth } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class MaxWidthBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexMaxWidth, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexMaxWidth, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MaxWidthClassesMapping();
    return new MaxWidthBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, grow: FlexMaxWidth) {
    return this.getClassName(breakpoint, grow);
  }
}

class MaxWidthClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexMaxWidth, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexMaxWidth, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<FlexMaxWidth, string>
    >("xs", new Map<FlexMaxWidth, string>([["none", "xs:max-w-none"]]));
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexMaxWidth, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexMaxWidth, string>>([
            [
              "xs",
              new Map<FlexMaxWidth, string>([
                [0, "xs:active:max-w-0"],
                ["px", "xs:active:max-w-px"],
                [0.5, "xs:active:max-w-0.5"],
                [1, "xs:active:max-w-1"],
                [1.5, "xs:active:max-w-1.5"],
                [2, "xs:active:max-w-2"],
                [2.5, "xs:active:max-w-2.5"],
                [3, "xs:active:max-w-3"],
                [3.5, "xs:active:max-w-3.5"],
                [4, "xs:active:max-w-4"],
                [5, "xs:active:max-w-5"],
                [6, "xs:active:max-w-6"],
                [7, "xs:active:max-w-7"],
                [8, "xs:active:max-w-8"],
                [9, "xs:active:max-w-9"],
                [10, "xs:active:max-w-10"],
                [11, "xs:active:max-w-11"],
                [12, "xs:active:max-w-12"],
                [14, "xs:active:max-w-14"],
                [16, "xs:active:max-w-16"],
                [20, "xs:active:max-w-20"],
                [24, "xs:active:max-w-24"],
                [28, "xs:active:max-w-28"],
                [32, "xs:active:max-w-32"],
                [36, "xs:active:max-w-36"],
                [40, "xs:active:max-w-40"],
                [44, "xs:active:max-w-44"],
                [48, "xs:active:max-w-48"],
                [52, "xs:active:max-w-52"],
                [56, "xs:active:max-w-56"],
                [60, "xs:active:max-w-60"],
                [64, "xs:active:max-w-64"],
                [72, "xs:active:max-w-72"],
                [80, "xs:active:max-w-80"],
                [96, "xs:active:max-w-96"],
                ["none", "xs:active:max-w-none"],
                ["xs", "xs:active:max-w-xs"],
                ["sm", "xs:active:max-w-sm"],
                ["md", "xs:active:max-w-md"],
                ["lg", "xs:active:max-w-lg"],
                ["xl", "xs:active:max-w-xl"],
                ["2xl", "xs:active:max-w-2xl"],
                ["3xl", "xs:active:max-w-3xl"],
                ["4xl", "xs:active:max-w-4xl"],
                ["5xl", "xs:active:max-w-5xl"],
                ["6xl", "xs:active:max-w-6xl"],
                ["7xl", "xs:active:max-w-7xl"],
                ["full", "xs:active:max-w-full"],
                ["min", "xs:active:max-w-min"],
                ["max", "xs:active:max-w-max"],
                ["fit", "xs:active:max-w-fit"],
                ["prose", "xs:active:max-w-prose"],
                ["screen-xs", "xs:active:max-w-screen-xs"],
                ["screen-sm", "xs:active:max-w-screen-sm"],
                ["screen-md", "xs:active:max-w-screen-md"],
                ["screen-lg", "xs:active:max-w-screen-lg"],
                ["screen-xl", "xs:active:max-w-screen-xl"],
                ["screen-2xl", "xs:active:max-w-screen-2xl"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxWidth, string>([
                [0, "sm:active:max-w-0"],
                ["px", "sm:active:max-w-px"],
                [0.5, "sm:active:max-w-0.5"],
                [1, "sm:active:max-w-1"],
                [1.5, "sm:active:max-w-1.5"],
                [2, "sm:active:max-w-2"],
                [2.5, "sm:active:max-w-2.5"],
                [3, "sm:active:max-w-3"],
                [3.5, "sm:active:max-w-3.5"],
                [4, "sm:active:max-w-4"],
                [5, "sm:active:max-w-5"],
                [6, "sm:active:max-w-6"],
                [7, "sm:active:max-w-7"],
                [8, "sm:active:max-w-8"],
                [9, "sm:active:max-w-9"],
                [10, "sm:active:max-w-10"],
                [11, "sm:active:max-w-11"],
                [12, "sm:active:max-w-12"],
                [14, "sm:active:max-w-14"],
                [16, "sm:active:max-w-16"],
                [20, "sm:active:max-w-20"],
                [24, "sm:active:max-w-24"],
                [28, "sm:active:max-w-28"],
                [32, "sm:active:max-w-32"],
                [36, "sm:active:max-w-36"],
                [40, "sm:active:max-w-40"],
                [44, "sm:active:max-w-44"],
                [48, "sm:active:max-w-48"],
                [52, "sm:active:max-w-52"],
                [56, "sm:active:max-w-56"],
                [60, "sm:active:max-w-60"],
                [64, "sm:active:max-w-64"],
                [72, "sm:active:max-w-72"],
                [80, "sm:active:max-w-80"],
                [96, "sm:active:max-w-96"],
                ["none", "sm:active:max-w-none"],
                ["sm", "sm:active:max-w-sm"],
                ["sm", "sm:active:max-w-sm"],
                ["md", "sm:active:max-w-md"],
                ["lg", "sm:active:max-w-lg"],
                ["xl", "sm:active:max-w-xl"],
                ["2xl", "sm:active:max-w-2xl"],
                ["3xl", "sm:active:max-w-3xl"],
                ["4xl", "sm:active:max-w-4xl"],
                ["5xl", "sm:active:max-w-5xl"],
                ["6xl", "sm:active:max-w-6xl"],
                ["7xl", "sm:active:max-w-7xl"],
                ["full", "sm:active:max-w-full"],
                ["min", "sm:active:max-w-min"],
                ["max", "sm:active:max-w-max"],
                ["fit", "sm:active:max-w-fit"],
                ["prose", "sm:active:max-w-prose"],
                ["screen-sm", "sm:active:max-w-screen-sm"],
                ["screen-sm", "sm:active:max-w-screen-sm"],
                ["screen-md", "sm:active:max-w-screen-md"],
                ["screen-lg", "sm:active:max-w-screen-lg"],
                ["screen-xl", "sm:active:max-w-screen-xl"],
                ["screen-2xl", "sm:active:max-w-screen-2xl"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxWidth, string>([
                [0, "md:active:max-w-0"],
                ["px", "md:active:max-w-px"],
                [0.5, "md:active:max-w-0.5"],
                [1, "md:active:max-w-1"],
                [1.5, "md:active:max-w-1.5"],
                [2, "md:active:max-w-2"],
                [2.5, "md:active:max-w-2.5"],
                [3, "md:active:max-w-3"],
                [3.5, "md:active:max-w-3.5"],
                [4, "md:active:max-w-4"],
                [5, "md:active:max-w-5"],
                [6, "md:active:max-w-6"],
                [7, "md:active:max-w-7"],
                [8, "md:active:max-w-8"],
                [9, "md:active:max-w-9"],
                [10, "md:active:max-w-10"],
                [11, "md:active:max-w-11"],
                [12, "md:active:max-w-12"],
                [14, "md:active:max-w-14"],
                [16, "md:active:max-w-16"],
                [20, "md:active:max-w-20"],
                [24, "md:active:max-w-24"],
                [28, "md:active:max-w-28"],
                [32, "md:active:max-w-32"],
                [36, "md:active:max-w-36"],
                [40, "md:active:max-w-40"],
                [44, "md:active:max-w-44"],
                [48, "md:active:max-w-48"],
                [52, "md:active:max-w-52"],
                [56, "md:active:max-w-56"],
                [60, "md:active:max-w-60"],
                [64, "md:active:max-w-64"],
                [72, "md:active:max-w-72"],
                [80, "md:active:max-w-80"],
                [96, "md:active:max-w-96"],
                ["none", "md:active:max-w-none"],
                ["md", "md:active:max-w-md"],
                ["sm", "md:active:max-w-sm"],
                ["md", "md:active:max-w-md"],
                ["lg", "md:active:max-w-lg"],
                ["xl", "md:active:max-w-xl"],
                ["2xl", "md:active:max-w-2xl"],
                ["3xl", "md:active:max-w-3xl"],
                ["4xl", "md:active:max-w-4xl"],
                ["5xl", "md:active:max-w-5xl"],
                ["6xl", "md:active:max-w-6xl"],
                ["7xl", "md:active:max-w-7xl"],
                ["full", "md:active:max-w-full"],
                ["min", "md:active:max-w-min"],
                ["max", "md:active:max-w-max"],
                ["fit", "md:active:max-w-fit"],
                ["prose", "md:active:max-w-prose"],
                ["screen-md", "md:active:max-w-screen-md"],
                ["screen-sm", "md:active:max-w-screen-sm"],
                ["screen-md", "md:active:max-w-screen-md"],
                ["screen-lg", "md:active:max-w-screen-lg"],
                ["screen-xl", "md:active:max-w-screen-xl"],
                ["screen-2xl", "md:active:max-w-screen-2xl"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxWidth, string>([
                [0, "lg:active:max-w-0"],
                ["px", "lg:active:max-w-px"],
                [0.5, "lg:active:max-w-0.5"],
                [1, "lg:active:max-w-1"],
                [1.5, "lg:active:max-w-1.5"],
                [2, "lg:active:max-w-2"],
                [2.5, "lg:active:max-w-2.5"],
                [3, "lg:active:max-w-3"],
                [3.5, "lg:active:max-w-3.5"],
                [4, "lg:active:max-w-4"],
                [5, "lg:active:max-w-5"],
                [6, "lg:active:max-w-6"],
                [7, "lg:active:max-w-7"],
                [8, "lg:active:max-w-8"],
                [9, "lg:active:max-w-9"],
                [10, "lg:active:max-w-10"],
                [11, "lg:active:max-w-11"],
                [12, "lg:active:max-w-12"],
                [14, "lg:active:max-w-14"],
                [16, "lg:active:max-w-16"],
                [20, "lg:active:max-w-20"],
                [24, "lg:active:max-w-24"],
                [28, "lg:active:max-w-28"],
                [32, "lg:active:max-w-32"],
                [36, "lg:active:max-w-36"],
                [40, "lg:active:max-w-40"],
                [44, "lg:active:max-w-44"],
                [48, "lg:active:max-w-48"],
                [52, "lg:active:max-w-52"],
                [56, "lg:active:max-w-56"],
                [60, "lg:active:max-w-60"],
                [64, "lg:active:max-w-64"],
                [72, "lg:active:max-w-72"],
                [80, "lg:active:max-w-80"],
                [96, "lg:active:max-w-96"],
                ["none", "lg:active:max-w-none"],
                ["lg", "lg:active:max-w-lg"],
                ["sm", "lg:active:max-w-sm"],
                ["md", "lg:active:max-w-md"],
                ["lg", "lg:active:max-w-lg"],
                ["xl", "lg:active:max-w-xl"],
                ["2xl", "lg:active:max-w-2xl"],
                ["3xl", "lg:active:max-w-3xl"],
                ["4xl", "lg:active:max-w-4xl"],
                ["5xl", "lg:active:max-w-5xl"],
                ["6xl", "lg:active:max-w-6xl"],
                ["7xl", "lg:active:max-w-7xl"],
                ["full", "lg:active:max-w-full"],
                ["min", "lg:active:max-w-min"],
                ["max", "lg:active:max-w-max"],
                ["fit", "lg:active:max-w-fit"],
                ["prose", "lg:active:max-w-prose"],
                ["screen-lg", "lg:active:max-w-screen-lg"],
                ["screen-sm", "lg:active:max-w-screen-sm"],
                ["screen-md", "lg:active:max-w-screen-md"],
                ["screen-lg", "lg:active:max-w-screen-lg"],
                ["screen-xl", "lg:active:max-w-screen-xl"],
                ["screen-2xl", "lg:active:max-w-screen-2xl"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxWidth, string>([
                [0, "xl:active:max-w-0"],
                ["px", "xl:active:max-w-px"],
                [0.5, "xl:active:max-w-0.5"],
                [1, "xl:active:max-w-1"],
                [1.5, "xl:active:max-w-1.5"],
                [2, "xl:active:max-w-2"],
                [2.5, "xl:active:max-w-2.5"],
                [3, "xl:active:max-w-3"],
                [3.5, "xl:active:max-w-3.5"],
                [4, "xl:active:max-w-4"],
                [5, "xl:active:max-w-5"],
                [6, "xl:active:max-w-6"],
                [7, "xl:active:max-w-7"],
                [8, "xl:active:max-w-8"],
                [9, "xl:active:max-w-9"],
                [10, "xl:active:max-w-10"],
                [11, "xl:active:max-w-11"],
                [12, "xl:active:max-w-12"],
                [14, "xl:active:max-w-14"],
                [16, "xl:active:max-w-16"],
                [20, "xl:active:max-w-20"],
                [24, "xl:active:max-w-24"],
                [28, "xl:active:max-w-28"],
                [32, "xl:active:max-w-32"],
                [36, "xl:active:max-w-36"],
                [40, "xl:active:max-w-40"],
                [44, "xl:active:max-w-44"],
                [48, "xl:active:max-w-48"],
                [52, "xl:active:max-w-52"],
                [56, "xl:active:max-w-56"],
                [60, "xl:active:max-w-60"],
                [64, "xl:active:max-w-64"],
                [72, "xl:active:max-w-72"],
                [80, "xl:active:max-w-80"],
                [96, "xl:active:max-w-96"],
                ["none", "xl:active:max-w-none"],
                ["xl", "xl:active:max-w-xl"],
                ["sm", "xl:active:max-w-sm"],
                ["md", "xl:active:max-w-md"],
                ["lg", "xl:active:max-w-lg"],
                ["xl", "xl:active:max-w-xl"],
                ["2xl", "xl:active:max-w-2xl"],
                ["3xl", "xl:active:max-w-3xl"],
                ["4xl", "xl:active:max-w-4xl"],
                ["5xl", "xl:active:max-w-5xl"],
                ["6xl", "xl:active:max-w-6xl"],
                ["7xl", "xl:active:max-w-7xl"],
                ["full", "xl:active:max-w-full"],
                ["min", "xl:active:max-w-min"],
                ["max", "xl:active:max-w-max"],
                ["fit", "xl:active:max-w-fit"],
                ["prose", "xl:active:max-w-prose"],
                ["screen-xl", "xl:active:max-w-screen-xl"],
                ["screen-sm", "xl:active:max-w-screen-sm"],
                ["screen-md", "xl:active:max-w-screen-md"],
                ["screen-lg", "xl:active:max-w-screen-lg"],
                ["screen-xl", "xl:active:max-w-screen-xl"],
                ["screen-2xl", "xl:active:max-w-screen-2xl"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexMaxWidth, string>>([
            [
              "xs",
              new Map<FlexMaxWidth, string>([
                [0, "xs:disabled:max-w-0"],
                ["px", "xs:disabled:max-w-px"],
                [0.5, "xs:disabled:max-w-0.5"],
                [1, "xs:disabled:max-w-1"],
                [1.5, "xs:disabled:max-w-1.5"],
                [2, "xs:disabled:max-w-2"],
                [2.5, "xs:disabled:max-w-2.5"],
                [3, "xs:disabled:max-w-3"],
                [3.5, "xs:disabled:max-w-3.5"],
                [4, "xs:disabled:max-w-4"],
                [5, "xs:disabled:max-w-5"],
                [6, "xs:disabled:max-w-6"],
                [7, "xs:disabled:max-w-7"],
                [8, "xs:disabled:max-w-8"],
                [9, "xs:disabled:max-w-9"],
                [10, "xs:disabled:max-w-10"],
                [11, "xs:disabled:max-w-11"],
                [12, "xs:disabled:max-w-12"],
                [14, "xs:disabled:max-w-14"],
                [16, "xs:disabled:max-w-16"],
                [20, "xs:disabled:max-w-20"],
                [24, "xs:disabled:max-w-24"],
                [28, "xs:disabled:max-w-28"],
                [32, "xs:disabled:max-w-32"],
                [36, "xs:disabled:max-w-36"],
                [40, "xs:disabled:max-w-40"],
                [44, "xs:disabled:max-w-44"],
                [48, "xs:disabled:max-w-48"],
                [52, "xs:disabled:max-w-52"],
                [56, "xs:disabled:max-w-56"],
                [60, "xs:disabled:max-w-60"],
                [64, "xs:disabled:max-w-64"],
                [72, "xs:disabled:max-w-72"],
                [80, "xs:disabled:max-w-80"],
                [96, "xs:disabled:max-w-96"],
                ["none", "xs:disabled:max-w-none"],
                ["xs", "xs:disabled:max-w-xs"],
                ["sm", "xs:disabled:max-w-sm"],
                ["md", "xs:disabled:max-w-md"],
                ["lg", "xs:disabled:max-w-lg"],
                ["xl", "xs:disabled:max-w-xl"],
                ["2xl", "xs:disabled:max-w-2xl"],
                ["3xl", "xs:disabled:max-w-3xl"],
                ["4xl", "xs:disabled:max-w-4xl"],
                ["5xl", "xs:disabled:max-w-5xl"],
                ["6xl", "xs:disabled:max-w-6xl"],
                ["7xl", "xs:disabled:max-w-7xl"],
                ["full", "xs:disabled:max-w-full"],
                ["min", "xs:disabled:max-w-min"],
                ["max", "xs:disabled:max-w-max"],
                ["fit", "xs:disabled:max-w-fit"],
                ["prose", "xs:disabled:max-w-prose"],
                ["screen-xs", "xs:disabled:max-w-screen-xs"],
                ["screen-sm", "xs:disabled:max-w-screen-sm"],
                ["screen-md", "xs:disabled:max-w-screen-md"],
                ["screen-lg", "xs:disabled:max-w-screen-lg"],
                ["screen-xl", "xs:disabled:max-w-screen-xl"],
                ["screen-2xl", "xs:disabled:max-w-screen-2xl"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxWidth, string>([
                [0, "sm:disabled:max-w-0"],
                ["px", "sm:disabled:max-w-px"],
                [0.5, "sm:disabled:max-w-0.5"],
                [1, "sm:disabled:max-w-1"],
                [1.5, "sm:disabled:max-w-1.5"],
                [2, "sm:disabled:max-w-2"],
                [2.5, "sm:disabled:max-w-2.5"],
                [3, "sm:disabled:max-w-3"],
                [3.5, "sm:disabled:max-w-3.5"],
                [4, "sm:disabled:max-w-4"],
                [5, "sm:disabled:max-w-5"],
                [6, "sm:disabled:max-w-6"],
                [7, "sm:disabled:max-w-7"],
                [8, "sm:disabled:max-w-8"],
                [9, "sm:disabled:max-w-9"],
                [10, "sm:disabled:max-w-10"],
                [11, "sm:disabled:max-w-11"],
                [12, "sm:disabled:max-w-12"],
                [14, "sm:disabled:max-w-14"],
                [16, "sm:disabled:max-w-16"],
                [20, "sm:disabled:max-w-20"],
                [24, "sm:disabled:max-w-24"],
                [28, "sm:disabled:max-w-28"],
                [32, "sm:disabled:max-w-32"],
                [36, "sm:disabled:max-w-36"],
                [40, "sm:disabled:max-w-40"],
                [44, "sm:disabled:max-w-44"],
                [48, "sm:disabled:max-w-48"],
                [52, "sm:disabled:max-w-52"],
                [56, "sm:disabled:max-w-56"],
                [60, "sm:disabled:max-w-60"],
                [64, "sm:disabled:max-w-64"],
                [72, "sm:disabled:max-w-72"],
                [80, "sm:disabled:max-w-80"],
                [96, "sm:disabled:max-w-96"],
                ["none", "sm:disabled:max-w-none"],
                ["sm", "sm:disabled:max-w-sm"],
                ["sm", "sm:disabled:max-w-sm"],
                ["md", "sm:disabled:max-w-md"],
                ["lg", "sm:disabled:max-w-lg"],
                ["xl", "sm:disabled:max-w-xl"],
                ["2xl", "sm:disabled:max-w-2xl"],
                ["3xl", "sm:disabled:max-w-3xl"],
                ["4xl", "sm:disabled:max-w-4xl"],
                ["5xl", "sm:disabled:max-w-5xl"],
                ["6xl", "sm:disabled:max-w-6xl"],
                ["7xl", "sm:disabled:max-w-7xl"],
                ["full", "sm:disabled:max-w-full"],
                ["min", "sm:disabled:max-w-min"],
                ["max", "sm:disabled:max-w-max"],
                ["fit", "sm:disabled:max-w-fit"],
                ["prose", "sm:disabled:max-w-prose"],
                ["screen-sm", "sm:disabled:max-w-screen-sm"],
                ["screen-sm", "sm:disabled:max-w-screen-sm"],
                ["screen-md", "sm:disabled:max-w-screen-md"],
                ["screen-lg", "sm:disabled:max-w-screen-lg"],
                ["screen-xl", "sm:disabled:max-w-screen-xl"],
                ["screen-2xl", "sm:disabled:max-w-screen-2xl"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxWidth, string>([
                [0, "md:disabled:max-w-0"],
                ["px", "md:disabled:max-w-px"],
                [0.5, "md:disabled:max-w-0.5"],
                [1, "md:disabled:max-w-1"],
                [1.5, "md:disabled:max-w-1.5"],
                [2, "md:disabled:max-w-2"],
                [2.5, "md:disabled:max-w-2.5"],
                [3, "md:disabled:max-w-3"],
                [3.5, "md:disabled:max-w-3.5"],
                [4, "md:disabled:max-w-4"],
                [5, "md:disabled:max-w-5"],
                [6, "md:disabled:max-w-6"],
                [7, "md:disabled:max-w-7"],
                [8, "md:disabled:max-w-8"],
                [9, "md:disabled:max-w-9"],
                [10, "md:disabled:max-w-10"],
                [11, "md:disabled:max-w-11"],
                [12, "md:disabled:max-w-12"],
                [14, "md:disabled:max-w-14"],
                [16, "md:disabled:max-w-16"],
                [20, "md:disabled:max-w-20"],
                [24, "md:disabled:max-w-24"],
                [28, "md:disabled:max-w-28"],
                [32, "md:disabled:max-w-32"],
                [36, "md:disabled:max-w-36"],
                [40, "md:disabled:max-w-40"],
                [44, "md:disabled:max-w-44"],
                [48, "md:disabled:max-w-48"],
                [52, "md:disabled:max-w-52"],
                [56, "md:disabled:max-w-56"],
                [60, "md:disabled:max-w-60"],
                [64, "md:disabled:max-w-64"],
                [72, "md:disabled:max-w-72"],
                [80, "md:disabled:max-w-80"],
                [96, "md:disabled:max-w-96"],
                ["none", "md:disabled:max-w-none"],
                ["md", "md:disabled:max-w-md"],
                ["sm", "md:disabled:max-w-sm"],
                ["md", "md:disabled:max-w-md"],
                ["lg", "md:disabled:max-w-lg"],
                ["xl", "md:disabled:max-w-xl"],
                ["2xl", "md:disabled:max-w-2xl"],
                ["3xl", "md:disabled:max-w-3xl"],
                ["4xl", "md:disabled:max-w-4xl"],
                ["5xl", "md:disabled:max-w-5xl"],
                ["6xl", "md:disabled:max-w-6xl"],
                ["7xl", "md:disabled:max-w-7xl"],
                ["full", "md:disabled:max-w-full"],
                ["min", "md:disabled:max-w-min"],
                ["max", "md:disabled:max-w-max"],
                ["fit", "md:disabled:max-w-fit"],
                ["prose", "md:disabled:max-w-prose"],
                ["screen-md", "md:disabled:max-w-screen-md"],
                ["screen-sm", "md:disabled:max-w-screen-sm"],
                ["screen-md", "md:disabled:max-w-screen-md"],
                ["screen-lg", "md:disabled:max-w-screen-lg"],
                ["screen-xl", "md:disabled:max-w-screen-xl"],
                ["screen-2xl", "md:disabled:max-w-screen-2xl"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxWidth, string>([
                [0, "lg:disabled:max-w-0"],
                ["px", "lg:disabled:max-w-px"],
                [0.5, "lg:disabled:max-w-0.5"],
                [1, "lg:disabled:max-w-1"],
                [1.5, "lg:disabled:max-w-1.5"],
                [2, "lg:disabled:max-w-2"],
                [2.5, "lg:disabled:max-w-2.5"],
                [3, "lg:disabled:max-w-3"],
                [3.5, "lg:disabled:max-w-3.5"],
                [4, "lg:disabled:max-w-4"],
                [5, "lg:disabled:max-w-5"],
                [6, "lg:disabled:max-w-6"],
                [7, "lg:disabled:max-w-7"],
                [8, "lg:disabled:max-w-8"],
                [9, "lg:disabled:max-w-9"],
                [10, "lg:disabled:max-w-10"],
                [11, "lg:disabled:max-w-11"],
                [12, "lg:disabled:max-w-12"],
                [14, "lg:disabled:max-w-14"],
                [16, "lg:disabled:max-w-16"],
                [20, "lg:disabled:max-w-20"],
                [24, "lg:disabled:max-w-24"],
                [28, "lg:disabled:max-w-28"],
                [32, "lg:disabled:max-w-32"],
                [36, "lg:disabled:max-w-36"],
                [40, "lg:disabled:max-w-40"],
                [44, "lg:disabled:max-w-44"],
                [48, "lg:disabled:max-w-48"],
                [52, "lg:disabled:max-w-52"],
                [56, "lg:disabled:max-w-56"],
                [60, "lg:disabled:max-w-60"],
                [64, "lg:disabled:max-w-64"],
                [72, "lg:disabled:max-w-72"],
                [80, "lg:disabled:max-w-80"],
                [96, "lg:disabled:max-w-96"],
                ["none", "lg:disabled:max-w-none"],
                ["lg", "lg:disabled:max-w-lg"],
                ["sm", "lg:disabled:max-w-sm"],
                ["md", "lg:disabled:max-w-md"],
                ["lg", "lg:disabled:max-w-lg"],
                ["xl", "lg:disabled:max-w-xl"],
                ["2xl", "lg:disabled:max-w-2xl"],
                ["3xl", "lg:disabled:max-w-3xl"],
                ["4xl", "lg:disabled:max-w-4xl"],
                ["5xl", "lg:disabled:max-w-5xl"],
                ["6xl", "lg:disabled:max-w-6xl"],
                ["7xl", "lg:disabled:max-w-7xl"],
                ["full", "lg:disabled:max-w-full"],
                ["min", "lg:disabled:max-w-min"],
                ["max", "lg:disabled:max-w-max"],
                ["fit", "lg:disabled:max-w-fit"],
                ["prose", "lg:disabled:max-w-prose"],
                ["screen-lg", "lg:disabled:max-w-screen-lg"],
                ["screen-sm", "lg:disabled:max-w-screen-sm"],
                ["screen-md", "lg:disabled:max-w-screen-md"],
                ["screen-lg", "lg:disabled:max-w-screen-lg"],
                ["screen-xl", "lg:disabled:max-w-screen-xl"],
                ["screen-2xl", "lg:disabled:max-w-screen-2xl"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxWidth, string>([
                [0, "xl:disabled:max-w-0"],
                ["px", "xl:disabled:max-w-px"],
                [0.5, "xl:disabled:max-w-0.5"],
                [1, "xl:disabled:max-w-1"],
                [1.5, "xl:disabled:max-w-1.5"],
                [2, "xl:disabled:max-w-2"],
                [2.5, "xl:disabled:max-w-2.5"],
                [3, "xl:disabled:max-w-3"],
                [3.5, "xl:disabled:max-w-3.5"],
                [4, "xl:disabled:max-w-4"],
                [5, "xl:disabled:max-w-5"],
                [6, "xl:disabled:max-w-6"],
                [7, "xl:disabled:max-w-7"],
                [8, "xl:disabled:max-w-8"],
                [9, "xl:disabled:max-w-9"],
                [10, "xl:disabled:max-w-10"],
                [11, "xl:disabled:max-w-11"],
                [12, "xl:disabled:max-w-12"],
                [14, "xl:disabled:max-w-14"],
                [16, "xl:disabled:max-w-16"],
                [20, "xl:disabled:max-w-20"],
                [24, "xl:disabled:max-w-24"],
                [28, "xl:disabled:max-w-28"],
                [32, "xl:disabled:max-w-32"],
                [36, "xl:disabled:max-w-36"],
                [40, "xl:disabled:max-w-40"],
                [44, "xl:disabled:max-w-44"],
                [48, "xl:disabled:max-w-48"],
                [52, "xl:disabled:max-w-52"],
                [56, "xl:disabled:max-w-56"],
                [60, "xl:disabled:max-w-60"],
                [64, "xl:disabled:max-w-64"],
                [72, "xl:disabled:max-w-72"],
                [80, "xl:disabled:max-w-80"],
                [96, "xl:disabled:max-w-96"],
                ["none", "xl:disabled:max-w-none"],
                ["xl", "xl:disabled:max-w-xl"],
                ["sm", "xl:disabled:max-w-sm"],
                ["md", "xl:disabled:max-w-md"],
                ["lg", "xl:disabled:max-w-lg"],
                ["xl", "xl:disabled:max-w-xl"],
                ["2xl", "xl:disabled:max-w-2xl"],
                ["3xl", "xl:disabled:max-w-3xl"],
                ["4xl", "xl:disabled:max-w-4xl"],
                ["5xl", "xl:disabled:max-w-5xl"],
                ["6xl", "xl:disabled:max-w-6xl"],
                ["7xl", "xl:disabled:max-w-7xl"],
                ["full", "xl:disabled:max-w-full"],
                ["min", "xl:disabled:max-w-min"],
                ["max", "xl:disabled:max-w-max"],
                ["fit", "xl:disabled:max-w-fit"],
                ["prose", "xl:disabled:max-w-prose"],
                ["screen-xl", "xl:disabled:max-w-screen-xl"],
                ["screen-sm", "xl:disabled:max-w-screen-sm"],
                ["screen-md", "xl:disabled:max-w-screen-md"],
                ["screen-lg", "xl:disabled:max-w-screen-lg"],
                ["screen-xl", "xl:disabled:max-w-screen-xl"],
                ["screen-2xl", "xl:disabled:max-w-screen-2xl"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexMaxWidth, string>>([
            [
              "xs",
              new Map<FlexMaxWidth, string>([
                [0, "xs:hover:max-w-0"],
                ["px", "xs:hover:max-w-px"],
                [0.5, "xs:hover:max-w-0.5"],
                [1, "xs:hover:max-w-1"],
                [1.5, "xs:hover:max-w-1.5"],
                [2, "xs:hover:max-w-2"],
                [2.5, "xs:hover:max-w-2.5"],
                [3, "xs:hover:max-w-3"],
                [3.5, "xs:hover:max-w-3.5"],
                [4, "xs:hover:max-w-4"],
                [5, "xs:hover:max-w-5"],
                [6, "xs:hover:max-w-6"],
                [7, "xs:hover:max-w-7"],
                [8, "xs:hover:max-w-8"],
                [9, "xs:hover:max-w-9"],
                [10, "xs:hover:max-w-10"],
                [11, "xs:hover:max-w-11"],
                [12, "xs:hover:max-w-12"],
                [14, "xs:hover:max-w-14"],
                [16, "xs:hover:max-w-16"],
                [20, "xs:hover:max-w-20"],
                [24, "xs:hover:max-w-24"],
                [28, "xs:hover:max-w-28"],
                [32, "xs:hover:max-w-32"],
                [36, "xs:hover:max-w-36"],
                [40, "xs:hover:max-w-40"],
                [44, "xs:hover:max-w-44"],
                [48, "xs:hover:max-w-48"],
                [52, "xs:hover:max-w-52"],
                [56, "xs:hover:max-w-56"],
                [60, "xs:hover:max-w-60"],
                [64, "xs:hover:max-w-64"],
                [72, "xs:hover:max-w-72"],
                [80, "xs:hover:max-w-80"],
                [96, "xs:hover:max-w-96"],
                ["none", "xs:hover:max-w-none"],
                ["xs", "xs:hover:max-w-xs"],
                ["sm", "xs:hover:max-w-sm"],
                ["md", "xs:hover:max-w-md"],
                ["lg", "xs:hover:max-w-lg"],
                ["xl", "xs:hover:max-w-xl"],
                ["2xl", "xs:hover:max-w-2xl"],
                ["3xl", "xs:hover:max-w-3xl"],
                ["4xl", "xs:hover:max-w-4xl"],
                ["5xl", "xs:hover:max-w-5xl"],
                ["6xl", "xs:hover:max-w-6xl"],
                ["7xl", "xs:hover:max-w-7xl"],
                ["full", "xs:hover:max-w-full"],
                ["min", "xs:hover:max-w-min"],
                ["max", "xs:hover:max-w-max"],
                ["fit", "xs:hover:max-w-fit"],
                ["prose", "xs:hover:max-w-prose"],
                ["screen-xs", "xs:hover:max-w-screen-xs"],
                ["screen-sm", "xs:hover:max-w-screen-sm"],
                ["screen-md", "xs:hover:max-w-screen-md"],
                ["screen-lg", "xs:hover:max-w-screen-lg"],
                ["screen-xl", "xs:hover:max-w-screen-xl"],
                ["screen-2xl", "xs:hover:max-w-screen-2xl"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxWidth, string>([
                [0, "sm:hover:max-w-0"],
                ["px", "sm:hover:max-w-px"],
                [0.5, "sm:hover:max-w-0.5"],
                [1, "sm:hover:max-w-1"],
                [1.5, "sm:hover:max-w-1.5"],
                [2, "sm:hover:max-w-2"],
                [2.5, "sm:hover:max-w-2.5"],
                [3, "sm:hover:max-w-3"],
                [3.5, "sm:hover:max-w-3.5"],
                [4, "sm:hover:max-w-4"],
                [5, "sm:hover:max-w-5"],
                [6, "sm:hover:max-w-6"],
                [7, "sm:hover:max-w-7"],
                [8, "sm:hover:max-w-8"],
                [9, "sm:hover:max-w-9"],
                [10, "sm:hover:max-w-10"],
                [11, "sm:hover:max-w-11"],
                [12, "sm:hover:max-w-12"],
                [14, "sm:hover:max-w-14"],
                [16, "sm:hover:max-w-16"],
                [20, "sm:hover:max-w-20"],
                [24, "sm:hover:max-w-24"],
                [28, "sm:hover:max-w-28"],
                [32, "sm:hover:max-w-32"],
                [36, "sm:hover:max-w-36"],
                [40, "sm:hover:max-w-40"],
                [44, "sm:hover:max-w-44"],
                [48, "sm:hover:max-w-48"],
                [52, "sm:hover:max-w-52"],
                [56, "sm:hover:max-w-56"],
                [60, "sm:hover:max-w-60"],
                [64, "sm:hover:max-w-64"],
                [72, "sm:hover:max-w-72"],
                [80, "sm:hover:max-w-80"],
                [96, "sm:hover:max-w-96"],
                ["none", "sm:hover:max-w-none"],
                ["sm", "sm:hover:max-w-sm"],
                ["sm", "sm:hover:max-w-sm"],
                ["md", "sm:hover:max-w-md"],
                ["lg", "sm:hover:max-w-lg"],
                ["xl", "sm:hover:max-w-xl"],
                ["2xl", "sm:hover:max-w-2xl"],
                ["3xl", "sm:hover:max-w-3xl"],
                ["4xl", "sm:hover:max-w-4xl"],
                ["5xl", "sm:hover:max-w-5xl"],
                ["6xl", "sm:hover:max-w-6xl"],
                ["7xl", "sm:hover:max-w-7xl"],
                ["full", "sm:hover:max-w-full"],
                ["min", "sm:hover:max-w-min"],
                ["max", "sm:hover:max-w-max"],
                ["fit", "sm:hover:max-w-fit"],
                ["prose", "sm:hover:max-w-prose"],
                ["screen-sm", "sm:hover:max-w-screen-sm"],
                ["screen-sm", "sm:hover:max-w-screen-sm"],
                ["screen-md", "sm:hover:max-w-screen-md"],
                ["screen-lg", "sm:hover:max-w-screen-lg"],
                ["screen-xl", "sm:hover:max-w-screen-xl"],
                ["screen-2xl", "sm:hover:max-w-screen-2xl"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxWidth, string>([
                [0, "md:hover:max-w-0"],
                ["px", "md:hover:max-w-px"],
                [0.5, "md:hover:max-w-0.5"],
                [1, "md:hover:max-w-1"],
                [1.5, "md:hover:max-w-1.5"],
                [2, "md:hover:max-w-2"],
                [2.5, "md:hover:max-w-2.5"],
                [3, "md:hover:max-w-3"],
                [3.5, "md:hover:max-w-3.5"],
                [4, "md:hover:max-w-4"],
                [5, "md:hover:max-w-5"],
                [6, "md:hover:max-w-6"],
                [7, "md:hover:max-w-7"],
                [8, "md:hover:max-w-8"],
                [9, "md:hover:max-w-9"],
                [10, "md:hover:max-w-10"],
                [11, "md:hover:max-w-11"],
                [12, "md:hover:max-w-12"],
                [14, "md:hover:max-w-14"],
                [16, "md:hover:max-w-16"],
                [20, "md:hover:max-w-20"],
                [24, "md:hover:max-w-24"],
                [28, "md:hover:max-w-28"],
                [32, "md:hover:max-w-32"],
                [36, "md:hover:max-w-36"],
                [40, "md:hover:max-w-40"],
                [44, "md:hover:max-w-44"],
                [48, "md:hover:max-w-48"],
                [52, "md:hover:max-w-52"],
                [56, "md:hover:max-w-56"],
                [60, "md:hover:max-w-60"],
                [64, "md:hover:max-w-64"],
                [72, "md:hover:max-w-72"],
                [80, "md:hover:max-w-80"],
                [96, "md:hover:max-w-96"],
                ["none", "md:hover:max-w-none"],
                ["md", "md:hover:max-w-md"],
                ["sm", "md:hover:max-w-sm"],
                ["md", "md:hover:max-w-md"],
                ["lg", "md:hover:max-w-lg"],
                ["xl", "md:hover:max-w-xl"],
                ["2xl", "md:hover:max-w-2xl"],
                ["3xl", "md:hover:max-w-3xl"],
                ["4xl", "md:hover:max-w-4xl"],
                ["5xl", "md:hover:max-w-5xl"],
                ["6xl", "md:hover:max-w-6xl"],
                ["7xl", "md:hover:max-w-7xl"],
                ["full", "md:hover:max-w-full"],
                ["min", "md:hover:max-w-min"],
                ["max", "md:hover:max-w-max"],
                ["fit", "md:hover:max-w-fit"],
                ["prose", "md:hover:max-w-prose"],
                ["screen-md", "md:hover:max-w-screen-md"],
                ["screen-sm", "md:hover:max-w-screen-sm"],
                ["screen-md", "md:hover:max-w-screen-md"],
                ["screen-lg", "md:hover:max-w-screen-lg"],
                ["screen-xl", "md:hover:max-w-screen-xl"],
                ["screen-2xl", "md:hover:max-w-screen-2xl"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxWidth, string>([
                [0, "lg:hover:max-w-0"],
                ["px", "lg:hover:max-w-px"],
                [0.5, "lg:hover:max-w-0.5"],
                [1, "lg:hover:max-w-1"],
                [1.5, "lg:hover:max-w-1.5"],
                [2, "lg:hover:max-w-2"],
                [2.5, "lg:hover:max-w-2.5"],
                [3, "lg:hover:max-w-3"],
                [3.5, "lg:hover:max-w-3.5"],
                [4, "lg:hover:max-w-4"],
                [5, "lg:hover:max-w-5"],
                [6, "lg:hover:max-w-6"],
                [7, "lg:hover:max-w-7"],
                [8, "lg:hover:max-w-8"],
                [9, "lg:hover:max-w-9"],
                [10, "lg:hover:max-w-10"],
                [11, "lg:hover:max-w-11"],
                [12, "lg:hover:max-w-12"],
                [14, "lg:hover:max-w-14"],
                [16, "lg:hover:max-w-16"],
                [20, "lg:hover:max-w-20"],
                [24, "lg:hover:max-w-24"],
                [28, "lg:hover:max-w-28"],
                [32, "lg:hover:max-w-32"],
                [36, "lg:hover:max-w-36"],
                [40, "lg:hover:max-w-40"],
                [44, "lg:hover:max-w-44"],
                [48, "lg:hover:max-w-48"],
                [52, "lg:hover:max-w-52"],
                [56, "lg:hover:max-w-56"],
                [60, "lg:hover:max-w-60"],
                [64, "lg:hover:max-w-64"],
                [72, "lg:hover:max-w-72"],
                [80, "lg:hover:max-w-80"],
                [96, "lg:hover:max-w-96"],
                ["none", "lg:hover:max-w-none"],
                ["lg", "lg:hover:max-w-lg"],
                ["sm", "lg:hover:max-w-sm"],
                ["md", "lg:hover:max-w-md"],
                ["lg", "lg:hover:max-w-lg"],
                ["xl", "lg:hover:max-w-xl"],
                ["2xl", "lg:hover:max-w-2xl"],
                ["3xl", "lg:hover:max-w-3xl"],
                ["4xl", "lg:hover:max-w-4xl"],
                ["5xl", "lg:hover:max-w-5xl"],
                ["6xl", "lg:hover:max-w-6xl"],
                ["7xl", "lg:hover:max-w-7xl"],
                ["full", "lg:hover:max-w-full"],
                ["min", "lg:hover:max-w-min"],
                ["max", "lg:hover:max-w-max"],
                ["fit", "lg:hover:max-w-fit"],
                ["prose", "lg:hover:max-w-prose"],
                ["screen-lg", "lg:hover:max-w-screen-lg"],
                ["screen-sm", "lg:hover:max-w-screen-sm"],
                ["screen-md", "lg:hover:max-w-screen-md"],
                ["screen-lg", "lg:hover:max-w-screen-lg"],
                ["screen-xl", "lg:hover:max-w-screen-xl"],
                ["screen-2xl", "lg:hover:max-w-screen-2xl"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxWidth, string>([
                [0, "xl:hover:max-w-0"],
                ["px", "xl:hover:max-w-px"],
                [0.5, "xl:hover:max-w-0.5"],
                [1, "xl:hover:max-w-1"],
                [1.5, "xl:hover:max-w-1.5"],
                [2, "xl:hover:max-w-2"],
                [2.5, "xl:hover:max-w-2.5"],
                [3, "xl:hover:max-w-3"],
                [3.5, "xl:hover:max-w-3.5"],
                [4, "xl:hover:max-w-4"],
                [5, "xl:hover:max-w-5"],
                [6, "xl:hover:max-w-6"],
                [7, "xl:hover:max-w-7"],
                [8, "xl:hover:max-w-8"],
                [9, "xl:hover:max-w-9"],
                [10, "xl:hover:max-w-10"],
                [11, "xl:hover:max-w-11"],
                [12, "xl:hover:max-w-12"],
                [14, "xl:hover:max-w-14"],
                [16, "xl:hover:max-w-16"],
                [20, "xl:hover:max-w-20"],
                [24, "xl:hover:max-w-24"],
                [28, "xl:hover:max-w-28"],
                [32, "xl:hover:max-w-32"],
                [36, "xl:hover:max-w-36"],
                [40, "xl:hover:max-w-40"],
                [44, "xl:hover:max-w-44"],
                [48, "xl:hover:max-w-48"],
                [52, "xl:hover:max-w-52"],
                [56, "xl:hover:max-w-56"],
                [60, "xl:hover:max-w-60"],
                [64, "xl:hover:max-w-64"],
                [72, "xl:hover:max-w-72"],
                [80, "xl:hover:max-w-80"],
                [96, "xl:hover:max-w-96"],
                ["none", "xl:hover:max-w-none"],
                ["xl", "xl:hover:max-w-xl"],
                ["sm", "xl:hover:max-w-sm"],
                ["md", "xl:hover:max-w-md"],
                ["lg", "xl:hover:max-w-lg"],
                ["xl", "xl:hover:max-w-xl"],
                ["2xl", "xl:hover:max-w-2xl"],
                ["3xl", "xl:hover:max-w-3xl"],
                ["4xl", "xl:hover:max-w-4xl"],
                ["5xl", "xl:hover:max-w-5xl"],
                ["6xl", "xl:hover:max-w-6xl"],
                ["7xl", "xl:hover:max-w-7xl"],
                ["full", "xl:hover:max-w-full"],
                ["min", "xl:hover:max-w-min"],
                ["max", "xl:hover:max-w-max"],
                ["fit", "xl:hover:max-w-fit"],
                ["prose", "xl:hover:max-w-prose"],
                ["screen-xl", "xl:hover:max-w-screen-xl"],
                ["screen-sm", "xl:hover:max-w-screen-sm"],
                ["screen-md", "xl:hover:max-w-screen-md"],
                ["screen-lg", "xl:hover:max-w-screen-lg"],
                ["screen-xl", "xl:hover:max-w-screen-xl"],
                ["screen-2xl", "xl:hover:max-w-screen-2xl"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexMaxWidth, string>>([
            [
              "xs",
              new Map<FlexMaxWidth, string>([
                [0, "xs:max-w-0"],
                ["px", "xs:max-w-px"],
                [0.5, "xs:max-w-0.5"],
                [1, "xs:max-w-1"],
                [1.5, "xs:max-w-1.5"],
                [2, "xs:max-w-2"],
                [2.5, "xs:max-w-2.5"],
                [3, "xs:max-w-3"],
                [3.5, "xs:max-w-3.5"],
                [4, "xs:max-w-4"],
                [5, "xs:max-w-5"],
                [6, "xs:max-w-6"],
                [7, "xs:max-w-7"],
                [8, "xs:max-w-8"],
                [9, "xs:max-w-9"],
                [10, "xs:max-w-10"],
                [11, "xs:max-w-11"],
                [12, "xs:max-w-12"],
                [14, "xs:max-w-14"],
                [16, "xs:max-w-16"],
                [20, "xs:max-w-20"],
                [24, "xs:max-w-24"],
                [28, "xs:max-w-28"],
                [32, "xs:max-w-32"],
                [36, "xs:max-w-36"],
                [40, "xs:max-w-40"],
                [44, "xs:max-w-44"],
                [48, "xs:max-w-48"],
                [52, "xs:max-w-52"],
                [56, "xs:max-w-56"],
                [60, "xs:max-w-60"],
                [64, "xs:max-w-64"],
                [72, "xs:max-w-72"],
                [80, "xs:max-w-80"],
                [96, "xs:max-w-96"],
                ["none", "xs:max-w-none"],
                ["xs", "xs:max-w-xs"],
                ["sm", "xs:max-w-sm"],
                ["md", "xs:max-w-md"],
                ["lg", "xs:max-w-lg"],
                ["xl", "xs:max-w-xl"],
                ["2xl", "xs:max-w-2xl"],
                ["3xl", "xs:max-w-3xl"],
                ["4xl", "xs:max-w-4xl"],
                ["5xl", "xs:max-w-5xl"],
                ["6xl", "xs:max-w-6xl"],
                ["7xl", "xs:max-w-7xl"],
                ["full", "xs:max-w-full"],
                ["min", "xs:max-w-min"],
                ["max", "xs:max-w-max"],
                ["fit", "xs:max-w-fit"],
                ["prose", "xs:max-w-prose"],
                ["screen-xs", "xs:max-w-screen-xs"],
                ["screen-sm", "xs:max-w-screen-sm"],
                ["screen-md", "xs:max-w-screen-md"],
                ["screen-lg", "xs:max-w-screen-lg"],
                ["screen-xl", "xs:max-w-screen-xl"],
                ["screen-2xl", "xs:max-w-screen-2xl"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxWidth, string>([
                [0, "sm:max-w-0"],
                ["px", "sm:max-w-px"],
                [0.5, "sm:max-w-0.5"],
                [1, "sm:max-w-1"],
                [1.5, "sm:max-w-1.5"],
                [2, "sm:max-w-2"],
                [2.5, "sm:max-w-2.5"],
                [3, "sm:max-w-3"],
                [3.5, "sm:max-w-3.5"],
                [4, "sm:max-w-4"],
                [5, "sm:max-w-5"],
                [6, "sm:max-w-6"],
                [7, "sm:max-w-7"],
                [8, "sm:max-w-8"],
                [9, "sm:max-w-9"],
                [10, "sm:max-w-10"],
                [11, "sm:max-w-11"],
                [12, "sm:max-w-12"],
                [14, "sm:max-w-14"],
                [16, "sm:max-w-16"],
                [20, "sm:max-w-20"],
                [24, "sm:max-w-24"],
                [28, "sm:max-w-28"],
                [32, "sm:max-w-32"],
                [36, "sm:max-w-36"],
                [40, "sm:max-w-40"],
                [44, "sm:max-w-44"],
                [48, "sm:max-w-48"],
                [52, "sm:max-w-52"],
                [56, "sm:max-w-56"],
                [60, "sm:max-w-60"],
                [64, "sm:max-w-64"],
                [72, "sm:max-w-72"],
                [80, "sm:max-w-80"],
                [96, "sm:max-w-96"],
                ["none", "sm:max-w-none"],
                ["sm", "sm:max-w-sm"],
                ["sm", "sm:max-w-sm"],
                ["md", "sm:max-w-md"],
                ["lg", "sm:max-w-lg"],
                ["xl", "sm:max-w-xl"],
                ["2xl", "sm:max-w-2xl"],
                ["3xl", "sm:max-w-3xl"],
                ["4xl", "sm:max-w-4xl"],
                ["5xl", "sm:max-w-5xl"],
                ["6xl", "sm:max-w-6xl"],
                ["7xl", "sm:max-w-7xl"],
                ["full", "sm:max-w-full"],
                ["min", "sm:max-w-min"],
                ["max", "sm:max-w-max"],
                ["fit", "sm:max-w-fit"],
                ["prose", "sm:max-w-prose"],
                ["screen-sm", "sm:max-w-screen-sm"],
                ["screen-sm", "sm:max-w-screen-sm"],
                ["screen-md", "sm:max-w-screen-md"],
                ["screen-lg", "sm:max-w-screen-lg"],
                ["screen-xl", "sm:max-w-screen-xl"],
                ["screen-2xl", "sm:max-w-screen-2xl"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxWidth, string>([
                [0, "md:max-w-0"],
                ["px", "md:max-w-px"],
                [0.5, "md:max-w-0.5"],
                [1, "md:max-w-1"],
                [1.5, "md:max-w-1.5"],
                [2, "md:max-w-2"],
                [2.5, "md:max-w-2.5"],
                [3, "md:max-w-3"],
                [3.5, "md:max-w-3.5"],
                [4, "md:max-w-4"],
                [5, "md:max-w-5"],
                [6, "md:max-w-6"],
                [7, "md:max-w-7"],
                [8, "md:max-w-8"],
                [9, "md:max-w-9"],
                [10, "md:max-w-10"],
                [11, "md:max-w-11"],
                [12, "md:max-w-12"],
                [14, "md:max-w-14"],
                [16, "md:max-w-16"],
                [20, "md:max-w-20"],
                [24, "md:max-w-24"],
                [28, "md:max-w-28"],
                [32, "md:max-w-32"],
                [36, "md:max-w-36"],
                [40, "md:max-w-40"],
                [44, "md:max-w-44"],
                [48, "md:max-w-48"],
                [52, "md:max-w-52"],
                [56, "md:max-w-56"],
                [60, "md:max-w-60"],
                [64, "md:max-w-64"],
                [72, "md:max-w-72"],
                [80, "md:max-w-80"],
                [96, "md:max-w-96"],
                ["none", "md:max-w-none"],
                ["md", "md:max-w-md"],
                ["sm", "md:max-w-sm"],
                ["md", "md:max-w-md"],
                ["lg", "md:max-w-lg"],
                ["xl", "md:max-w-xl"],
                ["2xl", "md:max-w-2xl"],
                ["3xl", "md:max-w-3xl"],
                ["4xl", "md:max-w-4xl"],
                ["5xl", "md:max-w-5xl"],
                ["6xl", "md:max-w-6xl"],
                ["7xl", "md:max-w-7xl"],
                ["full", "md:max-w-full"],
                ["min", "md:max-w-min"],
                ["max", "md:max-w-max"],
                ["fit", "md:max-w-fit"],
                ["prose", "md:max-w-prose"],
                ["screen-md", "md:max-w-screen-md"],
                ["screen-sm", "md:max-w-screen-sm"],
                ["screen-md", "md:max-w-screen-md"],
                ["screen-lg", "md:max-w-screen-lg"],
                ["screen-xl", "md:max-w-screen-xl"],
                ["screen-2xl", "md:max-w-screen-2xl"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxWidth, string>([
                [0, "lg:max-w-0"],
                ["px", "lg:max-w-px"],
                [0.5, "lg:max-w-0.5"],
                [1, "lg:max-w-1"],
                [1.5, "lg:max-w-1.5"],
                [2, "lg:max-w-2"],
                [2.5, "lg:max-w-2.5"],
                [3, "lg:max-w-3"],
                [3.5, "lg:max-w-3.5"],
                [4, "lg:max-w-4"],
                [5, "lg:max-w-5"],
                [6, "lg:max-w-6"],
                [7, "lg:max-w-7"],
                [8, "lg:max-w-8"],
                [9, "lg:max-w-9"],
                [10, "lg:max-w-10"],
                [11, "lg:max-w-11"],
                [12, "lg:max-w-12"],
                [14, "lg:max-w-14"],
                [16, "lg:max-w-16"],
                [20, "lg:max-w-20"],
                [24, "lg:max-w-24"],
                [28, "lg:max-w-28"],
                [32, "lg:max-w-32"],
                [36, "lg:max-w-36"],
                [40, "lg:max-w-40"],
                [44, "lg:max-w-44"],
                [48, "lg:max-w-48"],
                [52, "lg:max-w-52"],
                [56, "lg:max-w-56"],
                [60, "lg:max-w-60"],
                [64, "lg:max-w-64"],
                [72, "lg:max-w-72"],
                [80, "lg:max-w-80"],
                [96, "lg:max-w-96"],
                ["none", "lg:max-w-none"],
                ["lg", "lg:max-w-lg"],
                ["sm", "lg:max-w-sm"],
                ["md", "lg:max-w-md"],
                ["lg", "lg:max-w-lg"],
                ["xl", "lg:max-w-xl"],
                ["2xl", "lg:max-w-2xl"],
                ["3xl", "lg:max-w-3xl"],
                ["4xl", "lg:max-w-4xl"],
                ["5xl", "lg:max-w-5xl"],
                ["6xl", "lg:max-w-6xl"],
                ["7xl", "lg:max-w-7xl"],
                ["full", "lg:max-w-full"],
                ["min", "lg:max-w-min"],
                ["max", "lg:max-w-max"],
                ["fit", "lg:max-w-fit"],
                ["prose", "lg:max-w-prose"],
                ["screen-lg", "lg:max-w-screen-lg"],
                ["screen-sm", "lg:max-w-screen-sm"],
                ["screen-md", "lg:max-w-screen-md"],
                ["screen-lg", "lg:max-w-screen-lg"],
                ["screen-xl", "lg:max-w-screen-xl"],
                ["screen-2xl", "lg:max-w-screen-2xl"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxWidth, string>([
                [0, "xl:max-w-0"],
                ["px", "xl:max-w-px"],
                [0.5, "xl:max-w-0.5"],
                [1, "xl:max-w-1"],
                [1.5, "xl:max-w-1.5"],
                [2, "xl:max-w-2"],
                [2.5, "xl:max-w-2.5"],
                [3, "xl:max-w-3"],
                [3.5, "xl:max-w-3.5"],
                [4, "xl:max-w-4"],
                [5, "xl:max-w-5"],
                [6, "xl:max-w-6"],
                [7, "xl:max-w-7"],
                [8, "xl:max-w-8"],
                [9, "xl:max-w-9"],
                [10, "xl:max-w-10"],
                [11, "xl:max-w-11"],
                [12, "xl:max-w-12"],
                [14, "xl:max-w-14"],
                [16, "xl:max-w-16"],
                [20, "xl:max-w-20"],
                [24, "xl:max-w-24"],
                [28, "xl:max-w-28"],
                [32, "xl:max-w-32"],
                [36, "xl:max-w-36"],
                [40, "xl:max-w-40"],
                [44, "xl:max-w-44"],
                [48, "xl:max-w-48"],
                [52, "xl:max-w-52"],
                [56, "xl:max-w-56"],
                [60, "xl:max-w-60"],
                [64, "xl:max-w-64"],
                [72, "xl:max-w-72"],
                [80, "xl:max-w-80"],
                [96, "xl:max-w-96"],
                ["none", "xl:max-w-none"],
                ["xl", "xl:max-w-xl"],
                ["sm", "xl:max-w-sm"],
                ["md", "xl:max-w-md"],
                ["lg", "xl:max-w-lg"],
                ["xl", "xl:max-w-xl"],
                ["2xl", "xl:max-w-2xl"],
                ["3xl", "xl:max-w-3xl"],
                ["4xl", "xl:max-w-4xl"],
                ["5xl", "xl:max-w-5xl"],
                ["6xl", "xl:max-w-6xl"],
                ["7xl", "xl:max-w-7xl"],
                ["full", "xl:max-w-full"],
                ["min", "xl:max-w-min"],
                ["max", "xl:max-w-max"],
                ["fit", "xl:max-w-fit"],
                ["prose", "xl:max-w-prose"],
                ["screen-xl", "xl:max-w-screen-xl"],
                ["screen-sm", "xl:max-w-screen-sm"],
                ["screen-md", "xl:max-w-screen-md"],
                ["screen-lg", "xl:max-w-screen-lg"],
                ["screen-xl", "xl:max-w-screen-xl"],
                ["screen-2xl", "xl:max-w-screen-2xl"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexMaxWidth, string>>([
            [
              "xs",
              new Map<FlexMaxWidth, string>([
                [0, "xs:open:max-w-0"],
                ["px", "xs:open:max-w-px"],
                [0.5, "xs:open:max-w-0.5"],
                [1, "xs:open:max-w-1"],
                [1.5, "xs:open:max-w-1.5"],
                [2, "xs:open:max-w-2"],
                [2.5, "xs:open:max-w-2.5"],
                [3, "xs:open:max-w-3"],
                [3.5, "xs:open:max-w-3.5"],
                [4, "xs:open:max-w-4"],
                [5, "xs:open:max-w-5"],
                [6, "xs:open:max-w-6"],
                [7, "xs:open:max-w-7"],
                [8, "xs:open:max-w-8"],
                [9, "xs:open:max-w-9"],
                [10, "xs:open:max-w-10"],
                [11, "xs:open:max-w-11"],
                [12, "xs:open:max-w-12"],
                [14, "xs:open:max-w-14"],
                [16, "xs:open:max-w-16"],
                [20, "xs:open:max-w-20"],
                [24, "xs:open:max-w-24"],
                [28, "xs:open:max-w-28"],
                [32, "xs:open:max-w-32"],
                [36, "xs:open:max-w-36"],
                [40, "xs:open:max-w-40"],
                [44, "xs:open:max-w-44"],
                [48, "xs:open:max-w-48"],
                [52, "xs:open:max-w-52"],
                [56, "xs:open:max-w-56"],
                [60, "xs:open:max-w-60"],
                [64, "xs:open:max-w-64"],
                [72, "xs:open:max-w-72"],
                [80, "xs:open:max-w-80"],
                [96, "xs:open:max-w-96"],
                ["none", "xs:open:max-w-none"],
                ["xs", "xs:open:max-w-xs"],
                ["sm", "xs:open:max-w-sm"],
                ["md", "xs:open:max-w-md"],
                ["lg", "xs:open:max-w-lg"],
                ["xl", "xs:open:max-w-xl"],
                ["2xl", "xs:open:max-w-2xl"],
                ["3xl", "xs:open:max-w-3xl"],
                ["4xl", "xs:open:max-w-4xl"],
                ["5xl", "xs:open:max-w-5xl"],
                ["6xl", "xs:open:max-w-6xl"],
                ["7xl", "xs:open:max-w-7xl"],
                ["full", "xs:open:max-w-full"],
                ["min", "xs:open:max-w-min"],
                ["max", "xs:open:max-w-max"],
                ["fit", "xs:open:max-w-fit"],
                ["prose", "xs:open:max-w-prose"],
                ["screen-xs", "xs:open:max-w-screen-xs"],
                ["screen-sm", "xs:open:max-w-screen-sm"],
                ["screen-md", "xs:open:max-w-screen-md"],
                ["screen-lg", "xs:open:max-w-screen-lg"],
                ["screen-xl", "xs:open:max-w-screen-xl"],
                ["screen-2xl", "xs:open:max-w-screen-2xl"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMaxWidth, string>([
                [0, "sm:open:max-w-0"],
                ["px", "sm:open:max-w-px"],
                [0.5, "sm:open:max-w-0.5"],
                [1, "sm:open:max-w-1"],
                [1.5, "sm:open:max-w-1.5"],
                [2, "sm:open:max-w-2"],
                [2.5, "sm:open:max-w-2.5"],
                [3, "sm:open:max-w-3"],
                [3.5, "sm:open:max-w-3.5"],
                [4, "sm:open:max-w-4"],
                [5, "sm:open:max-w-5"],
                [6, "sm:open:max-w-6"],
                [7, "sm:open:max-w-7"],
                [8, "sm:open:max-w-8"],
                [9, "sm:open:max-w-9"],
                [10, "sm:open:max-w-10"],
                [11, "sm:open:max-w-11"],
                [12, "sm:open:max-w-12"],
                [14, "sm:open:max-w-14"],
                [16, "sm:open:max-w-16"],
                [20, "sm:open:max-w-20"],
                [24, "sm:open:max-w-24"],
                [28, "sm:open:max-w-28"],
                [32, "sm:open:max-w-32"],
                [36, "sm:open:max-w-36"],
                [40, "sm:open:max-w-40"],
                [44, "sm:open:max-w-44"],
                [48, "sm:open:max-w-48"],
                [52, "sm:open:max-w-52"],
                [56, "sm:open:max-w-56"],
                [60, "sm:open:max-w-60"],
                [64, "sm:open:max-w-64"],
                [72, "sm:open:max-w-72"],
                [80, "sm:open:max-w-80"],
                [96, "sm:open:max-w-96"],
                ["none", "sm:open:max-w-none"],
                ["sm", "sm:open:max-w-sm"],
                ["sm", "sm:open:max-w-sm"],
                ["md", "sm:open:max-w-md"],
                ["lg", "sm:open:max-w-lg"],
                ["xl", "sm:open:max-w-xl"],
                ["2xl", "sm:open:max-w-2xl"],
                ["3xl", "sm:open:max-w-3xl"],
                ["4xl", "sm:open:max-w-4xl"],
                ["5xl", "sm:open:max-w-5xl"],
                ["6xl", "sm:open:max-w-6xl"],
                ["7xl", "sm:open:max-w-7xl"],
                ["full", "sm:open:max-w-full"],
                ["min", "sm:open:max-w-min"],
                ["max", "sm:open:max-w-max"],
                ["fit", "sm:open:max-w-fit"],
                ["prose", "sm:open:max-w-prose"],
                ["screen-sm", "sm:open:max-w-screen-sm"],
                ["screen-sm", "sm:open:max-w-screen-sm"],
                ["screen-md", "sm:open:max-w-screen-md"],
                ["screen-lg", "sm:open:max-w-screen-lg"],
                ["screen-xl", "sm:open:max-w-screen-xl"],
                ["screen-2xl", "sm:open:max-w-screen-2xl"],
              ]),
            ],
            [
              "md",
              new Map<FlexMaxWidth, string>([
                [0, "md:open:max-w-0"],
                ["px", "md:open:max-w-px"],
                [0.5, "md:open:max-w-0.5"],
                [1, "md:open:max-w-1"],
                [1.5, "md:open:max-w-1.5"],
                [2, "md:open:max-w-2"],
                [2.5, "md:open:max-w-2.5"],
                [3, "md:open:max-w-3"],
                [3.5, "md:open:max-w-3.5"],
                [4, "md:open:max-w-4"],
                [5, "md:open:max-w-5"],
                [6, "md:open:max-w-6"],
                [7, "md:open:max-w-7"],
                [8, "md:open:max-w-8"],
                [9, "md:open:max-w-9"],
                [10, "md:open:max-w-10"],
                [11, "md:open:max-w-11"],
                [12, "md:open:max-w-12"],
                [14, "md:open:max-w-14"],
                [16, "md:open:max-w-16"],
                [20, "md:open:max-w-20"],
                [24, "md:open:max-w-24"],
                [28, "md:open:max-w-28"],
                [32, "md:open:max-w-32"],
                [36, "md:open:max-w-36"],
                [40, "md:open:max-w-40"],
                [44, "md:open:max-w-44"],
                [48, "md:open:max-w-48"],
                [52, "md:open:max-w-52"],
                [56, "md:open:max-w-56"],
                [60, "md:open:max-w-60"],
                [64, "md:open:max-w-64"],
                [72, "md:open:max-w-72"],
                [80, "md:open:max-w-80"],
                [96, "md:open:max-w-96"],
                ["none", "md:open:max-w-none"],
                ["md", "md:open:max-w-md"],
                ["sm", "md:open:max-w-sm"],
                ["md", "md:open:max-w-md"],
                ["lg", "md:open:max-w-lg"],
                ["xl", "md:open:max-w-xl"],
                ["2xl", "md:open:max-w-2xl"],
                ["3xl", "md:open:max-w-3xl"],
                ["4xl", "md:open:max-w-4xl"],
                ["5xl", "md:open:max-w-5xl"],
                ["6xl", "md:open:max-w-6xl"],
                ["7xl", "md:open:max-w-7xl"],
                ["full", "md:open:max-w-full"],
                ["min", "md:open:max-w-min"],
                ["max", "md:open:max-w-max"],
                ["fit", "md:open:max-w-fit"],
                ["prose", "md:open:max-w-prose"],
                ["screen-md", "md:open:max-w-screen-md"],
                ["screen-sm", "md:open:max-w-screen-sm"],
                ["screen-md", "md:open:max-w-screen-md"],
                ["screen-lg", "md:open:max-w-screen-lg"],
                ["screen-xl", "md:open:max-w-screen-xl"],
                ["screen-2xl", "md:open:max-w-screen-2xl"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMaxWidth, string>([
                [0, "lg:open:max-w-0"],
                ["px", "lg:open:max-w-px"],
                [0.5, "lg:open:max-w-0.5"],
                [1, "lg:open:max-w-1"],
                [1.5, "lg:open:max-w-1.5"],
                [2, "lg:open:max-w-2"],
                [2.5, "lg:open:max-w-2.5"],
                [3, "lg:open:max-w-3"],
                [3.5, "lg:open:max-w-3.5"],
                [4, "lg:open:max-w-4"],
                [5, "lg:open:max-w-5"],
                [6, "lg:open:max-w-6"],
                [7, "lg:open:max-w-7"],
                [8, "lg:open:max-w-8"],
                [9, "lg:open:max-w-9"],
                [10, "lg:open:max-w-10"],
                [11, "lg:open:max-w-11"],
                [12, "lg:open:max-w-12"],
                [14, "lg:open:max-w-14"],
                [16, "lg:open:max-w-16"],
                [20, "lg:open:max-w-20"],
                [24, "lg:open:max-w-24"],
                [28, "lg:open:max-w-28"],
                [32, "lg:open:max-w-32"],
                [36, "lg:open:max-w-36"],
                [40, "lg:open:max-w-40"],
                [44, "lg:open:max-w-44"],
                [48, "lg:open:max-w-48"],
                [52, "lg:open:max-w-52"],
                [56, "lg:open:max-w-56"],
                [60, "lg:open:max-w-60"],
                [64, "lg:open:max-w-64"],
                [72, "lg:open:max-w-72"],
                [80, "lg:open:max-w-80"],
                [96, "lg:open:max-w-96"],
                ["none", "lg:open:max-w-none"],
                ["lg", "lg:open:max-w-lg"],
                ["sm", "lg:open:max-w-sm"],
                ["md", "lg:open:max-w-md"],
                ["lg", "lg:open:max-w-lg"],
                ["xl", "lg:open:max-w-xl"],
                ["2xl", "lg:open:max-w-2xl"],
                ["3xl", "lg:open:max-w-3xl"],
                ["4xl", "lg:open:max-w-4xl"],
                ["5xl", "lg:open:max-w-5xl"],
                ["6xl", "lg:open:max-w-6xl"],
                ["7xl", "lg:open:max-w-7xl"],
                ["full", "lg:open:max-w-full"],
                ["min", "lg:open:max-w-min"],
                ["max", "lg:open:max-w-max"],
                ["fit", "lg:open:max-w-fit"],
                ["prose", "lg:open:max-w-prose"],
                ["screen-lg", "lg:open:max-w-screen-lg"],
                ["screen-sm", "lg:open:max-w-screen-sm"],
                ["screen-md", "lg:open:max-w-screen-md"],
                ["screen-lg", "lg:open:max-w-screen-lg"],
                ["screen-xl", "lg:open:max-w-screen-xl"],
                ["screen-2xl", "lg:open:max-w-screen-2xl"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMaxWidth, string>([
                [0, "xl:open:max-w-0"],
                ["px", "xl:open:max-w-px"],
                [0.5, "xl:open:max-w-0.5"],
                [1, "xl:open:max-w-1"],
                [1.5, "xl:open:max-w-1.5"],
                [2, "xl:open:max-w-2"],
                [2.5, "xl:open:max-w-2.5"],
                [3, "xl:open:max-w-3"],
                [3.5, "xl:open:max-w-3.5"],
                [4, "xl:open:max-w-4"],
                [5, "xl:open:max-w-5"],
                [6, "xl:open:max-w-6"],
                [7, "xl:open:max-w-7"],
                [8, "xl:open:max-w-8"],
                [9, "xl:open:max-w-9"],
                [10, "xl:open:max-w-10"],
                [11, "xl:open:max-w-11"],
                [12, "xl:open:max-w-12"],
                [14, "xl:open:max-w-14"],
                [16, "xl:open:max-w-16"],
                [20, "xl:open:max-w-20"],
                [24, "xl:open:max-w-24"],
                [28, "xl:open:max-w-28"],
                [32, "xl:open:max-w-32"],
                [36, "xl:open:max-w-36"],
                [40, "xl:open:max-w-40"],
                [44, "xl:open:max-w-44"],
                [48, "xl:open:max-w-48"],
                [52, "xl:open:max-w-52"],
                [56, "xl:open:max-w-56"],
                [60, "xl:open:max-w-60"],
                [64, "xl:open:max-w-64"],
                [72, "xl:open:max-w-72"],
                [80, "xl:open:max-w-80"],
                [96, "xl:open:max-w-96"],
                ["none", "xl:open:max-w-none"],
                ["xl", "xl:open:max-w-xl"],
                ["sm", "xl:open:max-w-sm"],
                ["md", "xl:open:max-w-md"],
                ["lg", "xl:open:max-w-lg"],
                ["xl", "xl:open:max-w-xl"],
                ["2xl", "xl:open:max-w-2xl"],
                ["3xl", "xl:open:max-w-3xl"],
                ["4xl", "xl:open:max-w-4xl"],
                ["5xl", "xl:open:max-w-5xl"],
                ["6xl", "xl:open:max-w-6xl"],
                ["7xl", "xl:open:max-w-7xl"],
                ["full", "xl:open:max-w-full"],
                ["min", "xl:open:max-w-min"],
                ["max", "xl:open:max-w-max"],
                ["fit", "xl:open:max-w-fit"],
                ["prose", "xl:open:max-w-prose"],
                ["screen-xl", "xl:open:max-w-screen-xl"],
                ["screen-sm", "xl:open:max-w-screen-sm"],
                ["screen-md", "xl:open:max-w-screen-md"],
                ["screen-lg", "xl:open:max-w-screen-lg"],
                ["screen-xl", "xl:open:max-w-screen-xl"],
                ["screen-2xl", "xl:open:max-w-screen-2xl"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
