import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexMinWidth } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class MinWidthBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexMinWidth, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexMinWidth, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MinWidthClassesMapping();
    return new MinWidthBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, grow: FlexMinWidth) {
    return this.getClassName(breakpoint, grow);
  }
}

class MinWidthClassesMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexMinWidth, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexMinWidth, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<FlexMinWidth, string>
    >("xs", new Map<FlexMinWidth, string>([["fit", "xs:min-w-fit"]]));
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexMinWidth, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexMinWidth, string>>([
            [
              "xs",
              new Map<FlexMinWidth, string>([
                [0, "xs:active:min-w-0"],
                [1, "xs:active:min-w-1"],
                [2, "xs:active:min-w-2"],
                [3, "xs:active:min-w-3"],
                [4, "xs:active:min-w-4"],
                [5, "xs:active:min-w-5"],
                [6, "xs:active:min-w-6"],
                [7, "xs:active:min-w-7"],
                [8, "xs:active:min-w-8"],
                [9, "xs:active:min-w-9"],
                [10, "xs:active:min-w-10"],
                [11, "xs:active:min-w-11"],
                [12, "xs:active:min-w-12"],
                [14, "xs:active:min-w-14"],
                [16, "xs:active:min-w-16"],
                [20, "xs:active:min-w-20"],
                [24, "xs:active:min-w-24"],
                [28, "xs:active:min-w-28"],
                [32, "xs:active:min-w-32"],
                [36, "xs:active:min-w-36"],
                [40, "xs:active:min-w-40"],
                [44, "xs:active:min-w-44"],
                [48, "xs:active:min-w-48"],
                [52, "xs:active:min-w-52"],
                [56, "xs:active:min-w-56"],
                [60, "xs:active:min-w-60"],
                [64, "xs:active:min-w-64"],
                [72, "xs:active:min-w-72"],
                [80, "xs:active:min-w-80"],
                [96, "xs:active:min-w-96"],
                ["px", "xs:active:min-w-px"],
                [0.5, "xs:active:min-w-0.5"],
                [1.5, "xs:active:min-w-1.5"],
                [2.5, "xs:active:min-w-2.5"],
                [3.5, "xs:active:min-w-3.5"],
                ["full", "xs:active:min-w-full"],
                ["min", "xs:active:min-w-min"],
                ["max", "xs:active:min-w-max"],
                ["fit", "xs:active:min-w-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinWidth, string>([
                [0, "sm:active:min-w-0"],
                [1, "sm:active:min-w-1"],
                [2, "sm:active:min-w-2"],
                [3, "sm:active:min-w-3"],
                [4, "sm:active:min-w-4"],
                [5, "sm:active:min-w-5"],
                [6, "sm:active:min-w-6"],
                [7, "sm:active:min-w-7"],
                [8, "sm:active:min-w-8"],
                [9, "sm:active:min-w-9"],
                [10, "sm:active:min-w-10"],
                [11, "sm:active:min-w-11"],
                [12, "sm:active:min-w-12"],
                [14, "sm:active:min-w-14"],
                [16, "sm:active:min-w-16"],
                [20, "sm:active:min-w-20"],
                [24, "sm:active:min-w-24"],
                [28, "sm:active:min-w-28"],
                [32, "sm:active:min-w-32"],
                [36, "sm:active:min-w-36"],
                [40, "sm:active:min-w-40"],
                [44, "sm:active:min-w-44"],
                [48, "sm:active:min-w-48"],
                [52, "sm:active:min-w-52"],
                [56, "sm:active:min-w-56"],
                [60, "sm:active:min-w-60"],
                [64, "sm:active:min-w-64"],
                [72, "sm:active:min-w-72"],
                [80, "sm:active:min-w-80"],
                [96, "sm:active:min-w-96"],
                ["px", "sm:active:min-w-px"],
                [0.5, "sm:active:min-w-0.5"],
                [1.5, "sm:active:min-w-1.5"],
                [2.5, "sm:active:min-w-2.5"],
                [3.5, "sm:active:min-w-3.5"],
                ["full", "sm:active:min-w-full"],
                ["min", "sm:active:min-w-min"],
                ["max", "sm:active:min-w-max"],
                ["fit", "sm:active:min-w-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinWidth, string>([
                [0, "md:active:min-w-0"],
                [1, "md:active:min-w-1"],
                [2, "md:active:min-w-2"],
                [3, "md:active:min-w-3"],
                [4, "md:active:min-w-4"],
                [5, "md:active:min-w-5"],
                [6, "md:active:min-w-6"],
                [7, "md:active:min-w-7"],
                [8, "md:active:min-w-8"],
                [9, "md:active:min-w-9"],
                [10, "md:active:min-w-10"],
                [11, "md:active:min-w-11"],
                [12, "md:active:min-w-12"],
                [14, "md:active:min-w-14"],
                [16, "md:active:min-w-16"],
                [20, "md:active:min-w-20"],
                [24, "md:active:min-w-24"],
                [28, "md:active:min-w-28"],
                [32, "md:active:min-w-32"],
                [36, "md:active:min-w-36"],
                [40, "md:active:min-w-40"],
                [44, "md:active:min-w-44"],
                [48, "md:active:min-w-48"],
                [52, "md:active:min-w-52"],
                [56, "md:active:min-w-56"],
                [60, "md:active:min-w-60"],
                [64, "md:active:min-w-64"],
                [72, "md:active:min-w-72"],
                [80, "md:active:min-w-80"],
                [96, "md:active:min-w-96"],
                ["px", "md:active:min-w-px"],
                [0.5, "md:active:min-w-0.5"],
                [1.5, "md:active:min-w-1.5"],
                [2.5, "md:active:min-w-2.5"],
                [3.5, "md:active:min-w-3.5"],
                ["full", "md:active:min-w-full"],
                ["min", "md:active:min-w-min"],
                ["max", "md:active:min-w-max"],
                ["fit", "md:active:min-w-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinWidth, string>([
                [0, "lg:active:min-w-0"],
                [1, "lg:active:min-w-1"],
                [2, "lg:active:min-w-2"],
                [3, "lg:active:min-w-3"],
                [4, "lg:active:min-w-4"],
                [5, "lg:active:min-w-5"],
                [6, "lg:active:min-w-6"],
                [7, "lg:active:min-w-7"],
                [8, "lg:active:min-w-8"],
                [9, "lg:active:min-w-9"],
                [10, "lg:active:min-w-10"],
                [11, "lg:active:min-w-11"],
                [12, "lg:active:min-w-12"],
                [14, "lg:active:min-w-14"],
                [16, "lg:active:min-w-16"],
                [20, "lg:active:min-w-20"],
                [24, "lg:active:min-w-24"],
                [28, "lg:active:min-w-28"],
                [32, "lg:active:min-w-32"],
                [36, "lg:active:min-w-36"],
                [40, "lg:active:min-w-40"],
                [44, "lg:active:min-w-44"],
                [48, "lg:active:min-w-48"],
                [52, "lg:active:min-w-52"],
                [56, "lg:active:min-w-56"],
                [60, "lg:active:min-w-60"],
                [64, "lg:active:min-w-64"],
                [72, "lg:active:min-w-72"],
                [80, "lg:active:min-w-80"],
                [96, "lg:active:min-w-96"],
                ["px", "lg:active:min-w-px"],
                [0.5, "lg:active:min-w-0.5"],
                [1.5, "lg:active:min-w-1.5"],
                [2.5, "lg:active:min-w-2.5"],
                [3.5, "lg:active:min-w-3.5"],
                ["full", "lg:active:min-w-full"],
                ["min", "lg:active:min-w-min"],
                ["max", "lg:active:min-w-max"],
                ["fit", "lg:active:min-w-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinWidth, string>([
                [0, "xl:active:min-w-0"],
                [1, "xl:active:min-w-1"],
                [2, "xl:active:min-w-2"],
                [3, "xl:active:min-w-3"],
                [4, "xl:active:min-w-4"],
                [5, "xl:active:min-w-5"],
                [6, "xl:active:min-w-6"],
                [7, "xl:active:min-w-7"],
                [8, "xl:active:min-w-8"],
                [9, "xl:active:min-w-9"],
                [10, "xl:active:min-w-10"],
                [11, "xl:active:min-w-11"],
                [12, "xl:active:min-w-12"],
                [14, "xl:active:min-w-14"],
                [16, "xl:active:min-w-16"],
                [20, "xl:active:min-w-20"],
                [24, "xl:active:min-w-24"],
                [28, "xl:active:min-w-28"],
                [32, "xl:active:min-w-32"],
                [36, "xl:active:min-w-36"],
                [40, "xl:active:min-w-40"],
                [44, "xl:active:min-w-44"],
                [48, "xl:active:min-w-48"],
                [52, "xl:active:min-w-52"],
                [56, "xl:active:min-w-56"],
                [60, "xl:active:min-w-60"],
                [64, "xl:active:min-w-64"],
                [72, "xl:active:min-w-72"],
                [80, "xl:active:min-w-80"],
                [96, "xl:active:min-w-96"],
                ["px", "xl:active:min-w-px"],
                [0.5, "xl:active:min-w-0.5"],
                [1.5, "xl:active:min-w-1.5"],
                [2.5, "xl:active:min-w-2.5"],
                [3.5, "xl:active:min-w-3.5"],
                ["full", "xl:active:min-w-full"],
                ["min", "xl:active:min-w-min"],
                ["max", "xl:active:min-w-max"],
                ["fit", "xl:active:min-w-fit"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexMinWidth, string>>([
            [
              "xs",
              new Map<FlexMinWidth, string>([
                [0, "xs:disabled:min-w-0"],
                [1, "xs:disabled:min-w-1"],
                [2, "xs:disabled:min-w-2"],
                [3, "xs:disabled:min-w-3"],
                [4, "xs:disabled:min-w-4"],
                [5, "xs:disabled:min-w-5"],
                [6, "xs:disabled:min-w-6"],
                [7, "xs:disabled:min-w-7"],
                [8, "xs:disabled:min-w-8"],
                [9, "xs:disabled:min-w-9"],
                [10, "xs:disabled:min-w-10"],
                [11, "xs:disabled:min-w-11"],
                [12, "xs:disabled:min-w-12"],
                [14, "xs:disabled:min-w-14"],
                [16, "xs:disabled:min-w-16"],
                [20, "xs:disabled:min-w-20"],
                [24, "xs:disabled:min-w-24"],
                [28, "xs:disabled:min-w-28"],
                [32, "xs:disabled:min-w-32"],
                [36, "xs:disabled:min-w-36"],
                [40, "xs:disabled:min-w-40"],
                [44, "xs:disabled:min-w-44"],
                [48, "xs:disabled:min-w-48"],
                [52, "xs:disabled:min-w-52"],
                [56, "xs:disabled:min-w-56"],
                [60, "xs:disabled:min-w-60"],
                [64, "xs:disabled:min-w-64"],
                [72, "xs:disabled:min-w-72"],
                [80, "xs:disabled:min-w-80"],
                [96, "xs:disabled:min-w-96"],
                ["px", "xs:disabled:min-w-px"],
                [0.5, "xs:disabled:min-w-0.5"],
                [1.5, "xs:disabled:min-w-1.5"],
                [2.5, "xs:disabled:min-w-2.5"],
                [3.5, "xs:disabled:min-w-3.5"],
                ["full", "xs:disabled:min-w-full"],
                ["min", "xs:disabled:min-w-min"],
                ["max", "xs:disabled:min-w-max"],
                ["fit", "xs:disabled:min-w-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinWidth, string>([
                [0, "sm:disabled:min-w-0"],
                [1, "sm:disabled:min-w-1"],
                [2, "sm:disabled:min-w-2"],
                [3, "sm:disabled:min-w-3"],
                [4, "sm:disabled:min-w-4"],
                [5, "sm:disabled:min-w-5"],
                [6, "sm:disabled:min-w-6"],
                [7, "sm:disabled:min-w-7"],
                [8, "sm:disabled:min-w-8"],
                [9, "sm:disabled:min-w-9"],
                [10, "sm:disabled:min-w-10"],
                [11, "sm:disabled:min-w-11"],
                [12, "sm:disabled:min-w-12"],
                [14, "sm:disabled:min-w-14"],
                [16, "sm:disabled:min-w-16"],
                [20, "sm:disabled:min-w-20"],
                [24, "sm:disabled:min-w-24"],
                [28, "sm:disabled:min-w-28"],
                [32, "sm:disabled:min-w-32"],
                [36, "sm:disabled:min-w-36"],
                [40, "sm:disabled:min-w-40"],
                [44, "sm:disabled:min-w-44"],
                [48, "sm:disabled:min-w-48"],
                [52, "sm:disabled:min-w-52"],
                [56, "sm:disabled:min-w-56"],
                [60, "sm:disabled:min-w-60"],
                [64, "sm:disabled:min-w-64"],
                [72, "sm:disabled:min-w-72"],
                [80, "sm:disabled:min-w-80"],
                [96, "sm:disabled:min-w-96"],
                ["px", "sm:disabled:min-w-px"],
                [0.5, "sm:disabled:min-w-0.5"],
                [1.5, "sm:disabled:min-w-1.5"],
                [2.5, "sm:disabled:min-w-2.5"],
                [3.5, "sm:disabled:min-w-3.5"],
                ["full", "sm:disabled:min-w-full"],
                ["min", "sm:disabled:min-w-min"],
                ["max", "sm:disabled:min-w-max"],
                ["fit", "sm:disabled:min-w-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinWidth, string>([
                [0, "md:disabled:min-w-0"],
                [1, "md:disabled:min-w-1"],
                [2, "md:disabled:min-w-2"],
                [3, "md:disabled:min-w-3"],
                [4, "md:disabled:min-w-4"],
                [5, "md:disabled:min-w-5"],
                [6, "md:disabled:min-w-6"],
                [7, "md:disabled:min-w-7"],
                [8, "md:disabled:min-w-8"],
                [9, "md:disabled:min-w-9"],
                [10, "md:disabled:min-w-10"],
                [11, "md:disabled:min-w-11"],
                [12, "md:disabled:min-w-12"],
                [14, "md:disabled:min-w-14"],
                [16, "md:disabled:min-w-16"],
                [20, "md:disabled:min-w-20"],
                [24, "md:disabled:min-w-24"],
                [28, "md:disabled:min-w-28"],
                [32, "md:disabled:min-w-32"],
                [36, "md:disabled:min-w-36"],
                [40, "md:disabled:min-w-40"],
                [44, "md:disabled:min-w-44"],
                [48, "md:disabled:min-w-48"],
                [52, "md:disabled:min-w-52"],
                [56, "md:disabled:min-w-56"],
                [60, "md:disabled:min-w-60"],
                [64, "md:disabled:min-w-64"],
                [72, "md:disabled:min-w-72"],
                [80, "md:disabled:min-w-80"],
                [96, "md:disabled:min-w-96"],
                ["px", "md:disabled:min-w-px"],
                [0.5, "md:disabled:min-w-0.5"],
                [1.5, "md:disabled:min-w-1.5"],
                [2.5, "md:disabled:min-w-2.5"],
                [3.5, "md:disabled:min-w-3.5"],
                ["full", "md:disabled:min-w-full"],
                ["min", "md:disabled:min-w-min"],
                ["max", "md:disabled:min-w-max"],
                ["fit", "md:disabled:min-w-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinWidth, string>([
                [0, "lg:disabled:min-w-0"],
                [1, "lg:disabled:min-w-1"],
                [2, "lg:disabled:min-w-2"],
                [3, "lg:disabled:min-w-3"],
                [4, "lg:disabled:min-w-4"],
                [5, "lg:disabled:min-w-5"],
                [6, "lg:disabled:min-w-6"],
                [7, "lg:disabled:min-w-7"],
                [8, "lg:disabled:min-w-8"],
                [9, "lg:disabled:min-w-9"],
                [10, "lg:disabled:min-w-10"],
                [11, "lg:disabled:min-w-11"],
                [12, "lg:disabled:min-w-12"],
                [14, "lg:disabled:min-w-14"],
                [16, "lg:disabled:min-w-16"],
                [20, "lg:disabled:min-w-20"],
                [24, "lg:disabled:min-w-24"],
                [28, "lg:disabled:min-w-28"],
                [32, "lg:disabled:min-w-32"],
                [36, "lg:disabled:min-w-36"],
                [40, "lg:disabled:min-w-40"],
                [44, "lg:disabled:min-w-44"],
                [48, "lg:disabled:min-w-48"],
                [52, "lg:disabled:min-w-52"],
                [56, "lg:disabled:min-w-56"],
                [60, "lg:disabled:min-w-60"],
                [64, "lg:disabled:min-w-64"],
                [72, "lg:disabled:min-w-72"],
                [80, "lg:disabled:min-w-80"],
                [96, "lg:disabled:min-w-96"],
                ["px", "lg:disabled:min-w-px"],
                [0.5, "lg:disabled:min-w-0.5"],
                [1.5, "lg:disabled:min-w-1.5"],
                [2.5, "lg:disabled:min-w-2.5"],
                [3.5, "lg:disabled:min-w-3.5"],
                ["full", "lg:disabled:min-w-full"],
                ["min", "lg:disabled:min-w-min"],
                ["max", "lg:disabled:min-w-max"],
                ["fit", "lg:disabled:min-w-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinWidth, string>([
                [0, "xl:disabled:min-w-0"],
                [1, "xl:disabled:min-w-1"],
                [2, "xl:disabled:min-w-2"],
                [3, "xl:disabled:min-w-3"],
                [4, "xl:disabled:min-w-4"],
                [5, "xl:disabled:min-w-5"],
                [6, "xl:disabled:min-w-6"],
                [7, "xl:disabled:min-w-7"],
                [8, "xl:disabled:min-w-8"],
                [9, "xl:disabled:min-w-9"],
                [10, "xl:disabled:min-w-10"],
                [11, "xl:disabled:min-w-11"],
                [12, "xl:disabled:min-w-12"],
                [14, "xl:disabled:min-w-14"],
                [16, "xl:disabled:min-w-16"],
                [20, "xl:disabled:min-w-20"],
                [24, "xl:disabled:min-w-24"],
                [28, "xl:disabled:min-w-28"],
                [32, "xl:disabled:min-w-32"],
                [36, "xl:disabled:min-w-36"],
                [40, "xl:disabled:min-w-40"],
                [44, "xl:disabled:min-w-44"],
                [48, "xl:disabled:min-w-48"],
                [52, "xl:disabled:min-w-52"],
                [56, "xl:disabled:min-w-56"],
                [60, "xl:disabled:min-w-60"],
                [64, "xl:disabled:min-w-64"],
                [72, "xl:disabled:min-w-72"],
                [80, "xl:disabled:min-w-80"],
                [96, "xl:disabled:min-w-96"],
                ["px", "xl:disabled:min-w-px"],
                [0.5, "xl:disabled:min-w-0.5"],
                [1.5, "xl:disabled:min-w-1.5"],
                [2.5, "xl:disabled:min-w-2.5"],
                [3.5, "xl:disabled:min-w-3.5"],
                ["full", "xl:disabled:min-w-full"],
                ["min", "xl:disabled:min-w-min"],
                ["max", "xl:disabled:min-w-max"],
                ["fit", "xl:disabled:min-w-fit"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexMinWidth, string>>([
            [
              "xs",
              new Map<FlexMinWidth, string>([
                [0, "xs:hover:min-w-0"],
                [1, "xs:hover:min-w-1"],
                [2, "xs:hover:min-w-2"],
                [3, "xs:hover:min-w-3"],
                [4, "xs:hover:min-w-4"],
                [5, "xs:hover:min-w-5"],
                [6, "xs:hover:min-w-6"],
                [7, "xs:hover:min-w-7"],
                [8, "xs:hover:min-w-8"],
                [9, "xs:hover:min-w-9"],
                [10, "xs:hover:min-w-10"],
                [11, "xs:hover:min-w-11"],
                [12, "xs:hover:min-w-12"],
                [14, "xs:hover:min-w-14"],
                [16, "xs:hover:min-w-16"],
                [20, "xs:hover:min-w-20"],
                [24, "xs:hover:min-w-24"],
                [28, "xs:hover:min-w-28"],
                [32, "xs:hover:min-w-32"],
                [36, "xs:hover:min-w-36"],
                [40, "xs:hover:min-w-40"],
                [44, "xs:hover:min-w-44"],
                [48, "xs:hover:min-w-48"],
                [52, "xs:hover:min-w-52"],
                [56, "xs:hover:min-w-56"],
                [60, "xs:hover:min-w-60"],
                [64, "xs:hover:min-w-64"],
                [72, "xs:hover:min-w-72"],
                [80, "xs:hover:min-w-80"],
                [96, "xs:hover:min-w-96"],
                ["px", "xs:hover:min-w-px"],
                [0.5, "xs:hover:min-w-0.5"],
                [1.5, "xs:hover:min-w-1.5"],
                [2.5, "xs:hover:min-w-2.5"],
                [3.5, "xs:hover:min-w-3.5"],
                ["full", "xs:hover:min-w-full"],
                ["min", "xs:hover:min-w-min"],
                ["max", "xs:hover:min-w-max"],
                ["fit", "xs:hover:min-w-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinWidth, string>([
                [0, "sm:hover:min-w-0"],
                [1, "sm:hover:min-w-1"],
                [2, "sm:hover:min-w-2"],
                [3, "sm:hover:min-w-3"],
                [4, "sm:hover:min-w-4"],
                [5, "sm:hover:min-w-5"],
                [6, "sm:hover:min-w-6"],
                [7, "sm:hover:min-w-7"],
                [8, "sm:hover:min-w-8"],
                [9, "sm:hover:min-w-9"],
                [10, "sm:hover:min-w-10"],
                [11, "sm:hover:min-w-11"],
                [12, "sm:hover:min-w-12"],
                [14, "sm:hover:min-w-14"],
                [16, "sm:hover:min-w-16"],
                [20, "sm:hover:min-w-20"],
                [24, "sm:hover:min-w-24"],
                [28, "sm:hover:min-w-28"],
                [32, "sm:hover:min-w-32"],
                [36, "sm:hover:min-w-36"],
                [40, "sm:hover:min-w-40"],
                [44, "sm:hover:min-w-44"],
                [48, "sm:hover:min-w-48"],
                [52, "sm:hover:min-w-52"],
                [56, "sm:hover:min-w-56"],
                [60, "sm:hover:min-w-60"],
                [64, "sm:hover:min-w-64"],
                [72, "sm:hover:min-w-72"],
                [80, "sm:hover:min-w-80"],
                [96, "sm:hover:min-w-96"],
                ["px", "sm:hover:min-w-px"],
                [0.5, "sm:hover:min-w-0.5"],
                [1.5, "sm:hover:min-w-1.5"],
                [2.5, "sm:hover:min-w-2.5"],
                [3.5, "sm:hover:min-w-3.5"],
                ["full", "sm:hover:min-w-full"],
                ["min", "sm:hover:min-w-min"],
                ["max", "sm:hover:min-w-max"],
                ["fit", "sm:hover:min-w-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinWidth, string>([
                [0, "md:hover:min-w-0"],
                [1, "md:hover:min-w-1"],
                [2, "md:hover:min-w-2"],
                [3, "md:hover:min-w-3"],
                [4, "md:hover:min-w-4"],
                [5, "md:hover:min-w-5"],
                [6, "md:hover:min-w-6"],
                [7, "md:hover:min-w-7"],
                [8, "md:hover:min-w-8"],
                [9, "md:hover:min-w-9"],
                [10, "md:hover:min-w-10"],
                [11, "md:hover:min-w-11"],
                [12, "md:hover:min-w-12"],
                [14, "md:hover:min-w-14"],
                [16, "md:hover:min-w-16"],
                [20, "md:hover:min-w-20"],
                [24, "md:hover:min-w-24"],
                [28, "md:hover:min-w-28"],
                [32, "md:hover:min-w-32"],
                [36, "md:hover:min-w-36"],
                [40, "md:hover:min-w-40"],
                [44, "md:hover:min-w-44"],
                [48, "md:hover:min-w-48"],
                [52, "md:hover:min-w-52"],
                [56, "md:hover:min-w-56"],
                [60, "md:hover:min-w-60"],
                [64, "md:hover:min-w-64"],
                [72, "md:hover:min-w-72"],
                [80, "md:hover:min-w-80"],
                [96, "md:hover:min-w-96"],
                ["px", "md:hover:min-w-px"],
                [0.5, "md:hover:min-w-0.5"],
                [1.5, "md:hover:min-w-1.5"],
                [2.5, "md:hover:min-w-2.5"],
                [3.5, "md:hover:min-w-3.5"],
                ["full", "md:hover:min-w-full"],
                ["min", "md:hover:min-w-min"],
                ["max", "md:hover:min-w-max"],
                ["fit", "md:hover:min-w-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinWidth, string>([
                [0, "lg:hover:min-w-0"],
                [1, "lg:hover:min-w-1"],
                [2, "lg:hover:min-w-2"],
                [3, "lg:hover:min-w-3"],
                [4, "lg:hover:min-w-4"],
                [5, "lg:hover:min-w-5"],
                [6, "lg:hover:min-w-6"],
                [7, "lg:hover:min-w-7"],
                [8, "lg:hover:min-w-8"],
                [9, "lg:hover:min-w-9"],
                [10, "lg:hover:min-w-10"],
                [11, "lg:hover:min-w-11"],
                [12, "lg:hover:min-w-12"],
                [14, "lg:hover:min-w-14"],
                [16, "lg:hover:min-w-16"],
                [20, "lg:hover:min-w-20"],
                [24, "lg:hover:min-w-24"],
                [28, "lg:hover:min-w-28"],
                [32, "lg:hover:min-w-32"],
                [36, "lg:hover:min-w-36"],
                [40, "lg:hover:min-w-40"],
                [44, "lg:hover:min-w-44"],
                [48, "lg:hover:min-w-48"],
                [52, "lg:hover:min-w-52"],
                [56, "lg:hover:min-w-56"],
                [60, "lg:hover:min-w-60"],
                [64, "lg:hover:min-w-64"],
                [72, "lg:hover:min-w-72"],
                [80, "lg:hover:min-w-80"],
                [96, "lg:hover:min-w-96"],
                ["px", "lg:hover:min-w-px"],
                [0.5, "lg:hover:min-w-0.5"],
                [1.5, "lg:hover:min-w-1.5"],
                [2.5, "lg:hover:min-w-2.5"],
                [3.5, "lg:hover:min-w-3.5"],
                ["full", "lg:hover:min-w-full"],
                ["min", "lg:hover:min-w-min"],
                ["max", "lg:hover:min-w-max"],
                ["fit", "lg:hover:min-w-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinWidth, string>([
                [0, "xl:hover:min-w-0"],
                [1, "xl:hover:min-w-1"],
                [2, "xl:hover:min-w-2"],
                [3, "xl:hover:min-w-3"],
                [4, "xl:hover:min-w-4"],
                [5, "xl:hover:min-w-5"],
                [6, "xl:hover:min-w-6"],
                [7, "xl:hover:min-w-7"],
                [8, "xl:hover:min-w-8"],
                [9, "xl:hover:min-w-9"],
                [10, "xl:hover:min-w-10"],
                [11, "xl:hover:min-w-11"],
                [12, "xl:hover:min-w-12"],
                [14, "xl:hover:min-w-14"],
                [16, "xl:hover:min-w-16"],
                [20, "xl:hover:min-w-20"],
                [24, "xl:hover:min-w-24"],
                [28, "xl:hover:min-w-28"],
                [32, "xl:hover:min-w-32"],
                [36, "xl:hover:min-w-36"],
                [40, "xl:hover:min-w-40"],
                [44, "xl:hover:min-w-44"],
                [48, "xl:hover:min-w-48"],
                [52, "xl:hover:min-w-52"],
                [56, "xl:hover:min-w-56"],
                [60, "xl:hover:min-w-60"],
                [64, "xl:hover:min-w-64"],
                [72, "xl:hover:min-w-72"],
                [80, "xl:hover:min-w-80"],
                [96, "xl:hover:min-w-96"],
                ["px", "xl:hover:min-w-px"],
                [0.5, "xl:hover:min-w-0.5"],
                [1.5, "xl:hover:min-w-1.5"],
                [2.5, "xl:hover:min-w-2.5"],
                [3.5, "xl:hover:min-w-3.5"],
                ["full", "xl:hover:min-w-full"],
                ["min", "xl:hover:min-w-min"],
                ["max", "xl:hover:min-w-max"],
                ["fit", "xl:hover:min-w-fit"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexMinWidth, string>>([
            [
              "xs",
              new Map<FlexMinWidth, string>([
                [0, "xs:min-w-0"],
                [1, "xs:min-w-1"],
                [2, "xs:min-w-2"],
                [3, "xs:min-w-3"],
                [4, "xs:min-w-4"],
                [5, "xs:min-w-5"],
                [6, "xs:min-w-6"],
                [7, "xs:min-w-7"],
                [8, "xs:min-w-8"],
                [9, "xs:min-w-9"],
                [10, "xs:min-w-10"],
                [11, "xs:min-w-11"],
                [12, "xs:min-w-12"],
                [14, "xs:min-w-14"],
                [16, "xs:min-w-16"],
                [20, "xs:min-w-20"],
                [24, "xs:min-w-24"],
                [28, "xs:min-w-28"],
                [32, "xs:min-w-32"],
                [36, "xs:min-w-36"],
                [40, "xs:min-w-40"],
                [44, "xs:min-w-44"],
                [48, "xs:min-w-48"],
                [52, "xs:min-w-52"],
                [56, "xs:min-w-56"],
                [60, "xs:min-w-60"],
                [64, "xs:min-w-64"],
                [72, "xs:min-w-72"],
                [80, "xs:min-w-80"],
                [96, "xs:min-w-96"],
                ["px", "xs:min-w-px"],
                [0.5, "xs:min-w-0.5"],
                [1.5, "xs:min-w-1.5"],
                [2.5, "xs:min-w-2.5"],
                [3.5, "xs:min-w-3.5"],
                ["full", "xs:min-w-full"],
                ["min", "xs:min-w-min"],
                ["max", "xs:min-w-max"],
                ["fit", "xs:min-w-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinWidth, string>([
                [0, "sm:min-w-0"],
                [1, "sm:min-w-1"],
                [2, "sm:min-w-2"],
                [3, "sm:min-w-3"],
                [4, "sm:min-w-4"],
                [5, "sm:min-w-5"],
                [6, "sm:min-w-6"],
                [7, "sm:min-w-7"],
                [8, "sm:min-w-8"],
                [9, "sm:min-w-9"],
                [10, "sm:min-w-10"],
                [11, "sm:min-w-11"],
                [12, "sm:min-w-12"],
                [14, "sm:min-w-14"],
                [16, "sm:min-w-16"],
                [20, "sm:min-w-20"],
                [24, "sm:min-w-24"],
                [28, "sm:min-w-28"],
                [32, "sm:min-w-32"],
                [36, "sm:min-w-36"],
                [40, "sm:min-w-40"],
                [44, "sm:min-w-44"],
                [48, "sm:min-w-48"],
                [52, "sm:min-w-52"],
                [56, "sm:min-w-56"],
                [60, "sm:min-w-60"],
                [64, "sm:min-w-64"],
                [72, "sm:min-w-72"],
                [80, "sm:min-w-80"],
                [96, "sm:min-w-96"],
                ["px", "sm:min-w-px"],
                [0.5, "sm:min-w-0.5"],
                [1.5, "sm:min-w-1.5"],
                [2.5, "sm:min-w-2.5"],
                [3.5, "sm:min-w-3.5"],
                ["full", "sm:min-w-full"],
                ["min", "sm:min-w-min"],
                ["max", "sm:min-w-max"],
                ["fit", "sm:min-w-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinWidth, string>([
                [0, "md:min-w-0"],
                [1, "md:min-w-1"],
                [2, "md:min-w-2"],
                [3, "md:min-w-3"],
                [4, "md:min-w-4"],
                [5, "md:min-w-5"],
                [6, "md:min-w-6"],
                [7, "md:min-w-7"],
                [8, "md:min-w-8"],
                [9, "md:min-w-9"],
                [10, "md:min-w-10"],
                [11, "md:min-w-11"],
                [12, "md:min-w-12"],
                [14, "md:min-w-14"],
                [16, "md:min-w-16"],
                [20, "md:min-w-20"],
                [24, "md:min-w-24"],
                [28, "md:min-w-28"],
                [32, "md:min-w-32"],
                [36, "md:min-w-36"],
                [40, "md:min-w-40"],
                [44, "md:min-w-44"],
                [48, "md:min-w-48"],
                [52, "md:min-w-52"],
                [56, "md:min-w-56"],
                [60, "md:min-w-60"],
                [64, "md:min-w-64"],
                [72, "md:min-w-72"],
                [80, "md:min-w-80"],
                [96, "md:min-w-96"],
                ["px", "md:min-w-px"],
                [0.5, "md:min-w-0.5"],
                [1.5, "md:min-w-1.5"],
                [2.5, "md:min-w-2.5"],
                [3.5, "md:min-w-3.5"],
                ["full", "md:min-w-full"],
                ["min", "md:min-w-min"],
                ["max", "md:min-w-max"],
                ["fit", "md:min-w-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinWidth, string>([
                [0, "lg:min-w-0"],
                [1, "lg:min-w-1"],
                [2, "lg:min-w-2"],
                [3, "lg:min-w-3"],
                [4, "lg:min-w-4"],
                [5, "lg:min-w-5"],
                [6, "lg:min-w-6"],
                [7, "lg:min-w-7"],
                [8, "lg:min-w-8"],
                [9, "lg:min-w-9"],
                [10, "lg:min-w-10"],
                [11, "lg:min-w-11"],
                [12, "lg:min-w-12"],
                [14, "lg:min-w-14"],
                [16, "lg:min-w-16"],
                [20, "lg:min-w-20"],
                [24, "lg:min-w-24"],
                [28, "lg:min-w-28"],
                [32, "lg:min-w-32"],
                [36, "lg:min-w-36"],
                [40, "lg:min-w-40"],
                [44, "lg:min-w-44"],
                [48, "lg:min-w-48"],
                [52, "lg:min-w-52"],
                [56, "lg:min-w-56"],
                [60, "lg:min-w-60"],
                [64, "lg:min-w-64"],
                [72, "lg:min-w-72"],
                [80, "lg:min-w-80"],
                [96, "lg:min-w-96"],
                ["px", "lg:min-w-px"],
                [0.5, "lg:min-w-0.5"],
                [1.5, "lg:min-w-1.5"],
                [2.5, "lg:min-w-2.5"],
                [3.5, "lg:min-w-3.5"],
                ["full", "lg:min-w-full"],
                ["min", "lg:min-w-min"],
                ["max", "lg:min-w-max"],
                ["fit", "lg:min-w-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinWidth, string>([
                [0, "xl:min-w-0"],
                [1, "xl:min-w-1"],
                [2, "xl:min-w-2"],
                [3, "xl:min-w-3"],
                [4, "xl:min-w-4"],
                [5, "xl:min-w-5"],
                [6, "xl:min-w-6"],
                [7, "xl:min-w-7"],
                [8, "xl:min-w-8"],
                [9, "xl:min-w-9"],
                [10, "xl:min-w-10"],
                [11, "xl:min-w-11"],
                [12, "xl:min-w-12"],
                [14, "xl:min-w-14"],
                [16, "xl:min-w-16"],
                [20, "xl:min-w-20"],
                [24, "xl:min-w-24"],
                [28, "xl:min-w-28"],
                [32, "xl:min-w-32"],
                [36, "xl:min-w-36"],
                [40, "xl:min-w-40"],
                [44, "xl:min-w-44"],
                [48, "xl:min-w-48"],
                [52, "xl:min-w-52"],
                [56, "xl:min-w-56"],
                [60, "xl:min-w-60"],
                [64, "xl:min-w-64"],
                [72, "xl:min-w-72"],
                [80, "xl:min-w-80"],
                [96, "xl:min-w-96"],
                ["px", "xl:min-w-px"],
                [0.5, "xl:min-w-0.5"],
                [1.5, "xl:min-w-1.5"],
                [2.5, "xl:min-w-2.5"],
                [3.5, "xl:min-w-3.5"],
                ["full", "xl:min-w-full"],
                ["min", "xl:min-w-min"],
                ["max", "xl:min-w-max"],
                ["fit", "xl:min-w-fit"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexMinWidth, string>>([
            [
              "xs",
              new Map<FlexMinWidth, string>([
                [0, "xs:open:min-w-0"],
                [1, "xs:open:min-w-1"],
                [2, "xs:open:min-w-2"],
                [3, "xs:open:min-w-3"],
                [4, "xs:open:min-w-4"],
                [5, "xs:open:min-w-5"],
                [6, "xs:open:min-w-6"],
                [7, "xs:open:min-w-7"],
                [8, "xs:open:min-w-8"],
                [9, "xs:open:min-w-9"],
                [10, "xs:open:min-w-10"],
                [11, "xs:open:min-w-11"],
                [12, "xs:open:min-w-12"],
                [14, "xs:open:min-w-14"],
                [16, "xs:open:min-w-16"],
                [20, "xs:open:min-w-20"],
                [24, "xs:open:min-w-24"],
                [28, "xs:open:min-w-28"],
                [32, "xs:open:min-w-32"],
                [36, "xs:open:min-w-36"],
                [40, "xs:open:min-w-40"],
                [44, "xs:open:min-w-44"],
                [48, "xs:open:min-w-48"],
                [52, "xs:open:min-w-52"],
                [56, "xs:open:min-w-56"],
                [60, "xs:open:min-w-60"],
                [64, "xs:open:min-w-64"],
                [72, "xs:open:min-w-72"],
                [80, "xs:open:min-w-80"],
                [96, "xs:open:min-w-96"],
                ["px", "xs:open:min-w-px"],
                [0.5, "xs:open:min-w-0.5"],
                [1.5, "xs:open:min-w-1.5"],
                [2.5, "xs:open:min-w-2.5"],
                [3.5, "xs:open:min-w-3.5"],
                ["full", "xs:open:min-w-full"],
                ["min", "xs:open:min-w-min"],
                ["max", "xs:open:min-w-max"],
                ["fit", "xs:open:min-w-fit"],
              ]),
            ],
            [
              "sm",
              new Map<FlexMinWidth, string>([
                [0, "sm:open:min-w-0"],
                [1, "sm:open:min-w-1"],
                [2, "sm:open:min-w-2"],
                [3, "sm:open:min-w-3"],
                [4, "sm:open:min-w-4"],
                [5, "sm:open:min-w-5"],
                [6, "sm:open:min-w-6"],
                [7, "sm:open:min-w-7"],
                [8, "sm:open:min-w-8"],
                [9, "sm:open:min-w-9"],
                [10, "sm:open:min-w-10"],
                [11, "sm:open:min-w-11"],
                [12, "sm:open:min-w-12"],
                [14, "sm:open:min-w-14"],
                [16, "sm:open:min-w-16"],
                [20, "sm:open:min-w-20"],
                [24, "sm:open:min-w-24"],
                [28, "sm:open:min-w-28"],
                [32, "sm:open:min-w-32"],
                [36, "sm:open:min-w-36"],
                [40, "sm:open:min-w-40"],
                [44, "sm:open:min-w-44"],
                [48, "sm:open:min-w-48"],
                [52, "sm:open:min-w-52"],
                [56, "sm:open:min-w-56"],
                [60, "sm:open:min-w-60"],
                [64, "sm:open:min-w-64"],
                [72, "sm:open:min-w-72"],
                [80, "sm:open:min-w-80"],
                [96, "sm:open:min-w-96"],
                ["px", "sm:open:min-w-px"],
                [0.5, "sm:open:min-w-0.5"],
                [1.5, "sm:open:min-w-1.5"],
                [2.5, "sm:open:min-w-2.5"],
                [3.5, "sm:open:min-w-3.5"],
                ["full", "sm:open:min-w-full"],
                ["min", "sm:open:min-w-min"],
                ["max", "sm:open:min-w-max"],
                ["fit", "sm:open:min-w-fit"],
              ]),
            ],
            [
              "md",
              new Map<FlexMinWidth, string>([
                [0, "md:open:min-w-0"],
                [1, "md:open:min-w-1"],
                [2, "md:open:min-w-2"],
                [3, "md:open:min-w-3"],
                [4, "md:open:min-w-4"],
                [5, "md:open:min-w-5"],
                [6, "md:open:min-w-6"],
                [7, "md:open:min-w-7"],
                [8, "md:open:min-w-8"],
                [9, "md:open:min-w-9"],
                [10, "md:open:min-w-10"],
                [11, "md:open:min-w-11"],
                [12, "md:open:min-w-12"],
                [14, "md:open:min-w-14"],
                [16, "md:open:min-w-16"],
                [20, "md:open:min-w-20"],
                [24, "md:open:min-w-24"],
                [28, "md:open:min-w-28"],
                [32, "md:open:min-w-32"],
                [36, "md:open:min-w-36"],
                [40, "md:open:min-w-40"],
                [44, "md:open:min-w-44"],
                [48, "md:open:min-w-48"],
                [52, "md:open:min-w-52"],
                [56, "md:open:min-w-56"],
                [60, "md:open:min-w-60"],
                [64, "md:open:min-w-64"],
                [72, "md:open:min-w-72"],
                [80, "md:open:min-w-80"],
                [96, "md:open:min-w-96"],
                ["px", "md:open:min-w-px"],
                [0.5, "md:open:min-w-0.5"],
                [1.5, "md:open:min-w-1.5"],
                [2.5, "md:open:min-w-2.5"],
                [3.5, "md:open:min-w-3.5"],
                ["full", "md:open:min-w-full"],
                ["min", "md:open:min-w-min"],
                ["max", "md:open:min-w-max"],
                ["fit", "md:open:min-w-fit"],
              ]),
            ],
            [
              "lg",
              new Map<FlexMinWidth, string>([
                [0, "lg:open:min-w-0"],
                [1, "lg:open:min-w-1"],
                [2, "lg:open:min-w-2"],
                [3, "lg:open:min-w-3"],
                [4, "lg:open:min-w-4"],
                [5, "lg:open:min-w-5"],
                [6, "lg:open:min-w-6"],
                [7, "lg:open:min-w-7"],
                [8, "lg:open:min-w-8"],
                [9, "lg:open:min-w-9"],
                [10, "lg:open:min-w-10"],
                [11, "lg:open:min-w-11"],
                [12, "lg:open:min-w-12"],
                [14, "lg:open:min-w-14"],
                [16, "lg:open:min-w-16"],
                [20, "lg:open:min-w-20"],
                [24, "lg:open:min-w-24"],
                [28, "lg:open:min-w-28"],
                [32, "lg:open:min-w-32"],
                [36, "lg:open:min-w-36"],
                [40, "lg:open:min-w-40"],
                [44, "lg:open:min-w-44"],
                [48, "lg:open:min-w-48"],
                [52, "lg:open:min-w-52"],
                [56, "lg:open:min-w-56"],
                [60, "lg:open:min-w-60"],
                [64, "lg:open:min-w-64"],
                [72, "lg:open:min-w-72"],
                [80, "lg:open:min-w-80"],
                [96, "lg:open:min-w-96"],
                ["px", "lg:open:min-w-px"],
                [0.5, "lg:open:min-w-0.5"],
                [1.5, "lg:open:min-w-1.5"],
                [2.5, "lg:open:min-w-2.5"],
                [3.5, "lg:open:min-w-3.5"],
                ["full", "lg:open:min-w-full"],
                ["min", "lg:open:min-w-min"],
                ["max", "lg:open:min-w-max"],
                ["fit", "lg:open:min-w-fit"],
              ]),
            ],
            [
              "xl",
              new Map<FlexMinWidth, string>([
                [0, "xl:open:min-w-0"],
                [1, "xl:open:min-w-1"],
                [2, "xl:open:min-w-2"],
                [3, "xl:open:min-w-3"],
                [4, "xl:open:min-w-4"],
                [5, "xl:open:min-w-5"],
                [6, "xl:open:min-w-6"],
                [7, "xl:open:min-w-7"],
                [8, "xl:open:min-w-8"],
                [9, "xl:open:min-w-9"],
                [10, "xl:open:min-w-10"],
                [11, "xl:open:min-w-11"],
                [12, "xl:open:min-w-12"],
                [14, "xl:open:min-w-14"],
                [16, "xl:open:min-w-16"],
                [20, "xl:open:min-w-20"],
                [24, "xl:open:min-w-24"],
                [28, "xl:open:min-w-28"],
                [32, "xl:open:min-w-32"],
                [36, "xl:open:min-w-36"],
                [40, "xl:open:min-w-40"],
                [44, "xl:open:min-w-44"],
                [48, "xl:open:min-w-48"],
                [52, "xl:open:min-w-52"],
                [56, "xl:open:min-w-56"],
                [60, "xl:open:min-w-60"],
                [64, "xl:open:min-w-64"],
                [72, "xl:open:min-w-72"],
                [80, "xl:open:min-w-80"],
                [96, "xl:open:min-w-96"],
                ["px", "xl:open:min-w-px"],
                [0.5, "xl:open:min-w-0.5"],
                [1.5, "xl:open:min-w-1.5"],
                [2.5, "xl:open:min-w-2.5"],
                [3.5, "xl:open:min-w-3.5"],
                ["full", "xl:open:min-w-full"],
                ["min", "xl:open:min-w-min"],
                ["max", "xl:open:min-w-max"],
                ["fit", "xl:open:min-w-fit"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
