import { Breakpoints, CSSSelector, FlexWidth } from "../../types";
import { WidthBreakpoints } from "./WidthBreakpoints";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakable } from "../../Entities/Brekable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";

export class Width
  extends CSSProperty<Map<FlexWidth, string>>
  implements Breakable<Map<Breakpoints, Map<FlexWidth, string>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<FlexWidth, string>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector) {
    const classesMapping = new WidthClassesMapping();
    return new Width(classesMapping, selector);
  }

  public breakpoints() {
    return WidthBreakpoints.create(this.cssSelector);
  }

  public write(size: FlexWidth) {
    return this.getClassName(size);
  }
}

class WidthClassesMapping implements ClassesMapping<Map<FlexWidth, string>> {
  private defaultValue: DefaultValue<FlexWidth, string>;

  constructor() {
    this.defaultValue = new DefaultValue<FlexWidth, string>("auto", "w-auto");
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<FlexWidth, string>>([
        [
          "active",
          new Map<FlexWidth, string>([
            [0, "active:w-0"],
            ["px", "active:w-px"],
            [0.5, "active:w-0.5"],
            [1, "active:w-1"],
            [1.5, "active:w-1.5"],
            [2, "active:w-2"],
            [2.5, "active:w-2.5"],
            [3, "active:w-3"],
            [3.5, "active:w-3.5"],
            [4, "active:w-4"],
            [5, "active:w-5"],
            [6, "active:w-6"],
            [7, "active:w-7"],
            [8, "active:w-8"],
            [9, "active:w-9"],
            [10, "active:w-10"],
            [11, "active:w-11"],
            [12, "active:w-12"],
            [14, "active:w-14"],
            [16, "active:w-16"],
            [20, "active:w-20"],
            [24, "active:w-24"],
            [28, "active:w-28"],
            [32, "active:w-32"],
            [36, "active:w-36"],
            [40, "active:w-40"],
            [44, "active:w-44"],
            [48, "active:w-48"],
            [52, "active:w-52"],
            [56, "active:w-56"],
            [60, "active:w-60"],
            [64, "active:w-64"],
            [72, "active:w-72"],
            [80, "active:w-80"],
            [96, "active:w-96"],
            ["auto", "active:w-auto"],
            ["1/2", "active:w-1/2"],
            ["1/3", "active:w-1/3"],
            ["2/3", "active:w-2/3"],
            ["1/4", "active:w-1/4"],
            ["2/4", "active:w-2/4"],
            ["3/4", "active:w-3/4"],
            ["1/5", "active:w-1/5"],
            ["2/5", "active:w-2/5"],
            ["3/5", "active:w-3/5"],
            ["4/5", "active:w-4/5"],
            ["1/6", "active:w-1/6"],
            ["2/6", "active:w-2/6"],
            ["3/6", "active:w-3/6"],
            ["4/6", "active:w-4/6"],
            ["5/6", "active:w-5/6"],
            ["1/12", "active:w-1/12"],
            ["2/12", "active:w-2/12"],
            ["3/12", "active:w-3/12"],
            ["4/12", "active:w-4/12"],
            ["5/12", "active:w-5/12"],
            ["6/12", "active:w-6/12"],
            ["7/12", "active:w-7/12"],
            ["8/12", "active:w-8/12"],
            ["9/12", "active:w-9/12"],
            ["10/12", "active:w-10/12"],
            ["11/12", "active:w-11/12"],
            ["full", "active:w-full"],
            ["screen", "active:w-screen"],
            ["svw", "active:w-svw"],
            ["lvw", "active:w-lvw"],
            ["dvw", "active:w-dvw"],
            ["min", "active:w-min"],
            ["max", "active:w-max"],
            ["fit", "active:w-fit"],
          ]),
        ],
        [
          "disabled",
          new Map<FlexWidth, string>([
            [0, "disabled:w-0"],
            ["px", "disabled:w-px"],
            [0.5, "disabled:w-0.5"],
            [1, "disabled:w-1"],
            [1.5, "disabled:w-1.5"],
            [2, "disabled:w-2"],
            [2.5, "disabled:w-2.5"],
            [3, "disabled:w-3"],
            [3.5, "disabled:w-3.5"],
            [4, "disabled:w-4"],
            [5, "disabled:w-5"],
            [6, "disabled:w-6"],
            [7, "disabled:w-7"],
            [8, "disabled:w-8"],
            [9, "disabled:w-9"],
            [10, "disabled:w-10"],
            [11, "disabled:w-11"],
            [12, "disabled:w-12"],
            [14, "disabled:w-14"],
            [16, "disabled:w-16"],
            [20, "disabled:w-20"],
            [24, "disabled:w-24"],
            [28, "disabled:w-28"],
            [32, "disabled:w-32"],
            [36, "disabled:w-36"],
            [40, "disabled:w-40"],
            [44, "disabled:w-44"],
            [48, "disabled:w-48"],
            [52, "disabled:w-52"],
            [56, "disabled:w-56"],
            [60, "disabled:w-60"],
            [64, "disabled:w-64"],
            [72, "disabled:w-72"],
            [80, "disabled:w-80"],
            [96, "disabled:w-96"],
            ["auto", "disabled:w-auto"],
            ["1/2", "disabled:w-1/2"],
            ["1/3", "disabled:w-1/3"],
            ["2/3", "disabled:w-2/3"],
            ["1/4", "disabled:w-1/4"],
            ["2/4", "disabled:w-2/4"],
            ["3/4", "disabled:w-3/4"],
            ["1/5", "disabled:w-1/5"],
            ["2/5", "disabled:w-2/5"],
            ["3/5", "disabled:w-3/5"],
            ["4/5", "disabled:w-4/5"],
            ["1/6", "disabled:w-1/6"],
            ["2/6", "disabled:w-2/6"],
            ["3/6", "disabled:w-3/6"],
            ["4/6", "disabled:w-4/6"],
            ["5/6", "disabled:w-5/6"],
            ["1/12", "disabled:w-1/12"],
            ["2/12", "disabled:w-2/12"],
            ["3/12", "disabled:w-3/12"],
            ["4/12", "disabled:w-4/12"],
            ["5/12", "disabled:w-5/12"],
            ["6/12", "disabled:w-6/12"],
            ["7/12", "disabled:w-7/12"],
            ["8/12", "disabled:w-8/12"],
            ["9/12", "disabled:w-9/12"],
            ["10/12", "disabled:w-10/12"],
            ["11/12", "disabled:w-11/12"],
            ["full", "disabled:w-full"],
            ["screen", "disabled:w-screen"],
            ["svw", "disabled:w-svw"],
            ["lvw", "disabled:w-lvw"],
            ["dvw", "disabled:w-dvw"],
            ["min", "disabled:w-min"],
            ["max", "disabled:w-max"],
            ["fit", "disabled:w-fit"],
          ]),
        ],
        [
          "hover",
          new Map<FlexWidth, string>([
            [0, "hover:w-0"],
            ["px", "hover:w-px"],
            [0.5, "hover:w-0.5"],
            [1, "hover:w-1"],
            [1.5, "hover:w-1.5"],
            [2, "hover:w-2"],
            [2.5, "hover:w-2.5"],
            [3, "hover:w-3"],
            [3.5, "hover:w-3.5"],
            [4, "hover:w-4"],
            [5, "hover:w-5"],
            [6, "hover:w-6"],
            [7, "hover:w-7"],
            [8, "hover:w-8"],
            [9, "hover:w-9"],
            [10, "hover:w-10"],
            [11, "hover:w-11"],
            [12, "hover:w-12"],
            [14, "hover:w-14"],
            [16, "hover:w-16"],
            [20, "hover:w-20"],
            [24, "hover:w-24"],
            [28, "hover:w-28"],
            [32, "hover:w-32"],
            [36, "hover:w-36"],
            [40, "hover:w-40"],
            [44, "hover:w-44"],
            [48, "hover:w-48"],
            [52, "hover:w-52"],
            [56, "hover:w-56"],
            [60, "hover:w-60"],
            [64, "hover:w-64"],
            [72, "hover:w-72"],
            [80, "hover:w-80"],
            [96, "hover:w-96"],
            ["auto", "hover:w-auto"],
            ["1/2", "hover:w-1/2"],
            ["1/3", "hover:w-1/3"],
            ["2/3", "hover:w-2/3"],
            ["1/4", "hover:w-1/4"],
            ["2/4", "hover:w-2/4"],
            ["3/4", "hover:w-3/4"],
            ["1/5", "hover:w-1/5"],
            ["2/5", "hover:w-2/5"],
            ["3/5", "hover:w-3/5"],
            ["4/5", "hover:w-4/5"],
            ["1/6", "hover:w-1/6"],
            ["2/6", "hover:w-2/6"],
            ["3/6", "hover:w-3/6"],
            ["4/6", "hover:w-4/6"],
            ["5/6", "hover:w-5/6"],
            ["1/12", "hover:w-1/12"],
            ["2/12", "hover:w-2/12"],
            ["3/12", "hover:w-3/12"],
            ["4/12", "hover:w-4/12"],
            ["5/12", "hover:w-5/12"],
            ["6/12", "hover:w-6/12"],
            ["7/12", "hover:w-7/12"],
            ["8/12", "hover:w-8/12"],
            ["9/12", "hover:w-9/12"],
            ["10/12", "hover:w-10/12"],
            ["11/12", "hover:w-11/12"],
            ["full", "hover:w-full"],
            ["screen", "hover:w-screen"],
            ["svw", "hover:w-svw"],
            ["lvw", "hover:w-lvw"],
            ["dvw", "hover:w-dvw"],
            ["min", "hover:w-min"],
            ["max", "hover:w-max"],
            ["fit", "hover:w-fit"],
          ]),
        ],
        [
          "none",
          new Map<FlexWidth, string>([
            [0, "w-0"],
            ["px", "w-px"],
            [0.5, "w-0.5"],
            [1, "w-1"],
            [1.5, "w-1.5"],
            [2, "w-2"],
            [2.5, "w-2.5"],
            [3, "w-3"],
            [3.5, "w-3.5"],
            [4, "w-4"],
            [5, "w-5"],
            [6, "w-6"],
            [7, "w-7"],
            [8, "w-8"],
            [9, "w-9"],
            [10, "w-10"],
            [11, "w-11"],
            [12, "w-12"],
            [14, "w-14"],
            [16, "w-16"],
            [20, "w-20"],
            [24, "w-24"],
            [28, "w-28"],
            [32, "w-32"],
            [36, "w-36"],
            [40, "w-40"],
            [44, "w-44"],
            [48, "w-48"],
            [52, "w-52"],
            [56, "w-56"],
            [60, "w-60"],
            [64, "w-64"],
            [72, "w-72"],
            [80, "w-80"],
            [96, "w-96"],
            ["auto", "w-auto"],
            ["1/2", "w-1/2"],
            ["1/3", "w-1/3"],
            ["2/3", "w-2/3"],
            ["1/4", "w-1/4"],
            ["2/4", "w-2/4"],
            ["3/4", "w-3/4"],
            ["1/5", "w-1/5"],
            ["2/5", "w-2/5"],
            ["3/5", "w-3/5"],
            ["4/5", "w-4/5"],
            ["1/6", "w-1/6"],
            ["2/6", "w-2/6"],
            ["3/6", "w-3/6"],
            ["4/6", "w-4/6"],
            ["5/6", "w-5/6"],
            ["1/12", "w-1/12"],
            ["2/12", "w-2/12"],
            ["3/12", "w-3/12"],
            ["4/12", "w-4/12"],
            ["5/12", "w-5/12"],
            ["6/12", "w-6/12"],
            ["7/12", "w-7/12"],
            ["8/12", "w-8/12"],
            ["9/12", "w-9/12"],
            ["10/12", "w-10/12"],
            ["11/12", "w-11/12"],
            ["full", "w-full"],
            ["screen", "w-screen"],
            ["svw", "w-svw"],
            ["lvw", "w-lvw"],
            ["dvw", "w-dvw"],
            ["min", "w-min"],
            ["max", "w-max"],
            ["fit", "w-fit"],
          ]),
        ],
        [
          "open",
          new Map<FlexWidth, string>([
            [0, "open:w-0"],
            ["px", "open:w-px"],
            [0.5, "open:w-0.5"],
            [1, "open:w-1"],
            [1.5, "open:w-1.5"],
            [2, "open:w-2"],
            [2.5, "open:w-2.5"],
            [3, "open:w-3"],
            [3.5, "open:w-3.5"],
            [4, "open:w-4"],
            [5, "open:w-5"],
            [6, "open:w-6"],
            [7, "open:w-7"],
            [8, "open:w-8"],
            [9, "open:w-9"],
            [10, "open:w-10"],
            [11, "open:w-11"],
            [12, "open:w-12"],
            [14, "open:w-14"],
            [16, "open:w-16"],
            [20, "open:w-20"],
            [24, "open:w-24"],
            [28, "open:w-28"],
            [32, "open:w-32"],
            [36, "open:w-36"],
            [40, "open:w-40"],
            [44, "open:w-44"],
            [48, "open:w-48"],
            [52, "open:w-52"],
            [56, "open:w-56"],
            [60, "open:w-60"],
            [64, "open:w-64"],
            [72, "open:w-72"],
            [80, "open:w-80"],
            [96, "open:w-96"],
            ["auto", "open:w-auto"],
            ["1/2", "open:w-1/2"],
            ["1/3", "open:w-1/3"],
            ["2/3", "open:w-2/3"],
            ["1/4", "open:w-1/4"],
            ["2/4", "open:w-2/4"],
            ["3/4", "open:w-3/4"],
            ["1/5", "open:w-1/5"],
            ["2/5", "open:w-2/5"],
            ["3/5", "open:w-3/5"],
            ["4/5", "open:w-4/5"],
            ["1/6", "open:w-1/6"],
            ["2/6", "open:w-2/6"],
            ["3/6", "open:w-3/6"],
            ["4/6", "open:w-4/6"],
            ["5/6", "open:w-5/6"],
            ["1/12", "open:w-1/12"],
            ["2/12", "open:w-2/12"],
            ["3/12", "open:w-3/12"],
            ["4/12", "open:w-4/12"],
            ["5/12", "open:w-5/12"],
            ["6/12", "open:w-6/12"],
            ["7/12", "open:w-7/12"],
            ["8/12", "open:w-8/12"],
            ["9/12", "open:w-9/12"],
            ["10/12", "open:w-10/12"],
            ["11/12", "open:w-11/12"],
            ["full", "open:w-full"],
            ["screen", "open:w-screen"],
            ["svw", "open:w-svw"],
            ["lvw", "open:w-lvw"],
            ["dvw", "open:w-dvw"],
            ["min", "open:w-min"],
            ["max", "open:w-max"],
            ["fit", "open:w-fit"],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
