import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexBasis } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class BasisBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexBasis, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexBasis, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new BasisBreakpointsMapping();
    return new BasisBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, grow: FlexBasis) {
    return this.getClassName(breakpoint, grow);
  }
}

class BasisBreakpointsMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexBasis, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexBasis, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexBasis, string>>(
      "xs",
      new Map<FlexBasis, string>([["auto", "xs:basis-auto"]])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexBasis, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexBasis, string>>([
            [
              "xs",
              new Map<FlexBasis, string>([
                [0, "xs:active:basis-0"],
                [1, "xs:active:basis-1"],
                [2, "xs:active:basis-2"],
                [3, "xs:active:basis-3"],
                [4, "xs:active:basis-4"],
                [5, "xs:active:basis-5"],
                [6, "xs:active:basis-6"],
                [7, "xs:active:basis-7"],
                [8, "xs:active:basis-8"],
                [9, "xs:active:basis-9"],
                [10, "xs:active:basis-10"],
                [11, "xs:active:basis-11"],
                [12, "xs:active:basis-12"],
                [14, "xs:active:basis-14"],
                [16, "xs:active:basis-16"],
                [20, "xs:active:basis-20"],
                [24, "xs:active:basis-24"],
                [28, "xs:active:basis-28"],
                [32, "xs:active:basis-32"],
                [36, "xs:active:basis-36"],
                [40, "xs:active:basis-40"],
                [44, "xs:active:basis-44"],
                [48, "xs:active:basis-48"],
                [52, "xs:active:basis-52"],
                [56, "xs:active:basis-56"],
                [60, "xs:active:basis-60"],
                [64, "xs:active:basis-64"],
                [72, "xs:active:basis-72"],
                [80, "xs:active:basis-80"],
                [96, "xs:active:basis-96"],
                ["auto", "xs:active:basis-auto"],
                ["px", "xs:active:basis-px"],
                [0.5, "xs:active:basis-0.5"],
                [1.5, "xs:active:basis-1.5"],
                [2.5, "xs:active:basis-2.5"],
                [3.5, "xs:active:basis-3.5"],
                ["1/2", "xs:active:basis-1/2"],
                ["1/3", "xs:active:basis-1/3"],
                ["2/3", "xs:active:basis-2/3"],
                ["1/4", "xs:active:basis-1/4"],
                ["2/4", "xs:active:basis-2/4"],
                ["3/4", "xs:active:basis-3/4"],
                ["1/5", "xs:active:basis-1/5"],
                ["2/5", "xs:active:basis-2/5"],
                ["3/5", "xs:active:basis-3/5"],
                ["4/5", "xs:active:basis-4/5"],
                ["1/6", "xs:active:basis-1/6"],
                ["2/6", "xs:active:basis-2/6"],
                ["3/6", "xs:active:basis-3/6"],
                ["4/6", "xs:active:basis-4/6"],
                ["5/6", "xs:active:basis-5/6"],
                ["1/12", "xs:active:basis-1/12"],
                ["2/12", "xs:active:basis-2/12"],
                ["3/12", "xs:active:basis-3/12"],
                ["4/12", "xs:active:basis-4/12"],
                ["5/12", "xs:active:basis-5/12"],
                ["6/12", "xs:active:basis-6/12"],
                ["7/12", "xs:active:basis-7/12"],
                ["8/12", "xs:active:basis-8/12"],
                ["9/12", "xs:active:basis-9/12"],
                ["10/12", "xs:active:basis-10/12"],
                ["11/12", "xs:active:basis-11/12"],
                ["full", "xs:active:basis-full"],
              ]),
            ],
            [
              "sm",
              new Map<FlexBasis, string>([
                [0, "sm:active:basis-0"],
                [1, "sm:active:basis-1"],
                [2, "sm:active:basis-2"],
                [3, "sm:active:basis-3"],
                [4, "sm:active:basis-4"],
                [5, "sm:active:basis-5"],
                [6, "sm:active:basis-6"],
                [7, "sm:active:basis-7"],
                [8, "sm:active:basis-8"],
                [9, "sm:active:basis-9"],
                [10, "sm:active:basis-10"],
                [11, "sm:active:basis-11"],
                [12, "sm:active:basis-12"],
                [14, "sm:active:basis-14"],
                [16, "sm:active:basis-16"],
                [20, "sm:active:basis-20"],
                [24, "sm:active:basis-24"],
                [28, "sm:active:basis-28"],
                [32, "sm:active:basis-32"],
                [36, "sm:active:basis-36"],
                [40, "sm:active:basis-40"],
                [44, "sm:active:basis-44"],
                [48, "sm:active:basis-48"],
                [52, "sm:active:basis-52"],
                [56, "sm:active:basis-56"],
                [60, "sm:active:basis-60"],
                [64, "sm:active:basis-64"],
                [72, "sm:active:basis-72"],
                [80, "sm:active:basis-80"],
                [96, "sm:active:basis-96"],
                ["auto", "sm:active:basis-auto"],
                ["px", "sm:active:basis-px"],
                [0.5, "sm:active:basis-0.5"],
                [1.5, "sm:active:basis-1.5"],
                [2.5, "sm:active:basis-2.5"],
                [3.5, "sm:active:basis-3.5"],
                ["1/2", "sm:active:basis-1/2"],
                ["1/3", "sm:active:basis-1/3"],
                ["2/3", "sm:active:basis-2/3"],
                ["1/4", "sm:active:basis-1/4"],
                ["2/4", "sm:active:basis-2/4"],
                ["3/4", "sm:active:basis-3/4"],
                ["1/5", "sm:active:basis-1/5"],
                ["2/5", "sm:active:basis-2/5"],
                ["3/5", "sm:active:basis-3/5"],
                ["4/5", "sm:active:basis-4/5"],
                ["1/6", "sm:active:basis-1/6"],
                ["2/6", "sm:active:basis-2/6"],
                ["3/6", "sm:active:basis-3/6"],
                ["4/6", "sm:active:basis-4/6"],
                ["5/6", "sm:active:basis-5/6"],
                ["1/12", "sm:active:basis-1/12"],
                ["2/12", "sm:active:basis-2/12"],
                ["3/12", "sm:active:basis-3/12"],
                ["4/12", "sm:active:basis-4/12"],
                ["5/12", "sm:active:basis-5/12"],
                ["6/12", "sm:active:basis-6/12"],
                ["7/12", "sm:active:basis-7/12"],
                ["8/12", "sm:active:basis-8/12"],
                ["9/12", "sm:active:basis-9/12"],
                ["10/12", "sm:active:basis-10/12"],
                ["11/12", "sm:active:basis-11/12"],
                ["full", "sm:active:basis-full"],
              ]),
            ],
            [
              "md",
              new Map<FlexBasis, string>([
                [0, "md:active:basis-0"],
                [1, "md:active:basis-1"],
                [2, "md:active:basis-2"],
                [3, "md:active:basis-3"],
                [4, "md:active:basis-4"],
                [5, "md:active:basis-5"],
                [6, "md:active:basis-6"],
                [7, "md:active:basis-7"],
                [8, "md:active:basis-8"],
                [9, "md:active:basis-9"],
                [10, "md:active:basis-10"],
                [11, "md:active:basis-11"],
                [12, "md:active:basis-12"],
                [14, "md:active:basis-14"],
                [16, "md:active:basis-16"],
                [20, "md:active:basis-20"],
                [24, "md:active:basis-24"],
                [28, "md:active:basis-28"],
                [32, "md:active:basis-32"],
                [36, "md:active:basis-36"],
                [40, "md:active:basis-40"],
                [44, "md:active:basis-44"],
                [48, "md:active:basis-48"],
                [52, "md:active:basis-52"],
                [56, "md:active:basis-56"],
                [60, "md:active:basis-60"],
                [64, "md:active:basis-64"],
                [72, "md:active:basis-72"],
                [80, "md:active:basis-80"],
                [96, "md:active:basis-96"],
                ["auto", "md:active:basis-auto"],
                ["px", "md:active:basis-px"],
                [0.5, "md:active:basis-0.5"],
                [1.5, "md:active:basis-1.5"],
                [2.5, "md:active:basis-2.5"],
                [3.5, "md:active:basis-3.5"],
                ["1/2", "md:active:basis-1/2"],
                ["1/3", "md:active:basis-1/3"],
                ["2/3", "md:active:basis-2/3"],
                ["1/4", "md:active:basis-1/4"],
                ["2/4", "md:active:basis-2/4"],
                ["3/4", "md:active:basis-3/4"],
                ["1/5", "md:active:basis-1/5"],
                ["2/5", "md:active:basis-2/5"],
                ["3/5", "md:active:basis-3/5"],
                ["4/5", "md:active:basis-4/5"],
                ["1/6", "md:active:basis-1/6"],
                ["2/6", "md:active:basis-2/6"],
                ["3/6", "md:active:basis-3/6"],
                ["4/6", "md:active:basis-4/6"],
                ["5/6", "md:active:basis-5/6"],
                ["1/12", "md:active:basis-1/12"],
                ["2/12", "md:active:basis-2/12"],
                ["3/12", "md:active:basis-3/12"],
                ["4/12", "md:active:basis-4/12"],
                ["5/12", "md:active:basis-5/12"],
                ["6/12", "md:active:basis-6/12"],
                ["7/12", "md:active:basis-7/12"],
                ["8/12", "md:active:basis-8/12"],
                ["9/12", "md:active:basis-9/12"],
                ["10/12", "md:active:basis-10/12"],
                ["11/12", "md:active:basis-11/12"],
                ["full", "md:active:basis-full"],
              ]),
            ],
            [
              "lg",
              new Map<FlexBasis, string>([
                [0, "lg:active:basis-0"],
                [1, "lg:active:basis-1"],
                [2, "lg:active:basis-2"],
                [3, "lg:active:basis-3"],
                [4, "lg:active:basis-4"],
                [5, "lg:active:basis-5"],
                [6, "lg:active:basis-6"],
                [7, "lg:active:basis-7"],
                [8, "lg:active:basis-8"],
                [9, "lg:active:basis-9"],
                [10, "lg:active:basis-10"],
                [11, "lg:active:basis-11"],
                [12, "lg:active:basis-12"],
                [14, "lg:active:basis-14"],
                [16, "lg:active:basis-16"],
                [20, "lg:active:basis-20"],
                [24, "lg:active:basis-24"],
                [28, "lg:active:basis-28"],
                [32, "lg:active:basis-32"],
                [36, "lg:active:basis-36"],
                [40, "lg:active:basis-40"],
                [44, "lg:active:basis-44"],
                [48, "lg:active:basis-48"],
                [52, "lg:active:basis-52"],
                [56, "lg:active:basis-56"],
                [60, "lg:active:basis-60"],
                [64, "lg:active:basis-64"],
                [72, "lg:active:basis-72"],
                [80, "lg:active:basis-80"],
                [96, "lg:active:basis-96"],
                ["auto", "lg:active:basis-auto"],
                ["px", "lg:active:basis-px"],
                [0.5, "lg:active:basis-0.5"],
                [1.5, "lg:active:basis-1.5"],
                [2.5, "lg:active:basis-2.5"],
                [3.5, "lg:active:basis-3.5"],
                ["1/2", "lg:active:basis-1/2"],
                ["1/3", "lg:active:basis-1/3"],
                ["2/3", "lg:active:basis-2/3"],
                ["1/4", "lg:active:basis-1/4"],
                ["2/4", "lg:active:basis-2/4"],
                ["3/4", "lg:active:basis-3/4"],
                ["1/5", "lg:active:basis-1/5"],
                ["2/5", "lg:active:basis-2/5"],
                ["3/5", "lg:active:basis-3/5"],
                ["4/5", "lg:active:basis-4/5"],
                ["1/6", "lg:active:basis-1/6"],
                ["2/6", "lg:active:basis-2/6"],
                ["3/6", "lg:active:basis-3/6"],
                ["4/6", "lg:active:basis-4/6"],
                ["5/6", "lg:active:basis-5/6"],
                ["1/12", "lg:active:basis-1/12"],
                ["2/12", "lg:active:basis-2/12"],
                ["3/12", "lg:active:basis-3/12"],
                ["4/12", "lg:active:basis-4/12"],
                ["5/12", "lg:active:basis-5/12"],
                ["6/12", "lg:active:basis-6/12"],
                ["7/12", "lg:active:basis-7/12"],
                ["8/12", "lg:active:basis-8/12"],
                ["9/12", "lg:active:basis-9/12"],
                ["10/12", "lg:active:basis-10/12"],
                ["11/12", "lg:active:basis-11/12"],
                ["full", "lg:active:basis-full"],
              ]),
            ],
            [
              "xl",
              new Map<FlexBasis, string>([
                [0, "xl:active:basis-0"],
                [1, "xl:active:basis-1"],
                [2, "xl:active:basis-2"],
                [3, "xl:active:basis-3"],
                [4, "xl:active:basis-4"],
                [5, "xl:active:basis-5"],
                [6, "xl:active:basis-6"],
                [7, "xl:active:basis-7"],
                [8, "xl:active:basis-8"],
                [9, "xl:active:basis-9"],
                [10, "xl:active:basis-10"],
                [11, "xl:active:basis-11"],
                [12, "xl:active:basis-12"],
                [14, "xl:active:basis-14"],
                [16, "xl:active:basis-16"],
                [20, "xl:active:basis-20"],
                [24, "xl:active:basis-24"],
                [28, "xl:active:basis-28"],
                [32, "xl:active:basis-32"],
                [36, "xl:active:basis-36"],
                [40, "xl:active:basis-40"],
                [44, "xl:active:basis-44"],
                [48, "xl:active:basis-48"],
                [52, "xl:active:basis-52"],
                [56, "xl:active:basis-56"],
                [60, "xl:active:basis-60"],
                [64, "xl:active:basis-64"],
                [72, "xl:active:basis-72"],
                [80, "xl:active:basis-80"],
                [96, "xl:active:basis-96"],
                ["auto", "xl:active:basis-auto"],
                ["px", "xl:active:basis-px"],
                [0.5, "xl:active:basis-0.5"],
                [1.5, "xl:active:basis-1.5"],
                [2.5, "xl:active:basis-2.5"],
                [3.5, "xl:active:basis-3.5"],
                ["1/2", "xl:active:basis-1/2"],
                ["1/3", "xl:active:basis-1/3"],
                ["2/3", "xl:active:basis-2/3"],
                ["1/4", "xl:active:basis-1/4"],
                ["2/4", "xl:active:basis-2/4"],
                ["3/4", "xl:active:basis-3/4"],
                ["1/5", "xl:active:basis-1/5"],
                ["2/5", "xl:active:basis-2/5"],
                ["3/5", "xl:active:basis-3/5"],
                ["4/5", "xl:active:basis-4/5"],
                ["1/6", "xl:active:basis-1/6"],
                ["2/6", "xl:active:basis-2/6"],
                ["3/6", "xl:active:basis-3/6"],
                ["4/6", "xl:active:basis-4/6"],
                ["5/6", "xl:active:basis-5/6"],
                ["1/12", "xl:active:basis-1/12"],
                ["2/12", "xl:active:basis-2/12"],
                ["3/12", "xl:active:basis-3/12"],
                ["4/12", "xl:active:basis-4/12"],
                ["5/12", "xl:active:basis-5/12"],
                ["6/12", "xl:active:basis-6/12"],
                ["7/12", "xl:active:basis-7/12"],
                ["8/12", "xl:active:basis-8/12"],
                ["9/12", "xl:active:basis-9/12"],
                ["10/12", "xl:active:basis-10/12"],
                ["11/12", "xl:active:basis-11/12"],
                ["full", "xl:active:basis-full"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexBasis, string>>([
            [
              "xs",
              new Map<FlexBasis, string>([
                [0, "xs:disabled:basis-0"],
                [1, "xs:disabled:basis-1"],
                [2, "xs:disabled:basis-2"],
                [3, "xs:disabled:basis-3"],
                [4, "xs:disabled:basis-4"],
                [5, "xs:disabled:basis-5"],
                [6, "xs:disabled:basis-6"],
                [7, "xs:disabled:basis-7"],
                [8, "xs:disabled:basis-8"],
                [9, "xs:disabled:basis-9"],
                [10, "xs:disabled:basis-10"],
                [11, "xs:disabled:basis-11"],
                [12, "xs:disabled:basis-12"],
                [14, "xs:disabled:basis-14"],
                [16, "xs:disabled:basis-16"],
                [20, "xs:disabled:basis-20"],
                [24, "xs:disabled:basis-24"],
                [28, "xs:disabled:basis-28"],
                [32, "xs:disabled:basis-32"],
                [36, "xs:disabled:basis-36"],
                [40, "xs:disabled:basis-40"],
                [44, "xs:disabled:basis-44"],
                [48, "xs:disabled:basis-48"],
                [52, "xs:disabled:basis-52"],
                [56, "xs:disabled:basis-56"],
                [60, "xs:disabled:basis-60"],
                [64, "xs:disabled:basis-64"],
                [72, "xs:disabled:basis-72"],
                [80, "xs:disabled:basis-80"],
                [96, "xs:disabled:basis-96"],
                ["auto", "xs:disabled:basis-auto"],
                ["px", "xs:disabled:basis-px"],
                [0.5, "xs:disabled:basis-0.5"],
                [1.5, "xs:disabled:basis-1.5"],
                [2.5, "xs:disabled:basis-2.5"],
                [3.5, "xs:disabled:basis-3.5"],
                ["1/2", "xs:disabled:basis-1/2"],
                ["1/3", "xs:disabled:basis-1/3"],
                ["2/3", "xs:disabled:basis-2/3"],
                ["1/4", "xs:disabled:basis-1/4"],
                ["2/4", "xs:disabled:basis-2/4"],
                ["3/4", "xs:disabled:basis-3/4"],
                ["1/5", "xs:disabled:basis-1/5"],
                ["2/5", "xs:disabled:basis-2/5"],
                ["3/5", "xs:disabled:basis-3/5"],
                ["4/5", "xs:disabled:basis-4/5"],
                ["1/6", "xs:disabled:basis-1/6"],
                ["2/6", "xs:disabled:basis-2/6"],
                ["3/6", "xs:disabled:basis-3/6"],
                ["4/6", "xs:disabled:basis-4/6"],
                ["5/6", "xs:disabled:basis-5/6"],
                ["1/12", "xs:disabled:basis-1/12"],
                ["2/12", "xs:disabled:basis-2/12"],
                ["3/12", "xs:disabled:basis-3/12"],
                ["4/12", "xs:disabled:basis-4/12"],
                ["5/12", "xs:disabled:basis-5/12"],
                ["6/12", "xs:disabled:basis-6/12"],
                ["7/12", "xs:disabled:basis-7/12"],
                ["8/12", "xs:disabled:basis-8/12"],
                ["9/12", "xs:disabled:basis-9/12"],
                ["10/12", "xs:disabled:basis-10/12"],
                ["11/12", "xs:disabled:basis-11/12"],
                ["full", "xs:disabled:basis-full"],
              ]),
            ],
            [
              "sm",
              new Map<FlexBasis, string>([
                [0, "sm:disabled:basis-0"],
                [1, "sm:disabled:basis-1"],
                [2, "sm:disabled:basis-2"],
                [3, "sm:disabled:basis-3"],
                [4, "sm:disabled:basis-4"],
                [5, "sm:disabled:basis-5"],
                [6, "sm:disabled:basis-6"],
                [7, "sm:disabled:basis-7"],
                [8, "sm:disabled:basis-8"],
                [9, "sm:disabled:basis-9"],
                [10, "sm:disabled:basis-10"],
                [11, "sm:disabled:basis-11"],
                [12, "sm:disabled:basis-12"],
                [14, "sm:disabled:basis-14"],
                [16, "sm:disabled:basis-16"],
                [20, "sm:disabled:basis-20"],
                [24, "sm:disabled:basis-24"],
                [28, "sm:disabled:basis-28"],
                [32, "sm:disabled:basis-32"],
                [36, "sm:disabled:basis-36"],
                [40, "sm:disabled:basis-40"],
                [44, "sm:disabled:basis-44"],
                [48, "sm:disabled:basis-48"],
                [52, "sm:disabled:basis-52"],
                [56, "sm:disabled:basis-56"],
                [60, "sm:disabled:basis-60"],
                [64, "sm:disabled:basis-64"],
                [72, "sm:disabled:basis-72"],
                [80, "sm:disabled:basis-80"],
                [96, "sm:disabled:basis-96"],
                ["auto", "sm:disabled:basis-auto"],
                ["px", "sm:disabled:basis-px"],
                [0.5, "sm:disabled:basis-0.5"],
                [1.5, "sm:disabled:basis-1.5"],
                [2.5, "sm:disabled:basis-2.5"],
                [3.5, "sm:disabled:basis-3.5"],
                ["1/2", "sm:disabled:basis-1/2"],
                ["1/3", "sm:disabled:basis-1/3"],
                ["2/3", "sm:disabled:basis-2/3"],
                ["1/4", "sm:disabled:basis-1/4"],
                ["2/4", "sm:disabled:basis-2/4"],
                ["3/4", "sm:disabled:basis-3/4"],
                ["1/5", "sm:disabled:basis-1/5"],
                ["2/5", "sm:disabled:basis-2/5"],
                ["3/5", "sm:disabled:basis-3/5"],
                ["4/5", "sm:disabled:basis-4/5"],
                ["1/6", "sm:disabled:basis-1/6"],
                ["2/6", "sm:disabled:basis-2/6"],
                ["3/6", "sm:disabled:basis-3/6"],
                ["4/6", "sm:disabled:basis-4/6"],
                ["5/6", "sm:disabled:basis-5/6"],
                ["1/12", "sm:disabled:basis-1/12"],
                ["2/12", "sm:disabled:basis-2/12"],
                ["3/12", "sm:disabled:basis-3/12"],
                ["4/12", "sm:disabled:basis-4/12"],
                ["5/12", "sm:disabled:basis-5/12"],
                ["6/12", "sm:disabled:basis-6/12"],
                ["7/12", "sm:disabled:basis-7/12"],
                ["8/12", "sm:disabled:basis-8/12"],
                ["9/12", "sm:disabled:basis-9/12"],
                ["10/12", "sm:disabled:basis-10/12"],
                ["11/12", "sm:disabled:basis-11/12"],
                ["full", "sm:disabled:basis-full"],
              ]),
            ],
            [
              "md",
              new Map<FlexBasis, string>([
                [0, "md:disabled:basis-0"],
                [1, "md:disabled:basis-1"],
                [2, "md:disabled:basis-2"],
                [3, "md:disabled:basis-3"],
                [4, "md:disabled:basis-4"],
                [5, "md:disabled:basis-5"],
                [6, "md:disabled:basis-6"],
                [7, "md:disabled:basis-7"],
                [8, "md:disabled:basis-8"],
                [9, "md:disabled:basis-9"],
                [10, "md:disabled:basis-10"],
                [11, "md:disabled:basis-11"],
                [12, "md:disabled:basis-12"],
                [14, "md:disabled:basis-14"],
                [16, "md:disabled:basis-16"],
                [20, "md:disabled:basis-20"],
                [24, "md:disabled:basis-24"],
                [28, "md:disabled:basis-28"],
                [32, "md:disabled:basis-32"],
                [36, "md:disabled:basis-36"],
                [40, "md:disabled:basis-40"],
                [44, "md:disabled:basis-44"],
                [48, "md:disabled:basis-48"],
                [52, "md:disabled:basis-52"],
                [56, "md:disabled:basis-56"],
                [60, "md:disabled:basis-60"],
                [64, "md:disabled:basis-64"],
                [72, "md:disabled:basis-72"],
                [80, "md:disabled:basis-80"],
                [96, "md:disabled:basis-96"],
                ["auto", "md:disabled:basis-auto"],
                ["px", "md:disabled:basis-px"],
                [0.5, "md:disabled:basis-0.5"],
                [1.5, "md:disabled:basis-1.5"],
                [2.5, "md:disabled:basis-2.5"],
                [3.5, "md:disabled:basis-3.5"],
                ["1/2", "md:disabled:basis-1/2"],
                ["1/3", "md:disabled:basis-1/3"],
                ["2/3", "md:disabled:basis-2/3"],
                ["1/4", "md:disabled:basis-1/4"],
                ["2/4", "md:disabled:basis-2/4"],
                ["3/4", "md:disabled:basis-3/4"],
                ["1/5", "md:disabled:basis-1/5"],
                ["2/5", "md:disabled:basis-2/5"],
                ["3/5", "md:disabled:basis-3/5"],
                ["4/5", "md:disabled:basis-4/5"],
                ["1/6", "md:disabled:basis-1/6"],
                ["2/6", "md:disabled:basis-2/6"],
                ["3/6", "md:disabled:basis-3/6"],
                ["4/6", "md:disabled:basis-4/6"],
                ["5/6", "md:disabled:basis-5/6"],
                ["1/12", "md:disabled:basis-1/12"],
                ["2/12", "md:disabled:basis-2/12"],
                ["3/12", "md:disabled:basis-3/12"],
                ["4/12", "md:disabled:basis-4/12"],
                ["5/12", "md:disabled:basis-5/12"],
                ["6/12", "md:disabled:basis-6/12"],
                ["7/12", "md:disabled:basis-7/12"],
                ["8/12", "md:disabled:basis-8/12"],
                ["9/12", "md:disabled:basis-9/12"],
                ["10/12", "md:disabled:basis-10/12"],
                ["11/12", "md:disabled:basis-11/12"],
                ["full", "md:disabled:basis-full"],
              ]),
            ],
            [
              "lg",
              new Map<FlexBasis, string>([
                [0, "lg:disabled:basis-0"],
                [1, "lg:disabled:basis-1"],
                [2, "lg:disabled:basis-2"],
                [3, "lg:disabled:basis-3"],
                [4, "lg:disabled:basis-4"],
                [5, "lg:disabled:basis-5"],
                [6, "lg:disabled:basis-6"],
                [7, "lg:disabled:basis-7"],
                [8, "lg:disabled:basis-8"],
                [9, "lg:disabled:basis-9"],
                [10, "lg:disabled:basis-10"],
                [11, "lg:disabled:basis-11"],
                [12, "lg:disabled:basis-12"],
                [14, "lg:disabled:basis-14"],
                [16, "lg:disabled:basis-16"],
                [20, "lg:disabled:basis-20"],
                [24, "lg:disabled:basis-24"],
                [28, "lg:disabled:basis-28"],
                [32, "lg:disabled:basis-32"],
                [36, "lg:disabled:basis-36"],
                [40, "lg:disabled:basis-40"],
                [44, "lg:disabled:basis-44"],
                [48, "lg:disabled:basis-48"],
                [52, "lg:disabled:basis-52"],
                [56, "lg:disabled:basis-56"],
                [60, "lg:disabled:basis-60"],
                [64, "lg:disabled:basis-64"],
                [72, "lg:disabled:basis-72"],
                [80, "lg:disabled:basis-80"],
                [96, "lg:disabled:basis-96"],
                ["auto", "lg:disabled:basis-auto"],
                ["px", "lg:disabled:basis-px"],
                [0.5, "lg:disabled:basis-0.5"],
                [1.5, "lg:disabled:basis-1.5"],
                [2.5, "lg:disabled:basis-2.5"],
                [3.5, "lg:disabled:basis-3.5"],
                ["1/2", "lg:disabled:basis-1/2"],
                ["1/3", "lg:disabled:basis-1/3"],
                ["2/3", "lg:disabled:basis-2/3"],
                ["1/4", "lg:disabled:basis-1/4"],
                ["2/4", "lg:disabled:basis-2/4"],
                ["3/4", "lg:disabled:basis-3/4"],
                ["1/5", "lg:disabled:basis-1/5"],
                ["2/5", "lg:disabled:basis-2/5"],
                ["3/5", "lg:disabled:basis-3/5"],
                ["4/5", "lg:disabled:basis-4/5"],
                ["1/6", "lg:disabled:basis-1/6"],
                ["2/6", "lg:disabled:basis-2/6"],
                ["3/6", "lg:disabled:basis-3/6"],
                ["4/6", "lg:disabled:basis-4/6"],
                ["5/6", "lg:disabled:basis-5/6"],
                ["1/12", "lg:disabled:basis-1/12"],
                ["2/12", "lg:disabled:basis-2/12"],
                ["3/12", "lg:disabled:basis-3/12"],
                ["4/12", "lg:disabled:basis-4/12"],
                ["5/12", "lg:disabled:basis-5/12"],
                ["6/12", "lg:disabled:basis-6/12"],
                ["7/12", "lg:disabled:basis-7/12"],
                ["8/12", "lg:disabled:basis-8/12"],
                ["9/12", "lg:disabled:basis-9/12"],
                ["10/12", "lg:disabled:basis-10/12"],
                ["11/12", "lg:disabled:basis-11/12"],
                ["full", "lg:disabled:basis-full"],
              ]),
            ],
            [
              "xl",
              new Map<FlexBasis, string>([
                [0, "xl:disabled:basis-0"],
                [1, "xl:disabled:basis-1"],
                [2, "xl:disabled:basis-2"],
                [3, "xl:disabled:basis-3"],
                [4, "xl:disabled:basis-4"],
                [5, "xl:disabled:basis-5"],
                [6, "xl:disabled:basis-6"],
                [7, "xl:disabled:basis-7"],
                [8, "xl:disabled:basis-8"],
                [9, "xl:disabled:basis-9"],
                [10, "xl:disabled:basis-10"],
                [11, "xl:disabled:basis-11"],
                [12, "xl:disabled:basis-12"],
                [14, "xl:disabled:basis-14"],
                [16, "xl:disabled:basis-16"],
                [20, "xl:disabled:basis-20"],
                [24, "xl:disabled:basis-24"],
                [28, "xl:disabled:basis-28"],
                [32, "xl:disabled:basis-32"],
                [36, "xl:disabled:basis-36"],
                [40, "xl:disabled:basis-40"],
                [44, "xl:disabled:basis-44"],
                [48, "xl:disabled:basis-48"],
                [52, "xl:disabled:basis-52"],
                [56, "xl:disabled:basis-56"],
                [60, "xl:disabled:basis-60"],
                [64, "xl:disabled:basis-64"],
                [72, "xl:disabled:basis-72"],
                [80, "xl:disabled:basis-80"],
                [96, "xl:disabled:basis-96"],
                ["auto", "xl:disabled:basis-auto"],
                ["px", "xl:disabled:basis-px"],
                [0.5, "xl:disabled:basis-0.5"],
                [1.5, "xl:disabled:basis-1.5"],
                [2.5, "xl:disabled:basis-2.5"],
                [3.5, "xl:disabled:basis-3.5"],
                ["1/2", "xl:disabled:basis-1/2"],
                ["1/3", "xl:disabled:basis-1/3"],
                ["2/3", "xl:disabled:basis-2/3"],
                ["1/4", "xl:disabled:basis-1/4"],
                ["2/4", "xl:disabled:basis-2/4"],
                ["3/4", "xl:disabled:basis-3/4"],
                ["1/5", "xl:disabled:basis-1/5"],
                ["2/5", "xl:disabled:basis-2/5"],
                ["3/5", "xl:disabled:basis-3/5"],
                ["4/5", "xl:disabled:basis-4/5"],
                ["1/6", "xl:disabled:basis-1/6"],
                ["2/6", "xl:disabled:basis-2/6"],
                ["3/6", "xl:disabled:basis-3/6"],
                ["4/6", "xl:disabled:basis-4/6"],
                ["5/6", "xl:disabled:basis-5/6"],
                ["1/12", "xl:disabled:basis-1/12"],
                ["2/12", "xl:disabled:basis-2/12"],
                ["3/12", "xl:disabled:basis-3/12"],
                ["4/12", "xl:disabled:basis-4/12"],
                ["5/12", "xl:disabled:basis-5/12"],
                ["6/12", "xl:disabled:basis-6/12"],
                ["7/12", "xl:disabled:basis-7/12"],
                ["8/12", "xl:disabled:basis-8/12"],
                ["9/12", "xl:disabled:basis-9/12"],
                ["10/12", "xl:disabled:basis-10/12"],
                ["11/12", "xl:disabled:basis-11/12"],
                ["full", "xl:disabled:basis-full"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexBasis, string>>([
            [
              "xs",
              new Map<FlexBasis, string>([
                [0, "xs:hover:basis-0"],
                [1, "xs:hover:basis-1"],
                [2, "xs:hover:basis-2"],
                [3, "xs:hover:basis-3"],
                [4, "xs:hover:basis-4"],
                [5, "xs:hover:basis-5"],
                [6, "xs:hover:basis-6"],
                [7, "xs:hover:basis-7"],
                [8, "xs:hover:basis-8"],
                [9, "xs:hover:basis-9"],
                [10, "xs:hover:basis-10"],
                [11, "xs:hover:basis-11"],
                [12, "xs:hover:basis-12"],
                [14, "xs:hover:basis-14"],
                [16, "xs:hover:basis-16"],
                [20, "xs:hover:basis-20"],
                [24, "xs:hover:basis-24"],
                [28, "xs:hover:basis-28"],
                [32, "xs:hover:basis-32"],
                [36, "xs:hover:basis-36"],
                [40, "xs:hover:basis-40"],
                [44, "xs:hover:basis-44"],
                [48, "xs:hover:basis-48"],
                [52, "xs:hover:basis-52"],
                [56, "xs:hover:basis-56"],
                [60, "xs:hover:basis-60"],
                [64, "xs:hover:basis-64"],
                [72, "xs:hover:basis-72"],
                [80, "xs:hover:basis-80"],
                [96, "xs:hover:basis-96"],
                ["auto", "xs:hover:basis-auto"],
                ["px", "xs:hover:basis-px"],
                [0.5, "xs:hover:basis-0.5"],
                [1.5, "xs:hover:basis-1.5"],
                [2.5, "xs:hover:basis-2.5"],
                [3.5, "xs:hover:basis-3.5"],
                ["1/2", "xs:hover:basis-1/2"],
                ["1/3", "xs:hover:basis-1/3"],
                ["2/3", "xs:hover:basis-2/3"],
                ["1/4", "xs:hover:basis-1/4"],
                ["2/4", "xs:hover:basis-2/4"],
                ["3/4", "xs:hover:basis-3/4"],
                ["1/5", "xs:hover:basis-1/5"],
                ["2/5", "xs:hover:basis-2/5"],
                ["3/5", "xs:hover:basis-3/5"],
                ["4/5", "xs:hover:basis-4/5"],
                ["1/6", "xs:hover:basis-1/6"],
                ["2/6", "xs:hover:basis-2/6"],
                ["3/6", "xs:hover:basis-3/6"],
                ["4/6", "xs:hover:basis-4/6"],
                ["5/6", "xs:hover:basis-5/6"],
                ["1/12", "xs:hover:basis-1/12"],
                ["2/12", "xs:hover:basis-2/12"],
                ["3/12", "xs:hover:basis-3/12"],
                ["4/12", "xs:hover:basis-4/12"],
                ["5/12", "xs:hover:basis-5/12"],
                ["6/12", "xs:hover:basis-6/12"],
                ["7/12", "xs:hover:basis-7/12"],
                ["8/12", "xs:hover:basis-8/12"],
                ["9/12", "xs:hover:basis-9/12"],
                ["10/12", "xs:hover:basis-10/12"],
                ["11/12", "xs:hover:basis-11/12"],
                ["full", "xs:hover:basis-full"],
              ]),
            ],
            [
              "sm",
              new Map<FlexBasis, string>([
                [0, "sm:hover:basis-0"],
                [1, "sm:hover:basis-1"],
                [2, "sm:hover:basis-2"],
                [3, "sm:hover:basis-3"],
                [4, "sm:hover:basis-4"],
                [5, "sm:hover:basis-5"],
                [6, "sm:hover:basis-6"],
                [7, "sm:hover:basis-7"],
                [8, "sm:hover:basis-8"],
                [9, "sm:hover:basis-9"],
                [10, "sm:hover:basis-10"],
                [11, "sm:hover:basis-11"],
                [12, "sm:hover:basis-12"],
                [14, "sm:hover:basis-14"],
                [16, "sm:hover:basis-16"],
                [20, "sm:hover:basis-20"],
                [24, "sm:hover:basis-24"],
                [28, "sm:hover:basis-28"],
                [32, "sm:hover:basis-32"],
                [36, "sm:hover:basis-36"],
                [40, "sm:hover:basis-40"],
                [44, "sm:hover:basis-44"],
                [48, "sm:hover:basis-48"],
                [52, "sm:hover:basis-52"],
                [56, "sm:hover:basis-56"],
                [60, "sm:hover:basis-60"],
                [64, "sm:hover:basis-64"],
                [72, "sm:hover:basis-72"],
                [80, "sm:hover:basis-80"],
                [96, "sm:hover:basis-96"],
                ["auto", "sm:hover:basis-auto"],
                ["px", "sm:hover:basis-px"],
                [0.5, "sm:hover:basis-0.5"],
                [1.5, "sm:hover:basis-1.5"],
                [2.5, "sm:hover:basis-2.5"],
                [3.5, "sm:hover:basis-3.5"],
                ["1/2", "sm:hover:basis-1/2"],
                ["1/3", "sm:hover:basis-1/3"],
                ["2/3", "sm:hover:basis-2/3"],
                ["1/4", "sm:hover:basis-1/4"],
                ["2/4", "sm:hover:basis-2/4"],
                ["3/4", "sm:hover:basis-3/4"],
                ["1/5", "sm:hover:basis-1/5"],
                ["2/5", "sm:hover:basis-2/5"],
                ["3/5", "sm:hover:basis-3/5"],
                ["4/5", "sm:hover:basis-4/5"],
                ["1/6", "sm:hover:basis-1/6"],
                ["2/6", "sm:hover:basis-2/6"],
                ["3/6", "sm:hover:basis-3/6"],
                ["4/6", "sm:hover:basis-4/6"],
                ["5/6", "sm:hover:basis-5/6"],
                ["1/12", "sm:hover:basis-1/12"],
                ["2/12", "sm:hover:basis-2/12"],
                ["3/12", "sm:hover:basis-3/12"],
                ["4/12", "sm:hover:basis-4/12"],
                ["5/12", "sm:hover:basis-5/12"],
                ["6/12", "sm:hover:basis-6/12"],
                ["7/12", "sm:hover:basis-7/12"],
                ["8/12", "sm:hover:basis-8/12"],
                ["9/12", "sm:hover:basis-9/12"],
                ["10/12", "sm:hover:basis-10/12"],
                ["11/12", "sm:hover:basis-11/12"],
                ["full", "sm:hover:basis-full"],
              ]),
            ],
            [
              "md",
              new Map<FlexBasis, string>([
                [0, "md:hover:basis-0"],
                [1, "md:hover:basis-1"],
                [2, "md:hover:basis-2"],
                [3, "md:hover:basis-3"],
                [4, "md:hover:basis-4"],
                [5, "md:hover:basis-5"],
                [6, "md:hover:basis-6"],
                [7, "md:hover:basis-7"],
                [8, "md:hover:basis-8"],
                [9, "md:hover:basis-9"],
                [10, "md:hover:basis-10"],
                [11, "md:hover:basis-11"],
                [12, "md:hover:basis-12"],
                [14, "md:hover:basis-14"],
                [16, "md:hover:basis-16"],
                [20, "md:hover:basis-20"],
                [24, "md:hover:basis-24"],
                [28, "md:hover:basis-28"],
                [32, "md:hover:basis-32"],
                [36, "md:hover:basis-36"],
                [40, "md:hover:basis-40"],
                [44, "md:hover:basis-44"],
                [48, "md:hover:basis-48"],
                [52, "md:hover:basis-52"],
                [56, "md:hover:basis-56"],
                [60, "md:hover:basis-60"],
                [64, "md:hover:basis-64"],
                [72, "md:hover:basis-72"],
                [80, "md:hover:basis-80"],
                [96, "md:hover:basis-96"],
                ["auto", "md:hover:basis-auto"],
                ["px", "md:hover:basis-px"],
                [0.5, "md:hover:basis-0.5"],
                [1.5, "md:hover:basis-1.5"],
                [2.5, "md:hover:basis-2.5"],
                [3.5, "md:hover:basis-3.5"],
                ["1/2", "md:hover:basis-1/2"],
                ["1/3", "md:hover:basis-1/3"],
                ["2/3", "md:hover:basis-2/3"],
                ["1/4", "md:hover:basis-1/4"],
                ["2/4", "md:hover:basis-2/4"],
                ["3/4", "md:hover:basis-3/4"],
                ["1/5", "md:hover:basis-1/5"],
                ["2/5", "md:hover:basis-2/5"],
                ["3/5", "md:hover:basis-3/5"],
                ["4/5", "md:hover:basis-4/5"],
                ["1/6", "md:hover:basis-1/6"],
                ["2/6", "md:hover:basis-2/6"],
                ["3/6", "md:hover:basis-3/6"],
                ["4/6", "md:hover:basis-4/6"],
                ["5/6", "md:hover:basis-5/6"],
                ["1/12", "md:hover:basis-1/12"],
                ["2/12", "md:hover:basis-2/12"],
                ["3/12", "md:hover:basis-3/12"],
                ["4/12", "md:hover:basis-4/12"],
                ["5/12", "md:hover:basis-5/12"],
                ["6/12", "md:hover:basis-6/12"],
                ["7/12", "md:hover:basis-7/12"],
                ["8/12", "md:hover:basis-8/12"],
                ["9/12", "md:hover:basis-9/12"],
                ["10/12", "md:hover:basis-10/12"],
                ["11/12", "md:hover:basis-11/12"],
                ["full", "md:hover:basis-full"],
              ]),
            ],
            [
              "lg",
              new Map<FlexBasis, string>([
                [0, "lg:hover:basis-0"],
                [1, "lg:hover:basis-1"],
                [2, "lg:hover:basis-2"],
                [3, "lg:hover:basis-3"],
                [4, "lg:hover:basis-4"],
                [5, "lg:hover:basis-5"],
                [6, "lg:hover:basis-6"],
                [7, "lg:hover:basis-7"],
                [8, "lg:hover:basis-8"],
                [9, "lg:hover:basis-9"],
                [10, "lg:hover:basis-10"],
                [11, "lg:hover:basis-11"],
                [12, "lg:hover:basis-12"],
                [14, "lg:hover:basis-14"],
                [16, "lg:hover:basis-16"],
                [20, "lg:hover:basis-20"],
                [24, "lg:hover:basis-24"],
                [28, "lg:hover:basis-28"],
                [32, "lg:hover:basis-32"],
                [36, "lg:hover:basis-36"],
                [40, "lg:hover:basis-40"],
                [44, "lg:hover:basis-44"],
                [48, "lg:hover:basis-48"],
                [52, "lg:hover:basis-52"],
                [56, "lg:hover:basis-56"],
                [60, "lg:hover:basis-60"],
                [64, "lg:hover:basis-64"],
                [72, "lg:hover:basis-72"],
                [80, "lg:hover:basis-80"],
                [96, "lg:hover:basis-96"],
                ["auto", "lg:hover:basis-auto"],
                ["px", "lg:hover:basis-px"],
                [0.5, "lg:hover:basis-0.5"],
                [1.5, "lg:hover:basis-1.5"],
                [2.5, "lg:hover:basis-2.5"],
                [3.5, "lg:hover:basis-3.5"],
                ["1/2", "lg:hover:basis-1/2"],
                ["1/3", "lg:hover:basis-1/3"],
                ["2/3", "lg:hover:basis-2/3"],
                ["1/4", "lg:hover:basis-1/4"],
                ["2/4", "lg:hover:basis-2/4"],
                ["3/4", "lg:hover:basis-3/4"],
                ["1/5", "lg:hover:basis-1/5"],
                ["2/5", "lg:hover:basis-2/5"],
                ["3/5", "lg:hover:basis-3/5"],
                ["4/5", "lg:hover:basis-4/5"],
                ["1/6", "lg:hover:basis-1/6"],
                ["2/6", "lg:hover:basis-2/6"],
                ["3/6", "lg:hover:basis-3/6"],
                ["4/6", "lg:hover:basis-4/6"],
                ["5/6", "lg:hover:basis-5/6"],
                ["1/12", "lg:hover:basis-1/12"],
                ["2/12", "lg:hover:basis-2/12"],
                ["3/12", "lg:hover:basis-3/12"],
                ["4/12", "lg:hover:basis-4/12"],
                ["5/12", "lg:hover:basis-5/12"],
                ["6/12", "lg:hover:basis-6/12"],
                ["7/12", "lg:hover:basis-7/12"],
                ["8/12", "lg:hover:basis-8/12"],
                ["9/12", "lg:hover:basis-9/12"],
                ["10/12", "lg:hover:basis-10/12"],
                ["11/12", "lg:hover:basis-11/12"],
                ["full", "lg:hover:basis-full"],
              ]),
            ],
            [
              "xl",
              new Map<FlexBasis, string>([
                [0, "xl:hover:basis-0"],
                [1, "xl:hover:basis-1"],
                [2, "xl:hover:basis-2"],
                [3, "xl:hover:basis-3"],
                [4, "xl:hover:basis-4"],
                [5, "xl:hover:basis-5"],
                [6, "xl:hover:basis-6"],
                [7, "xl:hover:basis-7"],
                [8, "xl:hover:basis-8"],
                [9, "xl:hover:basis-9"],
                [10, "xl:hover:basis-10"],
                [11, "xl:hover:basis-11"],
                [12, "xl:hover:basis-12"],
                [14, "xl:hover:basis-14"],
                [16, "xl:hover:basis-16"],
                [20, "xl:hover:basis-20"],
                [24, "xl:hover:basis-24"],
                [28, "xl:hover:basis-28"],
                [32, "xl:hover:basis-32"],
                [36, "xl:hover:basis-36"],
                [40, "xl:hover:basis-40"],
                [44, "xl:hover:basis-44"],
                [48, "xl:hover:basis-48"],
                [52, "xl:hover:basis-52"],
                [56, "xl:hover:basis-56"],
                [60, "xl:hover:basis-60"],
                [64, "xl:hover:basis-64"],
                [72, "xl:hover:basis-72"],
                [80, "xl:hover:basis-80"],
                [96, "xl:hover:basis-96"],
                ["auto", "xl:hover:basis-auto"],
                ["px", "xl:hover:basis-px"],
                [0.5, "xl:hover:basis-0.5"],
                [1.5, "xl:hover:basis-1.5"],
                [2.5, "xl:hover:basis-2.5"],
                [3.5, "xl:hover:basis-3.5"],
                ["1/2", "xl:hover:basis-1/2"],
                ["1/3", "xl:hover:basis-1/3"],
                ["2/3", "xl:hover:basis-2/3"],
                ["1/4", "xl:hover:basis-1/4"],
                ["2/4", "xl:hover:basis-2/4"],
                ["3/4", "xl:hover:basis-3/4"],
                ["1/5", "xl:hover:basis-1/5"],
                ["2/5", "xl:hover:basis-2/5"],
                ["3/5", "xl:hover:basis-3/5"],
                ["4/5", "xl:hover:basis-4/5"],
                ["1/6", "xl:hover:basis-1/6"],
                ["2/6", "xl:hover:basis-2/6"],
                ["3/6", "xl:hover:basis-3/6"],
                ["4/6", "xl:hover:basis-4/6"],
                ["5/6", "xl:hover:basis-5/6"],
                ["1/12", "xl:hover:basis-1/12"],
                ["2/12", "xl:hover:basis-2/12"],
                ["3/12", "xl:hover:basis-3/12"],
                ["4/12", "xl:hover:basis-4/12"],
                ["5/12", "xl:hover:basis-5/12"],
                ["6/12", "xl:hover:basis-6/12"],
                ["7/12", "xl:hover:basis-7/12"],
                ["8/12", "xl:hover:basis-8/12"],
                ["9/12", "xl:hover:basis-9/12"],
                ["10/12", "xl:hover:basis-10/12"],
                ["11/12", "xl:hover:basis-11/12"],
                ["full", "xl:hover:basis-full"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexBasis, string>>([
            [
              "xs",
              new Map<FlexBasis, string>([
                [0, "xs:basis-0"],
                [1, "xs:basis-1"],
                [2, "xs:basis-2"],
                [3, "xs:basis-3"],
                [4, "xs:basis-4"],
                [5, "xs:basis-5"],
                [6, "xs:basis-6"],
                [7, "xs:basis-7"],
                [8, "xs:basis-8"],
                [9, "xs:basis-9"],
                [10, "xs:basis-10"],
                [11, "xs:basis-11"],
                [12, "xs:basis-12"],
                [14, "xs:basis-14"],
                [16, "xs:basis-16"],
                [20, "xs:basis-20"],
                [24, "xs:basis-24"],
                [28, "xs:basis-28"],
                [32, "xs:basis-32"],
                [36, "xs:basis-36"],
                [40, "xs:basis-40"],
                [44, "xs:basis-44"],
                [48, "xs:basis-48"],
                [52, "xs:basis-52"],
                [56, "xs:basis-56"],
                [60, "xs:basis-60"],
                [64, "xs:basis-64"],
                [72, "xs:basis-72"],
                [80, "xs:basis-80"],
                [96, "xs:basis-96"],
                ["auto", "xs:basis-auto"],
                ["px", "xs:basis-px"],
                [0.5, "xs:basis-0.5"],
                [1.5, "xs:basis-1.5"],
                [2.5, "xs:basis-2.5"],
                [3.5, "xs:basis-3.5"],
                ["1/2", "xs:basis-1/2"],
                ["1/3", "xs:basis-1/3"],
                ["2/3", "xs:basis-2/3"],
                ["1/4", "xs:basis-1/4"],
                ["2/4", "xs:basis-2/4"],
                ["3/4", "xs:basis-3/4"],
                ["1/5", "xs:basis-1/5"],
                ["2/5", "xs:basis-2/5"],
                ["3/5", "xs:basis-3/5"],
                ["4/5", "xs:basis-4/5"],
                ["1/6", "xs:basis-1/6"],
                ["2/6", "xs:basis-2/6"],
                ["3/6", "xs:basis-3/6"],
                ["4/6", "xs:basis-4/6"],
                ["5/6", "xs:basis-5/6"],
                ["1/12", "xs:basis-1/12"],
                ["2/12", "xs:basis-2/12"],
                ["3/12", "xs:basis-3/12"],
                ["4/12", "xs:basis-4/12"],
                ["5/12", "xs:basis-5/12"],
                ["6/12", "xs:basis-6/12"],
                ["7/12", "xs:basis-7/12"],
                ["8/12", "xs:basis-8/12"],
                ["9/12", "xs:basis-9/12"],
                ["10/12", "xs:basis-10/12"],
                ["11/12", "xs:basis-11/12"],
                ["full", "xs:basis-full"],
              ]),
            ],
            [
              "sm",
              new Map<FlexBasis, string>([
                [0, "sm:basis-0"],
                [1, "sm:basis-1"],
                [2, "sm:basis-2"],
                [3, "sm:basis-3"],
                [4, "sm:basis-4"],
                [5, "sm:basis-5"],
                [6, "sm:basis-6"],
                [7, "sm:basis-7"],
                [8, "sm:basis-8"],
                [9, "sm:basis-9"],
                [10, "sm:basis-10"],
                [11, "sm:basis-11"],
                [12, "sm:basis-12"],
                [14, "sm:basis-14"],
                [16, "sm:basis-16"],
                [20, "sm:basis-20"],
                [24, "sm:basis-24"],
                [28, "sm:basis-28"],
                [32, "sm:basis-32"],
                [36, "sm:basis-36"],
                [40, "sm:basis-40"],
                [44, "sm:basis-44"],
                [48, "sm:basis-48"],
                [52, "sm:basis-52"],
                [56, "sm:basis-56"],
                [60, "sm:basis-60"],
                [64, "sm:basis-64"],
                [72, "sm:basis-72"],
                [80, "sm:basis-80"],
                [96, "sm:basis-96"],
                ["auto", "sm:basis-auto"],
                ["px", "sm:basis-px"],
                [0.5, "sm:basis-0.5"],
                [1.5, "sm:basis-1.5"],
                [2.5, "sm:basis-2.5"],
                [3.5, "sm:basis-3.5"],
                ["1/2", "sm:basis-1/2"],
                ["1/3", "sm:basis-1/3"],
                ["2/3", "sm:basis-2/3"],
                ["1/4", "sm:basis-1/4"],
                ["2/4", "sm:basis-2/4"],
                ["3/4", "sm:basis-3/4"],
                ["1/5", "sm:basis-1/5"],
                ["2/5", "sm:basis-2/5"],
                ["3/5", "sm:basis-3/5"],
                ["4/5", "sm:basis-4/5"],
                ["1/6", "sm:basis-1/6"],
                ["2/6", "sm:basis-2/6"],
                ["3/6", "sm:basis-3/6"],
                ["4/6", "sm:basis-4/6"],
                ["5/6", "sm:basis-5/6"],
                ["1/12", "sm:basis-1/12"],
                ["2/12", "sm:basis-2/12"],
                ["3/12", "sm:basis-3/12"],
                ["4/12", "sm:basis-4/12"],
                ["5/12", "sm:basis-5/12"],
                ["6/12", "sm:basis-6/12"],
                ["7/12", "sm:basis-7/12"],
                ["8/12", "sm:basis-8/12"],
                ["9/12", "sm:basis-9/12"],
                ["10/12", "sm:basis-10/12"],
                ["11/12", "sm:basis-11/12"],
                ["full", "sm:basis-full"],
              ]),
            ],
            [
              "md",
              new Map<FlexBasis, string>([
                [0, "md:basis-0"],
                [1, "md:basis-1"],
                [2, "md:basis-2"],
                [3, "md:basis-3"],
                [4, "md:basis-4"],
                [5, "md:basis-5"],
                [6, "md:basis-6"],
                [7, "md:basis-7"],
                [8, "md:basis-8"],
                [9, "md:basis-9"],
                [10, "md:basis-10"],
                [11, "md:basis-11"],
                [12, "md:basis-12"],
                [14, "md:basis-14"],
                [16, "md:basis-16"],
                [20, "md:basis-20"],
                [24, "md:basis-24"],
                [28, "md:basis-28"],
                [32, "md:basis-32"],
                [36, "md:basis-36"],
                [40, "md:basis-40"],
                [44, "md:basis-44"],
                [48, "md:basis-48"],
                [52, "md:basis-52"],
                [56, "md:basis-56"],
                [60, "md:basis-60"],
                [64, "md:basis-64"],
                [72, "md:basis-72"],
                [80, "md:basis-80"],
                [96, "md:basis-96"],
                ["auto", "md:basis-auto"],
                ["px", "md:basis-px"],
                [0.5, "md:basis-0.5"],
                [1.5, "md:basis-1.5"],
                [2.5, "md:basis-2.5"],
                [3.5, "md:basis-3.5"],
                ["1/2", "md:basis-1/2"],
                ["1/3", "md:basis-1/3"],
                ["2/3", "md:basis-2/3"],
                ["1/4", "md:basis-1/4"],
                ["2/4", "md:basis-2/4"],
                ["3/4", "md:basis-3/4"],
                ["1/5", "md:basis-1/5"],
                ["2/5", "md:basis-2/5"],
                ["3/5", "md:basis-3/5"],
                ["4/5", "md:basis-4/5"],
                ["1/6", "md:basis-1/6"],
                ["2/6", "md:basis-2/6"],
                ["3/6", "md:basis-3/6"],
                ["4/6", "md:basis-4/6"],
                ["5/6", "md:basis-5/6"],
                ["1/12", "md:basis-1/12"],
                ["2/12", "md:basis-2/12"],
                ["3/12", "md:basis-3/12"],
                ["4/12", "md:basis-4/12"],
                ["5/12", "md:basis-5/12"],
                ["6/12", "md:basis-6/12"],
                ["7/12", "md:basis-7/12"],
                ["8/12", "md:basis-8/12"],
                ["9/12", "md:basis-9/12"],
                ["10/12", "md:basis-10/12"],
                ["11/12", "md:basis-11/12"],
                ["full", "md:basis-full"],
              ]),
            ],
            [
              "lg",
              new Map<FlexBasis, string>([
                [0, "lg:basis-0"],
                [1, "lg:basis-1"],
                [2, "lg:basis-2"],
                [3, "lg:basis-3"],
                [4, "lg:basis-4"],
                [5, "lg:basis-5"],
                [6, "lg:basis-6"],
                [7, "lg:basis-7"],
                [8, "lg:basis-8"],
                [9, "lg:basis-9"],
                [10, "lg:basis-10"],
                [11, "lg:basis-11"],
                [12, "lg:basis-12"],
                [14, "lg:basis-14"],
                [16, "lg:basis-16"],
                [20, "lg:basis-20"],
                [24, "lg:basis-24"],
                [28, "lg:basis-28"],
                [32, "lg:basis-32"],
                [36, "lg:basis-36"],
                [40, "lg:basis-40"],
                [44, "lg:basis-44"],
                [48, "lg:basis-48"],
                [52, "lg:basis-52"],
                [56, "lg:basis-56"],
                [60, "lg:basis-60"],
                [64, "lg:basis-64"],
                [72, "lg:basis-72"],
                [80, "lg:basis-80"],
                [96, "lg:basis-96"],
                ["auto", "lg:basis-auto"],
                ["px", "lg:basis-px"],
                [0.5, "lg:basis-0.5"],
                [1.5, "lg:basis-1.5"],
                [2.5, "lg:basis-2.5"],
                [3.5, "lg:basis-3.5"],
                ["1/2", "lg:basis-1/2"],
                ["1/3", "lg:basis-1/3"],
                ["2/3", "lg:basis-2/3"],
                ["1/4", "lg:basis-1/4"],
                ["2/4", "lg:basis-2/4"],
                ["3/4", "lg:basis-3/4"],
                ["1/5", "lg:basis-1/5"],
                ["2/5", "lg:basis-2/5"],
                ["3/5", "lg:basis-3/5"],
                ["4/5", "lg:basis-4/5"],
                ["1/6", "lg:basis-1/6"],
                ["2/6", "lg:basis-2/6"],
                ["3/6", "lg:basis-3/6"],
                ["4/6", "lg:basis-4/6"],
                ["5/6", "lg:basis-5/6"],
                ["1/12", "lg:basis-1/12"],
                ["2/12", "lg:basis-2/12"],
                ["3/12", "lg:basis-3/12"],
                ["4/12", "lg:basis-4/12"],
                ["5/12", "lg:basis-5/12"],
                ["6/12", "lg:basis-6/12"],
                ["7/12", "lg:basis-7/12"],
                ["8/12", "lg:basis-8/12"],
                ["9/12", "lg:basis-9/12"],
                ["10/12", "lg:basis-10/12"],
                ["11/12", "lg:basis-11/12"],
                ["full", "lg:basis-full"],
              ]),
            ],
            [
              "xl",
              new Map<FlexBasis, string>([
                [0, "xl:basis-0"],
                [1, "xl:basis-1"],
                [2, "xl:basis-2"],
                [3, "xl:basis-3"],
                [4, "xl:basis-4"],
                [5, "xl:basis-5"],
                [6, "xl:basis-6"],
                [7, "xl:basis-7"],
                [8, "xl:basis-8"],
                [9, "xl:basis-9"],
                [10, "xl:basis-10"],
                [11, "xl:basis-11"],
                [12, "xl:basis-12"],
                [14, "xl:basis-14"],
                [16, "xl:basis-16"],
                [20, "xl:basis-20"],
                [24, "xl:basis-24"],
                [28, "xl:basis-28"],
                [32, "xl:basis-32"],
                [36, "xl:basis-36"],
                [40, "xl:basis-40"],
                [44, "xl:basis-44"],
                [48, "xl:basis-48"],
                [52, "xl:basis-52"],
                [56, "xl:basis-56"],
                [60, "xl:basis-60"],
                [64, "xl:basis-64"],
                [72, "xl:basis-72"],
                [80, "xl:basis-80"],
                [96, "xl:basis-96"],
                ["auto", "xl:basis-auto"],
                ["px", "xl:basis-px"],
                [0.5, "xl:basis-0.5"],
                [1.5, "xl:basis-1.5"],
                [2.5, "xl:basis-2.5"],
                [3.5, "xl:basis-3.5"],
                ["1/2", "xl:basis-1/2"],
                ["1/3", "xl:basis-1/3"],
                ["2/3", "xl:basis-2/3"],
                ["1/4", "xl:basis-1/4"],
                ["2/4", "xl:basis-2/4"],
                ["3/4", "xl:basis-3/4"],
                ["1/5", "xl:basis-1/5"],
                ["2/5", "xl:basis-2/5"],
                ["3/5", "xl:basis-3/5"],
                ["4/5", "xl:basis-4/5"],
                ["1/6", "xl:basis-1/6"],
                ["2/6", "xl:basis-2/6"],
                ["3/6", "xl:basis-3/6"],
                ["4/6", "xl:basis-4/6"],
                ["5/6", "xl:basis-5/6"],
                ["1/12", "xl:basis-1/12"],
                ["2/12", "xl:basis-2/12"],
                ["3/12", "xl:basis-3/12"],
                ["4/12", "xl:basis-4/12"],
                ["5/12", "xl:basis-5/12"],
                ["6/12", "xl:basis-6/12"],
                ["7/12", "xl:basis-7/12"],
                ["8/12", "xl:basis-8/12"],
                ["9/12", "xl:basis-9/12"],
                ["10/12", "xl:basis-10/12"],
                ["11/12", "xl:basis-11/12"],
                ["full", "xl:basis-full"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexBasis, string>>([
            [
              "xs",
              new Map<FlexBasis, string>([
                [0, "xs:open:basis-0"],
                [1, "xs:open:basis-1"],
                [2, "xs:open:basis-2"],
                [3, "xs:open:basis-3"],
                [4, "xs:open:basis-4"],
                [5, "xs:open:basis-5"],
                [6, "xs:open:basis-6"],
                [7, "xs:open:basis-7"],
                [8, "xs:open:basis-8"],
                [9, "xs:open:basis-9"],
                [10, "xs:open:basis-10"],
                [11, "xs:open:basis-11"],
                [12, "xs:open:basis-12"],
                [14, "xs:open:basis-14"],
                [16, "xs:open:basis-16"],
                [20, "xs:open:basis-20"],
                [24, "xs:open:basis-24"],
                [28, "xs:open:basis-28"],
                [32, "xs:open:basis-32"],
                [36, "xs:open:basis-36"],
                [40, "xs:open:basis-40"],
                [44, "xs:open:basis-44"],
                [48, "xs:open:basis-48"],
                [52, "xs:open:basis-52"],
                [56, "xs:open:basis-56"],
                [60, "xs:open:basis-60"],
                [64, "xs:open:basis-64"],
                [72, "xs:open:basis-72"],
                [80, "xs:open:basis-80"],
                [96, "xs:open:basis-96"],
                ["auto", "xs:open:basis-auto"],
                ["px", "xs:open:basis-px"],
                [0.5, "xs:open:basis-0.5"],
                [1.5, "xs:open:basis-1.5"],
                [2.5, "xs:open:basis-2.5"],
                [3.5, "xs:open:basis-3.5"],
                ["1/2", "xs:open:basis-1/2"],
                ["1/3", "xs:open:basis-1/3"],
                ["2/3", "xs:open:basis-2/3"],
                ["1/4", "xs:open:basis-1/4"],
                ["2/4", "xs:open:basis-2/4"],
                ["3/4", "xs:open:basis-3/4"],
                ["1/5", "xs:open:basis-1/5"],
                ["2/5", "xs:open:basis-2/5"],
                ["3/5", "xs:open:basis-3/5"],
                ["4/5", "xs:open:basis-4/5"],
                ["1/6", "xs:open:basis-1/6"],
                ["2/6", "xs:open:basis-2/6"],
                ["3/6", "xs:open:basis-3/6"],
                ["4/6", "xs:open:basis-4/6"],
                ["5/6", "xs:open:basis-5/6"],
                ["1/12", "xs:open:basis-1/12"],
                ["2/12", "xs:open:basis-2/12"],
                ["3/12", "xs:open:basis-3/12"],
                ["4/12", "xs:open:basis-4/12"],
                ["5/12", "xs:open:basis-5/12"],
                ["6/12", "xs:open:basis-6/12"],
                ["7/12", "xs:open:basis-7/12"],
                ["8/12", "xs:open:basis-8/12"],
                ["9/12", "xs:open:basis-9/12"],
                ["10/12", "xs:open:basis-10/12"],
                ["11/12", "xs:open:basis-11/12"],
                ["full", "xs:open:basis-full"],
              ]),
            ],
            [
              "sm",
              new Map<FlexBasis, string>([
                [0, "sm:open:basis-0"],
                [1, "sm:open:basis-1"],
                [2, "sm:open:basis-2"],
                [3, "sm:open:basis-3"],
                [4, "sm:open:basis-4"],
                [5, "sm:open:basis-5"],
                [6, "sm:open:basis-6"],
                [7, "sm:open:basis-7"],
                [8, "sm:open:basis-8"],
                [9, "sm:open:basis-9"],
                [10, "sm:open:basis-10"],
                [11, "sm:open:basis-11"],
                [12, "sm:open:basis-12"],
                [14, "sm:open:basis-14"],
                [16, "sm:open:basis-16"],
                [20, "sm:open:basis-20"],
                [24, "sm:open:basis-24"],
                [28, "sm:open:basis-28"],
                [32, "sm:open:basis-32"],
                [36, "sm:open:basis-36"],
                [40, "sm:open:basis-40"],
                [44, "sm:open:basis-44"],
                [48, "sm:open:basis-48"],
                [52, "sm:open:basis-52"],
                [56, "sm:open:basis-56"],
                [60, "sm:open:basis-60"],
                [64, "sm:open:basis-64"],
                [72, "sm:open:basis-72"],
                [80, "sm:open:basis-80"],
                [96, "sm:open:basis-96"],
                ["auto", "sm:open:basis-auto"],
                ["px", "sm:open:basis-px"],
                [0.5, "sm:open:basis-0.5"],
                [1.5, "sm:open:basis-1.5"],
                [2.5, "sm:open:basis-2.5"],
                [3.5, "sm:open:basis-3.5"],
                ["1/2", "sm:open:basis-1/2"],
                ["1/3", "sm:open:basis-1/3"],
                ["2/3", "sm:open:basis-2/3"],
                ["1/4", "sm:open:basis-1/4"],
                ["2/4", "sm:open:basis-2/4"],
                ["3/4", "sm:open:basis-3/4"],
                ["1/5", "sm:open:basis-1/5"],
                ["2/5", "sm:open:basis-2/5"],
                ["3/5", "sm:open:basis-3/5"],
                ["4/5", "sm:open:basis-4/5"],
                ["1/6", "sm:open:basis-1/6"],
                ["2/6", "sm:open:basis-2/6"],
                ["3/6", "sm:open:basis-3/6"],
                ["4/6", "sm:open:basis-4/6"],
                ["5/6", "sm:open:basis-5/6"],
                ["1/12", "sm:open:basis-1/12"],
                ["2/12", "sm:open:basis-2/12"],
                ["3/12", "sm:open:basis-3/12"],
                ["4/12", "sm:open:basis-4/12"],
                ["5/12", "sm:open:basis-5/12"],
                ["6/12", "sm:open:basis-6/12"],
                ["7/12", "sm:open:basis-7/12"],
                ["8/12", "sm:open:basis-8/12"],
                ["9/12", "sm:open:basis-9/12"],
                ["10/12", "sm:open:basis-10/12"],
                ["11/12", "sm:open:basis-11/12"],
                ["full", "sm:open:basis-full"],
              ]),
            ],
            [
              "md",
              new Map<FlexBasis, string>([
                [0, "md:open:basis-0"],
                [1, "md:open:basis-1"],
                [2, "md:open:basis-2"],
                [3, "md:open:basis-3"],
                [4, "md:open:basis-4"],
                [5, "md:open:basis-5"],
                [6, "md:open:basis-6"],
                [7, "md:open:basis-7"],
                [8, "md:open:basis-8"],
                [9, "md:open:basis-9"],
                [10, "md:open:basis-10"],
                [11, "md:open:basis-11"],
                [12, "md:open:basis-12"],
                [14, "md:open:basis-14"],
                [16, "md:open:basis-16"],
                [20, "md:open:basis-20"],
                [24, "md:open:basis-24"],
                [28, "md:open:basis-28"],
                [32, "md:open:basis-32"],
                [36, "md:open:basis-36"],
                [40, "md:open:basis-40"],
                [44, "md:open:basis-44"],
                [48, "md:open:basis-48"],
                [52, "md:open:basis-52"],
                [56, "md:open:basis-56"],
                [60, "md:open:basis-60"],
                [64, "md:open:basis-64"],
                [72, "md:open:basis-72"],
                [80, "md:open:basis-80"],
                [96, "md:open:basis-96"],
                ["auto", "md:open:basis-auto"],
                ["px", "md:open:basis-px"],
                [0.5, "md:open:basis-0.5"],
                [1.5, "md:open:basis-1.5"],
                [2.5, "md:open:basis-2.5"],
                [3.5, "md:open:basis-3.5"],
                ["1/2", "md:open:basis-1/2"],
                ["1/3", "md:open:basis-1/3"],
                ["2/3", "md:open:basis-2/3"],
                ["1/4", "md:open:basis-1/4"],
                ["2/4", "md:open:basis-2/4"],
                ["3/4", "md:open:basis-3/4"],
                ["1/5", "md:open:basis-1/5"],
                ["2/5", "md:open:basis-2/5"],
                ["3/5", "md:open:basis-3/5"],
                ["4/5", "md:open:basis-4/5"],
                ["1/6", "md:open:basis-1/6"],
                ["2/6", "md:open:basis-2/6"],
                ["3/6", "md:open:basis-3/6"],
                ["4/6", "md:open:basis-4/6"],
                ["5/6", "md:open:basis-5/6"],
                ["1/12", "md:open:basis-1/12"],
                ["2/12", "md:open:basis-2/12"],
                ["3/12", "md:open:basis-3/12"],
                ["4/12", "md:open:basis-4/12"],
                ["5/12", "md:open:basis-5/12"],
                ["6/12", "md:open:basis-6/12"],
                ["7/12", "md:open:basis-7/12"],
                ["8/12", "md:open:basis-8/12"],
                ["9/12", "md:open:basis-9/12"],
                ["10/12", "md:open:basis-10/12"],
                ["11/12", "md:open:basis-11/12"],
                ["full", "md:open:basis-full"],
              ]),
            ],
            [
              "lg",
              new Map<FlexBasis, string>([
                [0, "lg:open:basis-0"],
                [1, "lg:open:basis-1"],
                [2, "lg:open:basis-2"],
                [3, "lg:open:basis-3"],
                [4, "lg:open:basis-4"],
                [5, "lg:open:basis-5"],
                [6, "lg:open:basis-6"],
                [7, "lg:open:basis-7"],
                [8, "lg:open:basis-8"],
                [9, "lg:open:basis-9"],
                [10, "lg:open:basis-10"],
                [11, "lg:open:basis-11"],
                [12, "lg:open:basis-12"],
                [14, "lg:open:basis-14"],
                [16, "lg:open:basis-16"],
                [20, "lg:open:basis-20"],
                [24, "lg:open:basis-24"],
                [28, "lg:open:basis-28"],
                [32, "lg:open:basis-32"],
                [36, "lg:open:basis-36"],
                [40, "lg:open:basis-40"],
                [44, "lg:open:basis-44"],
                [48, "lg:open:basis-48"],
                [52, "lg:open:basis-52"],
                [56, "lg:open:basis-56"],
                [60, "lg:open:basis-60"],
                [64, "lg:open:basis-64"],
                [72, "lg:open:basis-72"],
                [80, "lg:open:basis-80"],
                [96, "lg:open:basis-96"],
                ["auto", "lg:open:basis-auto"],
                ["px", "lg:open:basis-px"],
                [0.5, "lg:open:basis-0.5"],
                [1.5, "lg:open:basis-1.5"],
                [2.5, "lg:open:basis-2.5"],
                [3.5, "lg:open:basis-3.5"],
                ["1/2", "lg:open:basis-1/2"],
                ["1/3", "lg:open:basis-1/3"],
                ["2/3", "lg:open:basis-2/3"],
                ["1/4", "lg:open:basis-1/4"],
                ["2/4", "lg:open:basis-2/4"],
                ["3/4", "lg:open:basis-3/4"],
                ["1/5", "lg:open:basis-1/5"],
                ["2/5", "lg:open:basis-2/5"],
                ["3/5", "lg:open:basis-3/5"],
                ["4/5", "lg:open:basis-4/5"],
                ["1/6", "lg:open:basis-1/6"],
                ["2/6", "lg:open:basis-2/6"],
                ["3/6", "lg:open:basis-3/6"],
                ["4/6", "lg:open:basis-4/6"],
                ["5/6", "lg:open:basis-5/6"],
                ["1/12", "lg:open:basis-1/12"],
                ["2/12", "lg:open:basis-2/12"],
                ["3/12", "lg:open:basis-3/12"],
                ["4/12", "lg:open:basis-4/12"],
                ["5/12", "lg:open:basis-5/12"],
                ["6/12", "lg:open:basis-6/12"],
                ["7/12", "lg:open:basis-7/12"],
                ["8/12", "lg:open:basis-8/12"],
                ["9/12", "lg:open:basis-9/12"],
                ["10/12", "lg:open:basis-10/12"],
                ["11/12", "lg:open:basis-11/12"],
                ["full", "lg:open:basis-full"],
              ]),
            ],
            [
              "xl",
              new Map<FlexBasis, string>([
                [0, "xl:open:basis-0"],
                [1, "xl:open:basis-1"],
                [2, "xl:open:basis-2"],
                [3, "xl:open:basis-3"],
                [4, "xl:open:basis-4"],
                [5, "xl:open:basis-5"],
                [6, "xl:open:basis-6"],
                [7, "xl:open:basis-7"],
                [8, "xl:open:basis-8"],
                [9, "xl:open:basis-9"],
                [10, "xl:open:basis-10"],
                [11, "xl:open:basis-11"],
                [12, "xl:open:basis-12"],
                [14, "xl:open:basis-14"],
                [16, "xl:open:basis-16"],
                [20, "xl:open:basis-20"],
                [24, "xl:open:basis-24"],
                [28, "xl:open:basis-28"],
                [32, "xl:open:basis-32"],
                [36, "xl:open:basis-36"],
                [40, "xl:open:basis-40"],
                [44, "xl:open:basis-44"],
                [48, "xl:open:basis-48"],
                [52, "xl:open:basis-52"],
                [56, "xl:open:basis-56"],
                [60, "xl:open:basis-60"],
                [64, "xl:open:basis-64"],
                [72, "xl:open:basis-72"],
                [80, "xl:open:basis-80"],
                [96, "xl:open:basis-96"],
                ["auto", "xl:open:basis-auto"],
                ["px", "xl:open:basis-px"],
                [0.5, "xl:open:basis-0.5"],
                [1.5, "xl:open:basis-1.5"],
                [2.5, "xl:open:basis-2.5"],
                [3.5, "xl:open:basis-3.5"],
                ["1/2", "xl:open:basis-1/2"],
                ["1/3", "xl:open:basis-1/3"],
                ["2/3", "xl:open:basis-2/3"],
                ["1/4", "xl:open:basis-1/4"],
                ["2/4", "xl:open:basis-2/4"],
                ["3/4", "xl:open:basis-3/4"],
                ["1/5", "xl:open:basis-1/5"],
                ["2/5", "xl:open:basis-2/5"],
                ["3/5", "xl:open:basis-3/5"],
                ["4/5", "xl:open:basis-4/5"],
                ["1/6", "xl:open:basis-1/6"],
                ["2/6", "xl:open:basis-2/6"],
                ["3/6", "xl:open:basis-3/6"],
                ["4/6", "xl:open:basis-4/6"],
                ["5/6", "xl:open:basis-5/6"],
                ["1/12", "xl:open:basis-1/12"],
                ["2/12", "xl:open:basis-2/12"],
                ["3/12", "xl:open:basis-3/12"],
                ["4/12", "xl:open:basis-4/12"],
                ["5/12", "xl:open:basis-5/12"],
                ["6/12", "xl:open:basis-6/12"],
                ["7/12", "xl:open:basis-7/12"],
                ["8/12", "xl:open:basis-8/12"],
                ["9/12", "xl:open:basis-9/12"],
                ["10/12", "xl:open:basis-10/12"],
                ["11/12", "xl:open:basis-11/12"],
                ["full", "xl:open:basis-full"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
