import { Breakpoints, CSSSelector, FlexBasis } from "../../types";
import { BasisBreakpoints } from "./BasisBreakpoints";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakable } from "../../Entities/Brekable";
import { ClassesMapping } from "../../Entities/ClassMap";
import { DefaultValue } from "../DefaultValue";

export class Basis
  extends CSSProperty<Map<FlexBasis, string>>
  implements Breakable<Map<Breakpoints, Map<FlexBasis, string>>>
{
  private constructor(
    classesMapping: ClassesMapping<Map<FlexBasis, string>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new BasisClassesMapping();
    return new Basis(classesMapping, selector);
  }

  public breakpoints() {
    return BasisBreakpoints.create(this.cssSelector);
  }

  public write(grow: FlexBasis) {
    return this.getClassName(grow);
  }
}

class BasisClassesMapping implements ClassesMapping<Map<FlexBasis, string>> {
  private defaultValue: DefaultValue<FlexBasis, string>;

  constructor() {
    this.defaultValue = new DefaultValue<FlexBasis, string>(
      "auto",
      "basis-auto"
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<FlexBasis, string>>([
        [
          "active",
          new Map<FlexBasis, string>([
            [0, "active:basis-0"],
            [1, "active:basis-1"],
            [2, "active:basis-2"],
            [3, "active:basis-3"],
            [4, "active:basis-4"],
            [5, "active:basis-5"],
            [6, "active:basis-6"],
            [7, "active:basis-7"],
            [8, "active:basis-8"],
            [9, "active:basis-9"],
            [10, "active:basis-10"],
            [11, "active:basis-11"],
            [12, "active:basis-12"],
            [14, "active:basis-14"],
            [16, "active:basis-16"],
            [20, "active:basis-20"],
            [24, "active:basis-24"],
            [28, "active:basis-28"],
            [32, "active:basis-32"],
            [36, "active:basis-36"],
            [40, "active:basis-40"],
            [44, "active:basis-44"],
            [48, "active:basis-48"],
            [52, "active:basis-52"],
            [56, "active:basis-56"],
            [60, "active:basis-60"],
            [64, "active:basis-64"],
            [72, "active:basis-72"],
            [80, "active:basis-80"],
            [96, "active:basis-96"],
            ["auto", "active:basis-auto"],
            ["px", "active:basis-px"],
            [0.5, "active:basis-0.5"],
            [1.5, "active:basis-1.5"],
            [2.5, "active:basis-2.5"],
            [3.5, "active:basis-3.5"],
            ["1/2", "active:basis-1/2"],
            ["1/3", "active:basis-1/3"],
            ["2/3", "active:basis-2/3"],
            ["1/4", "active:basis-1/4"],
            ["2/4", "active:basis-2/4"],
            ["3/4", "active:basis-3/4"],
            ["1/5", "active:basis-1/5"],
            ["2/5", "active:basis-2/5"],
            ["3/5", "active:basis-3/5"],
            ["4/5", "active:basis-4/5"],
            ["1/6", "active:basis-1/6"],
            ["2/6", "active:basis-2/6"],
            ["3/6", "active:basis-3/6"],
            ["4/6", "active:basis-4/6"],
            ["5/6", "active:basis-5/6"],
            ["1/12", "active:basis-1/12"],
            ["2/12", "active:basis-2/12"],
            ["3/12", "active:basis-3/12"],
            ["4/12", "active:basis-4/12"],
            ["5/12", "active:basis-5/12"],
            ["6/12", "active:basis-6/12"],
            ["7/12", "active:basis-7/12"],
            ["8/12", "active:basis-8/12"],
            ["9/12", "active:basis-9/12"],
            ["10/12", "active:basis-10/12"],
            ["11/12", "active:basis-11/12"],
            ["full", "active:basis-full"],
          ]),
        ],
        [
          "disabled",
          new Map<FlexBasis, string>([
            [0, "disabled:basis-0"],
            [1, "disabled:basis-1"],
            [2, "disabled:basis-2"],
            [3, "disabled:basis-3"],
            [4, "disabled:basis-4"],
            [5, "disabled:basis-5"],
            [6, "disabled:basis-6"],
            [7, "disabled:basis-7"],
            [8, "disabled:basis-8"],
            [9, "disabled:basis-9"],
            [10, "disabled:basis-10"],
            [11, "disabled:basis-11"],
            [12, "disabled:basis-12"],
            [14, "disabled:basis-14"],
            [16, "disabled:basis-16"],
            [20, "disabled:basis-20"],
            [24, "disabled:basis-24"],
            [28, "disabled:basis-28"],
            [32, "disabled:basis-32"],
            [36, "disabled:basis-36"],
            [40, "disabled:basis-40"],
            [44, "disabled:basis-44"],
            [48, "disabled:basis-48"],
            [52, "disabled:basis-52"],
            [56, "disabled:basis-56"],
            [60, "disabled:basis-60"],
            [64, "disabled:basis-64"],
            [72, "disabled:basis-72"],
            [80, "disabled:basis-80"],
            [96, "disabled:basis-96"],
            ["auto", "disabled:basis-auto"],
            ["px", "disabled:basis-px"],
            [0.5, "disabled:basis-0.5"],
            [1.5, "disabled:basis-1.5"],
            [2.5, "disabled:basis-2.5"],
            [3.5, "disabled:basis-3.5"],
            ["1/2", "disabled:basis-1/2"],
            ["1/3", "disabled:basis-1/3"],
            ["2/3", "disabled:basis-2/3"],
            ["1/4", "disabled:basis-1/4"],
            ["2/4", "disabled:basis-2/4"],
            ["3/4", "disabled:basis-3/4"],
            ["1/5", "disabled:basis-1/5"],
            ["2/5", "disabled:basis-2/5"],
            ["3/5", "disabled:basis-3/5"],
            ["4/5", "disabled:basis-4/5"],
            ["1/6", "disabled:basis-1/6"],
            ["2/6", "disabled:basis-2/6"],
            ["3/6", "disabled:basis-3/6"],
            ["4/6", "disabled:basis-4/6"],
            ["5/6", "disabled:basis-5/6"],
            ["1/12", "disabled:basis-1/12"],
            ["2/12", "disabled:basis-2/12"],
            ["3/12", "disabled:basis-3/12"],
            ["4/12", "disabled:basis-4/12"],
            ["5/12", "disabled:basis-5/12"],
            ["6/12", "disabled:basis-6/12"],
            ["7/12", "disabled:basis-7/12"],
            ["8/12", "disabled:basis-8/12"],
            ["9/12", "disabled:basis-9/12"],
            ["10/12", "disabled:basis-10/12"],
            ["11/12", "disabled:basis-11/12"],
            ["full", "disabled:basis-full"],
          ]),
        ],
        [
          "hover",
          new Map<FlexBasis, string>([
            [0, "hover:basis-0"],
            [1, "hover:basis-1"],
            [2, "hover:basis-2"],
            [3, "hover:basis-3"],
            [4, "hover:basis-4"],
            [5, "hover:basis-5"],
            [6, "hover:basis-6"],
            [7, "hover:basis-7"],
            [8, "hover:basis-8"],
            [9, "hover:basis-9"],
            [10, "hover:basis-10"],
            [11, "hover:basis-11"],
            [12, "hover:basis-12"],
            [14, "hover:basis-14"],
            [16, "hover:basis-16"],
            [20, "hover:basis-20"],
            [24, "hover:basis-24"],
            [28, "hover:basis-28"],
            [32, "hover:basis-32"],
            [36, "hover:basis-36"],
            [40, "hover:basis-40"],
            [44, "hover:basis-44"],
            [48, "hover:basis-48"],
            [52, "hover:basis-52"],
            [56, "hover:basis-56"],
            [60, "hover:basis-60"],
            [64, "hover:basis-64"],
            [72, "hover:basis-72"],
            [80, "hover:basis-80"],
            [96, "hover:basis-96"],
            ["auto", "hover:basis-auto"],
            ["px", "hover:basis-px"],
            [0.5, "hover:basis-0.5"],
            [1.5, "hover:basis-1.5"],
            [2.5, "hover:basis-2.5"],
            [3.5, "hover:basis-3.5"],
            ["1/2", "hover:basis-1/2"],
            ["1/3", "hover:basis-1/3"],
            ["2/3", "hover:basis-2/3"],
            ["1/4", "hover:basis-1/4"],
            ["2/4", "hover:basis-2/4"],
            ["3/4", "hover:basis-3/4"],
            ["1/5", "hover:basis-1/5"],
            ["2/5", "hover:basis-2/5"],
            ["3/5", "hover:basis-3/5"],
            ["4/5", "hover:basis-4/5"],
            ["1/6", "hover:basis-1/6"],
            ["2/6", "hover:basis-2/6"],
            ["3/6", "hover:basis-3/6"],
            ["4/6", "hover:basis-4/6"],
            ["5/6", "hover:basis-5/6"],
            ["1/12", "hover:basis-1/12"],
            ["2/12", "hover:basis-2/12"],
            ["3/12", "hover:basis-3/12"],
            ["4/12", "hover:basis-4/12"],
            ["5/12", "hover:basis-5/12"],
            ["6/12", "hover:basis-6/12"],
            ["7/12", "hover:basis-7/12"],
            ["8/12", "hover:basis-8/12"],
            ["9/12", "hover:basis-9/12"],
            ["10/12", "hover:basis-10/12"],
            ["11/12", "hover:basis-11/12"],
            ["full", "hover:basis-full"],
          ]),
        ],
        [
          "none",
          new Map<FlexBasis, string>([
            [0, "basis-0"],
            [1, "basis-1"],
            [2, "basis-2"],
            [3, "basis-3"],
            [4, "basis-4"],
            [5, "basis-5"],
            [6, "basis-6"],
            [7, "basis-7"],
            [8, "basis-8"],
            [9, "basis-9"],
            [10, "basis-10"],
            [11, "basis-11"],
            [12, "basis-12"],
            [14, "basis-14"],
            [16, "basis-16"],
            [20, "basis-20"],
            [24, "basis-24"],
            [28, "basis-28"],
            [32, "basis-32"],
            [36, "basis-36"],
            [40, "basis-40"],
            [44, "basis-44"],
            [48, "basis-48"],
            [52, "basis-52"],
            [56, "basis-56"],
            [60, "basis-60"],
            [64, "basis-64"],
            [72, "basis-72"],
            [80, "basis-80"],
            [96, "basis-96"],
            ["auto", "basis-auto"],
            ["px", "basis-px"],
            [0.5, "basis-0.5"],
            [1.5, "basis-1.5"],
            [2.5, "basis-2.5"],
            [3.5, "basis-3.5"],
            ["1/2", "basis-1/2"],
            ["1/3", "basis-1/3"],
            ["2/3", "basis-2/3"],
            ["1/4", "basis-1/4"],
            ["2/4", "basis-2/4"],
            ["3/4", "basis-3/4"],
            ["1/5", "basis-1/5"],
            ["2/5", "basis-2/5"],
            ["3/5", "basis-3/5"],
            ["4/5", "basis-4/5"],
            ["1/6", "basis-1/6"],
            ["2/6", "basis-2/6"],
            ["3/6", "basis-3/6"],
            ["4/6", "basis-4/6"],
            ["5/6", "basis-5/6"],
            ["1/12", "basis-1/12"],
            ["2/12", "basis-2/12"],
            ["3/12", "basis-3/12"],
            ["4/12", "basis-4/12"],
            ["5/12", "basis-5/12"],
            ["6/12", "basis-6/12"],
            ["7/12", "basis-7/12"],
            ["8/12", "basis-8/12"],
            ["9/12", "basis-9/12"],
            ["10/12", "basis-10/12"],
            ["11/12", "basis-11/12"],
            ["full", "basis-full"],
          ]),
        ],
        [
          "open",
          new Map<FlexBasis, string>([
            [0, "open:basis-0"],
            [1, "open:basis-1"],
            [2, "open:basis-2"],
            [3, "open:basis-3"],
            [4, "open:basis-4"],
            [5, "open:basis-5"],
            [6, "open:basis-6"],
            [7, "open:basis-7"],
            [8, "open:basis-8"],
            [9, "open:basis-9"],
            [10, "open:basis-10"],
            [11, "open:basis-11"],
            [12, "open:basis-12"],
            [14, "open:basis-14"],
            [16, "open:basis-16"],
            [20, "open:basis-20"],
            [24, "open:basis-24"],
            [28, "open:basis-28"],
            [32, "open:basis-32"],
            [36, "open:basis-36"],
            [40, "open:basis-40"],
            [44, "open:basis-44"],
            [48, "open:basis-48"],
            [52, "open:basis-52"],
            [56, "open:basis-56"],
            [60, "open:basis-60"],
            [64, "open:basis-64"],
            [72, "open:basis-72"],
            [80, "open:basis-80"],
            [96, "open:basis-96"],
            ["auto", "open:basis-auto"],
            ["px", "open:basis-px"],
            [0.5, "open:basis-0.5"],
            [1.5, "open:basis-1.5"],
            [2.5, "open:basis-2.5"],
            [3.5, "open:basis-3.5"],
            ["1/2", "open:basis-1/2"],
            ["1/3", "open:basis-1/3"],
            ["2/3", "open:basis-2/3"],
            ["1/4", "open:basis-1/4"],
            ["2/4", "open:basis-2/4"],
            ["3/4", "open:basis-3/4"],
            ["1/5", "open:basis-1/5"],
            ["2/5", "open:basis-2/5"],
            ["3/5", "open:basis-3/5"],
            ["4/5", "open:basis-4/5"],
            ["1/6", "open:basis-1/6"],
            ["2/6", "open:basis-2/6"],
            ["3/6", "open:basis-3/6"],
            ["4/6", "open:basis-4/6"],
            ["5/6", "open:basis-5/6"],
            ["1/12", "open:basis-1/12"],
            ["2/12", "open:basis-2/12"],
            ["3/12", "open:basis-3/12"],
            ["4/12", "open:basis-4/12"],
            ["5/12", "open:basis-5/12"],
            ["6/12", "open:basis-6/12"],
            ["7/12", "open:basis-7/12"],
            ["8/12", "open:basis-8/12"],
            ["9/12", "open:basis-9/12"],
            ["10/12", "open:basis-10/12"],
            ["11/12", "open:basis-11/12"],
            ["full", "open:basis-full"],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
