import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, MarginSpacing, SideMapping } from "../../types";
import { DefaultValue } from "../DefaultValue";
import { Breakable } from "../../Entities/Brekable";
import { MarginSidesInsideBreakpoints } from "./MarginSidesInsideBreakpoints";

export class MarginSides
  extends CSSProperty<Map<SideMapping, Map<MarginSpacing, string>>>
  implements
    Breakable<Map<Breakpoints, Map<SideMapping, Map<MarginSpacing, string>>>>
{
  private constructor(
    classesMapping: ClassesMapping<
      Map<SideMapping, Map<MarginSpacing, string>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MarginClassesMapping();
    return new MarginSides(classesMapping, selector);
  }

  public breakpoints() {
    return MarginSidesInsideBreakpoints.create(this.cssSelector);
  }

  public write(side: SideMapping, spacing: MarginSpacing) {
    return this.getClassName(side, spacing);
  }
}

class MarginClassesMapping
  implements ClassesMapping<Map<SideMapping, Map<MarginSpacing, string>>>
{
  private defaultValue: DefaultValue<SideMapping, Map<MarginSpacing, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      SideMapping,
      Map<MarginSpacing, string>
    >("bottom", new Map<MarginSpacing, string>([[0, "mb-0"]]));
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<SideMapping, Map<MarginSpacing, string>>>([
        [
          "active",
          new Map<SideMapping, Map<MarginSpacing, string>>([
            [
              "bottom",
              new Map<MarginSpacing, string>([
                [0, "active:mb-0"],
                ["px", "active:mb-px"],
                [0.5, "active:mb-0.5"],
                [1, "active:mb-1"],
                [1.5, "active:mb-1.5"],
                [2, "active:mb-2"],
                [2.5, "active:mb-2.5"],
                [3, "active:mb-3"],
                [3.5, "active:mb-3.5"],
                [4, "active:mb-4"],
                [5, "active:mb-5"],
                [6, "active:mb-6"],
                [7, "active:mb-7"],
                [8, "active:mb-8"],
                [9, "active:mb-9"],
                [10, "active:mb-10"],
                [11, "active:mb-11"],
                [12, "active:mb-12"],
                [14, "active:mb-14"],
                [16, "active:mb-16"],
                [20, "active:mb-20"],
                [24, "active:mb-24"],
                [28, "active:mb-28"],
                [32, "active:mb-32"],
                [36, "active:mb-36"],
                [40, "active:mb-40"],
                [44, "active:mb-44"],
                [48, "active:mb-48"],
                [52, "active:mb-52"],
                [56, "active:mb-56"],
                [60, "active:mb-60"],
                [64, "active:mb-64"],
                [72, "active:mb-72"],
                [80, "active:mb-80"],
                [96, "active:mb-96"],
                ["auto", "active:mb-auto"],
              ]),
            ],
            [
              "left",
              new Map<MarginSpacing, string>([
                [0, "active:ml-0"],
                ["px", "active:ml-px"],
                [0.5, "active:ml-0.5"],
                [1, "active:ml-1"],
                [1.5, "active:ml-1.5"],
                [2, "active:ml-2"],
                [2.5, "active:ml-2.5"],
                [3, "active:ml-3"],
                [3.5, "active:ml-3.5"],
                [4, "active:ml-4"],
                [5, "active:ml-5"],
                [6, "active:ml-6"],
                [7, "active:ml-7"],
                [8, "active:ml-8"],
                [9, "active:ml-9"],
                [10, "active:ml-10"],
                [11, "active:ml-11"],
                [12, "active:ml-12"],
                [14, "active:ml-14"],
                [16, "active:ml-16"],
                [20, "active:ml-20"],
                [24, "active:ml-24"],
                [28, "active:ml-28"],
                [32, "active:ml-32"],
                [36, "active:ml-36"],
                [40, "active:ml-40"],
                [44, "active:ml-44"],
                [48, "active:ml-48"],
                [52, "active:ml-52"],
                [56, "active:ml-56"],
                [60, "active:ml-60"],
                [64, "active:ml-64"],
                [72, "active:ml-72"],
                [80, "active:ml-80"],
                [96, "active:ml-96"],
                ["auto", "active:ml-auto"],
              ]),
            ],
            [
              "right",
              new Map<MarginSpacing, string>([
                [0, "active:mr-0"],
                ["px", "active:mr-px"],
                [0.5, "active:mr-0.5"],
                [1, "active:mr-1"],
                [1.5, "active:mr-1.5"],
                [2, "active:mr-2"],
                [2.5, "active:mr-2.5"],
                [3, "active:mr-3"],
                [3.5, "active:mr-3.5"],
                [4, "active:mr-4"],
                [5, "active:mr-5"],
                [6, "active:mr-6"],
                [7, "active:mr-7"],
                [8, "active:mr-8"],
                [9, "active:mr-9"],
                [10, "active:mr-10"],
                [11, "active:mr-11"],
                [12, "active:mr-12"],
                [14, "active:mr-14"],
                [16, "active:mr-16"],
                [20, "active:mr-20"],
                [24, "active:mr-24"],
                [28, "active:mr-28"],
                [32, "active:mr-32"],
                [36, "active:mr-36"],
                [40, "active:mr-40"],
                [44, "active:mr-44"],
                [48, "active:mr-48"],
                [52, "active:mr-52"],
                [56, "active:mr-56"],
                [60, "active:mr-60"],
                [64, "active:mr-64"],
                [72, "active:mr-72"],
                [80, "active:mr-80"],
                [96, "active:mr-96"],
                ["auto", "active:mr-auto"],
              ]),
            ],
            [
              "top",
              new Map<MarginSpacing, string>([
                [0, "active:mt-0"],
                ["px", "active:mt-px"],
                [0.5, "active:mt-0.5"],
                [1, "active:mt-1"],
                [1.5, "active:mt-1.5"],
                [2, "active:mt-2"],
                [2.5, "active:mt-2.5"],
                [3, "active:mt-3"],
                [3.5, "active:mt-3.5"],
                [4, "active:mt-4"],
                [5, "active:mt-5"],
                [6, "active:mt-6"],
                [7, "active:mt-7"],
                [8, "active:mt-8"],
                [9, "active:mt-9"],
                [10, "active:mt-10"],
                [11, "active:mt-11"],
                [12, "active:mt-12"],
                [14, "active:mt-14"],
                [16, "active:mt-16"],
                [20, "active:mt-20"],
                [24, "active:mt-24"],
                [28, "active:mt-28"],
                [32, "active:mt-32"],
                [36, "active:mt-36"],
                [40, "active:mt-40"],
                [44, "active:mt-44"],
                [48, "active:mt-48"],
                [52, "active:mt-52"],
                [56, "active:mt-56"],
                [60, "active:mt-60"],
                [64, "active:mt-64"],
                [72, "active:mt-72"],
                [80, "active:mt-80"],
                [96, "active:mt-96"],
                ["auto", "active:mt-auto"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<SideMapping, Map<MarginSpacing, string>>([
            [
              "bottom",
              new Map<MarginSpacing, string>([
                [0, "disabled:mb-0"],
                ["px", "disabled:mb-px"],
                [0.5, "disabled:mb-0.5"],
                [1, "disabled:mb-1"],
                [1.5, "disabled:mb-1.5"],
                [2, "disabled:mb-2"],
                [2.5, "disabled:mb-2.5"],
                [3, "disabled:mb-3"],
                [3.5, "disabled:mb-3.5"],
                [4, "disabled:mb-4"],
                [5, "disabled:mb-5"],
                [6, "disabled:mb-6"],
                [7, "disabled:mb-7"],
                [8, "disabled:mb-8"],
                [9, "disabled:mb-9"],
                [10, "disabled:mb-10"],
                [11, "disabled:mb-11"],
                [12, "disabled:mb-12"],
                [14, "disabled:mb-14"],
                [16, "disabled:mb-16"],
                [20, "disabled:mb-20"],
                [24, "disabled:mb-24"],
                [28, "disabled:mb-28"],
                [32, "disabled:mb-32"],
                [36, "disabled:mb-36"],
                [40, "disabled:mb-40"],
                [44, "disabled:mb-44"],
                [48, "disabled:mb-48"],
                [52, "disabled:mb-52"],
                [56, "disabled:mb-56"],
                [60, "disabled:mb-60"],
                [64, "disabled:mb-64"],
                [72, "disabled:mb-72"],
                [80, "disabled:mb-80"],
                [96, "disabled:mb-96"],
                ["auto", "disabled:mb-auto"],
              ]),
            ],
            [
              "left",
              new Map<MarginSpacing, string>([
                [0, "disabled:ml-0"],
                ["px", "disabled:ml-px"],
                [0.5, "disabled:ml-0.5"],
                [1, "disabled:ml-1"],
                [1.5, "disabled:ml-1.5"],
                [2, "disabled:ml-2"],
                [2.5, "disabled:ml-2.5"],
                [3, "disabled:ml-3"],
                [3.5, "disabled:ml-3.5"],
                [4, "disabled:ml-4"],
                [5, "disabled:ml-5"],
                [6, "disabled:ml-6"],
                [7, "disabled:ml-7"],
                [8, "disabled:ml-8"],
                [9, "disabled:ml-9"],
                [10, "disabled:ml-10"],
                [11, "disabled:ml-11"],
                [12, "disabled:ml-12"],
                [14, "disabled:ml-14"],
                [16, "disabled:ml-16"],
                [20, "disabled:ml-20"],
                [24, "disabled:ml-24"],
                [28, "disabled:ml-28"],
                [32, "disabled:ml-32"],
                [36, "disabled:ml-36"],
                [40, "disabled:ml-40"],
                [44, "disabled:ml-44"],
                [48, "disabled:ml-48"],
                [52, "disabled:ml-52"],
                [56, "disabled:ml-56"],
                [60, "disabled:ml-60"],
                [64, "disabled:ml-64"],
                [72, "disabled:ml-72"],
                [80, "disabled:ml-80"],
                [96, "disabled:ml-96"],
                ["auto", "disabled:ml-auto"],
              ]),
            ],
            [
              "right",
              new Map<MarginSpacing, string>([
                [0, "disabled:mr-0"],
                ["px", "disabled:mr-px"],
                [0.5, "disabled:mr-0.5"],
                [1, "disabled:mr-1"],
                [1.5, "disabled:mr-1.5"],
                [2, "disabled:mr-2"],
                [2.5, "disabled:mr-2.5"],
                [3, "disabled:mr-3"],
                [3.5, "disabled:mr-3.5"],
                [4, "disabled:mr-4"],
                [5, "disabled:mr-5"],
                [6, "disabled:mr-6"],
                [7, "disabled:mr-7"],
                [8, "disabled:mr-8"],
                [9, "disabled:mr-9"],
                [10, "disabled:mr-10"],
                [11, "disabled:mr-11"],
                [12, "disabled:mr-12"],
                [14, "disabled:mr-14"],
                [16, "disabled:mr-16"],
                [20, "disabled:mr-20"],
                [24, "disabled:mr-24"],
                [28, "disabled:mr-28"],
                [32, "disabled:mr-32"],
                [36, "disabled:mr-36"],
                [40, "disabled:mr-40"],
                [44, "disabled:mr-44"],
                [48, "disabled:mr-48"],
                [52, "disabled:mr-52"],
                [56, "disabled:mr-56"],
                [60, "disabled:mr-60"],
                [64, "disabled:mr-64"],
                [72, "disabled:mr-72"],
                [80, "disabled:mr-80"],
                [96, "disabled:mr-96"],
                ["auto", "disabled:mr-auto"],
              ]),
            ],
            [
              "top",
              new Map<MarginSpacing, string>([
                [0, "disabled:mt-0"],
                ["px", "disabled:mt-px"],
                [0.5, "disabled:mt-0.5"],
                [1, "disabled:mt-1"],
                [1.5, "disabled:mt-1.5"],
                [2, "disabled:mt-2"],
                [2.5, "disabled:mt-2.5"],
                [3, "disabled:mt-3"],
                [3.5, "disabled:mt-3.5"],
                [4, "disabled:mt-4"],
                [5, "disabled:mt-5"],
                [6, "disabled:mt-6"],
                [7, "disabled:mt-7"],
                [8, "disabled:mt-8"],
                [9, "disabled:mt-9"],
                [10, "disabled:mt-10"],
                [11, "disabled:mt-11"],
                [12, "disabled:mt-12"],
                [14, "disabled:mt-14"],
                [16, "disabled:mt-16"],
                [20, "disabled:mt-20"],
                [24, "disabled:mt-24"],
                [28, "disabled:mt-28"],
                [32, "disabled:mt-32"],
                [36, "disabled:mt-36"],
                [40, "disabled:mt-40"],
                [44, "disabled:mt-44"],
                [48, "disabled:mt-48"],
                [52, "disabled:mt-52"],
                [56, "disabled:mt-56"],
                [60, "disabled:mt-60"],
                [64, "disabled:mt-64"],
                [72, "disabled:mt-72"],
                [80, "disabled:mt-80"],
                [96, "disabled:mt-96"],
                ["auto", "disabled:mt-auto"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<SideMapping, Map<MarginSpacing, string>>([
            [
              "bottom",
              new Map<MarginSpacing, string>([
                [0, "hover:mb-0"],
                ["px", "hover:mb-px"],
                [0.5, "hover:mb-0.5"],
                [1, "hover:mb-1"],
                [1.5, "hover:mb-1.5"],
                [2, "hover:mb-2"],
                [2.5, "hover:mb-2.5"],
                [3, "hover:mb-3"],
                [3.5, "hover:mb-3.5"],
                [4, "hover:mb-4"],
                [5, "hover:mb-5"],
                [6, "hover:mb-6"],
                [7, "hover:mb-7"],
                [8, "hover:mb-8"],
                [9, "hover:mb-9"],
                [10, "hover:mb-10"],
                [11, "hover:mb-11"],
                [12, "hover:mb-12"],
                [14, "hover:mb-14"],
                [16, "hover:mb-16"],
                [20, "hover:mb-20"],
                [24, "hover:mb-24"],
                [28, "hover:mb-28"],
                [32, "hover:mb-32"],
                [36, "hover:mb-36"],
                [40, "hover:mb-40"],
                [44, "hover:mb-44"],
                [48, "hover:mb-48"],
                [52, "hover:mb-52"],
                [56, "hover:mb-56"],
                [60, "hover:mb-60"],
                [64, "hover:mb-64"],
                [72, "hover:mb-72"],
                [80, "hover:mb-80"],
                [96, "hover:mb-96"],
                ["auto", "hover:mb-auto"],
              ]),
            ],
            [
              "left",
              new Map<MarginSpacing, string>([
                [0, "hover:ml-0"],
                ["px", "hover:ml-px"],
                [0.5, "hover:ml-0.5"],
                [1, "hover:ml-1"],
                [1.5, "hover:ml-1.5"],
                [2, "hover:ml-2"],
                [2.5, "hover:ml-2.5"],
                [3, "hover:ml-3"],
                [3.5, "hover:ml-3.5"],
                [4, "hover:ml-4"],
                [5, "hover:ml-5"],
                [6, "hover:ml-6"],
                [7, "hover:ml-7"],
                [8, "hover:ml-8"],
                [9, "hover:ml-9"],
                [10, "hover:ml-10"],
                [11, "hover:ml-11"],
                [12, "hover:ml-12"],
                [14, "hover:ml-14"],
                [16, "hover:ml-16"],
                [20, "hover:ml-20"],
                [24, "hover:ml-24"],
                [28, "hover:ml-28"],
                [32, "hover:ml-32"],
                [36, "hover:ml-36"],
                [40, "hover:ml-40"],
                [44, "hover:ml-44"],
                [48, "hover:ml-48"],
                [52, "hover:ml-52"],
                [56, "hover:ml-56"],
                [60, "hover:ml-60"],
                [64, "hover:ml-64"],
                [72, "hover:ml-72"],
                [80, "hover:ml-80"],
                [96, "hover:ml-96"],
                ["auto", "hover:ml-auto"],
              ]),
            ],
            [
              "right",
              new Map<MarginSpacing, string>([
                [0, "hover:mr-0"],
                ["px", "hover:mr-px"],
                [0.5, "hover:mr-0.5"],
                [1, "hover:mr-1"],
                [1.5, "hover:mr-1.5"],
                [2, "hover:mr-2"],
                [2.5, "hover:mr-2.5"],
                [3, "hover:mr-3"],
                [3.5, "hover:mr-3.5"],
                [4, "hover:mr-4"],
                [5, "hover:mr-5"],
                [6, "hover:mr-6"],
                [7, "hover:mr-7"],
                [8, "hover:mr-8"],
                [9, "hover:mr-9"],
                [10, "hover:mr-10"],
                [11, "hover:mr-11"],
                [12, "hover:mr-12"],
                [14, "hover:mr-14"],
                [16, "hover:mr-16"],
                [20, "hover:mr-20"],
                [24, "hover:mr-24"],
                [28, "hover:mr-28"],
                [32, "hover:mr-32"],
                [36, "hover:mr-36"],
                [40, "hover:mr-40"],
                [44, "hover:mr-44"],
                [48, "hover:mr-48"],
                [52, "hover:mr-52"],
                [56, "hover:mr-56"],
                [60, "hover:mr-60"],
                [64, "hover:mr-64"],
                [72, "hover:mr-72"],
                [80, "hover:mr-80"],
                [96, "hover:mr-96"],
                ["auto", "hover:mr-auto"],
              ]),
            ],
            [
              "top",
              new Map<MarginSpacing, string>([
                [0, "hover:mt-0"],
                ["px", "hover:mt-px"],
                [0.5, "hover:mt-0.5"],
                [1, "hover:mt-1"],
                [1.5, "hover:mt-1.5"],
                [2, "hover:mt-2"],
                [2.5, "hover:mt-2.5"],
                [3, "hover:mt-3"],
                [3.5, "hover:mt-3.5"],
                [4, "hover:mt-4"],
                [5, "hover:mt-5"],
                [6, "hover:mt-6"],
                [7, "hover:mt-7"],
                [8, "hover:mt-8"],
                [9, "hover:mt-9"],
                [10, "hover:mt-10"],
                [11, "hover:mt-11"],
                [12, "hover:mt-12"],
                [14, "hover:mt-14"],
                [16, "hover:mt-16"],
                [20, "hover:mt-20"],
                [24, "hover:mt-24"],
                [28, "hover:mt-28"],
                [32, "hover:mt-32"],
                [36, "hover:mt-36"],
                [40, "hover:mt-40"],
                [44, "hover:mt-44"],
                [48, "hover:mt-48"],
                [52, "hover:mt-52"],
                [56, "hover:mt-56"],
                [60, "hover:mt-60"],
                [64, "hover:mt-64"],
                [72, "hover:mt-72"],
                [80, "hover:mt-80"],
                [96, "hover:mt-96"],
                ["auto", "hover:mt-auto"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<SideMapping, Map<MarginSpacing, string>>([
            [
              "bottom",
              new Map<MarginSpacing, string>([
                [0, "mb-0"],
                ["px", "mb-px"],
                [0.5, "mb-0.5"],
                [1, "mb-1"],
                [1.5, "mb-1.5"],
                [2, "mb-2"],
                [2.5, "mb-2.5"],
                [3, "mb-3"],
                [3.5, "mb-3.5"],
                [4, "mb-4"],
                [5, "mb-5"],
                [6, "mb-6"],
                [7, "mb-7"],
                [8, "mb-8"],
                [9, "mb-9"],
                [10, "mb-10"],
                [11, "mb-11"],
                [12, "mb-12"],
                [14, "mb-14"],
                [16, "mb-16"],
                [20, "mb-20"],
                [24, "mb-24"],
                [28, "mb-28"],
                [32, "mb-32"],
                [36, "mb-36"],
                [40, "mb-40"],
                [44, "mb-44"],
                [48, "mb-48"],
                [52, "mb-52"],
                [56, "mb-56"],
                [60, "mb-60"],
                [64, "mb-64"],
                [72, "mb-72"],
                [80, "mb-80"],
                [96, "mb-96"],
                ["auto", "mb-auto"],
              ]),
            ],
            [
              "left",
              new Map<MarginSpacing, string>([
                [0, "ml-0"],
                ["px", "ml-px"],
                [0.5, "ml-0.5"],
                [1, "ml-1"],
                [1.5, "ml-1.5"],
                [2, "ml-2"],
                [2.5, "ml-2.5"],
                [3, "ml-3"],
                [3.5, "ml-3.5"],
                [4, "ml-4"],
                [5, "ml-5"],
                [6, "ml-6"],
                [7, "ml-7"],
                [8, "ml-8"],
                [9, "ml-9"],
                [10, "ml-10"],
                [11, "ml-11"],
                [12, "ml-12"],
                [14, "ml-14"],
                [16, "ml-16"],
                [20, "ml-20"],
                [24, "ml-24"],
                [28, "ml-28"],
                [32, "ml-32"],
                [36, "ml-36"],
                [40, "ml-40"],
                [44, "ml-44"],
                [48, "ml-48"],
                [52, "ml-52"],
                [56, "ml-56"],
                [60, "ml-60"],
                [64, "ml-64"],
                [72, "ml-72"],
                [80, "ml-80"],
                [96, "ml-96"],
                ["auto", "ml-auto"],
              ]),
            ],
            [
              "right",
              new Map<MarginSpacing, string>([
                [0, "mr-0"],
                ["px", "mr-px"],
                [0.5, "mr-0.5"],
                [1, "mr-1"],
                [1.5, "mr-1.5"],
                [2, "mr-2"],
                [2.5, "mr-2.5"],
                [3, "mr-3"],
                [3.5, "mr-3.5"],
                [4, "mr-4"],
                [5, "mr-5"],
                [6, "mr-6"],
                [7, "mr-7"],
                [8, "mr-8"],
                [9, "mr-9"],
                [10, "mr-10"],
                [11, "mr-11"],
                [12, "mr-12"],
                [14, "mr-14"],
                [16, "mr-16"],
                [20, "mr-20"],
                [24, "mr-24"],
                [28, "mr-28"],
                [32, "mr-32"],
                [36, "mr-36"],
                [40, "mr-40"],
                [44, "mr-44"],
                [48, "mr-48"],
                [52, "mr-52"],
                [56, "mr-56"],
                [60, "mr-60"],
                [64, "mr-64"],
                [72, "mr-72"],
                [80, "mr-80"],
                [96, "mr-96"],
                ["auto", "mr-auto"],
              ]),
            ],
            [
              "top",
              new Map<MarginSpacing, string>([
                [0, "mt-0"],
                ["px", "mt-px"],
                [0.5, "mt-0.5"],
                [1, "mt-1"],
                [1.5, "mt-1.5"],
                [2, "mt-2"],
                [2.5, "mt-2.5"],
                [3, "mt-3"],
                [3.5, "mt-3.5"],
                [4, "mt-4"],
                [5, "mt-5"],
                [6, "mt-6"],
                [7, "mt-7"],
                [8, "mt-8"],
                [9, "mt-9"],
                [10, "mt-10"],
                [11, "mt-11"],
                [12, "mt-12"],
                [14, "mt-14"],
                [16, "mt-16"],
                [20, "mt-20"],
                [24, "mt-24"],
                [28, "mt-28"],
                [32, "mt-32"],
                [36, "mt-36"],
                [40, "mt-40"],
                [44, "mt-44"],
                [48, "mt-48"],
                [52, "mt-52"],
                [56, "mt-56"],
                [60, "mt-60"],
                [64, "mt-64"],
                [72, "mt-72"],
                [80, "mt-80"],
                [96, "mt-96"],
                ["auto", "mt-auto"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<SideMapping, Map<MarginSpacing, string>>([
            [
              "bottom",
              new Map<MarginSpacing, string>([
                [0, "open:mb-0"],
                ["px", "open:mb-px"],
                [0.5, "open:mb-0.5"],
                [1, "open:mb-1"],
                [1.5, "open:mb-1.5"],
                [2, "open:mb-2"],
                [2.5, "open:mb-2.5"],
                [3, "open:mb-3"],
                [3.5, "open:mb-3.5"],
                [4, "open:mb-4"],
                [5, "open:mb-5"],
                [6, "open:mb-6"],
                [7, "open:mb-7"],
                [8, "open:mb-8"],
                [9, "open:mb-9"],
                [10, "open:mb-10"],
                [11, "open:mb-11"],
                [12, "open:mb-12"],
                [14, "open:mb-14"],
                [16, "open:mb-16"],
                [20, "open:mb-20"],
                [24, "open:mb-24"],
                [28, "open:mb-28"],
                [32, "open:mb-32"],
                [36, "open:mb-36"],
                [40, "open:mb-40"],
                [44, "open:mb-44"],
                [48, "open:mb-48"],
                [52, "open:mb-52"],
                [56, "open:mb-56"],
                [60, "open:mb-60"],
                [64, "open:mb-64"],
                [72, "open:mb-72"],
                [80, "open:mb-80"],
                [96, "open:mb-96"],
                ["auto", "open:mb-auto"],
              ]),
            ],
            [
              "left",
              new Map<MarginSpacing, string>([
                [0, "open:ml-0"],
                ["px", "open:ml-px"],
                [0.5, "open:ml-0.5"],
                [1, "open:ml-1"],
                [1.5, "open:ml-1.5"],
                [2, "open:ml-2"],
                [2.5, "open:ml-2.5"],
                [3, "open:ml-3"],
                [3.5, "open:ml-3.5"],
                [4, "open:ml-4"],
                [5, "open:ml-5"],
                [6, "open:ml-6"],
                [7, "open:ml-7"],
                [8, "open:ml-8"],
                [9, "open:ml-9"],
                [10, "open:ml-10"],
                [11, "open:ml-11"],
                [12, "open:ml-12"],
                [14, "open:ml-14"],
                [16, "open:ml-16"],
                [20, "open:ml-20"],
                [24, "open:ml-24"],
                [28, "open:ml-28"],
                [32, "open:ml-32"],
                [36, "open:ml-36"],
                [40, "open:ml-40"],
                [44, "open:ml-44"],
                [48, "open:ml-48"],
                [52, "open:ml-52"],
                [56, "open:ml-56"],
                [60, "open:ml-60"],
                [64, "open:ml-64"],
                [72, "open:ml-72"],
                [80, "open:ml-80"],
                [96, "open:ml-96"],
                ["auto", "open:ml-auto"],
              ]),
            ],
            [
              "right",
              new Map<MarginSpacing, string>([
                [0, "open:mr-0"],
                ["px", "open:mr-px"],
                [0.5, "open:mr-0.5"],
                [1, "open:mr-1"],
                [1.5, "open:mr-1.5"],
                [2, "open:mr-2"],
                [2.5, "open:mr-2.5"],
                [3, "open:mr-3"],
                [3.5, "open:mr-3.5"],
                [4, "open:mr-4"],
                [5, "open:mr-5"],
                [6, "open:mr-6"],
                [7, "open:mr-7"],
                [8, "open:mr-8"],
                [9, "open:mr-9"],
                [10, "open:mr-10"],
                [11, "open:mr-11"],
                [12, "open:mr-12"],
                [14, "open:mr-14"],
                [16, "open:mr-16"],
                [20, "open:mr-20"],
                [24, "open:mr-24"],
                [28, "open:mr-28"],
                [32, "open:mr-32"],
                [36, "open:mr-36"],
                [40, "open:mr-40"],
                [44, "open:mr-44"],
                [48, "open:mr-48"],
                [52, "open:mr-52"],
                [56, "open:mr-56"],
                [60, "open:mr-60"],
                [64, "open:mr-64"],
                [72, "open:mr-72"],
                [80, "open:mr-80"],
                [96, "open:mr-96"],
                ["auto", "open:mr-auto"],
              ]),
            ],
            [
              "top",
              new Map<MarginSpacing, string>([
                [0, "open:mt-0"],
                ["px", "open:mt-px"],
                [0.5, "open:mt-0.5"],
                [1, "open:mt-1"],
                [1.5, "open:mt-1.5"],
                [2, "open:mt-2"],
                [2.5, "open:mt-2.5"],
                [3, "open:mt-3"],
                [3.5, "open:mt-3.5"],
                [4, "open:mt-4"],
                [5, "open:mt-5"],
                [6, "open:mt-6"],
                [7, "open:mt-7"],
                [8, "open:mt-8"],
                [9, "open:mt-9"],
                [10, "open:mt-10"],
                [11, "open:mt-11"],
                [12, "open:mt-12"],
                [14, "open:mt-14"],
                [16, "open:mt-16"],
                [20, "open:mt-20"],
                [24, "open:mt-24"],
                [28, "open:mt-28"],
                [32, "open:mt-32"],
                [36, "open:mt-36"],
                [40, "open:mt-40"],
                [44, "open:mt-44"],
                [48, "open:mt-48"],
                [52, "open:mt-52"],
                [56, "open:mt-56"],
                [60, "open:mt-60"],
                [64, "open:mt-64"],
                [72, "open:mt-72"],
                [80, "open:mt-80"],
                [96, "open:mt-96"],
                ["auto", "open:mt-auto"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
