import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { AxisMapping, Breakpoints, CSSSelector, MarginSpacing } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class MarginAxisInsideBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>
> {
  private constructor(
    classesMapping: ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MarginClassesMapping();
    return new MarginAxisInsideBreakpoints(classesMapping, selector);
  }

  public write(
    breakpoint: Breakpoints,
    axis: AxisMapping,
    spacing: MarginSpacing
  ) {
    return this.getClassName(breakpoint, axis, spacing);
  }
}

class MarginClassesMapping
  implements
    ClassesMapping<
      Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>
    >
{
  private defaultValue: DefaultValue<
    Breakpoints,
    Map<AxisMapping, Map<MarginSpacing, string>>
  >;

  constructor() {
    this.defaultValue = new DefaultValue<
      Breakpoints,
      Map<AxisMapping, Map<MarginSpacing, string>>
    >(
      "xs",
      new Map<AxisMapping, Map<MarginSpacing, string>>([
        ["x", new Map<MarginSpacing, string>([[0, "xs:mx-0"]])],
        ["y", new Map<MarginSpacing, string>([[0, "xs:my-0"]])],
      ])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<
        CSSSelector,
        Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>
      >([
        [
          "active",
          new Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xs:active:mx-0"],
                    ["px", "xs:active:mx-px"],
                    [0.5, "xs:active:mx-0.5"],
                    [1, "xs:active:mx-1"],
                    [1.5, "xs:active:mx-1.5"],
                    [2, "xs:active:mx-2"],
                    [2.5, "xs:active:mx-2.5"],
                    [3, "xs:active:mx-3"],
                    [3.5, "xs:active:mx-3.5"],
                    [4, "xs:active:mx-4"],
                    [5, "xs:active:mx-5"],
                    [6, "xs:active:mx-6"],
                    [7, "xs:active:mx-7"],
                    [8, "xs:active:mx-8"],
                    [9, "xs:active:mx-9"],
                    [10, "xs:active:mx-10"],
                    [11, "xs:active:mx-11"],
                    [12, "xs:active:mx-12"],
                    [14, "xs:active:mx-14"],
                    [16, "xs:active:mx-16"],
                    [20, "xs:active:mx-20"],
                    [24, "xs:active:mx-24"],
                    [28, "xs:active:mx-28"],
                    [32, "xs:active:mx-32"],
                    [36, "xs:active:mx-36"],
                    [40, "xs:active:mx-40"],
                    [44, "xs:active:mx-44"],
                    [48, "xs:active:mx-48"],
                    [52, "xs:active:mx-52"],
                    [56, "xs:active:mx-56"],
                    [60, "xs:active:mx-60"],
                    [64, "xs:active:mx-64"],
                    [72, "xs:active:mx-72"],
                    [80, "xs:active:mx-80"],
                    [96, "xs:active:mx-96"],
                    ["auto", "xs:active:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xs:active:my-0"],
                    ["px", "xs:active:my-px"],
                    [0.5, "xs:active:my-0.5"],
                    [1, "xs:active:my-1"],
                    [1.5, "xs:active:my-1.5"],
                    [2, "xs:active:my-2"],
                    [2.5, "xs:active:my-2.5"],
                    [3, "xs:active:my-3"],
                    [3.5, "xs:active:my-3.5"],
                    [4, "xs:active:my-4"],
                    [5, "xs:active:my-5"],
                    [6, "xs:active:my-6"],
                    [7, "xs:active:my-7"],
                    [8, "xs:active:my-8"],
                    [9, "xs:active:my-9"],
                    [10, "xs:active:my-10"],
                    [11, "xs:active:my-11"],
                    [12, "xs:active:my-12"],
                    [14, "xs:active:my-14"],
                    [16, "xs:active:my-16"],
                    [20, "xs:active:my-20"],
                    [24, "xs:active:my-24"],
                    [28, "xs:active:my-28"],
                    [32, "xs:active:my-32"],
                    [36, "xs:active:my-36"],
                    [40, "xs:active:my-40"],
                    [44, "xs:active:my-44"],
                    [48, "xs:active:my-48"],
                    [52, "xs:active:my-52"],
                    [56, "xs:active:my-56"],
                    [60, "xs:active:my-60"],
                    [64, "xs:active:my-64"],
                    [72, "xs:active:my-72"],
                    [80, "xs:active:my-80"],
                    [96, "xs:active:my-96"],
                    ["auto", "xs:active:my-auto"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "sm:active:mx-0"],
                    ["px", "sm:active:mx-px"],
                    [0.5, "sm:active:mx-0.5"],
                    [1, "sm:active:mx-1"],
                    [1.5, "sm:active:mx-1.5"],
                    [2, "sm:active:mx-2"],
                    [2.5, "sm:active:mx-2.5"],
                    [3, "sm:active:mx-3"],
                    [3.5, "sm:active:mx-3.5"],
                    [4, "sm:active:mx-4"],
                    [5, "sm:active:mx-5"],
                    [6, "sm:active:mx-6"],
                    [7, "sm:active:mx-7"],
                    [8, "sm:active:mx-8"],
                    [9, "sm:active:mx-9"],
                    [10, "sm:active:mx-10"],
                    [11, "sm:active:mx-11"],
                    [12, "sm:active:mx-12"],
                    [14, "sm:active:mx-14"],
                    [16, "sm:active:mx-16"],
                    [20, "sm:active:mx-20"],
                    [24, "sm:active:mx-24"],
                    [28, "sm:active:mx-28"],
                    [32, "sm:active:mx-32"],
                    [36, "sm:active:mx-36"],
                    [40, "sm:active:mx-40"],
                    [44, "sm:active:mx-44"],
                    [48, "sm:active:mx-48"],
                    [52, "sm:active:mx-52"],
                    [56, "sm:active:mx-56"],
                    [60, "sm:active:mx-60"],
                    [64, "sm:active:mx-64"],
                    [72, "sm:active:mx-72"],
                    [80, "sm:active:mx-80"],
                    [96, "sm:active:mx-96"],
                    ["auto", "sm:active:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "sm:active:my-0"],
                    ["px", "sm:active:my-px"],
                    [0.5, "sm:active:my-0.5"],
                    [1, "sm:active:my-1"],
                    [1.5, "sm:active:my-1.5"],
                    [2, "sm:active:my-2"],
                    [2.5, "sm:active:my-2.5"],
                    [3, "sm:active:my-3"],
                    [3.5, "sm:active:my-3.5"],
                    [4, "sm:active:my-4"],
                    [5, "sm:active:my-5"],
                    [6, "sm:active:my-6"],
                    [7, "sm:active:my-7"],
                    [8, "sm:active:my-8"],
                    [9, "sm:active:my-9"],
                    [10, "sm:active:my-10"],
                    [11, "sm:active:my-11"],
                    [12, "sm:active:my-12"],
                    [14, "sm:active:my-14"],
                    [16, "sm:active:my-16"],
                    [20, "sm:active:my-20"],
                    [24, "sm:active:my-24"],
                    [28, "sm:active:my-28"],
                    [32, "sm:active:my-32"],
                    [36, "sm:active:my-36"],
                    [40, "sm:active:my-40"],
                    [44, "sm:active:my-44"],
                    [48, "sm:active:my-48"],
                    [52, "sm:active:my-52"],
                    [56, "sm:active:my-56"],
                    [60, "sm:active:my-60"],
                    [64, "sm:active:my-64"],
                    [72, "sm:active:my-72"],
                    [80, "sm:active:my-80"],
                    [96, "sm:active:my-96"],
                    ["auto", "sm:active:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "md:active:mx-0"],
                    ["px", "md:active:mx-px"],
                    [0.5, "md:active:mx-0.5"],
                    [1, "md:active:mx-1"],
                    [1.5, "md:active:mx-1.5"],
                    [2, "md:active:mx-2"],
                    [2.5, "md:active:mx-2.5"],
                    [3, "md:active:mx-3"],
                    [3.5, "md:active:mx-3.5"],
                    [4, "md:active:mx-4"],
                    [5, "md:active:mx-5"],
                    [6, "md:active:mx-6"],
                    [7, "md:active:mx-7"],
                    [8, "md:active:mx-8"],
                    [9, "md:active:mx-9"],
                    [10, "md:active:mx-10"],
                    [11, "md:active:mx-11"],
                    [12, "md:active:mx-12"],
                    [14, "md:active:mx-14"],
                    [16, "md:active:mx-16"],
                    [20, "md:active:mx-20"],
                    [24, "md:active:mx-24"],
                    [28, "md:active:mx-28"],
                    [32, "md:active:mx-32"],
                    [36, "md:active:mx-36"],
                    [40, "md:active:mx-40"],
                    [44, "md:active:mx-44"],
                    [48, "md:active:mx-48"],
                    [52, "md:active:mx-52"],
                    [56, "md:active:mx-56"],
                    [60, "md:active:mx-60"],
                    [64, "md:active:mx-64"],
                    [72, "md:active:mx-72"],
                    [80, "md:active:mx-80"],
                    [96, "md:active:mx-96"],
                    ["auto", "md:active:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "md:active:my-0"],
                    ["px", "md:active:my-px"],
                    [0.5, "md:active:my-0.5"],
                    [1, "md:active:my-1"],
                    [1.5, "md:active:my-1.5"],
                    [2, "md:active:my-2"],
                    [2.5, "md:active:my-2.5"],
                    [3, "md:active:my-3"],
                    [3.5, "md:active:my-3.5"],
                    [4, "md:active:my-4"],
                    [5, "md:active:my-5"],
                    [6, "md:active:my-6"],
                    [7, "md:active:my-7"],
                    [8, "md:active:my-8"],
                    [9, "md:active:my-9"],
                    [10, "md:active:my-10"],
                    [11, "md:active:my-11"],
                    [12, "md:active:my-12"],
                    [14, "md:active:my-14"],
                    [16, "md:active:my-16"],
                    [20, "md:active:my-20"],
                    [24, "md:active:my-24"],
                    [28, "md:active:my-28"],
                    [32, "md:active:my-32"],
                    [36, "md:active:my-36"],
                    [40, "md:active:my-40"],
                    [44, "md:active:my-44"],
                    [48, "md:active:my-48"],
                    [52, "md:active:my-52"],
                    [56, "md:active:my-56"],
                    [60, "md:active:my-60"],
                    [64, "md:active:my-64"],
                    [72, "md:active:my-72"],
                    [80, "md:active:my-80"],
                    [96, "md:active:my-96"],
                    ["auto", "md:active:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "lg:active:mx-0"],
                    ["px", "lg:active:mx-px"],
                    [0.5, "lg:active:mx-0.5"],
                    [1, "lg:active:mx-1"],
                    [1.5, "lg:active:mx-1.5"],
                    [2, "lg:active:mx-2"],
                    [2.5, "lg:active:mx-2.5"],
                    [3, "lg:active:mx-3"],
                    [3.5, "lg:active:mx-3.5"],
                    [4, "lg:active:mx-4"],
                    [5, "lg:active:mx-5"],
                    [6, "lg:active:mx-6"],
                    [7, "lg:active:mx-7"],
                    [8, "lg:active:mx-8"],
                    [9, "lg:active:mx-9"],
                    [10, "lg:active:mx-10"],
                    [11, "lg:active:mx-11"],
                    [12, "lg:active:mx-12"],
                    [14, "lg:active:mx-14"],
                    [16, "lg:active:mx-16"],
                    [20, "lg:active:mx-20"],
                    [24, "lg:active:mx-24"],
                    [28, "lg:active:mx-28"],
                    [32, "lg:active:mx-32"],
                    [36, "lg:active:mx-36"],
                    [40, "lg:active:mx-40"],
                    [44, "lg:active:mx-44"],
                    [48, "lg:active:mx-48"],
                    [52, "lg:active:mx-52"],
                    [56, "lg:active:mx-56"],
                    [60, "lg:active:mx-60"],
                    [64, "lg:active:mx-64"],
                    [72, "lg:active:mx-72"],
                    [80, "lg:active:mx-80"],
                    [96, "lg:active:mx-96"],
                    ["auto", "lg:active:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "lg:active:my-0"],
                    ["px", "lg:active:my-px"],
                    [0.5, "lg:active:my-0.5"],
                    [1, "lg:active:my-1"],
                    [1.5, "lg:active:my-1.5"],
                    [2, "lg:active:my-2"],
                    [2.5, "lg:active:my-2.5"],
                    [3, "lg:active:my-3"],
                    [3.5, "lg:active:my-3.5"],
                    [4, "lg:active:my-4"],
                    [5, "lg:active:my-5"],
                    [6, "lg:active:my-6"],
                    [7, "lg:active:my-7"],
                    [8, "lg:active:my-8"],
                    [9, "lg:active:my-9"],
                    [10, "lg:active:my-10"],
                    [11, "lg:active:my-11"],
                    [12, "lg:active:my-12"],
                    [14, "lg:active:my-14"],
                    [16, "lg:active:my-16"],
                    [20, "lg:active:my-20"],
                    [24, "lg:active:my-24"],
                    [28, "lg:active:my-28"],
                    [32, "lg:active:my-32"],
                    [36, "lg:active:my-36"],
                    [40, "lg:active:my-40"],
                    [44, "lg:active:my-44"],
                    [48, "lg:active:my-48"],
                    [52, "lg:active:my-52"],
                    [56, "lg:active:my-56"],
                    [60, "lg:active:my-60"],
                    [64, "lg:active:my-64"],
                    [72, "lg:active:my-72"],
                    [80, "lg:active:my-80"],
                    [96, "lg:active:my-96"],
                    ["auto", "lg:active:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xl:active:mx-0"],
                    ["px", "xl:active:mx-px"],
                    [0.5, "xl:active:mx-0.5"],
                    [1, "xl:active:mx-1"],
                    [1.5, "xl:active:mx-1.5"],
                    [2, "xl:active:mx-2"],
                    [2.5, "xl:active:mx-2.5"],
                    [3, "xl:active:mx-3"],
                    [3.5, "xl:active:mx-3.5"],
                    [4, "xl:active:mx-4"],
                    [5, "xl:active:mx-5"],
                    [6, "xl:active:mx-6"],
                    [7, "xl:active:mx-7"],
                    [8, "xl:active:mx-8"],
                    [9, "xl:active:mx-9"],
                    [10, "xl:active:mx-10"],
                    [11, "xl:active:mx-11"],
                    [12, "xl:active:mx-12"],
                    [14, "xl:active:mx-14"],
                    [16, "xl:active:mx-16"],
                    [20, "xl:active:mx-20"],
                    [24, "xl:active:mx-24"],
                    [28, "xl:active:mx-28"],
                    [32, "xl:active:mx-32"],
                    [36, "xl:active:mx-36"],
                    [40, "xl:active:mx-40"],
                    [44, "xl:active:mx-44"],
                    [48, "xl:active:mx-48"],
                    [52, "xl:active:mx-52"],
                    [56, "xl:active:mx-56"],
                    [60, "xl:active:mx-60"],
                    [64, "xl:active:mx-64"],
                    [72, "xl:active:mx-72"],
                    [80, "xl:active:mx-80"],
                    [96, "xl:active:mx-96"],
                    ["auto", "xl:active:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xl:active:my-0"],
                    ["px", "xl:active:my-px"],
                    [0.5, "xl:active:my-0.5"],
                    [1, "xl:active:my-1"],
                    [1.5, "xl:active:my-1.5"],
                    [2, "xl:active:my-2"],
                    [2.5, "xl:active:my-2.5"],
                    [3, "xl:active:my-3"],
                    [3.5, "xl:active:my-3.5"],
                    [4, "xl:active:my-4"],
                    [5, "xl:active:my-5"],
                    [6, "xl:active:my-6"],
                    [7, "xl:active:my-7"],
                    [8, "xl:active:my-8"],
                    [9, "xl:active:my-9"],
                    [10, "xl:active:my-10"],
                    [11, "xl:active:my-11"],
                    [12, "xl:active:my-12"],
                    [14, "xl:active:my-14"],
                    [16, "xl:active:my-16"],
                    [20, "xl:active:my-20"],
                    [24, "xl:active:my-24"],
                    [28, "xl:active:my-28"],
                    [32, "xl:active:my-32"],
                    [36, "xl:active:my-36"],
                    [40, "xl:active:my-40"],
                    [44, "xl:active:my-44"],
                    [48, "xl:active:my-48"],
                    [52, "xl:active:my-52"],
                    [56, "xl:active:my-56"],
                    [60, "xl:active:my-60"],
                    [64, "xl:active:my-64"],
                    [72, "xl:active:my-72"],
                    [80, "xl:active:my-80"],
                    [96, "xl:active:my-96"],
                    ["auto", "xl:active:my-auto"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],

        [
          "disabled",
          new Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xs:disabled:mx-0"],
                    ["px", "xs:disabled:mx-px"],
                    [0.5, "xs:disabled:mx-0.5"],
                    [1, "xs:disabled:mx-1"],
                    [1.5, "xs:disabled:mx-1.5"],
                    [2, "xs:disabled:mx-2"],
                    [2.5, "xs:disabled:mx-2.5"],
                    [3, "xs:disabled:mx-3"],
                    [3.5, "xs:disabled:mx-3.5"],
                    [4, "xs:disabled:mx-4"],
                    [5, "xs:disabled:mx-5"],
                    [6, "xs:disabled:mx-6"],
                    [7, "xs:disabled:mx-7"],
                    [8, "xs:disabled:mx-8"],
                    [9, "xs:disabled:mx-9"],
                    [10, "xs:disabled:mx-10"],
                    [11, "xs:disabled:mx-11"],
                    [12, "xs:disabled:mx-12"],
                    [14, "xs:disabled:mx-14"],
                    [16, "xs:disabled:mx-16"],
                    [20, "xs:disabled:mx-20"],
                    [24, "xs:disabled:mx-24"],
                    [28, "xs:disabled:mx-28"],
                    [32, "xs:disabled:mx-32"],
                    [36, "xs:disabled:mx-36"],
                    [40, "xs:disabled:mx-40"],
                    [44, "xs:disabled:mx-44"],
                    [48, "xs:disabled:mx-48"],
                    [52, "xs:disabled:mx-52"],
                    [56, "xs:disabled:mx-56"],
                    [60, "xs:disabled:mx-60"],
                    [64, "xs:disabled:mx-64"],
                    [72, "xs:disabled:mx-72"],
                    [80, "xs:disabled:mx-80"],
                    [96, "xs:disabled:mx-96"],
                    ["auto", "xs:disabled:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xs:disabled:my-0"],
                    ["px", "xs:disabled:my-px"],
                    [0.5, "xs:disabled:my-0.5"],
                    [1, "xs:disabled:my-1"],
                    [1.5, "xs:disabled:my-1.5"],
                    [2, "xs:disabled:my-2"],
                    [2.5, "xs:disabled:my-2.5"],
                    [3, "xs:disabled:my-3"],
                    [3.5, "xs:disabled:my-3.5"],
                    [4, "xs:disabled:my-4"],
                    [5, "xs:disabled:my-5"],
                    [6, "xs:disabled:my-6"],
                    [7, "xs:disabled:my-7"],
                    [8, "xs:disabled:my-8"],
                    [9, "xs:disabled:my-9"],
                    [10, "xs:disabled:my-10"],
                    [11, "xs:disabled:my-11"],
                    [12, "xs:disabled:my-12"],
                    [14, "xs:disabled:my-14"],
                    [16, "xs:disabled:my-16"],
                    [20, "xs:disabled:my-20"],
                    [24, "xs:disabled:my-24"],
                    [28, "xs:disabled:my-28"],
                    [32, "xs:disabled:my-32"],
                    [36, "xs:disabled:my-36"],
                    [40, "xs:disabled:my-40"],
                    [44, "xs:disabled:my-44"],
                    [48, "xs:disabled:my-48"],
                    [52, "xs:disabled:my-52"],
                    [56, "xs:disabled:my-56"],
                    [60, "xs:disabled:my-60"],
                    [64, "xs:disabled:my-64"],
                    [72, "xs:disabled:my-72"],
                    [80, "xs:disabled:my-80"],
                    [96, "xs:disabled:my-96"],
                    ["auto", "xs:disabled:my-auto"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "sm:disabled:mx-0"],
                    ["px", "sm:disabled:mx-px"],
                    [0.5, "sm:disabled:mx-0.5"],
                    [1, "sm:disabled:mx-1"],
                    [1.5, "sm:disabled:mx-1.5"],
                    [2, "sm:disabled:mx-2"],
                    [2.5, "sm:disabled:mx-2.5"],
                    [3, "sm:disabled:mx-3"],
                    [3.5, "sm:disabled:mx-3.5"],
                    [4, "sm:disabled:mx-4"],
                    [5, "sm:disabled:mx-5"],
                    [6, "sm:disabled:mx-6"],
                    [7, "sm:disabled:mx-7"],
                    [8, "sm:disabled:mx-8"],
                    [9, "sm:disabled:mx-9"],
                    [10, "sm:disabled:mx-10"],
                    [11, "sm:disabled:mx-11"],
                    [12, "sm:disabled:mx-12"],
                    [14, "sm:disabled:mx-14"],
                    [16, "sm:disabled:mx-16"],
                    [20, "sm:disabled:mx-20"],
                    [24, "sm:disabled:mx-24"],
                    [28, "sm:disabled:mx-28"],
                    [32, "sm:disabled:mx-32"],
                    [36, "sm:disabled:mx-36"],
                    [40, "sm:disabled:mx-40"],
                    [44, "sm:disabled:mx-44"],
                    [48, "sm:disabled:mx-48"],
                    [52, "sm:disabled:mx-52"],
                    [56, "sm:disabled:mx-56"],
                    [60, "sm:disabled:mx-60"],
                    [64, "sm:disabled:mx-64"],
                    [72, "sm:disabled:mx-72"],
                    [80, "sm:disabled:mx-80"],
                    [96, "sm:disabled:mx-96"],
                    ["auto", "sm:disabled:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "sm:disabled:my-0"],
                    ["px", "sm:disabled:my-px"],
                    [0.5, "sm:disabled:my-0.5"],
                    [1, "sm:disabled:my-1"],
                    [1.5, "sm:disabled:my-1.5"],
                    [2, "sm:disabled:my-2"],
                    [2.5, "sm:disabled:my-2.5"],
                    [3, "sm:disabled:my-3"],
                    [3.5, "sm:disabled:my-3.5"],
                    [4, "sm:disabled:my-4"],
                    [5, "sm:disabled:my-5"],
                    [6, "sm:disabled:my-6"],
                    [7, "sm:disabled:my-7"],
                    [8, "sm:disabled:my-8"],
                    [9, "sm:disabled:my-9"],
                    [10, "sm:disabled:my-10"],
                    [11, "sm:disabled:my-11"],
                    [12, "sm:disabled:my-12"],
                    [14, "sm:disabled:my-14"],
                    [16, "sm:disabled:my-16"],
                    [20, "sm:disabled:my-20"],
                    [24, "sm:disabled:my-24"],
                    [28, "sm:disabled:my-28"],
                    [32, "sm:disabled:my-32"],
                    [36, "sm:disabled:my-36"],
                    [40, "sm:disabled:my-40"],
                    [44, "sm:disabled:my-44"],
                    [48, "sm:disabled:my-48"],
                    [52, "sm:disabled:my-52"],
                    [56, "sm:disabled:my-56"],
                    [60, "sm:disabled:my-60"],
                    [64, "sm:disabled:my-64"],
                    [72, "sm:disabled:my-72"],
                    [80, "sm:disabled:my-80"],
                    [96, "sm:disabled:my-96"],
                    ["auto", "sm:disabled:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "md:disabled:mx-0"],
                    ["px", "md:disabled:mx-px"],
                    [0.5, "md:disabled:mx-0.5"],
                    [1, "md:disabled:mx-1"],
                    [1.5, "md:disabled:mx-1.5"],
                    [2, "md:disabled:mx-2"],
                    [2.5, "md:disabled:mx-2.5"],
                    [3, "md:disabled:mx-3"],
                    [3.5, "md:disabled:mx-3.5"],
                    [4, "md:disabled:mx-4"],
                    [5, "md:disabled:mx-5"],
                    [6, "md:disabled:mx-6"],
                    [7, "md:disabled:mx-7"],
                    [8, "md:disabled:mx-8"],
                    [9, "md:disabled:mx-9"],
                    [10, "md:disabled:mx-10"],
                    [11, "md:disabled:mx-11"],
                    [12, "md:disabled:mx-12"],
                    [14, "md:disabled:mx-14"],
                    [16, "md:disabled:mx-16"],
                    [20, "md:disabled:mx-20"],
                    [24, "md:disabled:mx-24"],
                    [28, "md:disabled:mx-28"],
                    [32, "md:disabled:mx-32"],
                    [36, "md:disabled:mx-36"],
                    [40, "md:disabled:mx-40"],
                    [44, "md:disabled:mx-44"],
                    [48, "md:disabled:mx-48"],
                    [52, "md:disabled:mx-52"],
                    [56, "md:disabled:mx-56"],
                    [60, "md:disabled:mx-60"],
                    [64, "md:disabled:mx-64"],
                    [72, "md:disabled:mx-72"],
                    [80, "md:disabled:mx-80"],
                    [96, "md:disabled:mx-96"],
                    ["auto", "md:disabled:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "md:disabled:my-0"],
                    ["px", "md:disabled:my-px"],
                    [0.5, "md:disabled:my-0.5"],
                    [1, "md:disabled:my-1"],
                    [1.5, "md:disabled:my-1.5"],
                    [2, "md:disabled:my-2"],
                    [2.5, "md:disabled:my-2.5"],
                    [3, "md:disabled:my-3"],
                    [3.5, "md:disabled:my-3.5"],
                    [4, "md:disabled:my-4"],
                    [5, "md:disabled:my-5"],
                    [6, "md:disabled:my-6"],
                    [7, "md:disabled:my-7"],
                    [8, "md:disabled:my-8"],
                    [9, "md:disabled:my-9"],
                    [10, "md:disabled:my-10"],
                    [11, "md:disabled:my-11"],
                    [12, "md:disabled:my-12"],
                    [14, "md:disabled:my-14"],
                    [16, "md:disabled:my-16"],
                    [20, "md:disabled:my-20"],
                    [24, "md:disabled:my-24"],
                    [28, "md:disabled:my-28"],
                    [32, "md:disabled:my-32"],
                    [36, "md:disabled:my-36"],
                    [40, "md:disabled:my-40"],
                    [44, "md:disabled:my-44"],
                    [48, "md:disabled:my-48"],
                    [52, "md:disabled:my-52"],
                    [56, "md:disabled:my-56"],
                    [60, "md:disabled:my-60"],
                    [64, "md:disabled:my-64"],
                    [72, "md:disabled:my-72"],
                    [80, "md:disabled:my-80"],
                    [96, "md:disabled:my-96"],
                    ["auto", "md:disabled:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "lg:disabled:mx-0"],
                    ["px", "lg:disabled:mx-px"],
                    [0.5, "lg:disabled:mx-0.5"],
                    [1, "lg:disabled:mx-1"],
                    [1.5, "lg:disabled:mx-1.5"],
                    [2, "lg:disabled:mx-2"],
                    [2.5, "lg:disabled:mx-2.5"],
                    [3, "lg:disabled:mx-3"],
                    [3.5, "lg:disabled:mx-3.5"],
                    [4, "lg:disabled:mx-4"],
                    [5, "lg:disabled:mx-5"],
                    [6, "lg:disabled:mx-6"],
                    [7, "lg:disabled:mx-7"],
                    [8, "lg:disabled:mx-8"],
                    [9, "lg:disabled:mx-9"],
                    [10, "lg:disabled:mx-10"],
                    [11, "lg:disabled:mx-11"],
                    [12, "lg:disabled:mx-12"],
                    [14, "lg:disabled:mx-14"],
                    [16, "lg:disabled:mx-16"],
                    [20, "lg:disabled:mx-20"],
                    [24, "lg:disabled:mx-24"],
                    [28, "lg:disabled:mx-28"],
                    [32, "lg:disabled:mx-32"],
                    [36, "lg:disabled:mx-36"],
                    [40, "lg:disabled:mx-40"],
                    [44, "lg:disabled:mx-44"],
                    [48, "lg:disabled:mx-48"],
                    [52, "lg:disabled:mx-52"],
                    [56, "lg:disabled:mx-56"],
                    [60, "lg:disabled:mx-60"],
                    [64, "lg:disabled:mx-64"],
                    [72, "lg:disabled:mx-72"],
                    [80, "lg:disabled:mx-80"],
                    [96, "lg:disabled:mx-96"],
                    ["auto", "lg:disabled:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "lg:disabled:my-0"],
                    ["px", "lg:disabled:my-px"],
                    [0.5, "lg:disabled:my-0.5"],
                    [1, "lg:disabled:my-1"],
                    [1.5, "lg:disabled:my-1.5"],
                    [2, "lg:disabled:my-2"],
                    [2.5, "lg:disabled:my-2.5"],
                    [3, "lg:disabled:my-3"],
                    [3.5, "lg:disabled:my-3.5"],
                    [4, "lg:disabled:my-4"],
                    [5, "lg:disabled:my-5"],
                    [6, "lg:disabled:my-6"],
                    [7, "lg:disabled:my-7"],
                    [8, "lg:disabled:my-8"],
                    [9, "lg:disabled:my-9"],
                    [10, "lg:disabled:my-10"],
                    [11, "lg:disabled:my-11"],
                    [12, "lg:disabled:my-12"],
                    [14, "lg:disabled:my-14"],
                    [16, "lg:disabled:my-16"],
                    [20, "lg:disabled:my-20"],
                    [24, "lg:disabled:my-24"],
                    [28, "lg:disabled:my-28"],
                    [32, "lg:disabled:my-32"],
                    [36, "lg:disabled:my-36"],
                    [40, "lg:disabled:my-40"],
                    [44, "lg:disabled:my-44"],
                    [48, "lg:disabled:my-48"],
                    [52, "lg:disabled:my-52"],
                    [56, "lg:disabled:my-56"],
                    [60, "lg:disabled:my-60"],
                    [64, "lg:disabled:my-64"],
                    [72, "lg:disabled:my-72"],
                    [80, "lg:disabled:my-80"],
                    [96, "lg:disabled:my-96"],
                    ["auto", "lg:disabled:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xl:disabled:mx-0"],
                    ["px", "xl:disabled:mx-px"],
                    [0.5, "xl:disabled:mx-0.5"],
                    [1, "xl:disabled:mx-1"],
                    [1.5, "xl:disabled:mx-1.5"],
                    [2, "xl:disabled:mx-2"],
                    [2.5, "xl:disabled:mx-2.5"],
                    [3, "xl:disabled:mx-3"],
                    [3.5, "xl:disabled:mx-3.5"],
                    [4, "xl:disabled:mx-4"],
                    [5, "xl:disabled:mx-5"],
                    [6, "xl:disabled:mx-6"],
                    [7, "xl:disabled:mx-7"],
                    [8, "xl:disabled:mx-8"],
                    [9, "xl:disabled:mx-9"],
                    [10, "xl:disabled:mx-10"],
                    [11, "xl:disabled:mx-11"],
                    [12, "xl:disabled:mx-12"],
                    [14, "xl:disabled:mx-14"],
                    [16, "xl:disabled:mx-16"],
                    [20, "xl:disabled:mx-20"],
                    [24, "xl:disabled:mx-24"],
                    [28, "xl:disabled:mx-28"],
                    [32, "xl:disabled:mx-32"],
                    [36, "xl:disabled:mx-36"],
                    [40, "xl:disabled:mx-40"],
                    [44, "xl:disabled:mx-44"],
                    [48, "xl:disabled:mx-48"],
                    [52, "xl:disabled:mx-52"],
                    [56, "xl:disabled:mx-56"],
                    [60, "xl:disabled:mx-60"],
                    [64, "xl:disabled:mx-64"],
                    [72, "xl:disabled:mx-72"],
                    [80, "xl:disabled:mx-80"],
                    [96, "xl:disabled:mx-96"],
                    ["auto", "xl:disabled:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xl:disabled:my-0"],
                    ["px", "xl:disabled:my-px"],
                    [0.5, "xl:disabled:my-0.5"],
                    [1, "xl:disabled:my-1"],
                    [1.5, "xl:disabled:my-1.5"],
                    [2, "xl:disabled:my-2"],
                    [2.5, "xl:disabled:my-2.5"],
                    [3, "xl:disabled:my-3"],
                    [3.5, "xl:disabled:my-3.5"],
                    [4, "xl:disabled:my-4"],
                    [5, "xl:disabled:my-5"],
                    [6, "xl:disabled:my-6"],
                    [7, "xl:disabled:my-7"],
                    [8, "xl:disabled:my-8"],
                    [9, "xl:disabled:my-9"],
                    [10, "xl:disabled:my-10"],
                    [11, "xl:disabled:my-11"],
                    [12, "xl:disabled:my-12"],
                    [14, "xl:disabled:my-14"],
                    [16, "xl:disabled:my-16"],
                    [20, "xl:disabled:my-20"],
                    [24, "xl:disabled:my-24"],
                    [28, "xl:disabled:my-28"],
                    [32, "xl:disabled:my-32"],
                    [36, "xl:disabled:my-36"],
                    [40, "xl:disabled:my-40"],
                    [44, "xl:disabled:my-44"],
                    [48, "xl:disabled:my-48"],
                    [52, "xl:disabled:my-52"],
                    [56, "xl:disabled:my-56"],
                    [60, "xl:disabled:my-60"],
                    [64, "xl:disabled:my-64"],
                    [72, "xl:disabled:my-72"],
                    [80, "xl:disabled:my-80"],
                    [96, "xl:disabled:my-96"],
                    ["auto", "xl:disabled:my-auto"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xs:hover:mx-0"],
                    ["px", "xs:hover:mx-px"],
                    [0.5, "xs:hover:mx-0.5"],
                    [1, "xs:hover:mx-1"],
                    [1.5, "xs:hover:mx-1.5"],
                    [2, "xs:hover:mx-2"],
                    [2.5, "xs:hover:mx-2.5"],
                    [3, "xs:hover:mx-3"],
                    [3.5, "xs:hover:mx-3.5"],
                    [4, "xs:hover:mx-4"],
                    [5, "xs:hover:mx-5"],
                    [6, "xs:hover:mx-6"],
                    [7, "xs:hover:mx-7"],
                    [8, "xs:hover:mx-8"],
                    [9, "xs:hover:mx-9"],
                    [10, "xs:hover:mx-10"],
                    [11, "xs:hover:mx-11"],
                    [12, "xs:hover:mx-12"],
                    [14, "xs:hover:mx-14"],
                    [16, "xs:hover:mx-16"],
                    [20, "xs:hover:mx-20"],
                    [24, "xs:hover:mx-24"],
                    [28, "xs:hover:mx-28"],
                    [32, "xs:hover:mx-32"],
                    [36, "xs:hover:mx-36"],
                    [40, "xs:hover:mx-40"],
                    [44, "xs:hover:mx-44"],
                    [48, "xs:hover:mx-48"],
                    [52, "xs:hover:mx-52"],
                    [56, "xs:hover:mx-56"],
                    [60, "xs:hover:mx-60"],
                    [64, "xs:hover:mx-64"],
                    [72, "xs:hover:mx-72"],
                    [80, "xs:hover:mx-80"],
                    [96, "xs:hover:mx-96"],
                    ["auto", "xs:hover:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xs:hover:my-0"],
                    ["px", "xs:hover:my-px"],
                    [0.5, "xs:hover:my-0.5"],
                    [1, "xs:hover:my-1"],
                    [1.5, "xs:hover:my-1.5"],
                    [2, "xs:hover:my-2"],
                    [2.5, "xs:hover:my-2.5"],
                    [3, "xs:hover:my-3"],
                    [3.5, "xs:hover:my-3.5"],
                    [4, "xs:hover:my-4"],
                    [5, "xs:hover:my-5"],
                    [6, "xs:hover:my-6"],
                    [7, "xs:hover:my-7"],
                    [8, "xs:hover:my-8"],
                    [9, "xs:hover:my-9"],
                    [10, "xs:hover:my-10"],
                    [11, "xs:hover:my-11"],
                    [12, "xs:hover:my-12"],
                    [14, "xs:hover:my-14"],
                    [16, "xs:hover:my-16"],
                    [20, "xs:hover:my-20"],
                    [24, "xs:hover:my-24"],
                    [28, "xs:hover:my-28"],
                    [32, "xs:hover:my-32"],
                    [36, "xs:hover:my-36"],
                    [40, "xs:hover:my-40"],
                    [44, "xs:hover:my-44"],
                    [48, "xs:hover:my-48"],
                    [52, "xs:hover:my-52"],
                    [56, "xs:hover:my-56"],
                    [60, "xs:hover:my-60"],
                    [64, "xs:hover:my-64"],
                    [72, "xs:hover:my-72"],
                    [80, "xs:hover:my-80"],
                    [96, "xs:hover:my-96"],
                    ["auto", "xs:hover:my-auto"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "sm:hover:mx-0"],
                    ["px", "sm:hover:mx-px"],
                    [0.5, "sm:hover:mx-0.5"],
                    [1, "sm:hover:mx-1"],
                    [1.5, "sm:hover:mx-1.5"],
                    [2, "sm:hover:mx-2"],
                    [2.5, "sm:hover:mx-2.5"],
                    [3, "sm:hover:mx-3"],
                    [3.5, "sm:hover:mx-3.5"],
                    [4, "sm:hover:mx-4"],
                    [5, "sm:hover:mx-5"],
                    [6, "sm:hover:mx-6"],
                    [7, "sm:hover:mx-7"],
                    [8, "sm:hover:mx-8"],
                    [9, "sm:hover:mx-9"],
                    [10, "sm:hover:mx-10"],
                    [11, "sm:hover:mx-11"],
                    [12, "sm:hover:mx-12"],
                    [14, "sm:hover:mx-14"],
                    [16, "sm:hover:mx-16"],
                    [20, "sm:hover:mx-20"],
                    [24, "sm:hover:mx-24"],
                    [28, "sm:hover:mx-28"],
                    [32, "sm:hover:mx-32"],
                    [36, "sm:hover:mx-36"],
                    [40, "sm:hover:mx-40"],
                    [44, "sm:hover:mx-44"],
                    [48, "sm:hover:mx-48"],
                    [52, "sm:hover:mx-52"],
                    [56, "sm:hover:mx-56"],
                    [60, "sm:hover:mx-60"],
                    [64, "sm:hover:mx-64"],
                    [72, "sm:hover:mx-72"],
                    [80, "sm:hover:mx-80"],
                    [96, "sm:hover:mx-96"],
                    ["auto", "sm:hover:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "sm:hover:my-0"],
                    ["px", "sm:hover:my-px"],
                    [0.5, "sm:hover:my-0.5"],
                    [1, "sm:hover:my-1"],
                    [1.5, "sm:hover:my-1.5"],
                    [2, "sm:hover:my-2"],
                    [2.5, "sm:hover:my-2.5"],
                    [3, "sm:hover:my-3"],
                    [3.5, "sm:hover:my-3.5"],
                    [4, "sm:hover:my-4"],
                    [5, "sm:hover:my-5"],
                    [6, "sm:hover:my-6"],
                    [7, "sm:hover:my-7"],
                    [8, "sm:hover:my-8"],
                    [9, "sm:hover:my-9"],
                    [10, "sm:hover:my-10"],
                    [11, "sm:hover:my-11"],
                    [12, "sm:hover:my-12"],
                    [14, "sm:hover:my-14"],
                    [16, "sm:hover:my-16"],
                    [20, "sm:hover:my-20"],
                    [24, "sm:hover:my-24"],
                    [28, "sm:hover:my-28"],
                    [32, "sm:hover:my-32"],
                    [36, "sm:hover:my-36"],
                    [40, "sm:hover:my-40"],
                    [44, "sm:hover:my-44"],
                    [48, "sm:hover:my-48"],
                    [52, "sm:hover:my-52"],
                    [56, "sm:hover:my-56"],
                    [60, "sm:hover:my-60"],
                    [64, "sm:hover:my-64"],
                    [72, "sm:hover:my-72"],
                    [80, "sm:hover:my-80"],
                    [96, "sm:hover:my-96"],
                    ["auto", "sm:hover:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "md:hover:mx-0"],
                    ["px", "md:hover:mx-px"],
                    [0.5, "md:hover:mx-0.5"],
                    [1, "md:hover:mx-1"],
                    [1.5, "md:hover:mx-1.5"],
                    [2, "md:hover:mx-2"],
                    [2.5, "md:hover:mx-2.5"],
                    [3, "md:hover:mx-3"],
                    [3.5, "md:hover:mx-3.5"],
                    [4, "md:hover:mx-4"],
                    [5, "md:hover:mx-5"],
                    [6, "md:hover:mx-6"],
                    [7, "md:hover:mx-7"],
                    [8, "md:hover:mx-8"],
                    [9, "md:hover:mx-9"],
                    [10, "md:hover:mx-10"],
                    [11, "md:hover:mx-11"],
                    [12, "md:hover:mx-12"],
                    [14, "md:hover:mx-14"],
                    [16, "md:hover:mx-16"],
                    [20, "md:hover:mx-20"],
                    [24, "md:hover:mx-24"],
                    [28, "md:hover:mx-28"],
                    [32, "md:hover:mx-32"],
                    [36, "md:hover:mx-36"],
                    [40, "md:hover:mx-40"],
                    [44, "md:hover:mx-44"],
                    [48, "md:hover:mx-48"],
                    [52, "md:hover:mx-52"],
                    [56, "md:hover:mx-56"],
                    [60, "md:hover:mx-60"],
                    [64, "md:hover:mx-64"],
                    [72, "md:hover:mx-72"],
                    [80, "md:hover:mx-80"],
                    [96, "md:hover:mx-96"],
                    ["auto", "md:hover:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "md:hover:my-0"],
                    ["px", "md:hover:my-px"],
                    [0.5, "md:hover:my-0.5"],
                    [1, "md:hover:my-1"],
                    [1.5, "md:hover:my-1.5"],
                    [2, "md:hover:my-2"],
                    [2.5, "md:hover:my-2.5"],
                    [3, "md:hover:my-3"],
                    [3.5, "md:hover:my-3.5"],
                    [4, "md:hover:my-4"],
                    [5, "md:hover:my-5"],
                    [6, "md:hover:my-6"],
                    [7, "md:hover:my-7"],
                    [8, "md:hover:my-8"],
                    [9, "md:hover:my-9"],
                    [10, "md:hover:my-10"],
                    [11, "md:hover:my-11"],
                    [12, "md:hover:my-12"],
                    [14, "md:hover:my-14"],
                    [16, "md:hover:my-16"],
                    [20, "md:hover:my-20"],
                    [24, "md:hover:my-24"],
                    [28, "md:hover:my-28"],
                    [32, "md:hover:my-32"],
                    [36, "md:hover:my-36"],
                    [40, "md:hover:my-40"],
                    [44, "md:hover:my-44"],
                    [48, "md:hover:my-48"],
                    [52, "md:hover:my-52"],
                    [56, "md:hover:my-56"],
                    [60, "md:hover:my-60"],
                    [64, "md:hover:my-64"],
                    [72, "md:hover:my-72"],
                    [80, "md:hover:my-80"],
                    [96, "md:hover:my-96"],
                    ["auto", "md:hover:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "lg:hover:mx-0"],
                    ["px", "lg:hover:mx-px"],
                    [0.5, "lg:hover:mx-0.5"],
                    [1, "lg:hover:mx-1"],
                    [1.5, "lg:hover:mx-1.5"],
                    [2, "lg:hover:mx-2"],
                    [2.5, "lg:hover:mx-2.5"],
                    [3, "lg:hover:mx-3"],
                    [3.5, "lg:hover:mx-3.5"],
                    [4, "lg:hover:mx-4"],
                    [5, "lg:hover:mx-5"],
                    [6, "lg:hover:mx-6"],
                    [7, "lg:hover:mx-7"],
                    [8, "lg:hover:mx-8"],
                    [9, "lg:hover:mx-9"],
                    [10, "lg:hover:mx-10"],
                    [11, "lg:hover:mx-11"],
                    [12, "lg:hover:mx-12"],
                    [14, "lg:hover:mx-14"],
                    [16, "lg:hover:mx-16"],
                    [20, "lg:hover:mx-20"],
                    [24, "lg:hover:mx-24"],
                    [28, "lg:hover:mx-28"],
                    [32, "lg:hover:mx-32"],
                    [36, "lg:hover:mx-36"],
                    [40, "lg:hover:mx-40"],
                    [44, "lg:hover:mx-44"],
                    [48, "lg:hover:mx-48"],
                    [52, "lg:hover:mx-52"],
                    [56, "lg:hover:mx-56"],
                    [60, "lg:hover:mx-60"],
                    [64, "lg:hover:mx-64"],
                    [72, "lg:hover:mx-72"],
                    [80, "lg:hover:mx-80"],
                    [96, "lg:hover:mx-96"],
                    ["auto", "lg:hover:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "lg:hover:my-0"],
                    ["px", "lg:hover:my-px"],
                    [0.5, "lg:hover:my-0.5"],
                    [1, "lg:hover:my-1"],
                    [1.5, "lg:hover:my-1.5"],
                    [2, "lg:hover:my-2"],
                    [2.5, "lg:hover:my-2.5"],
                    [3, "lg:hover:my-3"],
                    [3.5, "lg:hover:my-3.5"],
                    [4, "lg:hover:my-4"],
                    [5, "lg:hover:my-5"],
                    [6, "lg:hover:my-6"],
                    [7, "lg:hover:my-7"],
                    [8, "lg:hover:my-8"],
                    [9, "lg:hover:my-9"],
                    [10, "lg:hover:my-10"],
                    [11, "lg:hover:my-11"],
                    [12, "lg:hover:my-12"],
                    [14, "lg:hover:my-14"],
                    [16, "lg:hover:my-16"],
                    [20, "lg:hover:my-20"],
                    [24, "lg:hover:my-24"],
                    [28, "lg:hover:my-28"],
                    [32, "lg:hover:my-32"],
                    [36, "lg:hover:my-36"],
                    [40, "lg:hover:my-40"],
                    [44, "lg:hover:my-44"],
                    [48, "lg:hover:my-48"],
                    [52, "lg:hover:my-52"],
                    [56, "lg:hover:my-56"],
                    [60, "lg:hover:my-60"],
                    [64, "lg:hover:my-64"],
                    [72, "lg:hover:my-72"],
                    [80, "lg:hover:my-80"],
                    [96, "lg:hover:my-96"],
                    ["auto", "lg:hover:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xl:hover:mx-0"],
                    ["px", "xl:hover:mx-px"],
                    [0.5, "xl:hover:mx-0.5"],
                    [1, "xl:hover:mx-1"],
                    [1.5, "xl:hover:mx-1.5"],
                    [2, "xl:hover:mx-2"],
                    [2.5, "xl:hover:mx-2.5"],
                    [3, "xl:hover:mx-3"],
                    [3.5, "xl:hover:mx-3.5"],
                    [4, "xl:hover:mx-4"],
                    [5, "xl:hover:mx-5"],
                    [6, "xl:hover:mx-6"],
                    [7, "xl:hover:mx-7"],
                    [8, "xl:hover:mx-8"],
                    [9, "xl:hover:mx-9"],
                    [10, "xl:hover:mx-10"],
                    [11, "xl:hover:mx-11"],
                    [12, "xl:hover:mx-12"],
                    [14, "xl:hover:mx-14"],
                    [16, "xl:hover:mx-16"],
                    [20, "xl:hover:mx-20"],
                    [24, "xl:hover:mx-24"],
                    [28, "xl:hover:mx-28"],
                    [32, "xl:hover:mx-32"],
                    [36, "xl:hover:mx-36"],
                    [40, "xl:hover:mx-40"],
                    [44, "xl:hover:mx-44"],
                    [48, "xl:hover:mx-48"],
                    [52, "xl:hover:mx-52"],
                    [56, "xl:hover:mx-56"],
                    [60, "xl:hover:mx-60"],
                    [64, "xl:hover:mx-64"],
                    [72, "xl:hover:mx-72"],
                    [80, "xl:hover:mx-80"],
                    [96, "xl:hover:mx-96"],
                    ["auto", "xl:hover:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xl:hover:my-0"],
                    ["px", "xl:hover:my-px"],
                    [0.5, "xl:hover:my-0.5"],
                    [1, "xl:hover:my-1"],
                    [1.5, "xl:hover:my-1.5"],
                    [2, "xl:hover:my-2"],
                    [2.5, "xl:hover:my-2.5"],
                    [3, "xl:hover:my-3"],
                    [3.5, "xl:hover:my-3.5"],
                    [4, "xl:hover:my-4"],
                    [5, "xl:hover:my-5"],
                    [6, "xl:hover:my-6"],
                    [7, "xl:hover:my-7"],
                    [8, "xl:hover:my-8"],
                    [9, "xl:hover:my-9"],
                    [10, "xl:hover:my-10"],
                    [11, "xl:hover:my-11"],
                    [12, "xl:hover:my-12"],
                    [14, "xl:hover:my-14"],
                    [16, "xl:hover:my-16"],
                    [20, "xl:hover:my-20"],
                    [24, "xl:hover:my-24"],
                    [28, "xl:hover:my-28"],
                    [32, "xl:hover:my-32"],
                    [36, "xl:hover:my-36"],
                    [40, "xl:hover:my-40"],
                    [44, "xl:hover:my-44"],
                    [48, "xl:hover:my-48"],
                    [52, "xl:hover:my-52"],
                    [56, "xl:hover:my-56"],
                    [60, "xl:hover:my-60"],
                    [64, "xl:hover:my-64"],
                    [72, "xl:hover:my-72"],
                    [80, "xl:hover:my-80"],
                    [96, "xl:hover:my-96"],
                    ["auto", "xl:hover:my-auto"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xs:mx-0"],
                    ["px", "xs:mx-px"],
                    [0.5, "xs:mx-0.5"],
                    [1, "xs:mx-1"],
                    [1.5, "xs:mx-1.5"],
                    [2, "xs:mx-2"],
                    [2.5, "xs:mx-2.5"],
                    [3, "xs:mx-3"],
                    [3.5, "xs:mx-3.5"],
                    [4, "xs:mx-4"],
                    [5, "xs:mx-5"],
                    [6, "xs:mx-6"],
                    [7, "xs:mx-7"],
                    [8, "xs:mx-8"],
                    [9, "xs:mx-9"],
                    [10, "xs:mx-10"],
                    [11, "xs:mx-11"],
                    [12, "xs:mx-12"],
                    [14, "xs:mx-14"],
                    [16, "xs:mx-16"],
                    [20, "xs:mx-20"],
                    [24, "xs:mx-24"],
                    [28, "xs:mx-28"],
                    [32, "xs:mx-32"],
                    [36, "xs:mx-36"],
                    [40, "xs:mx-40"],
                    [44, "xs:mx-44"],
                    [48, "xs:mx-48"],
                    [52, "xs:mx-52"],
                    [56, "xs:mx-56"],
                    [60, "xs:mx-60"],
                    [64, "xs:mx-64"],
                    [72, "xs:mx-72"],
                    [80, "xs:mx-80"],
                    [96, "xs:mx-96"],
                    ["auto", "xs:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xs:my-0"],
                    ["px", "xs:my-px"],
                    [0.5, "xs:my-0.5"],
                    [1, "xs:my-1"],
                    [1.5, "xs:my-1.5"],
                    [2, "xs:my-2"],
                    [2.5, "xs:my-2.5"],
                    [3, "xs:my-3"],
                    [3.5, "xs:my-3.5"],
                    [4, "xs:my-4"],
                    [5, "xs:my-5"],
                    [6, "xs:my-6"],
                    [7, "xs:my-7"],
                    [8, "xs:my-8"],
                    [9, "xs:my-9"],
                    [10, "xs:my-10"],
                    [11, "xs:my-11"],
                    [12, "xs:my-12"],
                    [14, "xs:my-14"],
                    [16, "xs:my-16"],
                    [20, "xs:my-20"],
                    [24, "xs:my-24"],
                    [28, "xs:my-28"],
                    [32, "xs:my-32"],
                    [36, "xs:my-36"],
                    [40, "xs:my-40"],
                    [44, "xs:my-44"],
                    [48, "xs:my-48"],
                    [52, "xs:my-52"],
                    [56, "xs:my-56"],
                    [60, "xs:my-60"],
                    [64, "xs:my-64"],
                    [72, "xs:my-72"],
                    [80, "xs:my-80"],
                    [96, "xs:my-96"],
                    ["auto", "xs:my-auto"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "sm:mx-0"],
                    ["px", "sm:mx-px"],
                    [0.5, "sm:mx-0.5"],
                    [1, "sm:mx-1"],
                    [1.5, "sm:mx-1.5"],
                    [2, "sm:mx-2"],
                    [2.5, "sm:mx-2.5"],
                    [3, "sm:mx-3"],
                    [3.5, "sm:mx-3.5"],
                    [4, "sm:mx-4"],
                    [5, "sm:mx-5"],
                    [6, "sm:mx-6"],
                    [7, "sm:mx-7"],
                    [8, "sm:mx-8"],
                    [9, "sm:mx-9"],
                    [10, "sm:mx-10"],
                    [11, "sm:mx-11"],
                    [12, "sm:mx-12"],
                    [14, "sm:mx-14"],
                    [16, "sm:mx-16"],
                    [20, "sm:mx-20"],
                    [24, "sm:mx-24"],
                    [28, "sm:mx-28"],
                    [32, "sm:mx-32"],
                    [36, "sm:mx-36"],
                    [40, "sm:mx-40"],
                    [44, "sm:mx-44"],
                    [48, "sm:mx-48"],
                    [52, "sm:mx-52"],
                    [56, "sm:mx-56"],
                    [60, "sm:mx-60"],
                    [64, "sm:mx-64"],
                    [72, "sm:mx-72"],
                    [80, "sm:mx-80"],
                    [96, "sm:mx-96"],
                    ["auto", "sm:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "sm:my-0"],
                    ["px", "sm:my-px"],
                    [0.5, "sm:my-0.5"],
                    [1, "sm:my-1"],
                    [1.5, "sm:my-1.5"],
                    [2, "sm:my-2"],
                    [2.5, "sm:my-2.5"],
                    [3, "sm:my-3"],
                    [3.5, "sm:my-3.5"],
                    [4, "sm:my-4"],
                    [5, "sm:my-5"],
                    [6, "sm:my-6"],
                    [7, "sm:my-7"],
                    [8, "sm:my-8"],
                    [9, "sm:my-9"],
                    [10, "sm:my-10"],
                    [11, "sm:my-11"],
                    [12, "sm:my-12"],
                    [14, "sm:my-14"],
                    [16, "sm:my-16"],
                    [20, "sm:my-20"],
                    [24, "sm:my-24"],
                    [28, "sm:my-28"],
                    [32, "sm:my-32"],
                    [36, "sm:my-36"],
                    [40, "sm:my-40"],
                    [44, "sm:my-44"],
                    [48, "sm:my-48"],
                    [52, "sm:my-52"],
                    [56, "sm:my-56"],
                    [60, "sm:my-60"],
                    [64, "sm:my-64"],
                    [72, "sm:my-72"],
                    [80, "sm:my-80"],
                    [96, "sm:my-96"],
                    ["auto", "sm:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "md:mx-0"],
                    ["px", "md:mx-px"],
                    [0.5, "md:mx-0.5"],
                    [1, "md:mx-1"],
                    [1.5, "md:mx-1.5"],
                    [2, "md:mx-2"],
                    [2.5, "md:mx-2.5"],
                    [3, "md:mx-3"],
                    [3.5, "md:mx-3.5"],
                    [4, "md:mx-4"],
                    [5, "md:mx-5"],
                    [6, "md:mx-6"],
                    [7, "md:mx-7"],
                    [8, "md:mx-8"],
                    [9, "md:mx-9"],
                    [10, "md:mx-10"],
                    [11, "md:mx-11"],
                    [12, "md:mx-12"],
                    [14, "md:mx-14"],
                    [16, "md:mx-16"],
                    [20, "md:mx-20"],
                    [24, "md:mx-24"],
                    [28, "md:mx-28"],
                    [32, "md:mx-32"],
                    [36, "md:mx-36"],
                    [40, "md:mx-40"],
                    [44, "md:mx-44"],
                    [48, "md:mx-48"],
                    [52, "md:mx-52"],
                    [56, "md:mx-56"],
                    [60, "md:mx-60"],
                    [64, "md:mx-64"],
                    [72, "md:mx-72"],
                    [80, "md:mx-80"],
                    [96, "md:mx-96"],
                    ["auto", "md:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "md:my-0"],
                    ["px", "md:my-px"],
                    [0.5, "md:my-0.5"],
                    [1, "md:my-1"],
                    [1.5, "md:my-1.5"],
                    [2, "md:my-2"],
                    [2.5, "md:my-2.5"],
                    [3, "md:my-3"],
                    [3.5, "md:my-3.5"],
                    [4, "md:my-4"],
                    [5, "md:my-5"],
                    [6, "md:my-6"],
                    [7, "md:my-7"],
                    [8, "md:my-8"],
                    [9, "md:my-9"],
                    [10, "md:my-10"],
                    [11, "md:my-11"],
                    [12, "md:my-12"],
                    [14, "md:my-14"],
                    [16, "md:my-16"],
                    [20, "md:my-20"],
                    [24, "md:my-24"],
                    [28, "md:my-28"],
                    [32, "md:my-32"],
                    [36, "md:my-36"],
                    [40, "md:my-40"],
                    [44, "md:my-44"],
                    [48, "md:my-48"],
                    [52, "md:my-52"],
                    [56, "md:my-56"],
                    [60, "md:my-60"],
                    [64, "md:my-64"],
                    [72, "md:my-72"],
                    [80, "md:my-80"],
                    [96, "md:my-96"],
                    ["auto", "md:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "lg:mx-0"],
                    ["px", "lg:mx-px"],
                    [0.5, "lg:mx-0.5"],
                    [1, "lg:mx-1"],
                    [1.5, "lg:mx-1.5"],
                    [2, "lg:mx-2"],
                    [2.5, "lg:mx-2.5"],
                    [3, "lg:mx-3"],
                    [3.5, "lg:mx-3.5"],
                    [4, "lg:mx-4"],
                    [5, "lg:mx-5"],
                    [6, "lg:mx-6"],
                    [7, "lg:mx-7"],
                    [8, "lg:mx-8"],
                    [9, "lg:mx-9"],
                    [10, "lg:mx-10"],
                    [11, "lg:mx-11"],
                    [12, "lg:mx-12"],
                    [14, "lg:mx-14"],
                    [16, "lg:mx-16"],
                    [20, "lg:mx-20"],
                    [24, "lg:mx-24"],
                    [28, "lg:mx-28"],
                    [32, "lg:mx-32"],
                    [36, "lg:mx-36"],
                    [40, "lg:mx-40"],
                    [44, "lg:mx-44"],
                    [48, "lg:mx-48"],
                    [52, "lg:mx-52"],
                    [56, "lg:mx-56"],
                    [60, "lg:mx-60"],
                    [64, "lg:mx-64"],
                    [72, "lg:mx-72"],
                    [80, "lg:mx-80"],
                    [96, "lg:mx-96"],
                    ["auto", "lg:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "lg:my-0"],
                    ["px", "lg:my-px"],
                    [0.5, "lg:my-0.5"],
                    [1, "lg:my-1"],
                    [1.5, "lg:my-1.5"],
                    [2, "lg:my-2"],
                    [2.5, "lg:my-2.5"],
                    [3, "lg:my-3"],
                    [3.5, "lg:my-3.5"],
                    [4, "lg:my-4"],
                    [5, "lg:my-5"],
                    [6, "lg:my-6"],
                    [7, "lg:my-7"],
                    [8, "lg:my-8"],
                    [9, "lg:my-9"],
                    [10, "lg:my-10"],
                    [11, "lg:my-11"],
                    [12, "lg:my-12"],
                    [14, "lg:my-14"],
                    [16, "lg:my-16"],
                    [20, "lg:my-20"],
                    [24, "lg:my-24"],
                    [28, "lg:my-28"],
                    [32, "lg:my-32"],
                    [36, "lg:my-36"],
                    [40, "lg:my-40"],
                    [44, "lg:my-44"],
                    [48, "lg:my-48"],
                    [52, "lg:my-52"],
                    [56, "lg:my-56"],
                    [60, "lg:my-60"],
                    [64, "lg:my-64"],
                    [72, "lg:my-72"],
                    [80, "lg:my-80"],
                    [96, "lg:my-96"],
                    ["auto", "lg:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xl:mx-0"],
                    ["px", "xl:mx-px"],
                    [0.5, "xl:mx-0.5"],
                    [1, "xl:mx-1"],
                    [1.5, "xl:mx-1.5"],
                    [2, "xl:mx-2"],
                    [2.5, "xl:mx-2.5"],
                    [3, "xl:mx-3"],
                    [3.5, "xl:mx-3.5"],
                    [4, "xl:mx-4"],
                    [5, "xl:mx-5"],
                    [6, "xl:mx-6"],
                    [7, "xl:mx-7"],
                    [8, "xl:mx-8"],
                    [9, "xl:mx-9"],
                    [10, "xl:mx-10"],
                    [11, "xl:mx-11"],
                    [12, "xl:mx-12"],
                    [14, "xl:mx-14"],
                    [16, "xl:mx-16"],
                    [20, "xl:mx-20"],
                    [24, "xl:mx-24"],
                    [28, "xl:mx-28"],
                    [32, "xl:mx-32"],
                    [36, "xl:mx-36"],
                    [40, "xl:mx-40"],
                    [44, "xl:mx-44"],
                    [48, "xl:mx-48"],
                    [52, "xl:mx-52"],
                    [56, "xl:mx-56"],
                    [60, "xl:mx-60"],
                    [64, "xl:mx-64"],
                    [72, "xl:mx-72"],
                    [80, "xl:mx-80"],
                    [96, "xl:mx-96"],
                    ["auto", "xl:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xl:my-0"],
                    ["px", "xl:my-px"],
                    [0.5, "xl:my-0.5"],
                    [1, "xl:my-1"],
                    [1.5, "xl:my-1.5"],
                    [2, "xl:my-2"],
                    [2.5, "xl:my-2.5"],
                    [3, "xl:my-3"],
                    [3.5, "xl:my-3.5"],
                    [4, "xl:my-4"],
                    [5, "xl:my-5"],
                    [6, "xl:my-6"],
                    [7, "xl:my-7"],
                    [8, "xl:my-8"],
                    [9, "xl:my-9"],
                    [10, "xl:my-10"],
                    [11, "xl:my-11"],
                    [12, "xl:my-12"],
                    [14, "xl:my-14"],
                    [16, "xl:my-16"],
                    [20, "xl:my-20"],
                    [24, "xl:my-24"],
                    [28, "xl:my-28"],
                    [32, "xl:my-32"],
                    [36, "xl:my-36"],
                    [40, "xl:my-40"],
                    [44, "xl:my-44"],
                    [48, "xl:my-48"],
                    [52, "xl:my-52"],
                    [56, "xl:my-56"],
                    [60, "xl:my-60"],
                    [64, "xl:my-64"],
                    [72, "xl:my-72"],
                    [80, "xl:my-80"],
                    [96, "xl:my-96"],
                    ["auto", "xl:my-auto"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>([
            [
              "xs",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xs:open:mx-0"],
                    ["px", "xs:open:mx-px"],
                    [0.5, "xs:open:mx-0.5"],
                    [1, "xs:open:mx-1"],
                    [1.5, "xs:open:mx-1.5"],
                    [2, "xs:open:mx-2"],
                    [2.5, "xs:open:mx-2.5"],
                    [3, "xs:open:mx-3"],
                    [3.5, "xs:open:mx-3.5"],
                    [4, "xs:open:mx-4"],
                    [5, "xs:open:mx-5"],
                    [6, "xs:open:mx-6"],
                    [7, "xs:open:mx-7"],
                    [8, "xs:open:mx-8"],
                    [9, "xs:open:mx-9"],
                    [10, "xs:open:mx-10"],
                    [11, "xs:open:mx-11"],
                    [12, "xs:open:mx-12"],
                    [14, "xs:open:mx-14"],
                    [16, "xs:open:mx-16"],
                    [20, "xs:open:mx-20"],
                    [24, "xs:open:mx-24"],
                    [28, "xs:open:mx-28"],
                    [32, "xs:open:mx-32"],
                    [36, "xs:open:mx-36"],
                    [40, "xs:open:mx-40"],
                    [44, "xs:open:mx-44"],
                    [48, "xs:open:mx-48"],
                    [52, "xs:open:mx-52"],
                    [56, "xs:open:mx-56"],
                    [60, "xs:open:mx-60"],
                    [64, "xs:open:mx-64"],
                    [72, "xs:open:mx-72"],
                    [80, "xs:open:mx-80"],
                    [96, "xs:open:mx-96"],
                    ["auto", "xs:open:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xs:open:my-0"],
                    ["px", "xs:open:my-px"],
                    [0.5, "xs:open:my-0.5"],
                    [1, "xs:open:my-1"],
                    [1.5, "xs:open:my-1.5"],
                    [2, "xs:open:my-2"],
                    [2.5, "xs:open:my-2.5"],
                    [3, "xs:open:my-3"],
                    [3.5, "xs:open:my-3.5"],
                    [4, "xs:open:my-4"],
                    [5, "xs:open:my-5"],
                    [6, "xs:open:my-6"],
                    [7, "xs:open:my-7"],
                    [8, "xs:open:my-8"],
                    [9, "xs:open:my-9"],
                    [10, "xs:open:my-10"],
                    [11, "xs:open:my-11"],
                    [12, "xs:open:my-12"],
                    [14, "xs:open:my-14"],
                    [16, "xs:open:my-16"],
                    [20, "xs:open:my-20"],
                    [24, "xs:open:my-24"],
                    [28, "xs:open:my-28"],
                    [32, "xs:open:my-32"],
                    [36, "xs:open:my-36"],
                    [40, "xs:open:my-40"],
                    [44, "xs:open:my-44"],
                    [48, "xs:open:my-48"],
                    [52, "xs:open:my-52"],
                    [56, "xs:open:my-56"],
                    [60, "xs:open:my-60"],
                    [64, "xs:open:my-64"],
                    [72, "xs:open:my-72"],
                    [80, "xs:open:my-80"],
                    [96, "xs:open:my-96"],
                    ["auto", "xs:open:my-auto"],
                  ]),
                ],
              ]),
            ],

            [
              "sm",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "sm:open:mx-0"],
                    ["px", "sm:open:mx-px"],
                    [0.5, "sm:open:mx-0.5"],
                    [1, "sm:open:mx-1"],
                    [1.5, "sm:open:mx-1.5"],
                    [2, "sm:open:mx-2"],
                    [2.5, "sm:open:mx-2.5"],
                    [3, "sm:open:mx-3"],
                    [3.5, "sm:open:mx-3.5"],
                    [4, "sm:open:mx-4"],
                    [5, "sm:open:mx-5"],
                    [6, "sm:open:mx-6"],
                    [7, "sm:open:mx-7"],
                    [8, "sm:open:mx-8"],
                    [9, "sm:open:mx-9"],
                    [10, "sm:open:mx-10"],
                    [11, "sm:open:mx-11"],
                    [12, "sm:open:mx-12"],
                    [14, "sm:open:mx-14"],
                    [16, "sm:open:mx-16"],
                    [20, "sm:open:mx-20"],
                    [24, "sm:open:mx-24"],
                    [28, "sm:open:mx-28"],
                    [32, "sm:open:mx-32"],
                    [36, "sm:open:mx-36"],
                    [40, "sm:open:mx-40"],
                    [44, "sm:open:mx-44"],
                    [48, "sm:open:mx-48"],
                    [52, "sm:open:mx-52"],
                    [56, "sm:open:mx-56"],
                    [60, "sm:open:mx-60"],
                    [64, "sm:open:mx-64"],
                    [72, "sm:open:mx-72"],
                    [80, "sm:open:mx-80"],
                    [96, "sm:open:mx-96"],
                    ["auto", "sm:open:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "sm:open:my-0"],
                    ["px", "sm:open:my-px"],
                    [0.5, "sm:open:my-0.5"],
                    [1, "sm:open:my-1"],
                    [1.5, "sm:open:my-1.5"],
                    [2, "sm:open:my-2"],
                    [2.5, "sm:open:my-2.5"],
                    [3, "sm:open:my-3"],
                    [3.5, "sm:open:my-3.5"],
                    [4, "sm:open:my-4"],
                    [5, "sm:open:my-5"],
                    [6, "sm:open:my-6"],
                    [7, "sm:open:my-7"],
                    [8, "sm:open:my-8"],
                    [9, "sm:open:my-9"],
                    [10, "sm:open:my-10"],
                    [11, "sm:open:my-11"],
                    [12, "sm:open:my-12"],
                    [14, "sm:open:my-14"],
                    [16, "sm:open:my-16"],
                    [20, "sm:open:my-20"],
                    [24, "sm:open:my-24"],
                    [28, "sm:open:my-28"],
                    [32, "sm:open:my-32"],
                    [36, "sm:open:my-36"],
                    [40, "sm:open:my-40"],
                    [44, "sm:open:my-44"],
                    [48, "sm:open:my-48"],
                    [52, "sm:open:my-52"],
                    [56, "sm:open:my-56"],
                    [60, "sm:open:my-60"],
                    [64, "sm:open:my-64"],
                    [72, "sm:open:my-72"],
                    [80, "sm:open:my-80"],
                    [96, "sm:open:my-96"],
                    ["auto", "sm:open:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "md",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "md:open:mx-0"],
                    ["px", "md:open:mx-px"],
                    [0.5, "md:open:mx-0.5"],
                    [1, "md:open:mx-1"],
                    [1.5, "md:open:mx-1.5"],
                    [2, "md:open:mx-2"],
                    [2.5, "md:open:mx-2.5"],
                    [3, "md:open:mx-3"],
                    [3.5, "md:open:mx-3.5"],
                    [4, "md:open:mx-4"],
                    [5, "md:open:mx-5"],
                    [6, "md:open:mx-6"],
                    [7, "md:open:mx-7"],
                    [8, "md:open:mx-8"],
                    [9, "md:open:mx-9"],
                    [10, "md:open:mx-10"],
                    [11, "md:open:mx-11"],
                    [12, "md:open:mx-12"],
                    [14, "md:open:mx-14"],
                    [16, "md:open:mx-16"],
                    [20, "md:open:mx-20"],
                    [24, "md:open:mx-24"],
                    [28, "md:open:mx-28"],
                    [32, "md:open:mx-32"],
                    [36, "md:open:mx-36"],
                    [40, "md:open:mx-40"],
                    [44, "md:open:mx-44"],
                    [48, "md:open:mx-48"],
                    [52, "md:open:mx-52"],
                    [56, "md:open:mx-56"],
                    [60, "md:open:mx-60"],
                    [64, "md:open:mx-64"],
                    [72, "md:open:mx-72"],
                    [80, "md:open:mx-80"],
                    [96, "md:open:mx-96"],
                    ["auto", "md:open:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "md:open:my-0"],
                    ["px", "md:open:my-px"],
                    [0.5, "md:open:my-0.5"],
                    [1, "md:open:my-1"],
                    [1.5, "md:open:my-1.5"],
                    [2, "md:open:my-2"],
                    [2.5, "md:open:my-2.5"],
                    [3, "md:open:my-3"],
                    [3.5, "md:open:my-3.5"],
                    [4, "md:open:my-4"],
                    [5, "md:open:my-5"],
                    [6, "md:open:my-6"],
                    [7, "md:open:my-7"],
                    [8, "md:open:my-8"],
                    [9, "md:open:my-9"],
                    [10, "md:open:my-10"],
                    [11, "md:open:my-11"],
                    [12, "md:open:my-12"],
                    [14, "md:open:my-14"],
                    [16, "md:open:my-16"],
                    [20, "md:open:my-20"],
                    [24, "md:open:my-24"],
                    [28, "md:open:my-28"],
                    [32, "md:open:my-32"],
                    [36, "md:open:my-36"],
                    [40, "md:open:my-40"],
                    [44, "md:open:my-44"],
                    [48, "md:open:my-48"],
                    [52, "md:open:my-52"],
                    [56, "md:open:my-56"],
                    [60, "md:open:my-60"],
                    [64, "md:open:my-64"],
                    [72, "md:open:my-72"],
                    [80, "md:open:my-80"],
                    [96, "md:open:my-96"],
                    ["auto", "md:open:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "lg",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "lg:open:mx-0"],
                    ["px", "lg:open:mx-px"],
                    [0.5, "lg:open:mx-0.5"],
                    [1, "lg:open:mx-1"],
                    [1.5, "lg:open:mx-1.5"],
                    [2, "lg:open:mx-2"],
                    [2.5, "lg:open:mx-2.5"],
                    [3, "lg:open:mx-3"],
                    [3.5, "lg:open:mx-3.5"],
                    [4, "lg:open:mx-4"],
                    [5, "lg:open:mx-5"],
                    [6, "lg:open:mx-6"],
                    [7, "lg:open:mx-7"],
                    [8, "lg:open:mx-8"],
                    [9, "lg:open:mx-9"],
                    [10, "lg:open:mx-10"],
                    [11, "lg:open:mx-11"],
                    [12, "lg:open:mx-12"],
                    [14, "lg:open:mx-14"],
                    [16, "lg:open:mx-16"],
                    [20, "lg:open:mx-20"],
                    [24, "lg:open:mx-24"],
                    [28, "lg:open:mx-28"],
                    [32, "lg:open:mx-32"],
                    [36, "lg:open:mx-36"],
                    [40, "lg:open:mx-40"],
                    [44, "lg:open:mx-44"],
                    [48, "lg:open:mx-48"],
                    [52, "lg:open:mx-52"],
                    [56, "lg:open:mx-56"],
                    [60, "lg:open:mx-60"],
                    [64, "lg:open:mx-64"],
                    [72, "lg:open:mx-72"],
                    [80, "lg:open:mx-80"],
                    [96, "lg:open:mx-96"],
                    ["auto", "lg:open:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "lg:open:my-0"],
                    ["px", "lg:open:my-px"],
                    [0.5, "lg:open:my-0.5"],
                    [1, "lg:open:my-1"],
                    [1.5, "lg:open:my-1.5"],
                    [2, "lg:open:my-2"],
                    [2.5, "lg:open:my-2.5"],
                    [3, "lg:open:my-3"],
                    [3.5, "lg:open:my-3.5"],
                    [4, "lg:open:my-4"],
                    [5, "lg:open:my-5"],
                    [6, "lg:open:my-6"],
                    [7, "lg:open:my-7"],
                    [8, "lg:open:my-8"],
                    [9, "lg:open:my-9"],
                    [10, "lg:open:my-10"],
                    [11, "lg:open:my-11"],
                    [12, "lg:open:my-12"],
                    [14, "lg:open:my-14"],
                    [16, "lg:open:my-16"],
                    [20, "lg:open:my-20"],
                    [24, "lg:open:my-24"],
                    [28, "lg:open:my-28"],
                    [32, "lg:open:my-32"],
                    [36, "lg:open:my-36"],
                    [40, "lg:open:my-40"],
                    [44, "lg:open:my-44"],
                    [48, "lg:open:my-48"],
                    [52, "lg:open:my-52"],
                    [56, "lg:open:my-56"],
                    [60, "lg:open:my-60"],
                    [64, "lg:open:my-64"],
                    [72, "lg:open:my-72"],
                    [80, "lg:open:my-80"],
                    [96, "lg:open:my-96"],
                    ["auto", "lg:open:my-auto"],
                  ]),
                ],
              ]),
            ],
            [
              "xl",
              new Map<AxisMapping, Map<MarginSpacing, string>>([
                [
                  "x",
                  new Map<MarginSpacing, string>([
                    [0, "xl:open:mx-0"],
                    ["px", "xl:open:mx-px"],
                    [0.5, "xl:open:mx-0.5"],
                    [1, "xl:open:mx-1"],
                    [1.5, "xl:open:mx-1.5"],
                    [2, "xl:open:mx-2"],
                    [2.5, "xl:open:mx-2.5"],
                    [3, "xl:open:mx-3"],
                    [3.5, "xl:open:mx-3.5"],
                    [4, "xl:open:mx-4"],
                    [5, "xl:open:mx-5"],
                    [6, "xl:open:mx-6"],
                    [7, "xl:open:mx-7"],
                    [8, "xl:open:mx-8"],
                    [9, "xl:open:mx-9"],
                    [10, "xl:open:mx-10"],
                    [11, "xl:open:mx-11"],
                    [12, "xl:open:mx-12"],
                    [14, "xl:open:mx-14"],
                    [16, "xl:open:mx-16"],
                    [20, "xl:open:mx-20"],
                    [24, "xl:open:mx-24"],
                    [28, "xl:open:mx-28"],
                    [32, "xl:open:mx-32"],
                    [36, "xl:open:mx-36"],
                    [40, "xl:open:mx-40"],
                    [44, "xl:open:mx-44"],
                    [48, "xl:open:mx-48"],
                    [52, "xl:open:mx-52"],
                    [56, "xl:open:mx-56"],
                    [60, "xl:open:mx-60"],
                    [64, "xl:open:mx-64"],
                    [72, "xl:open:mx-72"],
                    [80, "xl:open:mx-80"],
                    [96, "xl:open:mx-96"],
                    ["auto", "xl:open:mx-auto"],
                  ]),
                ],
                [
                  "y",
                  new Map<MarginSpacing, string>([
                    [0, "xl:open:my-0"],
                    ["px", "xl:open:my-px"],
                    [0.5, "xl:open:my-0.5"],
                    [1, "xl:open:my-1"],
                    [1.5, "xl:open:my-1.5"],
                    [2, "xl:open:my-2"],
                    [2.5, "xl:open:my-2.5"],
                    [3, "xl:open:my-3"],
                    [3.5, "xl:open:my-3.5"],
                    [4, "xl:open:my-4"],
                    [5, "xl:open:my-5"],
                    [6, "xl:open:my-6"],
                    [7, "xl:open:my-7"],
                    [8, "xl:open:my-8"],
                    [9, "xl:open:my-9"],
                    [10, "xl:open:my-10"],
                    [11, "xl:open:my-11"],
                    [12, "xl:open:my-12"],
                    [14, "xl:open:my-14"],
                    [16, "xl:open:my-16"],
                    [20, "xl:open:my-20"],
                    [24, "xl:open:my-24"],
                    [28, "xl:open:my-28"],
                    [32, "xl:open:my-32"],
                    [36, "xl:open:my-36"],
                    [40, "xl:open:my-40"],
                    [44, "xl:open:my-44"],
                    [48, "xl:open:my-48"],
                    [52, "xl:open:my-52"],
                    [56, "xl:open:my-56"],
                    [60, "xl:open:my-60"],
                    [64, "xl:open:my-64"],
                    [72, "xl:open:my-72"],
                    [80, "xl:open:my-80"],
                    [96, "xl:open:my-96"],
                    ["auto", "xl:open:my-auto"],
                  ]),
                ],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
