import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import {
  AxisMapping,
  Breakpoints,
  CSSSelector,
  MarginSpacing,
  SideMapping,
} from "../../types";
import { DefaultValue } from "../DefaultValue";
import { Breakable } from "../../Entities/Brekable";
import { MarginAxisInsideBreakpoints } from "./MarginAxisInsideBreakpoints";
import { Sideable } from "../../Entities/Sideable";
import { MarginSides } from "./MarginSides";

export class MarginAxis
  extends CSSProperty<Map<AxisMapping, Map<MarginSpacing, string>>>
  implements
    Breakable<Map<Breakpoints, Map<AxisMapping, Map<MarginSpacing, string>>>>,
    Sideable<Map<SideMapping, Map<MarginSpacing, string>>>
{
  private constructor(
    classesMapping: ClassesMapping<
      Map<AxisMapping, Map<MarginSpacing, string>>
    >,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new MarginClassesMapping();
    return new MarginAxis(classesMapping, selector);
  }

  public breakpoints() {
    return MarginAxisInsideBreakpoints.create(this.cssSelector);
  }

  public sides() {
    return MarginSides.create(this.cssSelector);
  }

  public write(axis: AxisMapping, spacing: MarginSpacing) {
    return this.getClassName(axis, spacing);
  }
}

class MarginClassesMapping
  implements ClassesMapping<Map<AxisMapping, Map<MarginSpacing, string>>>
{
  private defaultValue: DefaultValue<AxisMapping, Map<MarginSpacing, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<
      AxisMapping,
      Map<MarginSpacing, string>
    >("x", new Map<MarginSpacing, string>([[0, "mx-0"]]));
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<AxisMapping, Map<MarginSpacing, string>>>([
        [
          "active",
          new Map<AxisMapping, Map<MarginSpacing, string>>([
            [
              "x",
              new Map<MarginSpacing, string>([
                [0, "active:mx-0"],
                ["px", "active:mx-px"],
                [0.5, "active:mx-0.5"],
                [1, "active:mx-1"],
                [1.5, "active:mx-1.5"],
                [2, "active:mx-2"],
                [2.5, "active:mx-2.5"],
                [3, "active:mx-3"],
                [3.5, "active:mx-3.5"],
                [4, "active:mx-4"],
                [5, "active:mx-5"],
                [6, "active:mx-6"],
                [7, "active:mx-7"],
                [8, "active:mx-8"],
                [9, "active:mx-9"],
                [10, "active:mx-10"],
                [11, "active:mx-11"],
                [12, "active:mx-12"],
                [14, "active:mx-14"],
                [16, "active:mx-16"],
                [20, "active:mx-20"],
                [24, "active:mx-24"],
                [28, "active:mx-28"],
                [32, "active:mx-32"],
                [36, "active:mx-36"],
                [40, "active:mx-40"],
                [44, "active:mx-44"],
                [48, "active:mx-48"],
                [52, "active:mx-52"],
                [56, "active:mx-56"],
                [60, "active:mx-60"],
                [64, "active:mx-64"],
                [72, "active:mx-72"],
                [80, "active:mx-80"],
                [96, "active:mx-96"],
                ["auto", "active:mx-auto"],
              ]),
            ],
            [
              "y",
              new Map<MarginSpacing, string>([
                [0, "active:my-0"],
                ["px", "active:my-px"],
                [0.5, "active:my-0.5"],
                [1, "active:my-1"],
                [1.5, "active:my-1.5"],
                [2, "active:my-2"],
                [2.5, "active:my-2.5"],
                [3, "active:my-3"],
                [3.5, "active:my-3.5"],
                [4, "active:my-4"],
                [5, "active:my-5"],
                [6, "active:my-6"],
                [7, "active:my-7"],
                [8, "active:my-8"],
                [9, "active:my-9"],
                [10, "active:my-10"],
                [11, "active:my-11"],
                [12, "active:my-12"],
                [14, "active:my-14"],
                [16, "active:my-16"],
                [20, "active:my-20"],
                [24, "active:my-24"],
                [28, "active:my-28"],
                [32, "active:my-32"],
                [36, "active:my-36"],
                [40, "active:my-40"],
                [44, "active:my-44"],
                [48, "active:my-48"],
                [52, "active:my-52"],
                [56, "active:my-56"],
                [60, "active:my-60"],
                [64, "active:my-64"],
                [72, "active:my-72"],
                [80, "active:my-80"],
                [96, "active:my-96"],
                ["auto", "active:my-auto"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<AxisMapping, Map<MarginSpacing, string>>([
            [
              "x",
              new Map<MarginSpacing, string>([
                [0, "disabled:mx-0"],
                ["px", "disabled:mx-px"],
                [0.5, "disabled:mx-0.5"],
                [1, "disabled:mx-1"],
                [1.5, "disabled:mx-1.5"],
                [2, "disabled:mx-2"],
                [2.5, "disabled:mx-2.5"],
                [3, "disabled:mx-3"],
                [3.5, "disabled:mx-3.5"],
                [4, "disabled:mx-4"],
                [5, "disabled:mx-5"],
                [6, "disabled:mx-6"],
                [7, "disabled:mx-7"],
                [8, "disabled:mx-8"],
                [9, "disabled:mx-9"],
                [10, "disabled:mx-10"],
                [11, "disabled:mx-11"],
                [12, "disabled:mx-12"],
                [14, "disabled:mx-14"],
                [16, "disabled:mx-16"],
                [20, "disabled:mx-20"],
                [24, "disabled:mx-24"],
                [28, "disabled:mx-28"],
                [32, "disabled:mx-32"],
                [36, "disabled:mx-36"],
                [40, "disabled:mx-40"],
                [44, "disabled:mx-44"],
                [48, "disabled:mx-48"],
                [52, "disabled:mx-52"],
                [56, "disabled:mx-56"],
                [60, "disabled:mx-60"],
                [64, "disabled:mx-64"],
                [72, "disabled:mx-72"],
                [80, "disabled:mx-80"],
                [96, "disabled:mx-96"],
                ["auto", "disabled:mx-auto"],
              ]),
            ],
            [
              "y",
              new Map<MarginSpacing, string>([
                [0, "disabled:my-0"],
                ["px", "disabled:my-px"],
                [0.5, "disabled:my-0.5"],
                [1, "disabled:my-1"],
                [1.5, "disabled:my-1.5"],
                [2, "disabled:my-2"],
                [2.5, "disabled:my-2.5"],
                [3, "disabled:my-3"],
                [3.5, "disabled:my-3.5"],
                [4, "disabled:my-4"],
                [5, "disabled:my-5"],
                [6, "disabled:my-6"],
                [7, "disabled:my-7"],
                [8, "disabled:my-8"],
                [9, "disabled:my-9"],
                [10, "disabled:my-10"],
                [11, "disabled:my-11"],
                [12, "disabled:my-12"],
                [14, "disabled:my-14"],
                [16, "disabled:my-16"],
                [20, "disabled:my-20"],
                [24, "disabled:my-24"],
                [28, "disabled:my-28"],
                [32, "disabled:my-32"],
                [36, "disabled:my-36"],
                [40, "disabled:my-40"],
                [44, "disabled:my-44"],
                [48, "disabled:my-48"],
                [52, "disabled:my-52"],
                [56, "disabled:my-56"],
                [60, "disabled:my-60"],
                [64, "disabled:my-64"],
                [72, "disabled:my-72"],
                [80, "disabled:my-80"],
                [96, "disabled:my-96"],
                ["auto", "disabled:my-auto"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<AxisMapping, Map<MarginSpacing, string>>([
            [
              "x",
              new Map<MarginSpacing, string>([
                [0, "hover:mx-0"],
                ["px", "hover:mx-px"],
                [0.5, "hover:mx-0.5"],
                [1, "hover:mx-1"],
                [1.5, "hover:mx-1.5"],
                [2, "hover:mx-2"],
                [2.5, "hover:mx-2.5"],
                [3, "hover:mx-3"],
                [3.5, "hover:mx-3.5"],
                [4, "hover:mx-4"],
                [5, "hover:mx-5"],
                [6, "hover:mx-6"],
                [7, "hover:mx-7"],
                [8, "hover:mx-8"],
                [9, "hover:mx-9"],
                [10, "hover:mx-10"],
                [11, "hover:mx-11"],
                [12, "hover:mx-12"],
                [14, "hover:mx-14"],
                [16, "hover:mx-16"],
                [20, "hover:mx-20"],
                [24, "hover:mx-24"],
                [28, "hover:mx-28"],
                [32, "hover:mx-32"],
                [36, "hover:mx-36"],
                [40, "hover:mx-40"],
                [44, "hover:mx-44"],
                [48, "hover:mx-48"],
                [52, "hover:mx-52"],
                [56, "hover:mx-56"],
                [60, "hover:mx-60"],
                [64, "hover:mx-64"],
                [72, "hover:mx-72"],
                [80, "hover:mx-80"],
                [96, "hover:mx-96"],
                ["auto", "hover:mx-auto"],
              ]),
            ],
            [
              "y",
              new Map<MarginSpacing, string>([
                [0, "hover:my-0"],
                ["px", "hover:my-px"],
                [0.5, "hover:my-0.5"],
                [1, "hover:my-1"],
                [1.5, "hover:my-1.5"],
                [2, "hover:my-2"],
                [2.5, "hover:my-2.5"],
                [3, "hover:my-3"],
                [3.5, "hover:my-3.5"],
                [4, "hover:my-4"],
                [5, "hover:my-5"],
                [6, "hover:my-6"],
                [7, "hover:my-7"],
                [8, "hover:my-8"],
                [9, "hover:my-9"],
                [10, "hover:my-10"],
                [11, "hover:my-11"],
                [12, "hover:my-12"],
                [14, "hover:my-14"],
                [16, "hover:my-16"],
                [20, "hover:my-20"],
                [24, "hover:my-24"],
                [28, "hover:my-28"],
                [32, "hover:my-32"],
                [36, "hover:my-36"],
                [40, "hover:my-40"],
                [44, "hover:my-44"],
                [48, "hover:my-48"],
                [52, "hover:my-52"],
                [56, "hover:my-56"],
                [60, "hover:my-60"],
                [64, "hover:my-64"],
                [72, "hover:my-72"],
                [80, "hover:my-80"],
                [96, "hover:my-96"],
                ["auto", "hover:my-auto"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<AxisMapping, Map<MarginSpacing, string>>([
            [
              "x",
              new Map<MarginSpacing, string>([
                [0, "mx-0"],
                ["px", "mx-px"],
                [0.5, "mx-0.5"],
                [1, "mx-1"],
                [1.5, "mx-1.5"],
                [2, "mx-2"],
                [2.5, "mx-2.5"],
                [3, "mx-3"],
                [3.5, "mx-3.5"],
                [4, "mx-4"],
                [5, "mx-5"],
                [6, "mx-6"],
                [7, "mx-7"],
                [8, "mx-8"],
                [9, "mx-9"],
                [10, "mx-10"],
                [11, "mx-11"],
                [12, "mx-12"],
                [14, "mx-14"],
                [16, "mx-16"],
                [20, "mx-20"],
                [24, "mx-24"],
                [28, "mx-28"],
                [32, "mx-32"],
                [36, "mx-36"],
                [40, "mx-40"],
                [44, "mx-44"],
                [48, "mx-48"],
                [52, "mx-52"],
                [56, "mx-56"],
                [60, "mx-60"],
                [64, "mx-64"],
                [72, "mx-72"],
                [80, "mx-80"],
                [96, "mx-96"],
                ["auto", "mx-auto"],
              ]),
            ],
            [
              "y",
              new Map<MarginSpacing, string>([
                [0, "my-0"],
                ["px", "my-px"],
                [0.5, "my-0.5"],
                [1, "my-1"],
                [1.5, "my-1.5"],
                [2, "my-2"],
                [2.5, "my-2.5"],
                [3, "my-3"],
                [3.5, "my-3.5"],
                [4, "my-4"],
                [5, "my-5"],
                [6, "my-6"],
                [7, "my-7"],
                [8, "my-8"],
                [9, "my-9"],
                [10, "my-10"],
                [11, "my-11"],
                [12, "my-12"],
                [14, "my-14"],
                [16, "my-16"],
                [20, "my-20"],
                [24, "my-24"],
                [28, "my-28"],
                [32, "my-32"],
                [36, "my-36"],
                [40, "my-40"],
                [44, "my-44"],
                [48, "my-48"],
                [52, "my-52"],
                [56, "my-56"],
                [60, "my-60"],
                [64, "my-64"],
                [72, "my-72"],
                [80, "my-80"],
                [96, "my-96"],
                ["auto", "my-auto"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<AxisMapping, Map<MarginSpacing, string>>([
            [
              "x",
              new Map<MarginSpacing, string>([
                [0, "openmx-0"],
                ["px", "openmx-px"],
                [0.5, "openmx-0.5"],
                [1, "openmx-1"],
                [1.5, "openmx-1.5"],
                [2, "openmx-2"],
                [2.5, "openmx-2.5"],
                [3, "openmx-3"],
                [3.5, "openmx-3.5"],
                [4, "openmx-4"],
                [5, "openmx-5"],
                [6, "openmx-6"],
                [7, "openmx-7"],
                [8, "openmx-8"],
                [9, "openmx-9"],
                [10, "openmx-10"],
                [11, "openmx-11"],
                [12, "openmx-12"],
                [14, "openmx-14"],
                [16, "openmx-16"],
                [20, "openmx-20"],
                [24, "openmx-24"],
                [28, "openmx-28"],
                [32, "openmx-32"],
                [36, "openmx-36"],
                [40, "openmx-40"],
                [44, "openmx-44"],
                [48, "openmx-48"],
                [52, "openmx-52"],
                [56, "openmx-56"],
                [60, "openmx-60"],
                [64, "openmx-64"],
                [72, "openmx-72"],
                [80, "openmx-80"],
                [96, "openmx-96"],
                ["auto", "openmx-auto"],
              ]),
            ],
            [
              "y",
              new Map<MarginSpacing, string>([
                [0, "openmy-0"],
                ["px", "openmy-px"],
                [0.5, "openmy-0.5"],
                [1, "openmy-1"],
                [1.5, "openmy-1.5"],
                [2, "openmy-2"],
                [2.5, "openmy-2.5"],
                [3, "openmy-3"],
                [3.5, "openmy-3.5"],
                [4, "openmy-4"],
                [5, "openmy-5"],
                [6, "openmy-6"],
                [7, "openmy-7"],
                [8, "openmy-8"],
                [9, "openmy-9"],
                [10, "openmy-10"],
                [11, "openmy-11"],
                [12, "openmy-12"],
                [14, "openmy-14"],
                [16, "openmy-16"],
                [20, "openmy-20"],
                [24, "openmy-24"],
                [28, "openmy-28"],
                [32, "openmy-32"],
                [36, "openmy-36"],
                [40, "openmy-40"],
                [44, "openmy-44"],
                [48, "openmy-48"],
                [52, "openmy-52"],
                [56, "openmy-56"],
                [60, "openmy-60"],
                [64, "openmy-64"],
                [72, "openmy-72"],
                [80, "openmy-80"],
                [96, "openmy-96"],
                ["auto", "openmy-auto"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
