import { ClassesMapping } from "../../Entities/ClassMap";
import { CSSProperty } from "../../Entities/CSSProperty";
import { Breakpoints, CSSSelector, FlexDisplay } from "../../types";
import { DefaultValue } from "../DefaultValue";

export class DisplayBreakpoints extends CSSProperty<
  Map<Breakpoints, Map<FlexDisplay, string>>
> {
  private constructor(
    classesMapping: ClassesMapping<Map<Breakpoints, Map<FlexDisplay, string>>>,
    cssSelector: CSSSelector
  ) {
    super(classesMapping, cssSelector);
  }

  static create(selector: CSSSelector = "none") {
    const classesMapping = new DisplayMapping();
    return new DisplayBreakpoints(classesMapping, selector);
  }

  public write(breakpoint: Breakpoints, display: FlexDisplay) {
    return this.getClassName(breakpoint, display);
  }
}

class DisplayMapping
  implements ClassesMapping<Map<Breakpoints, Map<FlexDisplay, string>>>
{
  private defaultValue: DefaultValue<Breakpoints, Map<FlexDisplay, string>>;

  constructor() {
    this.defaultValue = new DefaultValue<Breakpoints, Map<FlexDisplay, string>>(
      "xs",
      new Map<FlexDisplay, string>([["block", "xs:block"]])
    );
  }

  get(selector: CSSSelector) {
    return (
      new Map<CSSSelector, Map<Breakpoints, Map<FlexDisplay, string>>>([
        [
          "active",
          new Map<Breakpoints, Map<FlexDisplay, string>>([
            [
              "xs",
              new Map<FlexDisplay, string>([
                ["block", "xs:active:block"],
                ["contents", "xs:active:contents"],
                ["flex", "xs:active:flex"],
                ["flow-root", "xs:active:flow-root"],
                ["grid", "xs:active:grid"],
                ["hidden", "xs:active:hidden"],
                ["inline", "xs:active:inline"],
                ["inline-block", "xs:active:inline-block"],
                ["inline-flex", "xs:active:inline-flex"],
                ["inline-grid", "xs:active:inline-grid"],
                ["inline-table", "xs:active:inline-table"],
                ["list-item", "xs:active:list-item"],
                ["table", "xs:active:table"],
                ["table-caption", "xs:active:table-caption"],
                ["table-cell", "xs:active:table-cell"],
                ["table-column", "xs:active:table-column"],
                ["table-column-group", "xs:active:table-column-group"],
                ["table-footer-group", "xs:active:table-footer-group"],
                ["table-header-group", "xs:active:table-header-group"],
                ["table-row", "xs:active:table-row"],
                ["table-row-group", "xs:active:table-row-group"],
              ]),
            ],
            [
              "sm",
              new Map<FlexDisplay, string>([
                ["block", "sm:active:block"],
                ["contents", "sm:active:contents"],
                ["flex", "sm:active:flex"],
                ["flow-root", "sm:active:flow-root"],
                ["grid", "sm:active:grid"],
                ["hidden", "sm:active:hidden"],
                ["inline", "sm:active:inline"],
                ["inline-block", "sm:active:inline-block"],
                ["inline-flex", "sm:active:inline-flex"],
                ["inline-grid", "sm:active:inline-grid"],
                ["inline-table", "sm:active:inline-table"],
                ["list-item", "sm:active:list-item"],
                ["table", "sm:active:table"],
                ["table-caption", "sm:active:table-caption"],
                ["table-cell", "sm:active:table-cell"],
                ["table-column", "sm:active:table-column"],
                ["table-column-group", "sm:active:table-column-group"],
                ["table-footer-group", "sm:active:table-footer-group"],
                ["table-header-group", "sm:active:table-header-group"],
                ["table-row", "sm:active:table-row"],
                ["table-row-group", "sm:active:table-row-group"],
              ]),
            ],
            [
              "md",
              new Map<FlexDisplay, string>([
                ["block", "md:active:block"],
                ["contents", "md:active:contents"],
                ["flex", "md:active:flex"],
                ["flow-root", "md:active:flow-root"],
                ["grid", "md:active:grid"],
                ["hidden", "md:active:hidden"],
                ["inline", "md:active:inline"],
                ["inline-block", "md:active:inline-block"],
                ["inline-flex", "md:active:inline-flex"],
                ["inline-grid", "md:active:inline-grid"],
                ["inline-table", "md:active:inline-table"],
                ["list-item", "md:active:list-item"],
                ["table", "md:active:table"],
                ["table-caption", "md:active:table-caption"],
                ["table-cell", "md:active:table-cell"],
                ["table-column", "md:active:table-column"],
                ["table-column-group", "md:active:table-column-group"],
                ["table-footer-group", "md:active:table-footer-group"],
                ["table-header-group", "md:active:table-header-group"],
                ["table-row", "md:active:table-row"],
                ["table-row-group", "md:active:table-row-group"],
              ]),
            ],
            [
              "lg",
              new Map<FlexDisplay, string>([
                ["block", "lg:active:block"],
                ["contents", "lg:active:contents"],
                ["flex", "lg:active:flex"],
                ["flow-root", "lg:active:flow-root"],
                ["grid", "lg:active:grid"],
                ["hidden", "lg:active:hidden"],
                ["inline", "lg:active:inline"],
                ["inline-block", "lg:active:inline-block"],
                ["inline-flex", "lg:active:inline-flex"],
                ["inline-grid", "lg:active:inline-grid"],
                ["inline-table", "lg:active:inline-table"],
                ["list-item", "lg:active:list-item"],
                ["table", "lg:active:table"],
                ["table-caption", "lg:active:table-caption"],
                ["table-cell", "lg:active:table-cell"],
                ["table-column", "lg:active:table-column"],
                ["table-column-group", "lg:active:table-column-group"],
                ["table-footer-group", "lg:active:table-footer-group"],
                ["table-header-group", "lg:active:table-header-group"],
                ["table-row", "lg:active:table-row"],
                ["table-row-group", "lg:active:table-row-group"],
              ]),
            ],
            [
              "xl",
              new Map<FlexDisplay, string>([
                ["block", "xl:active:block"],
                ["contents", "xl:active:contents"],
                ["flex", "xl:active:flex"],
                ["flow-root", "xl:active:flow-root"],
                ["grid", "xl:active:grid"],
                ["hidden", "xl:active:hidden"],
                ["inline", "xl:active:inline"],
                ["inline-block", "xl:active:inline-block"],
                ["inline-flex", "xl:active:inline-flex"],
                ["inline-grid", "xl:active:inline-grid"],
                ["inline-table", "xl:active:inline-table"],
                ["list-item", "xl:active:list-item"],
                ["table", "xl:active:table"],
                ["table-caption", "xl:active:table-caption"],
                ["table-cell", "xl:active:table-cell"],
                ["table-column", "xl:active:table-column"],
                ["table-column-group", "xl:active:table-column-group"],
                ["table-footer-group", "xl:active:table-footer-group"],
                ["table-header-group", "xl:active:table-header-group"],
                ["table-row", "xl:active:table-row"],
                ["table-row-group", "xl:active:table-row-group"],
              ]),
            ],
          ]),
        ],
        [
          "disabled",
          new Map<Breakpoints, Map<FlexDisplay, string>>([
            [
              "xs",
              new Map<FlexDisplay, string>([
                ["block", "xs:disabled:block"],
                ["contents", "xs:disabled:contents"],
                ["flex", "xs:disabled:flex"],
                ["flow-root", "xs:disabled:flow-root"],
                ["grid", "xs:disabled:grid"],
                ["hidden", "xs:disabled:hidden"],
                ["inline", "xs:disabled:inline"],
                ["inline-block", "xs:disabled:inline-block"],
                ["inline-flex", "xs:disabled:inline-flex"],
                ["inline-grid", "xs:disabled:inline-grid"],
                ["inline-table", "xs:disabled:inline-table"],
                ["list-item", "xs:disabled:list-item"],
                ["table", "xs:disabled:table"],
                ["table-caption", "xs:disabled:table-caption"],
                ["table-cell", "xs:disabled:table-cell"],
                ["table-column", "xs:disabled:table-column"],
                ["table-column-group", "xs:disabled:table-column-group"],
                ["table-footer-group", "xs:disabled:table-footer-group"],
                ["table-header-group", "xs:disabled:table-header-group"],
                ["table-row", "xs:disabled:table-row"],
                ["table-row-group", "xs:disabled:table-row-group"],
              ]),
            ],
            [
              "sm",
              new Map<FlexDisplay, string>([
                ["block", "sm:disabled:block"],
                ["contents", "sm:disabled:contents"],
                ["flex", "sm:disabled:flex"],
                ["flow-root", "sm:disabled:flow-root"],
                ["grid", "sm:disabled:grid"],
                ["hidden", "sm:disabled:hidden"],
                ["inline", "sm:disabled:inline"],
                ["inline-block", "sm:disabled:inline-block"],
                ["inline-flex", "sm:disabled:inline-flex"],
                ["inline-grid", "sm:disabled:inline-grid"],
                ["inline-table", "sm:disabled:inline-table"],
                ["list-item", "sm:disabled:list-item"],
                ["table", "sm:disabled:table"],
                ["table-caption", "sm:disabled:table-caption"],
                ["table-cell", "sm:disabled:table-cell"],
                ["table-column", "sm:disabled:table-column"],
                ["table-column-group", "sm:disabled:table-column-group"],
                ["table-footer-group", "sm:disabled:table-footer-group"],
                ["table-header-group", "sm:disabled:table-header-group"],
                ["table-row", "sm:disabled:table-row"],
                ["table-row-group", "sm:disabled:table-row-group"],
              ]),
            ],
            [
              "md",
              new Map<FlexDisplay, string>([
                ["block", "md:disabled:block"],
                ["contents", "md:disabled:contents"],
                ["flex", "md:disabled:flex"],
                ["flow-root", "md:disabled:flow-root"],
                ["grid", "md:disabled:grid"],
                ["hidden", "md:disabled:hidden"],
                ["inline", "md:disabled:inline"],
                ["inline-block", "md:disabled:inline-block"],
                ["inline-flex", "md:disabled:inline-flex"],
                ["inline-grid", "md:disabled:inline-grid"],
                ["inline-table", "md:disabled:inline-table"],
                ["list-item", "md:disabled:list-item"],
                ["table", "md:disabled:table"],
                ["table-caption", "md:disabled:table-caption"],
                ["table-cell", "md:disabled:table-cell"],
                ["table-column", "md:disabled:table-column"],
                ["table-column-group", "md:disabled:table-column-group"],
                ["table-footer-group", "md:disabled:table-footer-group"],
                ["table-header-group", "md:disabled:table-header-group"],
                ["table-row", "md:disabled:table-row"],
                ["table-row-group", "md:disabled:table-row-group"],
              ]),
            ],
            [
              "lg",
              new Map<FlexDisplay, string>([
                ["block", "lg:disabled:block"],
                ["contents", "lg:disabled:contents"],
                ["flex", "lg:disabled:flex"],
                ["flow-root", "lg:disabled:flow-root"],
                ["grid", "lg:disabled:grid"],
                ["hidden", "lg:disabled:hidden"],
                ["inline", "lg:disabled:inline"],
                ["inline-block", "lg:disabled:inline-block"],
                ["inline-flex", "lg:disabled:inline-flex"],
                ["inline-grid", "lg:disabled:inline-grid"],
                ["inline-table", "lg:disabled:inline-table"],
                ["list-item", "lg:disabled:list-item"],
                ["table", "lg:disabled:table"],
                ["table-caption", "lg:disabled:table-caption"],
                ["table-cell", "lg:disabled:table-cell"],
                ["table-column", "lg:disabled:table-column"],
                ["table-column-group", "lg:disabled:table-column-group"],
                ["table-footer-group", "lg:disabled:table-footer-group"],
                ["table-header-group", "lg:disabled:table-header-group"],
                ["table-row", "lg:disabled:table-row"],
                ["table-row-group", "lg:disabled:table-row-group"],
              ]),
            ],
            [
              "xl",
              new Map<FlexDisplay, string>([
                ["block", "xl:disabled:block"],
                ["contents", "xl:disabled:contents"],
                ["flex", "xl:disabled:flex"],
                ["flow-root", "xl:disabled:flow-root"],
                ["grid", "xl:disabled:grid"],
                ["hidden", "xl:disabled:hidden"],
                ["inline", "xl:disabled:inline"],
                ["inline-block", "xl:disabled:inline-block"],
                ["inline-flex", "xl:disabled:inline-flex"],
                ["inline-grid", "xl:disabled:inline-grid"],
                ["inline-table", "xl:disabled:inline-table"],
                ["list-item", "xl:disabled:list-item"],
                ["table", "xl:disabled:table"],
                ["table-caption", "xl:disabled:table-caption"],
                ["table-cell", "xl:disabled:table-cell"],
                ["table-column", "xl:disabled:table-column"],
                ["table-column-group", "xl:disabled:table-column-group"],
                ["table-footer-group", "xl:disabled:table-footer-group"],
                ["table-header-group", "xl:disabled:table-header-group"],
                ["table-row", "xl:disabled:table-row"],
                ["table-row-group", "xl:disabled:table-row-group"],
              ]),
            ],
          ]),
        ],
        [
          "hover",
          new Map<Breakpoints, Map<FlexDisplay, string>>([
            [
              "xs",
              new Map<FlexDisplay, string>([
                ["block", "xs:hover:block"],
                ["contents", "xs:hover:contents"],
                ["flex", "xs:hover:flex"],
                ["flow-root", "xs:hover:flow-root"],
                ["grid", "xs:hover:grid"],
                ["hidden", "xs:hover:hidden"],
                ["inline", "xs:hover:inline"],
                ["inline-block", "xs:hover:inline-block"],
                ["inline-flex", "xs:hover:inline-flex"],
                ["inline-grid", "xs:hover:inline-grid"],
                ["inline-table", "xs:hover:inline-table"],
                ["list-item", "xs:hover:list-item"],
                ["table", "xs:hover:table"],
                ["table-caption", "xs:hover:table-caption"],
                ["table-cell", "xs:hover:table-cell"],
                ["table-column", "xs:hover:table-column"],
                ["table-column-group", "xs:hover:table-column-group"],
                ["table-footer-group", "xs:hover:table-footer-group"],
                ["table-header-group", "xs:hover:table-header-group"],
                ["table-row", "xs:hover:table-row"],
                ["table-row-group", "xs:hover:table-row-group"],
              ]),
            ],
            [
              "sm",
              new Map<FlexDisplay, string>([
                ["block", "sm:hover:block"],
                ["contents", "sm:hover:contents"],
                ["flex", "sm:hover:flex"],
                ["flow-root", "sm:hover:flow-root"],
                ["grid", "sm:hover:grid"],
                ["hidden", "sm:hover:hidden"],
                ["inline", "sm:hover:inline"],
                ["inline-block", "sm:hover:inline-block"],
                ["inline-flex", "sm:hover:inline-flex"],
                ["inline-grid", "sm:hover:inline-grid"],
                ["inline-table", "sm:hover:inline-table"],
                ["list-item", "sm:hover:list-item"],
                ["table", "sm:hover:table"],
                ["table-caption", "sm:hover:table-caption"],
                ["table-cell", "sm:hover:table-cell"],
                ["table-column", "sm:hover:table-column"],
                ["table-column-group", "sm:hover:table-column-group"],
                ["table-footer-group", "sm:hover:table-footer-group"],
                ["table-header-group", "sm:hover:table-header-group"],
                ["table-row", "sm:hover:table-row"],
                ["table-row-group", "sm:hover:table-row-group"],
              ]),
            ],
            [
              "md",
              new Map<FlexDisplay, string>([
                ["block", "md:hover:block"],
                ["contents", "md:hover:contents"],
                ["flex", "md:hover:flex"],
                ["flow-root", "md:hover:flow-root"],
                ["grid", "md:hover:grid"],
                ["hidden", "md:hover:hidden"],
                ["inline", "md:hover:inline"],
                ["inline-block", "md:hover:inline-block"],
                ["inline-flex", "md:hover:inline-flex"],
                ["inline-grid", "md:hover:inline-grid"],
                ["inline-table", "md:hover:inline-table"],
                ["list-item", "md:hover:list-item"],
                ["table", "md:hover:table"],
                ["table-caption", "md:hover:table-caption"],
                ["table-cell", "md:hover:table-cell"],
                ["table-column", "md:hover:table-column"],
                ["table-column-group", "md:hover:table-column-group"],
                ["table-footer-group", "md:hover:table-footer-group"],
                ["table-header-group", "md:hover:table-header-group"],
                ["table-row", "md:hover:table-row"],
                ["table-row-group", "md:hover:table-row-group"],
              ]),
            ],
            [
              "lg",
              new Map<FlexDisplay, string>([
                ["block", "lg:hover:block"],
                ["contents", "lg:hover:contents"],
                ["flex", "lg:hover:flex"],
                ["flow-root", "lg:hover:flow-root"],
                ["grid", "lg:hover:grid"],
                ["hidden", "lg:hover:hidden"],
                ["inline", "lg:hover:inline"],
                ["inline-block", "lg:hover:inline-block"],
                ["inline-flex", "lg:hover:inline-flex"],
                ["inline-grid", "lg:hover:inline-grid"],
                ["inline-table", "lg:hover:inline-table"],
                ["list-item", "lg:hover:list-item"],
                ["table", "lg:hover:table"],
                ["table-caption", "lg:hover:table-caption"],
                ["table-cell", "lg:hover:table-cell"],
                ["table-column", "lg:hover:table-column"],
                ["table-column-group", "lg:hover:table-column-group"],
                ["table-footer-group", "lg:hover:table-footer-group"],
                ["table-header-group", "lg:hover:table-header-group"],
                ["table-row", "lg:hover:table-row"],
                ["table-row-group", "lg:hover:table-row-group"],
              ]),
            ],
            [
              "xl",
              new Map<FlexDisplay, string>([
                ["block", "xl:hover:block"],
                ["contents", "xl:hover:contents"],
                ["flex", "xl:hover:flex"],
                ["flow-root", "xl:hover:flow-root"],
                ["grid", "xl:hover:grid"],
                ["hidden", "xl:hover:hidden"],
                ["inline", "xl:hover:inline"],
                ["inline-block", "xl:hover:inline-block"],
                ["inline-flex", "xl:hover:inline-flex"],
                ["inline-grid", "xl:hover:inline-grid"],
                ["inline-table", "xl:hover:inline-table"],
                ["list-item", "xl:hover:list-item"],
                ["table", "xl:hover:table"],
                ["table-caption", "xl:hover:table-caption"],
                ["table-cell", "xl:hover:table-cell"],
                ["table-column", "xl:hover:table-column"],
                ["table-column-group", "xl:hover:table-column-group"],
                ["table-footer-group", "xl:hover:table-footer-group"],
                ["table-header-group", "xl:hover:table-header-group"],
                ["table-row", "xl:hover:table-row"],
                ["table-row-group", "xl:hover:table-row-group"],
              ]),
            ],
          ]),
        ],
        [
          "none",
          new Map<Breakpoints, Map<FlexDisplay, string>>([
            [
              "xs",
              new Map<FlexDisplay, string>([
                ["block", "xs:block"],
                ["contents", "xs:contents"],
                ["flex", "xs:flex"],
                ["flow-root", "xs:flow-root"],
                ["grid", "xs:grid"],
                ["hidden", "xs:hidden"],
                ["inline", "xs:inline"],
                ["inline-block", "xs:inline-block"],
                ["inline-flex", "xs:inline-flex"],
                ["inline-grid", "xs:inline-grid"],
                ["inline-table", "xs:inline-table"],
                ["list-item", "xs:list-item"],
                ["table", "xs:table"],
                ["table-caption", "xs:table-caption"],
                ["table-cell", "xs:table-cell"],
                ["table-column", "xs:table-column"],
                ["table-column-group", "xs:table-column-group"],
                ["table-footer-group", "xs:table-footer-group"],
                ["table-header-group", "xs:table-header-group"],
                ["table-row", "xs:table-row"],
                ["table-row-group", "xs:table-row-group"],
              ]),
            ],
            [
              "sm",
              new Map<FlexDisplay, string>([
                ["block", "sm:block"],
                ["contents", "sm:contents"],
                ["flex", "sm:flex"],
                ["flow-root", "sm:flow-root"],
                ["grid", "sm:grid"],
                ["hidden", "sm:hidden"],
                ["inline", "sm:inline"],
                ["inline-block", "sm:inline-block"],
                ["inline-flex", "sm:inline-flex"],
                ["inline-grid", "sm:inline-grid"],
                ["inline-table", "sm:inline-table"],
                ["list-item", "sm:list-item"],
                ["table", "sm:table"],
                ["table-caption", "sm:table-caption"],
                ["table-cell", "sm:table-cell"],
                ["table-column", "sm:table-column"],
                ["table-column-group", "sm:table-column-group"],
                ["table-footer-group", "sm:table-footer-group"],
                ["table-header-group", "sm:table-header-group"],
                ["table-row", "sm:table-row"],
                ["table-row-group", "sm:table-row-group"],
              ]),
            ],
            [
              "md",
              new Map<FlexDisplay, string>([
                ["block", "md:block"],
                ["contents", "md:contents"],
                ["flex", "md:flex"],
                ["flow-root", "md:flow-root"],
                ["grid", "md:grid"],
                ["hidden", "md:hidden"],
                ["inline", "md:inline"],
                ["inline-block", "md:inline-block"],
                ["inline-flex", "md:inline-flex"],
                ["inline-grid", "md:inline-grid"],
                ["inline-table", "md:inline-table"],
                ["list-item", "md:list-item"],
                ["table", "md:table"],
                ["table-caption", "md:table-caption"],
                ["table-cell", "md:table-cell"],
                ["table-column", "md:table-column"],
                ["table-column-group", "md:table-column-group"],
                ["table-footer-group", "md:table-footer-group"],
                ["table-header-group", "md:table-header-group"],
                ["table-row", "md:table-row"],
                ["table-row-group", "md:table-row-group"],
              ]),
            ],
            [
              "lg",
              new Map<FlexDisplay, string>([
                ["block", "lg:block"],
                ["contents", "lg:contents"],
                ["flex", "lg:flex"],
                ["flow-root", "lg:flow-root"],
                ["grid", "lg:grid"],
                ["hidden", "lg:hidden"],
                ["inline", "lg:inline"],
                ["inline-block", "lg:inline-block"],
                ["inline-flex", "lg:inline-flex"],
                ["inline-grid", "lg:inline-grid"],
                ["inline-table", "lg:inline-table"],
                ["list-item", "lg:list-item"],
                ["table", "lg:table"],
                ["table-caption", "lg:table-caption"],
                ["table-cell", "lg:table-cell"],
                ["table-column", "lg:table-column"],
                ["table-column-group", "lg:table-column-group"],
                ["table-footer-group", "lg:table-footer-group"],
                ["table-header-group", "lg:table-header-group"],
                ["table-row", "lg:table-row"],
                ["table-row-group", "lg:table-row-group"],
              ]),
            ],
            [
              "xl",
              new Map<FlexDisplay, string>([
                ["block", "xl:block"],
                ["contents", "xl:contents"],
                ["flex", "xl:flex"],
                ["flow-root", "xl:flow-root"],
                ["grid", "xl:grid"],
                ["hidden", "xl:hidden"],
                ["inline", "xl:inline"],
                ["inline-block", "xl:inline-block"],
                ["inline-flex", "xl:inline-flex"],
                ["inline-grid", "xl:inline-grid"],
                ["inline-table", "xl:inline-table"],
                ["list-item", "xl:list-item"],
                ["table", "xl:table"],
                ["table-caption", "xl:table-caption"],
                ["table-cell", "xl:table-cell"],
                ["table-column", "xl:table-column"],
                ["table-column-group", "xl:table-column-group"],
                ["table-footer-group", "xl:table-footer-group"],
                ["table-header-group", "xl:table-header-group"],
                ["table-row", "xl:table-row"],
                ["table-row-group", "xl:table-row-group"],
              ]),
            ],
          ]),
        ],
        [
          "open",
          new Map<Breakpoints, Map<FlexDisplay, string>>([
            [
              "xs",
              new Map<FlexDisplay, string>([
                ["block", "xs:open:block"],
                ["contents", "xs:open:contents"],
                ["flex", "xs:open:flex"],
                ["flow-root", "xs:open:flow-root"],
                ["grid", "xs:open:grid"],
                ["hidden", "xs:open:hidden"],
                ["inline", "xs:open:inline"],
                ["inline-block", "xs:open:inline-block"],
                ["inline-flex", "xs:open:inline-flex"],
                ["inline-grid", "xs:open:inline-grid"],
                ["inline-table", "xs:open:inline-table"],
                ["list-item", "xs:open:list-item"],
                ["table", "xs:open:table"],
                ["table-caption", "xs:open:table-caption"],
                ["table-cell", "xs:open:table-cell"],
                ["table-column", "xs:open:table-column"],
                ["table-column-group", "xs:open:table-column-group"],
                ["table-footer-group", "xs:open:table-footer-group"],
                ["table-header-group", "xs:open:table-header-group"],
                ["table-row", "xs:open:table-row"],
                ["table-row-group", "xs:open:table-row-group"],
              ]),
            ],
            [
              "sm",
              new Map<FlexDisplay, string>([
                ["block", "sm:open:block"],
                ["contents", "sm:open:contents"],
                ["flex", "sm:open:flex"],
                ["flow-root", "sm:open:flow-root"],
                ["grid", "sm:open:grid"],
                ["hidden", "sm:open:hidden"],
                ["inline", "sm:open:inline"],
                ["inline-block", "sm:open:inline-block"],
                ["inline-flex", "sm:open:inline-flex"],
                ["inline-grid", "sm:open:inline-grid"],
                ["inline-table", "sm:open:inline-table"],
                ["list-item", "sm:open:list-item"],
                ["table", "sm:open:table"],
                ["table-caption", "sm:open:table-caption"],
                ["table-cell", "sm:open:table-cell"],
                ["table-column", "sm:open:table-column"],
                ["table-column-group", "sm:open:table-column-group"],
                ["table-footer-group", "sm:open:table-footer-group"],
                ["table-header-group", "sm:open:table-header-group"],
                ["table-row", "sm:open:table-row"],
                ["table-row-group", "sm:open:table-row-group"],
              ]),
            ],
            [
              "md",
              new Map<FlexDisplay, string>([
                ["block", "md:open:block"],
                ["contents", "md:open:contents"],
                ["flex", "md:open:flex"],
                ["flow-root", "md:open:flow-root"],
                ["grid", "md:open:grid"],
                ["hidden", "md:open:hidden"],
                ["inline", "md:open:inline"],
                ["inline-block", "md:open:inline-block"],
                ["inline-flex", "md:open:inline-flex"],
                ["inline-grid", "md:open:inline-grid"],
                ["inline-table", "md:open:inline-table"],
                ["list-item", "md:open:list-item"],
                ["table", "md:open:table"],
                ["table-caption", "md:open:table-caption"],
                ["table-cell", "md:open:table-cell"],
                ["table-column", "md:open:table-column"],
                ["table-column-group", "md:open:table-column-group"],
                ["table-footer-group", "md:open:table-footer-group"],
                ["table-header-group", "md:open:table-header-group"],
                ["table-row", "md:open:table-row"],
                ["table-row-group", "md:open:table-row-group"],
              ]),
            ],
            [
              "lg",
              new Map<FlexDisplay, string>([
                ["block", "lg:open:block"],
                ["contents", "lg:open:contents"],
                ["flex", "lg:open:flex"],
                ["flow-root", "lg:open:flow-root"],
                ["grid", "lg:open:grid"],
                ["hidden", "lg:open:hidden"],
                ["inline", "lg:open:inline"],
                ["inline-block", "lg:open:inline-block"],
                ["inline-flex", "lg:open:inline-flex"],
                ["inline-grid", "lg:open:inline-grid"],
                ["inline-table", "lg:open:inline-table"],
                ["list-item", "lg:open:list-item"],
                ["table", "lg:open:table"],
                ["table-caption", "lg:open:table-caption"],
                ["table-cell", "lg:open:table-cell"],
                ["table-column", "lg:open:table-column"],
                ["table-column-group", "lg:open:table-column-group"],
                ["table-footer-group", "lg:open:table-footer-group"],
                ["table-header-group", "lg:open:table-header-group"],
                ["table-row", "lg:open:table-row"],
                ["table-row-group", "lg:open:table-row-group"],
              ]),
            ],
            [
              "xl",
              new Map<FlexDisplay, string>([
                ["block", "xl:open:block"],
                ["contents", "xl:open:contents"],
                ["flex", "xl:open:flex"],
                ["flow-root", "xl:open:flow-root"],
                ["grid", "xl:open:grid"],
                ["hidden", "xl:open:hidden"],
                ["inline", "xl:open:inline"],
                ["inline-block", "xl:open:inline-block"],
                ["inline-flex", "xl:open:inline-flex"],
                ["inline-grid", "xl:open:inline-grid"],
                ["inline-table", "xl:open:inline-table"],
                ["list-item", "xl:open:list-item"],
                ["table", "xl:open:table"],
                ["table-caption", "xl:open:table-caption"],
                ["table-cell", "xl:open:table-cell"],
                ["table-column", "xl:open:table-column"],
                ["table-column-group", "xl:open:table-column-group"],
                ["table-footer-group", "xl:open:table-footer-group"],
                ["table-header-group", "xl:open:table-header-group"],
                ["table-row", "xl:open:table-row"],
                ["table-row-group", "xl:open:table-row-group"],
              ]),
            ],
          ]),
        ],
      ]).get(selector) ?? this.defaultValue.getValue()
    );
  }
}
